### ISSUE TITLE
Centering text

### ISSUE THREAD

**Issue by btt423** [Hopding/pdf-lib#10]
I am trying to setup a process to essentially stamp values at certain spots on an existing PDF file (a completion certificate for a user of our software).  Pretty easy to get going and I have a basic working sample.  What I have not been able to figure out is how to center text on the page (or right align) when the text is a variable length.

What is the best approach to handle this?

Thanks!

**Comment by Hopding** [comment]
This is possible to do with _embedded fonts_, but not (currently) when using one of the standard fonts. There is not currently a nice API in `pdf-lib` for centering or measuring text, but this is something I plan to add in the future. That being said, here's how to do it:

## 1. Embed a font in your document:
```javascript
const pdfBytes  = // ...some Uint8Array for a PDF...
const fontBytes = // ...some Uint8Array for a font...
const pdfDoc    = PDFDocumentFactory.load(pdfBytes);

// We need the first element of the tuple to reference this font in a
// content stream. We'll use the second element to measure text.
const [fontRef, fontObj] = pdfDoc.embedFont(fontBytes);
```

## 2. Implement a function to measure a string of text in the embedded font:
I'm just going to hand wave the details of this, such as what `advanceWidth` is and where the number `1000` comes from. Eventually `pdf-lib` should make these available to you after you embed a font, rather than requiring you to implement them yourself.
```javascript
const getCodePointWidth = (codePoint) =>
  fontObj.font.glyphForCodePoint(codePoint).advanceWidth;

/* Returns the width of a string in the embedded font with a given font size. */
const getStringWidth = (string, fontSize) =>
  string
    .split('')
    .map((c) => c.charCodeAt(0))
    .map((c) => getCodePointWidth(c) * (fontSize / 1000))
    .reduce((total, width) => total + width, 0);
```

## 3. Get a reference to the page of the document you wish to modify:
Since this is an existing page and we haven't chosen its width and height, we'll need to pull those values out. The `PDFPage` class doesn't currently expose nice methods for this, but it can still be done:
```javascript
const pages = pdfDoc.getPages();
const page1 = pages[0];

const PAGE_WIDTH = page1.get('MediaBox').array[2];
const PAGE_HEIGHT = page1.get('MediaBox').array[3];
const EMBEDDED_FONT = 'EmbeddedFont';
```

## 4. Create a new content stream and use the `drawText` operator to draw text in the embedded font on the page:
```javascript
const contentStream = pdfDoc.createContentStream(
  drawText('Right Aligned', {
    font: EMBEDDED_FONT,
    size: 48,
    x: PAGE_WIDTH - getStringWidth('Right Aligned', 48),
    y: PAGE_HEIGHT - 48,
    colorRgb: [1, 0, 0],
  }),
  drawText('Centered', {
    font: EMBEDDED_FONT,
    size: 48,
    x: (PAGE_WIDTH - getStringWidth('Centered', 48)) / 2,
    y: PAGE_HEIGHT - (48 * 3),
    colorRgb: [1, 0, 0],
  }),
);

page1
  .addFontDictionary(EMBEDDED_FONT, fontRef)
  .addContentStreams(pdfDoc.register(contentStream));
```

**Comment by btt423** [comment]
Andrew - thanks so much!  That worked perfectly.  I really appreciate you building this library, it fills a huge need.

**Comment by btt423** [comment]
Andrew - I just got back to the point of finishing out the implementation of generating a PDF.  When I use the Ubuntu font that you used in the example here, the centering works like a champ.  I tried a couple other fonts and the centering is off - the 2 other fonts I chose calculated the x position a good bit to far to the left of the document.  Is there something special about the Ubuntu font?  Maybe only certain fonts can be embedded when trying to calculate the width of a string?

**Comment by btt423** [comment]
One thing I just figured out is that the PDFFontFactory that comes back from embedFont has a getCodePointWidth function that is slightly different than the one in the example here.  I used that function and the centering started working.  Makes sense after seeing the code of that function.  I did notice that using .ttf fonts seems to be way more reliable than trying to use a woff2 font.

Thanks again!

**Comment by Hopding** [comment]
Glad you were able to get this working! I've also found `.otf` and `.ttf` to be the most reliable font formats.

This is good info to have. I'd appreciate if you can share the code you used for creating your document, as well as the fonts that did/didn't work (if possible). As I mentioned, I'd like to return a simple function that can be used to measure a string's width after embedding a font. But I'd also like that function to work regardless of the particular font. So any additional info you can provide will be useful to test against when I get around to implementing this feature.

**Comment by Hopding** [comment]
Version [`0.6.0`](https://www.npmjs.com/package/pdf-lib/v/0.6.0) is now published. It adds new methods to measure the width and height of text in standard and embedded fonts ([example](https://github.com/Hopding/pdf-lib/blob/master/examples/measuring_text/node/index.js)). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.6.0).

You can install this new version with npm:
```
npm install pdf-lib@0.6.0
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.0/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.0/dist/pdf-lib.min.js

**Comment by MarcelloTheArcane** [comment]
@Hopding The example link [here](https://github.com/Hopding/pdf-lib/blob/master/examples/measuring_text/node/index.js) is broken now. Is there an example for getting aligned text?

**Comment by Hopding** [comment]
Hello @MarcelloTheArcane!

Here's an updated example that centers a piece of text vertically and horizontally:

```js
const pdfDoc = await PDFDocument.create();

const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

const page = pdfDoc.addPage();

const text = 'This text is centered.';
const textSize = 24;
const textWidth = helveticaFont.widthOfTextAtSize(text, textSize);
const textHeight = helveticaFont.heightAtSize(textSize);

page.drawText(text, {
  x: page.getWidth() / 2 - textWidth / 2,
  y: page.getHeight() / 2 - textHeight / 2,
  size: textSize,
  font: helveticaFont,
});

const pdfBytes = await pdfDoc.save();
```

And here's the result:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/75628328-80602880-5b9d-11ea-8285-1a78300fee7c.png" height="500">
</kbd>

**Comment by gregorymayo** [comment]
@Hopding Is there a way to make the text is still in the center while having a -45 rotation degree?

**Comment by gregorymayo** [comment]
@Hopding Hi Andrew, I am having a little bit problem here, Is there a straight forward way to make the text is still in the center while having a 45-degree rotation?

**Comment by khanhubgit** [comment]
@Hopding Thanks for the great work.

**Comment by thaker0503** [comment]
@gregorymayo Did you find a way to still keep the text in center with rotation?

**Comment by arodriguezl9302** [comment]
> ```js
> x: page.getWidth() / 2 - textWidth / 2,
>   y: page.getHeight() / 2 - textHeight / 2,
> ```

esto me ha funcionado super bien, gracias bro!

**Comment by Hellomik2002** [comment]
```
import { PDFFont } from 'pdf-lib';

export interface LayoutText {
  toDraw: {
    text: string;
    x: number;
    y: number;
  }[];
  height: number;
  lineHeight: number;
}

export function layoutText({
  text,
  maxWidth,
  font,
  fontSize,
  alignment,
}: {
  text: string;
  maxWidth: number;
  font: PDFFont;
  fontSize: number;
  alignment: 'left' | 'center' | 'right';
}): LayoutText {
  const words = text.split(' ');
  const lines = [];
  let currentLine = '';

  // Собираем слова в строки, пока их ширина не превысит maxWidth
  for (const word of words) {
    const testLine = currentLine ? currentLine + ' ' + word : word;
    if (font.widthOfTextAtSize(testLine, fontSize) <= maxWidth) {
      currentLine = testLine;
    } else {
      // Если добавление слова выходит за пределы, сохраняем текущую строку и начинаем новую
      if (currentLine) {
        lines.push(currentLine);
      }
      currentLine = word;
    }
  }
  if (currentLine) {
    lines.push(currentLine);
  }

  // Определяем высоту строки (можно добавить интервал, если нужно)
  const lineHeight = font.heightAtSize(fontSize);

  // Для каждой строки вычисляем x-координату в зависимости от выравнивания
  const toDraw = lines.map((line, index) => {
    const textWidth = font.widthOfTextAtSize(line, fontSize);
    let x = 0;
    if (alignment === 'center') {
      x = (maxWidth - textWidth) / 2;
    } else if (alignment === 'right') {
      x = maxWidth - textWidth;
    }
    // y можно рассчитывать как отступ для каждой строки (например, index * lineHeight)
    const y = index * lineHeight;
    return { text: line, x, y };
  });
  return {
    toDraw,
    height: lineHeight * (toDraw.length - 1),
    lineHeight: lineHeight,
  };
}
```

```
import { PDFFont, PDFPage } from 'pdf-lib';
import { LayoutText } from './layout_text';

export const paintLayoutText = async (__: {
  page: PDFPage;
  data: LayoutText;
  y: number;
  x: number;
  font: PDFFont;
  textSize: number
}) => {
  const { data, page, x: globalX, y: globalY, font, textSize } = __;
  const { height, width } = page.getSize();
  data.toDraw.forEach((val) => {
    page.drawText(val.text, {
      x: globalX + val.x,
      y: height - val.y - data.lineHeight / 1.5 - globalY,
      size: textSize,
      font: font,
    });
  });
};
```

Example how to use 
```
 const toDraw = layoutText({
    text: txt,
    alignment: 'center',
    font: playFairFont,
    fontSize: 32,
    maxWidth: 250,
  });

  paintLayoutText({
    data: toDraw,
    font: playFairFont,
    page: testPage,
    x: 10,
    y: 0,
    textSize: 32,
  });
```
