### ISSUE TITLE
form.getFields() should handle widget field without an appearance.

### ISSUE THREAD

**Issue by albaraks** [Hopding/pdf-lib#1005]
### What were you trying to do?

I have a pdf with a widget without an appearance set. When calling form.getFields() which gets the following exception:

Error: Expected instance of PDFName, but got instance of undefined.

I'm attaching the sample file I'm using. 
[f1040 filled (4).pdf](https://github.com/Hopding/pdf-lib/files/7230259/f1040.filled.4.pdf)

### Why were you trying to do this?

I need to enumerate all fields.

### How did you attempt to do it?

Just called the api getfields();

### What actually happened?

I get an exception: Error: Expected instance of PDFName, but got instance of undefined

File: PDFContext..js Function PDFContext.prototype.lookup throws the exception

  throw new UnexpectedObjectTypeError(types, result); 

### What did you expect to happen?

Get the list of fields including the widget without the appearance.

### How can we reproduce the issue?

Load the attached file into the library
Get form and call form.getFields();
[f1040 filled (4).pdf](https://github.com/Hopding/pdf-lib/files/7230263/f1040.filled.4.pdf)

### Version

https://cdn.jsdelivr.net/npm/pdf-lib/dist/pdf-lib.js

### What environment are you running pdf-lib in?

Browser

### Required Reading

- [X] I have read [www.sscce.org](http://www.sscce.org/).
- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have read [Smart Questions](http://catb.org/~esr/faqs/smart-questions.html).
- [X] I have read [45 GitHub Issues Dos and Don'ts](https://davidwalsh.name/45-github-issues-dos-donts).

**Comment by Hopding** [comment]
<kbd>
<img src="https://user-images.githubusercontent.com/10351828/134821298-26c03403-89ad-428e-9083-eee333f875a9.png">
</kbd>

> 

* This report does not include complete, executable code.
* Despite this, I tried to reproduce it anyways and was unable to.
* Here is an example of a proper, reproducible bug report: https://github.com/Hopding/pdf-lib/issues/1001

**Comment by codati** [comment]
hello
I have exactly the same problem
I made a small zip with enough to reproduce the problem
[pdf-bug.zip](https://github.com/user-attachments/files/15742105/pdf-bug.zip)

I created a new issue https://github.com/Hopding/pdf-lib/issues/1635
