### ISSUE TITLE
On Save using pdfDoc.save() all the Checkbox CROSS (X) style changes to Tick (✔)

### ISSUE THREAD

**Issue by vbgsmanzoor** [Hopding/pdf-lib#1016]
### What were you trying to do?

Whenever I save a document its appearance changes to  TICK from CROSS

Below are the original checkboxes
![original_pdf_checks](https://user-images.githubusercontent.com/75968426/135802975-6ad03ff4-beb0-43ff-96f2-58c678667b1b.png)

Below are after uncheck (showing Tick not Cross)
![after_pdf_checks](https://user-images.githubusercontent.com/75968426/135802984-48e9d603-1dc8-47d8-bb8f-eb70ebd7f09a.png)

### Why were you trying to do this?

I have to fill documents based on the input on the web page

### How did you attempt to do it?

await pdfDoc.save()

### What actually happened?

Below are the original checkboxes
![original_pdf_checks](https://user-images.githubusercontent.com/75968426/135802975-6ad03ff4-beb0-43ff-96f2-58c678667b1b.png)

Below are after uncheck (showing Tick not Cross)
![after_pdf_checks](https://user-images.githubusercontent.com/75968426/135802984-48e9d603-1dc8-47d8-bb8f-eb70ebd7f09a.png)

### What did you expect to happen?

If I save the document and any person checks that checkbox on the pdf manually it should maintain its style as CROSS not change to Tick

### How can we reproduce the issue?

reading some checkboxes from pdf and unchecking them and saving the document then check those boxes manually an see there style has been changed

### Version

"pdf-lib": "1.16.0"

### What environment are you running pdf-lib in?

Node

### Required Reading

- [X] I have read [www.sscce.org](http://www.sscce.org/).
- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have read [Smart Questions](http://catb.org/~esr/faqs/smart-questions.html).
- [X] I have read [45 GitHub Issues Dos and Don'ts](https://davidwalsh.name/45-github-issues-dos-donts).

**Comment by dcsline** [comment]
You write "I have to fill documents based on the input on the web page", so i am asked me, why do you not work with an pdf template file, so do you work directly with the input data.

**Comment by vbgsmanzoor** [comment]
> You write "I have to fill documents based on the input on the web page", so i am asked me, why do you not work with an pdf template file, so do you work directly with the input data.

**Comment by sirvanux** [comment]
I have the same problem. Did you solve it?? I suspect it has to do with the font type being "Adobe Pi" on the document and that not being a standard font on pdflib

**Comment by vbgsmanzoor** [comment]
> I have the same problem. Did you solve it?? I suspect it has to do with the font type being "Adobe Pi" on the document and that not being a standard font on pdflib

The solution I came up with is, that whenever set text, update appearance with the font as well and on saving the document pass save options as pdfDoc.save({updateFieldAppearances: false})
e.g
field.setText("abc")
field.updateAppearances(font)

field2.setText("xyz")
field2.updateAppearances(font)

and save with passing options

pdfDoc.save({updateFieldAppearances: false})

**Comment by vbgsmanzoor** [comment]
where font is ...

let font = await pdfDoc.embedFont(StandardFonts.Courier)

**Comment by freddy-pieters** [comment]
I do not think this is a bug. Read my explanation of the problem (and a possible solution) here: [https://github.com/Hopding/pdf-lib/issues/982](url)
What I did not mention there, but what reinforces my assessment that it is pure Acrobat behavior is the fact that the crosses I made in the appearances with pdf-lib were correctly shown in Foxit.
