### ISSUE TITLE
html symbol?

### ISSUE THREAD

**Issue by monski** [Hopding/pdf-lib#102]
Hi is it possible to draw an html symbol? like a check mark? thanks

**Comment by Hopding** [comment]
Hello @monski!

`pdf-lib` can draw arbitary unicode symbols. You just need to be sure to use a font that supports the symbols you wish to draw. The ZapfDingbats standard font supports checkmarks, so you can draw them without having to embed any fonts.

Here's an example:
```js
import { 
  PDFDocument,
  PDFDocumentFactory,
  PDFDocumentWriter,
  StandardFonts,
  drawText,
} from 'pdf-lib';

const pdfDoc = PDFDocumentFactory.create();

const [zapfDingbatsRef, zapfDingbatsFont] = pdfDoc.embedStandardFont(
  StandardFonts.ZapfDingbats,
);

const contentStream = pdfDoc.register(
  pdfDoc.createContentStream(
    drawText(zapfDingbatsFont.encodeText('✓'), {
      font: 'ZapfDingbats',
      x: 230,
      y: 230,
      size: 50,
    }),
  ),
);

const page = pdfDoc
  .createPage([500, 500])
  .addFontDictionary('ZapfDingbats', zapfDingbatsRef)
  .addContentStreams(contentStream);

pdfDoc.addPage(page);

const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
```

And here is the resulting PDF file: [1557017226163.pdf](https://github.com/Hopding/pdf-lib/files/3145002/1557017226163.pdf)

I hope this helps. Let let me know if you have any further questions!

**Comment by monski** [comment]
alright thanks alot
