### ISSUE TITLE
Unexpected warning when processing a very small file

### ISSUE THREAD

**Issue by alexshenker** [Hopding/pdf-lib#1029]
### What were you trying to do?

in **React**, using a form input field of type 'file', I created an Uint8Array, which I passed to PDFDocument.load in order to 
create a new PDFDocument instance.
I used multiple different PDFs, some of which are as large as 246MB. These files were processed without issue.
I have one particular PDF that is small - 395KB, that is processed correctly but results in the following error:

> "Parsed number that is too large for some PDF readers: 340282346638528859811704183484516925440, not capping." BaseParser.ts:71

### Why were you trying to do this?

To be able to modify the PDF using pdf-lib

### How did you attempt to do it?

After dragging the attached PDF to my file input:

```
const file = e.target.files[0];

file.arrayBuffer().then(async (arrayBuffer) => {
            const pdfDocument = await PDFDocument.load(
                new Uint8Array(arrayBuffer)
            );
}
```

### What actually happened?

The file was processed correctly but resulted in a warning: 
> "Parsed number that is too large for some PDF readers: 340282346638528859811704183484516925440, not capping." BaseParser.ts:71

### What did you expect to happen?

To process the PDF without warnings, or to understand the cause of the warning.

### How can we reproduce the issue?

in **React**, create the following component, download and drag the attached sample PDF to its' file input field.

```
const pdfComponent = () => {

const onChange = (e) => {
const file = e.target.files[0];
file.arrayBuffer().then(async (arrayBuffer) => {
            const pdfDocument = await PDFDocument.load(
                new Uint8Array(arrayBuffer)
            );
   }
}

  return (
     <form>
         <input type='file' onChange={onChange} />
     </form>
  )

}
```
[sample.pdf](https://github.com/Hopding/pdf-lib/files/7340855/sample.pdf)

### Version

1.16.0

### What environment are you running pdf-lib in?

Other

### Required Reading

- [X] I have read [www.sscce.org](http://www.sscce.org/).
- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have read [Smart Questions](http://catb.org/~esr/faqs/smart-questions.html).
- [X] I have read [45 GitHub Issues Dos and Don'ts](https://davidwalsh.name/45-github-issues-dos-donts).

**Comment by Hopding** [comment]
@alexshenker The example you shared is not self contained or compilable: http://www.sscce.org. 

Regardless, this warning is correct. It doesn't necessarily mean there's a problem, just that the PDF file your working with has a value that some readers might not tolerate well. You're free to ignore the error, but it is not a bug.
