### ISSUE TITLE
Converting multiple byte string's to single PDF

### ISSUE THREAD

**Issue by tomhands1** [Hopding/pdf-lib#1040]
### What were you trying to do?

I am attempting to use this library in conjunction with Cloudmersive `convertImageMultipageImageFormatConvert` as detailed here, the returned object from their API is https://api.cloudmersive.com/docs/convert.asp#tag-ConvertImage includes a Pages array with each page having a FileBytes attached.

```
  "Pages": [
    {
      "Filename": "string",
      "FileBytes": "string (byte)"
    }
  ]
```

I am mapping through these pages and returning an array of just the FileBytes strings before attempting to create a PDF and add a page for each of these pages.
![Screenshot 2021-10-18 at 16 35 58](https://user-images.githubusercontent.com/47323259/137763481-94dbb27d-dc2e-436e-aa03-8d615bb76b66.png)

Unfortunately I am getting an error at this point of `Failed to parse PDF document (line:578 col:1400 offset=55003): No PDF header found` and I am not sure if it is a problem with my approach to using this library or if argument I am passing to the `PDFDocument.load()` is the wrong type.

Any help would be greatly appreciated
 

### Why were you trying to do this?

I am hoping to convert a multi page .tiff file to a PDF

### How did you attempt to do it?

Detailed above. By passing an array of byte strings to my own method which creates a new PDF and attempts to load these pages and add them to the new document.

### What actually happened?

I am getting an error on the very first call of `PDFDocument.load()`

### What did you expect to happen?

An output buffer of the pages combined into a single PDF file

### How can we reproduce the issue?

You would first be required to have a cloudmersive account so that you could provide the initial tiff file to cloudmersive and return the string bytes for individual pages. Following this it would be a case of passing these strings (which I assume, although documentation is vague, are base64 encoded strings of the pages) individually to the static load method and noting the No PDF header found error

### Version

1.17.0

### What environment are you running pdf-lib in?

Node

### Required Reading

- [X] I have read [www.sscce.org](http://www.sscce.org/).
- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have read [Smart Questions](http://catb.org/~esr/faqs/smart-questions.html).
- [X] I have read [45 GitHub Issues Dos and Don'ts](https://davidwalsh.name/45-github-issues-dos-donts).

**Comment by Hopding** [comment]
1. This report doesn't include a SSCCE, so I'm unable to reproduce the issue myself.
2. From your description, it sounds like you're trying to pass TIFF files to `PDFDocument.load`. This method does not accept TIFF files, hence the error you're getting. It only accepts PDF files (though the data itself can be provided in a couple different formats). [See the API docs](https://pdf-lib.js.org/docs/api/classes/pdfdocument#static-load).

I hope this helps.

**Comment by Hopding** [comment]
Note also that pdf-lib does provide methods for embedding JPG and PNG files, but not TIFF files. That would be a nice feature to have though.

**Comment by Hopding** [comment]
If my understanding about what you're trying to do is incorrect, please provide a SSCCE (e.g. using the output of one of your Cloudmersive API calls) and I can take another look.
