### ISSUE TITLE
[Unhandled promise rejection: Error: Failed to parse PDF document (line:0 col:104 offset=52): No PDF header found]

### ISSUE THREAD

**Issue by ccraig09** [Hopding/pdf-lib#1056]
### What were you trying to do?

I want to load the pdf file and edit it

### Why were you trying to do this?

to be able to edit a pdf document loaded from internet

### How did you attempt to do it?

code used to load using react native expo

downloading the doc:

```
const chooseDoc = async () => {
    FileSystem.downloadAsync(
      "https://pdf-lib.js.org/assets/dod_character.pdf",
      FileSystem.documentDirectory + "test.pdf"
    )
      .then(({ uri }) => {
        console.log("Finished downloading to ", uri.toString());
        setPdfDoc(uri.toString());
      })
      .catch((error) => {
        console.error(error);
      });
  };
```

code to load pdf with pdf-lib

    let your_bytes = Buffer.from(pdfloaded, "base64");
    var bytes = new Uint8Array(your_bytes);

    console.log("loaded----", bytes);
    console.log("buffed----", your_bytes);

    const pdfDoc = await PDFDocument.load(your_bytes);

### What actually happened?

received error for [Unhandled promise rejection: Error: Failed to parse PDF document (line:0 col:104 offset=52): No PDF header found]

### What did you expect to happen?

i expected the pdf to load and be able to edit it

### How can we reproduce the issue?

using the code above and trying to load the pdf in react native expo

### Version

1.17.0

### What environment are you running pdf-lib in?

React Native, Other

### Required Reading

- [X] I have read [www.sscce.org](http://www.sscce.org/).
- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have read [Smart Questions](http://catb.org/~esr/faqs/smart-questions.html).
- [X] I have read [45 GitHub Issues Dos and Don'ts](https://davidwalsh.name/45-github-issues-dos-donts).

**Comment by Hopding** [comment]
Hello @ccraig09! 

This sounds like a problem with the code you're using to download the document, not pdf-lib itself. I can't provide any assistance with React Native or Expo specific APIs/code. If you'd like a working example of using pdf-lib in a React Native environment, check out the demo app in this repo, e.g. [`test3.js`](https://github.com/Hopding/pdf-lib/blob/master/apps/rn/src/tests/test3.js).

If the issue isn't specific to React Native or Expo, please provide a _complete_ SSCCE I can use to reproduce the issue without writing any code myself.
