### ISSUE TITLE
Add a button to post pdf form to Server and also close the pop up in which pdf is opened.

### ISSUE THREAD

**Issue by bhatrohit85** [Hopding/pdf-lib#1058]
### Describe your idea

I was wondering to see if we can post pdfdocuments as byte array , datauri or stream from a button added in the pdf form
after loading the pdf file from server into pdf-lib . I could not find any option to add submit action url to button.

### How could this be implemented?

We should have option to perform ajax action on button added inside the pdf form and then be able to perform client side
action after that.

### What problem are you trying to solve?

I am getting an editable pdf file from server action and then on client i am trying to load this.
after that , i would render this in either object / embed. Now user would edit that form and now i want to be able to 
either submit this form from an Html button and get the pdf edited in pop up or else add a pdfbutton inside the pdf form
and be able to perform submit on that and also close the pop up in which pdf is opened after success from server action.

### Why does this matter to you?

This is a very highlighted requirement that we need to achieve and thus want to decide basis the support that is available in your product. Can we please suggest at urgent basis if this is already present or can be achieved anyhow using your library.

### Would others find this helpful?

Yes

### Are you interested in implementing your proposal?

No

### Why are you submitting a proposal?

Yes , i want to know that its feasibility.

**Comment by Hopding** [comment]
It's not possible for pdf-lib to provide hooks into actions a user takes inside a PDF. See https://github.com/Hopding/pdf-lib/issues/965#issuecomment-925360182. If you user a PDF rendering library, you might be able to achieve something like this.
