### ISSUE TITLE
trigger printing command

### ISSUE THREAD

**Issue by monski** [Hopding/pdf-lib#106]
hi,

is it possible to trigger printing upon creation/modification of page? instead of downloading?

something like this...
 PDFDocumentWriter.openPrinterDialog(pdfDoc);

thanks

**Comment by Hopding** [comment]
Hello @monski! Sorry for the late response.

`pdf-lib` does not have any printing methods. I can see how this would be useful. However, `pdf-lib` is designed such that it does not contain any platform specific code. All `pdf-lib` code should work on any (modern) JavaScript platform. And printing dialogs are very much browser-specific. 

That being said, it should be _possible_ to do this sort of thing. This StackOverflow thread seems to have some [solutions](https://stackoverflow.com/a/16239785).

**Comment by monski** [comment]
no worries, thanks for the info...great job
