### ISSUE TITLE
Combining 2 or More PDF in For Loop Produces Blank PDF (JSFiddle Included)

### ISSUE THREAD

**Issue by kartiksolanki** [Hopding/pdf-lib#1060]
### What were you trying to do?

I am just trying to simply combine two PDF's from the URL's links in For Loop and the output is being produced as Blank PDF.
Here is the JS Fiddle Link: [https://jsfiddle.net/u4nhy6af/3/](https://jsfiddle.net/u4nhy6af/3/)

Here is my code:

```js
      const urlsArr = [
         'https://pdf-lib.js.org/assets/with_update_sections.pdf',
         'https://pdf-lib.js.org/assets/with_large_page_count.pdf'
      ];
     
     var pdfsBytesArr = [];
     urlsArr.forEach(async url => {
       const pdfBuffer = await fetch(url).then(res => res.arrayBuffer());
       pdfsBytesArr.push(pdfBuffer);
     });
     
     const mergedPdf = await PDFDocument.create(); 
      
      pdfsBytesArr.forEach(async (pdfByte) => {
      	const pdf = await PDFDocument.load(pdfByte);
        const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices()); 
        copiedPages.forEach((page) => {
          mergedPdf.addPage(page); 
        }); 
      });
      
      // Serialize the PDFDocument to bytes (a Uint8Array)
      const pdfBytesRes = await mergedPdf.save()
```

Any idea what am I doing wrong here? 

### Why were you trying to do this?

I want to combine 2 or more PDF's into a single document.

### How did you attempt to do it?

Using For Loop.

### What actually happened?

Blank PDF was produced.

### What did you expect to happen?

I was hoping to get 757 Pages of Single PDF with first URL PDF (Page Length 1) and second URL PDF (Page Length 756) combined.

### How can we reproduce the issue?

Here is the JS Fiddle Link:
[https://jsfiddle.net/u4nhy6af/3/](https://jsfiddle.net/u4nhy6af/3/)

### Version

1.17.0

### What environment are you running pdf-lib in?

Browser

### Required Reading

- [X] I have read [www.sscce.org](http://www.sscce.org/).
- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have read [Smart Questions](http://catb.org/~esr/faqs/smart-questions.html).
- [X] I have read [45 GitHub Issues Dos and Don'ts](https://davidwalsh.name/45-github-issues-dos-donts).

### Additional Notes

Any help would be greatly appreciated! Thanks.

**Comment by kartiksolanki** [comment]
@Hopding  Please help :)

**Comment by bhavyasaggi** [comment]
You probably are not using the async properly.
Try the following snippet.
Note: Always avoid async in loops. Either use Promise.all or chain your promises.

```
const urlsArr = [
    'https://pdf-lib.js.org/assets/with_update_sections.pdf',
    'https://pdf-lib.js.org/assets/with_large_page_count.pdf'
]

const mergedPdf = await PDFDocument.create()

await urlsArr.reduce((promiseChain, pdfUrl) => promiseChain.then(async () => {
    const pdfResponse = await fetch(pdfUrl)
    const pdfBytes = await pdfResponse.arrayBuffer()
    const pdf = await PDFDocument.load(pdfByte);
    const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
    copiedPages.forEach((page) => {
        mergedPdf.addPage(page)
    })
}), Promise.resolve())

const pdfBytesRes = await mergedPdf.save()
```

**Comment by Hopding** [comment]
@bhavyasaggi is spot on! You should never pass an async function to `.forEach`. The best way to handle resolving multiple promises is with `Promise.all`. If you really need to resolve them sequentially, you can use `.reduce` (as in @bhavyasaggi's example), or you can use an imperative loop:
```js
for (const foo of bar) {
  const qux = await baz(foo);
  // Do stuff with `qux`
}
// Do other stuff now that all your promises have resolved.
```
