### ISSUE TITLE
Add rounded border rectangle

### ISSUE THREAD

**Issue by Sharcoux** [Hopding/pdf-lib#1070]
### Describe your idea

drawRectangle doesn't provide any way to draw a rounded border

### How could this be implemented?

We could change the drawRectangle method to call drawSvgPath instead, and create a path that gives this rounded border effect.

### What problem are you trying to solve?

Impossible to draw a rounded border rectangle at the moment

### Why does this matter to you?

I need to draw them on my pdf

### Would others find this helpful?

Definitely

### Are you interested in implementing your proposal?

Yes

### Why are you submitting a proposal?

I need some info about the feasibility, if there is already something in progress about it and if there is a better approach than the one I provided.

**Comment by Hopding** [comment]
Hello @Sharcoux! 

I think this would be a nice enhancement to the `PDFPage.drawRectangle` and `PDFPage.drawSquare` methods. They currently use functions in [`operations.ts`](https://github.com/Hopding/pdf-lib/blob/49b8e5eed06f0a78b2ee78d21790130229ef0f68/src/api/operations.ts) that directly produce arrays of PDF graphics operators ([for example](https://github.com/Hopding/pdf-lib/blob/49b8e5eed06f0a78b2ee78d21790130229ef0f68/src/api/operations.ts#L178-L218)). I'd prefer to keep things this way and not use any SVG logic under the hood. 

Awhile back a PR was opened (https://github.com/Hopding/pdf-lib/pull/513) that did just this. If I recall correctly, it used [bezier curves](https://github.com/Hopding/pdf-lib/blob/49b8e5eed06f0a78b2ee78d21790130229ef0f68/src/api/operators.ts#L119-L134) to round the corners. This PR never quite made it through, but that was for unrelated reasons. The implementation approach itself was sound. I'd be happy to accept a new PR implementing this same approach.

**Comment by dcsline** [comment]
@Hopding Why not SVG? In Inkscape you can create a rect with rounded corner. Before you do save it you convert it to path, so with pdf-lib you can use drawSvgPath (with all his possibilities). Testes with sample from Issue 106
[ex2a.pdf](https://github.com/Hopding/pdf-lib/files/7537524/ex2a.pdf)

**Comment by Hopding** [comment]
@dcsline users are welcome to create rectangles with rounded corners (or whatever shapes they want) with pdf-lib's SVG drawing methods. But if we introduce a option to the existing `drawRectangle(...)` method, then we'll need to use the approach I described above.

**Comment by ghost** [comment]
Having to use SVG is not very good for dynamically generating rounded rectangles.

**Comment by Sharcoux** [comment]
We finally added the support for this to @cantoo/pdf-lib from version 2.1.0 and above. Enjoy.

**Comment by larsyr** [comment]
I made a solution that will not be suitable for everyone, but I will still explain it in the hopes it helps someone else!

You can create 4 circles in each corner and fill the space between these circles to make a rectangle with rounded corners.
This may be not the best solution, but it works with the current library without using SVG.
(I don't know if it is better than SVG)

Restrictions:
- You can not have a border
- You can not have opacity

I added a picture to visualize the concept:
![pdf-lib-RoundedCorners](https://github.com/Hopding/pdf-lib/assets/68858540/e6e3cf4c-c2ab-40b5-95a9-c4594ba57e5e)

**Comment by sameer-roofr** [comment]
> We finally added the support for this to @cantoo/pdf-lib from version 2.1.0 and above. Enjoy.

~~Do you have a documentation of this in the forked repo? I am reading the code and I see there's rx and ry options. It's not rounding the border of the drawRectangle()~~ Nevermind, the jsfile example on Cantoo's home page is not using the latest version of the library. After upgrade, it got fixed.
