### ISSUE TITLE
How to know the type of a PDFField

### ISSUE THREAD

**Issue by julienGrd** [Hopding/pdf-lib#1072]
### What were you trying to do?

try to iterate over the field of forms and identify the Signatures fields

### Why were you trying to do this?

to identify the signature fields and delete them

### How did you attempt to do it?

const form = this.pdfLib.getForm();
                    const fields = form.getFields();
                    fields.forEach(field => {
                        field.enableReadOnly();
                        const type = field.constructor.name;
                        const name = field.getName();
                        console.log(`${type}: ${name}`);
//expected in type something like 'Signature' so i can make a particular treatment, but have only this kinf of things (the signature have the same type than checkbox)
r: Text1
e: Check Box1
e: Check Box2
r: RadioGroup1
r: Dropdown1
e: Signature1
                    });

### What actually happened?

unable to identify the signature field

### What did you expect to happen?

have a property on the field object which indicate the type of the field

### How can we reproduce the issue?

no way to reproduce, its just a question (and evolution if needed and possible)

### Version

1.17.0

### What environment are you running pdf-lib in?

Browser

### Required Reading

- [X] I have read [www.sscce.org](http://www.sscce.org/).
- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have read [Smart Questions](http://catb.org/~esr/faqs/smart-questions.html).
- [X] I have read [45 GitHub Issues Dos and Don'ts](https://davidwalsh.name/45-github-issues-dos-donts).

**Comment by Hopding** [comment]
@julienGrd you'll need to use `instanceof` to check the type of field. See https://github.com/Hopding/pdf-lib/issues/736#issuecomment-757374967 and https://github.com/Hopding/pdf-lib/issues/933#issuecomment-925384244.

**Comment by mkhlz** [comment]
Radio fields and text fields return the same type `n` can we fix this? @Hopding

**Comment by Angel-del-dev** [comment]
I am having the exact same problem.

When using pdf-lib(Minified), using `instanceof` or `field.constructor.name` is not an option because it always returns `n`, `r` or `e`.

After browsing for a while, i couldn't find any solution so I came with my own.
It's not perfect and for sure can be improved however it might help others in the future. If the problem has been patched or there's a better way to do it, I'd apreciate @Hopding's word on it.

By using[ `form.getSignature`](https://pdf-lib.js.org/docs/api/classes/pdfform#getsignature), we could check if the current field is a PDFSignature instance.

Once that's done, its only a matter of basic error handling.

```js
const SIGNATURE_FIELDS = [];
form.getFields().forEach((field, _) => {
        try {
            form.getSignature(field.getName()); // If the field is not a PDFSignature instance, it won't keep executing and will jump to the catch clause
            SIGNATURE_FIELDS .push(field.getName()); // In my case I just need to know how many signatures the document has.
        } catch(e) {
            /*
               Do something with the other field types or ignore it if you just need to get the signatures
            */
        }
    });
    // Do something with SIGNATURE_FIELDS
```
