### ISSUE TITLE
Getting ReferenceError

### ISSUE THREAD

**Issue by Abdoul-Majid** [Hopding/pdf-lib#1086]
### What were you trying to do?

I were trying to custom the font and the color

### How did you attempt to do it?
```js
page.drawText("Hello world",{
    size: 20,
    font: timesRomanFont,
    color: rgb(0, 0.53, 0.71)
} );
```
### What actually happened?

I get error  : 
```
ReferenceError: timesRomanFont is not defined,
ReferenceError: rgb is not defined
```
### What did you expect to happen?

I expected change of the font and the color

### How can we reproduce the issue?
```js
let pdfDoc = await PDFLib.PDFDocument.create();
let page = pdfDoc.addPage([794, 1123]);
page.moveTo(0,1000);
page.drawText("Hello world",{
    size: 20,
    font: timesRomanFont,
    color: rgb(0, 0.53, 0.71)
} );
let pdfBytes = await pdfDoc.save();
```
### Version

1.4

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by Rihden** [comment]
Are you sure you imported StandardFonts from 'pdf-lib'?
`import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';`

And if you did.. did you embed it in the document before using it?
` const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman)`

Edit: added rgb to the import as dcsline pointed

**Comment by dcsline** [comment]
Extend the import statement for the rgb problem: import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

**Comment by Hopding** [comment]
@Rihden and @dcsline are correct, you need to import those variables. See the following examples:
* https://jsfiddle.net/Hopding/rxwsc8f5/13/
* https://jsfiddle.net/Hopding/rxwsc8f5/13/
