### ISSUE TITLE
PDF Form filling is not working in ReactNative Android release APK.

### ISSUE THREAD

**Issue by phanisai4u** [Hopding/pdf-lib#1089]
### What were you trying to do?

I tried to fill the pdf form using pdf-lib it working 💯 present perfectly in debug mode in the device also. but when i generated a new release apk it is stopped working. not information is filled in pdf.

### How did you attempt to do it?

 ```
let data = await RNFS.readFileAssets("template.pdf", 'base64')
    if (data) {
      try {
        // Load a PDF with form fields
        const pdfDoc = await PDFDocument.load(data);
        const form = pdfDoc.getForm()
        //Get form fileds given PDF
        const fields = form.getFields()
        //Process each form field
        for (let field of fields) {
          const type = _.get(field, "constructor.name", "")
          const name = field.getName()
          switch (type) {
            case "PDFTextField": {
              (field as PDFTextField).setText("Hello"); //clear text filed
              break;
            }
            default: {
              console.log(`Un Handled  ${type} name of ${name}`)
            }
          }
        }
        form.flatten() // flatten pdf file

       const pdfBytes = pdfDoc.saveAsBase64() // save flatten file in bytes


        let rn = new Date().getUTCMilliseconds()
        var filePath = `${RNFS.DocumentDirectoryPath}${"/Attachments/TemplateFilled"}${rn}${".pdf"}`

        if (!(await RNFS.exists(RNFS.DocumentDirectoryPath + "/Attachments/"))) {
          await RNFS.mkdir(RNFS.DocumentDirectoryPath + "/Attachments/");
        }
        if (await RNFS.exists(filePath)) {
          await RNFS.unlink(filePath)
        }
        await RNFS.writeFile(filePath, pdfBytes, 'base64') // write into pdf file
        console.log('File saved success', filePath);
        setData(filePath)
        return Promise.resolve(filePath)
      } catch (error) {
        console.log("error", JSON.stringify(error, null, 1))
        return Promise.reject("Unable to process file")
      }
    } else {
      console.log('File Not Found')
      return Promise.reject("Unable to process file")
    }

```
### What actually happened?

In a release APK pdf form filling is not working.

if hard codes filed like bellow it is working in release build also 
```
         form.getTextField("DatePage1").setText("Hello")
         form.getTextField("DatePage2").setText("Hello")
         form.getTextField("DatePage3").setText("Hello")
         form.getTextField("DatePage4").setText("Hello")
         form.getTextField("DatePage5").setText("Hello")
```

if I change code to loop (for or while ) it is not working
 ```
      let i: number = 0;
        while (i < fields.length) {

          const type = _.get(fields[i], "type", "")
          const name = _.get(fields[i], "name", "")
          if (type == "PDFTextField") {
            form.getTextField("CitationDatePage1").setText("Hello--loop")
          }
            i++;
        }
```

### What did you expect to happen?

it is supposed to fill the pdf form field with a given test in the release build also with loop.

### How can we reproduce the issue?

Please generate  relase apk from react-native environment (./gradlew assembleRelease)

### Version

1.17.1

### What environment are you running pdf-lib in?

React Native

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by phanisai4u** [comment]
the issue  the root cause is found.
` const type = _.get(field, "constructor.name", "")
`

it is returning "PDFTextfiled" in debug but in release mode, it becomes some random char like "T". So I'm closing the issue.

Thanks for the great framework :)

**Comment by Hopding** [comment]
See also https://github.com/Hopding/pdf-lib/issues/736#issuecomment-757374967.

**Comment by vipulparmarmt** [comment]
Hello @phanisai4u when this pdf open in mobile and if there is form available and user edit the form inside that pdf then how can you caputure the user input from that pdf file
