### ISSUE TITLE
Which page is the form field on

### ISSUE THREAD

**Issue by littlefatcat163** [Hopding/pdf-lib#1090]
### What were you trying to do?

```js
const form = pdfDoc.getForm();
const fields = form.getFields();
fields.forEach(field => {
  const name = field.getName();
  const textField = form.getTextField(name);
  const widgets = textField.acroField.getWidgets();
  widgets.forEach((w) => { console.log(w.getRectangle()) });
 // here can get x, y, width, height
 // and how to get which page the field is on
})
```

### How did you attempt to do it?

get a pdf document form field info

### What actually happened?

how do i know which page the field is on

### What did you expect to happen?

which page the field is on

### How can we reproduce the issue?

```js
const form = pdfDoc.getForm();
const fields = form.getFields();
fields.forEach(field => {
  const name = field.getName();
  const textField = form.getTextField(name);
  const widgets = textField.acroField.getWidgets();
  widgets.forEach((w) => { console.log(w.getRectangle()) });
 // here can get x, y, width, height
 // and how to get which page the field is on
})
```

### Version

v1.17.1

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by dcsline** [comment]
in the issue lists could you find different inspirations!
Try this:
//######################################################################################
const {PDFDocument, PDFName,PDFArray, PDFDict,PDFRawStream} = require('pdf-lib');
const fs = require('fs');
const getAcroFieldRefs = (pdfDoc) => {
  //if (!pdfDoc.catalog.getMaybe('AcroForm')) return [];
  if (!pdfDoc.catalog.get(PDFName.of('AcroForm'))) return [];
  //const acroForm = pdfDoc.index.lookup(pdfDoc.catalog.get('AcroForm'));
  const acroForm = pdfDoc.catalog.lookupMaybe(PDFName.of('AcroForm'), PDFDict);
 // if (!acroForm.getMaybe('Fields')) return [];
  //const acroFields = pdfDoc.index.lookup(acroForm.get('Fields'));
  //const acroFields = acroForm.lookupMaybe(PDFName.of('Fields'));
  const acroFields = acroForm.lookupMaybe(PDFName.of('Fields'), PDFArray);
  return acroFields.array;
  /*const fieldRefs = acroForm.lookupMaybe(PDFName.of('Fields'), PDFArray);
  if (!fieldRefs) return [];

  const fields = new Array(fieldRefs.size());
  for (let idx = 0, len = fieldRefs.size(); idx < len; idx++) {
    fields[idx] = fieldRefs.lookup(idx);
  }
  return fields; */
};

function findPage(Annots,fref) {
  var index=-1;
  for (var i = 0; i < Annots.length + 1; i++) {
    if (Annots[i].includes(fref)) {
        index = i;
        break;
    } 
}
if(index>-1) index++;
return index
}

async function runTest() {  
  var templ= 'test.pdf'; 
  const pdfDoc = await PDFDocument.load(fs.readFileSync(templ)); 

  const pages = pdfDoc.getPages();
  const form = pdfDoc.getForm();
  const fields = form.getFields();
  const fieldRefs = getAcroFieldRefs(pdfDoc);
// const fields = doc.getForm().getFields()

 const page1AnnotsRaw = pages[0].node.lookupMaybe(PDFName.of('Annots'), PDFArray);
 const page1Annots = page1AnnotsRaw ? page1AnnotsRaw.asArray() : [];
 const page2AnnotsRaw = pages[1].node.lookupMaybe(PDFName.of('Annots'), PDFArray)
 const page2Annots = page2AnnotsRaw ? page2AnnotsRaw.asArray() : [];
 
 const AnnotsRaw = [];
 const Annots = [];
 let idefix=0;
 pages.forEach((page) => {
  AnnotsRaw[idefix] = pages[idefix].node.lookupMaybe(PDFName.of('Annots'), PDFArray);
  Annots[idefix] = AnnotsRaw[idefix] ? AnnotsRaw[idefix].asArray() : [];
  idefix++; 
 })



  fields.forEach(field => {

    const type = field.constructor.name
    const name = field.getName();
   // const textField = form.getTextField(name);
   // const widgets = textField.acroField.getWidgets();
   // widgets.forEach((w) => { 
    //if(Annots[1].includes(field.ref)) console.log("Field:::"+ name + "<<<"  + Annots[1].includes(field.ref) + ">>>PAGE:::" + findPage(Annots,field.ref));
    console.log("Field:::"+ name +  ">>>PAGE:::" + findPage(Annots,field.ref));
  
    // });  
   // here can get x, y, width, height
   // and how to get which page the field is on
  }) 
    
}

runTest();
//######################################################################################

**Comment by adoriandoran** [comment]
Today I ran exactly into the same obstacle. After having a look over pdf-lib's source code, I discovered a way to retrieve the parent page of each widget.

This should do the trick:

```javascript
const form = pdfDoc.getForm();
const fields = form.getFields();
fields.forEach(field => {
  const name = field.getName();
  const textField = form.getTextField(name);
  const widgets = textField.acroField.getWidgets();
  widgets.forEach((w) => {
      let rectangle = w.getRectangle();
      let page = pdfDoc.getPages().find((p) => p.ref === w.P());
      let pageIndex = pdfDoc.getPages().findIndex((p) => p.ref === w.P());
  });
})
```

Here `w.P()` returns the PDFRef corresponding to the page which the widget belongs to. https://github.com/Hopding/pdf-lib/blob/93dd36e85aa659a3bca09867d2d8fac172501fbe/src/core/annotation/PDFWidgetAnnotation.ts#L43-L47

**Comment by littlefatcat163** [comment]
Both of the above methods are fine, thank you very much

**Comment by sayo96** [comment]
@adoriandoran  w.P() appears as undefined in some scenarios. Any idea on why that is caused?

**Comment by jameszhan02** [comment]
> P(): PDFRef | undefined { 
>    const P = this.dict.get(PDFName.of('P')); 
>    if (P instanceof PDFRef) return P; 
>    return undefined; 
>  }

did u figured out what happening here?

**Comment by jameszhan02** [comment]
> @adoriandoran w.P() appears as undefined in some scenarios. Any idea on why that is caused?

did you figured out what is happening here?

**Comment by mymattcarroll** [comment]
`w.P()` is also returning `undefined` for me. Is there a way to fix this?

**Comment by sayo96** [comment]
This library is not maintained I guess. At this point, I would recommend using this only if you are able to decode all the internal functions

**Comment by rmarquois** [comment]
Hi,

Found solution on [StackOverflow ](https://stackoverflow.com/a/72564607). Thanks to him ^^

I do this and it works :

```
const signatureField = fields.find((field) => field.getName() === "SIGNATURE")

const fieldPage = pdfDoc.findPageForAnnotationRef(signatureField.ref)
const fieldPageNum = pdfDoc.getPages().findIndex(page => page.ref.tag === fieldPage.ref.tag) + 1
```

**Comment by zenric-atlasopen1** [comment]
`w.P()` is also returning undefined for me
