### ISSUE TITLE
Ability to determine which page an object comes from

### ISSUE THREAD

**Issue by fancydev18** [Hopding/pdf-lib#1096]
### Describe your idea

Hello, I'd like to extract images and other objects from PDF, but knowing exactly from which page that object came.

https://pdf-lib.js.org/docs/api/classes/pdfpage (obtained with ` let pages = pdfDoc.getPages()`) repeats all the information which is in `pdfDoc`. 
First issue:  `pages[0].node.context` has the same number of objects as `pdfDoc.context`
Expected: since I'm looking at a specific page, it should include only objects which are on this specific page.

The code below works (in some cases) to get images for the entire PDF. 

Proposal:
Something similar to `pdfDoc.context.enumerateIndirectObjects()` should also work per page, eg
`pages[0].context.enumerateIndirectObjects()` -- get the list of all objects (images, texts...) on THIS page, not entire PDF.

Thanks

```
var fs = require('fs')
var path = require('path')
var Jimp = require('jimp')

const { PDFDocument, PDFRawStream, PDFName } = require('pdf-lib')


async function runTest() {
    //console.log("propName::" + propName);
    var templ = 'brochure.pdf'
    console.log("File:" + templ)
    //my load statement
    const pdfDoc = await PDFDocument.load(fs.readFileSync(templ))
    const enumeratedIndirectObjects = pdfDoc.context.enumerateIndirectObjects()
    enumeratedIndirectObjects.forEach(async (x, objIdx) => {
        const pdfRef = x[0]
        const pdfObject = x[1]

        if (!(pdfObject instanceof PDFRawStream)) return

        //const { dict } = pdfObject
        console.log('objIdx', objIdx, 'pdfObject', pdfObject)
        var buffer = Buffer.from(pdfObject.contents)
        try {
            const img = await Jimp.read(buffer)
            console.log(`${objIdx.toString()}.jpg`)
            img.writeAsync(`images/${objIdx.toString()}.jpg`, Jimp.MIME_JPEG)
        } catch (e) {
            // console.log(buffer);
            console.log([objIdx, e.message])
        }
    })

}

runTest()
```

### How could this be implemented?

The code which gets context should include a page index for each property.
This way, pages.context would be just a filter on pdfDoc.context

### What problem are you trying to solve?

Getting objects (images, texts) for each specific page.

### Why does this matter to you?

Trying to parse PDF documents page by page (then make edits on each page object)

### Would others find this helpful?

I believe it would be quite useful to know objects on each specific page.

### Are you interested in implementing your proposal?

Yes

### Why are you submitting a proposal?

I'd like to help, I don't know how to accomplish

**Comment by fancydev18** [comment]
Example docs
[brochure.pdf](https://github.com/Hopding/pdf-lib/files/7587619/brochure.pdf)
[toyota.pdf](https://github.com/Hopding/pdf-lib/files/7587620/toyota.pdf)

**Comment by Hopding** [comment]
Hello @fancydev18! Something like this might be possible. You'll need to understand the underlying structure of PDF files before you can make any headway. Have you read the sections of the spec outlined [here](https://github.com/Hopding/pdf-lib/blob/master/docs/CONTRIBUTING.md#understanding-pdfs)? Happy to discuss options if/once you've done this.

**Comment by hafsa-dmnt** [comment]
Hello, I wanted to know if something happened next ? I'm facing this issue, of knowing where an object comes from so it would be really useful atm :) thanks

**Comment by isohanvanani** [comment]
is there any solution for this? I am also looking for the same.

**Comment by hafsa-dmnt** [comment]
> is there any solution for this? I am also looking for the same.

Hello @isohanvanani ! Sorry to reply only now ; i in fact found a way to find which images come from a specific page. Maybe the code you're searching is not far from that.

A way to get an array of the refs of the images in a page,
Array.from(page.node.normalizedEntries().XObject.dict.values())

tell me if you need anything :)

**Comment by yannbertrand** [comment]
> > is there any solution for this? I am also looking for the same.
>
> A way to get an array of the refs of the images in a page,
> ```
> Array.from(page.node.normalizedEntries().XObject.dict.values())
> ```

I'm trying the same
``` 
Array.from(pdfDoc.getPage(0).node.normalizedEntries().XObject.dict.values());
```

But it looks like this code gives an array of `PDFRef`s and not an array of tuples `[PDFRef, PDFObject]`. Can you elaborate on the full code you have now?

**Comment by kotasudhakar** [comment]
Can someone please help me how I can get the page number of image objects when .enumerateObjects is called?
