### ISSUE TITLE
pdfDoc.images[] is empty

### ISSUE THREAD

**Issue by fancydev18** [Hopding/pdf-lib#1098]
### What were you trying to do?

Extract images from PDF

### How did you attempt to do it?

pdfDoc has specific object properties (Great!), including `images`, but it's an empty array.

This works:
```
var fs = require('fs')
var path = require('path')
var Jimp = require('jimp')

const { PDFDocument, PDFRawStream, PDFName } = require('pdf-lib')


async function runTest() {
    //console.log("propName::" + propName);
    var templ = 'brochure.pdf'
    console.log("File:" + templ)
    //my load statement
    const pdfDoc = await PDFDocument.load(fs.readFileSync(templ))
    const enumeratedIndirectObjects = pdfDoc.context.enumerateIndirectObjects()
    enumeratedIndirectObjects.forEach(async (x, objIdx) => {
        const pdfRef = x[0]
        const pdfObject = x[1]

        if (!(pdfObject instanceof PDFRawStream)) return

        //const { dict } = pdfObject
        console.log('objIdx', objIdx, 'pdfObject', pdfObject)
        var buffer = Buffer.from(pdfObject.contents)
        try {
            const img = await Jimp.read(buffer)
            console.log(`${objIdx.toString()}.jpg`)
            img.writeAsync(`images/${objIdx.toString()}.jpg`, Jimp.MIME_JPEG)
        } catch (e) {
            // console.log(buffer);
            console.log([objIdx, e.message])
        }
    })

}

runTest()

```

### What actually happened?

empty array

### What did you expect to happen?

get a list of images. Each image should have buffer (that can be extracted/written to disk) and page index (from what page in PDF it came)
[brochure.pdf](https://github.com/Hopding/pdf-lib/files/7587630/brochure.pdf)
[toyota.pdf](https://github.com/Hopding/pdf-lib/files/7587632/toyota.pdf)

### How can we reproduce the issue?

```
const pdfDoc = await PDFDocument.load(fs.readFileSync(originalPdfPath))
console.log('pdfDoc', pdfDoc)
```

### Version

1.17.1

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by Hopding** [comment]
Hello @fancydev18! Looks like you've misunderstood what the `images` property is used for. It's a `private readonly` property that is not part of the public API: https://github.com/Hopding/pdf-lib/blob/93dd36e85aa659a3bca09867d2d8fac172501fbe/src/api/PDFDocument.ts#L187

See https://github.com/Hopding/pdf-lib/issues/83#issuecomment-487383843 for more details on image extraction with pdf-lib.
