### ISSUE TITLE
Importing existing PDF 'URL scheme "file" is not supported.'

### ISSUE THREAD

**Issue by BBGun007** [Hopding/pdf-lib#1099]
### What were you trying to do?

I'm trying to modify an existing PDF. I have previously used this library this way and have had no issue. I even copied and pasted the code from both the place where I know it was working, and from the installation instructions, as well as taken a demo code from a different GitHub issue and tried to run that right away and the same thing happens.

### How did you attempt to do it?

Ways I've tried to do it is my using the PDF as a local file.

  ```
  async function modifyPdf() {
        const url = 'camper.pdf'
        const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

        const pdfDoc = await PDFDocument.load(existingPdfBytes)
        const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

        const pages = pdfDoc.getPages()
        const firstPage = pages[0]
        const { width, height } = firstPage.getSize()
        firstPage.drawText('This text was added with JavaScript!', {
            x: 5,
            y: height / 2 + 300,
            size: 50,
            font: helveticaFont,
            color: rgb(0.95, 0.1, 0.1),
            rotate: degrees(-45),
        })
        const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
        const pdfBytes = await pdfDoc.save();
        document.getElementById('pdf').src = pdfDataUri;

    }
```

Take note of URL. 

Another way I've tried is uploading the PDF onto a webhost

```
  async function modifyPdf() {
        const url = 'https://www.glmdfilehosting.com/camperorder/camper.pdf'
        const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

        const pdfDoc = await PDFDocument.load(existingPdfBytes)
        const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

        const pages = pdfDoc.getPages()
        const firstPage = pages[0]
        const { width, height } = firstPage.getSize()
        firstPage.drawText('This text was added with JavaScript!', {
            x: 5,
            y: height / 2 + 300,
            size: 50,
            font: helveticaFont,
            color: rgb(0.95, 0.1, 0.1),
            rotate: degrees(-45),
        })
        const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
        const pdfBytes = await pdfDoc.save();
        document.getElementById('pdf').src = pdfDataUri;

    }
```

Another thing I tried was the URL from the instructions on the main website for this library.

```
async function modifyPdf() {
        const url = 'https://pdf-lib.js.org/assets/with_update_sections.pdf'
        const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

        const pdfDoc = await PDFDocument.load(existingPdfBytes)
        const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

        const pages = pdfDoc.getPages()
        const firstPage = pages[0]
        const { width, height } = firstPage.getSize()
        firstPage.drawText('This text was added with JavaScript!', {
            x: 5,
            y: height / 2 + 300,
            size: 50,
            font: helveticaFont,
            color: rgb(0.95, 0.1, 0.1),
            rotate: degrees(-45),
        })
        const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
        const pdfBytes = await pdfDoc.save();
        document.getElementById('pdf').src = pdfDataUri;

    }
```

And this worked.... The only thing I changed was the URL.

### What actually happened?

Using just the url of 'camper.pdf' produced the following error. 52 Fetch API cannot load file:///C:/URL/camper.pdf. URL scheme "file" is not supported.

However using the whole URL domain. 'https://www.glmdfilehosting.com/camperorder/camper.pdf' I get a CORS error...

If I upload the script files onto the same webhost and use the local url of camper.pdf I have no errors but the iframe source is just white and doesn't fetch the PDF correctly.

### What did you expect to happen?

I expect that with the URL of 'https://www.glmdfilehosting.com/camperorder/camper.pdf' that it'll get the pdf document alter it and show it in the iframe. 

### How can we reproduce the issue?

Execute this code

```
const { degrees, PDFDocument, rgb, StandardFonts } = PDFLib

    async function modifyPdf() {
        const url = 'https://www.glmdfilehosting.com/camperorder/camper.pdf'
        const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

        const pdfDoc = await PDFDocument.load(existingPdfBytes)
        const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

        const pages = pdfDoc.getPages()
        const firstPage = pages[0]
        const { width, height } = firstPage.getSize()
        firstPage.drawText('This text was added with JavaScript!', {
            x: 5,
            y: height / 2 + 300,
            size: 50,
            font: helveticaFont,
            color: rgb(0.95, 0.1, 0.1),
            rotate: degrees(-45),
        })
        const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
        const pdfBytes = await pdfDoc.save();
        document.getElementById('pdf').src = pdfDataUri;

    }
```

This is how I get a CORS error.

Or go to https://www.glmdfilehosting.com/camperorder/camper.pdf download the pdf and then perform

```
const { degrees, PDFDocument, rgb, StandardFonts } = PDFLib

    async function modifyPdf() {
        const url = 'camper.pdf'
        const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

        const pdfDoc = await PDFDocument.load(existingPdfBytes)
        const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

        const pages = pdfDoc.getPages()
        const firstPage = pages[0]
        const { width, height } = firstPage.getSize()
        firstPage.drawText('This text was added with JavaScript!', {
            x: 5,
            y: height / 2 + 300,
            size: 50,
            font: helveticaFont,
            color: rgb(0.95, 0.1, 0.1),
            rotate: degrees(-45),
        })
        const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
        const pdfBytes = await pdfDoc.save();
        document.getElementById('pdf').src = pdfDataUri;

    }
```
And this will produce the URL scheme "file" is not supported. error

### Version

1.4.0

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

I am just running straight vanilla javascript.

**Comment by Hopding** [comment]
Hello @BBGun007! You're error is unrelated to pdf-lib itself. Looks like you're having trouble using the `fetch` API. I'd recommend doing some research on CORS, `fetch`, and loading local files into a script in a browser. In general, you'll need to use a HTTP server of some sort (unless you're writing a Node script). 

Google is your friend, but here's a few links that might help get you started:
* https://stackoverflow.com/questions/50007055/fetch-request-to-local-file-not-working
* https://stackoverflow.com/questions/49971575/chrome-fetch-api-cannot-load-file-how-to-workaround/59925724#59925724

You can also check out pdf-lib's `web` integration tests to see how they're setup to load local files.
