### ISSUE TITLE
getSize() method to return actual value in inches/centimeters

### ISSUE THREAD

**Issue by simonhrmo** [Hopding/pdf-lib#1101]
### Describe your idea

getSize() method to return actual value in inches/centimeters

- currently returns value in pts 
- similarly for get getWidth() and getHeight()

### How could this be implemented?

.getInchesSize()
.getCentimetersSize()

or 

.getSize().inches()
.getSize().centimeters

### What problem are you trying to solve?

I am trying to extract width and height property from my pdf (page size property)
Values are: 22.22 x 16.53 in

What I get from getSize() ?
1600 1190 (close but not precise)

### Why does this matter to you?

I am working on a project where precision is a key and current getSize() could lead to a problem with larger PDF files

### Would others find this helpful?

I couldn't find any other js library that would be able to read pdf page size accurately in inches/centimeters

### Are you interested in implementing your proposal?

No

### Why are you submitting a proposal?

I was wondering if there is a way this idea could be implemented 

### Additional Notes

Thanks for the consideration

**Comment by Hopding** [comment]
Hello @simonhrmo! Thanks for the proposal. I'd be open to accepting a PR for this. It should be fairly straightforward to implement.

Some info for anybody interested in working on it: The values returned by all size-related methods are in "point" units. `1 point = 1/72 inch`. See also https://github.com/Hopding/pdf-lib/issues/19#issuecomment-412275915.

A couple API possibilities come to mind:
```js
// New methods for each size unit
page.getWidthInches()
page.getHeightInches()
page.getSizeInches()

// An option parameter denoting the desired unit
import { Unit } from 'pdf-lib'
page.getWidth({ unit: Unit.Inch })
page.getHeight({ unit: Unit.Inch })
page.getSize({ unit: Unit.Inch })
```

I'm leaning towards an option parameter atm.

**Comment by hilmanski** [comment]
hi! is anyone working on this API yet? or already implemented?
would love to try to contribute if not
