### ISSUE TITLE
How to fill form radio fields

### ISSUE THREAD

**Issue by pammann-work** [Hopding/pdf-lib#111]
Can pdf-lib be used to programmatically fill out radio fields in a template PDF?
Analog to #48

PDF source looks like:
```
...
148 0 obj
<</BC[]/BG[0.952896 0.952896 0.952896]>>
endobj
149 0 obj
<</Count 0/Type/Outlines>>
endobj
150 0 obj
[214 0 R 171 0 R 184 0 R 202 0 R 176 0 R 186 0 R 180 0 R 192 0 R 188 0 R 178 0 R 196 0 R 198 0 R 200 0 R 194 0 R 190 0 R 182 0 R 151 0 R 152 0 R 153 0 R 18 0 R 70 0 R 19 0 R 24 0 R 79 0 R 71 0 R 17 0 R 75 0 R 68 0 R 67 0 R 59 0 R 74 0 R 37 0 R 86 0 R 38 0 R 90 0 R 94 0 R 88 0 R 40 0 R 89 0 R 30 0 R 28 0 R 34 0 R 26 0 R 105 0 R 113 0 R 99 0 R 127 0 R 104 0 R 142 0 R 98 0 R 143 0 R 115 0 R 110 0 R 147 0 R 117 0 R 141 0 R 130 0 R 103 0 R]
endobj
151 0 obj
<</FT/Btn/Ff 49152/Kids[211 0 R]/Opt 156 0 R/T(Radio 1)>>
endobj
152 0 obj
<</FT/Btn/Ff 49152/Kids[208 0 R]/Opt 155 0 R/T(Radio 2)>>
endobj
153 0 obj
<</FT/Btn/Ff 49152/Kids[204 0 R]/Opt 154 0 R/T(Radio 3)>>
endobj
154 0 obj
[(Choice1)]
endobj
155 0 obj
[(Choice1)]
endobj
156 0 obj
[(Choice1)]
endobj
157 0 obj
...
```

**Comment by Hopding** [comment]
Hello @pammann-work! 

I created an example script demonstrating how to do this: [pdf-lib_radio_button_form_fill_example.zip](https://github.com/Hopding/pdf-lib/files/3195143/pdf-lib_radio_button_form_fill_example.zip)

You can run the script with the following commands (you may have to tweak them a bit if you're running Windows):
```
unzip pdf-lib_radio_button_form_fill_example.zip
cd pdf-lib_radio_button_form_fill_example
npm install
node index.js
```

Here's the input PDF: [simple_form.pdf](https://github.com/Hopding/pdf-lib/files/3195150/simple_form.pdf)
And here's the output: [filled_form.pdf](https://github.com/Hopding/pdf-lib/files/3195151/filled_form.pdf)

Here's a snippet from the script showing the gist of the process:
```js
const getAcroFields = pdfDoc => {
  if (!pdfDoc.catalog.getMaybe('AcroForm')) return [];
  const acroForm = pdfDoc.index.lookup(pdfDoc.catalog.get('AcroForm'));

  if (!acroForm.getMaybe('Fields')) return [];
  const acroFields = pdfDoc.index.lookup(acroForm.get('Fields'));

  return acroFields.array.map(pdfDoc.index.lookup);
};

const findAcroFieldByName = (pdfDoc, name) => {
  const acroFields = getAcroFields(pdfDoc);
  return acroFields.find(acroField => {
    const fieldName = acroField.getMaybe('T');
    return !!fieldName && fieldName.string === name;
  });
};

console.log('Selecting "Stuff"');
const pdfDoc = PDFDocumentFactory.load(fs.readFileSync('./simple_form.pdf'));
const radioButtonGroup = findAcroFieldByName(pdfDoc, 'StuffOrThings');
radioButtonGroup.set('V', PDFName.from('Stuff'));

console.log('Saving PDF')
const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
fs.writeFileSync('./filled_form.pdf', pdfBytes);

console.log('Filled-in Form Written To ./filled_form.pdf');
```

I hope this helps! Please let me know if you have any additional questions.

**Comment by pammann-work** [comment]
@Hopding Thank you very much for this example.

When i look at your filled_form.pdf, i do not see the radio box set (in Acrobat Reader + Firefox). I was not able to find out a working solution.

PS: I am using v0.6.2 of pdf-lib

**Comment by Hopding** [comment]
@pammann-work Sorry about that. It works fine on Mac's Preview. But you're correct - when I test on Acrobat/Firefox/Chrome, it does not work.

I took another look at the spec, and it looks like I missed two steps in my initial script. It's also necessary to set the `NeedAppearances` field on the AcroForm, as well as the `AS` field of the specific radio button you are wanting to select.

Here's an updated version of the script that performs the additional steps: [pdf-lib_radio_button_form_fill_example.zip](https://github.com/Hopding/pdf-lib/files/3199889/pdf-lib_radio_button_form_fill_example.zip)
 
And here's the new output: [filled_form.pdf](https://github.com/Hopding/pdf-lib/files/3199892/filled_form.pdf)

Here's a snippet showing the new helper function and the additional steps:

```js
const getAcroForm = pdfDoc => {
  return pdfDoc.index.lookup(pdfDoc.catalog.get('AcroForm'));
};

const getRadioButtonByName = (pdfDoc, radioGroup, name) => {
  const index = pdfDoc.index;
  const radioButtonRefs = index.lookup(radioButtonGroup.get('Kids'));
  return radioButtonRefs
    .map(index.lookup)
    .find(radioButton => !!index
        .lookup(index.lookup(radioButton.get('AP')).get('D'))
        .getMaybe(name),
    );
}
...
const acroForm = getAcroForm(pdfDoc);
acroForm.set('NeedAppearances', PDFBoolean.fromBool(true));

const StuffButton = getRadioButtonByName(pdfDoc, radioButtonGroup, 'Stuff');
StuffButton.set('AS', PDFName.from('Stuff'));
```

**Comment by pammann-work** [comment]
@Hopding Thanks for the update, this one also works on my side.

My current problem is that i am not able to create such a PDF with InDesign.
When logging the options, there is no option name. Is there a special trick?
In InDesign i set name="same for all options" and value="different strings".

I get the error:
```
Error: Missing PDFDictionary entry "D".

From Line:
const getRadioButtonByName = (pdfDoc, radioGroup, name) => {
...
.lookup(index.lookup(radioButton.get('AP')).get('D'))
```


log:
```
Radio Button Group Options:
Option 0:
<<
/AP <<
/N <<
/0 208 0 R
/Off 209 0 R
>>
>>
/AS /Off
/BS <<
/S /I
/W 1
>>
/F 4
/MK 233 0 R
/P 165 0 R
/Parent 151 0 R
/Rect [ 34.0157 248.575 48.189 262.748 ]
/Subtype /Widget
/Type /Annot
>>

Option 1:
<<
/AP <<
/N <<
/1 205 0 R
/Off 206 0 R
>>
>>
/AS /Off
/BS <<
/S /I
/W 1
>>
/F 4
/MK 232 0 R
/P 165 0 R
/Parent 151 0 R
/Rect [ 122.457 248.575 136.63 262.748 ]
/Subtype /Widget
/Type /Annot
>>

Option 2:
<<
/AP <<
/N <<
/2 201 0 R
/Off 202 0 R
>>
>>
/AS /Off
/BS <<
/S /I
/W 1
>>
/F 4
/MK 231 0 R
/P 165 0 R
/Parent 151 0 R
/Rect [ 209.739 248.575 223.912 262.748 ]
/Subtype /Widget
/Type /Annot
>>
```

**Comment by Hopding** [comment]
@pammann-work

It looks like your radio button group has three options named `0`, `1`, and `2` (Instead of `Stuff` and `Things`). So you’ll want to use those values for the button names when selecting them.

Also, regarding the error you encountered: Change the `'D'` in that function to `'N'` and it should work. That was just another oversight on my part. The spec requires all buttons to define a value for `'N'`, but not for `'D'`. The `'D'` entry is optional. The PDF I was working with had it, but yours doesn’t seem to.

**Comment by Hopding** [comment]
@astanet Thanks for updating the example! 

I agree that it's rather difficult to understand the structure of PDF files. I still don't understand everything about them, and I've been working on `pdf-lib` for a little over 2 years now! (see the [first commit](https://github.com/Hopding/pdf-lib/commit/fd7459e5ecee898c4f6bbccae021af2d837d64be))

If you want to better understand the structure of PDF files, I'd advise reading through some key sections of the [PDF specification](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf). There really is no substitute for it. There is also [a book](http://shop.oreilly.com/product/0636920021483.do) by a fellow named John Whitington that might be useful, though I haven't read it myself.

**Comment by Hopding** [comment]
`pdf-lib` now has form creation and filling APIs that should be used instead of the above example(s). See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFRadioGroup.select`](https://pdf-lib.js.org/docs/api/classes/pdfradiogroup#select) method is of particular relevance to this issue.
