### ISSUE TITLE
Extract only content of pages 

### ISSUE THREAD

**Issue by danielNg25** [Hopding/pdf-lib#1127]
### What are you working on?

Hi, I'm trying to get the content data of a PDF file and hash it to find out whether its pages' content was modified. I tried to create new PDFDocument and copy all pages from original file to the new file and hash it with SHA256, but everytime I did it, i didn't get the same hashed string. Some of other information like metadata change everytime i create a new PDFDocument.
Is there any idea to do that?

**Comment by pranavburnwal** [comment]
@ndtr2000  Can you please share if you were able to achieve this? If yes maybe share how.

**Comment by danielNg25** [comment]
> 

@pranavburnwal So just as I said, the metadata was the problem. Specifically that is the creation and the modification date. So after copied to a new file, I changed the creation and the modification date to a specific date and I will get the same hash everytime I hash the new file (If the content wasn't changed).

**Comment by pranavburnwal** [comment]
Got it thanks!
