### ISSUE TITLE
How to add text with a web link

### ISSUE THREAD

**Issue by fmbrieva** [Hopding/pdf-lib#113]
Hi, can _pdf-lib_ add text with a web link?

I need  to add texts with links (simple URI link) in a document

Thanks for your work!!

**Comment by Hopding** [comment]
Hello @fmbrieva!

`pdf-lib` does support this. Please see my comment on https://github.com/Hopding/pdf-lib/issues/45#issuecomment-441043920 for an example.

I hope this helps. Let me know if you have any further questions!
