### ISSUE TITLE
Merge doesn't work with prototype.js

### ISSUE THREAD

**Issue by sudhar99** [Hopding/pdf-lib#1248]
### What were you trying to do?

I am trying to merge user uploaded PDF files into a single file and is not working with prototype.js. I can't remove this, as it is part of our framework. Suggest the best alternative to resolve this conflict. See the code snippet below.

### How did you attempt to do it?

```
<html>
	<head>	
		<!-- <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>  DOESN'T WORK WITH THIS -->
		<script src="https://unpkg.com/pdf-lib/dist/pdf-lib.js"></script>
		<script>
	      function download(file, filename, type) {
	         const link = document.getElementById('link');
	         link.download = filename;
	         let binaryData = [];
	         binaryData.push(file);
	         link.href = URL.createObjectURL(new Blob(binaryData, {type: type}))
	      }
	      async function merge() {
	         let PDFDocument = PDFLib.PDFDocument;
	         const mergedPdf = await PDFDocument.create(); 
	         for (var i = 0; i < document.getElementById('files').files.length; i++) {
		         const currentFile = document.getElementById('files').files[i];
		         const currentPdf = await PDFDocument.load(await currentFile.arrayBuffer());
		         const copiedPages = await mergedPdf.copyPages(currentPdf, currentPdf.getPageIndices());
		         copiedPages.forEach((page) => mergedPdf.addPage(page));
	         }
	         const mergedPdfFile = await mergedPdf.save();
	         download(mergedPdfFile, 'combined.pdf', 'application/pdf');
	      }
	   </script>
	</head>
	<body>
		<input type="file" id="files" multiple onchange="merge();"> <br>
		<br>
	  	<a id="link">Download</a>
	</body>
</html>
```   

### What actually happened?

It works without prototype; but with prototype, I get corrupted merged PDF file with Uint8Array of 90 bytes.

### What did you expect to happen?

I would like to have the merge function work with prototype.js.

### How can we reproduce the issue?

Please run the HTML snippet

### Version

1.17.1 - Latest

### What environment are you running pdf-lib in?

Browser

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by joewestcott** [comment]
`prototype.js` is well known for monkey-patching global objects, and breaking other libraries in the process!
https://en.wikipedia.org/wiki/Prototype_JavaScript_Framework#Problems

Unfortunately I wasn't able to find out exactly which part of pdf-lib was silently failing, or if it could be worked around. I don't think there would be any interest in solving this, as the techniques used by Prototype has fallen out of favour in modern JS. The latest version is many years old at this point. Perhaps you could debug further and find out where it's failing?

Another option could be doing your pdf-lib code in an iframe without Prototype involved?

**Comment by sudhar99** [comment]
Thanks and greatly appreciate your inputs. I used webworker and implemented it. Will try with iFrame solution.
