### ISSUE TITLE
index` must be at least 0 and at most 33 but my pdf have almost 41 pages

### ISSUE THREAD

**Issue by abubakar-dzinemedia** [Hopding/pdf-lib#1249]
### What were you trying to do?

I am trying to remove pages using thi pdf-lib library.

### How did you attempt to do it?

` async downloadPdfFile() {
      var url = "/uploads/" + this.pdfFile.upload.filename;
      var existingPdfBytes = await fetch(url).then((res) => res.arrayBuffer());
      var pdfDoc = await PDFDocument.load(existingPdfBytes);
      let pages = this.selectedPages;
      pages.sort(function (a, b) {
        return a - b;
      });
        pages.map((element) => {
          console.log(element);
          pdfDoc.removePage(element);
        });
      var PdfBytes = await pdfDoc.save();
      download(PdfBytes, `Delete Pdf ${new Date()}.pdf`, "application/pdf");
    },`

### What actually happened?

 Error: `index` must be at least 0 and at most 33, but was actually 38. But I have more than 38 pages in my pdf.

### What did you expect to happen?

I should remove the selected pages on the base of index given.

### How can we reproduce the issue?

` async downloadPdfFile() {
      var url = "/uploads/" + this.pdfFile.upload.filename;
      var existingPdfBytes = await fetch(url).then((res) => res.arrayBuffer());
      var pdfDoc = await PDFDocument.load(existingPdfBytes);
      let pages = this.selectedPages;
      pages.sort(function (a, b) {
        return a - b;
      });
        pages.map((element) => {
          console.log(element);
          pdfDoc.removePage(element);
        });
      var PdfBytes = await pdfDoc.save();
      download(PdfBytes, `Delete Pdf ${new Date()}.pdf`, "application/pdf");
    },`

### Version

1.17.1

### What environment are you running pdf-lib in?

Browser, Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by joewestcott** [comment]
This isn't a complete example, you've not provided the PDF or the `this.selectedPages` array!

Essentially, it seems like `this.selectedPages` contains an invalid page index. How many pages does `pdflib` report in the document? What's the result of `doc.getPageCount()`.

**Comment by abubakar-dzinemedia** [comment]
doc.getPageCount() is giving 42 pages.

> This isn't a complete example, you've not provided the PDF or the `this.selectedPages` array!
> 
> Essentially, it seems like `this.selectedPages` contains an invalid page index. How many pages does `pdflib` report in the document? What's the result of `doc.getPageCount()`.

its giving 42 pages. this.selectedPages is an array with numbers. but error is index` must be at least 0 and at most 33.

**Comment by joewestcott** [comment]
Could you supply the PDF?
Is the error you're seeing an [IndexOutOfBoundsError](https://github.com/Hopding/pdf-lib/blob/93dd36e85aa659a3bca09867d2d8fac172501fbe/src/core/errors.ts#L106-L111)? A stack trace would also be helpful, as I can't see how an error of that kind could be thrown from `pdfDoc.removePage(element)`.

**Comment by abubakar-dzinemedia** [comment]
I am seeing that library is removing the index and re-indexing the pages on pdfDoc.removePage(pageIndex). 
let we have 5 pages in a pdf. When I delete the page on index 3 the fourth page deleted and the fith page will move to the index 3. I dont know its a bug or something but I need a solution for it. If you have please describe I want to loop the array of indexes. Thanks.

**Comment by joewestcott** [comment]
Yes, if you remove the item at index 0, the item previously at item 1 would become 0.
This is intended, but to avoid attempting to remove pages at an invalid index, perhaps you could order the `selectedPages` array to be largest index first, rather than smallest first.

**Comment by abubakar-dzinemedia** [comment]
Yes I tried it. Its working fine Thanks.

**Comment by hilmanski** [comment]
Thanks for the trick @joewestcott 
I document it for other, in case anyone want an example
https://onebite.dev/removing-page-in-pdf-lib-show-error-index-must-be-at-least-x/

```
const pages [4 , 1 , 3, 2]
const sortedPages = pages.sort((a: number, b: number) => b - a)
sortedPages.forEach((page: any) => {
    const pageIndex = page - 1
    PDF_DOC.removePage(pageIndex)
})
```
