### ISSUE TITLE
Resize existing pages?

### ISSUE THREAD

**Issue by Hopding** [Hopding/pdf-lib#128]
Can `pdf-lib` be used to open an existing PDF document and resize the width and/or height of some of its pages?

**Comment by Hopding** [comment]
Yes. However, this requires a few custom functions to be written. I've created an example script to demonstrate how this can be done. Here's the high level idea:

```js
// Load the original PDF file
const pdfDoc = PDFDocumentFactory.load(originalPdfBytes);

// Get the first page in the PDF
const pages = pdfDoc.getPages();
const page = pages[0];

// Get the width and height of the page
const { width, height } = getPageDimensions(page);

// Increase the width and height of the page by 200 points.
// Note that this adds 200 points of whitespace to the top of the page,
// and 200 points of whitespace to the right of the page.
setPageDimensions(page, { width: width + 200, height: height + 200 });

// Translate/slide the page's contents to the top right corner of the page,
// (up 200 points and right 200 points) to make use of the new whitespace
// created in the previous step. 
translatePageContents(pdfDoc, page, { x: 200, y: 200 });

// Serialize the modified document
const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
```

And here are the custom functions referred to in the above snippet:

```js
const getPageMediabox = page => {
  let mediaBox;

  // Check for MediaBox on the page itself
  const hasMediaBox = !!page.getMaybe('MediaBox');
  if (hasMediaBox) {
    mediaBox = page.index.lookup(page.get('MediaBox'));
  }

  // Check for MediaBox on each parent node
  page.Parent.ascend(parent => {
    const parentHasMediaBox = !!parent.getMaybe('MediaBox');
    if (!mediaBox && parentHasMediaBox) {
      mediaBox = parent.index.lookup(parent.get('MediaBox'));
    }
  }, true);

  // This should never happen in valid PDF files
  if (!mediaBox) throw new Error('Page Tree is missing MediaBox');

  return mediaBox;
};

const getPageDimensions = page => {
  const mediaBox = getPageMediabox(page);
  return { width: mediaBox.array[2].number, height: mediaBox.array[3].number };
};

const setPageDimensions = (page, dims) => {
  const originalMediaBox = getPageMediabox(page);
  const newMediaBox = originalMediaBox.clone();
  newMediaBox.array[2] = PDFNumber.fromNumber(dims.width);
  newMediaBox.array[3] = PDFNumber.fromNumber(dims.height);
  page.set('MediaBox', newMediaBox);
};

const translatePageContents = (pdfDoc, page, shiftAmounts) => {
  const contentsRef = page.getMaybe('Contents');
  let contents = pdfDoc.index.lookupMaybe(page.getMaybe('Contents'));

  if (!contents) {
    contents = PDFArray.fromArray([], page.index);
    page.set('Contents', contents);
  } else if (contents instanceof PDFRawStream) {
    contents = PDFArray.fromArray([contentsRef], page.index);
    page.set('Contents', contents);
  } else if (!(contents instanceof PDFArray)) {
    const type = contents.constructor.name;
    throw new TypeError(`Unknown page.Contents type: ${type}`);
  }

  const startWrapperStream = pdfDoc.createContentStream(
    pushGraphicsState(),
    translate(shiftAmounts.x, shiftAmounts.y),
  );
  const endWrapperStream = pdfDoc.createContentStream(popGraphicsState());

  const startWrapperStreamRef = pdfDoc.register(startWrapperStream);
  const endWrapperStreamRef = pdfDoc.register(endWrapperStream);

  contents.array.unshift(startWrapperStreamRef);
  contents.array.push(endWrapperStreamRef);
};
```

Here's a zip file containing the complete working script: [pdf-lib_page-resizing.zip](https://github.com/Hopding/pdf-lib/files/3307368/pdf-lib_page-resizing.zip). To execute it, just download the zip file and run the following:
```bash
unzip pdf-lib_page-resizing.zip
cd pdf-lib_page-resizing
yarn install # or npm install
node index.js
```

Here's the input and output files for the script:
* Input: [original.pdf](https://github.com/Hopding/pdf-lib/files/3307397/original.pdf)
* Output: [modified.pdf](https://github.com/Hopding/pdf-lib/files/3307398/modified.pdf)

**Comment by vegarringdal** [comment]
@Hopding 
Almost similar tread, so figured I could ask here.
Will this be able to scale pages up or down with all content/annotations?

Need to set a multipage pdfs to be just A4 and A3 sizes.
So anything below A4 needs to be scaled up to A4. 
Between  A4 and A3 to A4 and above A3 down to A3.

Using print to PDF atm, but I really want to try and automated this, 
Atm this lib looks most promising. And it beeing made with typescript only is really impressive.

**Comment by sendrel-lambdas** [comment]
Works perfectly when increasing the size of the pdf. How can I modify this function so I can decrease the size of the pdf? What happens is that the pdf size decreases but it content doesn't so some of its contents are cut off. 

Is it possible?

Thanks.

**Comment by vegarringdal** [comment]
@sendrel-lambdas 
https://github.com/Hopding/pdf-lib/issues/692

**Comment by sendrel-lambdas** [comment]
Thanks! Managed to modify it to my liking.

**Comment by ll-BSN-ll** [comment]
How do I need to alter the code so dat is just set my trimbox to a round number, for example from 411.998 mm  to 412.00 mm or from 412.001 to 412.00 mm ?

**Comment by ajq47** [comment]
Hi! How do you install this exact same node-modules package in this custom code? I think this package is different from 

npm install pdf-lib

**Comment by ajq47** [comment]
Hi @Hopding , I am having an issue with some PDF uploaded here. Looks like some of them are not working on some PDFs. I noticed if it is trimmed, this code doesn't work
