### ISSUE TITLE
How to import pdf?

### ISSUE THREAD

**Issue by gegobyte** [Hopding/pdf-lib#129]
I am very new to modern javascript so I am unable to import a pdf file for modification.

My folder structure is like this:

```
 pdf-lib
  |- package.json
  |- webpack.config.js
  |- /dist
    |- bundle.js
    |- index.html
  |- /src
    |- /assets
      |- account_modification_form.pdf
    |- index.js
  |- /node_modules
```

I want to add some text to the pdf file in assets folder. Based on this [existing issue](https://github.com/Hopding/pdf-lib/issues/51), I got this code:

```javascript
fetch('../src/assets/account_modification_form.pdf')
      .then(function(response) {
        response.arrayBuffer()
        .then(function(buffer) {
          const existingPdfDocBytes = new Uint8Array(buffer);
          var pdfDoc = PDFLib.PDFDocumentFactory.load(existingPdfDocBytes);
        })
    });
```

And my whole index.js file looks like this:

```javascript
import { PDFDocumentFactory, PDFDocumentWriter, StandardFonts, drawText } from 'pdf-lib';

// This should be a Uint8Array.
// This data can be obtained in a number of different ways.
// If your running in a Node environment, you could use fs.readFile().
// In the browser, you could make a fetch() call and use res.arrayBuffer().

fetch('../src/assets/account_modification_form.pdf')
      .then(function(response) {
        response.arrayBuffer()
        .then(function(buffer) {
          const existingPdfDocBytes = new Uint8Array(buffer);
          var pdfDoc = PDFLib.PDFDocumentFactory.load(existingPdfDocBytes);
        })
    });    

// const pdfDoc = PDFDocumentFactory.load(assets.accountModificationPdfBytes);
const [helveticaRef, helveticaFont] = pdfDoc.embedStandardFont(
  StandardFonts.Helvetica,
);

const pages = pdfDoc.getPages();
const page  = pages[0];

page.addFontDictionary('Helvetica', helveticaRef);

const contentStream = pdfDoc.createContentStream(
  drawText(helveticaFont.encodeText('This text was added to the PDF with JavaScript!'), {
    x: 25,
    y: 25,
    size: 24,
    font: 'Helvetica',
    colorRgb: [0.95, 0.26, 0.21],
  }),
);

page.addContentStreams(pdfDoc.register(contentStream));

const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
```

I am getting some errors in console:

```
Fetch API cannot load file:///E:/<project-url>/src/assets/account_modification_form.pdf. URL scheme must be "http" or "https" for CORS request.

Uncaught ReferenceError: pdfDoc is not defined
    at Module.<anonymous> (bundle.js:1)
    at r (bundle.js:1)
    at bundle.js:1
    at bundle.js:1

Uncaught (in promise) TypeError: Failed to fetch
    at Module.<anonymous> (bundle.js:1)
    at r (bundle.js:1)
    at bundle.js:1
    at bundle.js:1
```

How to resolve these? Using Webpack, index.js becomes bundle.js in dist folder and I run index.html

**Comment by gegobyte** [comment]
What I want to do is have some text box on html page, user inputs value and those text go to predefined places on existing pdf.

**Comment by philipjmurphy** [comment]
I’d say to install a simple http server first and get content from there instead as error states that you need load content over http... 

npm i -g http-server

Start it in the same folder as your content. See https://www.npmjs.com/package/http-server for further information.

I posted an issue recently which may help you too: https://github.com/Hopding/pdf-lib/issues/124#issuecomment-50239418

**Comment by gegobyte** [comment]
@philipjmurphy I made it work by using fs as mentioned in [this example](https://github.com/Hopding/pdf-lib/blob/master/examples/document_modification/node/index.js) and running `node index.js` in src folder. And it generates the modified pdf file.

Now I installed http-server as you said and tried running it in the dist folder where my index.html and bundle.js lies. So I run webpack which converts index.js into bundle.js and then I run `http-server ./dist` and getting "Invalid response" error.

**Comment by philipjmurphy** [comment]
Could you zip it up and I'll have a quick look.

**Comment by gegobyte** [comment]
@philipjmurphy I just created a repository and uploaded the complete code and added you as a collaborator.

**Comment by philipjmurphy** [comment]
Ok - I have something working. However, I just realised that this is more of a webpack thing. Actually, I've never used webpack before, so wasn't too sure what was going on here. After some research, it appears that you need to specify what the target is e.g. web, node etc. Add this to the webpack config file stopped it from moaning about not being able to find the fs module. I made a few more changes as outlined here.

**package.json**
set "private": true, as recommended in webpack tutorial

**webpack.config.js**
I use main.js where you use bundle.js - but this is immaterial
target: 'node',
mode: 'development' (handy for debugging)

**src/index.js**
I removed the ${__dirname} in front of `./modified.pdf`

**src/assets**
I moved them to **dist/assets**

Probably a better way to do this, but I just cd'ed to the dist folder and ran the following to start a build and run cycle.

cd dist
(cd .. && npm run build)
node main.js

This will get you by, but might be better to research further on how to do this properly as this is a bit of guess work for me. Best of luck.

I've attached the new project for your convenience.

[pdflib-demo-new.zip](https://github.com/Hopding/pdf-lib/files/3318528/pdflib-demo-new.zip)

Agghh - just realised after re-reading your post that you are looking to do this from the web. Looking at the shared project I thought that you were doing it from the command-line. I've created another version that will work from the web which I'll post shortly.

**Comment by philipjmurphy** [comment]
Here's a web version that will work, but I'm no webpack expert (only started using it a few hours ago :-) ). Anyway, following some instructions from here: https://webpack.js.org/guides/development/ I've got it to work.

npm install
npm run build
npm start

You should see the PDF open in your default browser.

This is using webpack as a module loader. It is using webpack-dev-server instead of http-server as it comes with the webpack build stack. Have a look at the webpack config file for other options I added to ease development.

I stuck the output into an iframe, so that you can make changes and reload them more easily.

[pdflib-demo-web.zip](https://github.com/Hopding/pdf-lib/files/3318617/pdflib-demo-web.zip)

**Comment by Hopding** [comment]
@philipjmurphy Thanks for helping out with this! Much appreciated 👍 

@gegobyte Have you been able to get this working? Or are you still running into trouble?

**Comment by gegobyte** [comment]
@philipjmurphy Thank You.

@Hopding I am currently learning the basics of Express as my goal is to make input boxes and user enters some custom text which goes onto the pdf file. So I thought Express can help me in achieving that?

**Comment by gegobyte** [comment]
@philipjmurphy @Hopding So now I am using express to handle the navigation. I have created an html page containing a form with text box and button sent via post.

Here is my index.js

```javascript
const express = require('express');
const app = express();
const path = require('path');

// Body Parser Middleware
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

// Set static folder
app.use(express.static(path.join(__dirname, 'public')));

// Generate PDF Route
app.use('/generate', require('./routes/generate'));

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Listening on Port ${PORT}`));
```

index.html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Modification</title>
</head>

<body>
    <div class="container">
        <h1 class="mt-4">Modification</h1>
        <form action="/generate" method="POST" class="mb-4">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" class="form-control">
            </div>
            <input type="submit" value="Add Text" class="btn btn-primary btn-block">
        </form>
    </div>
</body>

</html>
```

generate.js

```javascript
const express = require('express');
const router = express.Router();
const fs = require('fs');
const fetch = require('node-fetch');

const {
    PDFDocumentFactory,
    PDFDocumentWriter,
    StandardFonts,
    drawText
} = require('pdf-lib');

// Handle User Data and Generate PDF
router.post('/', (req, res) => {
    console.log(`Form submitted with name ${req.body.name}`);

    fetch(`${req.protocol}://${req.get('host')}/public/assets/dummy.pdf`)
        .then(function (response) {
            response.arrayBuffer()
                .then(function (buffer) {
                    const existingPdfDocBytes = new Uint8Array(buffer);
                    var pdfDoc = PDFDocumentFactory.load(existingPdfDocBytes);

                    const [helveticaRef, helveticaFont] = pdfDoc.embedStandardFont(
                        StandardFonts.Helvetica,
                    );

                    const pages = pdfDoc.getPages();
                    const page = pages[0];

                    page.addFontDictionary('Helvetica', helveticaRef);

                    const contentStream = pdfDoc.createContentStream(
                        drawText(helveticaFont.encodeText(req.body.name), {
                            x: 25,
                            y: 25,
                            size: 24,
                            font: 'Helvetica',
                            colorRgb: [0.95, 0.26, 0.21],
                        }),
                    );

                    page.addContentStreams(pdfDoc.register(contentStream));

                    const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);

                    const filePath = `${__dirname}/modified.pdf`;
                    fs.writeFileSync(filePath, pdfBytes);
                    console.log(`PDF file written to: ${filePath}`);
                }).catch(function(err) {
                    console.log(err);
                })
        }).catch(function(error) {
            console.log(error);
        });
        res.redirect('/');
});

module.exports = router;
```

The above gives an error that "PDF is missing a header".

**Comment by philipjmurphy** [comment]
Is it something to do with the order of promises. Try the following simpler syntax to see if it fixes the issue:

... async (req, res) => {...

let pdfBuffer = await fetch(`${req.protocol}://${req.get('host')}/public/assets/dummy.pdf`).then(r => r.arrayBuffer()).then(buffer => new Uint8Array(buffer))
let pdfDoc = PDFDocumentFactory.load(pdfBuffer)
console.log('got here')

and see if 'got here' is printed out.

**Comment by gegobyte** [comment]
@philipjmurphy Getting the same error: `PDF is missing a header`

**Comment by philipjmurphy** [comment]
If you post your project I can have a quick look.

**Comment by gegobyte** [comment]
In the attached project, there are 2 branches - master and dev. master contains the code I had posted above and dev contains the code you had posted.

[pdflib-web.zip](https://github.com/Hopding/pdf-lib/files/3337627/pdflib-web.zip)

**Comment by philipjmurphy** [comment]
Ok - get rid of the folder 'public' from the path and you should be good. So, it should read 

```
    let pdfBuffer = await fetch(`${req.protocol}://${req.get('host')}/assets/dummy.pdf`).then(r => r.arrayBuffer()).then(buffer => new Uint8Array(buffer));
    let pdfDoc = PDFDocumentFactory.load(pdfBuffer);
    console.log('got here');
```

I figured it out by debugging the application. Do the following to debug:

node --inspect-brk index

Go to Chrome browser and visit: chrome://inspect

Select the target index and use the debugger as normal. I could see that it was actually returning a 404, so then knew it was a path problem.

**Comment by gegobyte** [comment]
@philipjmurphy It works, thanks!
