### ISSUE TITLE
Possible to save a change from a loaded PDF?

### ISSUE THREAD

**Issue by philipjmurphy** [Hopding/pdf-lib#130]
Hi,

I'm guessing that the answer to this is no (as PDF is sandboxed off in an iframe), but just wondering if this could be possible just in case? The scenario is as follows.

1) Read PDF into memory and display in an iframe using something like the following:

```
const pdfDoc = PDFDocumentFactory.load(pdfBuffer) // pdfBuffer was loaded via file open dialog
const pdfDocBytes = PDFDocumentWriter.saveToBytes(pdfDoc)
const pdfBlob = new Blob([pdfDocBytes], {type: 'application/pdf'})
const blobUrl = URL.createObjectURL(pdfBlob)
window.$('iframe')[1].src = blobUrl
```

2) The PDF is now displayed in the iframe. 

The question is, if I have a text field in the PDF and make a change is it possible to save that change (or get access access to it some how via the pdf-lib API)?

Thanks,

Philip

**Comment by Hopding** [comment]
Hello @philipjmurphy! Just to clarify... Are you trying to do the following?
1. Create/load a `PDFDocument` in memory
2. Save it to bytes and convert them into a `Blob` object
3. Render this `Blob` in an iframe
4. Edit the PDF rendered in the iframe
5. Extract the modified PDF from the iframe back into memory to load back into a `PDFDocument`?

**Comment by philipjmurphy** [comment]
Exactly - want to capture changes, so can send to server to save.

**Comment by Hopding** [comment]
I looked into this, and am unable to find a way to extract a PDF out of an iframe. I could be wrong, but I do not think this is possible to do. It would be quite handy if it were possible though.

Sorry for the late reply. I've been very busy getting v1.0.0 finished up.
