### ISSUE TITLE
Problem with vertical photo drawing. Photo autorotated.

### ISSUE THREAD

**Issue by ArkanRomanPango** [Hopding/pdf-lib#1329]
### What were you trying to do?

I tried to add vertical photo to pdf file. In result pdf I got rotated photo. When I tried to add horizontal photo - all works fine.

### How did you attempt to do it?

https://jsfiddle.net/b5nxyuhm/5 I took base64 photo and drawing it directly. If you paste base64 into some converter you will see vertical photo. Where you can try to check: https://codebeautify.org/base64-to-image-converter

### What actually happened?

Verical photo autorotated

### What did you expect to happen?

Not to rotate photo automatically. If I set vertical photo - draw vertical photo

### How can we reproduce the issue?

Took your example snippet, and used my base64 photo.
https://jsfiddle.net/b5nxyuhm/5

### Version

1.17.1

### What environment are you running pdf-lib in?

Browser, React Native

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

**Comment by ArkanRomanPango** [comment]
Found solution. As pdf-lib is cleaning or does not read exif data rotation, we have to detect what kind of rotation image has and then rotate image inside `drawImage options`.

I was using several libs 
1 - `base64-arraybuffer` - for decoding/endcoding base64 into bufferArray and vice versa
2 - `@ginpei/exif-orientation` - for detecting orientation in file

my result functions:

```
const rotationInExifImage = async (_base64: string): Promise<number> => {
  const imgArrayBuffer = decode(_base64);
  const orientation = await exif.getOrientation(imgArrayBuffer);
  return orientation?.rotation || 0;
};
```

```
const rotationFromOriginalPhoto = await rotationInExifImage(asset.base64);

let optionsForDrawImage: PDFPageDrawImageOptions;

    if (rotationFromOriginalPhoto === 90) {
      optionsForDrawImage = {
        x: page.getWidth() / 2 - jpgDims.height / 2,
        y: page.getHeight() / 2 + jpgDims.width / 2,
        width: jpgDims.width,
        height: jpgDims.height,
        rotate: {
          type: 'degrees',
          angle: -90,
        },
      };
    } else if (rotationFromOriginalPhoto === 180) {
      optionsForDrawImage = {
        y: page.getHeight() / 2 + jpgDims.height / 2,
        x: page.getWidth() / 2 + jpgDims.width / 2,
        width: jpgDims.width,
        height: jpgDims.height,
        rotate: {
          type: 'degrees',
          angle: -180,
        },
      };
    } else {
      optionsForDrawImage = {
        x: page.getWidth() / 2 - jpgDims.width / 2,
        y: page.getHeight() / 2 - jpgDims.height / 2,
        width: jpgDims.width,
        height: jpgDims.height,
      };
    }

    page.drawImage(_image, optionsForDrawImage);
```

**Comment by akovacevicfs24** [comment]
@ArkanRomanPango 
There is a solution that doesn't require any additional libraries, you can convert the jpg to png before embedding it to the document. Here is the code that works for me:

1. function to convert jpg b64 image to png b64 image:

```javascript
    jpgToPng(b64image) {
        return new Promise((resolve, reject) => {
            const img = new Image();
            img.src = b64Image;

            img.onload = () => {
                const canvas = document.createElement("canvas");
                canvas.width = img.width;
                canvas.height = img.height;
                const ctx = canvas.getContext("2d");
                ctx.drawImage(img, 0, 0);
                const dataURL = canvas.toDataURL("image/png");
                resolve(dataURL);
            };

            img.onerror = reject;
        });
    }
``` 

2. before embedding, check the extension and convert to png if needed:

```javascript

  embedImage(pdfDoc, b64image) {

        if (doc.extension != 'png') {
            b64image= await this.jpgToPng(b64image);
        }

        const image = await pdfDoc.embedPng(imageBytes);
        // ..... do your logic here

  }

```
