### ISSUE TITLE
Look up AcroField by name when it contains an extended character 

### ISSUE THREAD

**Issue by philipjmurphy** [Hopding/pdf-lib#133]
I'm trying to find an AcroField by name, however, when the name of the field is **€** (or it contains an extended character) it can't find it. Digging a bit deeper I can see that it appears to be stored as "þÿ ¬" (looks like a byte order mark and something else). Is there anyway to look up an AcroField by name for such instances (or to stop them being stored as such in the first place)?

BTW, I'm using your look up code as follows:

```
const getAcroFields = pdfDoc => {
  if (!pdfDoc.catalog.getMaybe('AcroForm')) return [];
  const acroForm = pdfDoc.index.lookup(pdfDoc.catalog.get('AcroForm'));

  if (!acroForm.getMaybe('Fields')) return [];
  const acroFields = pdfDoc.index.lookup(acroForm.get('Fields'));

  return acroFields.array.map(pdfDoc.index.lookup);
};

const findAcroFieldByName = (pdfDoc, name) => { // Fails when name is €
  const acroFields = getAcroFields(pdfDoc);

  return acroFields.find(acroField => {
    const fieldName = acroField.getMaybe('T');
    return !!fieldName && fieldName.string === name;
  });
};
```

PS All other look ups work fine.

**Comment by Hopding** [comment]
Hello @philipjmurphy! Can you provide an example document that I can use to reproduce the issue? It should be possible to make the lookup work, but I'll need to play around with a sample document to get it working.

**Comment by philipjmurphy** [comment]
Simple PDF with single field named '€' - look up code will fail to find it.

[euro_field_name.pdf](https://github.com/Hopding/pdf-lib/files/3366267/euro_field_name.pdf)

**Comment by philipjmurphy** [comment]
Just got it working with this code (note: this code is pdf-lib version 1.0+ beta code) - not completely tested, so use with caution.

```
const getAcroFields = async pdfDoc => {
  let pages = await pdfDoc.getPages()
  if (!pdfDoc.catalog.get(PDFName.of('AcroForm'))) return [];
  const acroForm = await pdfDoc.context.lookup(pdfDoc.catalog.get(PDFName.of('AcroForm')));

  if (!acroForm.get(PDFName.of('Fields'))) return [];
  const acroFields = await pdfDoc.context.lookup(acroForm.get(PDFName.of('Fields')));

  return acroFields.array.map((acroField) => pdfDoc.context.lookup(acroField));
};

const findAcroFieldByName = async (pdfDoc, name) => {
  const acroFields = await getAcroFields(pdfDoc);

  return acroFields.find(acroField => {
    const fieldName = acroField.get(PDFName.of('T'))

    let value = fieldName.value

    // If field name is of type PDFHexString it has been encoded as contained extended 
    // unicode characters. Need to decode them now.
    // For example: €_6 may be encoded in hex as "FEFF 20AC 005F 0036". Note,
    // first 4 characters (FEFF) are a 'ZERO WIDTH NO-BREAK SPACE' unicode character that may be
    // ignored.
    if(fieldName instanceof PDFHexString) {
      // Remove any 'ZERO WIDTH NO-BREAK SPACE' unicode characters and split into groups of 4 character.
      let parts = value.replace('FEFF', '').match(/[\s\S]{1,4}/g) || []
      value = ''
      for(let i = 0; i < parts.length; i++) {
        // Reconstruct string.
        value += String.fromCharCode(parseInt(parts[i], 16))
      }
    }

    return !!fieldName && value === name;
  });
};
```
With the above functions written the following may now be used to set an annotation value:

```
  let propertyName = '€'
  let value = '1,000'
  const input = await findAcroFieldByName(pdfDoc, propertyName);
  input.set(PDFName.of('V'), PDFString.of(value))
```

**Comment by philipjmurphy** [comment]
Not quite out of the woods. Tried this again and it didn't work. Eventually, figured out that the first document worked as I had run it through an online service at https://www.sejda.com/pdf-editor which actually automatically converted these field names from PDFString to PDFHexString. So, the field name went from something like "þÿ ¬_6" to "FEFF20AC005F0036" and hence my code worked. Can live with this, but might be nice if pdf-lib could do something similar.

**Comment by philipjmurphy** [comment]
FYI - I've moved away from using AcroField names and am now using their object ids instead. Need to support versions as they may change, however, they are much more reliable and compact. Closing issue.

**Comment by xia0ming** [comment]
hi, my similar problem is  in the 'acroField.set(name, value)', the value is a string which contains an extended character, and the pdf display incorrectly, maybe you can be helpful, thanks

**Comment by Hopding** [comment]
`pdf-lib` now has form creation and filling APIs that should be used instead of the below example(s). See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFForm.getField`](https://pdf-lib.js.org/docs/api/classes/pdfform#getfield) method is of particular relevance to this issue.
