### ISSUE TITLE
[Feature Request]: PDF should decrease in file size after calling `removePage`

### ISSUE THREAD

**Issue by jdbaculard** [Hopding/pdf-lib#140]
Hi

I use PDF-LIB with nodeJS. I've got a PDF File with 2000 pages for 13MB.
I remove 1900 pages (with pdfDoc.removePage(10),pdfDoc.removePage(11),pdfDoc.removePage(12), ...). It's working. it's great but the file size remains the same while only 100 pages remain in the modified file. 

Why ?

Any solution please ? Thanks

**Comment by Hopding** [comment]
Hello @jdbaculard!

The `removePage` method does not delete all of a page's objects from the document. It just removes the reference to the from the page tree (leaving the page's objects intact). The reason for this is that a page can actually be reused. If the objects themselves were deleted, then removing a single page might have unintended side effects elsewhere in the document. And even it it wasn't used multiple times, you may wish to reinsert the page after removing it (for example, [reordering pages](https://github.com/Hopding/pdf-lib/issues/139#issuecomment-513510466)).

That being said, I can certainly see how it would be desirable to actually delete a page's objects from the document, in addition to removing its reference from the page tree. I think it would make sense to add a new method, `PDFDocument.deletePage` that does this.

But, in the meantime, there is a workaround: You can copy the pages you want to keep into a document object. For example, if you want to keep pages 1, 4, and 75:
```js
const originalDoc = await PDFDocument.load(...)
const modifiedDoc = await PDFDocument.create()

const pages = await modifiedDoc.copyPages(originalDoc, [0, 3, 74])
pages.forEach(page => modifiedDoc.addPage(page))

const pdfBytes = await pdfDoc.save()
```

> **NOTE:** This code sample is based on the new v1.0.0 API. This is currently [in beta](https://github.com/Hopding/pdf-lib/issues/134). However, it is stable at this point and will graduate from beta to stable this weekend. So feel free to use it now.

I hope this helps. Please let me know if you have any additional questions!

**Comment by jdbaculard** [comment]
Thank you for your reply.
The copy method is not a good idea for me because each page keeps the logo and each page is 200KB. At the end the total weight of the file is 20MB for 100 pages is much larger than the original file of 2000 pages.

Can I test the deletePage in beta method?

Congratulations for your work.

**Comment by Hopding** [comment]
@jdbaculard Have you tried the page copying approach using the beta version? The current version (0.6.4) has an API flaw that results in duplicate objects being created (hence the large document size). But this has been fixed in the beta version. For example, in 0.6.4 the logo will be copied 2000 times. But in v1.0.0-beta.3 the logo will only be copied once.

The beta version does not currently have a `deletePage` method. This method hasn’t yet been implemented. And it will probably be at least a few weeks until I have time to work on it myself (of course, others are welcome to work on it and submit a PR).

**Comment by jdbaculard** [comment]
Great ! it's works !
Thanks

**Comment by sdfereday** [comment]
@Hopding Grand way of removing pages 👍 Just one thing I noticed (can raise an issue if that's preferred), but after creating the new document it seems to be missing a couple of entries in its catalog that the original document had (such as AcroForm, StructTreeRoot, etc).

Presumably document creation leaves that part up to you? So if I wanted to copy across extra catalog entries from the original, that's allowed?

**Comment by Hopding** [comment]
Reopening this to track it as a feature request. 

@sdfereday Just realized that my comment on https://github.com/Hopding/pdf-lib/issues/159#issuecomment-569318618 isn't applicable as it doesn't delete unused page objects.

**Comment by kevinswartz** [comment]
Hey guys, just wanted to voice my support for this feature.  This would help us out a lot.  Thanks for your great work on this!

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
