### ISSUE TITLE
Feature wish: Inserting raw text in PDF file

### ISSUE THREAD

**Issue by CleyFaye** [Hopding/pdf-lib#141]
We're trying to insert text in a PDF in such a way that the raw text will be visible in the output file (so we can grep on it, something like that).

I have seen this done, so it must be possible. But unfortunately I know too little about the PDF spec to know where to start.

If someone could nudge me in the right direction on how to do that using pdf-lib, it'd be great. I'm planning into looking where the text is transformed and how I could provide a parameter somewhere to avoid that, but if there's a "clean" way to do it, it's probably for the best.

**Comment by Hopding** [comment]
Hello @CleyFaye!

This could be done with a few small changes. However, you would be restricted to using the ASCII character set. Would this still work for your use case? If so, let me know, and I can share an example to demonstrate how this would be done.

**Comment by CleyFaye** [comment]
Yes, that's what we need (we embed some identifier, that happens to be only letters and numbers).
Please show me the way :)

**Comment by Hopding** [comment]
Is your identifier just metadata? Or does it need to be text that is actually rendered on the page? Adding metadata is definitely simpler (and actually frees you up to use more than just the ASCII character set).

**Comment by CleyFaye** [comment]
It have to be rendered; we already put the data in the file itself, but it'd be nicer to have it on the page too. The process is roughly like this: insert a placeholder identifier (exact same size as the final value), and feed the file into a processor that will grep for that, replace it with the proper value, and go on.

At first I thought "nope, we can't do that" (for various reason the final value isn't known when we can process the PDF), but then I found out that there are ways to put some text on a page that would end up raw in the file, and here I am.

**Comment by Hopding** [comment]
@CleyFaye Here's a script that draws ASCII text (in standard fonts) on a page:

```js
import fs from 'fs';
import {
  beginText,
  Color,
  endText,
  PDFContentStream,
  PDFDocument,
  PDFFont,
  PDFPage,
  PDFString,
  rgb,
  setFillingColor,
  setFontAndSize,
  showText,
  StandardFonts,
} from 'pdf-lib';

/**
 * @param font Must be a Standard Font with WinAnsi encoding (e.g. Helvetica)
 * @param text Must be a string of ASCII characters
 */
const drawRawText = (
  page: PDFPage,
  text: string,
  font: PDFFont,
  size: number,
  color: Color,
) => {
  page.setFont(font);
  const operators = [
    beginText(),
    setFillingColor(color),
    setFontAndSize((page as any).fontKey, size),
    showText(PDFString.of(text) as any),
    endText(),
  ];

  const dict = page.doc.context.obj({});
  const contentStream = PDFContentStream.of(dict, operators, false);
  const ref = page.doc.context.register(contentStream);

  page.node.addContentStream(ref);
};

(async () => {
  const pdfDoc = await PDFDocument.create();
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const page = pdfDoc.addPage();
  drawRawText(page, 'Testing...', helveticaFont, 25, rgb(0, 0, 0));

  const pdfBytes = await pdfDoc.save();
  fs.writeFileSync('./out.pdf', pdfBytes);
})();
```
> Note that this script is written in TypeScript. You'll need to remove the type casts and annotations if you are using plain JS.

I hope this helps. Please let me know if you have any additional questions!

**Comment by Hopding** [comment]
I should also state that I'm skeptical about adding this as a feature to `pdf-lib`. It requires disabling the encoding of the content stream that will hold the ASCII text. I'm not sure of a clean way to do this without disabling it for the whole page. It would also require building in the appropriate safeguards to prevent non-ASCII text and non-standard fonts from being used.

That being said, if a large number of people request this feature, then I'll work on figuring out a good way to add it. But I'm hoping that the above script I shared will do the trick for most people that need this sort of thing.

**Comment by CleyFaye** [comment]
Nice, I'll check that monday, thank you!

I also agree that this is a cornercase and most people won't want that. But still it's nice the library provide the low level tools to do so.

**Comment by CleyFaye** [comment]
For information, it works perfectly! I just added an operator for text placement based on other text drawing functions.
