### ISSUE TITLE
Issue for getting page size

### ISSUE THREAD

**Issue by sanjeet-leewayhertz** [Hopding/pdf-lib#147]
HI 
I have tried to get the size of a pdf which width is greater than the height, And I am getting the height as the width and width as the height. How can I get the correct size? Could you guys help me to resolve this? 
I am attaching that pdf.
[D600IN.pdf](https://github.com/Hopding/pdf-lib/files/3442863/D600IN.pdf)

Thanks

**Comment by Hopding** [comment]
Hello @sanjeet-leewayhertz!

It looks like the pages in your document are rotated 90 degrees. But the width and height of the page are defined irrespective of its rotation angle. This is why your width and height appear to be flipped around.

You can access the rotation angle of a page with the [`PDFPage.getRotation`](https://pdf-lib.js.org/docs/api/classes/pdfpage#getrotation) method. I can't say for sure what the right way to handle this is without knowing more about your use case. But here's a potential solution:
```js
function getSizeAdjustedForRotation(page) {
  const size = page.getSize();
  const rotation = page.getRotation().angle;
  const isFlipped = (rotation / 90) % 2 !== 0;
  return isFlipped
    ? { width: size.height, height: size.width }
    : { width: size.width, height: size.height };
}

const { width, height } = getSizeAdjustedForRotation(pdfDoc.getPages()[0])
```

I hope this helps. Please let me know if you have any additional questions!

**Comment by sanjeet-leewayhertz** [comment]
Hi @Hopding 
Thanks for the quick reply. However, I am able to get correct size From the above method.
My use case is to add some images and text to the pdf. After embedding them they are appearing vertically At the wrong coordinates. it might be caused by the rotation of the document. How can I fix this?

Please refer to the attachment for my use case.
![Screen Shot 2019-07-30 at 2 51 48 PM](https://user-images.githubusercontent.com/53079105/62117947-7bbb5500-b2da-11e9-9088-99b47c34cdcf.png)

Thanks

**Comment by Hopding** [comment]
@sanjeet-leewayhertz Here's a sample script that moves the origin of the page back to the lower-left corner (to account for the rotation of the page):
```js
const pdfDoc = await PDFDocument.load(fs.readFileSync('D600IN.pdf'));

const page = pdfDoc.getPages()[0];
const { height } = getSizeAdjustedForRotation(page);

page.drawText('Before', { x: 5, y: 5, size: 50, color: rgb(1, 0, 0) });

// Move the origin back to the lower left corner
page.pushOperators(rotateDegrees(90), translate(0, -height));

page.drawText('After', { x: 5, y: 5, size: 50, color: rgb(0, 1, 0) });

const pdfBytes = await pdfDoc.save();
```

Here's what the first page of the resulting PDF looks like:
![out](https://user-images.githubusercontent.com/10351828/62415784-f810a980-b5f4-11e9-8e32-89f01174dcb5.png)

Does this solve your problem?
