### ISSUE TITLE
build reactjs app (with Pdf-lib package) is not working with php

### ISSUE THREAD

**Issue by Rajkumar4385** [Hopding/pdf-lib#148]
We have created an app with Reactjs. we used pdf-lib to edit pdf in the reaact app. We want to use that app in the PHP application. So build the reactjs app (npm run build) and just copy the built files into php application. But when we open the pdf  through application. we are getting below error :
PDFObject.js:7 Uncaught TypeError: Cannot set property 'clone' of undefined
    at PDFObject.js:7
    at t (PDFStream.js:33)
    at t (PDFContentStream.js:46)
    at new <anonymous> (prototype.js:290)
    at Function.t.of (PDFContentStream.js:142)
    at Function.e.load (PDFDocumentFactory.js:49)
    at o (AutomaticPPt.jsx:31)
    at t.value (AutomaticPPt.jsx:29)
    at prototype.js:290
    at Object.<anonymous> (react-dom.production.min.js:49)  " in PDFObject.js file

**Comment by Hopding** [comment]
Hello @Rajkumar4385!

Can you share some sample code that I can use to reproduce the issue? I’ll need to see what pdf-lib code you have written, as well as any input data you’re using (PDFs, fonts, images, etc...).

**Comment by Rajkumar4385** [comment]
Hello @Hopding ,

I have updated the pdf-lib version to latest and now its working fine.

Thanks

**Comment by Hopding** [comment]
Awesome! Glad you were able to get it working.
