### ISSUE TITLE
PNG images loaded with RNFS cause error "incorrect header check"

### ISSUE THREAD

**Issue by Beeltec** [Hopding/pdf-lib#155]
Hi,

at the moment I'm migrating from react-native-pdf-lib to pdf-lib and ran into an error when I tried to implement a PNG that worked flawlessly with rnpl. I managed to work around the issue by converting the image to JPG, but I'd rather use the original PNG. Here is the code snippet:

    // helper consts
    const marginHorizontal = 68;
    const marginVertical = 45;
    const fontSizeTitle = 18;
    const fontSizeNormal = 12;

    // create document
    const pdfDoc = await PDFDocument.create();

    // embed all pictures into document
    const imagePath = (Platform.OS === 'ios' ? RNFS.MainBundlePath : "images") + "/test.png";
    const imageData = await RNFS.readFile(imagePath, 'base64');
    const image = await pdfDoc.embedPng(imageData);
    const imageDims = image.scale(0.15);

    // create page array and set current page and current y value
    let pages = [pdfDoc.addPage(PageSizes.A4)];
    let currentPage = 0;
    let currentY = Number(pages[currentPage].getHeight() - imageDims.height - (marginVertical * 2));

    // write pdf
    const pdfBytes = await pdfDoc.saveAsBase64();
    const pdfPath = RNFS.TemporaryDirectoryPath + Math.random().toString(36).substring(7) + '.pdf';
    await RNFS.writeFile(pdfPath, pdfBytes, 'base64');
    return pdfPath;

As I said, replacing the PNG with a JPG and embedding it with embedJpg works. I also looked at the base64-string of the file and that looked okay as well.

Best,

**Comment by Hopding** [comment]
Hello @Beeltec!

Can you please share a PNG image that I can use to try and reproduce the issue?

**Comment by Hopding** [comment]
I'm going to close this for now. But please feel free to reopen it if you're still having trouble.
