### ISSUE TITLE
Getting MissingPDFHeaderError.PDFParsingError from a valid PDF

### ISSUE THREAD

**Issue by jwoodrow** [Hopding/pdf-lib#156]
Hi,

I'm currently trying to use `pdf-lib` to inject custom metadata in an existing pdf using a node server for this.

The issue I'm having is that when I try to load my pdf files it fails with the following error
```javascript
Error: Failed to parse PDF document (line:0 col:0 offset=0): No PDF header found at MissingPDFHeaderError.PDFParsingError [as constructor]
```

The pdfs I'm using to test are generated using `pdfkit` and when I try to open them or do some validations with them they show no issues. Just in case here is the code I'm using for this which simply takes an image file's path and a pdf output file path:
```javascript
function(imagePath, pdfPath) {
  const pdf = new pdfkit({ autoFirstPage: false }),
    pdfStream = fs.createWriteStream(pdfPath, {encoding: 'binary'});

  pdfStream.on('finish', function() {
    fs.unlinkSync(imagePath);
  });

  const img = pdf.openImage(imagePath);
  const page = pdf.addPage({ size: [img.width, img.height] });
  pdf.image(img, 0, 0);

  pdf.pipe(pdfStream);
  pdf.end();
}
```

I then try to load this pdf using pdf-lib as such:
```javascript
function(data) {
  const pdfBytes = fs.readFileSync(data.dest);
  PDFDocument.load(pdfBytes)
    .then(function(pdf) {
      // Generating and injecting xmp here
      pdf.save().then(function(newPdf) {
        fs.writeFileSync(data.dest, newPdf);
      })
      .catch(function(err) {
        console.error(err);
      });
    })
    .catch(function(err) {
      console.error(err);
    });
}
```

And it's the `PDFDocument.load(pdfBytes)` catch that prints the  `MissingPDFHeaderError.PDFParsingError`

Any help would be appreciated

**Comment by Hopding** [comment]
Hello @jwoodrow!

What version of Node are you using? Also, can you please modify your code with the following and let me know what is printed out?
```js
function(data) {
  const pdfBytes = fs.readFileSync(data.dest);
  console.log('Type:', typeof(pdfBytes))
  console.log('Is Uint8Array:', pdfBytes instanceof Uint8Array)
  console.log('Head:', String(pdfBytes.subarray(0, 250)))
  PDFDocument.load(pdfBytes).then( ... ).catch( ... );
}
```

**Comment by jwoodrow** [comment]
Thanks for the swift reply, I'm currently using node v12.3.1.

After adding your logs here's the output.

```javascript
Type: object
Is Uint8Array: true
Head:
```

I tried with a pdf not generated using `pdfkit` and got a different output (although I'm still having issues with adding metadata to that file but that's not linked with this issue, I'm having trouble migrating some [code you posted](https://github.com/Hopding/pdf-lib/issues/55#issuecomment-447880119) in an issue that was made for an earlier release (before the 1.0.0))
```javascript
Type: object
Is Uint8Array: true
Head: %PDF-1.3
%����
1 0 obj
<< /Creator <feff0050007200610077006e>
/Producer <feff0050007200610077006e>
>>
endobj
2 0 obj
<< /Type /Catalog
/Pages 3 0 R
>>
endobj
3 0 obj
<< /Type /Pages
/Count 1
/Kids [5 0 R]
>>
endobj
4 0 obj
<< /Length 3382
>>
stream
q
```

If the head part is any indication it would seem there's either an issue with how I'm using `pdfkit` or with `pdfkit` itself

**Comment by jwoodrow** [comment]
Hi @Hopding just to keep you updated, I managed to load pdfs generated using `pdf-lib` so I've decided to fully switch to `pdf-lib`.

I'm now having trouble with adding Metadata into my pdfs encountering the following error:

```javascript
TypeError: key.sizeInBytes is not a function
```

Would you like me to create a new issue for this ?

**Comment by Hopding** [comment]
Hello @jwoodrow. My apologies for the delayed response. Did you make any progress resolving this? If not, please create a new issue with the code you're using to add metadata.
