### ISSUE TITLE
Feature Request: Remove duplicate objects in PDF

### ISSUE THREAD

**Issue by thebenlamm** [Hopding/pdf-lib#157]
I am creating a large PDF document that is essentially the same one PDF page repeated over multiple times with a little bit of text added to each page. The simplified code looks something like this:

```
  const originalPdfBytes = ...
  const pdfDoc = await PDFDocument.create();
  
  const pdfDoc2 = await PDFDocument.load(originalPdfBytes);
  pdfDoc2.getPages()[0].drawText('This is a page', { size: 13, color: rgb(0, 0, 0) });
  const [ copiedPage1 ] = await pdfDoc.copyPages(pdfDoc2, [0]);
  
  pdfDoc.addPage(copiedPage1);
  pdfDoc.addPage(copiedPage1);
  pdfDoc.addPage(copiedPage1);
  await pdfDoc.save();
```

Because each page adds all its own Objects to the new PDF document the size of the new document grows linearly.

Ideally added pages should be able to reuse existing Objects. Adding the same pdf page to the document should only make the final document grow by the size of the additional text and whatever references it needs to refer to the existing objects.

I've dug into this for a few hours now and have an inkling of an idea of the complexity involved. Just wondering if this is something on your roadmap and/or if you could give some pointers on implementing this myself in order to create a PR.

**Comment by thebenlamm** [comment]
If it helps, I wrote this code to find duplicate streams:

```
const fs = require('fs'),
      crypto = require('crypto');

let streamMap = {};

const replace = (buf) => {
    if (!Buffer.isBuffer(buf)) buf = Buffer(buf);
    const streamIdx = buf.indexOf('stream');
    if (streamIdx === -1) return buf;
    const endstreamIdx = buf.indexOf('endstream');

    const before = buf.slice(0, streamIdx+6);
    const stream = buf.slice(streamIdx+6, endstreamIdx);
    
    const digest = crypto.createHash('sha256').update(stream).digest('base64');
    console.log(`Generated hash: ${digest}`);
    if(streamMap[digest]){
        console.log('CRASH!!')
    } else {
        streamMap[digest] = 1;
    }

    const after = replace(buf.slice(endstreamIdx+9));
    return Buffer.concat([ before, Buffer(`\n${digest}\nendstream`), after ]);
}

const document = fs.readFileSync('mypdf.pdf);
fs.writeFileSync('mypdf.txt', replace(document));
```

**Comment by Hopding** [comment]
Hello @thebenlamm! My apologies for the delayed response.

Duplicate object detection would indeed be an interesting and useful feature. It has come up at least [once before](https://github.com/Hopding/pdf-lib/issues/9#issuecomment-415992408). I'd be happy to have a discussion about how best to approach this if you're interested in working on it.

That being said, it doesn't look like the specific code snippet you shared should be generating duplicate objects. This should really only have the potential to happen if you repeatedly call `pdfDoc.copyPages(...)` (which you are not doing). Is the snippet you shared the same code that is  producing large numbers of duplicate objects?

**Comment by thebenlamm** [comment]
Yes, you are right!! 🙈 The code I have above does not create duplicate objects. My source code was much more complex and was adding additional references for each pdf. Updated my code and am not having the problem now.

**Comment by Hopding** [comment]
Hello @thebenlamm! I've provided an updated version of my copy pages example in https://github.com/Hopding/pdf-lib/issues/47#issuecomment-569315318. My apologies for the (very) delayed response. 

I'm planning to create official support for this in the future. Something like `PDFPage.clone()`, perhaps. This is being tracked in https://github.com/Hopding/pdf-lib/issues/169.
