### ISSUE TITLE
NodeJS Usage

### ISSUE THREAD

**Issue by joshua-animas** [Hopding/pdf-lib#158]
I'm having a bit of trouble getting going on Node.

I get `Error: load is not a function`

```
const {PDFDocument} = require('pdf-lib');

const example = (buffer) => {
 const pdfDoc = PDFDocument.load(buffer);
 ...do stuff with pdfDoc...
}
```

Thank you for your time.

**Comment by thebenlamm** [comment]
Not sure if this is the cause of that error message but you need an await before the PDFDocument.load().

`const pdfDoc = await PDFDocument.load(buffer);`

**Comment by Hopding** [comment]
@joshua-animas What version of `pdf-lib` are you using? Make sure it is v1.0.0 or higher.

**Comment by joshua-animas** [comment]
I see a new version was pushed recently. I updated and that fixed it. Thank you!
