### ISSUE TITLE
Invalid PDFs on modification

### ISSUE THREAD

**Issue by davesmithbis** [Hopding/pdf-lib#16]
I cannot get this to work as intended - it always results in a PDF that cannot be opened due to errors.

Even if I run the modification example within the repo, it's the same thing.

Am I missing something? No errors are being generated and the output file is produced but just looks like the resulting PDF is corrupted or something.

Let me know if you need more info.

Thanks.

**Comment by Hopding** [comment]
Can you please share the PDF that you’ve produced by running the modification example? Also, what PDF viewer are you using to view the PDF?

**Comment by davesmithbis** [comment]
Certainly - this is the modified.pdf generated by the document-modification example. I get a similar error if I open it in Acrobat or any of the major browsers.

Any thoughts appreciated as this library looks really promising and just what we need. Thanks!

[modified.pdf](https://github.com/Hopding/pdf-lib/files/2195225/modified.pdf)

**Comment by Hopding** [comment]
I just took a look at the `modified.pdf` file that you shared, and it appears to be a CSV of numbers between 0-255:
```
37,80,68,70,45,49,46,55,10,37,130,130,130,130,10,49,32,48,32,111,98,...
```
---
I wrote a node script to:
1. Parse out these numbers.
2. Push them to an array.
3. Convert that array to a `Uint8Array`.
4. Save the results to a `test.pdf` file.
```javascript
const fs = require('fs')

const bytesCsv = fs.readFileSync('./modified.pdf')

const pdfBytes = []
let currByteChars = ''

for (let i = 0; i < bytesCsv.length; i++) {
  const byteChar = String.fromCharCode(bytesCsv[i])
  if (byteChar === ',') {
    pdfBytes.push(Number(currByteChars))
    currByteChars = ''
  } else {
    currByteChars += byteChar
  }
}

fs.writeFileSync('./test.pdf', new Uint8Array(pdfBytes))
```
---
As it turns out, each number in that CSV is a valid byte in a PDF file. Here's the resulting PDF file: 

[test.pdf](https://github.com/Hopding/pdf-lib/files/2195298/testing.pdf)

**Comment by Hopding** [comment]
Interestingly, if I change the last line of my node script:
```javascript
fs.writeFileSync('./test.pdf', new Uint8Array(pdfBytes))
```
to the following:
```javascript
fs.writeFileSync('./test.pdf', pdfBytes)
```
the resulting `test.pdf` file winds up containing a CSV of numbers again. 

It seems that the `fs.writeFileSync` function in Node handles `Uint8Array` object as one would expect: it saves the `Uint8Arrays`'s contents directly to a file. But when given a "normal" `Array` object filled with numbers, it appears to convert the `Array`'s contents to a CSV of numbers and saves _that_ to the file.

**Comment by Hopding** [comment]
So, long story short, it seems like perhaps your code is trying to save an `Array` to a file, not a `Uint8Array`. Please let me know if this is the case.

If not, can you please share the script you are running so I can play around with it?

**Comment by davesmithbis** [comment]
Thanks @Hopding , appreciate you taking a look at this. Interestingly, even with your suggestions I couldn't get a proper output...

As it turns out, the development environment was running Node v6.x (first thing I should have checked) - I upgraded it to v8 and, of course, it worked. D'oh.

**Comment by Hopding** [comment]
Good to know! I'm glad you got it working 👍 

I took a look at Node's changelog and sure enough, [v7.4.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#2017-01-04-version-740-current-evanlucas) included a change to

> Allow passing Uint8Array to fs methods where Buffers are supported.

Looks like in older version of Node, you just need to wrap the `Uint8Array` in a call to [`Buffer.from()`](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array). So the code would look something like:
```javascript
const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
fs.writeFileSync('./my.pdf', Buffer.from(pdfBytes));
```

This is certainly worth updating the docs and examples with, as I'm sure there are more than enough people running Node <7.4.0 who would get tripped up by this.
