### ISSUE TITLE
[QUESTION] drawImage inside a Circle - Image Clipping using geometric

### ISSUE THREAD

**Issue by Beethoven** [Hopding/pdf-lib#160]
There is a way to drawImage inside an object (ex: circle)?
Or use a object to clip an image?

**Comment by Hopding** [comment]
Hello @Beethoven!

You can indeed do this. Here's an example:
```js
import {
  clipEvenOdd,
  drawEllipsePath,
  endPath,
  PDFDocument,
  popGraphicsState,
  pushGraphicsState,
} from 'pdf-lib';

(async () => {
  const catJpgUrl = 'https://pdf-lib.js.org/assets/cat_riding_unicorn.jpg';
  const catJpgBytes = await fetch(catJpgUrl).then((res) => res.arrayBuffer());

  const pdfDoc = await PDFDocument.create();

  const img = await pdfDoc.embedJpg(catJpgBytes);
  const imgDims = img.scale(0.5);

  const page = pdfDoc.addPage();
  page.pushOperators(
    pushGraphicsState(),
    ...drawEllipsePath({
      x: 225,
      y: page.getHeight() - 100,
      xScale: 100,
      yScale: 100,
    }),
    clipEvenOdd(),
    endPath(),
  );
  page.drawImage(img, { ...imgDims, y: page.getHeight() - imgDims.height });
  page.pushOperators(popGraphicsState());

  const pdfBytes = await pdfDoc.save();
})();
```

Here's the output PDF: [out.pdf](https://github.com/Hopding/pdf-lib/files/3522701/out.pdf)
<img width="803" alt="image" src="https://user-images.githubusercontent.com/10351828/63386392-94161100-c368-11e9-876a-cc98ee0f2239.png">

I hope this helps. Please let me know if you have any additional questions!

**Comment by antonellogatto** [comment]
>     ...drawEllipsePath({
>       x: 225,
>       y: page.getHeight() - 100,
>       xScale: 100,
>       yScale: 100,
>     }),

drawEllipsePath method seems deprecated and it doesn't work. how can it be replaced?

**Comment by antonellogatto** [comment]
> drawEllipsePath

resolved: it can be replaced with drawEllipse (warning it doesn't work if in drawEllipse options is defined borderColor)
