### ISSUE TITLE
Express.js Working Example

### ISSUE THREAD

**Issue by dhollenbeck** [Hopding/pdf-lib#163]
Thank you very much for this amazing lib! Great job!

I would like to use `pdf-lib` in my express.js app. Below is a **working** example of an **express.js** app sending a **Hello World** pdf which Chrome reads just fine. 

**Am I doing things correctly?**

```js
'use strict';

var PdfLib = require('pdf-lib');
var PDFDocument = PdfLib.PDFDocument;
var StandardFonts = PdfLib.StandardFonts;
var rgb = PdfLib.rgb;

var express = require('express');
var app = express();
var port = 3000;

async function createPdf() {
	var pdfDoc = await PDFDocument.create();
	var timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
	var page = pdfDoc.addPage();
	var { width, height } = page.getSize();
	var fontSize = 30;
	page.drawText('Hello World', {
		x: 50,
		y: height - 4 * fontSize,
		size: fontSize,
		font: timesRomanFont,
		color: rgb(0, 0.53, 0.71),
	});
	var pdfBytes = await pdfDoc.save();
        var pdfBuffer = Buffer.from(pdfBytes.buffer, 'binary');
	return pdfBuffer;
}

app.get('/', function(req, res) {
	createPdf().then(function(pdfBuffer) {
		res.status(200);
		res.type('pdf');
		res.send(buffer);
	}).catch(function (err) {
		res.status(500);
		res.send(err.message);
	});
});

app.listen(port, function() {
	console.log(`Example app listening on port ${port}!`);
});

```

**Comment by Hopding** [comment]
Hello @dhollenbeck!

Your implementation looks good to me. Are you running into any problems with this? Or did you just want a sanity check of your code?

**Comment by dhollenbeck** [comment]
The example code above works correctly with no problems. I just posted it in case it helps others. @Hopding your work is awesome. Thank you so much.

**Comment by kimmobrunfeldt** [comment]
Thanks for this example! It seems that by default express doesn't handle Uint8Array nicely and returns the data in a weird format. Solution seems to be to return a Buffer: https://github.com/expressjs/express/issues/2910

**Comment by StillOnMyWay** [comment]
Thank you! I was doing this in a serverless environment, and was wondering what was causing an issue! This works perfectly, even though Buffer is throwing an error in my env.

**Comment by mrtcmn** [comment]
Thank you for solution.

**Comment by PrimaMateria** [comment]
I was already loosing my nerves on this. Thanks, you have saved my sanity.
