### ISSUE TITLE
basic drawLine feature missing

### ISSUE THREAD

**Issue by samezyane** [Hopding/pdf-lib#164]
Basic functionality to draw a line is missing in the PDFPage object.
Can workaround it by using 'drawRect' but it should not be the normal way of doing it.

Great library though and very promising!
Many thanks.

**Comment by Hopding** [comment]
Hello @samezyane! I agree that it would be useful for the [`PDFPage`](https://github.com/Hopding/pdf-lib/blob/master/src/api/PDFPage.ts) class to have a `drawLine` method. If anybody would like to work on this, I'd be happy to accept a PR for it!

**Comment by Hopding** [comment]
Version [`1.1.1`](https://www.npmjs.com/package/pdf-lib/v/1.1.1) is now published. It contains the `PDFPage.drawLine()` method. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.1.1).

You can install this new version with npm:
```
npm install pdf-lib@1.1.1
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@1.1.1/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@1.1.1/dist/pdf-lib.min.js
