### ISSUE TITLE
How to save as pdf in storage?

### ISSUE THREAD

**Issue by SunnySny** [Hopding/pdf-lib#166]
I am try to save pdf file in device storage but shows response as :-> 

Uint8Array(773) [37, 80, 68, 70, 45, 49, 46, 55, 10, 37, 129, 129, 129, 129, 10, 10, 54, 32, 48, 32, 111, 98, 106, 10, 60, 60, 10, 47, 70, 105, 108, 116, 101, 114, 32, 47, 70, 108, 97, 116, 101, 68, 101, 99, 111, 100, 101, 10, 47, 76, 101, 110, 103, 116, 104, 32, 49, 51, 51, 10, 62, 62, 10, 115, 116, 114, 101, 97, 109, 10, 120, 156, 29, 202, 187, 10, 2, 65, 12, 133, 225, 62, 79, 145, 90, 216, 53, 201, 228, 178, 3, 34, 40, 174, 149, 149, 228, 5, 44, 84, …]

Help me save this code as PDF file in device storage as readable form.I am using in react-native.

**Comment by samezyane** [comment]
Hi,
I am doing it this way:
const pdfPath = path.join(yourFolderPath, 'xyz.pdf')
  fs.writeFile(pdfPath, pdfData, err => {
    if (err) return console.log(err.message)
  })

where pdfData is your Uint8Array
Good luck

Saeed

**Comment by Hopding** [comment]
Hello @SunnySny! I'd suggest you take a look at [the example React Native app](https://github.com/Hopding/pdf-lib/tree/master/apps/rn). If you're specifically trying to save a `PDFDocument` to the file system, you can do so with [`rn-fetch-blob`](https://github.com/joltup/rn-fetch-blob). For example:
```js
import { PDFDocument } from 'pdf-lib';
import RNFetchBlob from 'rn-fetch-blob';

const PDF_PATH = `${RNFetchBlob.fs.dirs.DocumentDir}/out.pdf`;

const writePdf = async (pdfDoc: PDFDocument) =>
  RNFetchBlob.fs.writeFile(PDF_PATH, await pdfDoc.saveAsBase64(), 'base64');

(async () => {
  const pdfDoc = await PDFDocument.create();
  await writePdf(pdfDoc)
});
```
You can also [write the PDF in chunks](https://github.com/Hopding/pdf-lib/blob/1d4faa72fb44463c4de10b89396586e835d53c59/apps/rn/src/tests/assets.js#L6-L18), if it happens to be a large one.

I hope this helps. Please let me know if you have any additional questions!
