### ISSUE TITLE
Step-by-Step Run

### ISSUE THREAD

**Issue by maralamir** [Hopding/pdf-lib#167]
Hi,

Could you please kindly tell me how I can run this on a web browser? I have to mention I am new to JavaScript environment. I've been trying to use react native but I kept getting "Module not found: Can't resolve" error. I think I am not calling the yarn command in the correct directory.

**Comment by Hopding** [comment]
Hello @maralamir! There are as many ways to use this module in a browser as there are frameworks and build systems (and there are many). The simplest way to get started is to save the snippet below as an HTML file on your machine, and then open it in your browser.

```html
<html>
  <head>
    <meta charset="utf-8" />
    <script src="https://unpkg.com/pdf-lib"></script>
  </head>

  <body>
    <iframe id="pdf" style="width: 100%; height: 100%;"></iframe>
  </body>

  <script>
    createPdf();
    async function createPdf() {
      const pdfDoc = await PDFLib.PDFDocument.create();
      const page = pdfDoc.addPage([350, 400]);
      page.moveTo(110, 200);
      page.drawText('Hello World!');
      const pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });
      document.getElementById('pdf').src = pdfDataUri;
    }
  </script>
</html>
```

If you can explain a bit more about what environment and framework(s) you are using, perhaps I can provide more assistance.

> P.S. Welcome to the whimsical world of JavaScript!

**Comment by maralamir** [comment]
Hello @Hopding . Thank you for your kind and prompt reply. My final goal is to develop a syncfusion UI component and I would like to have your library integrated as one of my modules. Yes, I have tried your suggested option and it worked. I am looking for a solution that involves npm or yarn so it gives me more flexibility and dev options.

**Comment by Hopding** [comment]
Give this a shot:
```bash
$ mkdir pdf-lib-test
$ cd pdf-lib-test
$ yarn add pdf-lib
yarn add v1.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 5 new dependencies.
info Direct dependencies
└─ pdf-lib@1.0.1
info All dependencies
├─ @pdf-lib/standard-fonts@0.0.4
├─ base64-arraybuffer@0.1.5
├─ pdf-lib@1.0.1
├─ png-ts@0.0.3
└─ tslib@1.10.0
✨  Done in 2.08s
$ echo "
> const fs = require('fs');
> const { PDFDocument } = require('pdf-lib');
>
> (async () => {
>   const pdfDoc = await PDFDocument.create();
>   const page = pdfDoc.addPage();
>   page.drawText('Hello world!');
>   const pdfBytes = await pdfDoc.save();
>   fs.writeFileSync('./out.pdf', pdfBytes);
>   console.log('File written to ./out.pdf');
> })();
> " > index.js
$ node index.js
$ open out.pdf
```
This should generate a PDF file at `pdf-lib-test/out.pdf` and open it in your default PDF viewer.

**Comment by maralamir** [comment]
Thank you so much @Hopding for your example. I ran your example and it works. However, for my purpose, I would want to be able to run the library as a web application and view and edit a pdf file and save the edited pdf as a new pdf. How can I run this library as a web application?
Thanks
