### ISSUE TITLE
Rotate Source PDF File

### ISSUE THREAD

**Issue by gabhishekprdxn** [Hopding/pdf-lib#170]
Hi, 
First of all, I'll say thanks for building this lib. It's very amazing and fulfilling my all requirement.
I just need to rotate pages of the source PDF file and after that override the source PDF file. Is it possible to rotate the existing one source file and after rotating, override to the source file. 

Thanks in Advance!

**Comment by agencia** [comment]
Looks like it is possible 
https://github.com/Hopding/pdf-lib/issues/118#issuecomment-498457224

**Comment by Hopding** [comment]
Hello @gabhishekprdxn! Rotating a page is indeed possible. See https://pdf-lib.js.org/docs/api/classes/pdfpage#setrotation. 

As far as overwriting the source file, that depends on the environment you're running in. If you're using NodeJS, you would just need [`save()`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#save) the `PDFDocument` after rotating the page. You can then overwrite the original file with the resulting bytes.

I hope this helps. Please let me know if you have any additional questions!

**Comment by chenliyang1024** [comment]
Hi there I rotate the page with `page.setRotation(degrees(0))`, however, the page got rotated, but the content didnt get rotated. Any suggestion?

**Comment by awolad** [comment]
@chenliyang1024 Yes, it also not working for me with a non searchable PDF.
