### ISSUE TITLE
[Feature Request]: Support for Digital Signatures

### ISSUE THREAD

**Issue by kevin8479** [Hopding/pdf-lib#172]
Hi Guys--here is a feature for your consideration...would really, really, love to have it!   I suspect it would not be too easy, but I figure I would ask.
This link provides high level information on digital signatures in pdf:
https://www.adobe.com/devnet-docs/acrobatetk/tools/DigSigDC/Acrobat_DigitalSignatures_in_PDF.pdf

This link provides samples including a pdf with attached signature:
https://uwaterloo.ca/onbase/help/sample-pdf-documents

You will notice when you open the attached document in adobe reader it shows the signature panel.

Let me know if you need anymore details.

**Comment by scottie-schneider** [comment]
Yes please, been trying to figure this out for weeks.

**Comment by dhollenbeck** [comment]
For a technical introduction to digital signatures and how they are implemented in iText please read
[digitalsignatures20130304 2.pdf](https://github.com/Hopding/pdf-lib/files/3591561/digitalsignatures20130304.2.pdf)

**Comment by hotuy** [comment]
I have same problem, when i draw new image to my pdf file, and submit it to server and sign, result file isn't signed, but when i don't add image, result my file is signed. Please help me !

**Comment by Hopding** [comment]
Hello @kevin8479 @scottie-schneider @hotuy! Support for digital signatures is increasingly on my radar for `pdf-lib`. I've received _**many**_ issues, comments, and emails asking about this. And they certainly aren't slowing down! They're increasing, in fact. 

I'm going to be constructing a roadmap for `pdf-lib` in the coming days, and this will be on it in some shape/form. I think the highest priorities for the roadmap are support for encryption, AcroForms, and digital signatures (in no particular order). Although, AcroForm support and digital signatures are somewhat related, as signature fields are typically added as part of an AcroForm.

I'm not sure exactly how this will look. Whatever I end up doing, it will need to work in all JavaScript environments - not just NodeJS. Many of the questions I receive about digital signatures involve using `pdf-lib` in combination with `node-signpdf` to apply a signature to a new or existing document. So it may be that I'll just make some changes to `pdf-lib` that allow it to be used more easily with `node-signpdf`. Or perhaps I'll try to incorporate logic from `node-signpdf` directly into `pdf-lib` (though at the moment, this seems less likely). I'm not sure if `node-signpdf` has any native dependencies though. If it does, then it certainly can't be directly dropped into `pdf-lib`. Its name implies a native dependency, but after a brief overview of the code, I didn't actually spot any node-specific stuff.

**Comment by hotuy** [comment]
Hi @Hopding,
But i don't want using node-signpdf to this pdf-lib, it's from client slide, i only want to talk that when i add image to my pdf from Angular client by `pdf-lib`, after that, i submit pdf bytes to server golang, finally golang server using `unidoc` to sign my file with cert on server. But not success. Because had problem with new files created by pdf-lib.
Thanks.

**Comment by Hopding** [comment]
@hotuy This issue is tracking a feature request, so it's not a great place to discuss your problem. Would you please open a new issue describing your problem in detail? Please include the following:
* A careful description of your problem and how it relates to `pdf-lib`.
* The errors/stacktraces you are observing (either client or server side).
* Sample documents that illustrate your problem.

**Comment by hotuy** [comment]
ok @Hopding , i will open new issue, tks you.

**Comment by MarcGodard** [comment]
This can be related with https://github.com/Hopding/pdf-lib/issues/371

**Comment by dotob** [comment]
having this would be awesome. is there anyway do help with a donation?

**Comment by kevin8479** [comment]
Sorry Andrew--I have not followed this issue and am a little late replying:).  I took a different path on signatures.  I used an existing pdf library written in C++ and compiled it to web assembly along with openssl crypto lib.  At this point I do have LTV signatures, without timestamps however.  

These signatures do require an HSM so actual signing requests have to be fulfilled by a third party.  I forward the signing requests to google HSM.  A similar approach was taken (except with java) and documented in this article:  https://medium.com/google-developers/digital-signatures-how-sleek-leverages-cloud-hsm-to-guarantee-the-integrity-of-legal-documents-a7bd3b82faf6

**Comment by idanlo** [comment]
Can we have an update regarding this? I'm having trouble signing a PDF that was created with pdf-lib with node-signpdf, so having this functionality built in to this library would be great.

**Comment by therpobinski** [comment]
Hi for those who want to implement `pdf-lib` with `node-signpdf`. I mention that I have created a [fork](https://github.com/therpobinski/node-signpdf) of `node-signpdf` with some solutions from this library. But I have used `pdf-lib` to add the visible text in the pdf and it works for the first signature, but not for a second or more. I have noticed that `pdf-lib` does not meet the rules for incremental modification of PDF. I explain this in more detail in this [issue](https://github.com/Hopding/pdf-lib/issues/816#issuecomment-815187179).
Do you have any ideas to solve this problem? With this, I think the `pdflib` library is perfect to use with `node-sign pdf`

**Comment by aashishvanand** [comment]
Hi, Any updates on this? 
@therpobinski By any chance did you get it working using node-signpdf and pdf-lib

**Comment by Cuervo20** [comment]
> Hola para aquellos que quieran implementar `pdf-lib`con `node-signpdf`. He mencionado que he creado un [tenedor](https://github.com/therpobinski/node-signpdf) de `node-signpdf`algunas soluciones de esta biblioteca. Pero he usado `pdf-lib`para agregar el texto visible en el pdf y funciona para la primera firma, pero no para un segundo o más. He notado que `pdf-lib`no cumple con las reglas para la modificación incremental de PDF. Explico esto con más detalle en este [número](https://github.com/Hopding/pdf-lib/issues/816#issuecomment-815187179) .
> ¿Tiene alguna idea para solucionar este problema? Con esto, creo que la `pdflib`biblioteca es perfecta para usar con`node-sign pdf`

Hi, you can update the node-signpdf branch to be able to do the process with a single signature, thanks

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by insinfo** [comment]
Hi, Any updates on this?
