### ISSUE TITLE
[Feature Request]: `backgroundColor` option for `drawText`

### ISSUE THREAD

**Issue by fletchsod-developer** [Hopding/pdf-lib#174]
This is a would be nice to have enhancement but it is not a priority.

The drawText method as part of the addPage (PDFDocument) have json properties for x, y, size, font, color, etc.  Why not add the background color, this can either be a normal PDF feature or a debugging feature to see the actual drawing of the text so we would know if it's is offset too much or something.

This is what I did with PDFClown in the past when there's issue with positioning of the text.

Just an idea here.  So, not a priority here so no hurry.

**Comment by Hopding** [comment]
Hello @fletchsod-developer! I agree that this would be a useful feature, especially for debugging purposes. If anybody would like to submit a PR for this, I'd be happy to merge it!

**Comment by PatrikAarnivaara** [comment]
Sorry if this is not the right issue for this question, but I think it is the closest to what I am looking for. I have attached an image and wonder if it is possible to add a background to a drawText object. 

![Screenshot from 2022-03-15 09-33-32](https://user-images.githubusercontent.com/56720091/158338637-4ad39360-cc7c-43c2-8659-9915cf8e6256.png)

**Comment by SH-Programer** [comment]
Please add background color to the properties of drawtext.

The background color of the text is desperately needed.
