### ISSUE TITLE
HTML to PDF Support

### ISSUE THREAD

**Issue by SarvM** [Hopding/pdf-lib#176]
Thanks for your effort in creating such great javascript pdf library. Is it possible to provide support to convert a html page to pdf?

**Comment by Hopding** [comment]
Hello @SarvM! I'm afraid converting HTML into PDF is a pretty large task and is outside the scope of this library. Of course, if an enterprising individual wanted to create such a library, pdf-lib could certainly be used as the underlying PDF engine.
