### ISSUE TITLE
How can i getting started pdf-lib in Window environment?. Please help me!

### ISSUE THREAD

**Issue by namly5036** [Hopding/pdf-lib#18]
How can i getting started pdf-lib in Window environment. Please help me!

Thanks!

**Comment by Hopding** [comment]
Hi @namly5036. Can you clarify the exact problem you're encountering? Are you trying to use `pdf-lib` as a library for a JavaScript program running on Windows? Or are you trying to build and develop the source code for `pdf-lib` on Windows?

**Comment by Hopding** [comment]
I'm happy to provide whatever help I can, but I'm unable to do so without more information. I'm going to go ahead and close this issue for now. But feel free to reopen it if you're still having trouble.
