### ISSUE TITLE
How to do line break while using drawText method

### ISSUE THREAD

**Issue by khanhubgit** [Hopding/pdf-lib#182]
I am inserting new page into an existing pdf, I did this part. I also added some text with **drawText()** method, but now I am in need of an automatic **line break** if the text is too long. Thanks

**Comment by Hopding** [comment]
Hello @khanhubgit! 

Currently, line wrapping requires a bit of manual effort. You must use the [`PDFFont.widthOfTextAtSize()`](https://pdf-lib.js.org/docs/api/classes/pdffont#widthoftextatsize) method to determine when to insert a line break.

However, @multiplegeorges has done some great work to [add a `maxWidth` option](https://github.com/Hopding/pdf-lib/pull/173) when drawing text. This feature hasn't yet been merged into pdf-lib. It'll probably be a few days or maybe weeks before this happens. But in the meantime, please feel free to pull it into your own codebase by extending `PDFPage` or manually additing the method to its prototype (also see https://github.com/Hopding/pdf-lib/issues/168).

I hope this helps. Please let me know if you have any additional questions!
