### ISSUE TITLE
Flip content

### ISSUE THREAD

**Issue by xSAVIKx** [Hopding/pdf-lib#183]
Hello!

I have an issue that I wasn't able to solve using the available tools: I need to draw text on the PDF that is flipped both horizontally and vertically.

I can flip the text vertically using `rotate: 180` or using `font: -14`. But how to flip it horizontally?

**Comment by Hopding** [comment]
Hello @xSAVIKx! 

You'll need to alter the graphics state with some low-level operators ([`scale`](https://pdf-lib.js.org/docs/api/#const-scale) and [`translate`](https://pdf-lib.js.org/docs/api/#const-translate)) to achieve this effect. I've created an example demonstrating how to do this:

```js
import {
  degrees,
  PDFDocument,
  popGraphicsState,
  pushGraphicsState,
  rgb,
  scale,
  translate,
} from 'pdf-lib';

const red = rgb(1, 0, 0);
const green = rgb(0, 1, 0);
const blue = rgb(0, 0, 1);
const yellow = rgb(0.85, 0.85, 0.25);

const dims = { width: 200, height: 200 };
const center = { x: dims.width / 2, y: dims.height / 2 };

(async () => {
  const pdfDoc = await PDFDocument.create();

  const page = pdfDoc.addPage([dims.width, dims.height]);

  // Normal
  page.drawText('Foobar', { ...center, rotate: degrees(0), color: red });

  // Rotated 180 degrees about origin
  page.drawText('Foobar', { ...center, rotate: degrees(180), color: green });

  // Flipped over x axis
  page.pushOperators(
    pushGraphicsState(),
    scale(1, -1),
    translate(0, -dims.height),
  );
  page.drawText('Foobar', { ...center, rotate: degrees(0), color: yellow });
  page.pushOperators(popGraphicsState());

  // Flipped over x axis and rotated 180 degrees about origin
  page.pushOperators(
    pushGraphicsState(),
    scale(1, -1),
    translate(0, -dims.height),
  );
  page.drawText('Foobar', { ...center, rotate: degrees(180), color: blue });
  page.pushOperators(popGraphicsState());

  const pdfBytes = await pdfDoc.save();
})();
```

Here's the resulting file: [out.pdf](https://github.com/Hopding/pdf-lib/files/4003510/out.pdf)

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/71491567-fc816d00-27f6-11ea-9d9e-d9109d77e48a.png" alt="output file" height="400">
</kbd>

>

I hope this helps. Please let me know if you have any additional questions!
