### ISSUE TITLE
[Feature Request]: embedPdf, drawPdf

### ISSUE THREAD

**Issue by BoLaMN** [Hopding/pdf-lib#184]
allowing of drawing multiple pdfs into 1 page like jpeg and pngs 

[draw-pdf.pdf](https://github.com/Hopding/pdf-lib/files/3584195/draw-pdf.pdf)

[https://github.com/galkahana/PDF-Writer/wiki/PDF-Embedding](https://github.com/galkahana/PDF-Writer/wiki/PDF-Embedding)

**Comment by webdesq** [comment]
I'm also interested in such a feature; the current method using copyPages() from a donor PDF works, but does not allow a donor page to be 'drawn' over an existsing page in target document. In my case, I need to draw an advertorial page 'full scale' in my target page. The target page has different dimensions (but same ratio) as donor page.

**Comment by Hopding** [comment]
Hello @BoLaMN and @webdesq! I agree that this would be a useful feature. It shouldn't be terribly difficult to implement either. Most of the necessary supporting code already exists in the pdf-lib codebase. It'd mostly be a matter of putting the pieces together.

If anybody would like to create a PR for this, I'd be happy to provide advice and answer questions! Otherwise I'll get around to this after fixing some of the outstanding bugs and higher priority issues.

**Comment by 4rlekin** [comment]
Hey, could anyone help me and point me to the relevant part of codebase for rendering this pdf's?
(Hopding mentioned that some supporting code for this is mostly done).
I'd be happy to try and implement this for the project Im working on and then backport it to lib with PR.

**Comment by Hopding** [comment]
@4rlekin I'd suggest taking a look at #348 where @tessi has made some great progress on implementing this.

**Comment by Hopding** [comment]
Version [`1.4.0`](https://www.npmjs.com/package/pdf-lib/v/1.4.0) is now published. It contains PDF embedding support thanks to @tessi! (see [this example](https://github.com/Hopding/pdf-lib/tree/b693c81a5f05f4aef5633abba4d6d5c71f7c9305#embed-pdf-pages)). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.4.0).

You can install this new version with npm:

```
npm install pdf-lib@1.4.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.4.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.4.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.4.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.4.0/dist/pdf-lib.min.js
