### ISSUE TITLE
Update Read Me - RE: createContentStream

### ISSUE THREAD

**Issue by JLuboff** [Hopding/pdf-lib#188]
With the update to 1.0.x from 0.6.x I found myself unable to find anything in the update Read Me in regards to `createContentStream`. I believe there should be something in the Migrating to v1.0.0 part of the documentation to include the exclusion of `createContentStream`

**Comment by salgadohp** [comment]
I agree with you. Were you able to upgrade the lib?

**Comment by Hopding** [comment]
Hello @JLuboff and @salgadohp! I'm open to mentioning this in the migration section of the README. I'm not too sure what would be most useful to add though. Do you have any thoughts or suggestions? 

I should mention that previous versions of `pdf-lib` relied heavily on the `createContentStream` method for a number of things (e.g. drawing shapes, text, and images). The APIs for doing each of these things changed substantially in version `1.0.0`. The new approaches are documented in the [Usage Examples](https://github.com/Hopding/pdf-lib#usage-examples) section of the README.

Please do let me know what you think would be most helpful for users looking to migrate!

**Comment by JLuboff** [comment]
Hi @Hopding, I just took a look at my commit history to see what I had to change (it's been a little while 😄 ). Correct me if I'm wrong, but it seems you used to have to call on `createContentStream` and pass in `drawText`, where as now you call `drawText` directly on the page? If that's right, than I would just perhaps mention that (in better wording heh) in the migration section.

**Comment by Hopding** [comment]
@JLuboff That is correct. I'll update the README to mention that 👍
