### ISSUE TITLE
Merge/Inserting New PDF

### ISSUE THREAD

**Issue by kenzmca86** [Hopding/pdf-lib#189]
Hi Team, Is that possible to merge two existing base64 Url string into one file? If there is a way to do then send me the samples. otherwise how to insert Created page with my existing base64 string or else how to convert pdf pages with my existing base64 string,  Thanks for you help.

**Comment by Hopding** [comment]
Hello @kenzmca86! This is certainly possible. I've explained how to merge two documents in https://github.com/Hopding/pdf-lib/issues/252#issuecomment-566063380. I've adapted my example slightly for your specific question (merging existing documents stored as base64 data URIs):
```js
const mergedPdf = await PDFDocument.create();

const pdfA = await PDFDocument.load(base64DataUriA);
const pdfB = await PDFDocument.load(base64DataUriB);

const copiedPagesA = await mergedPdf.copyPages(pdfA, pdfA.getPageIndices());
copiedPagesA.forEach((page) => mergedPdf.addPage(page));

const copiedPagesB = await mergedPdf.copyPages(pdfB, pdfB.getPageIndices());
copiedPagesB.forEach((page) => mergedPdf.addPage(page));

const mergedPdfFile = await mergedPdf.save();
```
Note that this example assumes `base64DataUriA` and `base64DataUriB` each contain a string that looks something like the following (or any other data format supported by [`PDFDocument.load`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#static-load)):
```
data:application/pdf;base64,JVBERi0xLjcKJYG...
```

I hope this helps. Please let me know if you have any additional questions!
