### ISSUE TITLE
Can pdf-lib use with PDF.js and create annotations to view using PDF.js

### ISSUE THREAD

**Issue by ishanuda** [Hopding/pdf-lib#191]
Hi,
I would like to know the following using the pdf-lib.

01. Can I use PDF.js's raw data to load the existing PDF documents using the following function?
    ```js
    // Load a PDFDocument from the existing PDF bytes
    const pdfDoc = await PDFDocument.load(existingPdfBytes)  // <-- (PDF.js's raw data)
    ```
02. Can I use the pdf-lib to create annotations and save the PDF documents to view the 
created annotations by PFD.js library.

Please be kind enough to guide me through the following questions to a solution.
If there is any guide or documentation please direct me there.

regards.

**Comment by therpobinski** [comment]
Hi, 

1. These are the 3 possibilities that the `load` function supports. [here](
https://pdf-lib.js.org/docs/api/classes/pdfdocument#static-load)
2. To create annotations, you can use the function [drawtext](https://pdf-lib.js.org/docs/api/#const-drawtext), an example of how to use this in the API examples. [Here] (https://pdf-lib.js.org/#examples), in the Modify Document section.

**Comment by Hopding** [comment]
Hello @ishanuda! 
1. I'm not sure what you mean by "PDF.js's raw data". However, as @therpobinski mentioned, the `PDFDocument.load()` method is documented [here](https://pdf-lib.js.org/docs/api/classes/pdfdocument#static-load). I'd encourage you to create a quick script and try it out to know for sure.
2. You certainly can. Here's an example of creating a link annotation: https://github.com/Hopding/pdf-lib/issues/161#issuecomment-523186749. You can create other types of annotations as well, such as markup, text, redaction, etc...

I hope this helps. Please let me know if you have any additional questions!

**Comment by kevinbeal** [comment]
I can confirm this is possible. The `PdfDocumentProxy` object from PDF.js has a `.getData()` method. The value resolved there is a `Uint8Array` and can be fed directly into `PDFDocument.load(data)` as described above.

If you want to make changes to the document and re-render it, you can get the encoded `Uint8Array` value for the PDF document that was changed via `PDFDocument.prototype.save()` and put that straight into `getDocument(data)` from PDF.js.

I'm base64 encoding the `Uint8Array` value prior to giving it to `getDocument(data)` via the below function, but I'm unsure this is actually necessary:

```typescript
export function encodeTypedArray(rawData: Uint8Array): string {
    return btoa(
        rawData.reduce(function (data, byte) {
            return data + String.fromCharCode(byte);
        }, "")
    );
}
```

The signature for `getDocument()` says it can take `Unit8Array` values, so this is probably pointless work on my end.

**Comment by ishanuda** [comment]
Hi @therpobinski, @Hopding,  @kevinbeal,

Thank you very much for your guidance.

I will try the possibilities and get back to you.
Regards

**Comment by yc-cui** [comment]
> I can confirm this is possible. The `PdfDocumentProxy` object from PDF.js has a `.getData()` method. The value resolved there is a `Uint8Array` and can be fed directly into `PDFDocument.load(data)` as described above.
> 
> If you want to make changes to the document and re-render it, you can get the encoded `Uint8Array` value for the PDF document that was changed via `PDFDocument.prototype.save()` and put that straight into `getDocument(data)` from PDF.js.
> 
> I'm base64 encoding the `Uint8Array` value prior to giving it to `getDocument(data)` via the below function, but I'm unsure this is actually necessary:
> 
> ```ts
> export function encodeTypedArray(rawData: Uint8Array): string {
>     return btoa(
>         rawData.reduce(function (data, byte) {
>             return data + String.fromCharCode(byte);
>         }, "")
>     );
> }
> ```
> 
> The signature for `getDocument()` says it can take `Unit8Array` values, so this is probably pointless work on my end.

Hi @kevinbeal. Is it possible to provide interative options when annotating pdf? For example, If I want to draw a rectangle using `pdf-lib`, how to display it on the canvas that `pdf.js` rendered when I am drawing?

**Comment by kevinbeal** [comment]
> Hi @kevinbeal. Is it possible to provide interative options when annotating pdf? For example, If I want to draw a rectangle using `pdf-lib`, how to display it on the canvas that `pdf.js` rendered when I am drawing?

I don't think there is a performant option here with pdf-lib and pdf.js alone. Every time you want to repaint, you'll have get the buffer for that edited pdf-lib object and send it to pdf.js to render it. I imagine that it would be very slow to do (especially if you (de)serialize the document), but I could be wrong.

pdf-lib has a method to get the buffer for the document, and pdf.js has a method for receiving a buffer. But you may have to have some layer on top of pdf-lib & pdf.js that handles the drawing and rendering and syncs up those changes at some inconstant rate or on some event.

What I was trying for a period was handling the drawing with canvas with a transparent background over the pdf.js-rendered document. Then I would take the drawing data I had and created an annotation in pdf-lib and added it to the document when a "save" button was clicked. I abandoned the project though and never got it working fully.

**Comment by yc-cui** [comment]
> What I was trying for a period was handling the drawing with canvas with a transparent background over the pdf.js-rendered document. Then I would take the drawing data I had and created an annotation in pdf-lib and added it to the document when a "save" button was clicked.

That sounds like a good idea!  A transparent canvas background can be used for showing and editing annotations. That means we should make a great interaction between the two sides:

### canvas and pdf-lib 
We can add or edit drawing data with canvas. It should be converted to annotaitons  through pdf-lib after a "save" button was clicked as you said.

### pdf.js and canvas
As for opening a pdf with annotations, we can get them through pdf.js Annotation Layer(Maybe pdf-lib can do the same). Then to make it editable, we should convert them to canvas element.

All in all, the transparent  canvas plays a role as a middle layer so that users can add and edit annotations. Is that right? 
btw, why you abandoned this project? Is that too difficlut to complete or is it simply not possible?
