### ISSUE TITLE
Cannot import `fontkit` from @pdf-lib/fontkit

### ISSUE THREAD

**Issue by Pomelool** [Hopding/pdf-lib#195]
I am building an Angular project and trying to import fontkit as described in the README instruction. 
`import fontkit from '@pdf-lib/fontkit'` gives an error that says `Module '"/node_modules/@pdf-lib/fontkit/fontkit"' has no default export.`
I tried using `import * as fontkit from '@pdf-lib/fontkit'`, and this error does go away, but instead when I am registering this fontkit and using my custom font, it gives the error that says `fontkit.create is not a function.`
What I want to achieve is to write my Chinese characters on the pdf. How should I import this `fontkit` and use it correctly?

![image](https://user-images.githubusercontent.com/14008272/65392192-f97e6880-dd3f-11e9-85df-f52d6a8c93fd.png)

**Comment by Hopding** [comment]
Hello @Pomelool! You can add `"esModuleInterop": true` or `"allowSyntheticDefaultImports": true` to the `"compilerOptions"` section of your Angular project's `tsconfig.json` file. For example:
```diff
 {
   "compileOnSave": false,
   "compilerOptions": {
+    "esModuleInterop": true,
     "baseUrl": "./",
     "outDir": "./dist/out-tsc",
```
or
```diff
 {
   "compileOnSave": false,
   "compilerOptions": {
+    "allowSyntheticDefaultImports": true,
     "baseUrl": "./",
     "outDir": "./dist/out-tsc",
```
I hope this helps. Please let me know if you have any additional questions!

**Comment by bensadia-med** [comment]
Hi there i have the same problem in a Vuejs + electron app which I create a function that handle the pdf creation with custom font and i used pdf-lib/fontkit but it renders an error, so can i 

`
const { PDFDocument, StandardFonts, rgb } = require("pdf-lib");
const fontkit = require("@pdf-lib/fontkit");
const fs = require("fs");

module.exports = async function() {
  console.log('hello mother fucker')
  const url = 'src/services/Scheherazade-Bold.ttf'
  const fontBytes = fs.readFileSync(url);
  // const font = fontkit.create(fontBytes);
  console.log('hello mother fucker0')
  const pdfDoc = await PDFDocument.create();
  console.log('hello mother fucker1')
  pdfDoc.registerFontkit(fontkit);
  console.log('hello mother fucker2')
  const customFont = await pdfDoc.embedFont(fontBytes);
  console.log('hello mother fucker3')
  const page = pdfDoc.addPage();
  const text = "مرحبا يا عالم؟";
  const textSize = 35;
  const textWidth = customFont.widthOfTextAtSize(text, textSize);
  const textHeight = customFont.heightAtSize(textSize);

  page.drawText(text, {
    x: 40,
    y: 450,
    size: textSize,
    font: customFont,
    color: rgb(0, 0.53, 0.71),
  });
  page.drawRectangle({
    x: 40,
    y: 450,
    width: textWidth,
    height: textHeight,
    borderColor: rgb(1, 0, 0),
    borderWidth: 1.5,
  });

  fs.writeFileSync("./public/test.pdf", await pdfDoc.save());
};
`
it produces this error :
<img width="640" alt="Screenshot 2021-04-25 at 3 29 15 PM" src="https://user-images.githubusercontent.com/20243089/115997501-3a54f800-a5db-11eb-9f7d-76214499a014.png">

**Comment by tomhill991** [comment]
I'm also 

> Hi there i have the same problem in a Vuejs + electron app which I create a function that handle the pdf creation with custom font and i used pdf-lib/fontkit but it renders an error, so can i
> 
> `
> const { PDFDocument, StandardFonts, rgb } = require("pdf-lib");
> const fontkit = require("@pdf-lib/fontkit");
> const fs = require("fs");
> 
> module.exports = async function() {
> console.log('hello mother fucker')
> const url = 'src/services/Scheherazade-Bold.ttf'
> const fontBytes = fs.readFileSync(url);
> // const font = fontkit.create(fontBytes);
> console.log('hello mother fucker0')
> const pdfDoc = await PDFDocument.create();
> console.log('hello mother fucker1')
> pdfDoc.registerFontkit(fontkit);
> console.log('hello mother fucker2')
> const customFont = await pdfDoc.embedFont(fontBytes);
> console.log('hello mother fucker3')
> const page = pdfDoc.addPage();
> const text = "مرحبا يا عالم؟";
> const textSize = 35;
> const textWidth = customFont.widthOfTextAtSize(text, textSize);
> const textHeight = customFont.heightAtSize(textSize);
> 
> page.drawText(text, {
> x: 40,
> y: 450,
> size: textSize,
> font: customFont,
> color: rgb(0, 0.53, 0.71),
> });
> page.drawRectangle({
> x: 40,
> y: 450,
> width: textWidth,
> height: textHeight,
> borderColor: rgb(1, 0, 0),
> borderWidth: 1.5,
> });
> 
> fs.writeFileSync("./public/test.pdf", await pdfDoc.save());
> };
> `
> it produces this error :
> <img alt="Screenshot 2021-04-25 at 3 33 20 PM" width="640" src="https://user-images.githubusercontent.com/20243089/115997647-cb2bd380-a5db-11eb-90da-8a3a3deb4c59.png">

I'm also running into this issue with a node application. Any idea why?

**Comment by btielen** [comment]
I ran also into this problem in a browser environment. In Node everything worked fine. Setting `"allowSyntheticDefaultImports": true` didn't fix it for me. I forked the project and changed how it's being published on npm. This fixed everything for me.

```js
import { PDFDocument } from 'pdf-lib';
import * as fontkit from '@btielen/pdf-lib-fontkit';

const pdfDoc = await PDFDocument.create()
pdfDoc.registerFontkit(fontkit)
```

Maybe this helps anyone else.

**Comment by alealima** [comment]
@btielen thanks a ton! Fixed everything for me as well.

**Comment by SanjidHaque** [comment]
@btielen Thanks! After trying everything, this fixed the issue

**Comment by deepbytelab** [comment]
> I ran also into this problem in a browser environment. In Node everything worked fine. Setting `"allowSyntheticDefaultImports": true` didn't fix it for me. I forked the project and changed how it's being published on npm. This fixed everything for me.我在浏览器环境中也遇到了这个问题。在Node中，一切都很好。设置 `"allowSyntheticDefaultImports": true` 并没有为我解决这个问题。我分叉了这个项目，并改变了它在npm上的发布方式。这为我解决了一切。
> 
> import { PDFDocument } from 'pdf-lib';
> import * as fontkit from '@btielen/pdf-lib-fontkit';
> 
> const pdfDoc = await PDFDocument.create()
> pdfDoc.registerFontkit(fontkit)
> Maybe this helps anyone else.也许这对其他人有帮助。

Using the solution you provided, this problem still occurs on my end
