### ISSUE TITLE
Draw Text with fixed Width

### ISSUE THREAD

**Issue by ithillel-aminev** [Hopding/pdf-lib#20]
Hi, guys. That would be great if you to add drawing text with fixed width so that the text would wrap the next lines.

**Comment by Hopding** [comment]
Hello @ithillel-aminev. I agree that this would be useful. It's a feature I plan implement in `pdf-lib` eventually. 

In the mean time, however, you should be able to accomplish this manually if you're willing to do a bit of of work. I've explained how to center and right-align text on a page here: https://github.com/Hopding/pdf-lib/issues/10. In that thread, I include code for measuring a string of text. Once you're able to do this, it should be easy enough to manually wrap your lines when they exceed your desired line length.

Please let me know if this doesn't work for you, or you have additional questions!

**Comment by ithillel-aminev** [comment]
Thank you a lot

**Comment by Hopding** [comment]
Happy to help!

I'm going to close this for now. Feel free to reopen it if you have additional questions 👍

**Comment by ithillel-aminev** [comment]
Now I'm trying to wrap a text into lines and experience a problem with setting \n elements (\r or \r\n) in my test string literal. The result is the string is not wrapped and the \n elements are just drawn instead.

**Comment by Hopding** [comment]
Version [`0.6.0`](https://www.npmjs.com/package/pdf-lib/v/0.6.0) is now published. It adds new methods to measure the width and height of text in standard and embedded fonts ([example](https://github.com/Hopding/pdf-lib/blob/master/examples/measuring_text/node/index.js)). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.6.0).

You can install this new version with npm:
```
npm install pdf-lib@0.6.0
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.0/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.0/dist/pdf-lib.min.js

**Comment by rehman-ahmad-nbs** [comment]
> Version [`0.6.0`](https://www.npmjs.com/package/pdf-lib/v/0.6.0) is now published. It adds new methods to measure the width and height of text in standard and embedded fonts ([example](https://github.com/Hopding/pdf-lib/blob/master/examples/measuring_text/node/index.js)). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.6.0).

Example link isn't working

**Comment by Hopding** [comment]
@rehman-ahmad-nbs Here's the corresponding link for the current version of pdf-lib: https://github.com/Hopding/pdf-lib#embed-font-and-measure-text

**Comment by raphaelvazuso** [comment]
Here is a function to break lines with a width given
`function fillParagraph(text, font, fontSize, maxWidth) {
        var paragraphs = text.split('\n');
        for (let index = 0; index < paragraphs.length; index++) {
            var paragraph = paragraphs[index];
            if (font.widthOfTextAtSize(paragraph, fontSize) > maxWidth) {
                var words = paragraph.split(' ');
                var newParagraph = [];
                var i = 0;
                for (let k = 0; k < words.length; k++) {
                    var word = words[k];
                    if (Array.isArray(newParagraph[i]) == false)
                        newParagraph[i] = [];

                    newParagraph[i].push(word);
                    if (font.widthOfTextAtSize(newParagraph[i].join(' '), fontSize) > maxWidth) {
                        newParagraph[i].splice(-1); // retira a ultima palavra
                        i = i + 1;
                        newParagraph[i] = [];
                        newParagraph[i].push(word);
                    }
                }
                paragraphs[index] = newParagraph.map(p => p.join(' ')).join('\n');
            }
        }
        return paragraphs.join('\n');
    }`

**Comment by raphaelvazuso** [comment]
Here is a function to break lines with a maxWidth given.
```javascript
function fillParagraph(text, font, fontSize, maxWidth) {
    var paragraphs = text.split('\n');
    for (let index = 0; index < paragraphs.length; index++) {
        var paragraph = paragraphs[index];
        if (font.widthOfTextAtSize(paragraph, fontSize) > maxWidth) {
            var words = paragraph.split(' ');
            var newParagraph = [];
            var i = 0;
            for (let k = 0; k < words.length; k++) {
                var word = words[k];
                if (Array.isArray(newParagraph[i]) == false) {
                    newParagraph[i] = [];
                }
                newParagraph[i].push(word);
                if (font.widthOfTextAtSize(newParagraph[i].join(' '), fontSize) > maxWidth) {
                    newParagraph[i].splice(-1); // retira a ultima palavra
                    i = i + 1;
                    newParagraph[i] = [];
                    newParagraph[i].push(word);
                }
            }
            paragraphs[index] = newParagraph.map(p => p.join(' ')).join('\n');
        }
    }
    return paragraphs.join('\n');
}
```

**Comment by Gricardov** [comment]
> ```js
> function fillParagraph(text, font, fontSize, maxWidth) {
>     var paragraphs = text.split('\n');
>     for (let index = 0; index < paragraphs.length; index++) {
>         var paragraph = paragraphs[index];
>         if (font.widthOfTextAtSize(paragraph, fontSize) > maxWidth) {
>             var words = paragraph.split(' ');
>             var newParagraph = [];
>             var i = 0;
>             newParagraph[i] = [];
>             for (let k = 0; k < words.length; k++) {
>                 var word = words[k];
>                 newParagraph[i].push(word);
>                 if (font.widthOfTextAtSize(newParagraph[i].join(' '), fontSize) > maxWidth) {
>                     newParagraph[i].splice(-1); // retira a ultima palavra
>                     i = i + 1;
>                     newParagraph[i] = [];
>                     newParagraph[i].push(word);
>                 }
>             }
>             paragraphs[index] = newParagraph.map(p => p.join(' ')).join('\n');
>         }
>     }
>     return paragraphs.join('\n');
> ```

Gracias chamo, eres maravilloso!

**Comment by donmb1** [comment]
Great work guys, it works perfectly for me.
@raphaelvazuso I am using font size 6 and found out the the line height between one line and the other is kinda huge. Any tip for me how to decrease the line height in this case? I guess it could be one line-break too much in this case which is added. Probably an additional, non needed line-break.

**Comment by ottob** [comment]
Here is a typescript conversion of the code @raphaelvazuso wrote:
```ts
import { PDFFont } from 'pdf-lib'

export const fillPdfParagraph = (
  text: string,
  font: PDFFont,
  fontSize: number,
  maxWidth: number
): string => {
  const paragraphs = text.split('\n')
  for (let index = 0; index < paragraphs.length; index++) {
    const paragraph = paragraphs[index]
    if (font.widthOfTextAtSize(paragraph, fontSize) > maxWidth) {
      const words = paragraph.split(' ')
      const newParagraph: string[][] = []
      let i = 0
      newParagraph[i] = []
      for (let k = 0; k < words.length; k++) {
        const word = words[k]
        newParagraph[i].push(word)
        if (
          font.widthOfTextAtSize(newParagraph[i].join(' '), fontSize) > maxWidth
        ) {
          newParagraph[i].splice(-1) // retira a ultima palavra
          i = i + 1
          newParagraph[i] = []
          newParagraph[i].push(word)
        }
      }
      paragraphs[index] = newParagraph.map((p) => p.join(' ')).join('\n')
    }
  }
  return paragraphs.join('\n')
}
```
