### ISSUE TITLE
[QUESTION] Edit internal links of an existing PDF

### ISSUE THREAD

**Issue by nigellima** [Hopding/pdf-lib#206]
Hi,

Is it possible to replace external links of a PDF with internal links? For example, I have a PDF file that has several anchor tags (it was generated with HTML code) that redirects to external websites. I want to edit these anchor tags with internal links, like `<a href="#section1"><a/>. How would I achieve that?

Thanks in advance

**Comment by Hopding** [comment]
Hello @nigellima!

This is certainly possible to do. You just need to find the annotation dictionaries representing the external links and replace them with internal link annotations of your own making. Here's a working example script based on #123 and #161:

```js
import fs from 'fs';
import fetch from 'node-fetch';
import { PDFArray, PDFDict, PDFDocument, PDFName } from 'pdf-lib';

(async () => {
  // Get the original PDF with an external link
  const pdfWithLinkBytes = await fetch(
    'https://github.com/Hopding/pdf-lib/files/2608369/pdf_with_link.pdf',
  ).then((res) => res.arrayBuffer());

  // Load the original PDF
  const pdfDoc = await PDFDocument.load(pdfWithLinkBytes);

  // Grab a reference to the first page, and add a second page
  const page1 = pdfDoc.getPages()[0];
  const page2 = pdfDoc.addPage([page1.getWidth(), page1.getHeight()]);

  // Draw some text on the second page
  page2.drawText('Hello, I am page 2!', { x: 150, y: page2.getHeight() / 2 });

  // Get a reference to the external link annotation on the first page
  const annots = page1.node.lookup(PDFName.of('Annots'), PDFArray);
  const linkAnnotRef = annots.get(0);
  const linkAnnot = annots.lookup(0, PDFDict);

  // Create a new internal link annotation (going to the second page) by
  // copying the relevant properties from the external one
  const newAnnot = pdfDoc.context.obj({
    Type: 'Annot',
    Subtype: 'Link',
    Rect: linkAnnot.lookup(PDFName.of('Rect')),
    Border: linkAnnot.lookup(PDFName.of('Border')),
    C: linkAnnot.lookup(PDFName.of('C')),
    Dest: [page2.ref, 'XYZ', null, null, null],
  });

  // Replace all occurrences of the external annotation with the internal one
  pdfDoc.context.assign(linkAnnotRef, newAnnot);

  // Save the PDF file
  const pdfBytes = await pdfDoc.save();

  // Write the saved file to `out.pdf`
  fs.writeFileSync('./out.pdf', pdfBytes);
})();
```

And here's the resulting file: [out.pdf](https://github.com/Hopding/pdf-lib/files/3999105/out.pdf)

**Comment by Hopding** [comment]
I hope this helps. Please let me know if you have any additional questions!

**Comment by rameshdhanapal** [comment]
Hi
I am comparing two pdf files. if both file1 and file2 has same content, I will highlight content in both files with rectangle. If I click highlighted content in file1, It should navigate to file2 where exact matching content found/highlighted content in file2. I tried with internal/external links, it is not working. Any help would be appreciated
Thanks
Ramesh
