### ISSUE TITLE
Issue with PDFDocumentFactory.load since version v0.6.2

### ISSUE THREAD

**Issue by totorelmatador** [Hopding/pdf-lib#208]
Hello !

I have noticed a bug in the library when I try to load a pdf. To load it I use the following lines:

```
const fs = require('fs');
const { PDFDocumentFactory } = require('pdf-lib');

let typedarray = fs.readFileSync(filePath);
let myArray = new Uint8Array(typedarray);
const pdfDoc = PDFDocumentFactory.load(myArray);
// and then I use the document
```

It works perfectly... except for this document: [114 Grenelle(1).pdf](https://github.com/Hopding/pdf-lib/files/3677059/114.Grenelle.1.pdf)

Indeed, with this document the line `const pdfDoc = PDFDocumentFactory.load(myArray)` doesn't work.

I don't have a clue of the origine of this bug. The document is "normal", nothing to report.

However the code works if I install the version v0.6.1 of pdf-lib: `npm install --save pdf-lib@0.6.1`

Tell me if you understand this weird behavior !

I am ready to answer your questions and thank you all for your attention.

**Comment by Hopding** [comment]
Hello @totorelmatador! The document loading logic was improved substantially in version 1.0.0 of `pdf-lib`. Please try using the latest version: `npm install --save pdf-lib@1.1.1` and let me know if you still encounter this issue.
