### ISSUE TITLE
No PDF header found at MissingPDFHeaderError.PDFParsingError

### ISSUE THREAD

**Issue by kenzmca86** [Hopding/pdf-lib#209]
Hi,

When i was try to Load the HTML Base64 String to pdf file, I got the error like this "Error: Failed to parse PDF document (line:58 col:14 offset=396): No PDF header found".

Previously i saw your comment regarding the same issue, so tried this:
console.log('Type:', typeof(pdfBytes))
console.log('Is Uint8Array:', pdfBytes instanceof Uint8Array)
console.log('Head:', String(pdfBytes.subarray(0, 250)))

and i got

Type: object
Is Uint8Array: true
Head: 60,33,68,79,67,84,89,80,69,32,104,116,109,108,62,13,10,60,104,116,109,108,62,13,10,60,104,101,97,100,62,13,10,60,115,116,121,108,101,62,13,10,116,97,98,108,101,44,32,116,104,44,32,116,100,32,123,13,10,32,32,98,111,114,100,101,114,58,32,49,112,120,32,115,111,108,105,100,32,98,108,97,99,107,59,13,10,125,13,10,60,47,115,116,121,108,101,62,13,10,60,47,104,101,97,100,62,13,10,60,98,111,100,121,62,13,10,13,10,60,116,97,98,108,101,62,13,10,32,32,60,116,114,62,13,10,32,32,32,32,60,116,104,62,77,111,110,116,104,60,47,116,104,62,13,10,32,32,32,32,60,116,104,62,83,97,118,105,110,103,115,60,47,116,104,62,13,10,32,32,32,32,60,116,104,62,83,97,118,105,110,103,115,32,102,111,114,32,104,111,108,105,100,97,121,33,60,47,116,104,62,13,10,32,32,60,47,116,114,62,13,10,32,32,60,116,114,62,13,10,32,32,32,32,60,116,100,62,74,97,110,117,97,114,121,60,47,116,100,62

please help me to out on this. this makes me sever headache to me for couple weeks now.

Thanks.

**Comment by Hopding** [comment]
Hello @kenzmca86! I took a look at the content of the base64 string you are trying to load:
```js
const charCodes = [60,33,68,79,67,84,89, ..., 100,62]
const str = charCodes.map(code => String.fromCharCode(code)).join('')
console.log(str)
```
This outputs the following:
```
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
}
</style>
</head>
<body>

<table>
  <tr>
    <th>Month</th>
    <th>Savings</th>
    <th>Savings for holiday!</th>
  </tr>
  <tr>
    <td>January</td>
```
So it looks like you are trying to load a base64 encoded HTML document with `PDFDocument.load(...)`. I'm afraid that `pdf-lib` does not support HTML to PDF conversion, so this will not work. See https://github.com/Hopding/pdf-lib/issues/176.

I hope this helps. Please let me know if you have any additional questions!

**Comment by mohanobjmedsys** [comment]
Thanks for your quick reply, appreciated!

**Comment by kaniobjmed** [comment]
Hello @Hopding 

How can I see the pdf Header section like @PDF1.5 something like this.

Thanks in advance.

**Comment by Hopding** [comment]
@kaniobjmed You can do this:
```js
const pdfDoc = await PDFDocument.load(...);
console.log(pdfDoc.context.header.toString());
```
It will output something like the following:
```
%PDF-1.3
%
```
