### ISSUE TITLE
Page's Y axis positioning

### ISSUE THREAD

**Issue by ithillel-aminev** [Hopding/pdf-lib#21]
Hi, guys. That would be great if you to add support of both bottom and top positioning for Y axis on a page while adding texts or images.

**Comment by Hopding** [comment]
Hello @ithillel-aminev. If I understand what you're asking for, this should already be possible to do (though it isn't currently documented or demonstrated in any example code). 

-----

Here's a simple node script that uses the `translate` operator to move the location of the origin to the upper-left corner of the page before drawing some text:
```javascript {.line-numbers}
const fs = require('fs');
const { PDFDocumentFactory, PDFDocumentWriter, drawText, translate } = require('pdf-lib');

const pdfDoc = PDFDocumentFactory.create();
const [helveticaFontRef] = pdfDoc.embedStandardFont('Helvetica');

const PAGE_HEIGHT = 500;
const page1 = pdfDoc.createPage([350, PAGE_HEIGHT]);

const contentStream = pdfDoc.createContentStream(
  // `translate` moves the location of the origin for this content stream.
  translate(0, PAGE_HEIGHT),

  // Now we can draw text with the coordinate space's origin located in the
  // upper-left corner of the page. To move right, we increase `x`. To move
  // down, we decrease `y`.
  drawText('This text is at the top of the page.', {
    x: 5,
    y: -20,
    font: 'Helvetica',
    size: 20,
  }),
);

page1
  .addFontDictionary('Helvetica', helveticaFontRef)
  .addContentStreams(pdfDoc.register(contentStream));

pdfDoc.addPage(page1);

const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
fs.writeFileSync('./upper-left-origin.pdf', pdfBytes);
```
Here's the resulting PDF file: [upper-left-origin.pdf](https://github.com/Hopding/pdf-lib/files/2280301/upper-left-origin.pdf)

-----

We can also position the origin in the center of the page and draw text there. For example, changing the `const contentStream = pdfDoc.createContentStream( ... )` part of the above script to the following:
```javascript
const contentStream = pdfDoc.createContentStream(
  // `translate` moves the location of the origin for this content stream.
  translate(0, 0.5 * PAGE_HEIGHT),

  // Now we can draw text with the coordinate space's origin located in the
  // center-left of the page. To move right, we increase `x`. To move down, we
  // decrease `y`.
  drawText('This text is in the middle of the page.', {
    x: 5,
    y: 0,
    font: 'Helvetica',
    size: 20,
  }),
);
```
Here's the resulting PDF file: [center-left-origin.pdf](https://github.com/Hopding/pdf-lib/files/2280306/center-left-origin.pdf)

-----

Please let me know if this doesn't work, or you have any questions!

**Comment by Hopding** [comment]
I'm going to close this now. Feel free to reopen it if you have additional questions 👍
