### ISSUE TITLE
Draw text with non english alphabet

### ISSUE THREAD

**Issue by Brain2998** [Hopding/pdf-lib#211]
I am trying to draw text with cyrillic font by this font: https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans
Here is the code:
```
//Getting the font in Uint8Array
fetch("https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf").then(response => {
response.arrayBuffer().then(buffer => function(b, self){
          self.customFont = new Uint8Array(b)
        }(buffer, this));
}, response => {
})
....
//Creating embed font
const pdfDoc = await PDFDocument.load(this.file)
pdfDoc.registerFontkit(fontkit)
var font=await pdfDoc.embedFont(this.customFont)
//Draw the text
pdfPage.drawText(text, {
        x: x,
        y: y,
        size: 13,
        font: font,
        color: rgb(0, 0, 0),
        rotate: degrees(0),
})
```
Then i set `text` to 'фыв' it shows just '▯▯▯'
I tried to give `font.encodeText(text)` as input to `drawText` but it encodes as '000000000000'

Also, when i download .woff2 format of this font (https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFUZ0bbck.woff2) 'фыв' string draws as 'biє'. And i have printed multiple warning in console "Warning: getFontFileType: Unable to detect correct font file Type/Subtype.", "Warning: FormatError: Required "loca" table is not found". A little better result, but exmaple on main page uses .ttf

What am i doing wrong? Can someone show me right direction

**Comment by Taktan** [comment]
Возможно, что данная библиотека не умеет работать с кириллицей. Вот мой пример реализации: (_translate_ It is possible that this library does not know how to work with the Cyrillic alphabet. Here is my implementation example:)
```javascript
const existingPdfBytes = await fetch(pdfRent).then(res => res.arrayBuffer())
const pdfDoc = await PDFDocument.load(existingPdfBytes)
pdfDoc.registerFontkit(fontkit);
const fontBytes = await fetch(Montserrat).then((res) => {
return res.arrayBuffer()
})
const customFont = await pdfDoc.embedFont(fontBytes)
```
А в ответе я получаю ошибку в консоли:(_translate_ and in response I get an error in the console)
`Error: Unknown font format`

Если использовать стандартные шрифты, то при вводе кириллицы ответ в консоли будет таким: (_translate_ If you use standard fonts, then when you enter the Cyrillic alphabet, the answer in the console will be like this)
`WinAnsi cannot encode "П"`

**Comment by astanet** [comment]
Hi @Brain2998, I also try to learn this library.

It seems that you are about to use web fonts direct. I think web fonts are optimized for use in css. I tried same approach and searched for CDN that serves fonts, but I could not find.

So, we can serve fonts on by own server. Download fonts and place it on public web server.

Here is an example.  [pdf-lib_embed_custom_font_example.zip](https://github.com/Hopding/pdf-lib/files/3771177/pdf-lib_embed_custom_font_example.zip)

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Security-Policy" content="
            default-src 'self' 'unsafe-inline' blob: resource: https://unpkg.com/;
            object-src 'self' blob:;
            frame-src 'self' blob:;
          " />
  <script type="text/javascript" src="https://unpkg.com/pdf-lib@1.2.1/dist/pdf-lib.js"></script>
  <script type="text/javascript" src="https://unpkg.com/@pdf-lib/fontkit@0.0.4/dist/fontkit.umd.js"></script>
</head>

<body>
  <p>
    <button onclick="test()">Run Test</button>
  </p>
  <iframe id="iframe" width="500" height="600"></iframe>
</body>

<script type="text/javascript">
  const renderInIframe = (pdfBytes) => {
    const blob = new Blob([pdfBytes], { type: 'application/pdf' });
    const blobUrl = URL.createObjectURL(blob);
    document.getElementById('iframe').src = blobUrl;
  };

  async function test() {
    const {
      PDFDocument,
      rgb
    } = PDFLib;

    // This should be a Uint8Array or ArrayBuffer
    // This data can be obtained in a number of different ways
    // If your running in a Node environment, you could use fs.readFile()
    // In the browser, you could make a fetch() call and use res.arrayBuffer()
    const fontBytes = await fetch('/OpenSans-Regular.ttf').then((res) => res.arrayBuffer())

    // Create a new PDFDocument
    const pdfDoc = await PDFDocument.create()

    // Register the `fontkit` instance
    pdfDoc.registerFontkit(fontkit)

    // Embed our custom font in the document
    const customFont = await pdfDoc.embedFont(fontBytes)

    // Add a blank page to the document
    const page = pdfDoc.addPage()

    // Create a string of text and measure its width and height in our custom font
    const text = 'фыв'
    const textSize = 35
    const textWidth = customFont.widthOfTextAtSize(text, textSize)
    const textHeight = customFont.heightAtSize(textSize)

    // Draw the string of text on the page
    page.drawText(text, {
      x: 40,
      y: 450,
      size: textSize,
      font: customFont,
      color: rgb(0, 0.53, 0.71),
    })

    // Draw a box around the string of text
    page.drawRectangle({
      x: 40,
      y: 450,
      width: textWidth,
      height: textHeight,
      borderColor: rgb(1, 0, 0),
      borderWidth: 1.5,
    })

    // Serialize the PDFDocument to bytes (a Uint8Array)
    const pdfBytes = await pdfDoc.save()

    // For example, `pdfBytes` can be:
    //   • Written to a file in Node
    //   • Downloaded from the browser
    //   • Rendered in an <iframe>
    renderInIframe(pdfBytes);
  }
</script>

</html>
```
This example use sirv as static web server. `npm install` and `npm run serve` to test.
I made this example from [the example on README.md](https://github.com/Hopding/pdf-lib#create-document) and [the example for web](https://github.com/Hopding/pdf-lib/blob/master/apps/web/test1.html).

Encoding was not a problem in my environment.
Hope this helps.

**Comment by Sampadaak2613** [comment]
Hi there,

I want to append Japanese letters to pdf footer but I am getting error as "**Error: WinAnsi cannot encode "印"**".

I have installed npm install --save @pdf-lib/fontkit

import * as fontkit from '@pdf-lib/fontkit';
const url = "// Add here pdf document url";
var footerText = "印刷者 " + userName + ' 印刷日時 ' + date + ' 社長室会日時 ' + date;
const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())
const pdfDoc = await PDFDocument.load(existingPdfBytes)
pdfDoc.registerFontkit(fontkit)
const fontBytes = await fetch(footerText).then((res) => {
    return res.arrayBuffer()
})
const customFont = await pdfDoc.embedFont(fontBytes)

var pages = pdfDoc.getPages()
//Looping number of pages and edit the footer
for (var j = 0; j < pages.length; j++) {
    pages[j].drawText((footerText), {
        size: 9,
        font: customFont,
        color: rgb(0, 0, 0),
        lineHeight: 5,
        x: 5,
        y: 10,
    })
}

Any idea that how to add this footer text in pdf footer

**Comment by Hopding** [comment]
Hello @Brain2998, @Taktan, and @astanet! 

**The problem here is that [the font you are embedding](https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf) does not support the characters you are attempting to draw (`фыв`).** This is why it renders as `▯▯▯` on the page. The standard fonts throw an error when you try to draw a character which they do not support (e.g. `WinAnsi cannot encode "П"`) instead of rendering an empty square. Perhaps this should be done for embedded fonts as well.

That being said, the solution is to embed a font that supports all of the characters you wish to encode. After poking around for a bit, I found a version of the OpenSans font that does support the Cyrillic alphabet (or at least the characters you're attempting to draw). You can download it here: https://github.com/google/fonts/raw/master/apache/opensans/OpenSans-Regular.ttf.

I created an example script that demonstrates the issue, and also shows how to log the characters supported by a font:

```js
import fetch from 'node-fetch';
import fontkit from '@pdf-lib/fontkit';
import { PDFDocument } from 'pdf-lib';

(async () => {
  const openSansUrls = {
    partial:
      'https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf',
    full:
      'https://github.com/google/fonts/raw/master/apache/opensans/OpenSans-Regular.ttf',
  };

  // Download the font
  const url = openSansUrls.full;
  console.log(`Downloading font from ${url}\n`);
  const openSansBytes = await fetch(url).then((res) => res.arrayBuffer());

  // Create a PDFDocument
  const pdfDoc = await PDFDocument.create();

  // Embed the font
  pdfDoc.registerFontkit(fontkit);
  const openSansFont = await pdfDoc.embedFont(openSansBytes);

  // Print all characters supported by the font
  const supportedCharacters = openSansFont
    .getCharacterSet()
    .map((codePoint) => String.fromCodePoint(codePoint))
    .join('');
  console.log(`Characters supported by font: ${supportedCharacters}\n`);

  // Print whether each character in the string 'фыв' is supported by the font
  'фыв'.split('').forEach((c) => {
    console.log(`Font supports ${c}? ${supportedCharacters.includes(c)}`);
  });

  // Draw the string 'фыв' on a new page
  const page = pdfDoc.addPage([250, 300]);
  page.drawText('фыв', { size: 50, font: openSansFont });

  const pdfBytes = await pdfDoc.save();
})();
```

When executed with `const url = openSansUrls.partial;` the script outputs the following:
```
Downloading font from https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf

Characters supported by font:  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿıŒœʼˆ˚˜  ​–—‘’‚“”„•…′″‹›⁄⁴€™−�￿

Font supports ф? false
Font supports ы? false
Font supports в? false
```

However, when executed with `const url = openSansUrls.full;` it outputs this:
```
Downloading font from https://github.com/google/fonts/raw/master/apache/opensans/OpenSans-Regular.ttf

Characters supported by font:  !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſƒƠơƯưǰǺǻǼǽǾǿȘșȚțȷʼˆˇˉ˘˙˚˛˜˝˳̣̀́̃̉̏΄΅Ά·ΈΉΊΌΎΏΐΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩΪΫάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώϑϒϖЀЁЂЃЄЅІЇЈЉЊЋЌЍЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяѐёђѓєѕіїјљњћќѝўџѠѡѢѣѤѥѦѧѨѩѪѫѬѭѮѯѰѱѲѳѴѵѶѷѸѹѺѻѼѽѾѿҀҁ҂҃҄҅҆҈҉ҊҋҌҍҎҏҐґҒғҔҕҖҗҘҙҚқҜҝҞҟҠҡҢңҤҥҦҧҨҩҪҫҬҭҮүҰұҲҳҴҵҶҷҸҹҺһҼҽҾҿӀӁӂӃӄӅӆӇӈӉӊӋӌӍӎӏӐӑӒӓӔӕӖӗӘәӚӛӜӝӞӟӠӡӢӣӤӥӦӧӨөӪӫӬӭӮӯӰӱӲӳӴӵӶӷӸӹӺӻӼӽӾӿԀԁԂԃԄԅԆԇԈԉԊԋԌԍԎԏԐԑԒԓḀḁḾḿẀẁẂẃẄẅẠạẢảẤấẦầẨẩẪẫẬậẮắẰằẲẳẴẵẶặẸẹẺẻẼẽẾếỀềỂểỄễỆệỈỉỊịỌọỎỏỐốỒồỔổỖỗỘộỚớỜờỞởỠỡỢợỤụỦủỨứỪừỬửỮữỰựỲỳỴỵỶỷỸỹὍ           ​–—―‗‘’‚‛“”„†‡•…‰′″‹›‼⁄⁰⁴⁵⁶⁷⁸⁹ⁿ₣₤₧₫€℅ℓ№℠™Ω℮⅛⅜⅝⅞∂∆∏∑−√∞∫≈≠≤≥◊ﬀﬁﬂﬃﬄ￼�￿

Font supports ф? true
Font supports ы? true
Font supports в? true
```

And of course, when using the version of the font that supports the Cyrillic alphabet, it produces the following PDF page:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/71422501-2ba5ac00-2648-11ea-8623-b7611d004551.png" alt="output page" height="500">
</kbd>

>

I hope this helps. Please let me know if you have any additional questions!

**Comment by Hopding** [comment]
@Sampadaak2613 it looks like you are trying to `fetch` the text you wish to draw, not the actual font URL:
```js
var footerText = "印刷者 " + userName + ' 印刷日時 ' + date + ' 社長室会日時 ' + date;
...
const fontBytes = await fetch(footerText).then((res) => {
    return res.arrayBuffer()
})
const customFont = await pdfDoc.embedFont(fontBytes)
```
I'd suggest taking a look at my previous comment to see how to download and use a font.
