### ISSUE TITLE
Images being overwritten on PDFs with more than 100 pages

### ISSUE THREAD

**Issue by thebenlamm** [Hopding/pdf-lib#212]
This is a very strange issue that we've run into and took some time to be able to reliably reproduce.

When adding images to large PDFs, generally with more than 100 pages, the images from later pages end up replacing the images on earlier pages. (The images on the later pages remain as expected) 

Here is the code to reproduce it. On each page I print the page number and then create a corresponding QR code of the page number:

```
const QRCode = require('qrcode'),
      concat = require('concat-stream'),
      fs = require('fs'),
      { PDFDocument } = require('pdf-lib');

// Given some text returns a QR code
const createQRCode = (text) => {
  return new Promise(resolve => {
    QRCode.toFileStream(concat(resolve), text, {
      type: 'png',
      errorCorrectionLevel: 'L',
      scale: 2
    });
  })
}

// Take a multi-page pdf and print a number and qrcode on each page.
const pdfMocker = async (filePath) => {
  const originalPdfBytes = fs.readFileSync(filePath);
  const pdfDoc = await PDFDocument.load(originalPdfBytes);

  const pages = pdfDoc.getPages();
  for (var i = 0; i < pages.length; i++) {
    const page = pages[i];
    const number = `${i + 1}`;
    const qrCodeBuffer = await createQRCode(number);
    const qrCodeImage = await pdfDoc.embedPng(qrCodeBuffer);
    page.drawImage(qrCodeImage, {
      x: 465,
      y: 350,
      width: 80,
      height: 80
    });
    page.drawText(number, { x: 405, y: 562, size: 13 });
  }

  const pdfBytes = await pdfDoc.save()
  fs.writeFileSync('output.pdf', pdfBytes);
}

pdfMocker('blank-v4.pdf'); 
```

The expected output would be for each page to have its number and the corresponding QR code. Instead, approximately 1 in every 100 pages has the QR code of a different page. I ran this several times with 100 pages. 
test 1) page 67 had the QR code for page 85
test 2) page 19 had the QR code for page 94
test 3) page 78 had the QR code for page 85

In each case the QR code on the later page remained correct. It was just duplicated on the earlier page, replacing the QR code expected there.

Interestingly, this can only be reproduced this with PDFs of v1.4. Here is the PDF that I used. [blank-v4.pdf](https://github.com/Hopding/pdf-lib/files/3703857/blank-v4.pdf)

I have written some code (using OCR/ImageMagick) to automate the scanning and testing of PDFs to find the issue. Would be glad to share.

**Comment by thebenlamm** [comment]
FOUND THE BUG!! [here](https://github.com/Hopding/pdf-lib/blob/master/src/api/PDFPage.ts#L664)

The problem is when the xObjectKey is set it only adds 4 random digits. That level of randomness doesn't work consistently for PDFs with many images. Inevitably, collisions do occur. I upped that number to 10 and could not reproduce the above issue.

@Hopding is there a reason you decided to use the number 4? Can I open a pull request to raise that number?

**Comment by Hopding** [comment]
Hello @thebenlamm! Great work investigating this issue! There was no specific reason for deciding to use 4 random digits. I just had to use some number, and 4 seemed reasonable at the time. But I think it makes sense to increase the number of digits to 10 or so. That will reduce the likelihood of a naming collision from one in `10^4=10,000` to one in `10^10=10,000,000,000`. Please do open a pull request and I'll merge it.

**Comment by Hopding** [comment]
Version [`1.2.1`](https://www.npmjs.com/package/pdf-lib/v/1.2.1) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.2.1).

You can install this new version with npm:

```
npm install pdf-lib@1.2.1
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.2.1/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.2.1/dist/pdf-lib.min.js
