### ISSUE TITLE
Special Characters while adding metadata in UTF-8

### ISSUE THREAD

**Issue by minakshi-debut** [Hopding/pdf-lib#216]
while creating a pdf with metadata, metadata are not stored in UTF-8 format. Is there any way to add metadata in UTF-8 format.

**Comment by Hopding** [comment]
Hello @minakshi-debut! 

I'm afraid metadata cannot be stored in UTF-8 format. The [PDF specification](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) states that metadata should be stored as "text strings" (see **Table 317 – Entries in the document information dictionary**). And the spec states that text strings
> shall be encoded using either PDFDocEncoding or UTF-16BE with a leading byte-order marker.

(see **Table 35 – String Object Types** and **Section 7.9.2.2 Text String Type**).
