### ISSUE TITLE
Error when using emojis or special characters with standard font

### ISSUE THREAD

**Issue by andrewsadduq** [Hopding/pdf-lib#217]
When I use a standard font (Helvetica) and call the method _widthOfTextAtSize_ I receive the following error "WinAnsi cannot encode """. What can I do to solve this issue?

**Comment by Hopding** [comment]
Hello @andrewsadduq! 

You cannot draw emojis or many special characters in the standard fonts. This is something that I would like to document better, as it is a common point of confusion. This restriction is an unfortunate artifact of the PDF spec and its age. It is simply not possible to represent many unicode characters in the standard fonts defined in the PDF spec. Instead, you must embed your own font to accomplish this.

Here is a PDF file that demos the 14 standard fonts and the character set supported by each of them. The file was generated by pdf-lib's [10th integration test](https://github.com/Hopding/pdf-lib/blob/master/apps/node/tests/test10.ts):
> [standard_14_fonts_demo.pdf](https://github.com/Hopding/pdf-lib/files/3730963/standard_14_fonts_demo.pdf)
