### ISSUE TITLE
Page width and height

### ISSUE THREAD

**Issue by ithillel-aminev** [Hopding/pdf-lib#22]
Hi @Hopding. Is it possible to know width and height of a page? For instance, when we iterate over pages got by `const pages = pdfDoc.getPages();`

**Comment by ithillel-aminev** [comment]
Oh it seems https://github.com/Hopding/pdf-lib/issues/10 answers my question
`const pages = pdfDoc.getPages();
const page1 = pages[0];

const PAGE_WIDTH = page1.get('MediaBox').array[2];
const PAGE_HEIGHT = page1.get('MediaBox').array[3];`

**Comment by Hopding** [comment]
Yep, you've got it! I'd like to create a more intuitive API for this at some point, but that's the way to do it for now.

**Comment by Hopding** [comment]
**UPDATE:** Please use the `getPageDimensions()` function defined [here](https://github.com/Hopding/pdf-lib/issues/62#issuecomment-453847201) to obtain the width and/or height of a page. The `page1.get('MediaBox').array[...];` calls used here do not work on all documents.
