### ISSUE TITLE
drawSvgPath position issue

### ISSUE THREAD

**Issue by prosenjit-manna** [Hopding/pdf-lib#223]
DOC: https://pdf-lib.js.org/docs/api/classes/pdfpage#drawsvgpath

```
const svgPath = 'M 0,20 L 100,160 Q 130,200 150,120 C 190,-40 200,200 300,150 L 400,90';
page.drawSvgPath(svgPath, { x: 25, y: 75 })

```
This code paints the SVG path from the bottom axis. 

1. Is this correct behavior?
2. How I can calculate from the top axis?

More info:
- I am using the latest version
- Here is the jsbin : https://jsbin.com/segeca/1/edit?html,output

 **Annotation position in my UI.**
![image](https://user-images.githubusercontent.com/11558810/67276132-a8e66080-f4e1-11e9-953d-cf6441912eaf.png)
**And after written with pdf-lib the position changed.**
[some-file (2).pdf](https://github.com/Hopding/pdf-lib/files/3754834/some-file.2.pdf)

Here is the annotation data path that was calculated from JSON:
```
M201 70 204 70 M204 70 204 70 M204 70 207 70 M207 70 208 70 M208 70 211 70 M211 70 212 70 M212 70 214 70 M214 70 215 70 M215 70 216 70 M216 70 219 70 M219 70 220 70 M220 70 223 70 M223 70 225 70 M225 70 227 70 M227 70 229 70 M229 70 232 70 M232 70 236 70 M236 70 238 70 M238 70 241 70 M241 70 245 70 M245 70 248 70 M248 70 252 70 M252 70 256 70 M256 70 260 70 M260 70 264 70 M264 70 267 70 M267 70 271 70 M271 70 274 70 M274 70 277 70 M277 70 281 70 M281 70 283 70 M283 70 286 70 M286 70 288 68 M288 68 291 68 M291 68 293 68 M293 68 296 67 M296 67 298 66 M298 66 300 66 M300 66 302 66 M302 66 305 65 M305 65 307 64 M307 64 310 64 M310 64 314 63 M314 63 316 62 M316 62 319 62 M319 62 321 61 M321 61 324 61 M324 61 326 60 M326 60 329 60 M329 60 330 60 M330 60 332 60 M332 60 334 60 M334 60 336 60 M336 60 337 60 M337 60 338 60 M338 60 340 60 M340 60 341 60 M341 60 342 60 M342 60 345 60 M345 60 346 60 M346 60 348 60 M348 60 349 60 M349 60 351 60 M351 60 353 60 M353 60 354 60 M354 60 356 60 M356 60 357 60 M357 60 358 60 M358 60 359 60 M359 60 361 60 M361 60 361 61 M361 61 364 62 M364 62 366 63 M366 63 367 64 M367 64 368 64 M368 64 369 65 M369 65 370 65 M370 65 372 66 M372 66 373 67 M373 67 376 69 M376 69 377 69 M377 69 379 70 M379 70 381 72 M381 72 384 72 M384 72 385 73 M385 73 386 74 M386 74 389 75 M389 75 390 75 M390 75 392 76 M392 76 394 77 M394 77 395 78 M395 78 397 79 M397 79 398 80 M398 80 400 80 M400 80 401 82 M401 82 402 82 M402 82 403 83 M403 83 404 83 M404 83 404 84 M404 84 405 85 M405 85 405 85 M405 85 406 86 M406 86 406 86 M406 86 407 86 M407 86 407 87 M407 87 407 87 M407 87 407 88 M407 88 408 90 M408 90 409 91 M409 91 409 93 M409 93 409 94 M409 94 409 95 M409 95 409 97 M409 97 409 98 M409 98 409 99 M409 99 409 100 M409 100 409 101 M409 101 408 102 M408 102 407 103 M407 103 404 104 M404 104 402 106 M402 106 400 107 M400 107 395 110 M395 110 393 110 M393 110 389 112 M389 112 385 114 M385 114 380 117 M380 117 374 120 M374 120 372 121 M372 121 368 123 M368 123 364 125 M364 125 360 126 M360 126 356 128 M356 128 352 129 M352 129 348 131 M348 131 346 132 M346 132 342 133 M342 133 339 134 M339 134 335 135 M335 135 333 136 M333 136 329 137 M329 137 322 138 M322 138 320 138 M320 138 316 138 M316 138 313 138 M313 138 309 138 M309 138 307 138 M307 138 304 138 M304 138 300 138 M300 138 298 138 M298 138 295 138 M295 138 293 138 M293 138 290 138 M290 138 286 138 M286 138 284 138 M284 138 280 137 M280 137 278 136 M278 136 274 135 M274 135 270 134 M270 134 266 133 M266 133 262 131 M262 131 258 130 M258 130 254 129 M254 129 251 128 M251 128 248 126 M248 126 245 125 M245 125 241 124 M241 124 239 123 M239 123 236 122 M236 122 234 121 M234 121 231 120 M231 120 229 118 M229 118 226 118 M226 118 224 117 M224 117 221 115 M221 115 218 113 M218 113 216 112 M216 112 213 111 M213 111 211 109 M211 109 210 108 M210 108 207 107 M207 107 206 106 M206 106 204 105 M204 105 203 104 M203 104 201 104 M201 104 201 103 M201 103 200 102 M200 102 200 102 M200 102 199 101 M199 101 199 101 M199 101 199 99 M199 99 198 99 M198 99 198 98 M198 98 197 97 M197 97 197 96 M197 96 196 95 M196 95 196 94 M196 94 195 93 M195 93 195 92 M195 92 194 92 M194 92 194 91 M194 91 194 91 M194 91 194 90 M194 90 193 90 M193 90 193 88 M193 88 193 88 M193 88 193 87 M193 87 193 86 M193 86 192 84 M192 84 192 83 M192 83 192 82 M192 82 191 82 M191 82 191 81 M191 81 191 81 M191 81 191 80 M191 80 191 80 M191 80 191 79 M191 79 191 79 M191 79 191 78 M191 78 191 78 M191 78 191 77 M191 77 191 76 M191 76 191 76 M191 76 191 75 M191 75 191 75 M191 75 191 74 M191 74 191 74 M191 74 191 73 M191 73 191 73 M191 73 192 72 M192 72 192 71 M192 71 192 71 M192 71 193 71 M193 71 193 70 M193 70 194 70 M194 70 194 70 M194 70 195 70 M195 70 195 70 M195 70 196 70 M196 70 196 70 M196 70 197 70 M197 70 197 70 M197 70 198 70 M198 70 199 70 M199 70 199 70 M199 70 200 70 M200 70 200 70 M200 70 201 70 M201 70 201 70 M201 70 202 70 M202 70 202 70 M202 70 203 70 M203 70 203 70 M203 70 204 70Z
```

**Comment by Hopding** [comment]
Hello @prosenjit-manna!

> **1. Is this correct behavior?**

Yes, this behavior is expected. While it may be abnormal from a computer graphics perspective, it is the standard for PDF files. This coordinate system is documented in section **8.3.2.3 User Space** of the [PDF specification](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf):
> To avoid the device-dependent effects of specifying objects in device space, PDF defines a device-independent coordinate system that always bears the same relationship to the current page, regardless of the output device on which printing or displaying occurs. This device-independent coordinate system is called _user space_.
>
> The user space coordinate system shall be initialized to a default state for each page of a document. [...] The positive _x_ axis extends horizontally to the right and the positive _y_ axis vertically upward, as in standard mathematical practice [...] This coordinate system is called _default user space_.

> **2. How I can calculate from the top axis?**

The simplest way to do this is to obtain the height of the page with [`PDFPage.getHeight()`](https://pdf-lib.js.org/docs/api/classes/pdfpage#getheight) and subtract from it. For example:
```js
const pdfDoc = await PDFDocument.create();

const page = pdfDoc.addPage();

const svgPath =
  'M 0,20 L 100,160 Q 130,200 150,120 C 190,-40 200,200 300,150 L 400,90';

// Draw the path with the upper left corner 25pts below the top of the page
page.drawSvgPath(svgPath, { x: 25, y: page.getHeight() - 25 });

const pdfBytes = await pdfDoc.save();
```

This example produces the following:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/71385306-432f5700-25ac-11ea-8893-7c3caccc9de5.png" height="500" alt="out image">
</kbd>

>

I hope this helps. Please let me know if you have any additional questions!

**Comment by sbraaa** [comment]
Hi, I'm facing the same problem of @prosenjit-manna.
leaving out top coordinate calcolation, if you take a look his pdf output you will notice the all the coordinates are wrong (x & y)!
After doing some tests with the same SVG I discovered that if you convert it to image you'll be able to place it in the position you choice but, if you'll do the same using SVG, the output coordinates are wrong (using the same x,y and scale)!
Here a[ sample ](https://github.com/sbraaa/Apprise-v2/blob/master/pdf-lib_modification_example%20(4).pdf)!
@Hopding : could you explain me why this happend?
Thanks!

**Comment by prosenjit-manna** [comment]
Can you share your expected annotation with image format? So that I can guess what is the issue?

**Comment by prosenjit-manna** [comment]
Quick guess is, may be scalling issue.

**Comment by sbraaa** [comment]
@prosenjit-manna   I use the same scaling factor... should it change using SVG? It seems very strange..

**Comment by prosenjit-manna** [comment]
if the Annotation SVG layer scale does not match with the PDF-lib scale then the annotation position will differ. I was facing this issue in my project.

**Comment by sbraaa** [comment]
> if the Annotation SVG layer scale does not match with the PDF-lib scale then the annotation position will differ. I was facing this issue in my project.

Have you found any solution yet? 
My project let the user place his sign on a pdf. 
I use pdf.js to show pdf then I'll grab user's sign in svg format and display it over pdf using overlay canvas.
My goal is to use svg to place te sign on pdf because it is more defined than raster version.
First I transpose sign coordinates from canvas to pdf real dimension calculating x, y and scale.

this is raster version:
```
		let pngUrl = obj.toDataURL({
			format: 'png'
		});
		const pngImageBytes = await fetch(pngUrl).then((res) => res.arrayBuffer());
		const pngImage = await pdfDoc.embedPng(pngImageBytes);
		const pngDims = pngImage.scale(scale_factor);

		page.drawImage(pngImage, {
			x: x,
			y: (page.getHeight() - y) - pngDims.height,
			width: pngDims.width,
			height: pngDims.height,
		})
```

which is right.

This is svg version:
			svgOptions = {
				x: x,
				y: page.getHeight() - y,
				borderWidth: svgSignWidth,
				scale: scale_factor
			}

			if (svgSignFillColor != 'none') {
				svgOptions.color = svgSignFillColor;
			}
			page.pushOperators(pushGraphicsState(), setLineCap(LineCapStyle.Round));
			page.drawSvgPath(svgSignPath, svgOptions);

(obviously I made my custom function to extract path from SVG )

Coordinates are the same, scale also (variable scale_factor).
Any advice?

**Comment by Sharcoux** [comment]
Found the issue. The coordinate system is wrong: the origin does match the specs, but the y axis should be looking upwards, which is not the case here. You can check [this](https://jsbin.com/segeca/1/edit?html,output) if you need proof.

I'll try to open a PR
