### ISSUE TITLE
How to scale each chunk of text differently

### ISSUE THREAD

**Issue by ezekiel747** [Hopding/pdf-lib#225]
Hello, I have to draw several chunks of text, each one has distinct values for scaling on x and y.
The first chunk of text renders fine if i use page.pushOperators(scale(0.5, 1)) before drawText.

However if for the next chunk i use page.pushOperators(scale(0.75, 1))  - notice the different scaling values - the resulted text isn't what i expect. Somehow, the two scaling instructions combine.
I need to reset somehow the scaling - how can i do that? Thanks.

**Comment by ezekiel747** [comment]
Coming back to this since i haven't yet found a workaround.
Would be awesome to have an entry for **scaling** in the **options** object passed to each drawText call (along with x, y, size, rotate etc).
Or maybe could you please show an example with a workaround to this issue?
Thank you.

**Comment by Hopding** [comment]
Hello @ezekiel747! What you are encountering is one of the quirks of the PDF graphics model. Many PDF operators do not reset the variables they affect. Instead, they add/subtract/multiply/divide the preexisting values of the variables. This is the case with the scaling operator. 

If you wish to avoid this behavior, then you have to push and pop the graphics state. This can be done with the [`pushGraphicsState`](https://pdf-lib.js.org/docs/api/#const-pushgraphicsstate) and [`popGraphicsState`](https://pdf-lib.js.org/docs/api/#const-popgraphicsstate) operators in pdf-lib. 

I created an example script to demonstrate how this works:
```js
import {
  PDFDocument,
  popGraphicsState,
  pushGraphicsState,
  scale,
  StandardFonts,
  rgb,
} from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const size = 48;

  const page = pdfDoc.addPage([300, 350]);

  page.moveTo(0, 350);

  page.moveDown(size);
  page.pushOperators(pushGraphicsState(), scale(1.75, 1));
  page.drawText('Foobar', { font, size });
  page.pushOperators(popGraphicsState());

  page.moveDown(size);
  page.pushOperators(pushGraphicsState(), scale(1.5, 1));
  page.drawText('Foobar', { font, size });
  page.pushOperators(popGraphicsState());

  page.moveDown(size);
  page.pushOperators(pushGraphicsState(), scale(1.25, 1));
  page.drawText('Foobar', { font, size });
  page.pushOperators(popGraphicsState());

  page.moveDown(size);
  page.pushOperators(pushGraphicsState(), scale(1, 1));
  page.drawText('Foobar', { font, size, color: rgb(1, 0.25, 0.25) });
  page.pushOperators(popGraphicsState());

  page.moveDown(size);
  page.pushOperators(pushGraphicsState(), scale(0.75, 1));
  page.drawText('Foobar', { font, size });
  page.pushOperators(popGraphicsState());

  page.moveDown(size);
  page.pushOperators(pushGraphicsState(), scale(0.5, 1));
  page.drawText('Foobar', { font, size });
  page.pushOperators(popGraphicsState());

  page.moveDown(size);
  page.pushOperators(pushGraphicsState(), scale(0.25, 1));
  page.drawText('Foobar', { font, size });
  page.pushOperators(popGraphicsState());

  const pdfBytes = await pdfDoc.save();
})();
```

This produces the following:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/71371954-9687b200-2578-11ea-9367-93221dee7819.png" alt="output file image" height="500">
</kbd>

>
I hope this helps. Please let me know if you have any additional questions!

-----

Providing a simple API for the scaling operation does seem like a useful feature. If anybody would like to submit a PR adding scaling options to the `PDFPage.draw*` methods, I would be happy to merge it.
