### ISSUE TITLE
Rotation of text / images when inserting

### ISSUE THREAD

**Issue by curtisnn** [Hopding/pdf-lib#23]
Thanks for this module. I was wondering if there was a way to rotate text that is being inserted on an existing document. I need to insert some text and images upside down. I know I could do image processing to make the images upside down, just wondering if rotation was built in.

Might there be parameters like rotate, rotateOrigin?

Thanks

**Comment by Hopding** [comment]
It is possible to rotate text and images in `pdf-lib`. However, the `drawText` and `drawImage` operators don't currently have options for doing so. I plan to add these options in the next release of `pdf-lib`, but for now, you'll have to reimplement the operators with the `rotate` options yourself.

Here's the code for doing so:
```javascript
const {
  PDFOperators,
  pushGraphicsState,
  translate,
  scale,
  image,
  popGraphicsState,
  fillingRgbColor,
  fontAndSize,
  textPosition,
  text,
  PDFTextObject,
} = require('pdf-lib');

const { cm, Tm } = PDFOperators;

const rotateRadians = (angle) =>
  cm.of(
    Math.cos(angle + 0.00001),
    Math.sin(angle + 0.00001),
    -Math.sin(angle + 0.00001),
    Math.cos(angle + 0.00001),
    0,
    0,
  );

const rotateDegrees = (angle) => {
  const radians = angle * Math.PI / 180;
  return rotateRadians(radians);
};

const customDrawImage = (name, options) => [
  pushGraphicsState(),
  translate(options.x || 0, options.y || 0),
  rotateDegrees(options.rotate || 0),
  scale(options.width || 100, options.height || 100),
  image(name),
  popGraphicsState(),
];

const rotateTextRadiansAndTranslate = (angle, x, y) =>
  Tm.of(
    Math.cos(angle + 0.00001),
    Math.sin(angle + 0.00001),
    -Math.sin(angle + 0.00001),
    Math.cos(angle + 0.00001),
    x,
    y,
  );

const rotateTextDegreesAndTranslate = (angle, x, y) => {
  const radians = angle * Math.PI / 180;
  return rotateTextRadiansAndTranslate(radians, x, y);
};

const customDrawText = (line, options) => [
  PDFTextObject.of(
    fillingRgbColor(
      options.colorRgb ? options.colorRgb[0] : 0,
      options.colorRgb ? options.colorRgb[1] : 0,
      options.colorRgb ? options.colorRgb[2] : 0,
    ),
    rotateTextDegreesAndTranslate(
      options.rotate || 0,
      options.x || 0,
      options.y || 0
    ),
    fontAndSize(options.font, options.size || 12),
    text(line),
  ),
];
```

Once you've done this, you can use the `customDrawText` and `customDrawImage` operators like so:
```javascript
// Draw text upside down
customDrawText('This is upside down text!', {
  x: 25,
  y: 50,
  font: 'Helvetica',
  size: 24,
  colorRgb: [1, 0, 0],
  rotate: 180,
})

// This an image on its side
customDrawImage('some_image', {
  x: 25,
  y: 50,
  width: 500,
  height: 500,
  rotate: 90,
})
```

I've written a Node script that defines and uses these custom operators to draw some rotating text and an image: [index.js.zip](https://github.com/Hopding/pdf-lib/files/2297440/index.js.zip) ([here](https://github.com/Hopding/pdf-lib/blob/master/__integration_tests__/assets/images/small_mario.png) is the image used by the script)

Here's the resulting document: [out.pdf](https://github.com/Hopding/pdf-lib/files/2297442/out.pdf)

**Comment by curtisnn** [comment]
Rad! Thank you for this.

**Comment by Hopding** [comment]
You bet! 👍

**Comment by Hopding** [comment]
Version [`0.3.0`](https://www.npmjs.com/package/pdf-lib/v/0.3.0) is now published. It contains rotation and skewing options for the `drawImage` and `drawText` operators, as well as several others. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.3.0).

You can install this new version with npm:
```
npm install pdf-lib@0.3.0
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.3.0/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.3.0/dist/pdf-lib.min.js
