### ISSUE TITLE
Embedding woff/woff2 fonts

### ISSUE THREAD

**Issue by TomTomB** [Hopding/pdf-lib#231]
I´d like to embbed the Roboto font as .woff2 inside a pdf. 
Doing so, results in a blank page.

I wonder if the .woff2 filetype even is supported inside pdfs?

Here is a small reproduction script:

```
async function embedFont() {
  const url = 'https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu72xKOzY.woff2';

  const fontBytes = await fetch(url).then(res => res.arrayBuffer());

  const pdfDoc = await PDFDocument.create();

  pdfDoc.registerFontkit(fontkit);
  const customFont = await pdfDoc.embedFont(fontBytes);

  const page = pdfDoc.addPage();

  const text = 'This is text in an embedded font!';
  const textSize = 35;

  page.drawText(text, {
    x: 40,
    y: 450,
    size: textSize,
    font: customFont,
    color: rgb(0, 0.53, 0.71)
  });

  const pdfBytes = await pdfDoc.save();

  //fs.writeFileSync('path/to/desktop', pdfBytes);
}
```

**Comment by Hopding** [comment]
Hello @TomTomB! pdf-lib should be capable of embedding most WOFF/WOFF2 fonts. 

I was able to reproduce the issue when downloading the roboto font from the link you shared. However, when I download what appears to be a different version of the roboto fonts from [here](https://google-webfonts-helper.herokuapp.com/fonts/roboto?subsets=latin), I am able to embed the `.ttf`, `.woff`, and `.woff2` versions of the font without any issues.

Where did you obtain the `https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Mu72xKOzY.woff2` link?

**Comment by TomTomB** [comment]
Hi @Hopding, 
I´ve obtained the link from the css file genereated by [google fonts](https://fonts.google.com/).

E.g. selecting the Roboto font generates the following HTML: 
`<link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">`
Simply open that link inside a browser and you´ll get some @font-faces containing those rather cryptic links.

**Comment by Hopding** [comment]
I haven't run into this issue with WOFF/WOFF2 fonts before. I tried using the same WOFF2 font that you shared in a script with [`pdfkit`](https://github.com/foliojs/pdfkit) (it uses the same font engine that pdf-lib does: [`fontkit`](https://github.com/foliojs/fontkit)). It looks like `pdfkit` is also unable to render text with that font. So it would seem that something about those particular WOFF2 fonts being served by google makes `fontkit` goof up (or perhaps special handling needs to be done in both pdf-lib and pdfkit to handle it).

I'll leave this issue open as it seems to be legitimate. However, since the TTF version of the font works correctly, I don't consider this to be a high priority issue right now.

**Comment by zimt28** [comment]
I just ran into the same issue. macOS `Previev.app` can open the final PDF without issues and show the font correctly, iOS can too. Acrobat Reader on Mac/ Windows fails and shows:

```
Cannot extract the embedded font 'LobsterTwo-2969'. Some characters may not display or print correctly.
```

Also, my issue with ligatures #490 only happens with `.woff2` files (from Google, haven't tested others yet).

Another `.woff` file, also from Google, failed completely:

<img width="848" alt="Screenshot 2020-06-17 at 20 48 23" src="https://user-images.githubusercontent.com/1764689/84937365-ee444780-b0db-11ea-94a5-be2d1800eb0d.png">

Being able to use `.woff2` files would be great, as the resulting file size seems much smaller.

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by FedericaCabrera1** [comment]
> I haven't run into this issue with WOFF/WOFF2 fonts before. I tried using the same WOFF2 font that you shared in a script with [`pdfkit`](https://github.com/foliojs/pdfkit) (it uses the same font engine that pdf-lib does: [`fontkit`](https://github.com/foliojs/fontkit)). It looks like `pdfkit` is also unable to render text with that font. So it would seem that something about those particular WOFF2 fonts being served by google makes `fontkit` goof up (or perhaps special handling needs to be done in both pdf-lib and pdfkit to handle it).
> 
> I'll leave this issue open as it seems to be legitimate. However, since the TTF version of the font works correctly, I don't consider this to be a high priority issue right now.

Hey im also trying to embed that font, may i ask which url do you use for the TTF version that actually works please, as i've been trying with the only ones i found that are the WOFF2 and none of them seems to work (when rendering it i get a bunch of "A's" or some strange code, everything but my text). Thanks

**Comment by scadot** [comment]
Hello @FedericaCabrera1, 
I have the same problem as you.
Did you find any solutions or a workaround?

**Comment by sumitaney** [comment]
I would suggest Use it with local file in your project then fetch it to arrayBufferr. @TomTomB @scadot @Hopding @FedericaCabrera1

**Comment by madara3** [comment]
I have the same issue, it prints capital letter DDDD instead of text (roboto.woff2 from google fonts)
