### ISSUE TITLE
[Feature Request]: Document decryption

### ISSUE THREAD

**Issue by davidmatter** [Hopding/pdf-lib#233]
I would find it useful to support Encryption Handling as discussed in https://github.com/Hopding/pdf-lib#encryption-handling

**Comment by iamscopes123** [comment]
+1

**Comment by aawaken** [comment]
+1

**Comment by punisher97** [comment]
Please add support, pdfkit has [security ](https://github.com/foliojs/pdfkit/blob/master/lib/security.js)with this module and crypto-js

**Comment by Eric24** [comment]
By the way, maybe it makes sense to approach this as two separate enhancements: 1) The ability to encrypt and set permissions on a document on save; and 2) The ability to load and decrypt an encrypted document.

**Comment by Hopding** [comment]
@Eric24 I agree. Encryption and decryption should be implemented and released separately. My intent is to track decryption support in this issue, and to track encryption support in https://github.com/Hopding/pdf-lib/issues/243. But I suppose this issue's title doesn't make that especially clear.

**Comment by parasdahal** [comment]
+1

**Comment by deammer** [comment]
I would also love to see support for encrypted PDFs!

The USCIS website hosts a bunch of encrypted PDFs that could help test this functionality:
* [I-944](https://www.uscis.gov/system/files_force/files/form/i-944-pc.pdf)
* [I-130](https://www.uscis.gov/sites/default/files/files/form/i-130.pdf)
* [I-485](https://www.uscis.gov/system/files_force/files/form/i-485-pc.pdf)


--- 
Btw @Hopding, thank you for the amazing library. My work revolves around empowering immigrants to successfully navigate the American immigration system, which means dealing with a massive amount of scary forms and documents, so having the tools to manipulate PDFs is essential. You should consider adding a donation link to this repo!

**Comment by vpanyushenko** [comment]
+1 as well.

**Comment by humqn** [comment]
+1

**Comment by philip5221** [comment]
+1 - thanks for your work!

**Comment by vegarringdal** [comment]
+1

Will I be able to resize a pdf if printing is allowed?

Sample file, if this is ever needed
https://www.rotork.com/uploads/documents-versions/41003/1/pub002-039-00_0318.pdf

[pub002-039-00_0318.pdf](https://github.com/Hopding/pdf-lib/files/4933949/pub002-039-00_0318.pdf)

![image](https://user-images.githubusercontent.com/2901416/87717786-45a80700-c7b1-11ea-87c3-c6d2d0bf216a.png)

**Comment by divinehawk** [comment]
Would be interested in this as well. I tried out the Mozilla pdf.js and it appears to work with all of my sample pdfs.

**Comment by sundowndev** [comment]
Facing the same issue, as a workaround you can use **node-pdftk**

Quick snippet:

```typescript
import * as pdftk from 'node-pdftk';

function removePdfEncryption(input: string | Buffer): Promise<Buffer> {
    return pdftk.input(input).output();
}
```

**Comment by m-majetic** [comment]
@sundowndev Your solution with "pdftk" doesn't work on my end.

Thank you for the idea, but [this](https://github.com/jjwilly16/node-pdftk/issues/22#issuecomment-702711571) is what I have come to.
I have built the latest version of "PDFtk" on CentOS and used it because that's a requirement for my project.
Did you get a different result ?

@Hopding, is there any progress on this issue ?

**Comment by sundowndev** [comment]
@m-majetic Did you try decrypting the PDF file using PDFtk in the CLI ? May be PDFtk simply cannot decrypt that specific document.

**Comment by m-majetic** [comment]
@sundowndev I was able to decrypt that document using "qpdf" in CLI by simply running
`qpdf --decrypt encryptedDocument.pdf decryptedDocument.pdf` without using any password.

I tried to input an empty password in multiple ways to "PDFtk" in CLI as well, but to no avail.
Maybe there is a special character that should be used as "input_pw" in such a scenario.

**Comment by Ayfel** [comment]
+1 to this and wondering if there is a roadmap or estimation for decryption. Thank you again for the amazing project

**Comment by Sharcoux** [comment]
The code of pdf-js relative to decryption is [here](https://github.com/mozilla/pdf.js/blob/d6e0b2d92e243c56a6ce02be3d6cab92e9df9213/src/core/crypto.js#L1704). CipherTransformFactory seems to control it all. I'm not sure to be able to help much further... ^^"

**Comment by kingworm** [comment]
+1 to this because I'm trying to merge pdf pages from aws origin file

**Comment by kingworm** [comment]
I used qpdf to decrypt pdf without password
```qpdf --decrypt input.pdf output.pdf```

**Comment by H3RSKO** [comment]
+1 as well.

**Comment by Sukoiinea** [comment]
+1

**Comment by syantob** [comment]
+1

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by patilakshay56** [comment]
@Hopding any plan on this in upcoming releases ?

**Comment by Sharcoux** [comment]
@Hopding Why did you close this MR? I don't believe that you implemented it, did you?

I'm working on this: https://github.com/Hopding/pdf-lib/issues/1390 if someone wants to participate and help. There is an implementation of that feature, there, but it's not fully working yet.

**Comment by Sharcoux** [comment]
Feature done on npm package `@cantoo/pdf-lib`. Some details might change in the next few days, but don't hesitate to try and report.

@Hopding it will get more and more complex to merge our 2 projects if they keep diverging. Don't hesitate to tell me the course of action you'd prefer.

**Comment by pythongod** [comment]
@Sharcoux thanks for the great work. I don't see updated documentation on this here: https://github.com/cantoo-scribe/pdf-lib Can you give as a hint?

**Comment by nimpsch** [comment]
@pythongod
I saw in the code that there is a new parameter for the constructor "password". This code worked for me on multiple PDFs:
`PDFDocument.load(pdfBytes, { password: "" });`

@Sharcoux Great work :)

**Comment by RenaudF** [comment]
@nimpsch 

I had a look but couldn't find anything about the `password` argument, could you point me in the right direction?

**Comment by nimpsch** [comment]
@RenaudF 
This should the be line -> https://github.com/cantoo-scribe/pdf-lib/blob/fbba827a9ceada27ad7d6f3b9b79600ea5ac1820/src/api/PDFDocument.ts#L139

**Comment by Sharcoux** [comment]
![image](https://github.com/Hopding/pdf-lib/assets/797545/b0a90020-e3a5-4a98-adcc-83e6615f2587)

**Comment by sujit-kamireddy** [comment]
Has this change been published? I am using the v1.17.1 (https://www.npmjs.com/package/pdf-lib), which is the latest, but I can't find the password field.

In the npmjs url, it shows that the package is last published 2 years ago? That doesn't sound right.

**Comment by Sharcoux** [comment]
> Has this change been published? I am using the v1.17.1 (https://www.npmjs.com/package/pdf-lib), which is the latest, but I can't find the password field.
> 
> In the npmjs url, it shows that the package is last published 2 years ago? That doesn't sound right.

It's done only in @cantoo/pdf-lib
It's a fork. The current project is apparently on hold, but we actively maintain the fork.

**Comment by sujit-kamireddy** [comment]
> > Has this change been published? I am using the v1.17.1 (https://www.npmjs.com/package/pdf-lib), which is the latest, but I can't find the password field.
> > In the npmjs url, it shows that the package is last published 2 years ago? That doesn't sound right.
> 
> It's done only in @cantoo/pdf-lib It's a fork. The current project is apparently on hold, but we actively maintain the fork.

Thank you @Sharcoux . I am now using @cantoo/pdf-lib and its great.

**Comment by tarcisiomiranda** [comment]
+1

**Comment by tijmenvanetten** [comment]
+1

**Comment by enoh-barbu** [comment]
+5

**Comment by troublesprouter** [comment]
Did the official library end up supporting decryption?
