### ISSUE TITLE
Working with a PDF document encrypted with User Password

### ISSUE THREAD

**Issue by ithillel-aminev** [Hopding/pdf-lib#24]
Hi @Hopding. Is it possible to perform any manipulations with a PDF document encrypted with User Password? 

Now when trying to open a user password encrypted PDF the lib fails at node_modules/pdf-lib/lib/core/pdf-parser/parseDict.js:55 line: 

> var _a = parseName_1.default(remainder) || utils_1.error('Failed to parse dictionary key'), key = _a[0], r1 = _a[1];

**Comment by Hopding** [comment]
`pdf-lib` doesn't currently have any special support for encryption/decryption of documents. However, I think it should still be able to parse the document (which, from the error you shared, is what is failing). If you're able to share a document that you are having trouble with, I can take a look at the issue.

I don't plan on adding encryption/decryption support in the near term. There are too many other things that are more pressing that I have to work on. But I am open to providing support for it eventually. It really depends upon how many users need encryption/decryption support.

**Comment by Hopding** [comment]
I'm going to go ahead and close this issue for now. But please feel free to reopen it if you would still like some assistance!
