### ISSUE TITLE
Insert Euro Symbol into an Input Field

### ISSUE THREAD

**Issue by philipjmurphy** [Hopding/pdf-lib#242]
Hi @Hopding,

Trying to get a simple euro € symbol inserted into a PDF, but it doesn't get correctly encoded. I've attached a simple example - looks like this.

![image](https://user-images.githubusercontent.com/1055915/69499264-15d98580-0ee8-11ea-86fb-e71d7937f5ca.png)

I've also tried to embed a standard font, but still to no avail. Could you provide a little guidance please.

Thanks,

Philip

[euro-symbol-test.zip](https://github.com/Hopding/pdf-lib/files/3883973/euro-symbol-test.zip)

Have a look at line 67 that updates the field: acroField.set(PDFName.of('V'), PDFString.of(value))

**Comment by florianbepunkt** [comment]
@philipjmurphy Facing the same issue. Had the problem with other pdf libs before. Have you found a solution?

**Comment by philipjmurphy** [comment]
Afraid not. I’ll post back if a solution arises.

**Comment by florianbepunkt** [comment]
Interestingly the € and ¬ sign have similiar utf16 representation of 0x20AC and 0x00AC. Maybe there is a typo in the parser @Hopding?

**Comment by florianbepunkt** [comment]
@philipjmurphy Think I found a fix.

When setting the value of your field, you need to use `PDFHexString.fromText()` instead of `PDFString.of()`. This fixes the encoding issue.

```
acroField.set(PDFName.of("V"), PDFHexString.fromText("10€")); // produces correct € sign
acroField.set(PDFName.of("V"), PDFString.of("10€"));
```

**Comment by philipjmurphy** [comment]
Sweet - works like magic 😄
