### ISSUE TITLE
[Feature Request]: Encrypt a document

### ISSUE THREAD

**Issue by michaelktree** [Hopding/pdf-lib#243]
Hi,
In our app, we create new documents, and edit existing ones.
The documents we are manipulating are not encrypted, however I need to encrypt the new and edited documents I create.
Is that possible in pdf-lib?
I know this option exists in other libraries.
Thanks, and very nice work!

**Comment by Hopding** [comment]
Hello @michaelktree! It is not currently possible to encrypt a document with pdf-lib. However, this is a feature I'd be willing to consider adding. Especially if anybody would like to submit a PR for it.

**Comment by terehov** [comment]
Hi @Hopding thank you for this amazing library. Do you think you can point me in any direction, how this could be achieved? I am moving from PDFkit and really need this functionality. So before using any background unix programs thought of trying to add it here.

**Comment by Hopding** [comment]
Hello @terehov! I'd suggest reading through section **7.6 Encryption** of the [PDF specification](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) to learn about how encryption in PDFs works. After that, you might find it useful to reference the encryption implementations of other PDF libraries, such as PDFKit's [`security.js`](https://github.com/foliojs/pdfkit/blob/master/lib/security.js). Feel free to ask further questions should you decide to try implementing this!

**Comment by cboivin80** [comment]
For encryption support, that doc seen more simple ... 
https://www.cs.cmu.edu/~dst/Adobe/Gallery/anon21jul01-pdf-encryption.txt

**Comment by cboivin80** [comment]
If that documentation could help. 
https://www.cs.cmu.edu/~dst/Adobe/Gallery/anon21jul01-pdf-encryption.txt

**Comment by bluepuma77** [comment]
It would be really great to get an option to password protect PDFs with pdf-lib. 

Most other programming languages seem to have a library, but I can not find anything in NodeJS.

**Comment by Darkripper214** [comment]
I roughly got it how `pdfkit` implements their `encryption`. Their `security` class have everything we needed here, however I'm a little bit confused on overall flow of what happens after `pdfDoc.save()` run. Tried running with debugger on in `scratchpad` but can't really get through with flow of functions call.

If i got it correctly, i need to make sure the `security` object get pushed into `pdfDoc.context` before `PDFWriter.serializeToBuffer()` get called.

Could you kindly explain how `PDFWriter` is actually go through all the objects in `pdfDoc` and write it out as buffer?  I kind of know that `indirectObjects` is all the stuff that is inside the body of PDF, and `copyStringIntoBuffer` is the function that actually translate the data into buffer. I am still not sure how it does it in a way that is in the correct sequence.


Also, is there any good way to use existing `objects` to transform this 
```javascript
{
  Filter: 'Standard',
  V: 4,
  Length: 128,
  CF: { StdCF: { AuthEvent: 'DocOpen', CFM: 'AESV2', Length: 16 } },
  StmF: 'StdCF',
  StrF: 'StdCF',
  R: 4,
  O: <Buffer 92 38 64 75 aa 6b 97 4e f1 36 c0 49 b1 84 36 29 e4 4a f3 35 15 d1 c9 79 52 7d 69 0a a1 4b b9 9f>,
  U: <Buffer 45 1c 32 86 38 e4 5d ad 4c d6 80 f7 db 96 80 9e 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
  P: -3904
}
```
Into this? the closest I found is `PDFDict`, but the implementation is a little bit intimidating.
```
<<
/Filter /Standard
/V 4
/Length 128
/CF <<
/StdCF <<
/AuthEvent /DocOpen
/CFM /AESV2
/Length 16
>>
>>
/StmF /StdCF
/StrF /StdCF
/R 4
/O <0ba3835f88f90388e74e54584125ce142be0de24c6b0d37746e075b891756671>
/U <c2972c316687773966df3c7952b4332000000000000000000000000000000000>
/P -3904
>>
endobj
```

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by iampato** [comment]
To add on this,
Can I use `pdf-lib` to open a password protected pdf

**Comment by KTBsomen** [comment]
> To add on this, Can I use `pdf-lib` to open a password protected pdf

no
