### ISSUE TITLE
drawImage not working, export blank pdf

### ISSUE THREAD

**Issue by xt1991** [Hopding/pdf-lib#249]
Hi Sir, 
 I saw you code about draw image in there
https://pdf-lib.js.org/docs/api/classes/pdfpage#drawimage

But when i used it in my project

There is not working and pdf file is blank

My version "pdf-lib": "^1.2.1", 
My code as below :

`
const { PDFDocument, StandardFonts, rgb, degrees } = require('pdf-lib')

const page = newPdf.addPage([10000, 10000])

const arrayBuffer = await fetch('img.jpg').then(res => res.arrayBuffer())

const jpgImage = await newPdf.embedJpg(arrayBuffer)

page.drawImage(jpgImage, {
              x: 0,
              y: 0,
              width: 800,
              height: 500,
            })
`

Hope to hear from you soon !!!

**Comment by xt1991** [comment]
So sorry , my mistake

**Comment by MarcelloTheArcane** [comment]
@xt1991 What was the mistake?
