### ISSUE TITLE
Problem with PDFDocumentFactory.load some usual non-encrypted PDF documents

### ISSUE THREAD

**Issue by ithillel-aminev** [Hopding/pdf-lib#25]
Hi @Hopding. There are problems with importing some usual **non-encrypted** PDF documents via PDFDocumentFactory.load method. While these documents are still could be opened by common viewer programs and even other libraries still can manage with that files (e.d. modify and so on). Problems I faced so far: 

at node_modules/pdf-lib/es/core/pdf-document/PDFDocument.js:249
`validate(catalog, isInstance(PDFCatalog), '"catalog" must be a PDFCatalog object');`

at node_modules/pdf-lib/lib/core/pdf-parser/parseDict.js:67
`utils_1.error('Failed to parse dictionary value'), pdfObject = _b[0], r2 = _b[1];`

If it helps, I think I could even provide those pdf files that cause problems.

**Comment by Hopding** [comment]
If you can share the PDFs you’re having trouble loading, I’d be happy to take a look. It’s probably an issue with `pdf-lib`’s parser.

**Comment by Hopding** [comment]
I'm going to go ahead and close this issue for now. But please feel free to reopen it if you would still like some assistance!

**Comment by ithillel-aminev** [comment]
I've sent a letter with problem PDF samples. Thank you for help.

**Comment by Hopding** [comment]
@ithillel-aminev I just spent a few minutes testing `pdf-lib`'s parser on the documents you emailed to me. It is failing due to a bug in the parser. It should be a pretty quick and simple fix. I'll try to push a fix and and cut a new patch release this evening (or else in the coming days).

**Comment by Hopding** [comment]
@ithillel-aminev I just published a new pre-release: [`0.3.1-rc2`](https://www.npmjs.com/package/pdf-lib/v/0.3.1-rc2). It contains the parser fixes I made in https://github.com/Hopding/pdf-lib/pull/29. Please try it out when you get a chance and let me know if it works for you.

You can install this new version with npm:
```
npm install pdf-lib@0.3.1-rc2
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.3.1-rc2/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.3.1-rc2/dist/pdf-lib.min.js

**Comment by ithillel-aminev** [comment]
I've checked. It works perfectly. When are you going to merge it to main branch ?

**Comment by Hopding** [comment]
It's actually already been merged into the `master` branch. I've just not yet published a full release to NPM. I'll probably do this over the weekend. There are some other changes I'd like to include in the next release as well (e.g. https://github.com/Hopding/pdf-lib/pull/28).

You shouldn't need to wait to use the fix though. The pre-release is perfectly safe to use. The only thing that maks it a pre-release is that it's published under the `--next` tag, so it's not the default version installed by `npm install pdf-lib`. I also don't create [release notes](https://github.com/Hopding/pdf-lib/releases) for pre-releases.

**Comment by Hopding** [comment]
Version [`0.4.0`](https://www.npmjs.com/package/pdf-lib/v/0.4.0) is now published. It contains the parser bug fixes for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.4.0).

You can install this new version with npm:
```
npm install pdf-lib@0.4.0
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.4.0/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.4.0/dist/pdf-lib.min.js
