### ISSUE TITLE
[Feature Request]: Option for `page.drawImage` to draw behind existing content on page

### ISSUE THREAD

**Issue by jtinbergen** [Hopding/pdf-lib#251]
It is very useful when either merging PDF's or adding watermarks to PDFs to be able to draw an image on a page behind all the existing content instead of adding it over everything else at the end.

This is often useful when dealing with a PDF letter background you want to inject for company wide styling on documents.

**Comment by mseshachalam** [comment]
@Hopding hey you done with this ? Can you point me how to do this ?

**Comment by Hopding** [comment]
@mseshachalam I'm afraid I don't have time at the moment to create an example demonstrating how to do this. But essentially you'd need to change the position at which the content stream is inserted: 

https://github.com/Hopding/pdf-lib/blob/3c11ddfded4250e96c7e7f97c92c45754f9e7bee/src/api/PDFPage.ts#L1314

https://github.com/Hopding/pdf-lib/blob/3c11ddfded4250e96c7e7f97c92c45754f9e7bee/src/core/structures/PDFPageLeaf.ts#L119-L123

Rather than pushing the content stream to the end of the `Contents` array, you'd need to push it to the start, or perhaps somewhere in the middle.

**Comment by uchamad** [comment]
Just want to share my solution to this scenario of adding background image to an existing page. It may be useful to someone looking for a solution.

```
async function addBackgroundImageToPdf(pdfBytes, imageUrl, outputFilePath) {
  const pdfDoc = await PDFDocument.load(pdfBytes);
  const {width, height} = pdfDoc.getPages()[0].getSize();

  const imageBytes = await fetch(imageUrl).then((res) => res.arrayBuffer());
  const backgroundImage = await pdfDoc.embedJpg(imageBytes);

  const copiedPages = await pdfDoc.copyPages(pdfDoc, [0])
  const [firstPage] = copiedPages;

  const embeddedPage = await pdfDoc.embedPage(firstPage);

  const newPage = pdfDoc.insertPage(0);
  newPage.drawImage(backgroundImage, {
    x: 0,
    y: 0,
    width: width,
    height: height,
    blendMode: 'Normal',
  });
  newPage.drawPage(embeddedPage);
  pdfDoc.removePage(1);

  const pdfBytesWithBackground = await pdfDoc.save();
  fs.writeFileSync(outputFilePath, pdfBytesWithBackground);
}
```

I am simply copying the contents of an existing page to a new page with an image background and then removing the original page.

**Comment by yvesh** [comment]
Another workaround for backgrounds is just using `pdfDoc.embedPng` with a transparent background image (instead of a white one). This only works if there should be no text on the background ofc.

P.S.: An option would be nice 👍

**Comment by gavinoliver** [comment]
Based on what @Hopding said, I changed the PDFArray order in my PDFPageLeaf.
```typescript
const template = await fetch(`${templatesUrl}/bridge-card-dielines`).then(res => res.arrayBuffer());
const pdfDoc = await PDFDocument.load(template);
const firstPage = pdfDoc.getPage(0);

const embeddedImage = await pdfDoc.embedPng(image);
firstPage.drawImage(embeddedImage, {
    // x, y, width, height
});

const contents = firstPage.node.Contents();
if (contents instanceof PDFArray) {
    const contentsArray = contents.asArray();
    const newContents = pdfDoc.context.obj([
        contents.get(contentsArray.length - 1), 
        ...contentsArray.slice(0, contentsArray.length - 2)
    ]);
    firstPage.node.set(PDFName.Contents, newContents);
}
```
In my case, the dieline of a template pdf file had to appear on top of my embedded image. Embedding the first page again before removing it made it loose the pdf layer connection for toggling the dieline on and off. Hence the validation for printing failed. So I had the leave the template pretty much untouched.

Hope that helps someone. ✌

**Comment by akash-ramaswamy** [comment]
> Based on what @Hopding said, I changed the PDFArray order in my PDFPageLeaf.
> 
> ```ts
> const template = await fetch(`${templatesUrl}/bridge-card-dielines`).then(res => res.arrayBuffer());
> const pdfDoc = await PDFDocument.load(template);
> const firstPage = pdfDoc.getPage(0);
> 
> const embeddedImage = await pdfDoc.embedPng(image);
> firstPage.drawImage(embeddedImage, {
>     // x, y, width, height
> });
> 
> const contents = firstPage.node.Contents();
> if (contents instanceof PDFArray) {
>     const contentsArray = contents.asArray();
>     const newContents = pdfDoc.context.obj([
>         contents.get(contentsArray.length - 1), 
>         ...contentsArray.slice(0, contentsArray.length - 2)
>     ]);
>     firstPage.node.set(PDFName.Contents, newContents);
> }
> ```
> 
> In my case, the dieline of a template pdf file had to appear on top of my embedded image. Embedding the first page again before removing it made it loose the pdf layer connection for toggling the dieline on and off. Hence the validation for printing failed. So I had the leave the template pretty much untouched.
> 
> Hope that helps someone. ✌

@gavinoliver thanks a lot. It helped me in a production issue ❤️
