### ISSUE TITLE
How to merge pdf documents using pdf-lib

### ISSUE THREAD

**Issue by Sampadaak2613** [Hopding/pdf-lib#252]
How to merge multiple pdf documents into a single pdf document.
I am using Sharepoint Document Library and SPFx webpart.
Any idea?

**Comment by Hopding** [comment]
Hello @Sampadaak2613! The [Copy Pages](https://github.com/Hopding/pdf-lib#copy-pages) example demonstrates the pdf-lib features you'll want to use when merging documents. In addition, here's an example that demonstrates how to merge two PDF documents (`a.pdf` and `b.pdf`) into a single `PDFDocument` object:
```js
const mergedPdf = await PDFDocument.create();

const pdfA = await PDFDocument.load(fs.readFileSync('a.pdf'));
const pdfB = await PDFDocument.load(fs.readFileSync('b.pdf'));

const copiedPagesA = await mergedPdf.copyPages(pdfA, pdfA.getPageIndices());
copiedPagesA.forEach((page) => mergedPdf.addPage(page));

const copiedPagesB = await mergedPdf.copyPages(pdfB, pdfB.getPageIndices());
copiedPagesB.forEach((page) => mergedPdf.addPage(page));

const mergedPdfFile = await mergedPdf.save();
```

I hope this helps. Please let me know if you have any additional questions!

**Comment by obabichev** [comment]
Hi, I tried to use this solution and it brokes the links inside the document. I mean, if there is for example table of content with clickable links they will be broken...

But in general, this solution returns merged pdf.

**Comment by Hopding** [comment]
@obabichev Please see https://github.com/Hopding/pdf-lib/issues/341.

**Comment by obabichev** [comment]
@Hopding Thank you for the answer, I think I spend not enough time to look at the other issues

**Comment by Hopding** [comment]
@obabichev No worries!

**Comment by icodeforlove** [comment]
@Hopding thanks for that bit.

I needed to be able to merge any amount of pdf buffers, and not just 2. But with a few changes your code worked great.

```javascript
async function mergePDFDocuments(documents) {
	const mergedPdf = await PDFDocument.create();

	for (let document of documents) {
		document = await PDFDocument.load(document);

		const copiedPages = await mergedPdf.copyPages(document, document.getPageIndices());
		copiedPages.forEach((page) => mergedPdf.addPage(page));    
	}
	
	return await mergedPdf.save();
}
```

**Comment by svendehens** [comment]
@icodeforlove Could you tell me how you define 'documents', or with what values? I'm trying to merge pdf's from local storage, after the user selects some documents to be merged. I've been trying to pass the function different kinds of values but keep getting type errors.

**Comment by icodeforlove** [comment]
@svendehens sorry in this situation they would be the file buffers, this was used on the server-side.

**Comment by Sjoerd82** [comment]
It works.. kinda. I'm merging multiple PDF's with forms on them, but the form data remains hidden. I think maybe you can't have multiple AcroForms? I set the NeedAppearances to true. Separately each PDF works, but when merged this seems to be ignored and the result is a nicely merge PDF, but no (visible) data.

**Comment by zakpatterson** [comment]
To anyone seeing the above comment, yes it seems we still can't have multiple forms combined into a single document, but you can do this:
```
    const files: Array<[FormData, PDFDocument]> = await getFiles(f1040)
    // create a final master file
    const single = await PDFDocument.create()

    const pdfBytes = await Promise.all(
      files.map(async ([formData, f]) => {
        // Insert field values into form fields:
        fillPDF(f, formData)
        // Save the filled form to a byte array
        const pageBytes = await f.save() 
        // Reload those bytes as a new PDF and combine
        const filledForm = await PDFDocument.load(pageBytes)
        const newPages = await single.copyPages(filledForm, filledForm.getPageIndices())
        newPages.forEach((p) => single.addPage(p))
      })
    )
    .then(async () => await single.save())

**Comment by jelizarovas** [comment]
With promise all i had problem where the documents would be merged in a random order. The ones who were processed faster would show up earlier in the merged doc.

My current solution is

i have a react app with couple of pdfs in public/pdf, and also have Array of fields and values that i would like to fill in the form.

```
const files = [
  "pdf/Buyers order.PDF",
  "pdf/Arbitration agreement.pdf",
  "pdf/As Is Disclaimer.pdf",
  "pdf/Buyers Guide.pdf",
  "pdf/Vehicle title application.pdf",
];
```

```
const fillData = {
  "CONTRACT NR": "1",
  DATE: "9/14/2021",
  PRICE: "2999",
  "SALES TAX": "311.90",
[...]
};
```

```
export async function fillPDF(data) {
  // https://github.com/Hopding/pdf-lib/issues/252

  const pdfDoc = await PDFDocument.create();

  const setField = (form, pdfField, value, condition = false) => {
    if (!pdfField || !value || condition) return;
    if (Array.isArray(value)) value = value.join(", ");
    if (!form.getFieldMaybe(pdfField)) return;
    return form.getTextField(pdfField).setText(value.toString());
  };

  const getFile = async (pdf) => {
    const baseUrl = window.location.origin.toString() + process.env.PUBLIC_URL + "/";
    const formPdfBytes = await fetch(baseUrl + pdf).then((res) => res.arrayBuffer());
    const currentDocument = await PDFDocument.load(formPdfBytes);

    const form = currentDocument.getForm();

    for (const [key, value] of Object.entries(fillData)) {
      setField(form, key, value);
    }

    form.flatten();
    await currentDocument.save();

    const coppiedPages = await pdfDoc.copyPages(currentDocument, currentDocument.getPageIndices());
    coppiedPages.forEach((page) => pdfDoc.addPage(page));
    return currentDocument;
  };

  for (let file of files) {
    await getFile(file);
  }

  return await pdfDoc.save();
}
```

And finally have a component with a button onClick event and getPDF function that uses `downloadjs`
```
const getPDF = async (e) => {
    download(await fillPDF(), `file.pdf`, "application/pdf");
  };
```

` <Button onClick={getPDF}>FILL PDF</Button>`

**Comment by Brainpitcher** [comment]
Hi there from the future) trying to use pdf-lib 1.17.1 to merge multiply files but have no luck and get one corrupted file.
here is my code:
```

import { PDFDocument } from 'pdf-lib';
import express from 'express';
import multer from 'multer';
import cors from 'cors';

const app = express();

// Enable CORS
app.use(cors());

// Set up multer to handle file uploads
const upload = multer({
  storage: multer.memoryStorage(),
  limits: {
    fileSize: 10 * 1024 * 1024, // 10 MB limit
  },
});

// Define a route for merging PDF files
app.post('/merge', upload.array('pdfs', 10), async (req, res) => {
  const contentType = req.headers['content-type'];
  if (!contentType || !contentType.startsWith('multipart/form-data')) {
    return res.status(400).send('Expected multipart/form-data request');
  }
  // Get an array of PDF buffers from the uploaded files
  const pdfBuffers = (req.files as Express.Multer.File[])?.map((file) => file.buffer);

  if (!pdfBuffers) {
    return res.status(400).send('No PDFs provided');
  }

  // Merge the PDFs into a single PDF document
  const mergedPdf = await PDFDocument.create();
  for (const pdfBuffer of pdfBuffers) {
    const pdf = await PDFDocument.load(pdfBuffer);
    const pages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
    for (const page of pages) {
      mergedPdf.addPage(page);
    }
  }

  // Send the merged PDF as a response
  const mergedPdfBytes = await mergedPdf.save();
  res.type('application/octet-stream').send(mergedPdfBytes);
});

// Start the server
app.listen(3000, () => {
  console.log('PDF merging API listening on port 3000');
});

```
as i can see from the container logs and post with curl everything uploads and downloads but every time i am getting the corrupted merge file
what do i have to do to fix it? Can you give me a hand?
PS all files are very simple and validating perfectly

**Comment by Jxmedia** [comment]
> Hello @Sampadaak2613! The [Copy Pages](https://github.com/Hopding/pdf-lib#copy-pages) example demonstrates the pdf-lib features you'll want to use when merging documents. In addition, here's an example that demonstrates how to merge two PDF documents (`a.pdf` and `b.pdf`) into a single `PDFDocument` object:
> 
> ```js
> const mergedPdf = await PDFDocument.create();
> 
> const pdfA = await PDFDocument.load(fs.readFileSync('a.pdf'));
> const pdfB = await PDFDocument.load(fs.readFileSync('b.pdf'));
> 
> const copiedPagesA = await mergedPdf.copyPages(pdfA, pdfA.getPageIndices());
> copiedPagesA.forEach((page) => mergedPdf.addPage(page));
> 
> const copiedPagesB = await mergedPdf.copyPages(pdfB, pdfB.getPageIndices());
> copiedPagesB.forEach((page) => mergedPdf.addPage(page));
> 
> const mergedPdfFile = await mergedPdf.save();
> ```
> 
> I hope this helps. Please let me know if you have any additional questions!

From 5 years in the future.....this works perfectly, saved me some extra hours of research

**Comment by Ericokim** [comment]
@icodeforlove  Here is an updated version of your code for my Reactjs project. 

 ```javaScript
const mergePDFHandler = async (documents) => {
    const mergedPdf = await PDFDocument.create();

    for (const document of documents) {
      const existingPdfBytes = await fetch(document).then((res) =>
        res.arrayBuffer()
      );

      const pdfDoc = await PDFDocument.load(existingPdfBytes);

      const copiedPages = await mergedPdf.copyPages(
        pdfDoc,
        pdfDoc.getPageIndices()
      );
      copiedPages.forEach((page) => mergedPdf.addPage(page));
    }

    const pdfBytes = await mergedPdf.save();

    const docUrl = URL.createObjectURL(
      new Blob([pdfBytes], { type: "application/pdf" })
    );

    let iframe = document.createElement("iframe");
    document.body.appendChild(iframe);

    iframe.style.display = "none";
    iframe.src = docUrl;
    iframe.onload = () => {
      setTimeout(() => {
        iframe.focus();
        iframe.contentWindow.print();
      }, 1);
    };
  };
```
