### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by jotae1e** [Hopding/pdf-lib#257]
I am wondering if it's posible transform an encrypted document to one unencrypted copying pages from the document encrypted to the another with this library.

Is any differerence between if the document is encrypted for reading or for another permissions?

Can anyone guide me?

Thanks

**Comment by Hopding** [comment]
Hello @jotae1e! pdf-lib does [not currently support](https://github.com/Hopding/pdf-lib#encryption-handling) reading/writing encrypted documents at all. However, this is a feature that will likely be implemented in the future. The request is currently being tracked in #233. So I'm going to close this issue in favor of that one, to keep things organized.
