### ISSUE TITLE
AcroForm Field Structures By Field Type

### ISSUE THREAD

**Issue by cshenks** [Hopding/pdf-lib#262]
As a step toward a general AcroForms API, we want individual structures to represent the different possible types of AcroForm fields.

### Tasks
- [x] Button Field (#263)
- [x] Text Field (#264)
- [x] Choice Field (#265)
- [ ] Signature Field (#266 )

### Dependencies
- Requires #261 

Parent #263 
Parent #264 
Parent #265 
Parent #266

**Comment by Hopding** [comment]
@cshenks I'm hoping that I'll have some time free up this next week or two to help contribute to the AcroForms API work. At the moment I'm thinking I'll work on setting up the high level APIs (whatever those might look like - not sure atm) for the end-user to read and manipulate acroforms. I'll probably start with buttons and radio groups. Please let me know if there's anything you think I should know or be aware of before starting!
