### ISSUE TITLE
Unable to display content of PDF on IE11 and Edge

### ISSUE THREAD

**Issue by Sampadaak2613** [Hopding/pdf-lib#274]
Hi All,

I am using the pdf-lib library in SPFX list view command set to edit the footer of a PDF using drawtext. It works fine in google chrome browser. However it does nothing at all in IE 11 and Edge. 

Here is the code which I have used - 

const url = 'https://pdf-lib.js.org/assets/with_update_sections.pdf'
  const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

  const pdfDoc = await PDFDocument.load(existingPdfBytes)
  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

  const pages = pdfDoc.getPages()
  const firstPage = pages[0]
  const { width, height } = firstPage.getSize()
  firstPage.drawText('This text was added with JavaScript!', {
    x: 5,
    y: height / 2 + 300,
    size: 50,
    font: helveticaFont,
    color: rgb(0.95, 0.1, 0.1),
    rotate: degrees(-45),
  })

  const pdfBytes = await pdfDoc.save()

**Comment by Hopding** [comment]
Hello @Sampadaak2613. I'm afraid I can't help you without more information. You said "it does nothing at all in IE 11 and Edge". What exactly do you mean by this? Does it throw an error?

**Comment by Sampadaak2613** [comment]
Hi Andrew,

In IE 11, it is giving error as Type Error : Slice is undefined.
When I debug the code, it is giving error in BaseParser.js, PDFParser.js
file where Slice function is used


Regards,
Sampada

**Comment by Hopding** [comment]
It looks like IE11 does not have a `TypedArray.prototype.slice` implementation, hence the error. You can try adding a polyfill. Such as [this one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#Polyfill) from MDN:
```js
if (!Uint8Array.prototype.slice) {
  Object.defineProperty(Uint8Array.prototype, 'slice', {
    value: function (begin, end)
     {
        return new Uint8Array(Array.prototype.slice.call(this, begin, end));
     }
  });
}
```

**Comment by Sampadaak2613** [comment]
Hi there,

Thanks for your inputs. I will try this solution.
I have raised new ticket (#277) for this same issue where I have attached details of the issues.
Request you to please provide your input on the same.
