### ISSUE TITLE
Failed to load resource: the server responded with a status of 429 ()

### ISSUE THREAD

**Issue by Raneto4ka** [Hopding/pdf-lib#279]
Hello!
I add your library on the unpkg CDN: https://unpkg.com/pdf-lib/dist/pdf-lib.min.js.
But today i have a problem. This link doesn't work. How can I use your library again?

thanks

**Comment by Hopding** [comment]
Hello @Raneto4ka! It looks like unpkg was recently down for a few hours (see https://github.com/mjackson/unpkg/issues/237). However, it appears to be back up and running, so you should no longer have this issue.

This is always a risk when using a CDN, unfortunately. You may wish to consider hosting the files yourself to avoid this in the future. But if you really must use a CDN, you can download pdf-lib from [jsDelivr](https://www.jsdelivr.com/) as well as unpkg (I'll make a note of this in the README). Here are the jsDelivr links for pdf-lib:

* https://cdn.jsdelivr.net/npm/pdf-lib/dist/pdf-lib.js
* https://cdn.jsdelivr.net/npm/pdf-lib/dist/pdf-lib.min.js

Note that if you wish to use the CDN scripts in production, you should include a specific version number in the URL, for example: 

* https://cdn.jsdelivr.net/npm/pdf-lib@1.3.0/dist/pdf-lib.min.js
