### ISSUE TITLE
Merging multiple pdf's to single pdf (Sharepoint SPFx Extension)

### ISSUE THREAD

**Issue by Sampadaak2613** [Hopding/pdf-lib#281]
Hi,

With reference to #252 , regarding copy page, I am using below code but it copies 0th Page of 2nd Pdf after 0th page of 1st pdf.

`import { PDFDocument } from 'pdf-lib'

async function copyPages() {
  const url1 = 'PDF Document 1 URL from Sharepoint Document Library'
  const url2 = 'PDF Document 2 URL from Sharepoint Document Library'

  const firstDonorPdfBytes = await fetch(url1).then(res => res.arrayBuffer())
  const secondDonorPdfBytes = await fetch(url2).then(res => res.arrayBuffer())

  const firstDonorPdfDoc = await PDFDocument.load(firstDonorPdfBytes)
  const secondDonorPdfDoc = await PDFDocument.load(secondDonorPdfBytes)

  const pdfDoc = await PDFDocument.create();

  const [firstDonorPage] = await pdfDoc.copyPages(firstDonorPdfDoc, [0]) // 0th Page of PDF 1
  const [secondDonorPage] = await pdfDoc.copyPages(secondDonorPdfDoc, [0]) // 0th Page of PDF 2

  pdfDoc.addPage(firstDonorPage)
  pdfDoc.insertPage(0, secondDonorPage)

  const pdfBytes = await pdfDoc.save()
}
`

I want to merge multiple pdf files in a one file.
Lets say, in Pdf 1, I am having 4 pages and in Pdf 2, I am having 5 page.
I want to generate Pdf 3 which should contain 9 pages ( Pages of Pdf1 + Pdf 2).
While merging, I want to add blank page between these 2 pdf's.

--------------------------------------------------------------------------------------------------------

I am trying to use below code mentioned in #189 now.
In this, I will convert my selected pdf's in BASE64 format and then will pass to PDFDocument Object

`const mergedPdf = await PDFDocument.create();

const pdfA = await PDFDocument.load(base64DataUriA);
const pdfB = await PDFDocument.load(base64DataUriB);

const copiedPagesA = await mergedPdf.copyPages(pdfA, pdfA.getPageIndices());
copiedPagesA.forEach((page) => mergedPdf.addPage(page));

const copiedPagesB = await mergedPdf.copyPages(pdfB, pdfB.getPageIndices());
copiedPagesB.forEach((page) => mergedPdf.addPage(page));

const mergedPdfFile = await mergedPdf.save();
`

**Comment by Hopding** [comment]
Hello @Sampadaak2613. If you want to add blank pages between the copied pages, you'll need to call `pdfDoc.addPage()` between adding each copied page to the merged PDF. For example:
```js
const mergedPdf = await PDFDocument.create();

const pdfA = await PDFDocument.load(...);
const pdfB = await PDFDocument.load(...);

const copiedPagesA = await mergedPdf.copyPages(pdfA, pdfA.getPageIndices());
const copiedPagesB = await mergedPdf.copyPages(pdfB, pdfB.getPageIndices());

const allCopiedPages = [...copiedPagesA, ...copiedPagesB];

allCopiedPages.forEach((page, idx) => {
  mergedPdf.addPage(page);
  if (idx < allCopiedPages.length - 1) {
    const { width, height } = page.getSize()
    mergedPdf.addPage([width, height]);
  }
});

const mergedPdfFile = await mergedPdf.save();
```

**Comment by Sampadaak2613** [comment]
Hi,

Thanks for your help.
It worked as expected.
