### ISSUE TITLE
Cannot apply digital signature with 'unidoc' after drawing image with 'pdf-lib'

### ISSUE THREAD

**Issue by hotuy** [Hopding/pdf-lib#288]
I have problem from pdf after add image and sign digital signature!

I add image to my pdf from Angular client by `pdf-lib`, after that, i submit pdf bytes to server golang, finally golang server using `unidoc` to sign my file with cert on server. But not success. Because had problem with new files created by `pdf-lib`.

You can test yourself pdf with image from your server in here: [embed_png_and_jpeg_images.pdf](https://pdf-lib.js.org/assets/embed_png_and_jpeg_images.pdf) .I used [unidoc](https://github.com/unidoc/unipdf) to sign above pdf not working. Nothing signature displayed here:
<img width="371" alt="Screen Shot 2019-12-29 at 10 06 19 AM" src="https://user-images.githubusercontent.com/1819570/71551833-e22bd700-2a22-11ea-9c4d-ce7e8b9dc1a6.png"> 

But when i use another standard file, example this file: [SAMPLE PDF.pdf](https://github.com/Hopding/pdf-lib/files/4007707/SAMPLE.PDF.pdf), it's ok.
I using acrobat reader to verify signature: 
<img width="305" alt="Screen Shot 2019-12-29 at 10 10 07 AM" src="https://user-images.githubusercontent.com/1819570/71551871-6d0cd180-2a23-11ea-885f-c209650d452a.png">

With my angular code, when i using pdf-lib, i comment code add image, it's working, but when i open code add image, it's not working.

```
lastPage.drawImage(jpgImage, {
            x: offsetLeft,
            y: offsetTop,
            width: width,
            height: height,
        })
```

Please help me!

**Comment by Hopding** [comment]
Hello @hotuy! Can you please provide the following additional information?
* Is your Go server-side code generating any logs, errors, warnings, or stacktraces when it attempts to apply the signature via `unidoc`? If so, would you please provide them?
* Is your JS client-side code generating any logs, errors, warnings, or stacktraces when you modify the PDF with `pdf-lib`? If so, would you please provide them?
* Can you please share before and after versions of your file (so 4 files in total)? For example:
  * `unsigned_pdf_without_image.pdf`
  * `signed_pdf_without_image.pdf`
  * `unsigned_pdf_with_image.pdf`
  * `signed_pdf_with_image.pdf`
* Are you able to modify PDF files with `pdf-lib` in **any** way, other than drawing images (e.g. drawing text or shapes), and successfully apply a signature with `unidoc`?
* Would you please provide the portions of your code where you are using `pdf-lib` to modify PDFs?

**Comment by hotuy** [comment]
Hi @Hopding .
- My server and JS Client don't generate any logs or errors, if have i had showed in here.
- Sorry, don't relative with drawImage, but i only load arrayBuffer pdf by `pdf-lib` and output new arrayBuffer, and file cannot apply digital signature.

```
import { PDFDocument } from 'pdf-lib';
async addSign() {
 const pdfDoc = await PDFDocument.load(this.source);
 return await pdfDoc.save()
}
```

[unsigned_pdf_without_pdf_lib.pdf](https://github.com/Hopding/pdf-lib/files/4008179/unsigned_pdf_without_pdf_lib.pdf)
[signed_pdf_without_pdf_lib.pdf](https://github.com/Hopding/pdf-lib/files/4008180/signed_pdf_without_pdf_lib.pdf)
[unsigned_pdf_with_pdf_lib.pdf](https://github.com/Hopding/pdf-lib/files/4008183/unsigned_pdf_with_pdf_lib.pdf)
[signed_pdf_with_pdf_lib.pdf](https://github.com/Hopding/pdf-lib/files/4008184/signed_pdf_with_pdf_lib.pdf)

Pdf buffer input: 
<img width="1008" alt="Screen Shot 2019-12-29 at 10 25 01 PM" src="https://user-images.githubusercontent.com/1819570/71558851-28685100-2a8a-11ea-9d99-103f9c89ba77.png">

Pdf buffer after load and save by pdf-lib:
<img width="869" alt="Screen Shot 2019-12-29 at 10 25 10 PM" src="https://user-images.githubusercontent.com/1819570/71558853-2f8f5f00-2a8a-11ea-8ac6-d886592379da.png">

**Comment by Hopding** [comment]
@hotuy I took a look at the documents you shared. I am unable to find anything wrong with the document saved by `pdf-lib` (`unsigned_pdf_with_pdf_lib.pdf`). However, it does seem that there might be a missing object in the signed version of the file (`signed_pdf_with_pdf_lib.pdf`):
```
$ qpdf --check signed_pdf_with_pdf_lib.pdf
WARNING: signed_pdf_with_pdf_lib.pdf: reported number of objects (41) inconsistent with actual number of objects (40)
checking signed_pdf_with_pdf_lib.pdf
PDF Version: 1.7
File is not encrypted
File is not linearized
```
It's possible this is why the signatures aren't showing up in Acrobat. But I'm not sure which object is missing. The signature objects all appear to be present in the file and wired up correctly. Meaning:
* The catalog references an AcroForm dictionary
* The AcroForm dictionary references two signature widgets in its `Fields` array
* Each of the signature widgets references a corresponding signature dictionary via their `V` entries
* Each of the signature dictionaries has the required entries (including `Contents` and `ByteRange`)

So I'm not exactly sure what is wrong here. It doesn't appear to be the case that the signatures are invalid. If that was the case, Acrobat should show them and indicate their invalidity. But that isn't what is happening. Acrobat just isn't showing them at all.

This seems more likely to be an issue in the code you are using to sign the document with `unidoc`, or perhaps in `unidoc` itself. After all, `unidoc` is what is generating the signatures, not `pdf-lib`. I would suggest that you reach out to `unidoc` and see what they have to say about it. And feel free to share a link to this thread with them when you do.

Lastly, you might try saving the PDF without using object streams and see what happens:
```diff
import { PDFDocument } from 'pdf-lib';
async addSign() {
 const pdfDoc = await PDFDocument.load(this.source);
- return await pdfDoc.save()
+ return await pdfDoc.save({ useObjectStreams: false })
}
```
This will cause `pdf-lib` to save the document in a slightly different format. It's possible that you'll have more luck applying a digital signature when the document in saved in this alternate format. (Even though both formats are equally valid).

**Comment by hotuy** [comment]
Great @Hopding , i had resolved problem, may be `unidoc` unlicense, so pdffile had been truncated somewhere with objectStreams=true...
Thank you very much and have a nice day!

**Comment by hotuy** [comment]
Hi @Hopding ,Problem not resolved, it's not problem of unlicense unidoc, with small pdf file i had upload above, it's ok, but it has problem with many another pdf file:

Example:

[sample_pdf_not_signed.pdf](https://github.com/Hopding/pdf-lib/files/4057200/sample_pdf_not_signed.pdf)
[sample_pdf_signed_without_pdflib.pdf](https://github.com/Hopding/pdf-lib/files/4057202/sample_pdf_signed_without_pdflib.pdf)
[sample_pdf_signed_with_pdflib.pdf](https://github.com/Hopding/pdf-lib/files/4057204/sample_pdf_signed_with_pdflib.pdf)

File with name sample_pdf_signed_without_pdflib, signed valid:
<img width="784" alt="Screen Shot 2020-01-14 at 10 29 55 AM" src="https://user-images.githubusercontent.com/1819570/72311906-e27dd080-36b8-11ea-89e9-bda003527d81.png">

File with name sample_pdf_signed_with_pdflib.pdf, signed but not valid sign:

<img width="918" alt="Screen Shot 2020-01-14 at 10 20 44 AM" src="https://user-images.githubusercontent.com/1819570/72311857-a5b1d980-36b8-11ea-8a58-d22a5cf7b0c3.png">

Please help me.

**Comment by Hopding** [comment]
@hotuy Are you trying to use pdf-lib to modify an existing PDF that already has a signature?

**Comment by Hopding** [comment]
I’m going to close this since it’s been several days. But feel free to reopen if you’re still having problems.
