### ISSUE TITLE
Restrictions of an encrypted document

### ISSUE THREAD

**Issue by jotae1e** [Hopding/pdf-lib#291]
I was making tests with encrypted documents and if the document it's encrypted but has disabled some restrictions like "printing", I can create one blank pdf and copy all the pages to this one.  This has not restrictions and it's editable.  

But, is there any method to get the restrictions of the document?  At this moment only method "isEncrypted" is available.

May I suggest to implement another method to get restrictions?

Thanks in advance

**Comment by Hopding** [comment]
@jotae1e Are you saying you have a source PDF which is both encrypted and also has restrictions disallowing printing? And you're able to copy pages from this encrypted and restricted PDF into a new document that does not retain either the encryption or restrictions?

**Comment by jotae1e** [comment]
Well, I have this pdf that I download from internet to test pdf-lib.

> https://drive.google.com/file/d/1xn9w7rDag10sMq0ZAPeZdQoZksg1UM5t/view?usp=sharing

When I tried to load in pdf-lib, throws an error because is encrypted, by change, I charged I can saw it in pdf-viewer in angular.

Then, I open the properties of this pdf in acrobat reader and said that it's protected by password some functions.  (It's in Spanish, but I thinks that you can understand it)

> https://drive.google.com/file/d/1xn9w7rDag10sMq0ZAPeZdQoZksg1UM5t/view?usp=sharing


(I made the copy with hummus (not support pdf encryption too), because I didn't see that pdf-lib has a create method.  :-)

I think that could be the same in pdf-lib, but I doesn't try it, but I can think that it will be the same.  I will try it today at night.

**Comment by jotae1e** [comment]
I test it with  a simple code like this:

`
this.http.get('assets/test.pdf', { responseType: 'arraybuffer' })
      .subscribe(

        async data => {

          const pdfDocOriginal = await PDFDocument.load(data, { ignoreEncryption: true });

          const pdfDocSalida = await PDFDocument.create();

          const copiedPages = await pdfDocSalida.copyPages(pdfDocOriginal, [0, 1]);
          const [p0, p1] = copiedPages;

          pdfDocSalida.addPage(p0);
          pdfDocSalida.addPage(p1);

          const pdfBytes = await pdfDocSalida.save();

          const blob = new Blob([pdfBytes], {
            type: 'application/pdf'
          });

          FileSaver.saveAs(blob);

        }

      );

`
And, as you know, blank pages are inserted.

If it helps you, know that with hummus and without entering the password of the file, copying of pages is allowed and working. In fact, I am currently doing this process, but I have to send the file to the server and wait for the return to continue processing in the client with your pdf-lib.

**Comment by Hopding** [comment]
@jotae1e It looks like `pdf-lib` is behaving as expected. The [README has a section](https://github.com/Hopding/pdf-lib#encryption-handling) explaining that `pdf-lib` does not support encrypted documents. And while you can tell it to ignore the encryption, that does not mean it decrypts the file:

> Note that **using this option does not decrypt the document**. This means that any modifications you attempt to make on the returned `PDFDocument` may fail, or have unexpected results.

The blank pages you end up copying fall under the "may fail, or have unexpected results" warning.

The reason that HummusJS does not require you to enter a password is that the document uses the default PDF password. I explain more about how this works here: https://github.com/Hopding/pdf-lib/issues/134#issuecomment-509452191.

So, having explained all of this, I'm not sure if there's anything remaining for this issue? Do you have a feature request, or were you just not expected `pdf-lib` to handle the encrypted document as it does?

**Comment by jotae1e** [comment]
Yes.  All it's working as expected.  

I will close the issue because we must wait until support for encrypted documents are ready.

Thanks a lot.

**Comment by troublesprouter** [comment]
Did the official library end up supporting decryption?
