### ISSUE TITLE
Document is unreadable

### ISSUE THREAD

**Issue by Serhioromano** [Hopding/pdf-lib#305]
I have a very simple code. Open the document and save it

```js
let pdfBookBytes = fs.readFileSync(dir.build + "book.pdf");
let pdfBookDoc = await PDFDocument.load(pdfBookBytes);
let bookBytes = pdfBookDoc.save();
fs.writeFileSync(dir.build + "book2.pdf", bookBytes);
```

But after that the new document is unreadable. Although I di not do any manipulations with it. Very obvious I miss something but I cannot guess what.

**Comment by Hopding** [comment]
@Serhioromano It looks like you forgot to `await` the promise returned by `pdfDoc.save()`. Try this:
```diff
let pdfBookBytes = fs.readFileSync(dir.build + "book.pdf");
let pdfBookDoc = await PDFDocument.load(pdfBookBytes);
- let bookBytes = pdfBookDoc.save();
+ let bookBytes = await pdfBookDoc.save();
fs.writeFileSync(dir.build + "book2.pdf", bookBytes);
```

**Comment by Serhioromano** [comment]
Oh my! How could I miss this! Thank you! Now everything works just fine.
