### ISSUE TITLE
can i use this to manually draw rectangles over pdf?

### ISSUE THREAD

**Issue by kishandonepudi** [Hopding/pdf-lib#32]
I mean, can i open some PDF file and draw some line/rectangles/circles/arrow head over the pdf and save it?

**Comment by Hopding** [comment]
You certainly can. Here are some examples of PDF modification:

* https://github.com/Hopding/pdf-lib#document-modification
* https://github.com/Hopding/pdf-lib/tree/master/examples/document_modification/node

Let me know if you run into any trouble and I can provide more assistance 👍
