### ISSUE TITLE
Croping images when drawing

### ISSUE THREAD

**Issue by syonfox** [Hopding/pdf-lib#322]
I believe this is not possible in the current version. but it would be nice to be able to add an portion of an image to the pdf with `drawImage()` maybe something like `drawImageCrop(x,y,width,height,[top,botom,left,right])`

Anyways Ill keep looking for another solution but if anyone know if this is possible or if there is an easy way of coping Blob or base64url images in js let me know.

**Comment by syonfox** [comment]
if anyon gose down the same rabit hole as me here is a solution:

```function resizeImage(url, x, y,width, height, callback) {
    var canvas = document.createElement("canvas");
    var context = canvas.getContext('2d');
    var imageObj = new Image();

    // set canvas dimensions

    canvas.width = width;
    canvas.height = height;

    imageObj.onload = function () {
        context.drawImage(imageObj, x, y, width, height, 0, 0, width, height);
        callback(canvas.toDataURL());
    };

    imageObj.src = url;
}```

**Comment by Hopding** [comment]
@syonfox Have you tried using the clipping operators? Here's an example: https://github.com/Hopding/pdf-lib/issues/160#issuecomment-523205152.
