### ISSUE TITLE
Inverse Y for beggining to top of page

### ISSUE THREAD

**Issue by TheMechanic** [Hopding/pdf-lib#325]
Hi,
Is there a way to inverse Y layout to begin at top of the page (0 = top) ?

Thanks

**Comment by Hopding** [comment]
Hello @TheMechanic! 

I'm afraid there is no way to do this. The PDF specification defines `y=0` at the bottom of the page and `pdf-lib` does not build any abstraction on top of this. If you need to draw something a certain distance from the top of the page, the best approach is to get the height of the page with [`PDFPage.getHeight()`](https://pdf-lib.js.org/docs/api/classes/pdfpage#getheight) and subtract from it. For example:
```js
const pdfDoc = await PDFDocument.create();

const page = pdfDoc.addPage();

const offset = 25;
const fontSize = 25;
page.drawText('Foo', {
  x: offset,
  y: page.getHeight() - (offset + fontSize),
  size: fontSize,
});

const pdfBytes = await pdfDoc.save();
```
