### ISSUE TITLE
RTL ?

### ISSUE THREAD

**Issue by tsabbay** [Hopding/pdf-lib#326]
Hi Guys,
Any documentation/support regarding RTL texts?
Much appreciated,
B.

**Comment by Hopding** [comment]
Hello @tsabbay!

The high level [`PDFPage.drawText()`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawtext) API does not provide special support for RTL text. However, I do think that would be a valuable feature to offer. 

Can you please provide an example of exactly what you are trying to do? I'll then be able to share example code to demonstrate how you can achieve it with pdf-lib's current APIs.

**Comment by Hopding** [comment]
I'm going to close this issue for now. Please feel free to reopen it if you would like to discuss this further.

**Comment by YumcoderCom** [comment]
such as :

![image](https://user-images.githubusercontent.com/29568969/98230004-dfb5da00-1f6f-11eb-9ad2-9fef4d025a1e.png)

https://fonts.google.com/specimen/Amiri?subset=arabic&query=amiri&sidebar.open=true&selection.family=Amiri#standard-styles

**Comment by meirlamdan** [comment]
I enclose an example of why we need support for languages ​​that are rtl.
The example below has text with the words "Hello World" in Hebrew and English.
And as you can see that English text ends at the location of the line, but in Hebrew it starts from the line (and can even exceed the page ...)


[Hello World.pdf](https://github.com/Hopding/pdf-lib/files/9085905/Hello.World.pdf)
