### ISSUE TITLE
How to get working without web browser

### ISSUE THREAD

**Issue by sudachi808** [Hopding/pdf-lib#327]
I try to oepn a PDF without web browser.

However, I get the error below.

```main.js
// main.js
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
```

```bash
$ node -v
v12.14.1
$ node main.js
/private/tmp/proj/main.js:1
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```
What is the right way to work this code?

**Comment by Mysteryum** [comment]
> I try to oepn a PDF without web browser.
> 
> However, I get the error below.
> 
> ```js
> // main.js
> import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
> ```
> 
> ```shell
> $ node -v
> v12.14.1
> $ node main.js
> /private/tmp/proj/main.js:1
> import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at Module._compile (internal/modules/cjs/loader.js:891:18)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
>     at Module.load (internal/modules/cjs/loader.js:811:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
>     at internal/main/run_main_module.js:17:11
> ```
> 
> What is the right way to work this code?

const PDFDocument = require("pdf-lib").PDFDocument
    , rgb = require("pdf-lib").rgb

**Comment by sudachi808** [comment]
>const PDFDocument = require("pdf-lib").PDFDocument

@Mysteryum 
I did not know this solution.
Thank you so much 🙏   

I continue to get work the [example](https://www.npmjs.com/package/pdf-lib#create-document).

```main.js
// main.js
const PDFDocument = require("pdf-lib").PDFDocument
const StandardFonts = require("pdf-lib").StandardFonts

const pdfDoc = PDFDocument.create()
const timesRomanFont = pdfDoc.embedFont(StandardFonts.TimesRoman)
```
So, This code gets below😕
```
$ node main.js 
/private/tmp/proj/main.js:5
const timesRomanFont = pdfDoc.embedFont(StandardFonts.TimesRoman)
                              ^

TypeError: pdfDoc.embedFont is not a function
    at Object.<anonymous> (/private/tmp/proj/main.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
``` 

Something is missing❓

**Comment by Hopding** [comment]
@sudachi808 You need to either `await` or use promise chaining. For example:
```js
const { PDFDocument, StandardFonts } = require("pdf-lib");

(async () => {
  const pdfDoc = await PDFDocument.create();
  const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
})();
```
or
```js
const { PDFDocument, StandardFonts } = require("pdf-lib");

PDFDocument.create().then(pdfDoc => {
  return pdfDoc.embedFont(StandardFonts.TimesRoman);
}).then(timesRomanFont => {
  // ...
});
```
