### ISSUE TITLE
Example of modifying existing "word"

### ISSUE THREAD

**Issue by richardfrost** [Hopding/pdf-lib#33]
First off, thanks for this great project, it looks like you have made awesome progress on it. I am looking for a way to modify an existing word inside a pdf. For example, say I want to replace any instance of `the` in the document and replace it with an all caps version `THE`.

An example of what I'm hoping for might be something like this:

```js
import { PDFDocumentFactory, PDFDocumentWriter, drawText } from 'pdf-lib';

const existingPdfDocBytes = fs.readFileSync('testFiles/test.pdf');
const pdfDoc = PDFDocumentFactory.load(existingPdfDocBytes);
const pages = pdfDoc.getPages();

// Code describing what I think I want to do
pages.forEach(function(page) {
  // Need to look through each word on each page:
  page.Content.magicFunction.words.forEach(function(word){
    let wordText = word.toString();
    if (wordText.match(/^the$/)) {
      wordText = wordText.toUpperCase();
    }

    drawText(
      wordText,
      word.coordinates.x,
      words.coordinates.y,
      ...
    );
  });
});
```

Is this in the scope of the project? Is it already implemented and I'm just missing it? Thanks for your time. If this isn't in the scope feel free to just close this.

**Comment by Hopding** [comment]
Hi there @richardfrost. It is not currently possible to parse the _content_ of a page with `pdf-lib`. However, if you have some other means of knowing where the text is (getting its x & y coords on a page), you could use `pdf-lib` to draw _over_ it. You might be able to use [`psf2json`](https://github.com/modesty/pdf2json) to locate the text.
