### ISSUE TITLE
Find a string in the PDF

### ISSUE THREAD

**Issue by gonzaloramirezabella** [Hopding/pdf-lib#331]
Hi, I dont know if it´s possible, but i´m trying to find some text in the PDF document, to replace it. 
Wich is the better way to do this, if there is a way.

Thanks for the project, is amazing.

**Comment by Hopding** [comment]
Hello @gonzaloramirezabella!

This is not currently possible to do with pdf-lib. See my comment here for more details: https://github.com/Hopding/pdf-lib/issues/33#issuecomment-420740506.
