### ISSUE TITLE
"Uncaught incorrect header check" when trying to modify pdf

### ISSUE THREAD

**Issue by Cvanvollenstee** [Hopding/pdf-lib#34]
Hi,

I'm trying to modify a pdf document with the UMD Module. I keep getting an "Uncaught incorrect header check" (pdf-lib.js:14849). It seem to be happening from documents saved as in Word.

I'm using this version: https://unpkg.com/pdf-lib@0.3.1-rc3/dist/pdf-lib.js

Any help would be appreciated.

[Test1.pdf](https://github.com/Hopding/pdf-lib/files/2450284/Test1.pdf)

**Comment by Hopding** [comment]
Hello @Cvanvollenstee. I just tried using `pdf-lib` to open and modify the document you shared. It worked fine for me, so I don't _think_ it's a bug in `pdf-lib`. Would you mind sharing a code snippet or HTML file that I can use to reproduce the error?

**Comment by Cvanvollenstee** [comment]
Thanks for your response. I'm just trying to get the example up and running.
I get the error on the PDFDocumentFactory.load.
I take a base64 pdf string convert it to UInt8Array and parse it through in the load function.

I'm quite sure the conversion is correct, because it is working with other pdf's.



[Working_Base64.txt](https://github.com/Hopding/pdf-lib/files/2466093/Working_Base64.txt)
[Test1_not_working_base64.txt](https://github.com/Hopding/pdf-lib/files/2466094/Test1_not_working_base64.txt)

This is what I'm seeing when trying to load Test.pdf:
![image](https://user-images.githubusercontent.com/19389583/46760149-8cf68f00-ccd1-11e8-919c-a45d42d4507a.png)

This is the piece of code I use:
`// UMD module`
`var PDFDocumentFactory = PDFLib.PDFDocumentFactory;`
`const existingPdfDocBytes = base64ToUint8Array(base64);`
`const pdfDoc = PDFDocumentFactory.load(existingPdfDocBytes);`

`function base64ToUint8Array(base64) {`
`      var raw = atob(base64);`
`      var uint8Array = new Uint8Array(raw.length);`
`      for (var i = 0; i < raw.length; i++) {`
`        uint8Array[i] = raw.charCodeAt(i);`
`      }`
`      return uint8Array;`
`}`

**Comment by Hopding** [comment]
Dealing with binary data in JavaScript is rather tricky. It's easy to make subtle mistakes (I made **so** many in the process of creating `pdf-lib`).

It looks like your `base64ToUint8Array` has a bug. It works by converting your base64 string into a "binary" string, then taking the character codes of the binary string's characters and putting them in a `Uint8Array`. This only works if you're lucky enough to have a base64 string that when decoded, can be represented in unicode codepoints. But there's no guarantee that the bytes of a PDF file have to be entirely unicode. And when they aren't, your `base64ToUint8Array` function is silently corrupting the data. 

There's a nice library on NPM that can handle the conversion from `base64 string -> binary Uint8Array` for you: [`base64-arraybuffer`](https://github.com/niklasvh/base64-arraybuffer). I've used it myself successfully. If you aren't using a package manager, you can just copy/paste the code from here: https://github.com/niklasvh/base64-arraybuffer/blob/master/lib/base64-arraybuffer.js#L39-L66

**Comment by jaserma** [comment]
Hi @Hopding,

I have the same problem than @Cvanvollenstee. I convert a base64 code (created with Word, exported to pdf) to arraybuffer with the base64-arraybuffer library. After, I convert arraybuffer to Uint8 but I get the error: Uncaught incorrect header check. 

``` 
    let buffer = base64_arraybuffer.decode(res.file);
    var uint8View = new Uint8Array(buffer);
    const pdfDoc = PDFDocumentFactory.load(uint8View);
```

Something wrong?

**Comment by Hopding** [comment]
Hello @jaserma.

The snippet you shared doesn't look wrong. I can help you further if you supply the following information:
* Is the PDF you are working with encrypted or password protected? That is one potential cause of an `incorrect header check` error (see https://github.com/Hopding/pdf-lib/issues/61). 
* What is `res.file`?
