### ISSUE TITLE
Possibility to modify encrypted PDF using password

### ISSUE THREAD

**Issue by aawaken** [Hopding/pdf-lib#342]
Hello,
we need a feature for modifying an encrypted PDF using password. Is this planned in the next future?

Thanks
Andre

**Comment by Hopding** [comment]
Hello @aawaken!

This feature will eventually be added to pdf-lib. There is not currently an ETA date, however. I’m going to close this issue as we are tracking this in https://github.com/Hopding/pdf-lib/issues/233.
