### ISSUE TITLE
Is there a way to catch user input value from the form field?

### ISSUE THREAD

**Issue by jumpypixels** [Hopding/pdf-lib#343]
First thank you for such a great job.
I used pdf-lib with a file with acroFields. I found only prefilled fields and pdf-lib updated fields  can be saved but If a user manually add/update a value, it won't be saved.
Is there a way to record user updated fields?

Thanks

Henry

**Comment by Hopding** [comment]
Hello @jumpypixels!

I’m afraid I do not understand what you mean by the following:
> I found only prefilled fields and pdf-lib updated fields can be saved but If a user manually add/update a value, it won't be saved.
> Is there a way to record user updated fields?

Can you provide an example, and perhaps some code snippets, to clarify what you are asking about?

**Comment by jumpypixels** [comment]
I uploaded a test project:
https://github.com/jumpypixels/pdftest
It's an react frontend project displaying the template.pdf from your sample project:
https://github.com/Hopding/pdf-lib/files/3693350/pdf-lib_form_fill_example_3.zip

I filled in the age field with my keyboard, pressed the download button from the viewer, the age field in the downloaded file was empty.
I added console.log for the age field, the value was not changed before/after I typed in age value:

The source code is at:
https://github.com/jumpypixels/pdftest/blob/master/src/PDFTest.js

If I open the template.pdf using Acrobat reader, fill in the form field, I have the option to save what I just put in. What I'm asking is if pdf-lib can provide the same function?

Thanks

**Comment by Hopding** [comment]
Hello @jumpypixels!

It sounds like you've pretty much figured out the issue, based on your comment in #346. However, I should mention that it wouldn't be _impossible_ to build something that could do what you are describing. For example, if you rendered the PDF with [`pdf.js`](https://github.com/mozilla/pdf.js) you could inspect the changes a user made to the AcroForm fields via the DOM and translate those to modifications of the actual PDF file using pdf-lib's loading/editing capabilities. Note that this might require some changes to `pdf.js` to support editing of AcroForm fields. I _think_ that right now they only support read-only AcroForm fields.

**Comment by jumpypixels** [comment]
You're right. I found a commercial solution based on the pdfjs (https://pdfjs.express/). They may just did what you mentioned.

**Comment by drafs10** [comment]
I suppose nothing has changed in the pdf-lib to support this issue. @jumpypixels @Hopding is there any
 open source solution you had found for this?
