### ISSUE TITLE
Cant write in react native the file help please

### ISSUE THREAD

**Issue by diegommc** [Hopding/pdf-lib#344]
hello please help, im new coding in RN and java, i have problems writing in the device storage i tried with RN fetch blob
fs.writeFile
and
Fs.CreateFile and i got this errors

![image](https://user-images.githubusercontent.com/60480117/73475522-28dc5c00-4356-11ea-8ef1-14b424a34ee2.png)
possible unhandled promise rejection id0:

(async () => {
  const pdfDoc = await PDFDocument.create()
  const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman)

  const page = pdfDoc.addPage()
  const { width, height } = page.getSize()
  const fontSize = 30
  page.drawText('Creating PDFs in JavaScript is awesome!', {
    x: 50,
    y: height - 4 * fontSize,
    size: fontSize,
    font: timesRomanFont,
    color: rgb(0, 0.53, 0.71),
  })

  const pdfBytes = await pdfDoc.save()
  const dirs = RNFetchBlob.fs.dirs
      
    
      const NEW_FILE_PATH = dirs.DownloadDir + '/test22.pdf'
     RNFetchBlob.fs.writeFile(NEW_FILE_PATH, pdfBytes,'utf-8')
    })();

please help me thanks in advance

**Comment by diegommc** [comment]
got it

**Comment by EricWiener** [comment]
@diegommc what did you need to do?

**Comment by Hopding** [comment]
There is an example React Native app that should demonstrate how to write documents to the file system if you're having trouble: https://github.com/Hopding/pdf-lib/tree/master/apps/rn
