### ISSUE TITLE
PDF version 1.7

### ISSUE THREAD

**Issue by jumpypixels** [Hopding/pdf-lib#349]
I tried to extract acro fields from IRS 1040 form (https://www.irs.gov/pub/irs-pdf/f1040.pdf) but failed.
Is it because of the version? The irs form is version 1.7
I had no problem to get fields from a 1.3 version PDF file.

The code I used:

```js
const getAcroFields = (pdfDoc) => {
    if (!pdfDoc.catalog.get(PDFName.of('AcroForm'))) return [];
    const acroForm = pdfDoc.context.lookup(pdfDoc.catalog.get(PDFName.of('AcroForm')));

    if (!acroForm.get(PDFName.of('Fields'))) return [];
    const acroFields = acroForm.context.lookup(acroForm.get(PDFName.of('Fields')));

    return acroFields.array.map(ref => acroForm.context.lookup(ref));
};
```

**Comment by Hopding** [comment]
Hello @jumpypixels!

The problem has nothing to do with PDF versions. It's actually due to the fact that the `f1040.pdf` file you shared contains nested acroform fields. I wrote a script to traverse the nested field tree and produce a single flat array of all the acroform fields in the document:

```js
import fs from 'fs';
import { PDFArray, PDFDict, PDFDocument, PDFName } from 'pdf-lib';

const recurseAcroFieldKids = (field: PDFDict) => {
  const kids = field.lookupMaybe(PDFName.of('Kids'), PDFArray);
  if (!kids) return [field];

  const acroFields = new Array<PDFDict>(kids.size());
  for (let idx = 0, len = kids.size(); idx < len; idx++) {
    acroFields[idx] = field.context.lookup(kids.get(idx), PDFDict);
  }

  const flatKids: PDFDict[] = [];
  for (let idx = 0, len = acroFields.length; idx < len; idx++) {
    flatKids.push(...recurseAcroFieldKids(acroFields[idx]));
  }

  return flatKids;
};

const getRootAcroFields = (pdfDoc: PDFDocument) => {
  if (!pdfDoc.catalog.get(PDFName.of('AcroForm'))) return [];
  const acroForm = pdfDoc.context.lookup(
    pdfDoc.catalog.get(PDFName.of('AcroForm')),
    PDFDict,
  );

  if (!acroForm.get(PDFName.of('Fields'))) return [];
  const acroFieldRefs = acroForm.context.lookup(
    acroForm.get(PDFName.of('Fields')),
    PDFArray,
  );

  const acroFields = new Array<PDFDict>(acroFieldRefs.size());
  for (let idx = 0, len = acroFieldRefs.size(); idx < len; idx++) {
    acroFields[idx] = pdfDoc.context.lookup(acroFieldRefs.get(idx), PDFDict);
  }

  return acroFields;
};

(async () => {
  const pdfDoc = await PDFDocument.load(fs.readFileSync('f1040.pdf'));

  const rootFields = getRootAcroFields(pdfDoc);

  const fields: PDFDict[] = [];
  for (let idx = 0, len = rootFields.length; idx < len; idx++) {
    fields.push(...recurseAcroFieldKids(rootFields[idx]));
  }

  fields.forEach((field) => {
    console.log(String(field));
    console.log();
  });

  console.log('Total fields:', fields.length);
})();
```

Here's some of the script's output:
```
<<
/AP <<
/D <<
/1 929 0 R
/Off 930 0 R
>>
/N <<
/1 928 0 R
>>
>>
/AS /Off
/DA (/ZaDb 5.6 Tf 0 g /ZaDb 5.6 Tf 0 g )
/F 4
/FT /Btn
/MK <<
/CA (4)
>>
/P 927 0 R
/Parent 131 0 R
/Rect [ 95.599 716.002 103.599 724.002 ]
/StructParent 1
/Subtype /Widget
/T (þÿc1_01[0])
/Type /Annot
>>

...

<<
/DA (/HelveticaLTStd-Bold 8.00 Tf 0.000 0.000 0.502 rg)
/F 4
/FT /Tx
/MK <<
>>
/MaxLen 10
/P 1 0 R
/Parent 129 0 R
/Q 1
/Rect [ 509.745 306 576 317.999 ]
/StructParent 117
/Subtype /Widget
/T (þÿf2_37[0])
/Type /Annot
>>

Total fields: 116
```

As you can see, it finds 116 total fields.

I hope this helps! Please let me know if you have any additional questions.

**Comment by jumpypixels** [comment]
Thank you for the help. 
I have a suggestion related to the same document. From the output of your script, you will notice some special characters(/T (þÿf2_37[0])) in the name value. I can remove them with regular expression but it will be better it can be done by pdf-lib itself.  I'm not sure it's a bug or come from the document itself. I used pdfjs and Winking's PDF Analyzer, they both have no special characters in the value.
Regards

Henry

**Comment by Hopding** [comment]
@jumpypixels The special characters you're encountering are actually the raw encoded name of the field in the PDF file. `pdf-lib` doesn't currently contain APIs to decode these text strings. However, support for this will hopefully land when https://github.com/Hopding/pdf-lib/pull/336 is completed.

**Comment by Hopding** [comment]
`pdf-lib` now has form creation and filling APIs that should be used instead of the above example(s). See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFForm.getFields`](https://pdf-lib.js.org/docs/api/classes/pdfform#getfields) method is of particular relevance to this issue.
