### ISSUE TITLE
drawText reference point and baseline

### ISSUE THREAD

**Issue by syonfox** [Hopding/pdf-lib#355]
I am playing around with drawing text in predefined boxes and having issues centering it.
I looked through some of the other issues on centering text but don't see a clear answer to this so sorry if I missed something :)
or if this is just me using the wrong numbers.

Either way I think it would be valuable to add this info to the page.drawText() documentation

what is the reference point for drawing text?  
![image](https://user-images.githubusercontent.com/9345677/74586678-d4182280-4f9e-11ea-9666-9a1e2b4a883d.png)

I thought it was the bottom of the descender(A in fig)
but my drawings are off and I was trying to find the information and cant :(

if you know please tell me if at the baseline(B) or even at the top (C)

also, I assume font. heightAtSize(size) is the height from the top of the ascender to the bottom of the descender. if the text is drawn from the baseline is it possible to measure either the height from the top of the text to the baseline or vis versa.

**Comment by Hopding** [comment]
Hello @syonfox! 

The reference point for `drawText` is the baseline of the font being used. The `heightOfFontAtSize` methods return the difference between the ascender and descender of the font (times a scaling factor). Here's the relevant source code for the standard and custom font embedders for reference:

https://github.com/Hopding/pdf-lib/blob/0578530f222db72bf3ca321488d5fccee05793cd/src/core/embedders/StandardFontEmbedder.ts#L70-L75

https://github.com/Hopding/pdf-lib/blob/0578530f222db72bf3ca321488d5fccee05793cd/src/core/embedders/CustomFontEmbedder.ts#L71-L76

I hope this helps. Please let me know if you have any additional questions!
