### ISSUE TITLE
Can I create pdf from html?

### ISSUE THREAD

**Issue by Raneto4ka** [Hopding/pdf-lib#358]
Hi!
I need to get PDF-file from HTML block, can i use your lib?
like here: https://codepen.io/Raneto4ka/full/MWwyqom (btn 'Get PDF')
Thanks

**Comment by Hopding** [comment]
Hello @Raneto4ka! I’m afraid pdf-lib does not support converting HTML to PDF. Please see https://github.com/Hopding/pdf-lib/issues/176#issuecomment-527265939.
