### ISSUE TITLE
Cant figure out how to delete a certain page using your modify document method 

### ISSUE THREAD

**Issue by sammanton** [Hopding/pdf-lib#359]
Hey Guys,

Odd one i know but how would you go about removing a certain page number(for me its the first page) using the methods you have been using below ?
```
<html>
  <head>
    <meta charset="utf-8" />
    <script src="https://unpkg.com/pdf-lib@1.3.0"></script>
    <script src="https://unpkg.com/downloadjs@1.4.7"></script>
  </head>

  <body>
    <p>Click the button to modify an existing PDF document with <code>pdf-lib</code></p>
    <button onclick="modifyPdf()">Modify PDF</button>
    <p class="small">(Your browser will download the resulting file)</p>
  </body>

  <script>
    const { degrees, PDFDocument, rgb, StandardFonts } = PDFLib

    async function modifyPdf() {
      // Fetch an existing PDF document
      const url = 'https://pdf-lib.js.org/assets/with_update_sections.pdf'
  		const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

      // Load a PDFDocument from the existing PDF bytes
      const pdfDoc = await PDFDocument.load(existingPdfBytes)

      // Embed the Helvetica font
      const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

      // Get the first page of the document
      const pages = pdfDoc.getPages()
      const firstPage = pages[0]
      const secondPage = pages[0]

      // Get the width and height of the first page
      const { width, height } = firstPage.getSize()

      // Draw a string of text diagonally across the first page
      firstPage.drawText('This text was added with JavaScript!', {
        x: 5,
        y: height / 2 + 300,
        size: 50,
        font: helveticaFont,
        color: rgb(0.95, 0.1, 0.1),
        rotate: degrees(-45),
      })

      // Serialize the PDFDocument to bytes (a Uint8Array)
      const pdfBytes = await pdfDoc.save()

			// Trigger the browser to download the PDF document
      download(pdfBytes, "pdf-lib_modification_example.pdf", "application/pdf");
    }
  </script>
</html>
```

**Comment by Hopding** [comment]
Hello @sammanton!

Have you tried the `PDFDocument.removePage` method? (https://pdf-lib.js.org/docs/api/classes/pdfdocument#removepage)

**Comment by sammanton** [comment]
Hey Andrew,

Thank you for replying, I had added this in however the code still does not look correct. Again really sorry as JS not my strongest point. The code i have been trying is below:

Thanks
Sam

<html>
  <head>
    <meta charset="utf-8" />
    <script src="https://unpkg.com/pdf-lib@1.3.0"></script>
    <script src="https://unpkg.com/downloadjs@1.4.7"></script>
  </head>

  <body>
    <p>Click the button to modify an existing PDF document with <code>pdf-lib</code></p>
    <button onclick="modifyPdf()">Modify PDF</button>
    <p class="small">(Your browser will download the resulting file)</p>
  </body>

  <script>
    const { degrees, PDFDocument, rgb, StandardFonts } = PDFLib

    async function modifyPdf() {
      // Fetch an existing PDF document
      const url = 'https://pdf-lib.js.org/assets/with_update_sections.pdf'
  		const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

      // Load a PDFDocument from the existing PDF bytes
      const pdfDoc = await PDFDocument.load(existingPdfBytes)

      // Embed the Helvetica font
      const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

      // Get the first page of the document
      const pages = pdfDoc.getPages()
      const firstPage = pages[0]
      const secondPage = pages[0]

      // Get the width and height of the first page
      const { width, height } = firstPage.getSize()

     pdfDoc.removePage(0)   // Remove the first page of the document
     pdfDoc.removePage(2)   // Remove the third page of the document
     pdfDoc.removePage(197) // Remove the 198th page of the document

      // Serialize the PDFDocument to bytes (a Uint8Array)
      const pdfBytes = await pdfDoc.save()

			// Trigger the browser to download the PDF document
      download(pdfBytes, "pdf-lib_modification_example.pdf", "application/pdf");
    }
  </script>
</html>

**Comment by sammanton** [comment]
Hey @Hopding 
Sorry this is the code in a txt file for better viewing 
[pfdpagedelete.txt](https://github.com/Hopding/pdf-lib/files/4225776/pfdpagedelete.txt)

**Comment by Hopding** [comment]
@sammanton Here's a working version:
```html
<html>
  <head>
    <meta charset="utf-8" />
    <script src="https://unpkg.com/pdf-lib@1.3.0"></script>
    <script src="https://unpkg.com/downloadjs@1.4.7"></script>
  </head>

  <body>
    <p>
      Click the button to modify an existing PDF document with
      <code>pdf-lib</code>
    </p>
    <button onclick="modifyPdf()">Modify PDF</button>
    <p class="small">(Your browser will download the resulting file)</p>
  </body>

  <script>
    const { PDFDocument } = PDFLib;

    async function modifyPdf() {
      // Fetch an existing PDF document
      const url =
        'https://raw.githubusercontent.com/Hopding/pdf-lib/master/assets/pdfs/normal.pdf';
      const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer());

      // Load a PDFDocument from the existing PDF bytes
      const pdfDoc = await PDFDocument.load(existingPdfBytes);

      // Remove the first page of the document
      pdfDoc.removePage(0);

      // Serialize the PDFDocument to bytes (a Uint8Array)
      const pdfBytes = await pdfDoc.save();

      // Trigger the browser to download the PDF document
      download(pdfBytes, 'pdf-lib_modification_example.pdf', 'application/pdf');
    }
  </script>
</html>

```

**Comment by sammanton** [comment]
Thank you @Hopding massive help much appreciated :)
