### ISSUE TITLE
Is it possible to get the size of an existing page?

### ISSUE THREAD

**Issue by gregbacchus** [Hopding/pdf-lib#36]
Hi, 
I'm wanting to load a PDF and read out the size of the first page. Is this possible using `pdf-lib`?

Thanks

**Comment by Hopding** [comment]
Yes, `pdf-lib` can do this. However, the API for it is not currently documented. But I have explained how to do it here: https://github.com/Hopding/pdf-lib/issues/10#issuecomment-402326518. For example:
```js
const pages = pdfDoc.getPages();
const page1 = pages[0];

const PAGE_WIDTH = page1.get('MediaBox').array[2];
const PAGE_HEIGHT = page1.get('MediaBox').array[3];
```
Please let me know if you have any trouble with this.
