### ISSUE TITLE
Form fields and Rotated PDF

### ISSUE THREAD

**Issue by Slyther** [Hopding/pdf-lib#360]
So I've been following the code snippets from https://github.com/Hopding/pdf-lib/issues/205 to fill in some PDF form fields with great results, but some of the PDFs had to be rotated by 90 degrees in order for all PDFs to be in landscape mode. I still have the non-rotated versions, but the end result needs to be in landscape. I'm dealing with single page PDFs.

The issue I encounter is that since the PDF's dimensions and orientation don't really change, the form fields on the rotated PDFs have swapped widths, heights, and text orientations. I tried implementing the code found in https://github.com/Hopding/pdf-lib/issues/147 with no luck, since setting the origin doesn't do anything about the orientation, widths or heights of the document, nor does this seem to be a permanent change on the document after saving it (my hope was that, after changing the origin, new form fields would have correct widths and heights, but they do not).

So I can detect if the document is rotated, and I'm using basically the same code from #205. Is there a way to either:

a) account for the rotation when writing to the form fields, or 
b) create a truly rotated PDF which doesn't just apply a rotation visually to the page, but rather actually changes the orientation of the document (redefines width, height, origin, orientation, etc.)?

I've tried all options on acrobat to create a new PDF to no avail, and I've tried toying around with the code snippet from #205 but I don't have a strong understanding of what the Appearance Stream code is doing in order to modify it to account for rotation.

**Comment by Hopding** [comment]
Hello @Slyther!

Have you tried setting the page’s rotation with `PDFPage.setRotation`? (https://pdf-lib.js.org/docs/api/classes/pdfpage#setrotation)

**Comment by Slyther** [comment]
Hi @Hopding,

The problem is more to do with the notion that the rotation is just a visual change rather than a redefinition of the page's dimensions and orientation. Perhaps my example attached will help with understanding the issue.

Both PDFs have been modified to have form fields, and they both work as intended on Acrobat. The problem would be that one of them has a rotation applied to it, so when filling the PDFs programmatically, the code from #205 doesn't account for this and writes an incorrect Appearance Stream.

I'm also using a rendering library, react-pdf, which renders the annotation layer separately and it also makes a mess out of the form fields.

[PDF Examples.zip](https://github.com/Hopding/pdf-lib/files/4225543/PDF.Examples.zip)

**Comment by Hopding** [comment]
@Slyther

Here's an example script that fills out one of the PDFs you shared, correcting for its rotation:

```js

import {
  asPDFName,
  degrees,
  drawText,
  PDFArray,
  PDFContentStream,
  PDFDict,
  PDFDocument,
  PDFFont,
  PDFHexString,
  PDFName,
  PDFNumber,
  PDFOperator,
  PDFOperatorNames as Ops,
  popGraphicsState,
  pushGraphicsState,
  rgb,
  rotateDegrees,
  StandardFonts,
  translate,
} from 'pdf-lib';

const getAcroForm = (pdfDoc: PDFDocument) =>
  pdfDoc.catalog.lookup(PDFName.of('AcroForm'), PDFDict);

const getAcroFields = (pdfDoc: PDFDocument) => {
  const acroForm = getAcroForm(pdfDoc);
  if (!acroForm) return [];

  const fieldRefs = acroForm.lookupMaybe(PDFName.of('Fields'), PDFArray);
  if (!fieldRefs) return [];

  const fields = new Array(fieldRefs.size());
  for (let idx = 0, len = fieldRefs.size(); idx < len; idx++) {
    fields[idx] = fieldRefs.lookup(idx);
  }
  return fields;
};

const findAcroFieldByName = (pdfDoc: PDFDocument, name: string) => {
  const acroFields = getAcroFields(pdfDoc);
  return acroFields.find((acroField) => {
    const fieldName = acroField.get(PDFName.of('T'));
    return !!fieldName && fieldName.value === name;
  });
};

const fillAcroTextField = (acroField: PDFDict, text: string, font: PDFFont) => {
  const rect = acroField.lookup(PDFName.of('Rect'), PDFArray);
  const width =
    rect.lookup(2, PDFNumber).value() - rect.lookup(0, PDFNumber).value();
  const height =
    rect.lookup(3, PDFNumber).value() - rect.lookup(1, PDFNumber).value();

  const MK = acroField.lookupMaybe(PDFName.of('MK'), PDFDict);
  const R = MK && MK.lookupMaybe(PDFName.of('R'), PDFNumber);
  const rotation = R ? R.value() : 0;

  const N = singleLineAppearanceStream(font, text, rotation, width, height);

  acroField.set(PDFName.of('AP'), acroField.context.obj({ N }));
  acroField.set(PDFName.of('Ff'), PDFNumber.of(1 /* Read Only */));
  acroField.set(PDFName.of('V'), PDFHexString.fromText(text));
};

const beginMarkedContent = (tag: string) =>
  PDFOperator.of(Ops.BeginMarkedContent, [asPDFName(tag)]);

const endMarkedContent = () => PDFOperator.of(Ops.EndMarkedContent);

const singleLineAppearanceStream = (
  font: PDFFont,
  text: string,
  rotation: number,
  width: number,
  height: number,
) => {
  const rotationCorrectedHeight = rotation % 90 === 0 ? width : height;

  const size = font.sizeAtHeight(rotationCorrectedHeight - 8);
  const encodedText = font.encodeText(text);
  const x = 0;
  const y = rotationCorrectedHeight - size;

  return textFieldAppearanceStream(
    font,
    size,
    encodedText,
    rotation,
    x,
    y,
    width,
    height,
  );
};

const textFieldAppearanceStream = (
  font: PDFFont,
  size: number,
  encodedText: PDFHexString,
  rotation: number,
  x: number,
  y: number,
  width: number,
  height: number,
) => {
  const dict = font.doc.context.obj({
    Type: 'XObject',
    Subtype: 'Form',
    FormType: 1,
    BBox: [0, 0, width, height],
    Resources: { Font: { F0: font.ref } },
  });

  const operators = [
    rotateDegrees(rotation),
    translate(0, rotation % 90 === 0 ? -width : 0),
    beginMarkedContent('Tx'),
    pushGraphicsState(),
    ...drawText(encodedText, {
      color: rgb(0, 0, 0),
      font: 'F0',
      size,
      rotate: degrees(0),
      xSkew: degrees(0),
      ySkew: degrees(0),
      x,
      y,
    }),
    popGraphicsState(),
    endMarkedContent(),
  ];

  const stream = PDFContentStream.of(dict, operators);

  return font.doc.context.register(stream);
};

(async () => {
  const pdfDoc = await PDFDocument.load(
    fs.readFileSync('/Users/user/Desktop/pdf_examples/BAE-5H.pdf'),
  );

  getAcroFields(pdfDoc).forEach((field) => {
    console.log(String(field.lookup(PDFName.of('T'))));
  });

  const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const fillInField = (fieldName: string, text: string) => {
    const field = findAcroFieldByName(pdfDoc, fieldName);
    if (field) fillAcroTextField(field, text, helveticaFont);
  };

  const lockField = (acroField: any) => {
    const fieldType = acroField.lookup(PDFName.of('FT'));
    if (fieldType === PDFName.of('Tx')) {
      acroField.set(PDFName.of('Ff'), PDFNumber.of(1 << 0 /* Read Only */));
    }
  };

  fillInField('name', 'Danica Caudillo');
  fillInField('facility', 'Community Pool');
  fillInField('time', '1');
  fillInField('city', 'A city with a dramatically long name');
  fillInField('state', 'Minnesota');
  fillInField('signature', 'Jose Avila');
  fillInField('date', 'Oct 31, 2019');

  const acroFields = getAcroFields(pdfDoc);
  acroFields.forEach((field) => lockField(field));

  const pdfBytes = await pdfDoc.save();

  fs.writeFileSync('out.pdf', pdfBytes);
})();
```

I hope this helps!

**Comment by Hopding** [comment]
Btw, here's what the resulting PDF looks like:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/75636211-6563d780-5be2-11ea-8c8c-9edf49a64f07.png" height="500">
</kbd>
