### ISSUE TITLE
SVG Path with stroke features 

### ISSUE THREAD

**Issue by ihmc3jn09hk** [Hopding/pdf-lib#363]
From #202, there is a feature added for SVG path, great thank to the contributors.
Yet there is some feature missing for path, say
stroke-width, stroke-color, fill, stroke-linecap etc.

I know that will be quite tedious to write a [parser](https://github.com/alafr/SVG-to-PDFKit) for these.
For a short fix, could they be added to the options?

**Comment by Hopding** [comment]
Hello @ihmc3jn09hk! I'd be willing to accept a PR for this if anybody would like to work on it.

**Comment by ihmc3jn09hk** [comment]
I would like to contribute @Hopding. I had a quick look at the code but yet figure out how it work exactly. I aint JS guru but would like to give it a shot. Maybe please clear my understanding on the stucture before anything else.
In code tracing, svgPath.ts, operator.ts and PDFOperatorNames.ts are the files of interest ?? I cannot find where the implementation of a function is located. 
E.g. moveTo()
PDFOperatorNames.ts       //A marco defination?
operator.ts                         //Registration of the function?
svgPath.ts                           //Here again, another map to the function like operator.ts

So, where exactly is the implementation of the mapped function?
I am sorry if it is a dump question in JS development. I just studied the project for a short time.

**Comment by Hopding** [comment]
@ihmc3jn09hk I just released the PDF embedding feature yesterday. In #348 you mentioned that it would be a good workaround for you. If so, are you still interested in working on this feature? Please let me know if you are, and I'll take some time to answer your questions!

**Comment by ihmc3jn09hk** [comment]
@Hopding wow, that's great. Thanks. It's a big jump for the library. Will try it out asap which I think is fitting my needs. Much thanks to 
@tessi the hero for this.
