### ISSUE TITLE
Pdf page x,y origin location

### ISSUE THREAD

**Issue by Herz3h** [Hopding/pdf-lib#365]
I'm using this library to stamp pdf's. I've noticed that in most cases the x,y origin is located in the bottom left of the document.

However I have a document where the x,y origin seems to be on the top right....Also the image I'm adding to the document is rotated towards bottom (180°).

Code used is like this: 

```javascript
                page.drawImage(stampPng, {
                    x: pageDimensions.width * relativeHorizontalPosition,
                    y: pageDimensions.height - (relativeVerticalPosition * pageDimensions.height) - pageDimensions.height * relativeHeight , // This is because the Y origin is in the bottom left.
                    width:  pageDimensions.width * relativeWidth,
                    height: pageDimensions.height * relativeHeight,
                    rotateDegrees: 0,
                });
```

Same code is used in both cases. Most pdfs give the expected result, but one pdf I cannot share unfortunately gives wrong position.

Version used: 1.3.2

Am I missing something ?

**Comment by demalmar** [comment]
I have had trouble with this too. It seems X axys is fine,but Y axis is from bottom to top, so weird.

**Comment by Herz3h** [comment]
Well, the origin is in bottom left  indeed. That's in most pdfs, except this one where origin is in top right...Wondering if there is a way to detect this

**Comment by Hopding** [comment]
Hello @Herz3h!

It sounds like the page you are working with may be rotated. You can access the rotation angle of a page using the [`PDFPage.getRotation()`](https://pdf-lib.js.org/docs/api/classes/pdfpage#getrotation) method. If the resulting angle is anything other than `0` then the page is rotated by some amount. (Note also that you set the rotation of a page with [`PDFPage.setRotation()`](https://pdf-lib.js.org/docs/api/classes/pdfpage#setrotation)).

I hope this helps. Please let me know if you have any additional questions.

**Comment by Herz3h** [comment]
That was indeed the issue, thank you very much !

Awesome library :)
