### ISSUE TITLE
Error TS1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by demalmar** [Hopding/pdf-lib#366]
After installing the recent version, that fixes PNG problems, I have encounter these errors:

ERROR in node_modules/pdf-lib/cjs/core/streams/Stream.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.
get isEmpty(): number;
node_modules/pdf-lib/cjs/core/streams/Stream.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.
get isEmpty(): boolean;

**Comment by doug-gov** [comment]
I'm recieving the same error.  tried to uninstall/reinstall typescript.  I am using webpack v 4.34 & typescript v 3.5.3

**Comment by Hopding** [comment]
@demalmar @doug-gov 

Version [`1.4.0`](https://www.npmjs.com/package/pdf-lib/v/1.4.0) is now published. It contains additional TypeScript declarations for older version of TypeScript that should resolve this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.4.0).

You can install this new version with npm:

```
npm install pdf-lib@1.4.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.4.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.4.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.4.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.4.0/dist/pdf-lib.min.js
