### ISSUE TITLE
Patching the generated PDF version (1.7 -> 1.6)

### ISSUE THREAD

**Issue by DoubleHub** [Hopding/pdf-lib#367]
I know that this library adheres to the PDF 1.7 spec, but would it be possible to patch the version to make it 1.6? Even an hard patch would be good. Thanks in advance!

EDIT: I know that I can do it with GhostScript, I just want to know if it is possible to do it without using it.

**Comment by Hopding** [comment]
Hello @DoubleHub!

If by "hard patch" you mean directly edit the version number, then yes, this is pretty easy to do. However, note that simply changing the version number does not mean the actual PDF file is compliant with PDF version 1.6 (though it may be).

Here's how you can do it:

```js
const pdfDoc = await PDFDocument.load(...);
const pdfBytes = await pdfDoc.save({ useObjectStreams: false });
pdfBytes[7] = '6'.charCodeAt(0);
fs.writeFileSync('out.pdf', pdfBytes);
```
