### ISSUE TITLE
Error when parsing some PDF documents

### ISSUE THREAD

**Issue by gregbacchus** [Hopding/pdf-lib#37]
Version: pdf-lib@0.3.0

Unfortunately I'm unable to provide the offending documents as they come from a customer.

```
TypeError: Cannot read property '0' of null
  at parseObjData (.../node_modules/pdf-lib/lib/core/pdf-parser/parseObjectStream.js:44:64)
  at Object.parseObjectStream [as default] (.../node_modules/pdf-lib/lib/core/pdf-parser/parseObjectStream.js:67:19)
  at Object.exports.default (.../node_modules/pdf-lib/lib/core/pdf-parser/parseStream.js:82:55)
  at Object.parseDictOrStream [as default] (.../node_modules/pdf-lib/lib/core/pdf-parser/parseDictOrStream.js:28:44)
  at Object.parseIndirectObj [as default] (.../node_modules/pdf-lib/lib/core/pdf-parser/parseIndirectObj.js:43:41)
  at parseBodySection (.../node_modules/pdf-lib/lib/core/pdf-parser/parseDocument.js:24:48)
  at Object.parseDocument [as default] (.../node_modules/pdf-lib/lib/core/pdf-parser/parseDocument.js:78:21)
  at PDFParser.parse (.../node_modules/pdf-lib/lib/core/pdf-parser/PDFParser.js:38:40)
  at Function.PDFDocumentFactory.load (.../node_modules/pdf-lib/lib/core/pdf-document/PDFDocumentFactory.js:45:35)
  at FileModel.<anonymous> (.../src/models/file.model.ts:128:40)
```

**Comment by Hopding** [comment]
Hello @gregbacchus. Has `pdf-lib` worked for you on other documents? I’m wondering if it has failed consistently with every document you’ve tried, or if it’s just this particular one that’s generating an error.

**Comment by gregbacchus** [comment]
Yes, it has worked on other documents from other sources. I have only just started playing with `pdf-lib` so haven't tested it on very many examples, but I find that the documents that we receive are from many different sources (and I suspect that have varying degrees of compliance with PDF specs).

**Comment by Hopding** [comment]
This will be difficult to debug since I can't directly access the documents, and have been unable to reproduce this myself. If you're interested in helping, can you please do the following:

1. Open `node_modules/pdf-lib/lib/core/pdf-parser/parseObjectStream.js` in an editor
2. Add 3 log statements to the `parseObjData` function, defined on line `28`:
```js
var parseObjData = function (dict, input) {
    // Add these three lines:
    console.log('parseObjData.dict:', dict);
    console.log('arrayToString(parseObjData.input):', utils_1.arrayToString(input));
    console.log('parseObjData.input:', input);
    
    // Extract the value of the "N" entry from the dict
    var numObjects = dict.get('N').number;
    ...
```
3. Run your project with the problematic documents and trigger the error
4. Share the output of those three log statements with me

This should give me enough information to try to figure out the cause and reproduce it myself, without you having to provide the actual documents or sensitive customer info.

**Comment by gregbacchus** [comment]
Hi,

`dict` is

```javascript
parseObjData.dict: PDFDictionary {
  toString: [Function],
  bytesSize: [Function],
  copyBytesInto: [Function],
  filter: [Function],
  getMaybe: [Function],
  get: [Function],
  set: [Function],
  index:
   PDFObjectIndex {
     index: Map {},
     set: [Function],
     lookupMaybe: [Function],
     lookup: [Function] },
  validKeys: undefined,
  map:
   Map {
     PDFName {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     key: 'First' } => PDFNumber {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     number: 1786 },
     PDFName {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     key: 'Filter' } => PDFName {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     key: 'FlateDecode' },
     PDFName {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     key: 'N' } => PDFNumber {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     number: 182 },
     PDFName {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     key: 'Type' } => PDFName {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     key: 'ObjStm' },
     PDFName {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     key: 'Length' } => PDFNumber {
     toString: [Function],
     bytesSize: [Function],
     copyBytesInto: [Function],
     number: 6256 } } }
```

outputting just the input (as byte array) got truncated, so I wrote it directly to a file 
[input.txt](https://github.com/Hopding/pdf-lib/files/2489181/input.txt)

So
```javascript
var numObjects = dict.get('N').number; // = 182
```

and adding 
```javasript
  while (i < numObjects) {
    console.log(i, remaining.substring(0, 100));
    var _a = remaining.match(objDatumRegex), fullmatch = _a[0], objNum = _a[1], byteOffset = _a[2];
```
yields
```
0 '2 0\n265 34\n267 449\n4 864\n268 971\n270 1386\n272 1801\n273 2216\n275 2631\n10 2805\n277 2996\n278 4050\n280 5'
1 '\n265 34\n267 449\n4 864\n268 971\n270 1386\n272 1801\n273 2216\n275 2631\n10 2805\n277 2996\n278 4050\n280 5104'
```

i.e. the `\n` is not being trimmed

One way of dealing with this might be to split by `\n` then map the resultant array to objData... I'll do a PR with my suggestion.

**Comment by gregbacchus** [comment]
Or, as I thought of afterwards,

```typescript
const objDatumRegex = /^ *(\d+) *(\d+)[ \n\r]*/;
```

will also fix.

**Comment by gregbacchus** [comment]
Made a pull PR with second approach as first does't work.

**Comment by gregbacchus** [comment]
I have updated that PR. However, I noticed a number of other places where there are regexs searching for `[\n\r ]` or similar. I'm guessing that some of these should also include the extra white space chars?

**Comment by Hopding** [comment]
Version [`0.4.0`](https://www.npmjs.com/package/pdf-lib/v/0.4.0) is now published. It contains the parser bug fixes for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.4.0).

You can install this new version with npm:
```
npm install pdf-lib@0.4.0
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.4.0/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.4.0/dist/pdf-lib.min.js

@gregbacchus Thanks for your contributions to this release!
