### ISSUE TITLE
[Feature Request] Timestamp Authority with or without LTV

### ISSUE THREAD

**Issue by MarcGodard** [Hopding/pdf-lib#371]
I think it would be amazing to be able to add timestamp authority signatures / certs.

This is obviously jut a cool feature request. Glad your lib exist.

**Comment by MarcGodard** [comment]
@Hopding This might just be more meta data. If you can direct me to the PDF standards for this (I have no idea where to look), I might be able to rustle up a PR for it. I don't need this feature, but it would be a nice to have for a few projects that I am currently storing this separately.

**Comment by MarcGodard** [comment]
Just leaving this here for future work: https://github.com/vbuch/node-signpdf

I would like to build a pr for this when i have time.

**Comment by taxilian** [comment]
I have a copy of the pdf standards document relevant to this; if anyone is serious about working on it I'm willing to share or even donate it. it's not public domain, you have to buy it.

**Comment by MarcGodard** [comment]
@taxilian I am willing to start working on this. Where can I buy it?

**Comment by vicpara** [comment]
I think this is introduces the concepts. I don't know about any other standard document: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

**Comment by MarcGodard** [comment]
@vicpara that is like saying the answer is on duckduckgo. lol

**Comment by vicpara** [comment]
Apologies but that was not the intention. That is the only official documentation I found available on their website. Adobe does claim they have more but they encourage paying to use their SDK.

**Comment by MarcGodard** [comment]
@vicpara No stress, it wasn't an accusation. It is just a big document. Hopefully I have time soon to work on this.

**Comment by MarcGodard** [comment]
This isn't an issue, it is a feature-request.

**Comment by Hopding** [comment]
Related to https://github.com/Hopding/pdf-lib/issues/433#issuecomment-925347404

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
