### ISSUE TITLE
Cannot embed custom font from local file

### ISSUE THREAD

**Issue by AlanHadzic** [Hopding/pdf-lib#372]
Hi, 

I'm trying to set a custom font from a local file as it was shown in examples. 

```js
...
const url = '/opt/path/to/my/font/file/OpenSans-Bold.5a100916.ttf'
const fontBytes = fs.readFileSync(url);
const existingPDF = fs.readFileSync(outputPath);
const pdfDoc = await PDFDocument.load(existingPDF);

pdfDoc.registerFontkit(fontkit);

const customFont= await pdfDoc.embedFont(fontBytes);
const pages = pdfDoc.getPages();
...
```

I keep getting this error message: 

> Error: Input to `PDFDocument.embedFont` was a custom font, but no `fontkit` instance was found. You must register a `fontkit` instance with `PDFDocument.registerFontkit(...)` before embedding custom fonts.

I'm using:

Node: v13.3.0
"pdf-lib": "^1.4.0",
"@pdf-lib/fontkit": "0.0.4",

Question is, how to register fontkit correctly or is there something else I'm doing wrong?

**Comment by Hopding** [comment]
Hello @AlanHadzic!

What does the `fontkit` variable in the snippet you shared refer to? I don’t see an import of it anywhere.

Note also that the instructions for registering fontkit can be found here: https://github.com/Hopding/pdf-lib/blob/master/README.md#fontkit-installation

**Comment by Hopding** [comment]
I'm going to close this issue for now. But please feel free to reopen it if you are still having trouble.

**Comment by DYW972** [comment]
Hello,

I know this is a closed issue but I wanted to give some informations because this issue was the closest to what I needed.

I'm using pdf-lib on Node.js in order to edit a pdf document.

I wanted to add my own fonts in my method and this issue guide me to my goal.

If you are working with a Node.js API and want to add custom font, this is how it's works for me.

Just one thing first, you need to set your variables and in **Node.js** it's 

`require ('@pdf-lib/fontkit')` ✅

not 

`import fontKit from '@pdf-lib/fontkit` ❌

I said that for people like me who start to code... 😅

Here a quick exemple :

Imagine we create a router for editing a pdf doc:



```
const fs = require('fs');
const {PDFDocument, degrees, rgb, StandardFonts} = require('pdf-lib');
const fontkit = require('@pdf-lib/fontkit'); // <= here is the Most Important Thing.


router.put('/pdf', async (req, res, next) => {

    // Get an existing pdf file to edit 
    const existingPdfBytes = fs.readFileSync(path/to/the/name_of_your_pdf_file.pdf');

    // Load the file
    const pdfDoc = await PDFDocument.load(existingPdfBytes);

   // Add font kit to the project
    pdfDoc.registerFontkit(fontkit);

   // Get all pages of the pdf document 
    const pages = pdfDoc.getPages();

  // Select the page to working on
    const firstPage = pages[0];

    // Here it's where you start to add your custom font nothing to hard to understand I think
   // Get the file with file system.
    const customFont1 = fs.readFileSync(path/to/the/name_of_your_font1.otf');
    const customFont2 = fs.readFileSync(path/to/the/name_of_your_font2.otf')
    const customFont3 =  fs.readFileSync(path/to/the/name_of_your_font3.otf')

   // Add the font file content into the doc
    const cusFont1 = await pdfDoc.embedFont(customFont1);
    const cusFont2 = await pdfDoc.embedFont(customFont2);
    const cusFont3 = await pdfDoc.embedFont(customFont3);


   // Now you can draw your text on your document, 
  // It is just an exemple to show you how it's works...

    firstPage.drawText('Write something', {
        x: 217,
        y: 210,
        size: 12,
        font: cusFont1,
        color: rgb(0.95, 0.1, 0.1),
    });

    firstPage.drawText('Write another thing, {
        x: 230,
        y: 140,
        size: 20,
        font: cusFont2,
        color: rgb(0.95, 0.1, 0.1),
    });
   
 // Lets write the Date on the document...
    let todayDate = new Date();

    firstPage.drawText(todayDate.getDate() + ' ' + months[todayDate.getMonth()] + ' ' + todayDate.getFullYear(), {
        x: 62,
        y: 70,
        size: 12,
        font: cusFont3,
        color: rgb(0.95, 0.1, 0.1),
    });

   // Like in the official documentation, this is you final document
    const pdfBytes = await pdfDoc.save();

 // Save the doc where you want to. I recommend you tu use a try/catch for safety...

    try {

        fs.writeFileSync(path/to/destination/where/saving/the_name_of_your_pdf_file.pdf', pdfBytes);
        return res.json({
            "result": true,
            "response": {src: '/where/saving/the_name_of_your_pdf_file.pdf'}
        })

    } catch (e) {

        return res.json({
            "result": false,
            "response": {error: e}
        })

    }

});
```


Voilà, 
I hope you will more understand how to add custom fonts in pdf-lib with Node.js.

If you need more information about FileSystem, check this => [https://nodejs.org/api/fs.html](url)

Thanks for watching, reading, sharing, enjoying this comment, and don't forget to say thank you to @Hopding for this nice and cool project .

🙋🏾‍♂️

**Comment by tomhill991** [comment]
> Hello,
> 
> I know this is a closed issue but I wanted to give some informations because this issue was the closest to what I needed.
> 
> I'm using pdf-lib on Node.js in order to edit a pdf document.
> 
> I wanted to add my own fonts in my method and this issue guide me to my goal.
> 
> If you are working with a Node.js API and want to add custom font, this is how it's works for me.
> 
> Just one thing first, you need to set your variables and in **Node.js** it's
> 
> ```js
> const fontKit = require ('@pdf-lib/fontkit') ✅
> ```
> 
.....

This was so helpful, thank you

Project I'm currently doing is filling PDF's that already have radio buttons, selects and fields etc. so If anyone is looking to fill in a current pdf (i.e if they want to setText etc.) using a custom font in NodeJS, you can follow this:

`
const pdfLib = require('pdf-lib');
const { PDFDocument } = pdfLib;
const fs = require('fs');
const fontKit = require('@pdf-lib/fontkit');

    makePdf = (async (template, answers) => {
        const that = this;
        return new Promise((resolve, reject) => {
            const pdfUri = template.uri;
            //template is a PDF file that is stored on the server and being passed into makePdf
            const existingPdfBytes = fs.readFileSync(template);

            fs.readFile(pdfFile, async (fsErr, data) => {
                if (fsErr) {
                    const obj = {
                        status: 'error',
                        data: null,
                        error: fsErr
                    };

                    reject(obj);
                }

                
                const formPdfBytes = data;
                const pdfDoc = await PDFDocument.load(formPdfBytes);
                const form = pdfDoc.getForm();
                // use font kit in PDF to add a custom font
                pdfDoc.registerFontkit(fontKit);
                // get array buffer of font
                const fontBytes = fs.readFileSync('path/to/the/name_of_your_font1.otf'');
                // embed array buffer of font into PDF
                const customFont = await pdfDoc.embedFont(fontBytes);
                // get the names of the fields that are mapped onto the PDF
                const fields = form.getFields();
                const fieldNames = fields.map((f) => f.getName());

                fieldNames.forEach((field) => {
                    const formField = form.getField(field);
                    // if it's a text field
                    if (formField.setText) {
                        formField.setText(answers[field]);
                    }
                    // if it's a checkbox
                    if (formField.isChecked) {
                        if (answers[field] === 'true') {
                            formField.check();
                        }
                    }

                    // if it's a radio
                    if (formField.getOptions) {
                        if (answers[field]) {
                            formField.select(answers[field]);
                        }
                    }
                });

                // this part is very important (and must go before await pdfDoc.save() 
                form.updateFieldAppearances(customFont);

                const pdfBytes = await pdfDoc.save();

                // location where you want to save your PDF (if you want to store it on your server). Need this on my project as have 
                to send an email with the filled out PDF to the user
                const rootToPdf = `/location-you-want-to-save-pdf-on-server/name-of-pdf.pdf`;
                
                 // save PDF on server
                fs.writeFile(rootToPdf, pdfBytes, (error) => {
                    if (!error) {
                        resolve(rootToPdf);
                    } else {
                        reject(error);
                    }
                });
            });
        });
    })
`

**Comment by jamesmcglinn** [comment]
This looks like a default export issue with fontkit so another potential solution is to replace the import with:

```
import * as fontkit from '@pdf-lib/fontkit';
```

**Comment by CrisAlejo26** [comment]
> Esto parece ser un problema de exportación predeterminado con fontkit, por lo que otra posible solución es reemplazar la importación con:
> 
> ```
> import * as fontkit from '@pdf-lib/fontkit';
> ```

It's September 2024 and this is how it works.

**Comment by Rezolon** [comment]
> > Esto parece ser un problema de exportación predeterminado con fontkit, por lo que otra posible solución es reemplazar la importación con:
> > ```
> > import * as fontkit from '@pdf-lib/fontkit';
> > ```
> 
> Сейчас сентябрь 2024 года, и вот как это работает.

подтверждаю работает 04.10.2024
