### ISSUE TITLE
Replace the existing text from pdf file

### ISSUE THREAD

**Issue by amitgithub1947** [Hopding/pdf-lib#374]
@Hopding I want to replace the existing text with new text in any page. 

I am not getting any method to get the existing text and can write new text instead of this. 

How we can achieve it?

**Comment by Hopding** [comment]
Hello @amitgithub1947!

I'm afraid this is not currently possible to do with pdf-lib. Please see https://github.com/Hopding/pdf-lib/issues/33#issuecomment-420740506, https://github.com/Hopding/pdf-lib/issues/137#issuecomment-513505409, and https://github.com/Hopding/pdf-lib/issues/331#issuecomment-579757022 for details.
