### ISSUE TITLE
Filter or Remove Scripts and Named Destinations

### ISSUE THREAD

**Issue by mcmspark** [Hopding/pdf-lib#375]
I am using pdf-lib to add annotations to the document.
I would like to also do other processing while I have it in memory.
Specifically, I have a request to remove both scripts and "links".

This may be more of a how to request.  

1. It looks like I might be able to overwrite the destination on all "Named Destinations".  Is that OK?
2. For scripts, it is not clear to me how to identify them and what removal method would be safe.

**Comment by Hopding** [comment]
Hello @mcmspark!

1. Overwriting named destinations is fine. I can't think of a reason that this would be problematic.
2. You should be able to identify scripts by finding all JavaScript action objects (see section **12.6.4.16 JavaScript Actions** of the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf)) in the document. Something like the following should work:
   ```js
   const pdfDoc = await PDFDocument.load(...)
   const jsActions: Array<[PDFRef, PDFObject]> = pdfDoc.context
     .enumerateIndirectObjects()
     .filter(
       ([, object]) =>
         object instanceof PDFDict &&
         object.lookup(PDFName.of('S')) === PDFName.of('JavaScript'),
     );
    // Do stuff with the the JavaScript actions...
   ```

I hope this helps!

**Comment by tomeronen** [comment]
Hello, this is a bit old. But in case its still relevant i did something like this:
```

const pdfObjectHasJsActions = (pdfObject: PDFObject): boolean => {
  if (pdfObject instanceof PDFDict) {
    const entries = pdfObject.entries();
    return entries.some(([_, childObject]) => pdfObjectHasJsActions(childObject));
  } else if (pdfObject instanceof PDFName) {
    // here you can do what you want with the object
    return pdfObject === PDFName.of('JavaScript');
  } else {
    return false;
  }
}

export const pdfDocHasJs = (pdfDoc: PDFDocument) => {
  return pdfDoc.context.enumerateIndirectObjects()
    .some(([_, object]) => pdfObjectHasJsActions(object));
}
```
