### ISSUE TITLE
Removing last page of document fails with Index out of bounds error

### ISSUE THREAD

**Issue by Narigo** [Hopding/pdf-lib#376]
Thank you for this great library, its API is really nice to use!

I have a small problem with one PDF I've used to test though: Trying to remove the last page of the document results in an error:

```
$ node src/index.js Nextcloud\ Manual.pdf
Error! Error: Index out of bounds: 2/2
    at PDFPageTree.removeLeafNode (/app/node_modules/pdf-lib/cjs/core/structures/PDFPageTree.js:81:23)
    at PDFCatalog.removeLeafNode (/app/node_modules/pdf-lib/cjs/core/structures/PDFCatalog.js:27:22)
    at PDFDocument.removePage (/app/node_modules/pdf-lib/cjs/api/PDFDocument.js:336:22)
    at run (/app/src/index.js:16:7)
```

Below is the reproducer. I have the feeling that the PDF is somehow corrupt but since I can open it with MacOS Preview, I would assume it works with this as well. I can even add pages, save and remove them later through pdf-lib. As soon as it gets to the last page of the initial document though, it will result in the error above.

____

Here is the reproducer script:

```
#!/usr/bin/env node

const fs = require("fs");
const pdfLib = require("pdf-lib");

const pdfPath = process.argv[2];
const outPath = "output.pdf";

run({ pdfPath, outPath }).catch(error => console.error("Error!", error));

async function run({ pdfPath, outPath }) {
  const pdfDocument = fs.readFileSync(pdfPath);
  const doc = await pdfLib.PDFDocument.load(pdfDocument);
  const amountOfPages = doc.getPages().length;
  const lastPageIndex = amountOfPages - 1;
  doc.removePage(lastPageIndex);
  const bytes = await doc.save();
  fs.writeFileSync(outPath, bytes);
}
```

...and the file that fails:
[Nextcloud Manual.pdf](https://github.com/Hopding/pdf-lib/files/4286377/Nextcloud.Manual.pdf)

**Comment by Hopding** [comment]
Hello @Narigo! 

The PDF you shared is not corrupt. In fact, you uncovered an off-by-one bug in the page removal code. I fixed the issue in #378. I'm planning to cut a release this weekend with this fix (and another unrelated one). Once I do, you can pull down the new version and get past this issue!

**Comment by Hopding** [comment]
@Narigo Version [`1.4.1`](https://www.npmjs.com/package/pdf-lib/v/1.4.1) is now published. It contains the fix for this issue. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.4.1).

You can install this new version with npm:

```
npm install pdf-lib@1.4.1
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.4.1/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.4.1/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.4.1/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.4.1/dist/pdf-lib.min.js

**Comment by Narigo** [comment]
Very cool, thanks - it works very well now.
I'm using your library in my [pdf-document-feeder project](https://github.com/compose-us-research/pdf-document-feeder), to sort documents after scanning them with a document feeder.

**Comment by Hopding** [comment]
Neat project! I'm glad it's working for you.
