### ISSUE TITLE
Signature flow question - clickable rectangle with "menu" buttons?

### ISSUE THREAD

**Issue by arthabus** [Hopding/pdf-lib#377]
Hello, I'm new to pdf and maybe I'm approaching it in the wrong way, but I hope you could provide some guidance.

Basically I'm trying to implement a signature flow similar to hellosign.com

The way they do it is that one party adds a signature "box" and the other party can click it to add their signature. They can click the "box" one more time to edit or remove their signature.

Here is how it looks like:

A clickable box to add signature:
<img width="471" alt="Screen Shot 2020-03-04 at 19 46 35" src="https://user-images.githubusercontent.com/8145834/75912517-a57cc180-5e51-11ea-9102-e2e43faa265b.png">

Once they click the box, it fires a "click" event I assume, so a custom dialog appears to setup the signature:
<img width="883" alt="Screen Shot 2020-03-04 at 19 46 45" src="https://user-images.githubusercontent.com/8145834/75912622-cba26180-5e51-11ea-8253-079751e530a5.png">

Once done, they can click the box again to edit or delete the signature:
<img width="502" alt="Screen Shot 2020-03-04 at 19 46 28" src="https://user-images.githubusercontent.com/8145834/75912736-f987a600-5e51-11ea-8c63-3492ee70cdca.png">

The flow that I assume and the questions are as below:

- I need to draw a clickable rectangle so that when someone clicks it, it will fire a javascript "click" event. **(is that possible at all?)**
- once signature is available, to paste it to that rectangle **(how to obtain the specific pdf object that was clicked?)**

What is the best way to approach this?

**Comment by MarcGodard** [comment]
@arthabus I have built many of these types of applications. I did it by using PDF2HTMLEx to convert the pdf to html. Then I modified their javascript file with a function that adds the boxes, opens the signature stuff when clicked on (also scroll and zooming features), then when they "save" the signature image is applied to the pdf on the backend. Done. I have also added Timestamp Authority to my software, but right now those are saved separately, but would like that feature to embed them in this library. https://github.com/Hopding/pdf-lib/issues/371

This library by itself cannot do what you want to do, as far as my understanding it.

**Comment by arthabus** [comment]
thanks @MarcGodard! appreciate your input.

I was just playing more with hellosign interface and I can see now that they've just rendered the pdf as an image and overlaid it with everything else in html - that works just fine for my case.
