### ISSUE TITLE
Save pdf as png?

### ISSUE THREAD

**Issue by arthabus** [Hopding/pdf-lib#379]
Hi, is it possible to save the resulting pdf as an image in nodejs with this library?

**Comment by Hopding** [comment]
Hello @arthabus!

Converting PDF documents to PNG images is not possible to do with pdf-lib. However, you can use [`pdf.js`](https://github.com/mozilla/pdf.js) for this. Here's a [NodeJS example](https://github.com/mozilla/pdf.js/tree/7b07b88e714f55b14b933e6fafc44b247aec41ab/examples/node/pdf2png) they provide. 

You'd need to modify [lines 53-57](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2png/pdf2png.js#L53-L57) of the example to use the output of [`PDFDocument.save()`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#save):
```js
// Create and manipulate your PDF document
var pdfDoc = await PDFDocument.create() // or `PDFDocument.load(...)`
...

// Read the PDF file into a typed array so PDF.js can load it.
var rawData = await pdfDoc.save()
```

**Comment by arthabus** [comment]
Thanks @Hopding. I tried that before - it doesn't work consistently in node unfortunately - it fails to render text every now and then. Then hopefully ImageMagic could do a better job here.

**Comment by marcdacz** [comment]
Hi @Hopding,

Good day!
Similar to @arthabus, I am facing issue with pdfjs in rendering texts (missing fonts) hence I also thought of using pdf-lib and render it to canvas. My current solution was using graphicsmagick but was hoping to make a pure standalone app.
I've been trying to render the page to a canvas but have no success. Was hoping you could allow this behaviour or maybe shed light if this is even possible.

Many thanks
Marc
