### ISSUE TITLE
Unable to update font in pdf using pdf-lib

### ISSUE THREAD

**Issue by saurabh14t** [Hopding/pdf-lib#381]
Hi @Hopding 
I am unable to update font on pdf. 
I am getting error   <code> Missing PDFDictionary entry "Rect" </code>.

Please suggest what could be the issue. 
Find below code for reference.
```js
const fillInField = (fieldName, text) => {
        const field = findAcroFieldByName(pdfDoc, fieldName);
        if (!field) {
            // if acro field is not present in pdf then return and dont write anything into pdf
            return;
            //throw new Error(`Missing AcroField: ${fieldName}`);
        }
        fillAcroTextField(pdfDoc, field, FontHelvetica, text, 15);
    };


const fillAcroTextField = (pdfDoc, acroField, fontObject, text,fontSize = 15) => {
         const fieldRect = acroField.get('Rect');
         const fieldWidth = fieldRect.get(2).number - fieldRect.get(0).number;
         const fieldHeight = fieldRect.get(3).number - fieldRect.get(1).number;
      
        const appearanceStream = pdfDoc.register(
          PDFContentStream.of(
            PDFDictionary.from({
              Type: PDFName.from('XObject'),
              Subtype: PDFName.from('AcroForm'),
              BBox: PDFArray.fromArray([
                PDFNumber.fromNumber(0),
                PDFNumber.fromNumber(0),
                PDFNumber.fromNumber(402),
                PDFNumber.fromNumber(800),
              ], pdfDoc.index),
              Resources: PDFDictionary.from({
                Font: PDFDictionary.from({
                  FontObject: fontObject
                }, pdfDoc.index)
              }, pdfDoc.index),
            }, pdfDoc.index),
            drawLinesOfText(text.split('\n'), {
              x: 408,
              y: 320,
              font: 'FontObject',
              size: fontSize,
              colorRgb: [0.3, 0.8, 0.5],
            })
          ),
        );
      
        acroField.set('V', PDFString.fromString(text));
        acroField.set('Ff', PDFNumber.fromNumber(1));
        acroField.set('AP', PDFDictionary.from({ N: appearanceStream }, pdfDoc.index));
      };

fillInField('month', 'February');
```

Please let me know if anything else is required.

**Comment by saurabh14t** [comment]
@Hopding 
Could this be issue with the pdf we are using?

Please suggest.

**Comment by saurabh14t** [comment]
@Hopding ,
How do we update multiple fields with same name in a pdf. 
The issue is that if in a pdf when we have fiels with same name it appends #0, #1 with it. Hence it is giving the above error. If the text field name is single it is working. 

Please suggest asap.

**Comment by saurabh14t** [comment]
@Hopding 
Please look into this

**Comment by JerryKusenberger** [comment]
@saurabh14t I just ran into the same issue with multiple fields having the same name. For now i'm just renaming duplicate fields so that they are all unique. Would be awesome to not have to do that though. Any insight @Hopding ?

**Comment by Hopding** [comment]
@saurabh14t @JerryKusenberger If I understand correctly solving this problem should just require changing the logic you're using to lookup acrofields. What code are you guys using to find acrofields in a document?

**Comment by JerryKusenberger** [comment]
@Hopding I cobbled this together from a few different issues that you commented on. I created a function that sits on top of it all that allows me to pass in an existing PDF template URL(hosted on s3) and a 'fields' object that contains the name of the field and the string to assign it.

Posting the code in it's entirety just in case someone else stumbles upon it as this was a challenge for me to understand.

`import download from 'downloadjs'

const {
  asPDFName,
  degrees,
  drawImage,
  drawText,
  PDFArray,
  PDFBool,
  PDFContentStream,
  PDFDict,
  PDFDocument,
  PDFFont,
  PDFHexString,
  PDFImage,
  PDFName,
  PDFNumber,
  PDFOperator,
  PDFOperatorNames,
  popGraphicsState,
  pushGraphicsState,
  rgb,
  rotateDegrees,
  StandardFonts,
  translate
} = require('pdf-lib')

const getAcroForm = pdfDoc =>
  pdfDoc.catalog.lookup(PDFName.of('AcroForm'), PDFDict)

const getAcroFields = pdfDoc => {
  const acroForm = getAcroForm(pdfDoc)
  acroForm.set(PDFName.of('NeedAppearances'), PDFBool.True)
  if (!acroForm) return []

  const fieldRefs = acroForm.lookupMaybe(PDFName.of('Fields'), PDFArray)
  if (!fieldRefs) return []

  const fields = new Array(fieldRefs.size())
  for (let idx = 0, len = fieldRefs.size(); idx < len; idx++) {
    fields[idx] = fieldRefs.lookup(idx)
  }
  return fields
}

const findAcroFieldByName = (pdfDoc, name) => {
  const acroFields = getAcroFields(pdfDoc)

  return acroFields.find(acroField => {
    const fieldName = acroField.get(PDFName.of('T'))
    return !!fieldName && fieldName.value === name
  })
}

const imageAppearanceStream = (image, rotation, width, height) => {
  const dict = image.doc.context.obj({
    Type: 'XObject',
    Subtype: 'Form',
    FormType: 1,
    BBox: [0, 0, width, height],
    Resources: { XObject: { Image: image.ref } }
  })

  const operators = [
    rotateDegrees(rotation),
    translate(0, rotation % 90 === 0 ? -width : 0),
    ...drawImage('Image', {
      x: 0,
      y: 0,
      width: height,
      height: width,
      rotate: degrees(0),
      xSkew: degrees(0),
      ySkew: degrees(0)
    })
  ]

  const stream = PDFContentStream.of(dict, operators, false)

  return image.doc.context.register(stream)
}

const fillAcroTextField = (acroField, text, font) => {
  const rect = acroField.lookup(PDFName.of('Rect'), PDFArray)
  const width =
    rect.lookup(2, PDFNumber).value() - rect.lookup(0, PDFNumber).value()
  const height =
    rect.lookup(3, PDFNumber).value() - rect.lookup(1, PDFNumber).value()

  const MK = acroField.lookupMaybe(PDFName.of('MK'), PDFDict)
  const R = MK && MK.lookupMaybe(PDFName.of('R'), PDFNumber)
  const rotation = R ? R.value() : 0

  const N = singleLineAppearanceStream(font, text, rotation, width, height)

  acroField.set(PDFName.of('AP'), acroField.context.obj({ N }))
  //acroField.set(PDFName.of('Ff'), PDFNumber.of(0)); /* set to 1 for read only */
  acroField.set(PDFName.of('AS'), PDFName.of('Yes'))
  acroField.set(PDFName.of('V'), PDFHexString.fromText(text))
}

const beginMarkedContent = tag =>
  PDFOperator.of(PDFOperatorNames.BeginMarkedContent, [asPDFName(tag)])

const endMarkedContent = () => PDFOperator.of(PDFOperatorNames.EndMarkedContent)

const singleLineAppearanceStream = (font, text, rotation, width, height) => {
  const rotationCorrectedHeight = rotation % 90 === 0 ? width : height
  const size = 12
  const encodedText = font.encodeText(text)
  const x = 1
  const y = rotationCorrectedHeight - size

  return textFieldAppearanceStream(
    font,
    size,
    encodedText,
    rotation,
    x,
    y,
    width,
    height
  )
}

const textFieldAppearanceStream = (
  font,
  size,
  encodedText,
  rotation,
  x,
  y,
  width,
  height
) => {
  const dict = font.doc.context.obj({
    Type: 'XObject',
    Subtype: 'Form',
    FormType: 1,
    BBox: [0, 0, width, height],
    Resources: { Font: { F0: font.ref } }
  })

  const operators = [
    rotateDegrees(rotation),
    translate(0, rotation % 90 === 0 ? -width : 0),
    beginMarkedContent('Tx'),
    pushGraphicsState(),
    ...drawText(encodedText, {
      color: rgb(0.95, 0.1, 0.1),
      font: 'F0',
      size: size,
      rotate: degrees(0),
      xSkew: degrees(0),
      ySkew: degrees(0),
      x,
      y,
      lineHeight: size + 2
    }),
    popGraphicsState(),
    endMarkedContent()
  ]

  const stream = PDFContentStream.of(dict, operators)

  return font.doc.context.register(stream)
}

export default {
  async createContract(url, fields) {

    const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

    const pdfDoc = await PDFDocument.load(existingPdfBytes)

    const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

    const fillInField = (fieldName, text) => {
      const field = findAcroFieldByName(pdfDoc, fieldName)
      if (field) fillAcroTextField(field, text, helveticaFont)
    }

    /* Output all field names */
    const acroFields = getAcroFields(pdfDoc)
    acroFields.forEach(field => {
      const fieldName = field.get(PDFName.of('T'))
      console.log(fieldName)
    })

    for (var i = 0; i < fields.length; i++) {
      fillInField(fields[i].name, fields[i].value)
    }

    const pdfBytes = await pdfDoc.save()

    download(pdfBytes, 'document.pdf', 'application/pdf')
  }
}
`

**Comment by Hopding** [comment]
@JerryKusenberger Would you mind sharing an example document containing two fields with the same name? I'll see if I can update your example to handle it. But I'll need the document first.

**Comment by Hopding** [comment]
I'm going to close this issue for now. Please feel free to reopen if you'd like to discuss this further.

**Comment by sagartrehan** [comment]
Hi Hopding,

Thanks for the awesome library.

I have used this library to fill a pdf template. I have downloaded and build the example of "mario character" pdf template. When I opened the filled pdf in the "adobe acrobat reader", the pdf text fields are getting "resized" and getting "autoaligned" to center of the text field.

1. I set the "Ff" field on acroField to "read-only | multiline" which fixed the issue of text is getting aligned to center on click. But there is a field with display text "Mario" which is still getting center aligned on click.

2. The font size of the text field is still getting resized on click. Please help me to fix this issue.

```
acroField.set('Ff', PDFNumber.fromNumber(
    1 << 0 // Read Only
    |
    1 << 12 // Multiline
  ));
```

Please let me know if this is not an issue and it is because of opening the filled pdf in "Adobe Acrobat Reader". 

Code link
[pdf-lib_form_fill_example_3.zip](https://github.com/Hopding/pdf-lib/files/3693350/pdf-lib_form_fill_example_3.zip)

Video Links
1. [Video of "Ff" field set to Read or Multiline Only](https://drive.google.com/file/d/1kt9Gf-p1fIADQJh56kOL_hIbtBmznUFi/view?usp=sharing)

2. [Video of "Ff" field set to Read Only](https://drive.google.com/file/d/1mRv090HXCDeU8FGFCYFqHP8saseWT1Uy/view?usp=sharing)
