### ISSUE TITLE
[Feature Request] add drawTable similar to jspdf-autotable

### ISSUE THREAD

**Issue by longweiquan** [Hopding/pdf-lib#382]
I hope to add new feature support to draw a table with data array like the library jspdf-autotable.

**Comment by multiplegeorges** [comment]
Hi @Hopding,

I noticed that in #591 you mentioned that the PDF specification doesn't have special support for tables. I think that's accurate from a visual/drawing point of view, but the PDF spec does allow for tagging content as belonging to a logical table in Section 14.8.4.3.4. 

I think that this is part of a larger addition to pdf-lib for creating a Tagged PDF. 

Have you taken a look at that part of the spec? I'd be interested if you'd be able to weigh in on that and any guidance you could provide for someone looking to contribute by tackling these areas.

Thanks!

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
