### ISSUE TITLE
because i can't visit the jsfiddle,can your put the demos on codepen.io or github?

### ISSUE THREAD

**Issue by Wteakenji** [Hopding/pdf-lib#388]

**Comment by Hopding** [comment]
Hello @Wteakenji! 

Would you please explain why you aren't you able to access the jsfiddle demos? Any additional demos I might create would require additional effort to upkeep on my part. There's already a fair amount of work I need to do to upkeep everything as new releases go out, so I hesitate to add anything more unless there's a good reason.

Please also note that there are many examples already available on the [project site](https://pdf-lib.js.org/) and in the README:
* https://github.com/Hopding/pdf-lib#usage-examples
* https://github.com/Hopding/pdf-lib#complete-examples

Depending on your use case, you may find the node or browser app examples to be the most accessible:
* https://github.com/Hopding/pdf-lib/tree/master/apps/node/tests
* https://github.com/Hopding/pdf-lib/tree/master/apps/web
