### ISSUE TITLE
Can't generate latin extended characters

### ISSUE THREAD

**Issue by Team-Terry** [Hopding/pdf-lib#389]
Does the library provide a solution to use, for example polish characters like 'ą' , 'ę', 'ł' etc. Becuasue when I am inputing a string to drawText() method with that kind of character, in my console log there is an statement: 'WinAnsi cannot encode "ś" '. Is there a chance to use these letters?

**Comment by Hopding** [comment]
Hello @Team-Terry!

This is certainly possible to do. You just need to use a font that supports polish characters. Here's a script that does this using the Ubuntu font:
```js
import fontkit from '@pdf-lib/fontkit';
import { PDFDocument } from 'pdf-lib';

(async () => {
  const ubuntuFontBytes = await fetch(
    'https://github.com/Hopding/pdf-lib/raw/master/assets/fonts/ubuntu/Ubuntu-R.ttf',
  ).then((res) => res.arrayBuffer());

  const pdfDoc = await PDFDocument.create();

  pdfDoc.registerFontkit(fontkit);

  const ubuntuFont = await pdfDoc.embedFont(ubuntuFontBytes);

  const page = pdfDoc.addPage([250, 250]);

  page.drawText('ą ę ł ś', { x: 97, y: 125, font: ubuntuFont });

  const pdfBytes = await pdfDoc.save();
})();
```

And here's the resulting page:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/78947714-c1e0cf00-7a8b-11ea-9d6b-873c95a4ea9c.png" height="400">
</kbd>

>

I hope this helps. Please let me know if you have any additional questions!
