### ISSUE TITLE
PDFDocument always inserts empty page

### ISSUE THREAD

**Issue by TheVanDoom** [Hopding/pdf-lib#392]
Hi,

I was trying to write a simple PDF merge program based on the example from the documentation. But even when I just load the first source document and simply copy the pages into the new document, an empty, white page is inserted at index 0.

```
const pdfDoc = await PDFDocument.create();
const baseDocument = await PDFDocument.load(input.pdfData);

baseDocument.getPageIndices().forEach(async (idx) => {
    const [copiedPage] = await pdfDoc.copyPages(baseDocument,[idx]);
    pdfDoc.addPage(copiedPage);
});
```

Unfortunately, I cannot remove the empty page, as the PDFDocument does not seem to generate the necessary metadata. It initially reports that there are no pages in the document, but when saved the empty page is always there. After running through the loop the pdfDoc contains all pages of the baseDocument (plus the initial empty page) when saved, but getPageIndices or getPages does not yield anything. Hence, I cannot remove the initial page, as the removePage method throws an error due to the non-existing pages in the document...

Weirdly enough, adding an empty page (addPage without parameters) seems to replace the initial white page. Using insertPage also seems to get rid of this empty page and set the document metadata correctly. So for now, I am going to use this as a workaround (but I hope add page will work again

Node: v10.14.1
pdf-lib: 1.4.1
OS: MacOS 10.15.2

**Comment by TheVanDoom** [comment]
Ok, insert seems to only move the page to the end (did not see that at first)....

**Comment by TheVanDoom** [comment]
Another update:
It seems like the problem is the `forEach` loop. If I run this code:
```
for (idx of baseDocument.getPageIndices()) {
    const [copiedPage] = await pdfDoc.copyPages(baseDocument,[idx]);
    pdfDoc.addPage(copiedPage);
}
```
The initial empty page is properly removed when I insert the first copied one :-)

**Comment by Hopding** [comment]
Hello @TheVanDoom!

This is actually working as intended. `pdf-lib` will automatically insert an empty page if you attempt to save a `PDFDocument` object that does not contain any pages. The idea behind this design is twofold:
1. It should help new users get comfortable with the library and produce a working script without having to get too deep into the page creation APIs.
2. It should help reduce the number of corrupt/invalid documents produced by bugs in the code of dependent scripts.

However, this is a feature that can be disabled if you so choose. It is controlled by the [`addDefaultPage`](https://pdf-lib.js.org/docs/api/interfaces/saveoptions#optional-adddefaultpage) option to the [`PDFDocument.save()`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#save) method. For example:
```js
import fs from 'fs';
import { PDFDocument } from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();
  const pdfBytes = await pdfDoc.save({ addDefaultPage: false });
  fs.writeFileSync('./out.pdf', pdfBytes);
})();
```
This produces a document with no pages. However, note that many PDF readers will fail to open it. For example, here's what Acrobat displays when you try to view it:

![Screen Shot 2020-03-31 at 6 22 20 PM](https://user-images.githubusercontent.com/10351828/78084322-7472ac80-737d-11ea-85c1-f57f82568846.png)
