### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by MKlersy2** [Hopding/pdf-lib#397]
Hi, 
Im actually on dev of pdf generator. 
I want to use an existing PDF and just input variable on. 

So, when I take the Fiddle code (Copy-Pages), and change url, by url of my PDF, this return error in console : `
Access to fetch at 'myUrlPdf' from origin 'https://fiddle.jshell.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
myUrlPdf:1 Failed to load resource: net::ERR_FAILED
(index):113 Uncaught (in promise) TypeError: Failed to fetch`

The code I actually use : 

https://jsfiddle.net/3m7s0j91/1/

So, if you have any idea how to fix this? Thanks a lot !

**Comment by Hopding** [comment]
Hello @MKlersy2!

CORS is a web protocol that can prevent browsers from accessing certain resources on a server ([read more](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)). It sounds like your server is not setup to respond the the CORS `OPTIONS` request, most likely. I'd suggest looking into that. But it doesn't appear to be an issue with JSFiddle or pdf-lib.

Note that I'm assuming you are substituting the string `'myPdfUrl'` for a valid URL. If not, then that's the first thing you'll need to fix.
