### ISSUE TITLE
[Feature Request] adding stroke-linecap support for svg path

### ISSUE THREAD

**Issue by sbraaa** [Hopding/pdf-lib#398]
Hi @Hopding,
I really appreciated the possibility to draw svg path.
I'm developing a webapp wich use pdf-lib to overlay some user free-hand draws to pdf files. 
Doing that I realize that a svg feature was missing : stroke-linecap.
Drawing freehand lines show clearly how stroke-linecap (in my case : round) is very important. 
Any plans to add this feature?
Thank you for the job you did.

**Comment by Hopding** [comment]
Hello @sbraaa!

As you know, currently pdf-lib only supports drawing SVG _paths_ - not SVG tags. This makes it difficult to add any SVG features that apply to tags but not paths. And, unfortunately, as far as I can tell the `stroke-linecap` attribute applies to SVG tags, not paths.

However, I would very much like to support drawing SVG tags and SVG files, not just paths. I do not have time to implement this feature in the near future. But if anybody would like to submit a PR for it, I would be grateful!

All that being said, I think you can still achieve what you're looking for with the current APIs. You'll just need to push the [`setLineCap()`](https://pdf-lib.js.org/docs/api/#const-setlinecap) operator onto the page before drawing your SVG path. Here's an example:

```js
import {
  LineCapStyle,
  PDFDocument,
  popGraphicsState,
  pushGraphicsState,
  setLineCap,
} from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();

  const page = pdfDoc.addPage([40, 100]);

  page.pushOperators(pushGraphicsState(), setLineCap(LineCapStyle.Butt));
  page.drawSvgPath('M 0 0 L 0 80', { x: 10, y: 90, borderWidth: 5 });
  page.pushOperators(popGraphicsState());

  page.pushOperators(pushGraphicsState(), setLineCap(LineCapStyle.Round));
  page.drawSvgPath('M 0 0 L 0 80', { x: 20, y: 90, borderWidth: 5 });
  page.pushOperators(popGraphicsState());

  page.pushOperators(pushGraphicsState(), setLineCap(LineCapStyle.Projecting));
  page.drawSvgPath('M 0 0 L 0 80', { x: 30, y: 90, borderWidth: 5 });
  page.pushOperators(popGraphicsState());

  const pdfBytes = await pdfDoc.save();
})();
```

Here's what the resulting document looks like:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/79056464-888b9900-7c1c-11ea-9aa0-b3c9f7302eb5.png">
</kbd>

>

Left: `LineCapStyle.Butt`
Middle: `LineCapStyle.Round` 
Right: `LineCapStyle.Projecting`

Note also that there is a [`setLineJoin()`](https://pdf-lib.js.org/docs/api/#const-setlinejoin) operator that you may also find useful.

I hope this helps. Please let me know if you have any additional questions!
