### ISSUE TITLE
Is it possible to center text?

### ISSUE THREAD

**Issue by asgeirfri** [Hopding/pdf-lib#40]
I want to center text by x-axis on a page, when modifying a pdf by adding text to it.
Is this possible?

**Comment by Hopding** [comment]
Yes, this is possible to do with embedded fonts. Please see my explanation in https://github.com/Hopding/pdf-lib/issues/10. Let me know if you need more detail than what I provide in that thread.

Note that you could also make this work with standard (non-embedded) fonts if you have a fixed-width string. The reason I state that you need an embedded font in my response to https://github.com/Hopding/pdf-lib/issues/10, is that you can dynamically measure string widths for embedded fonts. This is not _currently_ possible for non-embedded fonts.

**Comment by Hopding** [comment]
Version [`0.6.0`](https://www.npmjs.com/package/pdf-lib/v/0.6.0) is now published. It adds new methods to measure the width and height of text in standard and embedded fonts ([example](https://github.com/Hopding/pdf-lib/blob/master/examples/measuring_text/node/index.js)). The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v0.6.0).

You can install this new version with npm:
```
npm install pdf-lib@0.6.0
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.0/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.0/dist/pdf-lib.min.js

**Comment by Susheel12345** [comment]
is it possible to text align right in this library?
