### ISSUE TITLE
Rendering of text fields in PDF form does not work in Preview or Safari

### ISSUE THREAD

**Issue by BigGillyStyle** [Hopding/pdf-lib#401]
OS: macOS Catalina 10.15.4
Preview: 11.0 (999.4)
Safari:  13.1 (15609.1.20.111.8)
Chrome: 80.0.3987.163
Acrobat Reader: 2020.006.20042

I am trying to fill in text fields on a PDF form.  I have searched through the examples provided across various GH issues here and discovered a solution with one caveat...the solution only renders properly (on my Mac) in Acrobat Reader and Chrome.  Mac Preview and Safari do **not** work.  I've created a sample Github repo here:

https://github.com/BigGillyStyle/pdf-form-fill-app

**Comment by BigGillyStyle** [comment]
Fixed my own issue thanks to this solution: https://github.com/Hopding/pdf-lib/issues/213#issuecomment-569550078  I have uploaded that change to my sample repo.

**Comment by Hopding** [comment]
Hello @BigGillyStyle!

It looks like you were able to find a good solution to your issue. I've documented an alternative approach you can take as well, if you're interested: https://github.com/Hopding/pdf-lib/issues/205#issuecomment-568938999.

**Comment by BigGillyStyle** [comment]
Thanks @Hopding !
