### ISSUE TITLE
Copying/Duplicating Form Fields... Is it possible?

### ISSUE THREAD

**Issue by KrisHedges** [Hopding/pdf-lib#409]
I would like to be able to duplicate an existing form field and place that copy below the first.
The following code appears to do what I want sort of... meaning the new field refs are not clones but new objects with the same attributes. however they do not appear in the final output...  as you can tell towards the end here I am just desperatly trying update everything up the ladder but to no avail...
Any help/guidance would be greatly appreciated...

```
    const pdfDoc = await PDFDocument.load(pdfBuffer);

    const form = pdfDoc.context.lookup( pdfDoc.catalog.get( PDFName.of( 'AcroForm' )));
    if ( !form ) {
        throw new Error( 'PDF does not contain a form' );
    }

    const fieldRefs = form.context.lookup( form.get( PDFName.of( 'Fields' )));
    if ( !fieldRefs ) {
        throw new Error( 'PDF form does not contain any fields' );
    }

    const copier = PDFObjectCopier.for(pdfDoc.context, pdfDoc.context);

    fieldRefs.array.forEach( ref => {
        let newFieldRef = copier.copy(ref);
        let newField = form.context.lookup(newFieldRef);

        const name = newField.get( PDFName.of( 'T' ));
        const new_name = name.value + '_copy';
        newField.set(PDFName.of('T'), PDFString.of(new_name));

        let newFieldRect = newField.get( PDFName.of( 'Rect' ));
        let top_left_x = newFieldRect.get(0).value();
        let top_left_y = newFieldRect.get(1).value();
        let bottom_right_x = newFieldRect.get(2).value();
        let bottom_right_y = newFieldRect.get(3).value();

        let height = bottom_right_y - top_left_y;

        newFieldRect.set(0, PDFNumber.of(top_left_x));
        newFieldRect.set(1, PDFNumber.of(top_left_y - height));
        newFieldRect.set(2, PDFNumber.of(bottom_right_x));
        newFieldRect.set(3, PDFNumber.of(bottom_right_y - height));

        fieldRefs.push(newFieldRef);
    });

    form.set(PDFName.of('Fields'), fieldRefs);
    pdfDoc.catalog.set( PDFName.of( 'AcroForm' ), form);
```

**Comment by Hopding** [comment]
@KrisHedges Can you share a sample PDF I can use to try out your code on?

**Comment by KrisHedges** [comment]
Ok... So I think I was going about this the wrong way. Basically what I would like to do is get the current page and it's dimensions from a field. Then I'd like to hide/remove that field and begin drawing something text and rects where that field exists... 
Essentially I need to draw a table from an array using the field and it's name as the placeholder in the document...

I see how to drawRect and drawText from the page object but I need to get that page object and the x, y, and height from the field...

I see these values which are probably what I need from the field...
```
PDFArray {
[
PDFNumber { numberValue: 17.4, stringValue: '17.4' },
PDFNumber { numberValue: 380.8, stringValue: '380.8' },
PDFNumber { numberValue: 165.1, stringValue: '165.1' },
PDFNumber { numberValue: 395.8, stringValue: '395.8' }
],
...
```
But how do i get the page object from there? context?
And then how do I hide/remove the field?
Any help help would be greatly appreciated.. I'm just circling back to this sorry for the long delay.

**Comment by Hopding** [comment]
Hello @KrisHedges! 

Apologies for the delayed response. pdf-lib has a new forms API that should make this much easier. See the README and API docs for details. 

That being said, it would still require a bit of work to achieve. See https://github.com/Hopding/pdf-lib/issues/529 for an example of how to remove an annotation. This is what you'll need to do with the widgets of the field you wish to remove. 

To figure out which page a widget belongs to, you'll need to iterate through each page's `Annots` array until you find a `PDFRef` that matches the widget you're searching for.
