### ISSUE TITLE
Convert and compress to PDF/A-3

### ISSUE THREAD

**Issue by Drosaca** [Hopding/pdf-lib#410]
I saw that PDF/A-3 (1.7 version) standard format provides some compression using jpeg2000. 
I want to use this feature to load a PDF file with 1.3 spec and save it as PDF with PDF/A-3 standard which will potentially reduce the size of the file. 
Is there any way to use the compression from PDF/A-3 standard using pdf-lib ?
if not will it be possible in future versions or is there another library that can do that ?

thanks

**Comment by Hopding** [comment]
@Drosaca pdf-lib does not provide any special support for generating PDF/A-3 documents. But that doesn't mean you can't still do it. It's just on you to ensure they are compliant with the PDF/A-3 spec. I'd recommend taking a look at https://github.com/Hopding/pdf-lib/issues/230.

It's possible that special support could be added for PDF/A-3 documents, depending on what changes it would require. Also, I am not aware of any other libraries that can do this.

I hope this helps!
