### ISSUE TITLE
[Feature Request]: PDF Annotations

### ISSUE THREAD

**Issue by wandit** [Hopding/pdf-lib#411]

**Comment by Hopding** [comment]
Hello @wandit! Can you please add some details to this describing what exactly you are looking for here?

**Comment by vegarringdal** [comment]
@Hopding 
Maybe wrong issue 😄 
But I tried to embed PDF pages in a new pdf to resize them, noticed the annotations made in acrobat (stamps/comments etc) was not included.
Figured its not supported since someone created this feature request?

**Comment by Hopding** [comment]
Hello @vegarringdal! 

I'm not actually too sure what this feature request is for. I'm going to close it as it's ambiguous.

That being said, `pdf-lib` does support copying annotations between documents. But it only works if you do so with [`PDFDocument.copyPages(...)`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#copypages). Embedding pages will not retain the annotations.

Also, you do not need to embed or copy pages between documents to resize them. You can just use one or more of these `PDFPage` methods:
* https://pdf-lib.js.org/docs/api/classes/pdfpage#setwidth
* https://pdf-lib.js.org/docs/api/classes/pdfpage#setheight
* https://pdf-lib.js.org/docs/api/classes/pdfpage#setsize
* https://pdf-lib.js.org/docs/api/classes/pdfpage#translatecontent

I hope this helps. Please let me know if you have any additional questions!

**Comment by vegarringdal** [comment]
@Hopding 

Im pretty sure I tried the setsize part last time and it was really just doing cropping not really resizing :-)
But Ill try again.

**Comment by vegarringdal** [comment]
@Hopding 

Just tried setWidth, setHeight and setSize.
None of them will resize the page with its content, just crop it if you try and make it smaller.
Using embed I could resize/scale them, but lost annotations.

Any other suggestion ?

**Comment by Hopding** [comment]
@vegarringdal Here's an example of how to scale the page's contents (based on the [PDFPage.translateContent](https://github.com/Hopding/pdf-lib/blob/c47aae6/src/api/PDFPage.ts#L545-L562) method):
```js
const scaleContent = (page: PDFPage, x: number, y: number) => {
  page.node.normalize();

  // @ts-ignore
  page.getContentStream();

  // @ts-ignore
  const start = page.createContentStream(pushGraphicsState(), scale(x, y));
  const startRef = page.doc.context.register(start);

  // @ts-ignore
  const end = page.createContentStream(popGraphicsState());
  const endRef = page.doc.context.register(end);

  page.node.wrapContentStreams(startRef, endRef);
};

(async () => {
  const pdfDoc = await PDFDocument.load(...);

  const page = pdfDoc.getPage(0);

  // Scale all content on the page to half-size
  scaleContent(page, 0.5, 0.5);

  const pdfBytes = await pdfDoc.save();
})();
```

This, in combination with the other methods, should get you what you need.

I should also mention that I'd be open to adding adding a `scaleContent` method directly to `PDFPage` if anybody would like to submit a PR.

**Comment by vegarringdal** [comment]
@Hopding 

Thank you for taking the time to respond.
Tried the sample code, but the annotations does not scale when Im doing it this way.
Is there a way to also get this scaled?

**Comment by wandit** [comment]
> Hello @wandit! Can you please add some details to this describing what exactly you are looking for here?

Hi we do have a couple of annotations that PDF-LIB supports but do we have comment annotations support?
