### ISSUE TITLE
Large amount of text in form field doesn't render consistently

### ISSUE THREAD

**Issue by BigGillyStyle** [Hopding/pdf-lib#413]
OS: macOS 10.15.4
Preview: 11.0 (999.4)
Chrome: 81.0.4044.113
Firefox: 75.0
Adobe Acrobat: 2020.006.20042

When I fill a large amount of text into an AcroForm text field, it only renders as expected (wrapping text to continue to next line) in Mac Preview.  All other PDF rendering engines listed above have different and undesirable behavior:

Chrome: Text is vertically centered in form field and doesn't wrap
Firefox: Text wraps but continues past form field onto the remainder of the document
Acrobat: Text is not visible at all

Example code repo: https://github.com/BigGillyStyle/pdf-form-fill-app (run `npm run pdf-fill`)
[result.pdf](https://github.com/Hopding/pdf-lib/files/4496607/result.pdf)

**Comment by Hopding** [comment]
Hello @BigGillyStyle! pdf-lib has a new forms API that should solve this problem. Please see the README and API docs for details.
