### ISSUE TITLE
Delete a page from pdf?

### ISSUE THREAD

**Issue by agiratech-hari** [Hopding/pdf-lib#42]
How we can delete a page from pdf and display the thumbnail using pdf-lib? Can you please help me?

**Comment by Hopding** [comment]
Hello @agiratech-hari. 

You can delete pages using the [`removePage`](https://github.com/Hopding/pdf-lib/blob/master/docs/classes/_core_pdf_document_pdfdocument_.pdfdocument.md#removepage) method of the `PDFDocument` class. [Integration test 3](https://github.com/Hopding/pdf-lib/blob/1705aebc2bd07e51479d3480958c6cdd169d6d1f/__integration_tests__/tests/test3.ts#L52-L76) tests page removal, so you can reference it as an example.

I'm not sure what you mean by `display the thumbnail using pdf-lib`. Can you explain in more detail what your asking here?

**Comment by agiratech-hari** [comment]
Thumbnail means i need a small view list of full pages in left side like we are seeing in adobe reader and on the right it should display eachpage one by one. Hope you understand? if you didn`t understand let me know

**Comment by agiratech-hari** [comment]
One more doubt, i am new to angular, so how can i access removePage() function from my component? I tried to do like this, but its getting error, 

getpages(){
    getPages = (): PDFPage[] => {
      const pages = [] as PDFPage[];
      this.catalog.Pages.traverse((kid) => {
        if (kid instanceof PDFPage) pages.push(kid);
      });
      return pages;
    };
  }

so how can i access getPages from my component

**Comment by Hopding** [comment]
I think I understand what you mean by thumbnails. I checked the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) and found the following:

> **12.3.4 Thumbnail Images**
> A PDF document may contain thumbnail images representing the contents of its pages in miniature form. A conforming reader may display these images on the screen, allowing the user to navigate to a page by clicking its thumbnail image.

Let me know if this sounds like what you're referring to. This should be possible to do with `pdf-lib`. I can try to take a look this weekend and provide an example.

**Comment by Hopding** [comment]
I'm not sure I understand your question about Angular. I've never written Angular code before myself, so I'm not sure that I can provide much help with that.

As far as how to access the `removePage()` function: You'll need to have a `PDFDocument` created first (via `PDFDocument.create` or `PDFDocument.load`). Then, just call `removePage()` on that object to remove the page at a certain index. For example:
```js
import { PDFDocument } from 'pdf-lib';

// (1) Load an existing document into a PDFDocument object
const pdfBytes: Uint8Array = /* The bytes of some PDF document */
const pdfDoc: PDFDocument = PDFDocument.load(pdfBytes);

// (2) Remove the second page from the document
pdfDoc.removePage(1);

// (3) Serialize the modified PDFDocument into its raw bytes
const modifiedPdfBytes: Uint8Array = pdfDoc.saveToBytes();
```

**Comment by agiratech-hari** [comment]
> I think I understand what you mean by thumbnails. I checked the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) and found the following:
> 
> > **12.3.4 Thumbnail Images**
> > A PDF document may contain thumbnail images representing the contents of its pages in miniature form. A conforming reader may display these images on the screen, allowing the user to navigate to a page by clicking its thumbnail image.
> 
> Let me know if this sounds like what you're referring to. This should be possible to do with `pdf-lib`. I can try to take a look this weekend and provide an example.

Can you please share it? It will be helpful for us to use `pdf-lib`. We are in urgent situation.

**Comment by Hopding** [comment]
@agiratech-hari I think I misunderstood what you meant by page thumbnails. I thought you wanted to set the thumbnail image that would appear when the PDF was opened in a PDF viewer. But after rereading your question today, it seems more like you want to know how to _render_ a PDF page as a thumbnail for a web app. 

`pdf-lib` doesn't do any kind of rendering. It is solely a library for creating/editing PDFs, not rendering them. However, [PDF.js](https://mozilla.github.io/pdf.js/) is a fantastic library maintained by Mozilla that does do rendering. I'd suggest checking that project out. Here's some code for extracting PDF pages into thumbnail images with PDF.js: https://gist.github.com/ichord/9808444

**Comment by agiratech-hari** [comment]
@Hopding Thanks for the update and the suggestion. We will check it
