### ISSUE TITLE
How to make digital signature widget have a visible text?

### ISSUE THREAD

**Issue by nilopaim** [Hopding/pdf-lib#420]
I'm using a code to digitally sign a PDF. It works nicelly.

But I have a doubt. 

```js
  const widgetDict = pdfDoc.context.obj({
    Type: "Annot",
    Subtype: "Widget",
    FT: "Sig",
    Rect: [10, 10, 500, 20],
    V: signatureDictRef,
    T: PDFString.of("Signature1"),
    F: 4,
    P: pages[0].ref,
  });
  const widgetDictRef = pdfDoc.context.register(widgetDict);
```

This code creates a field that, when clicked, shows me a dialog with information about my signature. But this filed has no visible contents. 

How can I put a visible text in this field without breaking the digital signature?

**Comment by Hopding** [comment]
Hello @nilopaim! Please see https://github.com/Hopding/pdf-lib/issues/418#issuecomment-697052730.
