### ISSUE TITLE
Merge PDF Issue

### ISSUE THREAD

**Issue by johnnywhite612** [Hopding/pdf-lib#424]
Really appreciate this library, it's fantastic. However when I use the sample code provided to merge multiple PDFs, it instead makes multiple copies of the first file in the list of files to merge.

E.g. if I use the code to merge file1, file2, and file3, the output merged pdf will contain 3 copies of file1, rather than all three files together. Hope that makes sense.

**Comment by Hopding** [comment]
Hello @johnnywhite612!

Can you please share some sample code and PDF documents that I can use to reproduce the scenario you are describing?

**Comment by johnnywhite612** [comment]
Hey @Hopding , apologies - this issue isn't actually happening. I found out that the real issue occurs when I try to merge 2 PDFs with acro form fields.

For example, if I have a PDF form and I use the library to make 2 separate copies of the form and fill out each copy out separately...when it comes to merging the two, it overwrites the second one with the field values from the first. This is because the acro form fields have the same names in both I presume.

Are there future plans to allow PDF flattening? this would solve this issue. Many many thanks for your help :)

**Comment by Hopding** [comment]
Ah, that makes sense. 

I would like to support PDF flattening. But I'm afraid I don't have plans to work on that myself in the near term. I've got a few other important features to complete first.

**Comment by lucifiel0121** [comment]
Could you have any API provide for save PDF with acro form fields filled transform to pure text (acro form => text only) ?

I wanna make 2 separate PDF with acro form fields , but merge with nice filled by code.
Current save method seems can not do this.
