### ISSUE TITLE
 create PDFArray from array

### ISSUE THREAD

**Issue by rayburrows** [Hopding/pdf-lib#428]
Hi
having problems understanding how to create a PDFArray for 
setting TrimBox of an existing PDF when page.node.TrimBox() returns
undefined. 
I have found old references from PDFArray.fromarray()  but tis seems to be obsolete .
 
page.node.set(PDFName.of(boxName), newBox);

**Comment by Hopding** [comment]
Version `1.5.0` (released just a couple days ago) actually has a dedicated API for setting a page's TrimBox: https://pdf-lib.js.org/docs/api/classes/pdfpage#settrimbox.
```js
const trimBox = page.getTrimBox()

page.setTrimBox(0, 0, 250, 500)
page.setTrimBox(trimBox.x, trimBox.y, 50, 100)
page.setTrimBox(15, 5, trimBox.width - 50, trimBox.height - 100)
```

However, you are correct that the code to create a `PDFArray` has changed. The best way to do it now is as follows:
```js
const pdfDoc = await PDFDocument.create();
const myPdfArray = pdfDoc.context.obj([15, 21, 7, 34]);
```
