### ISSUE TITLE
Very occasional lock-up on PdfDocument.save

### ISSUE THREAD

**Issue by dmccoy42** [Hopding/pdf-lib#431]
[ImageConverter.txt](https://github.com/Hopding/pdf-lib/files/4553293/ImageConverter.txt)
We are experiencing very intermittent lock-ups when calling PdfDocument.save.

We are running your library from AWS lambda to create PDFs from image files (please find the impacted code attached).  The behavior we are seeing is an occasional time out in the lambda at 60 seconds (for an operation that typically requires 4-5 seconds).  Using log messages, we were able to isolate the point of failure at line 27 where we call PdfDocument.save.  The failure only appears to happen with png files, but typically cannot be reproduced with the same png file.  The lambda is not running out of memory when the failure occurs.  I have had no success reproducing the issue locally with thousands of executions.

We first saw the issue with version 1.3.1 of pdf-lib, using sharp 0.25.1 to determine the size and format of the incoming image.

I realize this isn't much to go on, but any guidance you can provide is greatly appreciated.

**Comment by Hopding** [comment]
Hello @dmccoy42!

This is a strange issue. I'm not too sure what is going on here. Even if you aren't running out of memory when these lockups occur, do you find that the memory increases and stays allocated during the lockup? What does the CPU activity look like before and during a lockup?

**Comment by dmccoy42** [comment]
Hi Andrew,



I’m afraid I don’t have detailed metrics on the failure.  Maximum memory is
512 mb, but maximum memory use was 239 mb.  In my attempts to reproduce the
issue locally the library was very well behaved – memory was returned
quickly and CPU use remained constant.  I was never successful at
reproducing the issue outside of AWS lambda.



I don’t know that there’s much you can do for me.  Just wanted to see if
anyone else has experienced similar issues or if you could see anything
problematic in the way we are using your library.



Thank you for your time and help, Andrew.



David





*From:* Andrew Dillon <notifications@github.com>
*Sent:* Thursday, April 30, 2020 5:52 PM
*To:* Hopding/pdf-lib <pdf-lib@noreply.github.com>
*Cc:* dmccoy42 <david.mccoy@ephesoft.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [Hopding/pdf-lib] Very occasional lock-up on
PdfDocument.save (#431)



Hello @dmccoy42 <https://github.com/dmccoy42>!

This is a strange issue. I'm not too sure what is going on here. Even if
you aren't running out of memory when these lockups occur, do you find that
the memory increases and stays allocated during the lockup? What does the
CPU activity look like before and during a lockup?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Hopding/pdf-lib/issues/431#issuecomment-622179482>, or
unsubscribe

**Comment by Hopding** [comment]
@dmccoy42 If you were able to solve this issue or have new information/findings, I would be very interested to know!

**Comment by dmccoy42** [comment]
Hello,



I’m sorry – we did resolve the issue and I forgot to update the thread.
The issue was not related to pdf-lib.



The issue was actually with sharp and the amount of memory allocated to our
lambda.  Over time,  sharp would consume more memory until it eventually
hit the limit, causing the strange timeout behavior we were seeing in the
lambda.  We upped the memory available and eventually found a point where
sharp behaved well.



Thank you for your attention to this and I apologize for the red herring.



Best of health.



David



*From:* Andrew Dillon <notifications@github.com>
*Sent:* Sunday, September 20, 2020 3:01 PM
*To:* Hopding/pdf-lib <pdf-lib@noreply.github.com>
*Cc:* dmccoy42 <david.mccoy@ephesoft.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [Hopding/pdf-lib] Very occasional lock-up on
PdfDocument.save (#431)



Closed #431 <https://github.com/Hopding/pdf-lib/issues/431>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Hopding/pdf-lib/issues/431#event-3786412786>, or
unsubscribe

**Comment by Hopding** [comment]
No worries! Thanks for the update 👍
