### ISSUE TITLE
DrawText: is right align possible?

### ISSUE THREAD

**Issue by spock123** [Hopding/pdf-lib#432]
I am sorry for asking this question but I have trolled all the Documentation, API, Google etc but can't seem to figure out if this is possible:

Right align text in a DrawText()

I am generating an invoice PDF from order lines and some of the text entries need to be in a right aligned column...

Is this possible at all? I tried setting the width of a text field but could not find parameters for text alignment.

Thanks

**Comment by Hopding** [comment]
Hello @spock123!

This is certainly possible to do. You'll just need to measure how wide the text you wish to draw is and position it based on that. Here's an example:

```js
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();

  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const text = 'Foo bar';
  const fontSize = 35;
  const textWidth = font.widthOfTextAtSize(text, fontSize);
  const boxWidth = 250;
  const boxHeight = 100;
  const boxX = 50;
  const boxY = 50;

  const page = pdfDoc.addPage([350, 350]);
  page.drawRectangle({
    x: boxX,
    y: boxY,
    width: boxWidth,
    height: boxHeight,
    borderColor: rgb(1, 0, 0),
  });
  page.drawText(text, {
    x: boxX + boxWidth - textWidth,
    y: boxY,
    font,
    size: fontSize,
  });

  const pdfBytes = await pdfDoc.save();
})();
```

And here's what the resulting page looks like:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/80869958-f1d55980-8c68-11ea-9ddd-c68a9082e90c.png" height="500">
</kbd>

>

I hope this helps. Please let me know if you have any additional questions!

**Comment by spock123** [comment]
@Hopding wow thank you for a very thorough and detailed answer. I'll play around with it. Thank you again!

**Comment by hilmanski** [comment]
HI. has anyone figure out how to work with text-alignment on multiline? or at least a snippet that we can improve on
currently looking around at API / samples / issues haven't found one..

[update]
this might be close to the case:
https://github.com/Hopding/pdf-lib/issues/72
https://github.com/Hopding/pdf-lib/issues/701

**Comment by garma83** [comment]
im a bit shocked that the accepted answer is actually considered acceptable. Right text alignment is super standard functionality, and now I need to a) break up my text in multi lines myself and then b) calculate where to position the text per line

This is not a solution its a workaround. Then at least say its not supported.
