### ISSUE TITLE
[Feature Request] API to sanitize documents

### ISSUE THREAD

**Issue by MarcGodard** [Hopding/pdf-lib#433]
I am looking for a function that will open a pdf, and remove harmful script tags and other harmful elements in the meta data.

Usually a security scan finds these, but I would like to prevent them without having to do a scan.

I would also like to preserve the remaining pdf, unlike just scanning and deny the file.

**Comment by Hopding** [comment]
Hello @MarcGodard!

I think an API like this could belong in pdf-lib, if it's just a matter of removing scripts, links, etc... That being said, I don't personally have time to work on this right now. But I'd be happy to accept a PR for it, and answer any questions you (or others) might have about implementing it.

Please also see https://github.com/Hopding/pdf-lib/issues/375 and https://github.com/Hopding/pdf-lib/issues/536. They have some additional information/examples about removing scripts and links.

**Comment by MarcGodard** [comment]
@Hopding Great, I will do a deep dive into this and the auth stuff that you mentioned a similar response to. Just lately work has been crazy.

**Comment by MarcGodard** [comment]
This isn't an issue, it is a feature-request.

**Comment by Hopding** [comment]
@MarcGodard please see https://github.com/Hopding/pdf-lib/issues/177#issuecomment-924479149

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
