### ISSUE TITLE
would this be possible?

### ISSUE THREAD

**Issue by techsin** [Hopding/pdf-lib#434]
How should I go about creating this program or is this even a good lib for that?

Imagine you have 5 forms, all of them ask for the same information again and again.

So why not put Variables in all of those places once, like so $FIRST_NAME, $LAST_NAME, $DOB, etc... 

Then have a json file where you define all variables and their values.

Run a nodejs program to which you provide pdf files, and json file. and it creates output fold with all those variables field in

I'm not sure what to do about checkboxes and select boxes.

I can write nodejs program to parse json file etc, but not sure how to go about modifying pdf files .

**Comment by Hopding** [comment]
Closing as this question was addressed in https://github.com/Hopding/pdf-lib/issues/550.
