### ISSUE TITLE
Error when using Arabic characters with standard font

### ISSUE THREAD

**Issue by shiheb** [Hopding/pdf-lib#435]
Hello guys
I just tired to use arabic letters (like this sentence for example : اهلا وسهلا) in a form to generate automatically a PDF with pdf-lib, It generates an error

> Encoding.js:17 Uncaught (in promise) Error: WinAnsi cannot encode "ه"
    at hn.encodeUnicodeCodePoint (Encoding.js:17)
    at t.encodeTextAsGlyphs (StandardFontEmbedder.js:79)
    at t.encodeText (StandardFontEmbedder.js:24)
    at t.encodeText (PDFFont.js:35)
    at e.drawText (PDFPage.js:779)
    at modifyPdf ((index):93)

Is there any suggestion to resole this ?
if not, anyone have an idea to integrate some arabic letters to a pdf in javascript? 

Thank you.

**Comment by Hopding** [comment]
Hello @shiheb!

You will need to embed a custom font that supports arabic characters. The README contains an example demonstrating how to do this: https://github.com/Hopding/pdf-lib#embed-font-and-measure-text. Please also see #389, #217, #211, and #50.

**Comment by Hopding** [comment]
See https://github.com/Hopding/pdf-lib#fonts-and-unicode for more details on this.

**Comment by MertHaddad** [comment]
> Hello guys I just tired to use arabic letters (like this sentence for example : اهلا وسهلا) in a form to generate automatically a PDF with pdf-lib, It generates an error
> 
> > Encoding.js:17 Uncaught (in promise) Error: WinAnsi cannot encode "ه"
> > at hn.encodeUnicodeCodePoint (Encoding.js:17)
> > at t.encodeTextAsGlyphs (StandardFontEmbedder.js:79)
> > at t.encodeText (StandardFontEmbedder.js:24)
> > at t.encodeText (PDFFont.js:35)
> > at e.drawText (PDFPage.js:779)
> > at modifyPdf ((index):93)
> 
> Is there any suggestion to resole this ? if not, anyone have an idea to integrate some arabic letters to a pdf in javascript?
> 
> Thank you.

did you find a fix?
