### ISSUE TITLE
PDF-A2 compliance

### ISSUE THREAD

**Issue by danisss9** [Hopding/pdf-lib#439]
Hello,

I have been using pdf-lib to create pdfs and it has been great, but recently I was asked to make the generated pdfs compliant with the PDF-A2 rules. I checked the generated pdfs with the [VeraPdf tool](https://verapdf.org/) and it failed on 3 aspects: [report](https://i.imgur.com/Eiketbk.png). Is there any way to make it PDF-A compliant, or any plans for pdf-lib to support this?

Best regards!

**Comment by Hopding** [comment]
Hello @danisss9!

It is possible to generate PDF-A2 compliant PDFs with `pdf-lib`. Please see https://github.com/Hopding/pdf-lib/issues/230 and https://github.com/Hopding/pdf-lib/issues/410.
