### ISSUE TITLE
What is the Unit of Measurement used for x and y coordinates? 

### ISSUE THREAD

**Issue by VinnyV88** [Hopding/pdf-lib#442]
Hello,

I'm coming over from pdfkit where the UOM for x and y coordinates are Points. I can't find anywhere in the documentation what UOM is used in this library. It does not appear to be Points because when I port over my code, the text is not plotted where I expect it to be.

Also, is there a way to specify the margin applied to pages? I would like specify 0 margin all around.

Thank you for your time.

Vincent

**Comment by VinnyV88** [comment]
Sorry, I just found this answer in one of your closed issues. Weird that it seems to use the same UOM as pdfkit but my data is plotting differently in pdf-lib.

https://github.com/Hopding/pdf-lib/issues/19#issuecomment-412275915

**Comment by VinnyV88** [comment]
OK, I figured it out. The x coordinate was fine. I had to use height - y coordinate to get it where I wanted on the page.

**Comment by Hopding** [comment]
Hello @VinnyV88!

Glad you were able to get this working!
