### ISSUE TITLE
[Feature Request] API to set access privileges

### ISSUE THREAD

**Issue by ianaz** [Hopding/pdf-lib#443]
Hey Hopding, nice work!

Just pointing out that access privileges like read-only, copying,... could be a nice addition, for example as `options` parameter when saving.

`pdfDoc.save({ readOnly: true, copy: false })`

I'm looking at the pdfkit implementation and doesn't look that straighforward, unfortunately would take lots of time for me to try to do it but maybe someone knows the way :)

**Comment by gettalong** [comment]
FYI: Access privileges can only be set on encrypted documents, so encrypting a document has to be supported.

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
