### ISSUE TITLE
Converting matching colors to spot colors

### ISSUE THREAD

**Issue by kimmobrunfeldt** [Hopding/pdf-lib#445]
Hi!

I'm trying to convert colors in an existing PDF document using pdf-lib. My PDF has only 1 page but ideally the solution would support multiple pages.

On a higher level, I assume the process would go something like: go through all the pages in the PDF, and for each object in the page, check if it's an object that has a color (text, rectangle, paths, etc). I'm not concerned about changing any embedded images, only about vector objects.

I looked into anything "traverse" or "iterate" or "getObjects" in API docs or issues, but didn't find clues how to move forward. [This issue](https://github.com/Hopding/pdf-lib/issues/296) had code that traverses text objects but not sure how to move forward from that.

How could this be done? I attached an example PDF, I'm trying to convert all rgb (0, 0, 0) colors to a certain spot color. AFAIK, spot color is a CMYK color underneath, but in its own color space (?). Some more about spot colors: https://github.com/alafr/SVG-to-PDFKit/pull/62 

The process with Adobe tools is described here: https://graphicdesign.stackexchange.com/questions/119758/why-isnt-convert-all-spots-to-cmyk-converting-my-pdf-to-cmyk-in-adobe-acroba

[test.pdf](https://github.com/Hopding/pdf-lib/files/4628923/test.pdf)

**Comment by kimmobrunfeldt** [comment]
I researched PDF specification and the library code as much as possible to get further. pdf-lib code is *really well* written, thousand kudos for that :+1: :+1:

In any case, it seems that what I'd need to do is to first add the spot color definition to the document (more in [8.6.6.4 Separation Colour Spaces](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf)). I'm not yet sure if the `/Separation` definition should be done or copied to all occurrences where color is changed, or just once in the document.

After that, traverse the document pages through, iterate their decoded content stream and replace all [color definitions](https://github.com/Hopding/pdf-lib/blob/1268907c8686d1cec48465b5650286f384e736f4/src/core/operators/PDFOperatorNames.ts) with a new color definition. If I understand correctly, changing color with an operator keeps the color the same for the subsequent draw operators. so there could be room optimizing in that regards but I'd prefer to keep this a dumb search and replace. In the test.pdf there are two embedded pdfs on the first page, as you can see from this image:

<img width="516" alt="Screenshot 2020-05-15 10 49 27" src="https://user-images.githubusercontent.com/1232405/82025672-55647b80-969a-11ea-8b15-c363ffd2cc1e.png">

This means that embedded PDFs should be taken into account in the traversal.

**Comment by Hopding** [comment]
Hello @kimmobrunfeldt!

I'm afraid I don't have time to write out a full example right now. But I've written up something to help get you started. 

The script below runs the `processContentStream(...)` function with each content stream and FormXObject in the document. Most of the work to replace colors would need to be done in the `processContentStream(...)` function. You might find the example I provided in https://github.com/Hopding/pdf-lib/issues/446#issuecomment-629561090 to be helpful. It demonstrates how to decode a content stream, parse its contents with a regex, and insert a modified version back into the document.

```js
import fs from 'fs';

import { PDFDocument, PDFRawStream, PDFRef, PDFPage, PDFName } from 'pdf-lib';

const processPageContentsAndFormXObjects = (page: PDFPage) => {
  const { Contents, XObject } = page.node.normalizedEntries();

  if (Contents) {
    Contents.asArray().forEach((streamRef) => {
      if (streamRef instanceof PDFRef) {
        const stream = page.doc.context.lookup(streamRef);
        if (stream instanceof PDFRawStream) {
          processContentStream(page, streamRef, stream);
        }
      }
    });
  }

  XObject.entries().forEach(([, xObjectRef]) => {
    const xObject = page.doc.context.lookup(xObjectRef);
    if (
      xObjectRef instanceof PDFRef &&
      xObject instanceof PDFRawStream &&
      xObject.dict.lookup(PDFName.of('Subtype')) === PDFName.of('Form')
    ) {
      processContentStream(page, xObjectRef, xObject);
    }
  });
};

const processContentStream = (
  page: PDFPage,
  ref: PDFRef,
  stream: PDFRawStream,
) => {
  console.log('Processing stream:', ref);
  // TODO: Make this do something useful
};

(async () => {
  const pdfDoc = await PDFDocument.load(...);

  pdfDoc.getPages().forEach((page) => {
    processPageContentsAndFormXObjects(page);
  });

  const pdfBytes = await pdfDoc.save();

  fs.writeFileSync('./out.pdf', pdfBytes);
})();
```

The other large piece of the puzzle I haven't yet mentioned is how to embed and use the spot color itself. Here's a quick example demonstrating how to do this (the spot color is based on https://github.com/Hopding/pdf-lib/issues/444):
```js
import fs from 'fs';

import {
  PDFDocument,
  PDFName,
  PDFOperator,
  PDFOperatorNames as Ops,
  pushGraphicsState,
  popGraphicsState,
} from 'pdf-lib';

const setStrokingColorSpace = (colorSpace: PDFName) =>
  PDFOperator.of(Ops.StrokingColorspace, [colorSpace]);

const setNonStrokingColorSpace = (colorSpace: PDFName) =>
  PDFOperator.of(Ops.NonStrokingColorspace, [colorSpace]);

(async () => {
  const pdfDoc = await PDFDocument.load(...);

  // Embed spot color in document
  const colorSpace = pdfDoc.context.obj([
    'Separation',
    'MyGoldSC',
    'DeviceCMYK',
    {
      // Note: I'm not sure if this transform function is valid/correct
      FunctionType: 2,
      Domain: [0, 1],
      C0: [0, 0, 0, 0],
      C1: [0, 0.17, 0.74, 0.17],
      N: 1,
      Length: 62,
    },
  ]);
  const colorSpaceRef = pdfDoc.context.register(colorSpace);

  // Get the first page
  const page = pdfDoc.getPage(0);

  // Add the spot color to the page's resources
  const { Resources } = page.node.normalizedEntries();
  const colorName = PDFName.of('MyGoldSC');
  Resources.set(colorName, colorSpaceRef);

  // Draw stuff on the page using the spot color
  page.pushOperators(
    pushGraphicsState(),
    setStrokingColorSpace(colorName),
    setNonStrokingColorSpace(colorName),
    // ...other drawing operations go here...
    popGraphicsState(),
  );

  const pdfBytes = await pdfDoc.save();

  fs.writeFileSync('./out.pdf', pdfBytes);
})();
```

My apologies if you notice any errors in the example scripts. I didn't have much time to write and test them.

I hope this helps. Please let me know if you have any additional questions!

**Comment by kimmobrunfeldt** [comment]
Thank you for the great examples and help!

**Comment by Hopding** [comment]
You're welcome. I hope you found them useful 👍

**Comment by signalwerk** [comment]
@kimmobrunfeldt have you been successful and have somewhere your code published? I have a similar problem I would like to solve.
