### ISSUE TITLE
[Feature Request] API to create an outline (table of contents) for PDF readers

### ISSUE THREAD

**Issue by achordia20** [Hopding/pdf-lib#450]
This should allow users to display a visual outline that is linked to different parts of the pdf.

**Comment by leverarch-app** [comment]
This was mentioned in [issue #127](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi2–O-_NrpAhWtXRUIHTj4CeMQFjAAegQIAxAB&url=https%3A%2F%2Fgithub.com%2FHopding%2Fpdf-lib%2Fissues%2F127&usg=AOvVaw0_Rx_cSTGml0TXPfpeGQHi) but I think the suggested solution only works with an earlier version of pdf-lib.

I’d love to find out how you can do this with the later version.

**Comment by jackwshepherd** [comment]
+1 for this

**Comment by feodormak** [comment]
@leverarch-app, I have [just posted in issue #127](https://github.com/Hopding/pdf-lib/issues/127#issuecomment-641710694) my updated code for @Hopding's solution with the current version.

**Comment by lillallol** [comment]
@achordia20 @leverarch-app 
I created a module that has a high level api and uses pdf-lib to add outline to outline-less pdfs. You can find it [here](https://www.npmjs.com/package/@lillallol/outline-pdf).

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
