### ISSUE TITLE
 Cannot replace a form value, for a form field, where multiple occurrences of the form field exist

### ISSUE THREAD

**Issue by YOU54F** [Hopding/pdf-lib#451]
Hey @Hopding,

Thank you for the awesome repository, it has been really useful.

I've created a demo using [pdf-lib](https://github.com/Hopding/pdf-lib) to fill out form fields in an AcroForm PDF to look to alternatives to an existing solution using iTextPDF. The functions have come from examples in some of the other issues, and would actually be quite nice exposed as part of the pdflib api! :) Happy to help do this, as I think it would be really useful!

Issue:-  Cannot replace a form value, for a form field, where multiple occurrences of the form field exist 

Expected Behaviour:- A single name reference can be provided, and this value is used to fill in all form fields matching that name reference.

Actual Behaviour:- An exception is thrown where we have two fields with the same name, as they are referenced as instalments#0 & instalments#1 in the adobe form

```
Error: Expected instance of PDFArray, but got instance of undefined
```

Steps to reproduce:-

I have created a minimal example here - https://github.com/YOU54F/pdf-form-node

It contains a test.pdf with 3 form fields.

<img width="532" alt="Screenshot 2020-05-18 at 19 01 16" src="https://user-images.githubusercontent.com/19932401/82244955-ff156800-9939-11ea-9d33-fe943a315b91.png">

## Filling in a form field, where it only exists once in a document

To run:

```sh
npm install
npm run single
```

- Reads the `test.pdf` template and outputs as `filled_single.pdf`.
- QPDF is called to correct `filled_single.pdf` and outputs as `fixed_single.pdf`

## Filling in a form field, where it exists more once in a document

To run:

```sh
npm install
npm run multiple
```

- Reads the `test.pdf` template and outputs as `filled_multiple.pdf`.
- QPDF is called to correct `filled_multiple.pdf` and outputs as `fixed_multiple.pdf`

**Comment by YOU54F** [comment]
I actually think this will work, as it has correctly read there are three fields, when I have just ran it against the above pdf. Will test out and report back!


https://github.com/Hopding/pdf-lib/issues/349#issuecomment-585508339

**Comment by YOU54F** [comment]
So that has found the three fields, just trying to fill values on the kids now

```
➜  pdf-form-node git:(master) ✗ ts-node nested.ts
rootField
<<
/AP <<
/N 105 0 R
>>
/BS <<
/S /S
/W 0
>>
/DA (/Helv 6 Tf 0 g)
/DV (this is a single field)
/F 4
/FT /Tx
/MK <<
>>
/P 19 0 R
/Rect [ 264.379 488.376 504.748 528.144 ]
/Subtype /Widget
/T (single)
/Type /Annot
/V (this is a single field)
>>

rootField
<<
/DA (/Helv 6 Tf 0 g)
/DV (this is text to be replaced entered in a mulitple form fields, the text get shown on all fields)
/FT /Tx
/Kids [ 35 0 R 36 0 R ]
/T (multiple)
/V (this is text to be replaced entered in a mulitple form fields, the text get shown on all fields)
>>

Total fields: 2
childField
<<
/AP <<
/N 105 0 R
>>
/BS <<
/S /S
/W 0
>>
/DA (/Helv 6 Tf 0 g)
/DV (this is a single field)
/F 4
/FT /Tx
/MK <<
>>
/P 19 0 R
/Rect [ 264.379 488.376 504.748 528.144 ]
/Subtype /Widget
/T (single)
/Type /Annot
/V (this is a single field)
>>

childField
<<
/AP <<
/N 104 0 R
>>
/BS <<
/S /S
/W 0
>>
/F 4
/MK <<
>>
/P 19 0 R
/Parent 102 0 R
/Rect [ 264.775 379.39 505.144 419.158 ]
/Subtype /Widget
/Type /Annot
>>

childField
<<
/AP <<
/N 103 0 R
>>
/BS <<
/S /S
/W 0
>>
/DA (/Helv 6 Tf 0 g)
/F 4
/MK <<
>>
/P 19 0 R
/Parent 102 0 R
/Rect [ 266.098 274.644 506.467 314.412 ]
/Subtype /Widget
/Type /Annot
>>

Total childFields: 3
```

**Comment by YOU54F** [comment]
Looks like the kids don't have this property
```
    PDFName { encodedName: '/T' } => PDFString { value: 'single' },
```
but could look up that valuee on the parent, as it has a parent value
```
    PDFName { encodedName: '/Parent' } => PDFRef { objectNumber: 102, generationNumber: 0, tag: '102 0 R' },
```

```
found a field matching multiple: acroField: TRUE which has the the fieldName undefined

PDFDict {
  dict: Map {
    PDFName { encodedName: '/AP' } => PDFDict { dict: [Map], context: [PDFContext] },
    PDFName { encodedName: '/BS' } => PDFDict { dict: [Map], context: [PDFContext] },
    PDFName { encodedName: '/F' } => PDFNumber { numberValue: 4, stringValue: '4' },
    PDFName { encodedName: '/MK' } => PDFDict { dict: Map {}, context: [PDFContext] },
    PDFName { encodedName: '/P' } => PDFRef { objectNumber: 19, generationNumber: 0, tag: '19 0 R' },
    PDFName { encodedName: '/Parent' } => PDFRef { objectNumber: 102, generationNumber: 0, tag: '102 0 R' },
    PDFName { encodedName: '/Rect' } => PDFArray { array: [Array], context: [PDFContext] },
    PDFName { encodedName: '/Subtype' } => PDFName { encodedName: '/Widget' },
    PDFName { encodedName: '/Type' } => PDFName { encodedName: '/Annot' }
  },
PDFDict {
  dict: Map {
    PDFName { encodedName: '/AP' } => PDFDict { dict: [Map], context: [PDFContext] },
    PDFName { encodedName: '/BS' } => PDFDict { dict: [Map], context: [PDFContext] },
    PDFName { encodedName: '/DA' } => PDFString { value: '/Helv 6 Tf 0 g' },
    PDFName { encodedName: '/F' } => PDFNumber { numberValue: 4, stringValue: '4' },
    PDFName { encodedName: '/MK' } => PDFDict { dict: Map {}, context: [PDFContext] },
    PDFName { encodedName: '/P' } => PDFRef { objectNumber: 19, generationNumber: 0, tag: '19 0 R' },
    PDFName { encodedName: '/Parent' } => PDFRef { objectNumber: 102, generationNumber: 0, tag: '102 0 R' },
    PDFName { encodedName: '/Rect' } => PDFArray { array: [Array], context: [PDFContext] },
    PDFName { encodedName: '/Subtype' } => PDFName { encodedName: '/Widget' },
    PDFName { encodedName: '/Type' } => PDFName { encodedName: '/Annot' }
  },
found a field matching single: acroField: TRUE which has the the fieldName (single)
{
  dict: Map {
    PDFName { encodedName: '/AP' } => PDFDict { dict: [Map], context: [PDFContext] },
    PDFName { encodedName: '/BS' } => PDFDict { dict: [Map], context: [PDFContext] },
    PDFName { encodedName: '/DA' } => PDFString { value: '/Helv 6 Tf 0 g' },
    PDFName { encodedName: '/DV' } => PDFString { value: 'this is a single field' },
    PDFName { encodedName: '/F' } => PDFNumber { numberValue: 4, stringValue: '4' },
    PDFName { encodedName: '/FT' } => PDFName { encodedName: '/Tx' },
    PDFName { encodedName: '/MK' } => PDFDict { dict: Map {}, context: [PDFContext] },
    PDFName { encodedName: '/P' } => PDFRef { objectNumber: 19, generationNumber: 0, tag: '19 0 R' },
    PDFName { encodedName: '/Rect' } => PDFArray { array: [Array], context: [PDFContext] },
    PDFName { encodedName: '/Subtype' } => PDFName { encodedName: '/Widget' },
    PDFName { encodedName: '/T' } => PDFString { value: 'single' },
    PDFName { encodedName: '/Type' } => PDFName { encodedName: '/Annot' },
    PDFName { encodedName: '/V' } => PDFString { value: 'this is a single field' }
  },
```

**Comment by YOU54F** [comment]
Got this working now nicely, will update my repo when I get time and post back the solution! Thanks again for the great repo

**Comment by Hopding** [comment]
`pdf-lib` now has form creation and filling APIs that should be used instead of the above example(s). See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFTextField.setText`](https://pdf-lib.js.org/docs/api/classes/pdftextfield#settext) method is of particular relevance to this issue.

**Comment by YOU54F** [comment]
Thanks again @Hopding ! Look forward to trying this out 👍🏽
