### ISSUE TITLE
Change font in loaded PDF document

### ISSUE THREAD

**Issue by Hatgor** [Hopding/pdf-lib#452]
Good day! 
I'm stuck in trying to convert a pdf document to the array of png images. 
I tried to use the pdf.js library, but seems there are some unresolved issues in rendering text layer of the document. 

![image](https://user-images.githubusercontent.com/30573650/82249046-cf725a00-9951-11ea-9d03-ae9fb090a4a0.png)

Seems it happens due to unsupported font type. 

Can I use your lib to change the font type in the document? 
Or maybe there is some way to change the font type by copying the page into the new document? 

Thank you in advance!

**Comment by Hopding** [comment]
Hello @Hatgor! I'm afraid this would be difficult to do with pdf-lib. Most of the necessary APIs to access the document and edit its structure exist. But swapping out a font is challenging for many reasons, and I do not have nearly enough time to construct an example of how to do it.

Best of luck!
