### ISSUE TITLE
Regarding Text styling and paras 

### ISSUE THREAD

**Issue by hari-gillala** [Hopding/pdf-lib#453]
Hi, 

I can see pdf-lib can be used to add text to it, using the below.
```js
 page.drawText(`Information That's unavailable`, {
        x: 20,
        y: height - 4 * fontSize,
        size: fontSize,
    })
```
But How can I do multiline Headings, paragraphs with stylings as below attached in the screenshot please?
![pdf-lib](https://user-images.githubusercontent.com/55185692/82574965-c2d34900-9b7f-11ea-85c4-9f059ce40815.JPG)

**Comment by Hopding** [comment]
Hello @hari-gillala! I'm not sure I really understand exactly what you're asking about. But it sounds similar to https://github.com/Hopding/pdf-lib/issues/568#issuecomment-695129047. Please take a look at that issue and my answer. If you still have questions, please open a new issue with some more details, specifics, and examples.
