### ISSUE TITLE
Broken PDF after processing with pdf-lib

### ISSUE THREAD

**Issue by Werewolve** [Hopding/pdf-lib#456]
After just loading and saving a pdf with pdf-lib its broken, can't be loaded with any pdf reader. The file looks in an text editor like this:
![broken_pdf](https://user-images.githubusercontent.com/3767530/82696228-e6bd8a00-9c66-11ea-96e8-0cc68a369559.png)
Normally its more cryptic and not so numeric.

I use this code:
```js
const pdfDoc = await PDFDocument.load(fs.readFileSync('./assets/pdfs/file.pdf'));
const pdfBytes = await pdfDoc.save();

res.attachment('File.pdf');
res.contentType('application/pdf');
res.send(pdfBytes);
````

Any ideas what I'm doing wrong?

**Comment by Hopding** [comment]
Hello @Werewolve!

It looks like you're sending back the response with `express`. I believe you need to wrap the `pdfBytes` in a `Buffer` (see https://github.com/Hopding/pdf-lib/issues/163#issuecomment-628189771). For example:
```js
res.send(Buffer.from(pdfBytes));
```

**Comment by Werewolve** [comment]
Works! Thanks! :)

**Comment by ywaserblat-excelforce** [comment]
This hidden peace of info about handling pdf in express.js response should be prominently displayed somewhere in the docs. I've spent half a day figuring this out till i found this closed thread.
