### ISSUE TITLE
HELP WANTED

### ISSUE THREAD

**Issue by sundsx** [Hopding/pdf-lib#457]
In forst thank you for pdf-lib. 
If it is possible to split pages from a pdf file master, collect individual pages and save as zip? 
ex: one pdf with 6 page to 6 pdf files from each pages.
Thank you

**Comment by sebastinez** [comment]
Hi @sundsx 

Yes, you could load the document, check how many pages the document has, then create a new document for each page, and save each new document to it's own `Uint8Array`.
```js
  const existingDoc = await PDFDocument.load(
    fs.readFileSync("pathToExistingFile"),
  );

  let byteArrays = existingDoc.getPages().map(async (_, i) => {
    let doc = await PDFDocument.create();
    let [copiedPage] = await doc.copyPages(existingDoc, [i]);
    doc.addPage(copiedPage);
    return await doc.save();
  });

  Promise.all(byteArrays).then((byteArray) => {
    // Pipe them into a gzip stream or use something like 
    // node-zip (https://www.npmjs.com/package/node-zip)
  });
```

**Comment by sundsx** [comment]
Thank you Sebastian for the quickly reply! So after learn a bit more
pdf-lib I know now that I can be better than zip.

So it is possible send the ceated pdf directly to php by Ajax? I’m stuck on
save document in the path. I don t use node.js. My server script lives on
php.

Can you put me in the right path for achiachieve my goal?

We’ll be awesome

Il giorno dom 24 mag 2020 alle 09:53 Sebastian Martinez <
notifications@github.com> ha scritto:

**Comment by sebastinez** [comment]
Buongiorno @sundsx 😃 

Don't know really your requirements, if you're using a frontend framework, and what you want to receive via AJAX on your php server script

But you can use pdf-lib also in the web browser inside a HTML file, here for example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <input type="file" name="file" id="file" />
    <script src="https://cdn.jsdelivr.net/npm/pdf-lib@1.6.0/dist/pdf-lib.js"></script>
    <script defer>
      // Destructure PDFDocument
      const { PDFDocument } = PDFLib;

      const fileInput = document.getElementById("file");
      fileInput.addEventListener("change", (evt) => {

        // Using a FileReader() you can read the selected file into an ArrayBuffer
        const reader = new FileReader();
        reader.addEventListener("load", (event) => {

          // This trigger once the FileReader, read the whole file.
          PDFDocument.load(event.target.result)
            .then((existingDoc) => {

              // This is the same code as in the before example.
              let byteArrays = existingDoc.getPages().map(async (_, i) => {
                let doc = await PDFDocument.create();
                let [copiedPage] = await doc.copyPages(existingDoc, [i]);
                doc.addPage(copiedPage);
                return await doc.save();
              });

              Promise.all(byteArrays).then((byteArray) => {
              // Here you could make a AJAX call to your PHP on your server
              // sending the byte arrays with every page of the PDF Document on its own
              });
            })
            .catch(console.error);
        });
        reader.readAsArrayBuffer(evt.target.files[0]);
      });
    </script>
  </body>
</html>
```

**Comment by sundsx** [comment]
Buonasera Sebastian 😀, you are a very gentleman.

try to be short.i need to send a pdf certificate to each participant in a
seminar (non profit).
Each certificate must have printed Name and Surname on face.
The list of participant come from json file uploaded in front end.
Like this: [
 {
   "Nome": "John",
   "Cognome": "Doe",
   "Email": "john.doe@emailaddress.eu"
 },
 {
   "Nome": "Sunds",
   "Cognome": "Sundsx",
   "Email": "sundsx@gmail.com"
 }
]//.....

- i can loop each JSON[ i ],

- i can pass Name, Surname and email property to function
embedFontAndMeasureText(){}


- add text with custom font with success.

But instead of saving the file via browser I would like to send it as an
attachment
We can start from here.

// SO similar request:
https://stackoverflow.com/questions/60675321/send-pdfbyte-array-from-js-to-php-via-ajax-and-send-an-email-with-the-php-file
CODE ///

<html>
  <head>
    <meta charset="utf-8" />

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title></title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="
https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
integrity=
"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
crossorigin="anonymous">

 <script src="js/jquery-3.4.1.min.js" ></script>

<script src="
https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
integrity=
"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
crossorigin="anonymous"></script>
<script src="
https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
integrity=
"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
crossorigin="anonymous"></script>

<link rel="stylesheet" type="text/css" href="
http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.min.css"
/>
<link rel="stylesheet" href="
http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/blackboard.min.css
">
<link rel="stylesheet" href="
http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.min.css
">
<link rel="stylesheet" href="summernote/dist/oceanic-next.css">
<script type="text/javascript" src="
http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></
script>
<script src="
http://cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.min.js"
></script>
<script src="
http://cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.min.js"><
/script>

<link rel="stylesheet" href="summernote/dist/summernote-bs4.css">
<script src="summernote/dist/summernote-bs4.js" ></script>
<script src=
"summernote/dist/summernote-image-attributes-master/summernote-image-attributes.js"
 ></script>
<script src=
"summernote/dist/summernote-image-attributes-master/lang/it-IT.js" ></script
>
<script src="https://unpkg.com/pdf-lib@1.4.0"></script>
<script src="https://unpkg.com/@pdf-lib/fontkit@0.0.4"></script>
<script src="https://unpkg.com/downloadjs@1.4.7"></script>

  </head>

  <body>

      <p></p>
      <h1>test</h1>
      <br>
      <div class="container">

      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">@</span>
        </div>
        <input type="file" name="file" class="form-control" id="input-file"
placeholder="Username" aria-label="Username" aria-describedby="basic-addon1"
>
      </div>

      </div>
      <div class="container">
        <h1>Summernote with Bootstrap 4</h1>
        <p>
          <span class="badge badge-primary">jQuery v3.4.1</span>
          <span class="badge badge-info">Bootstrap v4.4.1</span>
        </p>
        <div class="summernote"></div>
        <hr>
        <div class="row">
          <button type="button" class="btn btn-primary" id="btnx">Primary</
button>
        </div>

      </div>


    <p id="small"></p>
  </body>


<script>

// A $( document ).ready() block.
$(document).ready(function() {
    console.log( "ready!" );

    $('.summernote').summernote({
      toolbar: [
    //[groupname, [button list]]
    ['style', ['bold', 'italic', 'underline', 'clear']],
    ['fontname', ['fontname']],
    ['color', ['color']],
    ['para', ['ul', 'ol', 'paragraph']],
    ['insert',['picture','link', 'video', 'table', 'hr']],
    ['view', ['fullscreen', 'codeview', 'help']],

    ],
        popover: {
            image: [
                ['custom', ['imageAttributes']],
                ['imagesize', ['imageSize100', 'imageSize50', 'imageSize25'
]],
                ['float', ['floatLeft', 'floatRight', 'floatNone']],
                ['remove', ['removeMedia']]
            ],
        },
      lang: 'it-IT', // default: 'en-US',
      imageAttributes:{
            icon:'<i class="note-icon-pencil"/>',
            removeEmpty:false,
// true = remove attributes | false = leave empty if present
            disableUpload: false
// true = don't display Upload Options | Display Upload Options
        },
        height: 300,
        tabsize: 2,
        codemirror: {
          theme: 'monokai'
        }
      });


  function readTextFile(file, callback) {
    var rawFile = new XMLHttpRequest();
    rawFile.overrideMimeType("application/json");
    rawFile.open("GET", file, true);
    rawFile.onreadystatechange = function () {
      if (rawFile.readyState === 4 && rawFile.status == "200") {
        callback(rawFile.responseText);
      }
    }
    rawFile.send(null);
  }


  $('#btnx').click(function () {

    var fileToUpload = $('#input-file').prop('files')[0];
    var path
 = (window.URL || window.webkitURL).createObjectURL(fileToUpload);
    var markupStr = $('.summernote').summernote('code');
    console.log(markupStr);

    readTextFile(path, function (text) {
      var data = JSON.parse(text);
      console.log(data);
      //Your ajax call here.
      console.log(data.length);
      for (var i = 0; i < data.length; i++) {
        embedFontAndMeasureText(data[i].Nome, data[i].Cognome,
data[i].Email, markupStr, data[i].Path);
      }
    });



  });

  const { PDFDocument, PDFDocumentWriter, rgb } = PDFLib

  async function embedFontAndMeasureText(nome, cognome, email, markupStr) {
    // Fetch custom font
    const url = 'myfont/Gotham-Medium.otf'
    const fontBytes = await fetch(url).then(res => res.arrayBuffer())

    const url_file = 'files/Intelligenza_emotiva.pdf'
    const existingPdfBytes = await
 fetch(url_file).then(res => res.arrayBuffer())

    // Load a PDFDocument from the existing PDF bytes
    const pdfDoc = await PDFDocument.load(existingPdfBytes)

    // Get the first page of the document
    const pages = pdfDoc.getPages()
    const firstPage = pages[0]

    // Get the width and height of the first page
    const { width, height } = firstPage.getSize()

    // Create a new PDFDocument
    //const pdfDoc = await PDFDocument.create()

    // Register the `fontkit` instance
    pdfDoc.registerFontkit(fontkit)

    // Embed our custom font in the document
    const customFont = await pdfDoc.embedFont(fontBytes)

    // Add a blank page to the document
    //const page = pdfDoc.addPage()


// Create a string of text and measure its width and height in our custom font
    const text = nome+" "+cognome
    const textSize = 30
    const textWidth = customFont.widthOfTextAtSize(text, textSize)
    const textHeight = customFont.heightAtSize(textSize)

    // Draw the string of text on the page
    firstPage.drawText(text, {
      x: (width - textWidth) / 2,
      y: height / 2 - 60,
      size: textSize,
      font: customFont,
      color: rgb(0, 0, 0),
    })

    // Serialize the PDFDocument to bytes (a Uint8Array)
    const pdfBytes = await pdfDoc.save()

    download(pdfBytes, "pdf-lib_creation_example.pdf", "application/pdf");
// until here work all like a charm
/*
    Promise.all(pdfBytes).then((pdfBytes) => {

      // Here you could make a AJAX call to your PHP on your server
      $.ajax({
        url: "test.php",
        type: 'POST',

        data: {
          nome: nome,
          cognome: cognome,
          email: email,
          markupStr: markupStr,
          path: pdfBytes, // ?? i am stuck here
          processData: false
        },
        success: function (data) {
          console.log("success: " + JSON.stringify(data));
          if (data.success == "success") {
            alert(data.success);

            console.log("Success send");

          }
        }
      })

// sending the byte arrays with every page of the PDF Document on its own

      });
*/

    }

});
</script>

</html>

end ///
I don't know how to thank you enough



Il giorno dom 24 mag 2020 alle ore 15:37 Sebastian Martinez <
notifications@github.com> ha scritto:

**Comment by sebastinez** [comment]
@sundsx 

Your project sounds great, unfortunately I don't have lot of spare time on my hands at the moment, here some ideas that will eventually help you.

> But instead of saving the file via browser I would like to send it as an attachment.

As I understand you want to send an email, with the generated PDF as an attachment.

```js
path: pdfBytes, // ?? i am stuck here
```
I guess, from the property name here `path` you think `pdf-lib` generates you a path to a file.
`pdfBytes` is an array of bytes which consists of the content of your created file, which you can send to your PHP script on your server, but there you'll have to make use of PHP to attach this byteArray to an email for example with help of PHPMailer (https://github.com/PHPMailer/PHPMailer).

Hope you can make it work.

**Comment by sundsx** [comment]
Thank you a lot for your time!
Grazie!

Il giorno lun 25 mag 2020 alle 02:09 Sebastian Martinez <
notifications@github.com> ha scritto:

**Comment by sundsx** [comment]
Hi Sebastian, i want share with you my success!

after learn more about base64 encoding and a lot of headaches, i got it!

JS side:
const pdfBytes = await pdfDoc.save()

//console.log(pdfBytes);

'use strict';

function bufferToBase64(buf) {
    var binstr = Array.prototype.map.call(buf, function (ch) {
        return String.fromCharCode(ch);
    }).join('');
    return btoa(binstr);
}

//var arr = [73, 32, 194, 189, 32, 226, 153, 165, 32, 240, 159, 146, 169];
var data = new Uint8Array(pdfBytes);

var base64 = bufferToBase64(data);

console.log(base64);

var formData = new FormData();

formData.append("nome", nome);
formData.append("cognome", cognome);
// number 123456 is immediately converted to a string "123456"
formData.append("email", email);
formData.append("markupStr", markupStr);
formData.append("pdffile", base64);


var request = new XMLHttpRequest();
request.open("POST", "test.php");
request.send(formData);


PHP SIDE:

# Decode the Base64 string, making sure that it contains only valid characters
$bin = base64_decode($binarr, true);

# Perform a basic validation to make sure that the result is a valid PDF file
# Be aware! The magic number (file signature) is not 100% reliable
solution to validate PDF files
# Moreover, if you get Base64 from an untrusted source, you must
sanitize the PDF contents
if (strpos($bin, '%PDF') !== 0) {
  throw new Exception('Missing the PDF file signature');
}

# Write the PDF contents to a local file
file_put_contents($filePath, $bin);


SO TAHNK YOU FOR YOUR COOL FRAMEWORK!

Sundsx

Il giorno lun 25 mag 2020 alle ore 07:24 Sandro <sundsx@gmail.com> ha
scritto:

**Comment by Hopding** [comment]
Hello @sundsx!

Just wanted to note that the base64 encoding algorithm you shared is not robust. It may corrupt your documents. I would suggest using the [`PDFDocument.saveAsBase64`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#saveasbase64) method instead. This approach will successfully serialize any PDF document to a base64 string without risk of corruption.

So instead of this:
```js
const pdfBytes = await pdfDoc.save()

function bufferToBase64(buf) {
    var binstr = Array.prototype.map.call(buf, function (ch) {
        return String.fromCharCode(ch);
    }).join('');
    return btoa(binstr);
}

var data = new Uint8Array(pdfBytes);

var base64 = bufferToBase64(data);
```

You can simply do this:
```js
var base64 = await pdfDoc.saveAsBase64()
```

**Comment by sundsx** [comment]
Hi Sebastian, i feel stupid now: 3 days learning and test base64 encoding,
while you library already have a method for this purpose.

Your suggestion work very well!!!

I want to thank you both for your honorable help and for this wonderful
library that has allowed me to wipe out many and boring repetitive tasks in
one fell swoop.
So thank you

Il giorno sab 30 mag 2020 alle ore 19:20 Andrew Dillon <
notifications@github.com> ha scritto:
