### ISSUE TITLE
AcroField of Text type are getting misaligned and resized on click

### ISSUE THREAD

**Issue by sagartrehan** [Hopding/pdf-lib#459]
Hi Hopding,

Thanks for the awesome library.

I have used this library to fill a pdf template. I have downloaded and build the example of "mario character" pdf template. When I opened the filled pdf in the "adobe acrobat reader", the pdf text fields are getting "resized" and getting "autoaligned" to center of the text field.

1. I set the "Ff" field on acroField to "read-only | multiline" which fixed the issue of text is getting aligned to center on click. But there is a field with display text "Mario" which is still getting center aligned on click.

2. The font size of the text field is still getting resized on click. Please help me to fix this issue.

```
acroField.set('Ff', PDFNumber.fromNumber(
    1 << 0 // Read Only
    |
    1 << 12 // Multiline
  ));
```

Please let me know if this is not an issue and it is because of opening the filled pdf in "Adobe Acrobat Reader". 

Code link
[pdf-lib_form_fill_example_3.zip](https://github.com/Hopding/pdf-lib/files/3693350/pdf-lib_form_fill_example_3.zip)

Video Links
1. [Video of "Ff" field set to Read or Multiline Only](https://drive.google.com/file/d/1kt9Gf-p1fIADQJh56kOL_hIbtBmznUFi/view?usp=sharing)

2. [Video of "Ff" field set to Read Only](https://drive.google.com/file/d/1mRv090HXCDeU8FGFCYFqHP8saseWT1Uy/view?usp=sharing)

**Comment by sagartrehan** [comment]
Hi @Hopding 
please help me to fix this issue

**Comment by sagartrehan** [comment]
Hi @Hopding 
Is it mandatory to set the appearance while filling the form acrofields? If I don't set the appearance the data is not displaying until i clicked on the field. Is it possible that it auto takes the apperance of the acro field.

**Comment by Hopding** [comment]
Hello @sagartrehan! pdf-lib has a new form creation and filling API. Please give it a try and open a new issue if you're still having problems. See the README and API docs for details on the new API.
