### ISSUE TITLE
Issue embedding fonts

### ISSUE THREAD

**Issue by kevinswartz** [Hopding/pdf-lib#46]
Hi!
Your library is fantastic, thanks so much for your work here.  I'm having some kind of problem embedding fonts.  I'm using pdf-lib to write to files, and pdf.js to display them.  Here's my scenario.  I have a pdf that I've embedded a non standard font in, and written some text, I can view it in pdf.js without issue.  If I then write another string of text to it in a different font, either standard or non-standard, I get warnings from pdfjs about not being able to find the first font I embedded.

Here's an example error from pdf.js:

> Warning: fontRef not available
> Warning: Error during font loading: Font La Belle Aurore is not available

Here's some of my code I'm using to draw text in the pdf:
```
drawText: function(pageIndex, x, y, text, fontFamily, fontSize){
    var me = this;
  
    var pages = me.pdfDoc.getPages();
    var page  = pages[pageIndex];
  
    //https://github.com/Hopding/pdf-lib/issues/10#issuecomment-402326518
    var toWidth = page.get('MediaBox').array[2].number;
    var toHeight = page.get('MediaBox').array[3].number;
  
    var embeddedFont = null;
    if(me.isStandardFont(fontFamily)){
      embeddedFont = me.pdfDoc.embedStandardFont(fontFamily)[0];
    }
    else{
      embeddedFont = me.pdfDoc.embedFont(me.getFontData(fontFamily))[0];
    }
  
    fontSize = +fontSize.split('px')[0];
    
    page.addFontDictionary(fontFamily, embeddedFont);
    var contentStream = me.pdfDoc.createContentStream(
      window.PDFLib.drawText(text, {
        x: x,
        y: toHeight - y - fontSize,
        size: fontSize,
        font: fontFamily,
        colorRgb: [0,0,0],
      })
    );
  
    page.addContentStreams(me.pdfDoc.register(contentStream));
 }
```

It appears that if I re-embed the first non-standard font I used, things seem to work.  In order to view the changes I made, I call `PDFLib.PDFDocumentWriter.saveToBytes()`, process that into a base 64 string, and pass that into pdf.js.  It works except for this font issue.

I know that's complicated, and involves a library that isn't yours.  Does that make sense?  Do you have any ideas I could try?  Thanks for your help!

**Comment by Hopding** [comment]
Hello @kevinswartz. The scenario you are describing seems like it should work. If you can provide some additional information, I'd be happy to dig further into this.
* Can you please share the code/library/function you are using to perform the base64 encoding?
* Can you create and share a minimal example that I can use to reproduce the issue? Just an HTML file or Node JS script will do fine.

**Comment by Hopding** [comment]
@kevinswartz are you still having trouble with this?

**Comment by kevinswartz** [comment]
Yes, sorry for the slow response.  I'll get you some code to reproduce a little later this evening.  Thanks!

**Comment by kevinswartz** [comment]
Hi @Hopding,
Here's my method to get a base64 string for a document from pdf-lib:
```
getb64Doc: function(){
    var me = this;
  
    var uintArray = window.PDFLib.PDFDocumentWriter.saveToBytes(me.pdfDoc);
    var binary = '';
    var len = uintArray.byteLength;
    for (var i = 0; i < len; i++) {
      binary += String.fromCharCode(uintArray[i]);
    }
    var str = window.btoa(binary);
    return "data:application/pdf;base64," + str;
  },
```

I take output from that function, and directly input into this one to render the updated pdf:

```
buildPdfDocument: function(uri){
    var me = this;
    
    var pdfjsLib = window['pdfjs-dist/build/pdf'];
    pdfjsLib.GlobalWorkerOptions.workerSrc = '/node_modules/pdfjs-dist/build/pdf.worker.js';
    pdfjsLib.getDocument({
        url: uri,
        cMapUrl: "/node_modules/pdfjs-dist/cmaps/",
        cMapPacked: true,
      })
      .then(function(pdf) {
        me.pdfObj = pdf;
        me.currentPage = 0;
        me.scale = 1;
        
        var pages = [];
        var pageFinishedCount = 0;
        for(var num = 1; num <= me.pdfObj.numPages; num++) {
          pages.push({})
          me.pdfObj.getPage(num)
            .then(function(page){
              pages[page.pageIndex] = page;
              pageFinishedCount++;
              
              if(pageFinishedCount === me.pdfObj.numPages){
                me.pages = pages;
                me.doneLoading();
              }
            });
        }
      }, function(err){
        me.handleNoPreview();
      })
  },
```

Does that get you close enough?  My project is built with an older version of ExtJS, and it would take a while to break out my font and pdf loading into an easy example.

**Comment by Hopding** [comment]
@kevinswartz Thanks for the code snippets!

I suspect your problem is coming from your `UintArray -> Base64String` conversion. Unfortunately, JavaScript makes it easy to do base64 encoding/decoding incorrectly (see https://github.com/Hopding/pdf-lib/issues/34#issuecomment-428765074). There's a great NPM package called [`base64-arraybuffer`](https://github.com/niklasvh/base64-arraybuffer) that I recommend you take a look at. It has a function that encodes `Uint8Arrays` to base64 strings. If you aren't using a package manager, you can just copy the `encode` function from [here](https://github.com/niklasvh/base64-arraybuffer/blob/e9457ccb7b140f5ae54a2880c8e9b967ffb03a7d/lib/base64-arraybuffer.js#L19-L37).

**However**, if the only reason you are doing the base64 encoding is to feed `pdf-lib` into `pdf.js`, I think that you're incurring unnecessary time/space overhead. The docs for `pdf.js` indicate that [it accepts `TypedArrays` as input to `getDocument`](https://mozilla.github.io/pdf.js/api/draft/global.html#getDocument). So you should be able to do something like this:
```js
 pdfjsLib.getDocument({
        data: window.PDFLib.PDFDocumentWriter.saveToBytes(me.pdfDoc),
        cMapUrl: "/node_modules/pdfjs-dist/cmaps/",
        cMapPacked: true,
      })
      .then(function(pdf) {
        ...
      })
```

Let me know if this helps, or if you're still stuck after trying these approaches.

**Comment by kevinswartz** [comment]
Hi Anthony,
So you fixed my issue by skipping the step of encoding to base64, and passing the raw bytes directly into the data param of pdfjsLib.getDocument().  Thanks so much for the help!  You're doing some great work here.
