### ISSUE TITLE
Check PDF pages for equality

### ISSUE THREAD

**Issue by abielg** [Hopding/pdf-lib#462]
I have a set of PDF documents of varying page length. When iterated over in order, there's occasionally a duplicated page -- namely the last page of the preceding document being the same as the first page of the next document.

I want to merge all PDF documents into a single one, and doing so correctly would mean removing the duplicate pages -- so I first need to identify them.

I got close to achieving this by copying the pages I wanted to compare each to a separate new PDFDocument object, serializing both documents via the `save` function, and comparing the stringified bytes.

However, this only worked if both pages were the first ones in their respective documents (i.e. document #3 is a single page in length, document #4 is two pages in length, and the first pages of each were equal). If the preceding document (document #3 in this example) is two pages in length, and I take the second page and copy it into its own PDFDocument, then the above comparison stops working.

Is there a better way to achieve this?

**Comment by Hopding** [comment]
Hello @abielg!

Apologies for the late response. There are a number of "hacky" you could try to compare pages in a document. But the best way to do what you're attempting is probably to compare the actual contents of the pages (text, images, etc...). You might be able to do this with pdf-lib by decoding the page's content streams and comparing them. See https://github.com/Hopding/pdf-lib/issues/446#issuecomment-629561090 and https://github.com/Hopding/pdf-lib/issues/296#issuecomment-570053040 for some examples of how to access and decode content streams.

Another approach you could try is using [Mozilla's `pdf.js`](https://mozilla.github.io/pdf.js/) library to extract the actual text and images on the pages in question. You could them compare the text/images on the pages to see if they match.
