### ISSUE TITLE
Is it possible to get a list of fonts that the PDF users and check if they are embedded?

### ISSUE THREAD

**Issue by Friesens-JeffreyR** [Hopding/pdf-lib#463]
I'm looking for a way to programmatically check all the fonts in a PDF and see if they are embedded or not. Is this possible?
![image](https://user-images.githubusercontent.com/1532789/83063231-6e1f4a80-a025-11ea-8e85-e04e488a1c25.png)

**Comment by ElePhontitis** [comment]
Would like to know that too!

**Comment by Hopding** [comment]
Hello @Friesens-JeffreyR!

This is certainly possible to do. However, pdf-lib does not have a high-level API for this, so you'll have to use the low-level APIs directly. There's a few ways you could do this. Below is a quick example that shows the key parts of what would be necessary:

```js
import { PDFDocument, PDFDict, PDFName } from 'pdf-lib';

(async () => {
  const url = 'https://pdf-lib.js.org/assets/normal.pdf';
  const normalPdfBytes = await fetch(url).then((res) => res.arrayBuffer());

  const pdfDoc = await PDFDocument.load(normalPdfBytes);

  const pages = pdfDoc.getPages();
  pages.forEach((page) => {
    const { Font } = page.node.normalizedEntries();
    Font.entries().forEach(([fontName, fontRef]) => {
      const fontDict = pdfDoc.context.lookupMaybe(fontRef, PDFDict);
      if (fontDict) {
        console.log('Font name:', fontName.decodeText());
        console.log();

        console.log(fontDict.toString());
        console.log();

        const descriptor = fontDict.lookup(
          PDFName.of('FontDescriptor'),
          PDFDict,
        );
        console.log(descriptor.toString());
        console.log();

        const isEmbedded =
          descriptor.has(PDFName.of('FontFile')) ||
          descriptor.has(PDFName.of('FontFile2')) ||
          descriptor.has(PDFName.of('FontFile3'));

        console.log('Is embedded?', isEmbedded);
        console.log('----------------');
      }
    });
  });
})();
```

Partial output:
```
Font name: Tc1

<<
/Type /Font
/Subtype /Type1
/BaseFont /FHPAOR+NewsGothicBT-Bold
/FontDescriptor 75 0 R
/Encoding /MacRomanEncoding
/FirstChar 48
/LastChar 50
/Widths [ 606 606 606 ]
>>

<<
/Type /FontDescriptor
/FontName /FHPAOR+NewsGothicBT-Bold
/Flags 32
/FontBBox [ -198 -268 1324 996 ]
/ItalicAngle 0
/Ascent 965
/Descent -237
/CapHeight 857
/StemV 123
/XHeight 643
/StemH 106
/AvgWidth 606
/MaxWidth 1522
/FontFile3 76 0 R
>>

Is embedded? true
----------------
...
----------------
Font name: TT7

<<
/Type /Font
/Subtype /TrueType
/BaseFont /OFBPZU+FranklinGothic-Heavy
/FontDescriptor 107 0 R
/ToUnicode 108 0 R
/FirstChar 33
/LastChar 79
/Widths [ 583 530 372 297 855 586 586 587 250 470 553 643 587 294 512 900 591 586 392 594 381 585 523 546 638 681 743 321 650 587 506 628 569 539 586 586 586 586 586 586 471 275 586 586 586 586 679 ]
>>

<<
/Type /FontDescriptor
/FontName /OFBPZU+FranklinGothic-Heavy
/Flags 4
/FontBBox [ -249 -307 1146 983 ]
/ItalicAngle 0
/Ascent 917
/Descent -217
/CapHeight 677
/StemV 0
/XHeight 507
/AvgWidth 473
/MaxWidth 1162
/FontFile2 110 0 R
>>

Is embedded? true
----------------
```

Please see section **9.5 Introduction to Font Data Structures** of the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) for details about fonts and embedded fonts.

I hope this helps! Please let me know if you have any additional questions.

**Comment by niklas-dahl** [comment]
@Hopding 
This works great, is it possible to get a PDFFont Object to these fonts in order to use them im `drawText`.
I want to use `drawText` using the already existing embeded fonts.
Thanks.

**Comment by jkoutavas** [comment]
> @Hopding
> This works great, is it possible to get a PDFFont Object to these fonts in order to use them im `drawText`.
> I want to use `drawText` using the already existing embeded fonts.
> Thanks.

@Hopding did you ever figure this out?

**Comment by garmoshka-mo** [comment]
Reusing fonts in PDFs is mostly not possible since only the characters that are used in the PDF are stored. So if you never used an uppercase W in your PDF template and want to add text with one, then it cannot be displayed.

So I embedded fonts from files:
```
    import fontkit from '@pdf-lib/fontkit';
    
    pdfDoc.registerFontkit(fontkit);
    const fontBytes = fs.readFileSync('arial_bold.ttf')
    const customFont = await pdfDoc.embedFont(fontBytes)
```

**Comment by dcbr** [comment]
If the font was previously embedded using pdf-lib, e.g. using
```js
const fontBytes = fs.readFileSync("Courier.ttf");
pdfDoc.registerFontkit(fontkit);
const font = await pdfDoc.embedFont(fontBytes);
console.log(font.ref);// Save this reference such that it can be reused later
// Use font to draw some text
```
I found that following "hack" worked to reuse these embedded fonts (and prevent them from being embedded again):
```js
import { PDFArray, PDFDict, PDFDocument, PDFFont, PDFName, PDFRawStream, PDFRef, CustomFontEmbedder, decodePDFRawStream } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';

const fontRef = PDFRef.of(R);// Use the saved reference number (R) from above
// First retrieve and decode the embedded font bytes. These are located in FontDict[DescendantFonts][0][FontDescriptor][FontFile2].
const fontDict = doc.context.lookup(fontRef, PDFDict);
const fontCID = doc.context.lookup((fontDict.get(PDFName.of('DescendantFonts')) as PDFArray).get(0) as PDFRef, PDFDict);
const fontDescr = doc.context.lookup(fontCID.get(PDFName.of('FontDescriptor')) as PDFRef, PDFDict);
const fontFileStream = doc.context.lookup(fontDescr.get(PDFName.of('FontFile2')) as PDFRef) as PDFRawStream;
const fontBytes = decodePDFRawStream(fontFileStream).decode();
// Now create a PDFFont object directly from the font bytes, such that it is not reembedded.
const embedder = await CustomFontEmbedder.for(fontkit, fontBytes);
const font = PDFFont.of(fontRef, doc, embedder);
// Use font to draw some text
```

**Comment by vijayrajesh** [comment]
> Reusing fonts in PDFs is mostly not possible since only the characters that are used in the PDF are stored. So if you never used an uppercase W in your PDF template and want to add text with one, then it cannot be displayed.
> 
> So I embedded fonts from files:
> 
> ```
>     import fontkit from '@pdf-lib/fontkit';
>     
>     pdfDoc.registerFontkit(fontkit);
>     const fontBytes = fs.readFileSync('arial_bold.ttf')
>     const customFont = await pdfDoc.embedFont(fontBytes)
> ```

I understand, but suppose, if I want to use numbers only which are already embedded 0 to 9, can i use it?
