### ISSUE TITLE
Changing page labels (changing page numbers in PDF)

### ISSUE THREAD

**Issue by leverarch-app** [Hopding/pdf-lib#464]
Thanks once again for this fantastic library.

In my use case, I am merging together lots of different PDF files and creating an index for them on the fly.

The index refers to each file with page numbers accordingly.

Many users have asked that the “official page numbering” (i.e. the page number it says in the UI of your PDF Reader) starts at 1 on the first document, not the index.

So the merged PDF looks like this:

- Page i = index
- Page 1 = first page of first doc
- Page 2 = second page of first doc etc.

Is that possible with this library?

Thanks

Jack

**Comment by Hopding** [comment]
Hello @leverarch-app!

Are you asking if `pdf-lib` can change the page count numbering (as shown below)?

![Screen Shot 2020-05-30 at 12 09 46 PM](https://user-images.githubusercontent.com/10351828/83334808-a4033f80-a26e-11ea-99e6-1dfd7db976f1.png)

AFAIK this is not possible to do with any PDF library. The only way to impact this numbering is by rearranging (or adding/removing) pages. PDF readers simply show which page number you are viewing. It's pretty common for this to not match up with the page numbering shown on the pages themselves.

I hope this helps. Please let me know if you have any additional questions!

**Comment by Mogztter** [comment]
Hello @Hopding 

I have a similar question.
In my case, I have a PDF with basic numbering (i.e. first page is 1, second page is 2, etc...) but I want to use roman numerals (iv, xi) on all front matter pages starting from "i" on the first page.

Basically, I'm loading this PDF:

![84009065-047f3480-a973-11ea-916d-cfdbf8df1298](https://user-images.githubusercontent.com/333276/84589309-e3fd2180-ae2d-11ea-8897-966f7a8aa340.png)

And I want to update the page labels as follow:

![84009067-0517cb00-a973-11ea-9c9d-9b584ba221e5](https://user-images.githubusercontent.com/333276/84589313-ee1f2000-ae2d-11ea-9e81-fb2f9202156c.png)


Apparently it's possible using `/PageLabels` entry, as described in: https://www.w3.org/TR/WCAG20-TECHS/PDF17.html#PDF17-ex2

> Are you asking if pdf-lib can change the page count numbering (as shown below)?

I believe that the page count numbering should remain the same (I don't add or remove pages, I just change the labels)

Let me know if I need create a new issue, the title of this issue "Changing page labels (changing page numbers in PDF)" is exactly what I change to do.

**Comment by Hopding** [comment]
@Mogztter @leverarch-app 

Thanks for the tip @Mogztter, I wasn't aware of that feature of the spec! Here's an example of how to change the page labels with `pdf-lib`:

```js
import { PDFDocument, PDFName, PDFHexString } from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();

  pdfDoc.addPage().drawText('Page 0');
  pdfDoc.addPage().drawText('Page 1');
  pdfDoc.addPage().drawText('Page 2');
  pdfDoc.addPage().drawText('Page 3');
  pdfDoc.addPage().drawText('Page 4');
  pdfDoc.addPage().drawText('Page 5');
  pdfDoc.addPage().drawText('Page 6');
  pdfDoc.addPage().drawText('Page 7');
  pdfDoc.addPage().drawText('Page 8');

  const pageLabels = pdfDoc.context.obj({
    Nums: [
      0, { S: 'r' },
      4, { S: 'D' },
      7, { S: 'D', P: PDFHexString.fromText('A-'), St: 8 },
    ]
  });

  pdfDoc.catalog.set(PDFName.of('PageLabels'), pageLabels);

  const pdfBytes = await pdfDoc.save();
})();
```

This will produce a document containing 9 pages with the following labels:
```
i, ii, iii, iv, 1, 2, 3, A-8, A-9
```

You can check out [the example](https://www.w3.org/TR/WCAG20-TECHS/PDF17.html#PDF17-ex2) provided by @Mogztter and/or read section **12.4.2 Page Labels** of the [PDF specification](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) for details on how the page labels dictionary works and what the rather cryptic entries in my example mean.

If either of you guys are interested in writing up a PR, I'd love to see pdf-lib have a proper API for setting (and reading) PDF page labels!

**Comment by Mogztter** [comment]
Awesome!
I wasn't sure it was possible without a specific API.

Thanks for the detailed example I will give it a try. I might have time to work on a pull request 😀
