### ISSUE TITLE
How to update meta data of a PDF added via html input

### ISSUE THREAD

**Issue by dubeyabhishek36** [Hopding/pdf-lib#465]
Hi @Hopding,

I am trying to update meta data (only title and author) of PDF which the user selects via html input.
Steps which I want to happen:
1. Browse file using html input (Please note: I am not uploading them anywhere, everything will be on local machine)
<input type="file" id="pdf-file" name="pdf" accept="application/pdf" />

2. Read the meta data into text inputs (which I am able to do so currently)
<input type="text" id="title-of-pdf" placeholder="title">
<input type="text" id="author-of-pdf" placeholder="Author">

3. Update the title and author in the input and hit modify button to save and download the updated file
```js
  <button id="update-meta">Modify</button>

  $("#update-meta").on("click", function(e){
    editDocumentMetadata();
  })


async function editDocumentMetadata(pdf) {
 var titleInput  = document.getElementById("title-of-pdf");
var authorInput  = document.getElementById("author-of-pdf");

const url = $('#pdf-file').val();
const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())
const pdfDoc = await PDFDocument.load(existingPdfBytes, { 
updateMetadata: false 
})
pdfDoc.setTitle(titleInput.value)
pdfDoc.setAuthor(authorInput.value)
const pdfBytes = await pdfDoc.saveAsBase64({ dataUri: true });
 download(pdfBytes, "binder.pdf", "application/pdf");
}
```

But the above function show me error "URL scheme "file" is not supported" 
Please help!!

Regards,
Abhishek

**Comment by Hopding** [comment]
Hello @dubeyabhishek36!

From what you've shared, it looks to me like your probably passing a URL to `fetch` with the `file` protocol, meaning it begins with the string `file://`. If so, that would explain the error you're encountering. AFAIK, `fetch` only supports HTTP(S) URLs. What you need to do is read in the file's contents as an `ArrayBuffer` or `Uint8Array`. Instead of using `fetch`, you might try a `FileReader`. See this article for some examples: https://web.dev/read-files/#read-content.

I hope this helps. Let me know if you have any additional questions!

**Comment by dubeyabhishek36** [comment]
Hello @Hopding ,

Thanks for the response but I am new to coding and I am stuck here from last 3 days. I have also looked at the reference you provided but that I have checked earlier this day and that also didn't helped that much.
Till now I am only able to achieve the below code, can you please him me in this.
<section id="merger-editor">
        Files: <input type="file" id="files" name="files" multiple><br/>
        <div id="selectedFiles"></div>
    <div class="mergepdf-button-wrapper">
  <button id="mergepdf-button">Modify</button>
    </div>
</section>

//Script starts here
var filesarray;
  var selDiv = "";
  var uint8Array;
   var arrayOfArrayBuffer = [];

  document.addEventListener("DOMContentLoaded", init, false);
  function init() {
    document.querySelector('#files').addEventListener('change', handleFileSelect, false);
    selDiv = document.querySelector("#selectedFiles");
  }
  function handleFileSelect(e) {
    if(!e.target.files) return;
    selDiv.innerHTML = "";
    var files = e.target.files;
   filesarray = new Array(files);
console.log("filesarray" + files);
    for(var i=0; i<files.length; i++) {
      var f = files[i];
      selDiv.innerHTML += f.name + "<br/>";
     uint8Array = new TextEncoder("utf-8").encode(files[i]);
     arrayOfArrayBuffer.push(uint8Array);
    }
  }

////Click action to merge the fetched files
  $("#mergepdf-button").on("click", function(e){
   mergePdfs(arrayOfArrayBuffer);
  })

////Function to merge
async function mergePdfs(pdfsToMerge) {
  const mergedPdf = await PDFDocument.create();
  for (const pdfCopyDoc of pdfsToMerge) {   

//I am stuck here now since I am not using node.j its just plain vanilla js I am not able to call the fileSystem and read the files.. The section below this doesnt work at all.
 
    const pdfBytes = fs.readFileSync(pdfCopyDoc);
    const pdf = await PDFDocument.load(pdfBytes);
    const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
  copiedPages.forEach((page) => {
    mergedPdf.addPage(page);
    });
  }
  const mergedPdfFile = await mergedPdf.save();
  download(mergedPdfFile, "mergedFile.pdf", "application/pdf");
}

Regards,
Abhishek

**Comment by jamols09** [comment]
`fs.readFileSync` will not work on client side (frontend frameworks). This will most likely work on javascript server side such as ExpressJs, etc..

**Comment by iamshulz** [comment]
> Hello @Hopding ,
> 
> Thanks for the response but I am new to coding and I am stuck here from last 3 days. I have also looked at the reference you provided but that I have checked earlier this day and that also didn't helped that much. Till now I am only able to achieve the below code, can you please him me in this.
> 
> Files:
> Modify
> //Script starts here var filesarray; var selDiv = ""; var uint8Array; var arrayOfArrayBuffer = [];
> 
> document.addEventListener("DOMContentLoaded", init, false); function init() { document.querySelector('#files').addEventListener('change', handleFileSelect, false); selDiv = document.querySelector("#selectedFiles"); } function handleFileSelect(e) { if(!e.target.files) return; selDiv.innerHTML = ""; var files = e.target.files; filesarray = new Array(files); console.log("filesarray" + files); for(var i=0; i<files.length; i++) { var f = files[i]; selDiv.innerHTML += f.name + ""; uint8Array = new TextEncoder("utf-8").encode(files[i]); arrayOfArrayBuffer.push(uint8Array); } }
> 
> ////Click action to merge the fetched files $("#mergepdf-button").on("click", function(e){ mergePdfs(arrayOfArrayBuffer); })
> 
> ////Function to merge async function mergePdfs(pdfsToMerge) { const mergedPdf = await PDFDocument.create(); for (const pdfCopyDoc of pdfsToMerge) {
> 
> //I am stuck here now since I am not using node.j its just plain vanilla js I am not able to call the fileSystem and read the files.. The section below this doesnt work at all.
> 
> ```
> const pdfBytes = fs.readFileSync(pdfCopyDoc);
> const pdf = await PDFDocument.load(pdfBytes);
> const copiedPages = await mergedPdf.copyPages(pdf, pdf.getPageIndices());
> ```
> 
> copiedPages.forEach((page) => { mergedPdf.addPage(page); }); } const mergedPdfFile = await mergedPdf.save(); download(mergedPdfFile, "mergedFile.pdf", "application/pdf"); }
> 
> Regards, Abhishek

`fs.readFileSync()` will not work on client side (frontend frameworks). This will most likely work on javascript server side such as ExpressJs, etc..
