### ISSUE TITLE
Copying a page

### ISSUE THREAD

**Issue by mikeciz** [Hopding/pdf-lib#47]
This library is fantastic and easy to work with, however, I've run into a snag.
I am loading an existing 1 page PDF and would like to duplicate the first page multiple times before I start adding text and images.

I can get a reference to the first page and then use:
this.pdfDoc.addPage(this.pages[0]);
or even
this.pdfDoc.insertPage(1, this.pages[0]);

This will successfully copy the page, however, when I then add the content stream to page 0,
this.pages[0].addContentStreams...etc.
...it also adds the identical content stream to the second page.   It seems like my pages are the same instance of the page. How can I modify these pages separately?

Thanks again for the amazing library!
-mike

**Comment by Hopding** [comment]
Hello @mikeciz. 

What you are seeing sounds about right, since you are inserting the same `PDFPage` object into a different location of the document. What you're looking to do is first copy the `PDFPage` and then insert the copy as a second page. 

This can be done by writing a `copyPage` function. No such function currently exists in `pdf-lib` (though I'll think about adding one in a future release). But here's a working implementation that you can copy into your project:
```js
import {
  PDFArray,
  PDFDictionary,
  PDFDocument,
  PDFDocumentFactory,
  PDFDocumentWriter,
  PDFPage,
} from 'pdf-lib';

/* Copies a PDFPage object */
const copyPage = (originalPage) => {
  const originalContents = originalPage.Contents;
  const copiedContents = PDFArray.fromArray(
    originalContents.array.slice(),
    originalPage.index
  );

  const copiedPage = PDFPage.fromDict(
    PDFDictionary.from(new Map(originalPage.map), originalPage.index),
  );
  copiedPage.set('Contents', copiedContents);

  return copiedPage;
};

const pdfBytes = /* Uint8Array containing existing PDF */
const pdfDoc = PDFDocumentFactory.load(pdfBytes);

const pages = pdfDoc.getPages();

const firstPage = pages[0];
const secondPage = copyPage(firstPage);

pdfDoc.insertPage(1, secondPage);

/* Modify the first page without changing the second page */
firstPage
  .addFontDictionary(/* ... */)
  .addXObject(/* ... */)
  .addContentStreams(/* ... */);

const modifiedPdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
```

Please let me know if this works for you.

**Comment by mikeciz** [comment]
That worked PERFECTLY! Thanks so much.  The only change I needed to make was to add a check for original contents since my existing PDF page didn't have any content

```javascript
let copiedContents: PDFArray;
const copiedPage = PDFPage.fromDict(PDFDictionary.from(new Map(originalPage.map), originalPage.index));
// An existing PDF may not have any original content
if (originalContents.array){
     copiedContents = PDFArray.fromArray(originalContents.array.slice(), originalPage.index);
     copiedPage.set('Contents', copiedContents);
}
```

**Comment by Hopding** [comment]
@mikeciz Glad to hear it's working!

You're correct about the `Content` entry being optional for pages. It can actually be three different types (the PDF specification is awful like that 😉):
* `undefined`
* `PDFIndirectReference<PDFStream>`
* `PDFArray<PDFIndirectReference<PDFStream>>`

I hadn't really considered the first and second cases in the `copyPage` function I initially wrote. Your changes are an improvement, but I can't quite tell if it handles all three cases safely with the snippet you provided. Here's an amended version of my original `copyPage` function that should safely handle all possible scenarios:
```js
/* Copies a PDFPage object */
const copyPage = (originalPage) => {
  const copiedPage = PDFPage.fromDict(
    PDFDictionary.from(new Map(originalPage.map), originalPage.index),
  );

  if (originalPage.getMaybe('Contents')) {
    originalPage.normalizeContents();
    const originalContents = originalPage.Contents;
    const copiedContents = PDFArray.fromArray(
      originalContents.array.slice(),
      originalPage.index
    );
    copiedPage.set('Contents', copiedContents);
  }

  return copiedPage;
};
```
(Note that is uses the [`PDFPage.normalizeContents()`](https://github.com/Hopding/pdf-lib/blob/2a1d00061c25ce952f609e7dac2f72a080d18b2a/src/core/pdf-structures/PDFPage.ts#L111-L122) method to coerce the `Contents` into an array if it isn't `undefined`).

Please let me know if this works for you. If so, I'll update my original comment for future users that might come across this thread.

**Comment by mikeciz** [comment]
Yes, that worked perfectly! Thanks again so much for all your help!

**Comment by Hopding** [comment]
@thebenlamm Here's an updated example for version `1.3.0`:
```js
import { PDFDocument, PDFName, PDFPage, rgb } from 'pdf-lib';

/* Copies a PDFPage object */
const copyPage = (originalPage) => {
  const cloneNode = originalPage.node.clone();

  const { Contents } = originalPage.node.normalizedEntries();
  if (Contents) cloneNode.set(PDFName.of('Contents'), Contents.clone());

  const cloneRef = originalPage.doc.context.register(cloneNode);
  const clonePage = PDFPage.of(cloneNode, cloneRef, originalPage.doc);
  return clonePage;
};

(async () => {
  const donorBytes = await fetch(
    'https://github.com/Hopding/pdf-lib/raw/master/assets/pdfs/normal.pdf',
  ).then((res) => res.arrayBuffer());

  const pdfDoc = await PDFDocument.create();
  const donorDoc = await PDFDocument.load(donorBytes);

  const [page1] = await pdfDoc.copyPages(donorDoc, [0]);

  const page2 = copyPage(page1);
  const page3 = copyPage(page1);

  pdfDoc.addPage(page1);
  pdfDoc.addPage(page2);
  pdfDoc.addPage(page3);

  const { width, height } = page1.getSize();
  const options = {
    size: 50,
    x: width / 2 - 70,
    y: height / 2,
    color: rgb(1, 0, 0),
  };

  page1.drawText('Page 1', options);
  page2.drawText('Page 2', options);
  page3.drawText('Page 3', options);

  const pdfBytes = await pdfDoc.save();
})();
```

And here's the resulting file: [out.pdf](https://github.com/Hopding/pdf-lib/files/4005914/out.pdf)

**Comment by AhmadrezaHK** [comment]
Thank you for the example. I just want to add `Annots.clone()` to the `copyPage` function. In my case, I want to copy a single page with PDF forms multiple times. Without `Annots.clone()`, adding a form field to one page will cause a change to other copied pages. So, here is the updated copyPage function:

```
/* Copies a PDFPage object */
const copyPage = (originalPage) => {
  const cloneNode = originalPage.node.clone();

  const { Contents, Annots } = originalPage.node.normalizedEntries();
  if (Contents) cloneNode.set(PDFName.of("Contents"), Contents.clone());
  if (Annots) cloneNode.set(PDFName.of("Annots"), Annots.clone());

  const cloneRef = originalPage.doc.context.register(cloneNode);
  const clonePage = PDFPage.of(cloneNode, cloneRef, originalPage.doc);
  return clonePage;
};
```

**Comment by AhmadrezaHK** [comment]
and if you want just to copy the page without it's Annots that would like this:

```
/* Copies a PDFPage object */
const copyPage = (originalPage) => {
  const cloneNode = originalPage.node.clone();

  const { Contents, Annots } = originalPage.node.normalizedEntries();
  if (Contents) cloneNode.set(PDFName.of("Contents"), Contents.clone());
  cloneNode.set(PDFName.of("Annots"), originalPage.node.context.obj([]));

  const cloneRef = originalPage.doc.context.register(cloneNode);
  const clonePage = PDFPage.of(cloneNode, cloneRef, originalPage.doc);
  return clonePage;
};
```
