### ISSUE TITLE
Keep only the upper half of a page

### ISSUE THREAD

**Issue by josephernest** [Hopding/pdf-lib#471]
I use this to crop the page in order to **keep the upper half** of a (portrait) page:

```
var H = p1.getHeight(); 
var W = p1.getWidth();
p1.translateContent(0, -Math.floor(H/2));
p1.setSize(W, H/2);
```

**It works most of the time, but in some rare cases it does not: it keeps the lower half of the page (!).** (probably because of a layer not being translated and staying on top?)

**What's the cleanest way to crop a page with pdf-lib.js?**

I hesitated to use setMediaBox, setArtBox, etc. because I did not know which one to choose, so many possibilities...

**Comment by Hopding** [comment]
Hello @josephernest! 

Apologies for the late response. This is an interesting issue. It may have to do with the pages you are cropping being rotated. Though I can't say for sure without reproducing the issue myself. Can you share some code and a document that I can use to reproduce this issue?

**Comment by Hopding** [comment]
I'm going to close this issue for now. Please feel free to reopen it with some additional info if you're still having trouble.
