### ISSUE TITLE
[Feature Request] Set document permissions

### ISSUE THREAD

**Issue by sundsx** [Hopding/pdf-lib#472]
It would be very useful to set permission for example only print.
Thank you awesome pdf-lib

**Comment by wesleimarinho** [comment]
It should be nice to have this feature.

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by choff5507** [comment]
Curious if there is any update on this feature?

**Comment by aashishvanand** [comment]
Do you happen to have any updates on the set permission?
