### ISSUE TITLE
how to generate a valid AppearanceStream of text annotation

### ISSUE THREAD

**Issue by Leed-Y** [Hopding/pdf-lib#475]
@Hopding Nick work! 
I would like to add text annotations to existing pdf files and customize text annotation appearance stream, but cannot generate a valid AppearanceStream, and the resulting file cannot display the image content.
Here is my code:
pdf-lib version: 1.7.0
```JavaScript
import {
        PDFDocument,
        PDFName,
        PDFArray,
        PDFString,
        PDFRawStream,
    } from 'pdf-lib';

const imageAppearanceStream = (
        image,
        rotation,
        width,
        height,
        uint8Array,
    ) => {
    const dict = image.doc.context.obj({
            Type: 'XObject',
            Subtype: 'Form',
            FormType: 1,
            BBox: [0, 0, width, height],
            Resources: {XObject: {Image: image.ref}, FRM: 'FRM'},
     });
     const stream = PDFRawStream.of(dict, uint8Array);
     return image.doc.context.register(stream);
};

async downloadPdf() {
    const arrayBuffer = await fetch(this.pdfDataUri).then(res => res.arrayBuffer());
    const pdfDoc = await PDFDocument.load(arrayBuffer);
    const page = pdfDoc.getPage(0);
    const imageBytes = await fetch(this.svgUrl).then((res) => res.arrayBuffer());
    const uint8Array = new Uint8Array(imageBytes, 0, imageBytes.byteLength);
    const image = await pdfDoc.embedPng(imageBytes);
    const imageAppearanceStreamRef = imageAppearanceStream(
                    image,
                    0,
                    image.width,
                    image.height,
                    uint8Array
     );
     const noteAnnotation = pdfDoc.context.obj({
                    Type: 'Annot',
                    Subtype: 'Text',
                    Rect: [100, page.getHeight() / 2, 400, 400],
                    Contents: 'this is text annot!',
                    Name: PDFString.of('Help'),
                    AP: pdfDoc.context.obj({N: imageAppearanceStreamRef})
      });
      const annots = page.node.lookup(PDFName.of('Annots'), PDFArray);
      annots.push(noteAnnotation);
      const linkSource = await pdfDoc.saveAsBase64({dataUri: true});
      const downloadLink = document.createElement("a");
      const fileName = "output.pdf";
      downloadLink.href = linkSource;
      downloadLink.download = fileName;
      downloadLink.click();
};
downloadPdf();
```
Any suggestions？

**Comment by Hopding** [comment]
Hello @Leed-Y!

Your content stream doesn't look like it'll work to me. I don't see any graphics operators in it. I would also expect to see some text drawing operators and an embedded font. I don't have time right now to create a working example for you, but if you're still working on this, I'd recommend the following:
1. Take a look at the recent forms PR: https://github.com/Hopding/pdf-lib/pull/599. It has a lot of code for generating appearance streams. At lot of it will not be necessary for your simple use case. But it should help you understand what is required to produce them.
2. Look through sections **8.10 FormXObjects**, **12.5.5 Appearance Streams**, and **12.5.6.4 Text Annotations** of the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf). 
3. Review some of the many issues this repo has about generating appearance streams. There's lots of working example code to be found (though it will need to be adapted for text annotations).

Best of luck!

**Comment by awaismehmood88** [comment]
> @Hopding Nick work!
> I would like to add text annotations to existing pdf files and customize text annotation appearance stream, but cannot generate a valid AppearanceStream, and the resulting file cannot display the image content.
> Here is my code:
> pdf-lib version: 1.7.0
> 
> ```js
> import {
>         PDFDocument,
>         PDFName,
>         PDFArray,
>         PDFString,
>         PDFRawStream,
>     } from 'pdf-lib';
> 
> const imageAppearanceStream = (
>         image,
>         rotation,
>         width,
>         height,
>         uint8Array,
>     ) => {
>     const dict = image.doc.context.obj({
>             Type: 'XObject',
>             Subtype: 'Form',
>             FormType: 1,
>             BBox: [0, 0, width, height],
>             Resources: {XObject: {Image: image.ref}, FRM: 'FRM'},
>      });
>      const stream = PDFRawStream.of(dict, uint8Array);
>      return image.doc.context.register(stream);
> };
> 
> async downloadPdf() {
>     const arrayBuffer = await fetch(this.pdfDataUri).then(res => res.arrayBuffer());
>     const pdfDoc = await PDFDocument.load(arrayBuffer);
>     const page = pdfDoc.getPage(0);
>     const imageBytes = await fetch(this.svgUrl).then((res) => res.arrayBuffer());
>     const uint8Array = new Uint8Array(imageBytes, 0, imageBytes.byteLength);
>     const image = await pdfDoc.embedPng(imageBytes);
>     const imageAppearanceStreamRef = imageAppearanceStream(
>                     image,
>                     0,
>                     image.width,
>                     image.height,
>                     uint8Array
>      );
>      const noteAnnotation = pdfDoc.context.obj({
>                     Type: 'Annot',
>                     Subtype: 'Text',
>                     Rect: [100, page.getHeight() / 2, 400, 400],
>                     Contents: 'this is text annot!',
>                     Name: PDFString.of('Help'),
>                     AP: pdfDoc.context.obj({N: imageAppearanceStreamRef})
>       });
>       const annots = page.node.lookup(PDFName.of('Annots'), PDFArray);
>       annots.push(noteAnnotation);
>       const linkSource = await pdfDoc.saveAsBase64({dataUri: true});
>       const downloadLink = document.createElement("a");
>       const fileName = "output.pdf";
>       downloadLink.href = linkSource;
>       downloadLink.download = fileName;
>       downloadLink.click();
> };
> downloadPdf();
> ```
> 
> Any suggestions？

DO THIS.  fetch all annotation from page using and push your annotation in it then set all annotations.
1. fetch all annotations > const annots = page.node.Annots().array;
2. Push your anno > annots.push(noteAnnotation);
3. Set all annotation in require page > await page.node.set(PDFName.of('Annots'), pdfDoc.context.obj(annots));

**Comment by jean9696** [comment]
In case someone encounters the same struggle to find a working example of creating a FreeText annotation from scratch, here is what I came up with:
```typescript

export const addAnnotations = (
  pdfPage: PDFPage,
  context: PDFContext,
  dicts: PDFDict[]
) => {
  // @ts-ignore
  const existingAnnotations = pdfPage.node.Annots()?.array
  pdfPage.node.set(
    PDFName.of('Annots'),
    context.obj([
      ...dicts.map((dict) => context.register(dict)),
      ...existingAnnotations,
    ])
  )
}

export interface CreateFreeTextAnnotationParams extends Position, Size {
  rotate: number
  fontSize: number
  pdfFont: PDFFont
}

export const createFreeTextAnnotation = async (
  context: PDFContext,
  text: string,
  params: CreateFreeTextAnnotationParams
) => {
  const fontKey = 'F0'

  const dict = context.obj({
    Type: 'XObject',
    Subtype: 'Form',
    FormType: 1,
    BBox: [0, 0, params.width, params.height],
    Resources: context.obj({
      Font: context.obj({
        [fontKey]: params.pdfFont.ref,
      }),
    }),
  })

  const operators = [
    ...drawText(params.pdfFont.encodeText(text), {
      color: rgb(0, 0, 0),
      font: fontKey,
      size: params.fontSize,
      rotate: degrees(params.rotate),
      xSkew: degrees(0),
      ySkew: degrees(0),
      x: params.width / 2,
      y: params.height / 2,
    }),
  ]
  const stream = PDFContentStream.of(dict, operators, false)
  const streamRef = context.register(stream)
  const appearance = context.obj({ N: streamRef })

  return context.obj({
    Subtype: PDFName.of('FreeText'),
    Contents: PDFString.of(text),
    Rect: [
      params.x,
      params.y,
      params.x + params.width,
      params.y - params.height,
    ],
    F: AnnotationFlags.NoZoom,
    CA: 1,
    AP: appearance,
  }) as PDFDict
}
```
