### ISSUE TITLE
Embed JS

### ISSUE THREAD

**Issue by btecu** [Hopding/pdf-lib#477]
Is there a way to embed Javascript into a PDF using `pdf-lib`?

**Comment by Hopding** [comment]
Hello @btecu! 

You certainly can. However, pdf-lib doesn't have any special APIs for this, so you'll have to use the lower-level APIs. Here's a basic example demonstrating how to create a JavaScript action dictionary with pdf-lib:
```js
import { PDFDocument, PDFHexString } from 'pdf-lib';

const pdfDoc = await PDFDocument.create()

const jsActionDict = pdfDoc.context.obj({
  Type: 'Action',
  S: 'JavaScript',
  JS: PDFHexString.fromText(`
    // Insert the JavaScript you want to embed here...
  `),
})

// Now use the `jsActionDict`...
```

See section **12.6.4.16 JavaScript Actions** of the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) for more details about JavaScript action dictionaries and how to use them.
