### ISSUE TITLE
Is contents of text annotation support utf-8?

### ISSUE THREAD

**Issue by Leed-Y** [Hopding/pdf-lib#478]
Is contents of text annotation support utf8?
![image](https://user-images.githubusercontent.com/39029421/84122410-f90f3480-aa6a-11ea-8dcc-d2e6da374d94.png)

**Comment by Hopding** [comment]
Hello @Leed-Y! The `Contents` entry in a text annotation dictionary supports UTF-16BE. Any value whose `type` is `text string` supports UTF-16BE. To produce a `text string` data type with pdf-lib, you'll want to use the [`PDFHexString.fromText`](https://github.com/Hopding/pdf-lib/blob/master/src/core/objects/PDFHexString.ts#L17-L26) method. For example:
```js
import { PDFHexString } from 'pdf-lib';
const Contents = PDFHexString.fromText('Foo 文 😃')
```
