### ISSUE TITLE
How to rearrange and remove existing pages and merge new PDF in between 2 pages

### ISSUE THREAD

**Issue by HeyLetsDebug** [Hopding/pdf-lib#479]
Hi @Hopding ,

Can you help me with the snippet to rearrange or remove existing pages from a PDF and merge new PDF in between 2 pages of some other pdf at the same time? 

For eg. we do in Adobe acrobat drag and re-arrange pages or delete pages which are not required or merge a new pdf into existing one. Currently I am able to view the pages of a pdf and re-arrange them using jquery UI (only in front end) and delete pages of pdf using the removePage function but not sure how to merge PDFs with deleted pages. Please help!

$( '#show-pdf-page-wrapper' ).on( 'click', 'p', function () {
  var pageID = $(this).attr('id'); //gives me number of the page which needs to be deleted
  var parentID =  $(this).closest('div').attr('id');  //gives me number of the blob url (URL.createObjectURL) of the PDF selected from which the page needs to be deleted
  $(this).closest('div').hide(); //hides the deleted page from front end to give the effect that page is deleted to front-end user
  removePDF(parentID, pageID);
});

async function removePDF(pdfURL, pagenumber)
{
  var pgNum = parseInt(pagenumber, 10) - 1;
 const existingPdfBytes = await fetch(pdfURL).then(res => res.arrayBuffer())
var bytes = new Uint8Array(existingPdfBytes);
const pdfDoc = await PDFDocument.load(bytes)
pdfDoc.removePage(pgNum);
 const pdfBytes = await pdfDoc.save();
}

![image](https://user-images.githubusercontent.com/38434912/84421857-cbc4b100-ac39-11ea-9ede-09a6dcc4a83b.png)

Regards,
Abhishek Dubey

**Comment by soadzoor** [comment]
@dubeyabhishek36 I'd create a new PDF (const newPDF = await PDFDocument.create), and add the necessary pages. You have all the necessary APIs, like "copyPages", and "addPage". Please try and let me know

**Comment by HeyLetsDebug** [comment]
Hi @soadzoor ,

I am actually bit confused right now. You can have a look on the code below, so what I am currently able to achieve is:

1. Render PDF in canvas (using pdf.js) as shown in image above
2. Delete pages from pdf using the delete button.
3. Rearrange the pdfs using jQueri UI (drag and drop)

What I am not able to understand and do is:
1. How to merge 2 (or more) pdfs after changing the sequence of pages and after deleting any page?

Any help would be highly appreciated!!

/************************************CODE****************************/

var PDFDocument = PDFLib.PDFDocument;
var StandardFonts = PDFLib.StandardFonts
 var titleInput  = document.getElementById("title-of-pdf");
var to_merge_files = document.getElementById("files");
var save_pdf_name = document.getElementById("pdf-name-input");
var  name_of_pdf;
var listofFiles = [];


// loading files in work-area on change event

to_merge_files.addEventListener('change', function() {

    var file = this.files[0];

    var mime_types = [ 'application/pdf' ];
    
    if(mime_types.indexOf(file.type) == -1) {
        alert('Error : Incorrect file type');
        return;
    }
    _OBJECT_URL = URL.createObjectURL(file)

// calling the show pdf function using pdf.js
    showPDF(_OBJECT_URL);
// creating an array of object URL for the files added in the work-area everytime a new file is loaded
        for(var i = 0; i< to_merge_files.files.length; i++){
    nameOfFile = [];
    nameOfFile = to_merge_files.files[i].name;
    listofFiles.push(URL.createObjectURL(to_merge_files.files[i]));
  }
});

// function to render PDF
 var thePdf = null;
    var scale = 1;
function showPDF(pdf_url) {
    PDFJS.getDocument({ url: pdf_url }).promise.then(function(pdf) {
        thePdf = pdf;
        viewer = document.getElementById('show-pdf-page-wrapper');
console.log(pdf);

        for(page = 1; page <= pdf.numPages; page++) {
           var li = document.createElement('div');
           viewer.appendChild(li);
           var last = listofFiles[listofFiles.length - 1];
           li.setAttribute("id", last); 
          canvas = document.createElement("canvas");    
          canvas.className = 'pdf-page-canvas';         
          li.appendChild(canvas);            
          renderPage(page, canvas);
           var deleteText = document.createElement('p');
           deleteText.setAttribute("id", page);
           deleteText.setAttribute("class", "delete-page");// 
           var t = document.createTextNode("Delete"); 
           deleteText.appendChild(t);
           li.appendChild(deleteText);
        }
    });
}

    function renderPage(pageNumber, canvas) {
        thePdf.getPage(pageNumber).then(function(page) {
          viewport = page.getViewport(scale);
          canvas.height = viewport.height;
          canvas.width = viewport.width;          
          page.render({canvasContext: canvas.getContext('2d'), viewport: viewport});
    });
    }

 $("#show-pdf-page-wrapper").sortable({
     cursor: 'move',
     placeholder: "ui-state-highlight",
     revert: true
 });

 $("#show-pdf-page-wrapper").disableSelection();


$( '#show-pdf-page-wrapper' ).on( 'click', 'p', function () {
  var pageID = $(this).attr('id');//gives me number of the page which needs to be deleted
  var parentID =  $(this).closest('div').attr('id');//gives me number of the blob url (URL.createObjectURL) of the PDF selected from which the page needs to be deleted
  $(this).closest('div').hide(); //hides the deleted page from front end to give the effect that page is deleted to front-end user
  removePDF(parentID, pageID)
});

async function removePDF(pdfURL, pagenumber)
{
  var pgNum = parseInt(pagenumber, 10) - 1;
 const existingPdfBytes = await fetch(pdfURL).then(res => res.arrayBuffer())
var bytes = new Uint8Array(existingPdfBytes);
const pdfDoc = await PDFDocument.load(bytes)
pdfDoc.removePage(pgNum);
 const pdfBytes = await pdfDoc.save();
}

**Comment by soadzoor** [comment]
@HeyLetsDebug Do you have a live demo (or github link) to this somewhere?

**Comment by HeyLetsDebug** [comment]
@soadzoor nope nothing as such..

**Comment by HeyLetsDebug** [comment]
Hi @Hopding and @soadzoor any updates or any solution to this??

**Comment by soadzoor** [comment]
@HeyLetsDebug Again: If I were you, I'd create a new PDF document with `await PDFDocument.create()`, then add the required pages one-by-one in the order I want them. That's how I'd merge the pages into a single pdf document. Without a live example from you, I don't think I could help more.
