### ISSUE TITLE
Deno - how to import with typings?

### ISSUE THREAD

**Issue by bockoblur** [Hopding/pdf-lib#484]
Hi.
Great library. I am trying to use it in Deno, but can't seem to get typings to work...
I am importing via
    
    import {PDFDocument} from "https://cdn.pika.dev/pdf-lib@^1.7.0";
    
and everything works, but I *don't have types imported*, so I don't have intellisense in VS code.

When I import this library for node project (via `npm` ), everything is fine.
Am I missing something?
Thanks.

**Comment by bockoblur** [comment]
Example from **Node** project - intellisense working perfectly:
![image](https://user-images.githubusercontent.com/10337815/84525697-607feb00-acdc-11ea-8944-2afa5aec69ff.png)

Example from **Deno** project - intellisense not working:
![image](https://user-images.githubusercontent.com/10337815/84525904-b3f23900-acdc-11ea-9564-cdc740bb2d04.png)

**Comment by Hopding** [comment]
Hello @bockoblur!

It looks like the types should be available to Deno. E.g. if you try to run the following script in Deno you should get an error, because `PDFDocument` is not assignable to `number`:
```
import { PDFDocument } from 'https://cdn.pika.dev/pdf-lib@^1.7.0';
const pdfDoc: number = await PDFDocument.create();
```

The problem is that VSCode cannot access the types. My understanding is that this is a common issue with Deno today and is not specific to `pdf-lib`. I'd expect you to encounter this using any typed library in Deno. You might try reading this section of the Deno manual and see if that provides any pointers for you to get this working: https://deno.land/manual/getting_started/setup_your_environment#editors-and-ides.

**Comment by bockoblur** [comment]
@Hopding - thank you for your prompt response.

I forgot to mention, but I do have [recommended VSCode plugin](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) installed.
And with modules imported from `deno.land` I do have intellisense.

Example:
![image](https://user-images.githubusercontent.com/10337815/84562070-c3f83000-ad51-11ea-98ac-033b44136c6e.png)

Also, types are *not* available to Typescript compiler, and I'm not getting an error compiling your snippet.

It is **definitely** not specific to `pdf-lib`, since other TypeScript libraries imported via `cdn.pika.dev` are behaving in the similar manner. (Tried `moment` to check this.)

Maybe it's about the way `cdn.pika.dev` serves the library? (Just guessing...)

Can you please consider adding your awesome library to [Deno Third Party Modules](https://deno.land/x)? Maybe that will solve my problem.

Thanks.

**Comment by Hopding** [comment]
@bockoblur What version of `deno` are you using? When I write my example to `test.ts` and execute it as follows, I do get a TypeScript error:
```
$ deno run test.ts
Compile file:///Users/user/test.ts
error: TS2322 [ERROR]: Type 'PDFDocument' is not assignable to type 'number'.
const pdfDoc: number = await PDFDocument.create();
      ~~~~~~
    at file:///Users/user/test.ts:2:7
```

**Comment by bockoblur** [comment]
@Hopding  I started this with Deno 1.0.5, now upgraded to 1.1.0

```shell
$ deno --version
deno 1.1.0
v8 8.4.300
typescript 3.9.2
```
And i am not using any `tsconfig.json` but relying on Deno's built-in configuration.

**Comment by bockoblur** [comment]
### Follow-up
After some investigation, turns out that official VS Code plugin [Deno by denoland](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) is not working as it should.
Reverting to VS Code plugin marked as deprecated [[Deprecated] Deno by axetroy](https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno) solved the issue. 

### Conclusion
There's really no issue here with your library after all. Sorry to bother you and keep up the excellent work!

**Comment by zackdotcomputer** [comment]
Did too much investigation here, full details in the other Issue but the TLDR is:
- No longer have to downgrade to the deprecated plugin
- Instead, have to add `?dts` to the end of imports from skypack.dev (formerly pika.dev)

So `import { PDFDocument } from 'https://cdn.skypack.dev/pdf-lib@^1.11.1?dts';` works
