### ISSUE TITLE
Unwanted ligatures

### ISSUE THREAD

**Issue by zimt28** [Hopding/pdf-lib#490]
I want to use a font from `fonts.google.com` and am running into an issue.

I've included the font (Nunito) like so:
```js
const nunitoBoldUrl =
  "https://fonts.gstatic.com/s/nunito/v12/XRXW3I6Li01BKofA6sKUYevIWzgPDA.woff2";
const nunitoBoldFontBytes = await fetch(nunitoBoldUrl).then((res) => res.arrayBuffer());

const nunitoBold = await pdfDoc.embedFont(nunitoBoldFontBytes);
```

This works, with one exception (there might be more, but this is what I could find):

Printing `fi` adds unwanted spacing after it which shouldn't be there, the Google preview also doesn't show it.

`fi ir fir`:
<img width="352" alt="Screenshot 2020-06-15 at 21 05 12" src="https://user-images.githubusercontent.com/1764689/84696215-6aa82080-af4c-11ea-951b-21dd5e72dcfb.png">

I _think_ the font has a special ligature for `fi`, if I install the font on my system I get the same connected `f` and `i` letters, but without the spacing. Is this an issue with `pdf-kit` or `fontkit`?

**Comment by fobdy** [comment]
The same problem for me with "Source Sans Pro" font

**Comment by fobdy** [comment]
We could try to turn off the ligatures if there was access to the low-level fontkit api
```js
font.layout(lineTxt, { liga:false })
```

Related https://github.com/foliojs/fontkit/issues/170

**Comment by zimt28** [comment]
@fobdy Which file format are you trying to use?

**Comment by fobdy** [comment]
> @fobdy Which file format are you trying to use?

I'm using `.ttf`

**Comment by Hopding** [comment]
Hello @zimt28 @fobdy! As far as I'm aware this is an issue with `fontkit`, though I haven't been able to confirm this. If anybody is interested, it is possible to disable ligatures when performing text layout with `fontkit` (as @fobdy mentioned). You would just need to update the API to pass options here:
https://github.com/Hopding/pdf-lib/blob/193e48ff2ce07d72f8191087adcdd01aa3c48a62/src/core/embedders/CustomFontEmbedder.ts#L52-L57

I'd be happy to accept a PR if anybody is interested in working on this.

**Comment by Hopding** [comment]
Version `1.14.0` includes an API that can disable font ligatures (thanks to @hefler!): https://github.com/Hopding/pdf-lib/blob/c9577682b6176ead2bf5167418702db987e15b45/apps/node/tests/test6.ts#L37-L40

**Comment by direnc** [comment]
Same problem with Garamond.   ` features: { liga: false } ` solution is not working, still with spacing .

**Comment by ephraimduncan** [comment]
Same problem with Caveat, disabling ligatures is not working

**Comment by r4dulf** [comment]
@ephraimduncan For the Caveat font, setting `calt: false` solved the problem
```
 const caveatRegular = await documentProxy.embedFont(caveatFontData, {
    features: { calt: false },
  });
```
![image](https://github.com/Hopding/pdf-lib/assets/49458723/e9d36a75-3f20-486b-8d8e-cf25261d175b)
