### ISSUE TITLE
Find & Edit or Remove specific text in the PDF

### ISSUE THREAD

**Issue by Simobain** [Hopding/pdf-lib#492]
Hello,

There is a pdf I'd like to edit by changing words.
did not find a way to find and then delete, remove or edit a text in the pdf.

Any help ? 

Thanks a lot,

**Comment by keyhoffman** [comment]
Running into same issue

**Comment by hungdev** [comment]
good feature !

**Comment by fabioselau077** [comment]
same issue

**Comment by Hopding** [comment]
Hello @Simobain! This is possible only if the text your finding/editing/removing is in a form field. See https://github.com/Hopding/pdf-lib#limitations and https://github.com/Hopding/pdf-lib/issues/590#issuecomment-693718538.
