### ISSUE TITLE
PDFDocument.load is not a function

### ISSUE THREAD

**Issue by jitesh95** [Hopding/pdf-lib#493]
Hello, 

I have installed this library in my node js application and imported it. 

I installed it with command : npm install pdf-lib --save

and imported it with : var PDFDocument= require('pdf-lib');

While calling the method, i am getting the error "PDFDocument.load is not a function". Could you please help me with the issue. Thanks

**Comment by Hopding** [comment]
Hello @jitesh95!

Your import is incorrect. Try either of the following:
```js
const { PDFDocument } = require('pdf-lib');
// or
const PDFLib = require('pdf-lib');
const PDFDocument = PDFLib.PDFDocument;
```
