### ISSUE TITLE
Support for blend modes [enhancement]

### ISSUE THREAD

**Issue by bockoblur** [Hopding/pdf-lib#500]
Have you considered implementing `Blend Modes` for drawing objects/text, as defined in **Section 11.3.5.** and **Table 136** _(page 324)_ of the [pdf_specification.pdf](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf)?

**Comment by bockoblur** [comment]
Hey @Hopding 

I looked around your code, and I got this feature working.
I introduced new (optional) property named `blendMode` in all of the `PDFPageDraw[xxx]Options`  and new operator `BlendModeOperator = 'BM',`

I did some (manual) testing, and it seems to be working ok. 

Changed files are attached. If you would like, I could PR and continue on this... or someone else can take over, 

[blendModes.zip](https://github.com/Hopding/pdf-lib/files/4820237/blendModes.zip)

**Comment by Hopding** [comment]
Hello @bockoblur! 

Looks like you're on the right track! It'd be great if you could open a PR for this. I'd be happy to get this feature added! (note that you'll need to update the integration tests to use this feature before the PR can be merged).

Let me know if you have any questions!

**Comment by bockoblur** [comment]
Opened PR (#503 - Add Blend Modes)
I am having trouble running apps/tests for Node & Deno on my Windows PC.

**Comment by Hopding** [comment]
What exactly is giving you trouble @bockoblur?

**Comment by bockoblur** [comment]
When I run the `app:node` or `app:deno` scripts, 1st test completes, but system cannot open resulting file. File is generated ok, and I can open it manually from system temp folder, but script halts on error and would not continue.

I wrote new test (`test14.ts`) for Node and Deno, and it generates a good pdf file demonstrating the new functionality (`blendMode`) when run separately.

At first I thought that problem is with path separator ('\\' on Windows instead of '/'), but I changed that in Node script (now uses `path.sep`) and still no luck. Same error occurs in `Deno.run` when running `app:deno`.
Maybe someone could try the tests on Mac or Linux?

**Comment by Hopding** [comment]
@bockoblur Just pushed https://github.com/Hopding/pdf-lib/commit/ff447a9d7164f0b5e45c99fc884e79b1d22890e7 to fix those issues on Windows. The integration tests should run seamlessly for you now

**Comment by Hopding** [comment]
Closing as this feature was added in https://github.com/Hopding/pdf-lib/pull/503.

**Comment by Hopding** [comment]
Version [`1.9.0`](https://www.npmjs.com/package/pdf-lib/v/1.9.0) is now published with this feature. The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.9.0).

You can install this new version with npm:

```
npm install pdf-lib@1.9.0
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.9.0/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.9.0/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.9.0/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.9.0/dist/pdf-lib.min.js
