### ISSUE TITLE
To prevent text overflowing what's the best practice

### ISSUE THREAD

**Issue by x4080** [Hopding/pdf-lib#501]
Hi, for instance if we have 2 columns and wanted to prevent text for column 1 not overflowing to column 2

What's the best practice for this? Knowing the column width and from that we can now if it is overflowing but then what procedure we should do, is it to have rectangle to draw before drawing column 2?

Sorry if it's confusing

**Comment by Hopding** [comment]
Hello @x4080!

You’ll want to use the [`maxWidth`](https://pdf-lib.js.org/docs/api/interfaces/pdfpagedrawtextoptions#optional-maxwidth) option for [`drawText`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawtext).

I hope this helps. Please let me know if you have any additional questions.

**Comment by x4080** [comment]
Thanks @Hopding

**Comment by x4080** [comment]
@Hopding, Using maxWidth, breaks the text into multiple lines, and working nicely, if I wanted that the text to clip in certain width (not going to next line), do you recommend a solution ?

Thanks

**Comment by Hopding** [comment]
@x4080 You can certainly clip the text. I'd suggest taking a look at the [`clip()`](https://pdf-lib.js.org/docs/api/#const-clip) operator. I don't have time to write up a bespoke example for you right now, but you can take a look at the following test for an example of how to use it:
https://github.com/Hopding/pdf-lib/blob/ff447a9d7164f0b5e45c99fc884e79b1d22890e7/apps/node/tests/test1.ts#L79-L103

(Note that you can follow the instructions [here](https://github.com/Hopding/pdf-lib/blob/master/CONTRIBUTING.md#running-the-integration-tests) if you want to run the test and see what the result looks like).

**Comment by x4080** [comment]
@Hopding Thanks for your help

**Comment by x4080** [comment]
@Hopding, sorry to bother you again, regarding your first solution with maxWidth and the text is overflowing to new lines below, can we get the last y coordinate of the last line ? So that I can draw next line below that last line

TIA
