### ISSUE TITLE
load .pdf from browser

### ISSUE THREAD

**Issue by mathiasleroy** [Hopding/pdf-lib#51]
Hi,
I'm stuck with this explanation :

> // This should be a Uint8Array.
> // In the browser, you could make a fetch() call and use res.arrayBuffer().

Can someone explain a bit more about this ?  
Can this be done with ajax request ?

EDIT
Almost  got it with

    fetch('docs/example.pdf')
          .then(function(response) {
                response.arrayBuffer().then(function(buffer) {
                  const existingPdfDocBytes = buffer[""[[Uint8Array]]""]

But that opens the pdf in the window, don't know why...

**Comment by mathiasleroy** [comment]
I think I got it with

    fetch('docs/example.pdf')
          .then(function(response) {
                response.arrayBuffer().then(function(buffer) {
                  const existingPdfDocBytes = buffer[""[[Uint8Array]]""]

**Comment by Hopding** [comment]
Hello @mathiasleroy. You snippet looks close to what you want. Try the below code to convert the `ArrayBuffer` produced by `response.arrayBuffer()` into a `Uint8Array`:
```js

```
