### ISSUE TITLE
PDFString does not handle escaping

### ISSUE THREAD

**Issue by daniloarcidiacono** [Hopding/pdf-lib#510]
Hello,
the `PDFString` class does not handle escaping; its documentation reports:

```
  // The PDF spec allows newlines and parens to appear directly within a literal
  // string. These character _may_ be escaped. But they do not _have_ to be. So
  // for simplicity, we will not bother escaping them.
```

which is incorrect, because parenthesis may not be escaped **only** if they are balanced.

Furthermore, strings longer than 255 characters are split into multiple lines, which is not handled by `PDFString` as well.

![image](https://user-images.githubusercontent.com/17272323/86236586-9d802480-bb9a-11ea-9dcf-3127a2b56faf.png)

The screenshot shows a PDF form field with `/TU` set to a string 320 characters long. Adobe Reader automatically inserts a 5C0D (a reverse solidus followed by carriage return) at the 255th character. `PDFString` does not handle this.

**Comment by Hopding** [comment]
Hello @daniloarcidiacono! You are correct that `PDFString` does not auto-escape its input. The `PDFString` class is part of pdf-lib's low-level `core` API. It is assumed that the caller of `PDFString` has already handled any necessary escaping. That being said, I'd be open to a PR that adds a new method to `PDFString` which escapes its input.
