### ISSUE TITLE
Export Scanned Image from PDF

### ISSUE THREAD

**Issue by mcmspark** [Hopding/pdf-lib#512]
I followed the guidance in issue 83 https://github.com/Hopding/pdf-lib/issues/83
However, your solution only implements some of the pdf.js decoding.
My pdf's have JBIG2Decode and CCITTFaxDecode identified, and i am attempting to use approaches in pdf.js as you suggest but without success.

To produce a sample simply use a scanner to produce a PDF.  I used an HP OfficeJet Pro.
[scan0001Black.pdf](https://github.com/Hopding/pdf-lib/files/4865606/scan0001Black.pdf)

Do you have insight into dealing with these scanned PDF files?

**Comment by Hopding** [comment]
Hello @mcmspark!

The approach I documented in #83 is only a partial solution. A complete solution that handles all possible image encodings would require additional work. As I mentioned in https://github.com/Hopding/pdf-lib/issues/83#issuecomment-487383843, I do not personally have time to work on this right now. 

If you've taken a stab at pulling the `pdf.js` code into `pdf-lib` as suggested in #83 but are having trouble, I can try to take a look at your code and see what might be wrong with it. Please feel free to reopen this issue with a link to your code.
