### ISSUE TITLE
Can I add TOC bookmark to a pdf by pdf-lib?

### ISSUE THREAD

**Issue by l0o0** [Hopding/pdf-lib#514]
Hi, I have a json like data that indicates page number and content. I hope I can use this data to add a table of contents bookmark in the pdf. It's something like below
![图片](https://user-images.githubusercontent.com/2743744/86429415-047c1580-bd22-11ea-9658-60056ce9174d.png)

**Comment by caspervanpomeren** [comment]
Look at #127 , it has the same problem and a possible solution. 

Problem is: 
`pdf-lib doesn't have a high level API for it yet. So it requires a bit of lower-level code.`

**Comment by l0o0** [comment]
@caspervanpomeren Thank you for your reply. I am trying to use non-js tools to do this.
