### ISSUE TITLE
Garbled error when set chinese in outline

### ISSUE THREAD

**Issue by suninuni** [Hopding/pdf-lib#516]
Hi @Hopding ,

I just tried to use chinese as outline item title(refer to https://github.com/Hopding/pdf-lib/issues/127#issuecomment-641710694), but i got some garbled strings, e.g

![image](https://user-images.githubusercontent.com/7345529/86546711-c3c20d80-bf68-11ea-831e-8fea9beb87d6.png)

Actually in the code, some of them are:

![image](https://user-images.githubusercontent.com/7345529/86547442-9c207480-bf6b-11ea-98d8-f2281121a10b.png)

So, i found a pdf which has chinese in outline and print it in the console. They are also garbled strings, such as `þÿ{,\\u00001zà\\u0000 g`. But when i set `þÿ{,\\u00001zà\\u0000 g` as a outline item title, i got `第一章` in the result pdf's outline which is display in the right way.

Is there any suggestion to resole this? 

Thank you.

Some informations which may be helpful:

- https://tex.stackexchange.com/questions/236863/incorrect-encoding-in-pdf-outlines/237277#237277

**Comment by inetfuture** [comment]
@Hopding any suggestions on this? thanks.

**Comment by suninuni** [comment]
> https://tex.stackexchange.com/questions/236863/incorrect-encoding-in-pdf-outlines/237277#237277

According this, i found a function `utf16Encode()` in https://github.com/Hopding/pdf-lib/blob/350c54ba1e655a592cfa405e295e258b70c20fa5/src/utils/unicode.ts#L203-L206

After this, i found `PDFHexString.fromText()` which used this function https://github.com/Hopding/pdf-lib/blob/350c54ba1e655a592cfa405e295e258b70c20fa5/src/core/objects/PDFHexString.ts#L17-L26

So i resolved this garbled problem by `dict.set(PDFName.Title, title ? PDFHexString.fromText(title) : title);`

And i saw you are working at https://github.com/Hopding/pdf-lib/pull/486 which about `PDFOutline`, so i recommend using `PDFHexString.fromText` instead of `PDFString.of` when set `PDFName.Title` in https://github.com/Hopding/pdf-lib/pull/486/files#diff-cf25ad19a97bf84bda22a1a3621dbdf1R28

Thank you anyway.
