### ISSUE TITLE
StandardFonts support Edit

### ISSUE THREAD

**Issue by jfw10973** [Hopding/pdf-lib#517]
There is some font (like PingFang-SC), already pre-install in our Mac, but code 
https://github.com/Hopding/pdf-lib/blob/129b846610051a252ea0b3aa6c6856f49f6525aa/src/utils/objects.ts#L7

It will be false and force the developer to embed a font file in PDF file. 
Could you add a feature to solve the problem?

**Comment by Hopding** [comment]
Hello @jfw10973! 

The standard fonts cannot be changed, as they are defined by the PDF specification. Please see https://github.com/Hopding/pdf-lib#fonts-and-unicode. 

The PDF spec allows non-standard fonts to be either embedded, or provided by the system. It sounds like you are looking to use a system provided font. pdf-lib does not provide any APIs to do this, as it's a relatively rare use-case. Most non-standard fonts are embedded. That being said, I would be happy to accept PRs that update pdf-lib's API to support this feature. But I will not personally have time to work on this.
