### ISSUE TITLE
opacity option not working for drawLine function

### ISSUE THREAD

**Issue by tazilios** [Hopding/pdf-lib#518]
I definitely the opacity option so that users can "highlight" text (I'm using a transparent yellow).
The generated result (see attached file) does not reflect any of the value I set for opacity:
[Test document.pdf](https://github.com/Hopding/pdf-lib/files/4884930/Test.document.pdf)

            pdfPage.drawLine({
              start: { x: posX, y: posY },
              end: { x: posXEnd, y: posYEnd },
              thickness: 10,
              color: rgb(0.98, 1, 0),
              opacity: 0.75
            });

Did I miss something?

Thanks for your help

**Comment by Hopding** [comment]
Hello @tazilios!

The opacity option seems to be working fine for me. Here's an example script:
```js
import { PDFDocument, rgb } from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();

  const page = pdfDoc.addPage([500, 500]);

  page.drawCircle({
    x: 250,
    y: 250,
    size: 100,
    color: rgb(1, 0, 0),
  });

  page.drawLine({
    start: { x: 25, y: 250 },
    end: { x: 475, y: 250 },
    thickness: 150,
    color: rgb(0, 0, 1),
    opacity: 0.5,
  });

  const pdfBytes = await pdfDoc.save();
})();
```

This produces the following:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/86788895-48c22b00-c02c-11ea-8b7d-08b31ff0bb2f.png" alt="output PDF">
</kbd>

>

Does this example work for you?

**Comment by tazilios** [comment]
Hi Andrew !

Thanks for your answer, let me double check this.
Note that I'm actually adding those lines to an existing document.

Cheers

Anastasios

**Comment by tazilios** [comment]
Hi again ;-)

Forget about this issue, I saw some work was made since version 1.7 on the opacity so I upgraded to the last one (1.9) and guess what... It now works.
Thanks for the quick reaction and the good work you did !!

Cheers
