### ISSUE TITLE
Merging pdf does not retain source pdf formatting

### ISSUE THREAD

**Issue by kimlambiguit** [Hopding/pdf-lib#519]
Hello @Hopding,

First of all, awesome tool. the best, free library so far. 

Anyway, I have an issue that I've been trying to resolve. I'm currently merging multiple pdfs using the example in your README. However, the merged pdf does not retain the original formatting of the source PDF. Is this an expected behavior? Since I've read from one of your comments here that copying pdf contents does not copy other underlying data (e.g. links ). Does this perhaps include the formatting as well? If so, can you suggest any workaround?

Thanks!!!

**Comment by Hopding** [comment]
Hello @kimlambiguit!

Can you share some sample PDFs and screenshots?

**Comment by kimlambiguit** [comment]
Hi @Hopding 

Forgot to mention this are Acrofields.  So basically what happens is I have a bunch of PDFs with acrofields that are filled and saved. The saved PDFs are then merged. Below is a sample page.

**Original, non merged PDF**
![original](https://user-images.githubusercontent.com/1272232/86806711-b3ff1200-c0ab-11ea-9542-e41bd4dc3fa2.png)

**Merged.** 
![merged](https://user-images.githubusercontent.com/1272232/86807037-0c361400-c0ac-11ea-9b54-5ec4f93bd197.png)

Thank you for taking notice and good day.

**Comment by kimlambiguit** [comment]
Hello @Hopding. is there additional information that you need to help formulate a root cause or a workaround?

**Comment by Hopding** [comment]
@kimlambiguit pdf-lib doesn't currently copy AcroForms when copying or embedding pages. See https://github.com/Hopding/pdf-lib/issues/417#issuecomment-620900368. One thing you could try is "flattening" the form fields before using pdf-lib to load the documents. This would remove the form fields themselves while preserving their filled values. (Note, however, that you'll have to find a different tool to do the flattening. pdf-lib does not have APIs for that).
