### ISSUE TITLE
Rotate an image around it's center

### ISSUE THREAD

**Issue by snc** [Hopding/pdf-lib#520]
When I add an image to a page via the following code, it gets positioned to the bottom left of the page:

```
page.drawImage(img, {
  x: 0,
  y: 0,
  width,
  height,
});
```

Now I want to rotate the image by 180°:

```
page.drawImage(img, {
  x: 0,
  y: 0,
  width,
  height,
  rotate: degrees(180),
});
```

Because the transformation origin is bottom left, the image will not be visible because it was rotated out of the page. Is it somehow possible to rotate the image based on the center of itself, so that the image is still visible on the bottom left but upside down?

**Comment by snc** [comment]
Solved it, here is my code:

```
page.pushOperators(
  pushGraphicsState(),
  concatTransformationMatrix(
    1,
    0,
    0,
    1,
    originX,
    originY,
  ),
  concatTransformationMatrix(
    cos(angle),
    sin(angle),
    -sin(angle),
    cos(angle),
    0,
    0,
  ),
  concatTransformationMatrix(
    1,
    0,
    0,
    1,
    -1 * originX,
    -1 * originY,
  ),
);
page.drawImage(img, {
  x: originX - (width / 2),
  y: originY - (height / 2),
  width: width,
  height: height,
});
page.pushOperators(
  popGraphicsState(),
);
```

**Comment by princ09** [comment]
@snc I am facing same issue, please explain your solution or provide 
![Uploading 20210105_111753.jpg…]()
I want to achieve something like this where i want my image to get added top left always irrespective of angle of pdf.
Your solution giving me hope.

**Comment by meliodev** [comment]
page.drawImage(jpgImage, {
      x: page.getWidth() / 2 - jpgDims.height / 2,
      y: page.getHeight() / 2 + jpgDims.width / 2,
      width: jpgDims.width,
      height: jpgDims.height,
      rotate: degrees(-90),
    })

**Comment by bktan81** [comment]
cool!

just in case anyone wants to add a watermark in the middle of the PDF page, here is the code

https://jsfiddle.net/bktan81/8os7rwx0/
