### ISSUE TITLE
Include StandardFonts in the bundle only when it really necessary

### ISSUE THREAD

**Issue by AlexRekish** [Hopding/pdf-lib#522]
Is it possible to somehow exclude standard fonts from bundle if we dont use it? In our project `@pdf-lib/standard-fonts/es` adds extra ~95kB(gzipped) to final bundle even if we don't use any related to fonts functionality. 
Thnx.

**Comment by Hopding** [comment]
Hello @AlexRekish!

The only way to accomplish this would be to fork `pdf-lib` and remove the code that imports `@pdf-lib/standard-fonts`. It would be nice if `pdf-lib` allowed that dependency to be tree-shaken or provided a straightforward way to produce a build without it. But that would require breaking API changes and just isn't possible right now.

I hope this helps. Please let me know if you have any additional questions!
