### ISSUE TITLE
Strange orientation problem 

### ISSUE THREAD

**Issue by sbraaa** [Hopding/pdf-lib#524]
In my project I use pdf-lib to place some watermarks on pdf loded by users.
Testing my project using various pdf provided by the users I found a pdf whichis rendered as normal A4 portrait but has page size 841.68 x 595.08 pts (A4) and page rotation 270 degrees.
This pdf was originally created starting from paper using a printer/scanner.
My problem is that if I try to draw an image it appers in wrong position and with wrong orientation.
Using parameter rotate of drawImage fix orientation problem but  position are still wrong!
I've tried the solution provided in #65 but it doesn't solve.
Someone faced problem like this?

**Comment by sbraaa** [comment]
Doing more tests I found that solution provided in #65 by @kevinswartz really works!
My problem was I'm not using text but images with center origin coordinates which require different calculations.
Another problem I found was calculate the correct scale factor: if screen dimensions are different than pdf ones remenber that with 90 or 270 degrees rotation you must compare screen height with pdf width and viceversa.
I hope that these cases will be managed by the library itself in the future (al least the pdf rotation).

**Comment by doot0** [comment]
@sbraaa Can you provide some example of how you did the width/height calculation for images? I'm also facing the same issue.

**Comment by sbraaa** [comment]
> @sbraaa Can you provide some example of how you did the width/height calculation for images? I'm also facing the same issue.

I calculated scale factor comparing canvas dimensions with pdf dimensions: as I wrote you must take care of pdf orientation.
After doing that I converted my canvas object to png extracting dimensions and applying scale factor

```
let pngUrl = canvas_object.toDataURL({
	format: 'png',
	enableRetinaScaling: true
});

const pngImageBytes = await fetch(pngUrl).then((res) => res.arrayBuffer());
const pngImage = await pdfDoc.embedPng(pngImageBytes);
const pngDims = pngImage.scale(scale);
```

then I followed solution #65 for x and y cordinates calculation.

You must take care about device pixel ratio so you must divide image width/height for window.devicePixelRatio otherwise you could get wrong image size (which  tipically happens with smartphones and Mac using  retina display).
Hope it helps

**Comment by doot0** [comment]
@sbraaa Thanks! This doesn't seem to be documented anywhere else so this should help those having trouble over at https://github.com/Hopding/pdf-lib/issues/545.

**Comment by princ09** [comment]
> Doing more tests I found that solution provided in #65 by @kevinswartz really works!
> My problem was I'm not using text but images with center origin coordinates which require different calculations.
> Another problem I found was calculate the correct scale factor: if screen dimensions are different than pdf ones remenber that with 90 or 270 degrees rotation you must compare screen height with pdf width and viceversa.
> I hope that these cases will be managed by the library itself in the future (al least the pdf rotation).

@sbraaa Hi I am also facing same issue with images and @kevinswartz solution isn't working properly for me.
![20210105_111753](https://user-images.githubusercontent.com/47990313/103617632-99bbc900-4f54-11eb-9549-903e86c9b1a6.jpg)
I am trying to achieve this. Any suggestions?

**Comment by sbraaa** [comment]
From what I see I guess you want the circle image will rotate according pdf page, is this your goal?
So, If your are able to understand which is actual pdf page rotation value you must simply rotate your image according that value.

**Comment by SecureExchanges** [comment]
> > Doing more tests I found that solution provided in #65 by @kevinswartz really works!
> > My problem was I'm not using text but images with center origin coordinates which require different calculations.
> > Another problem I found was calculate the correct scale factor: if screen dimensions are different than pdf ones remenber that with 90 or 270 degrees rotation you must compare screen height with pdf width and viceversa.
> > I hope that these cases will be managed by the library itself in the future (al least the pdf rotation).
> 
> @sbraaa Hi I am also facing same issue with images and @kevinswartz solution isn't working properly for me.
> ![20210105_111753](https://user-images.githubusercontent.com/47990313/103617632-99bbc900-4f54-11eb-9549-903e86c9b1a6.jpg)
> I am trying to achieve this. Any suggestions?

Did you find your answer. We faced exaclty the same problem has you.  The solution proposed by @kevinswartz  do not work for us :-(

**Comment by princ09** [comment]
> > > Doing more tests I found that solution provided in #65 by @kevinswartz really works!
> > > My problem was I'm not using text but images with center origin coordinates which require different calculations.
> > > Another problem I found was calculate the correct scale factor: if screen dimensions are different than pdf ones remenber that with 90 or 270 degrees rotation you must compare screen height with pdf width and viceversa.
> > > I hope that these cases will be managed by the library itself in the future (al least the pdf rotation).
> > 
> > 
> > @sbraaa Hi I am also facing same issue with images and @kevinswartz solution isn't working properly for me.
> > ![20210105_111753](https://user-images.githubusercontent.com/47990313/103617632-99bbc900-4f54-11eb-9549-903e86c9b1a6.jpg)
> > I am trying to achieve this. Any suggestions?
> 
> Did you find your answer. We faced exaclty the same problem has you. The solution proposed by @kevinswartz do not work for us :-(

@SecureExchanges  , I found work around for that. 
                        ```
const currentPage = pages[+i - 1];
			const { width, height } = currentPage.getSize();
			const pageRotation = currentPage.getRotation();
			let drawWidth = width,
				drawHeight = height;
			if (pageRotation.angle == 90 || pageRotation.angle == 270) {
				drawWidth = height;
				drawHeight = width;
				this.changeCanvasSize(height*2, width*2);
			} else {
				this.changeCanvasSize(width*2, height*2);
			}
			let url = this.getCanvasUrl(+i, pageRotation.angle);
			const pngBytes = await fetch(url).then((res) => res.arrayBuffer());
			const pngImage = await this.pdfDoc.embedPng(pngBytes);
			let x = 0;
			let y = 0;
			if (pageRotation.angle == 90) {
				x = width;
			} else if (pageRotation.angle == 270) {
				y = height;
			} else if (pageRotation.angle == 180) {
				y = height;
				x = width;
			}
			currentPage.drawImage(pngImage, {
				x: x,
				y: y,
				width: drawWidth,
				height: drawHeight,
				rotate: degrees(pageRotation.angle),
			});
```

basically three things You need to take care. 
1. Angle of Page ,
2. Rotate Image/Canvas based on pdf page rotation.
3. find the co-ordinate to draw image on pdf based on Angle of page.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/47990313/111563641-54badb00-87be-11eb-89c4-680078db70d8.png)

180 deg example is incorrect , Image would go diagonally. Others are right. You can refer it.

**Comment by SecureExchanges** [comment]
@princ09  thanks for your answer. Finally after reading and testing the code of @kevinswartz it's working very well. 

I just remove the "fontSize" parameter, for us it was not usefull. 

Thanks to @kevinswartz and @prince09

**Comment by penspulse326** [comment]
> > > > Doing more tests I found that solution provided in #65 by @kevinswartz really works!
> > > > My problem was I'm not using text but images with center origin coordinates which require different calculations.
> > > > Another problem I found was calculate the correct scale factor: if screen dimensions are different than pdf ones remenber that with 90 or 270 degrees rotation you must compare screen height with pdf width and viceversa.
> > > > I hope that these cases will be managed by the library itself in the future (al least the pdf rotation).
> > > 
> > > 
> > > @sbraaa Hi I am also facing same issue with images and @kevinswartz solution isn't working properly for me.
> > > ![20210105_111753](https://user-images.githubusercontent.com/47990313/103617632-99bbc900-4f54-11eb-9549-903e86c9b1a6.jpg)
> > > I am trying to achieve this. Any suggestions?
> > 
> > 
> > Did you find your answer. We faced exaclty the same problem has you. The solution proposed by @kevinswartz do not work for us :-(
> 
> @SecureExchanges , I found work around for that.
> 
> ```
> const currentPage = pages[+i - 1];
> 			const { width, height } = currentPage.getSize();
> 			const pageRotation = currentPage.getRotation();
> 			let drawWidth = width,
> 				drawHeight = height;
> 			if (pageRotation.angle == 90 || pageRotation.angle == 270) {
> 				drawWidth = height;
> 				drawHeight = width;
> 				this.changeCanvasSize(height*2, width*2);
> 			} else {
> 				this.changeCanvasSize(width*2, height*2);
> 			}
> 			let url = this.getCanvasUrl(+i, pageRotation.angle);
> 			const pngBytes = await fetch(url).then((res) => res.arrayBuffer());
> 			const pngImage = await this.pdfDoc.embedPng(pngBytes);
> 			let x = 0;
> 			let y = 0;
> 			if (pageRotation.angle == 90) {
> 				x = width;
> 			} else if (pageRotation.angle == 270) {
> 				y = height;
> 			} else if (pageRotation.angle == 180) {
> 				y = height;
> 				x = width;
> 			}
> 			currentPage.drawImage(pngImage, {
> 				x: x,
> 				y: y,
> 				width: drawWidth,
> 				height: drawHeight,
> 				rotate: degrees(pageRotation.angle),
> 			});
> ```
> 
> basically three things You need to take care.
> 
> 1. Angle of Page ,
> 2. Rotate Image/Canvas based on pdf page rotation.
> 3. find the co-ordinate to draw image on pdf based on Angle of page.
>    ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/47990313/111563641-54badb00-87be-11eb-89c4-680078db70d8.png)
>    red point is Origin.
> 
> 180 deg example is incorrect , Image would go diagonally. Others are right. You can refer it.

Awesome explanation!
I referred your picture and wrote a function to fix some problems of elements' position and rotation

```js
function adjustCoordinatesForRotation(
  x,
  y,
  width,
  height,
  pageWidth,
  pageHeight,
  rotation
) {
  switch (rotation) {
    case 90:
      return [height + y, x];
    case 180:
      return [pageWidth - x, height + y];
    case 270:
      return [pageWidth - y - height, pageHeight - x];
    default:
      return [x, pageHeight - y - height];
  }
}
```

Now it works good, but no effect when drawSvgPath.
If someone want to add a svg object, I recommand converting  that to an img and then use the function
