### ISSUE TITLE
Trying to get field names from AcroForm fields

### ISSUE THREAD

**Issue by coler-j** [Hopding/pdf-lib#526]
I am using a collection of different snippets scattered from around Github issues.

I have an acroForm field and when I do this:

`console.log(String(field));`

Output:
```
<
/Type /Annot
/Subtype /Widget
/Rect [ 94.6 683.968 272.85 697.969 ]
/Parent 4 0 R
/AP <<
/N 6 0 R
>>
/DA (/HelveticaLTStd-Bold 8 Tf 0 0 .49804 rg)
/F 4
/Ff 8388608
/FT /Tx
/P 1 0 R
/StructParent 1
/T (þÿ f 1 _ 0 1 [ 0 ])
/Q 0
```

```
const fieldName = field['dict'].get(PDFName.of( 'T' ))?.value
console.log(fieldName)
> "þÿ\u0000f\u00001\u0000_\u00000\u00001\u0000[\u00000\u0000]"
```

Why is the string not naturally decoded into UTF-8? Attempts I have made to change encoding have not been working, just wondering if I am missing something as this seems like something really basic.

**Comment by AceLondon** [comment]
I know you are asking about encoding (which I think is due to the fact that PDFs could be an image or other, and would then contain no text), however I have a snippet of code taken from examples that may give you what you are looking for:

```

  const pdfBuffer = fs.readFileSync(`${cwd}/pdfs/test.pdf`);
  const pdfDoc = await PDFDocument.load(pdfBuffer, {
    updateMetadata: false
  });

  const form = pdfDoc.context.lookup(
    pdfDoc.catalog.get(PDFName.of('AcroForm'))
  ) as PDFObjectType;
  if (!form) {
    throw new Error('PDF does not contain a form');
  }

  const fieldRefs = form.context.lookup(
    form.get(PDFName.of('Fields'))
  ) as PDFObjectType;
  if (!fieldRefs) {
    throw new Error('PDF form does not contain any fields');
  }

  const fields = fieldRefs.array.map((ref: any) => form.context.lookup(ref));

  fields.forEach((field: any) => {
    const name = field.get(PDFName.of('T'));
    const data = field.get(PDFName.of('V'));
    // const boolData = field.get(PDFName.of('Type'));
    if (name) {
      const keyValue = { name: name.value, data: data ? data.value : null };
      console.log(keyValue);
```

**Comment by EricDaviesRok** [comment]
When I try to follow AceLondon's example, I run into the problem that the field doesn't appear have a get method.
My assumption is that you are using the acroform branch instead of the master branch. If so, may I ask how you built it or where you downloaded it from?

thank you.

**Comment by Hopding** [comment]
Hello @coler-j @AceLondon @EricDaviesRok! pdf-lib has a new forms API that makes this much simpler. Please see the [fill form](https://github.com/Hopding/pdf-lib#fill-form) example. You can find more info in the [README](https://github.com/Hopding/pdf-lib#creating-and-filling-forms) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform).
