### ISSUE TITLE
UI for drawing and text

### ISSUE THREAD

**Issue by rogeriocbrito** [Hopding/pdf-lib#527]
How can we have an UI so the user can actually draw (circles, rectangles, lines) on the PDF using the browser?
Click on the PDF to insert text?
Thanks

**Comment by Hopding** [comment]
Hello @rogeriocbrito! This library is solely a JavaScript API for creating, modifying, and filling PDF documents. To get what you’re describing, you would have to build something on top of pdf-lib. Perhaps using Mozilla’s `pdf.js` library for the rendering layer, and `pdf-lib` for the PDF editing layer.
