### ISSUE TITLE
Is it possible to add PDF namedActions such as Print?

### ISSUE THREAD

**Issue by avinash-sah24** [Hopding/pdf-lib#528]
I have been trying out a way to open Pdf print dialog when a pdf file is opened. I want to use PDF namedActions instead of javascript.
@Hopding Could you please help me.

**Comment by Hopding** [comment]
Hello @avinash-sah24! I'm not sure if it's even possible to use named actions to perform an action when a PDF file is opened. I don't know how to do this off the top of my head. I'd have to do some research to figure it out.

If you can share a document that exhibits this behavior, then I'd be happy to show you how to use `pdf-lib` to cause other documents to behave the same way.
