### ISSUE TITLE
Remove all annotations from pdf

### ISSUE THREAD

**Issue by cle1000** [Hopding/pdf-lib#529]
Hi, 

is there a way to delete all annotations from a pdf file?

Thanks!

Best Clemens

**Comment by vegarringdal** [comment]
```js
const { PDFDocument } = require("pdf-lib");
const fs = require("fs");

// use path if you need more advanced path..
const importFilename = "./test.pdf";
const exportFilename = "./test-annofree.pdf";

async function removeAnnots() {
  const uint8Array = fs.readFileSync(importFilename);
  const pdfDoc = await PDFDocument.load(uint8Array);
  const pages = pdfDoc.getPages();

  pages.forEach((page) => {
    const annots = page.node.Annots();
    const size = annots?.size();
    if (size) {
      for (let i = 0; i < size; i++) {
        annots.context.delete(annots.get(i));
      }
    }
  });

  const pdfBytes = await pdfDoc.save();
  fs.writeFileSync(exportFilename, pdfBytes);
}

removeAnnots();
console.log("annotations removed");
```

Looks like this works..
@Hopding  can tell us if this is doing something bad 😂

**Comment by cle1000** [comment]
Thank you! It works!

**Comment by Hopding** [comment]
@vegarringdal @cle1000 This approach looks fine to me 👍

**Comment by chislin** [comment]
On version `1.11.1` experiencing this error when calling `pdfDoc.getForm()` after `pdfDoc.load()`:

``` 
Error: Expected instance of PDFDict, but got instance of undefined
```

But if I remove `pdfDoc.getForm()` call, everything works as expected. Any ideas?

**Comment by JHarrisGTI** [comment]
This seems to have stopped working. When I do `annots.context` I get "Property 'context' is private and only accessible within class 'PDFArray'."

(I'm using TypeScript--I don't know if that's related?)

**Comment by Sharcoux** [comment]
@JHarrisGTI Just ignore the error

**Comment by jasrajk** [comment]
i'm also trying to remove the rectangle drawn to represent the link annotation or AP for the annotation. how can it be done. it only remove the context
