### ISSUE TITLE
Constructor of class 'PDFNumber' is private and only accessible within the class declaration.ts(2673)

### ISSUE THREAD

**Issue by vegarringdal** [Hopding/pdf-lib#530]
I get the error
`Constructor of class 'PDFNumber' is private and only accessible within the class declaration.ts(2673)`
When I use `new PDFNumber`

Guess this is the reason (pictuire below)
Does the constructor need to be private ?
Or is here another reason why Im geting this error?

![image](https://user-images.githubusercontent.com/2901416/87557796-a9023e00-c6b8-11ea-9e94-cdb2aab05c61.png)

**Comment by Hopding** [comment]
Hello @vegarringdal!

If you want to construct an instance of `PDFNumber`, please do either of the following:
```js
const pdfDoc = await PDFDocument.create();

// Use the `PDFNumber.of` factory method
const x = PDFNumber.of(21);

// Use the `PDFContext.obj` factory method
const y = pdfDoc.context.obj(21);
```
