### ISSUE TITLE
Add Example of Reading PDF Data

### ISSUE THREAD

**Issue by jbeuckm** [Hopding/pdf-lib#531]
I need an example of using the context / lookup functionality to find items in a PDF.

For example, if I write an SVG path to the PDF, how could I find that bit and read the path data back?

Maybe I just haven't found the example yet?

**Comment by punisher97** [comment]
Any solution?
I have same question, but search the solution you should create custom Form XObject, to handle and get this, maybe @Hopding help us

**Comment by Hopding** [comment]
Hello @jbeuckm!

The PDF specification does not actually support SVGs per se. It just defines a format for drawing vector graphics. When you draw an SVG path, pdf-lib converts the SVG path to the PDF vector format. See https://github.com/Hopding/pdf-lib/blob/master/src/api/svgPath.ts. This means that it would be difficult to read back out the SVG data once it has been embedded in the document. If you're curious, this is where the SVG embedding occurs: https://github.com/Hopding/pdf-lib/blob/11fe35cf22946af460baacd769a4d764604bd366/src/api/PDFPage.ts#L1166-L1181

I hope this helps! Please let me know if you have additional questions.

**Comment by jbeuckm** [comment]
Thanks! It looks like SVG might not be the way to do what I want. I need to write a bit of data (could be string) to the PDF - not in metadata - and read it back later.
