### ISSUE TITLE
How to write to file or render to iframe in the browser.

### ISSUE THREAD

**Issue by Bodata** [Hopding/pdf-lib#532]
Hallo,

In the code you state the following:
    
    // For example, `pdfBytes` can be:
    //   • Written to a file in Node
    //   • Downloaded from the browser
    //   • Rendered in an <iframe>

Of the download you made an example in jfiddle.

I tried the fs node module, but can not get it to work. ( I think this is because i am running code in the browser. )

Rendering to an iframe i have not found any clue how to do this.
Is there an example of this option ?

Regards,
Bo

**Comment by Bodata** [comment]
After another round of seaching if found a solution.
I have used PDFObject

    const pdfBytes = await pdfDoc.save();
    var blob = new Blob([pdfBytes], {type: "application/pdf"});
    var link = window.URL.createObjectURL(blob);

    window.PDFObject.embed(link, "#test_xx" );

This seems to work ;-)

Regards,
Bo

**Comment by moos** [comment]
For future reference, [PDFObject](https://pdfobject.com/) merely generates an `<embed>` tag and browser's native PDF renderer renders the PDF.  There is no API access to the rendered view.
