### ISSUE TITLE
Does PDF-LIB strip out Links & Scripts? Can it be made to do so?

### ISSUE THREAD

**Issue by TBXIHUB** [Hopding/pdf-lib#536]
If someone wanted to merge PDF data together from a potentially untrusted source, would it be possible to use PDF-LIB to only take an image+text layer copy of the document, rather than with links+scripts? I'm considering having to use a PDF to PNG layer with a later return back to PDF just to do this, but I'd much rather rely on one library to do so.

Perhaps the library already does this for simplicity?

Any tips in this regard would be much appreciated!

Thanks!

-TBXI

**Comment by Hopding** [comment]
Hello @TBXIHUB!

pdf-lib does not provide any special APIs for this. But it provides the all the low-level access necessary to implement it yourself. Please see these related issues: https://github.com/Hopding/pdf-lib/issues/206, https://github.com/Hopding/pdf-lib/issues/375.

I hope this helps!
