### ISSUE TITLE
Different binary for same pdf written multiple times makes regression testing more intensive

### ISSUE THREAD

**Issue by trevtrich** [Hopding/pdf-lib#537]
When attempting to regression test pdfs it's nice to be able to look at the binary data to see if anything has changed before attempting to do any more detailed diffing with other, slower, tools. We recently started using pdf-lib to modify our pdfs (excellent work, BTW. it's a great tool) and realized that even when reading and writing the same pdf multiple times, the binaries differ between the two. I did some digging into the content and didn't see any clear path to do something like "ignore header bytes" or something similar. Is there any chance an easy update could be done so that the same pdf written multiple times produces the same binary?

**Comment by Hopding** [comment]
Hello @trevtrich!

By default, when a `PDFDocument` is loaded (or created) its modification date is updated to the current time:

https://github.com/Hopding/pdf-lib/blob/a118cd4cfa1e54622c605385aec34095e79095e9/src/api/PDFDocument.ts#L205

https://github.com/Hopding/pdf-lib/blob/a118cd4cfa1e54622c605385aec34095e79095e9/src/api/PDFDocument.ts#L1160-L1171

This is probably the reason for your binary output being different. However, you can tell `pdf-lib` not to update this metadata by setting the [`updateMetadata`](https://pdf-lib.js.org/docs/api/interfaces/loadoptions#optional-updatemetadata) option to `false`:

```js
const pdfDoc = await PDFDocument.load(..., { updateMetadata: false });
```

This will make the result of `pdfDoc.save()` entirely deterministic based on the input PDF provided and any operations you might have performed after loading it. 

Here's an example script showing how the output of `pdfDoc.save()` is different if you wait one second between loading two documents.

```js
import { PDFDocument } from 'pdf-lib';

const arraysAreEqual = (a: Uint8Array, b: Uint8Array) => {
  if (a.length !== b.length) return false;
  for (let idx = 0, len = a.length; idx < len; idx++) {
    if (a[idx] !== b[idx]) return false;
  }
  return true;
};

const sleep = (millis: number) =>
  new Promise((resolve) => setTimeout(resolve, millis));

(async () => {
  const inputBytes = await fetch(
    'https://pdf-lib.js.org/assets/normal.pdf',
  ).then((res) => res.arrayBuffer());

  const pdfDoc1 = await PDFDocument.load(inputBytes);
  const pdfBytes1 = await pdfDoc1.save();

  await sleep(1000);

  const pdfDoc2 = await PDFDocument.load(inputBytes);
  const pdfBytes2 = await pdfDoc2.save();

  console.log('pdfBytes1 === pdfBytes2:', arraysAreEqual(pdfBytes1, pdfBytes2));
})();

// => pdfBytes1 === pdfBytes2: false
```

But if we change this script to set `updateMetadata: false`, you'll see that the output is identical:

```js
(async () => {
  const inputBytes = await fetch(
    'https://pdf-lib.js.org/assets/normal.pdf',
  ).then((res) => res.arrayBuffer());

  const pdfDoc1 = await PDFDocument.load(inputBytes, { updateMetadata: false });
  const pdfBytes1 = await pdfDoc1.save();

  await sleep(1000);

  const pdfDoc2 = await PDFDocument.load(inputBytes, { updateMetadata: false });
  const pdfBytes2 = await pdfDoc2.save();

  console.log('pdfBytes1 === pdfBytes2:', arraysAreEqual(pdfBytes1, pdfBytes2));
})();

// => pdfBytes1 === pdfBytes2: true
```

I hope this helps!

**Comment by trevtrich** [comment]
This is perfect! Thanks!

**Comment by trevtrich** [comment]
I was able to reproduce your case above and work from there to debug ours when I realized that our binaries were still differing with the `updateMetadata` flag turned off. It appears that embedding a font is also causing our  binaries to be different each time. Is there any similar options I can use for handling diffs that result from embedding a font? I did some digging through the docs and did not see any.

**Comment by Hopding** [comment]
@trevtrich Are you embedding a custom font or a standard one?

**Comment by trevtrich** [comment]
This is a custom font loaded from file bytes.

**Comment by trevtrich** [comment]
In doing some digging here, it appears that the embed font method eventually calls https://github.com/Hopding/pdf-lib/blob/a5fca7932c230d4ecc58db5be40e3615b826f3d3/src/utils/strings.ts#L34-L35, which might be the culprit in our case.

**Comment by Hopding** [comment]
@trevtrich That does seem likely to be the cause (or at least one of them). The first solution that comes to mind is seeding the RNG, but JavaScript doesn’t support that for `Math.random()`.

**Comment by Hopding** [comment]
Or perhaps the API could allow users to optionally specify their own name and thereby avoid the RNG entirely

**Comment by trevtrich** [comment]
We're going to fork and test a few things locally. If that doesn't turn into a rabbit hole of other binary-diffs, I'll put together a PR if you'd be open to it.

**Comment by Hopding** [comment]
@trevtrich Sounds good to me! If you decide to open a PR, please be sure to read https://github.com/Hopding/pdf-lib/blob/master/CONTRIBUTING.md. And if you find it necessary to add dependencies or make significant/sweeping changes, it'd be good to discuss your approach first.
