### ISSUE TITLE
Auto Field Creator/Labeling (Question/Request)

### ISSUE THREAD

**Issue by acg-thp** [Hopding/pdf-lib#539]
Does pdf-lib or any other software that is open source have the ability to auto detect were fields should be placed in a pdf and auto place them and label them?

I cannot use templates as for the application I am developing this for the data comes in dynamically (Varrying number of rows and checkboxes, varying questions on certain pages etc)

I started to develop a webserver that can fill the PDF AFTER adobes auto field generator is run, but its a bit clunky at times and labels things in ways that are hard to use without remapping values.

**Comment by Hopding** [comment]
Hello @acg-thp! Are you asking if pdf-lib can fill in PDF interactive form fields (text fields, check boxes, radio groups, etc...)?

**Comment by acg-thp** [comment]
I am asking if it can auto generate the fields and labels on a pdf with do
fields defined.

Currently we receive paperwork with checkboxs and such but they are not
actually marked as a field. And its dynamically coming in so some forms
varry in how many check boxes, fields, etc and were they are on the page
changes (so templating it out isn't really possible without a bunch of
extra leg work)

Adobe acrobat has a auto field generating feature but it lacks proper
labeling given how the pdfs come in from the system we receive the pdfs
from.

**Comment by Hopding** [comment]
Ah, I see. I'm afraid pdf-lib can't do this. Not aware of any software that can either (though I haven't looked).

**Comment by acg-thp** [comment]
Thank you for the response. The only software at the moment that I have found that does this is Adobe (And honestly the labeling of the auto generated fields is almost unusable if your forms are dynamically changing)

My boss is probably going to have me work on a project that can do this so I will go ahead and link it to this project once I have something functional.

**Comment by Hopding** [comment]
@acg-thp Sounds like an interesting project. Good luck! Please do share a link if you’re able to get something working.
