### ISSUE TITLE
Modify PDF to 1.3% or 1.5%

### ISSUE THREAD

**Issue by hmpvillegas** [Hopding/pdf-lib#541]
Kudos to the team who make this PDF modify function in which most developers used this until today for modification process.
Since after saving the PDF from modify, the version of the PDF is 1.7% which is the latest, my question is, can i degrade the modify pdf to 1.3% or 1.5% ? My load pdf is version 1.3% upon using load pdf function , it converts to the latest, i want to use the 1.3% in order to apply digital signaute.

**Comment by Hopding** [comment]
Hello @hmpvillegas!

pdf-lib does not provide any special APIs to downgrade or change the output PDF version. It's not clear to me exactly why you need version `1.3`, as `1.7` supports digital signatures as well. However, one of the main issues people have with `1.7` is its use of object streams in the output PDF. Some PDF tools have trouble dealing with them. You can turn them off by setting [`useObjectStreams`](https://pdf-lib.js.org/docs/api/interfaces/saveoptions#optional-useobjectstreams) to `false`:
```js
const pdfBytes = await pdfDoc.save({ useObjectStreams: false });
```

**Comment by RichardBray** [comment]
This is the exact problem I had, thought I had to downgrade but your solution worked @hmpvillegas thanks man 👍
