### ISSUE TITLE
Better support for SVG text

### ISSUE THREAD

**Issue by dleric** [Hopding/pdf-lib#546]
I wanted to get info if you plan to make better support for SVG text - I'm primarily interested in stretching/squeezing text to fit the container and putting a text on a path.

If you have it on the roadmap, do you have a rough estimate when it could be available. If not, I would be interested in contribution.

A general support for SVG graphics would be useful. Maybe there's an easy way to allow uploading SVG files (the same way as it's possible to upload and merge existing PDF files)?

**Comment by Hopding** [comment]
Hello @dleric!

This functionality is certainly possible to implement and I would love to have it in the library. I think @taxilian might have started working on porting [SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit) into `pdf-lib`. I think he's pressed for time, so you may be able to help him. Perhaps he can provide some details on his progress with this?

**Comment by taxilian** [comment]
I am indeed working on it, but it keeps getting shoved back unfortunately :-( My plan was to port it to typescript which is about 50% done and then abstract it to work with either PDFKit or pdf-lib.

**Comment by dleric** [comment]
@Hopding Great to hear that! Your library is definitely the most powerful out there and on the whole different level - I believe I tried all other PDF plugins, but yours is the most comprehensive.

@taxilian Let me know if I could help you anyhow.

**Comment by Hopding** [comment]
@taxilian Do you happen to have the work you've done on a branch or repo somewhere?

@dleric To help bring you up to speed, here's a link to some info about porting `SVG-to-PDFKit` to `pdf-lib`: https://discordapp.com/channels/726544376008015922/726544376008015925/727897748111753650

**Comment by Hopding** [comment]
@taxilian Just wanted to poke you about this. Have you done enough work on this that it makes sense for @dleric to pickup where you've left off? Or do you think it would be better to start from scratch with `SVG-to-PDFKit` as a reference?

**Comment by Hopding** [comment]
@dleric If you're still interested in working on this, it might be best to start fresh. As mentioned above, I'd suggest using [`SVG-to-PDFKit`](https://github.com/alafr/SVG-to-PDFKit) as a reference. It should provide a decent example of parsing SVGs and converting them to PDF primitives. Of course, it is not written in TypeScript and is designed to interface with [`pdfkit`](https://github.com/foliojs/pdfkit) APIs. So most of the work would be porting/rewriting it in TypeScript and implementing it with `pdf-lib` APIs. You may wish to look at the source code for [`PDFPage.drawSvgPath`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawsvgpath) to get an understanding of what it looks like to convert SVG path primitives to PDF vector graphics primitives: https://github.com/Hopding/pdf-lib/blob/master/src/api/svgPath.ts.

Please let me know if you have any questions!
