### ISSUE TITLE
Space issue in Embedding Hindi (Mangal Based) Font

### ISSUE THREAD

**Issue by aashutoshrathi** [Hopding/pdf-lib#549]
### Code used to embed the font

```js
const ourFont = await fetch(path_to_font).then((res) => res.arrayBuffer())
pdfDoc.registerFontkit(fontkit)
const font = await pdfDoc.embedFont(ourFont)
```

### Results 
| In Generated PDF | In Word |
|---|---|
| ![image](https://user-images.githubusercontent.com/21199234/89267036-53380a80-d654-11ea-90e5-295e8f1caa6b.png) | ![image](https://user-images.githubusercontent.com/21199234/89267058-5b904580-d654-11ea-97ad-feb9bbc96dab.png) |

There is unwanted space in half-characters with Mangal type fonts, the meanwhile same font works perfectly in MS Word, Is there something I'm missing while embedding this font?
Thanks in Advance.

**Comment by aashutoshrathi** [comment]
I was able to fix this by adding `{subset: true}` while embedding font.

**Comment by ShivamJoker** [comment]
They should mention this in docs somewere.

**Comment by kancherish** [comment]
@aashutoshrathi  @ShivamJoker  @duffyd  @DkDavid  @multiplegeorges 
> I was able to fix this by adding `{subset: true}` while embedding font.

can you tell me which font are you using , done same but couldnt solve the issue
