### ISSUE TITLE
Add metadata

### ISSUE THREAD

**Issue by erjimmmy** [Hopding/pdf-lib#55]
Hello,

Is it possible to add metadata to the PDF?

Thanks!

**Comment by Hopding** [comment]
Hello @erjimmmy. You can add metadata to PDFs with `pdf-lib`. There isn't currently a nice high level API for it, though. So the code is a bit ugly, but it works nonetheless!

(Note that PDFs store metadata in [XMP](https://en.wikipedia.org/wiki/Extensible_Metadata_Platform) format. The [XMP standard](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/xmp/pdfs/XMP%20SDK%20Release%20cc-2016-08/XMPSpecificationPart1.pdf) supports a wide variety of options, and even allows you to add your own custom tags.)

Here's a snippet that creates a PDF and adds metadata to it with a couple details omitted for brevity:
```js
...

const addMetadataToDoc = (pdfDoc, options) => {
  const metadataXML = `
    <?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
      <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.2-c001 63.139439, 2010/09/27-13:37:26        ">
        <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

          <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
            <dc:format>application/pdf</dc:format>
            <dc:creator>
              <rdf:Seq>
                <rdf:li>${options.author}</rdf:li>
              </rdf:Seq>
            </dc:creator>
            <dc:title>
               <rdf:Alt>
                  <rdf:li xml:lang="x-default">${options.title}</rdf:li>
               </rdf:Alt>
            </dc:title>
            <dc:subject>
              <rdf:Bag>
                ${options.keywords
                  .map((keyword) => `<rdf:li>${keyword}</rdf:li>`)
                  .join('\n')}
              </rdf:Bag>
            </dc:subject>
          </rdf:Description>

          <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
            <xmp:CreatorTool>${options.creatorTool}</xmp:CreatorTool>
            <xmp:CreateDate>${options.documentCreationDate.toISOString()}</xmp:CreateDate>
            <xmp:ModifyDate>${options.documentModificationDate.toISOString()}</xmp:ModifyDate>
            <xmp:MetadataDate>${options.metadataModificationDate.toISOString()}</xmp:MetadataDate>
          </rdf:Description>

          <rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
            <pdf:Subject>${options.subject}</pdf:Subject>
            <pdf:Producer>${options.producer}</pdf:Producer>
          </rdf:Description>

        </rdf:RDF>
      </x:xmpmeta>
      ${whitespacePadding}
    <?xpacket end="w"?>
  `.trim();

  const metadataStreamDict = PDFDictionary.from(
    {
      Type: PDFName.from('Metadata'),
      Subtype: PDFName.from('XML'),
      Length: PDFNumber.fromNumber(metadataXML.length),
    },
    pdfDoc.index,
  );

  const metadataStream = PDFRawStream.from(
    metadataStreamDict,
    typedArrayFor(metadataXML),
  );

  const metadataStreamRef = pdfDoc.register(metadataStream);

  pdfDoc.catalog.set('Metadata', metadataStreamRef);
};

const pdfDoc = PDFDocumentFactory.create();
const [TimesRomanFont] = pdfDoc.embedStandardFont('Times-Roman');
const [HelveticaFont] = pdfDoc.embedStandardFont('Helvetica');

const contentStream = pdfDoc.createContentStream( ... );

const page = pdfDoc
  .createPage([500, 600])
  .addFontDictionary('Helvetica', HelveticaFont)
  .addFontDictionary('TimesRoman', TimesRomanFont)
  .addContentStreams(pdfDoc.register(contentStream));

pdfDoc.addPage(page);

addMetadataToDoc(pdfDoc, {
  author: 'Humpty Dumpty',
  title: 'The Life of an Egg',
  subject: 'An Epic Tale of Woe',
  keywords: ['eggs', 'wall', 'fall', 'king', 'horses', 'men'],
  producer: `Your App's Name Goes Here`,
  creatorTool:
    'pdf-lib pdf-lib_version_goes_here (https://github.com/Hopding/pdf-lib)',
  documentCreationDate: new Date(),
  documentModificationDate: new Date(),
  metadataModificationDate: new Date(),
});

const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
```

-----

* Here is the resulting PDF file: [the_life_of_an_egg.pdf](https://github.com/Hopding/pdf-lib/files/2686605/the_life_of_an_egg.pdf)
* And here is a screenshot of the resulting PDF in Acrobat, with the "File -> Properties" window opened:
![screen shot 2018-12-17 at 8 52 09 am](https://user-images.githubusercontent.com/10351828/50095408-18613480-01db-11e9-921e-4555ed4286de.png)
* Finally, here is the complete Node.js script (the `.txt` extension is to make GitHub happy): [humpty_dumpty.js.txt](https://github.com/Hopding/pdf-lib/files/2686608/humpty_dumpty.js.txt) 

Please let me know if this is what you're looking for!

**Comment by erjimmmy** [comment]
Thanks @Hopding!! It works! You are very kind! :)

**Comment by Hopding** [comment]
Great! I'm glad it's working for you 👍

**Comment by jaserma** [comment]
Hello @Hopding, 

I edit a PDF, I add a signature to the document and I would like to add metadata. It's an Ionic project and I generate the pdf without problems, but when I try to add metadata I don't get my goal, the fields are empty. The output of the following code is "x: undefinied".
`let x = addMetadataToDoc (pdfDoc, {
       author: 'Humpty Dumpty',
       title: 'The Life of an Egg',
       subject: 'An Epic Tale of Woe',
       keywords: ['eggs', 'wall', 'fall', 'king', 'horses', 'men'],
       producer: `Your App's Name Goes Here`,
       creatorTool:
         'pdf-lib pdf-lib_version_goes_here (https://github.com/Hopding/pdf-lib)',
       documentCreationDate: new Date (),
       documentModificationDate: new Date (),
       metadataModificationDate: new Date (),
     });
     console.log ('x:' + x) `

Can you help me?
Thanks!

**Comment by Hopding** [comment]
Hello @jaserma. 

The `addMetadataToDoc()` function (defined in [this script](https://github.com/Hopding/pdf-lib/files/2686608/humpty_dumpty.js.txt)) does not return anything. Instead of returning an object that you have to add to the `pdfDoc` yourself, it just adds the metadata to the `pdfDoc` that you pass in. So the `x: undefined` that you are seeing looks correct.

When you open the resulting PDF in a reader, are you able to see the metadata?

**Comment by jaserma** [comment]
Hi @Hopding,

I have tried to create the document as your example, but the fields are empty:
<img width="1437" alt="captura de pantalla 2019-01-04 a las 23 02 54" src="https://user-images.githubusercontent.com/46374287/50713389-1ae5da00-1075-11e9-9fc7-c25afe1396f1.png">

I have created a function to add a signature to the document:
```
editPdf(data: any, image: any, iso: any): any{
    const {
      PDFDictionary,
      PDFDocumentFactory,
      PDFDocumentWriter,
      PDFName,
      PDFNumber,
      PDFRawStream,
      drawImage,
    } = require('pdf-lib');
    const charCodes = (str) => str.split('').map((c) => c.charCodeAt(0));
    const typedArrayFor = (str) => new Uint8Array(charCodes(str));
    const whitespacePadding = new Array(20).fill(' '.repeat(100)).join('\n');
    const addMetadataToDoc = (pdfDoc, options) => {
      const metadataXML = `
        <?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
          <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.2-c001 63.139439, 2010/09/27-13:37:26        ">
            <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    
              <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
                <dc:format>application/pdf</dc:format>
                <dc:creator>
                  <rdf:Seq>
                    <rdf:li>${options.author}</rdf:li>
                  </rdf:Seq>
                </dc:creator>
                <dc:title>
                   <rdf:Alt>
                      <rdf:li xml:lang="x-default">${options.title}</rdf:li>
                   </rdf:Alt>
                </dc:title>
                <dc:subject>
                  <rdf:Bag>
                    ${options.keywords
                      .map((keyword) => `<rdf:li>${keyword}</rdf:li>`)
                      .join('\n')}
                  </rdf:Bag>
                </dc:subject>
              </rdf:Description>
    
              <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
                <xmp:CreatorTool>${options.creatorTool}</xmp:CreatorTool>
                <xmp:CreateDate>${options.documentCreationDate.toISOString()}</xmp:CreateDate>
                <xmp:ModifyDate>${options.documentModificationDate.toISOString()}</xmp:ModifyDate>
                <xmp:MetadataDate>${options.metadataModificationDate.toISOString()}</xmp:MetadataDate>
              </rdf:Description>
    
              <rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
                <pdf:Subject>${options.subject}</pdf:Subject>
                <pdf:Producer>${options.producer}</pdf:Producer>
              </rdf:Description>
    
            </rdf:RDF>
          </x:xmpmeta>
          ${whitespacePadding}
        <?xpacket end="w"?>
      `.trim();
    
      const metadataStreamDict = PDFDictionary.from(
        {
          Type: PDFName.from('Metadata'),
          Subtype: PDFName.from('XML'),
          Length: PDFNumber.fromNumber(metadataXML.length),
        },
        pdfDoc.index,
      );
    
      const metadataStream = PDFRawStream.from(
        metadataStreamDict,
        typedArrayFor(metadataXML),
      );
    
      const metadataStreamRef = pdfDoc.register(metadataStream);
    
      pdfDoc.catalog.set('Metadata', metadataStreamRef);
    };
    // End Add metadata

    let res = new RespuestaModel(data);
    let existingPdfDocBytes = this.toUint8Array(res.Res.Datos)

    const pdfDoc = PDFDocumentFactory.load(existingPdfDocBytes);
    const pages = pdfDoc.getPages();

    // Add signature
    const page  = pages[0];
    const [pngImage, pngDims] = pdfDoc.embedPNG(image);
    const contentStream = pdfDoc.createContentStream(
      drawImage('MySignature', {
        x: 300,
        y: 0,
        width: pngDims.width * 0.5,
        height: pngDims.height * 0.5,
      }),
    );

    // Create PDF with signature
    page.addContentStreams(pdfDoc.register(contentStream)).addImageObject('MySignature', pngImage);

// Add values to metadata
    addMetadataToDoc(pdfDoc, {
      author: 'Humpty Dumpty',
      title: 'The Life of an Egg',
      subject: 'An Epic Tale of Woe',
      keywords: ['eggs', 'wall', 'fall', 'king', 'horses', 'men'],
      producer: `Your App's Name Goes Here`,
      creatorTool:
        'pdf-lib pdf-lib_version_goes_here (https://github.com/Hopding/pdf-lib)',
      documentCreationDate: new Date(),
      documentModificationDate: new Date(),
      metadataModificationDate: new Date(),
    });

    const pdfBytes = PDFDocumentWriter.saveToBytes(pdfDoc);
    return pdfBytes;
  }

**Comment by Hopding** [comment]
@jaserma I'm wondering if this is an issue specific to Foxit's Reader. 
* What version of Foxit Reader are you using? 
* Can you view the metadata if you open the PDF in another reader, such as Acrobat?
* Would you please upload the specific file you're working with, just in case it's somehow different from the one generated by the example script?

**Comment by jaserma** [comment]
Hi @Hopding ,

You're right. In Acrobat Reader I can see the metadata. The strange thing is that in Foxit Reader I can see metadata of another documents (not generated with the library), but it doesn't matter, your method works well.

Thank you very much for your help.

**Comment by yltlatl** [comment]
Hello @Hopding ,

It looks like most of the classes used for the adding metadata code are no longer exported post-1.0.0. Is there still a way to add the metadata in the current version?

Thanks,
AG

**Comment by Hopding** [comment]
Hello @yltlatl! Here's an updated version of the script for post-1.0.0: [humpty_dumpty.js.txt](https://github.com/Hopding/pdf-lib/files/3569518/humpty_dumpty.js.txt)

Here are the key parts of the script so you can look at it without downloading the file:

```js
const addMetadataToDoc = (pdfDoc, options) => {
  const metadataXML = `
    <?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
      <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.2-c001 63.139439, 2010/09/27-13:37:26        ">
        <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">

          <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/">
            <dc:format>application/pdf</dc:format>
            <dc:creator>
              <rdf:Seq>
                <rdf:li>${options.author}</rdf:li>
              </rdf:Seq>
            </dc:creator>
            <dc:title>
               <rdf:Alt>
                  <rdf:li xml:lang="x-default">${options.title}</rdf:li>
               </rdf:Alt>
            </dc:title>
            <dc:subject>
              <rdf:Bag>
                ${options.keywords
                  .map(keyword => `<rdf:li>${keyword}</rdf:li>`)
                  .join('\n')}
              </rdf:Bag>
            </dc:subject>
          </rdf:Description>

          <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
            <xmp:CreatorTool>${options.creatorTool}</xmp:CreatorTool>
            <xmp:CreateDate>${options.documentCreationDate.toISOString()}</xmp:CreateDate>
            <xmp:ModifyDate>${options.documentModificationDate.toISOString()}</xmp:ModifyDate>
            <xmp:MetadataDate>${options.metadataModificationDate.toISOString()}</xmp:MetadataDate>
          </rdf:Description>

          <rdf:Description rdf:about="" xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
            <pdf:Subject>${options.subject}</pdf:Subject>
            <pdf:Producer>${options.producer}</pdf:Producer>
          </rdf:Description>

        </rdf:RDF>
      </x:xmpmeta>
      ${whitespacePadding}
    <?xpacket end="w"?>
  `.trim();

  const metadataStream = pdfDoc.context.stream(metadataXML, {
    Type: 'Metadata',
    Subtype: 'XML',
    Length: metadataXML.length,
  });

  const metadataStreamRef = pdfDoc.context.register(metadataStream);

  pdfDoc.catalog.set(PDFName.of('Metadata'), metadataStreamRef);
};

const pdfDoc = await PDFDocument.create();

const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman);
const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

const page = pdfDoc.addPage([500, 600]);

page.setFont(timesRomanFont);
page.drawText('The Life of an Egg', { x: 60, y: 500, size: 50 });
page.drawText('An Epic Tale of Woe', { x: 125, y: 460, size: 25 });

page.setFont(helveticaFont);
page.drawText(
  [
    'Humpty Dumpty sat on a wall',
    'Humpty Dumpty had a great fall;',
    `All the king's horses and all the king's men`,
    `Couldn't put Humpty together again.`,
  ].join('\n'),
  { x: 75, y: 275, size: 20, lineHeight: 25 },
);
page.drawText('- Humpty Dumpty', { x: 250, y: 150, size: 20 });

addMetadataToDoc(pdfDoc, {
  author: 'Humpty Dumpty',
  title: 'The Life of an Egg',
  subject: 'An Epic Tale of Woe',
  keywords: ['eggs', 'wall', 'fall', 'king', 'horses', 'men'],
  producer: `Your App's Name Goes Here`,
  creatorTool:
    'pdf-lib pdf-lib_version_goes_here (https://github.com/Hopding/pdf-lib)',
  documentCreationDate: new Date(),
  documentModificationDate: new Date(),
  metadataModificationDate: new Date(),
});

const pdfBytes = await pdfDoc.save();
```

**Comment by yltlatl** [comment]
That's awesome, thank you @Hopding ! Simpler than the older version. I will try it out.

**Comment by Hopding** [comment]
Version [`1.2.0`](https://www.npmjs.com/package/pdf-lib/v/1.2.0) is now published. 

It contains several new methods on `PDFDocument` to easily add metadata to documents:
  * `PDFDocument.setTitle(string)`
  * `PDFDocument.setAuthor(string)`
  * `PDFDocument.setSubject(string)`
  * `PDFDocument.setKeywords(string[])`
  * `PDFDocument.setProducer(string)`
  * `PDFDocument.setCreator(string)`
  * `PDFDocument.setCreationDate(Date)`
  * `PDFDocument.setModificationDate(Date)`

The full release notes are available [here](https://github.com/Hopding/pdf-lib/releases/tag/v1.2.0).

You can install this new version with npm:
```
npm install pdf-lib@1.2.0
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@1.2.0/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@1.2.0/dist/pdf-lib.min.js

**Comment by nokome** [comment]
Heya :wave:. Thanks for `pdf-lib!' :clap: 

Small question. What is the purpose of `${whitespacePadding}` in the above script?

**Comment by Hopding** [comment]
Hello @nokome. The whitespace padding is recommended by the PDF spec so that additional metadata can be added later without having to change the byte offset of other objects in the document. 

However, I would suggest that you shy away from the XMP metadata approach used in the snippets in this thread. The metadata methods on `PDFDocument` use a more widely supported format (plain PDF objects). I would recommend using only those methods to set metadata on documents, as the resulting metadata will be visible in almost all PDF readers. Whereas the XMP approach seems to only be supported by Acrobat Reader.

**Comment by nokome** [comment]
Thanks for the detailed answer @Hopding. 

We are using already using `setAuthor`, `setTitle` etc but need to add additional custom XML metadata so XMP is the best fit for that.

Slightly off topic but what is the best way to read the "Info Dict" metadata. Currently, I'm resorting to this:

```ts
  // @ts-ignore that getInfoDict is private
  const info = pdf.getInfoDict()
  const title = info.get(PDFName.of('Title')).toString()
```

**Comment by Hopding** [comment]
@nokome What you are doing is probably the best way at the moment. There are currently no special methods built for reading values out of the Info dict. `getInfoDict` probably doesn't really need to be private either. The rationale for labeling it as such was that dedicated read methods would be preferable, so users shouldn't need to access the Info dict directly.

**Comment by timKraeuter** [comment]
@Hopding  Hi, I really like the pdf-lib you have created. Especially the functions to modify the pdf metadata.

I'm trying to read the pdf metadata fields in another javascript/typescript application. You encode the strings with `PDFHexString.fromText(title)` (UTF16 or something?). I was wondering how I can decode the values. I'm reading them as @nokome pointed out. I really am a pdf noob, so thanks in advance for the help.

Having appropriate read methods would be a great feature. But if you could point out a solution that would also be helpful.

**Comment by Hopding** [comment]
Hello @timKraeuter! I agree that having getter methods would be useful. Feel free to open a feature request for this.

As you noticed, the text is encoded in UTF-16 and stored in a hex string. I'm afraid I don't have time at the moment to create a working example, but decoding the hex strings involves the following steps:
1. Extract the hex string.
2. Convert it to an array of numbers (or a typed array). Note that each pair of hex digits in the string constitutes a single byte of data.
3. Convert the array from (2) to a `string` object. `pdf-lib` only contains functions for utf8/16 _encoding_ (https://github.com/Hopding/pdf-lib/blob/master/src/utils/unicode.ts). It provides nothing for _decoding_. You can implement the decoding algorithm yourself if you feel adventurous. Otherwise there are probably some libraries for it (e.g. [`utfx`](https://github.com/dcodeIO/utfx)). Or you could try this implementation: https://gist.github.com/also/912792.

**Comment by timKraeuter** [comment]
Hello @Hopding sounds great thanks! I will try to implement it later when i get back to my computer and inform you if i need further help.

**Comment by timKraeuter** [comment]
I had time yesterday and managed to read the metadata as wanted. Thanks for the step by step explanation on how to do it.
I used the following code to read the Keywords field from a pdf.

```typescript
private readKeywords(pdfDocument: PDFDocument): string {
        // @ts-ignore that getInfoDict is private
        const info = pdfDocument.getInfoDict();
        let keywords: string = info.get(PDFName.of('Keywords')).toString();
        // Extract hex value
        keywords = keywords.substr(keywords.indexOf('<') + 1, keywords.lastIndexOf('>') - 1);

        const bytes: number[] = [];

        // ignore bom for the string output
        keywords = keywords.substr(4);
        while (keywords.length > 1) {
            const nextTwoDigits = keywords.substr(0, 2);
            // Get the first two digits
            keywords = keywords.substr(2);

            // Ignore whitespaces
            if (nextTwoDigits === '00') {
                continue;
            }

            // Hex is base 16
            bytes.push(parseInt(nextTwoDigits, 16));
        }
        return new TextDecoder('UTF-16').decode(new Uint16Array(bytes));
    }
```

I plan to open a Pull-Request with a generalized version of this example code (so we have getters for the metadata fields we now only have setters for). But I don't really have time till the end of February.
I have also tried https://gist.github.com/also/912792 instead of the TextDecoder. It also works fine.

**Comment by timKraeuter** [comment]
I added a pull request with cleaned up code see https://github.com/Hopding/pdf-lib/pull/336.

**Comment by tbelch-at-eHealth-Tec** [comment]
Hi @Hopding thank you for your example here. My issue: it seems like the module `PDFDictionary` isn't part of pdf-lib anymore. There is a `PDFDict` but it doesn't provide a `from` method, as used in your example.

Could you please update your example according to the changed API?

Best regards,
Tobias

**Comment by bhsiaoNFLX** [comment]
@Hopding  I followed your post-1.0.0: humpty_dumpty.js example, then added a custom XMP tag `xmp:Foo`:
```
           ...
          <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
            ...
            <xmp:MetadataDate>${options.metadataModificationDate.toISOString()}</xmp:MetadataDate>
            <xmp:Foo>Bar</xmp:Foo> <-- added this
          </rdf:Description>
          ...
```
Then ran the script. Using `exiftool` cli, I can confirm my custom tag is correctly written:
```
)> exiftool -j -g -all -xmp -b new.pdf | jq '.[0].XMP.Foo'
"Bar"
```

Q: Now how do I do the same exact thing of extract the value in js? `getInfoDict` doesn't seem to work for me as it only exposes `Producer`, `ModDate`, `Creator`, `CreationDate`
![see screenshot](https://user-images.githubusercontent.com/54922075/103019945-77f62700-44fc-11eb-91ab-38d577077686.png). I'm using the same code has @nokome above. 

Also, @nokome could you share your minimal example? What I have:

```
const info = pdf.getInfoDict()

```
yields
'<FEFF007000640066002D006C006900620020002800680074007400700073003A002F002F006700690074006800750062002E0063006F006D002F0048006F007000640069006E0067002F007000640066002D006C006900620029>'

but
```
info.get(PDFName.of('Producer')) // yields `{ value: "FEFF007000640066002D006C006900620020002800680074007400700073003A002F002F006700690074006800750062002E0063006F006D002F0048006F007000640069006E0067002F007000640066002D006C006900620029"}`
info.get(PDFName.of('Foo')) // yields `undefined`
```

**Comment by AnthonyLevillon** [comment]
Hi @Hopding , Thanks for the great work.

If anyone need to add custom metadata, as a temporary fix, even if getInfoDict function is private, I was able to add custom metadata like so:

`pdfDoc['getInfoDict']().set(PDFName.of('fooMetadata'), PDFHexString.fromText('FooMetadataValue'));`

**Comment by imkazebui** [comment]
pdfDoc['getInfoDict']().set(PDFName.of('fooMetadata'), PDFHexString.fromText('FooMetadataValue'));

it works for me. Thank you very much

**Comment by obrunofontana** [comment]
> pdfDoc'getInfoDict'.set(PDFName.of('fooMetadata'), PDFHexString.fromText('FooMetadataValue'));
> 
> it works for me. Thank you very much

it work for me to, but I can't read the property after adding it. :(

**Comment by AnthonyLevillon** [comment]
> > pdfDoc'getInfoDict'.set(PDFName.of('fooMetadata'), PDFHexString.fromText('FooMetadataValue'));
> > it works for me. Thank you very much
> 
> it work for me to, but I can't read the property after adding it. :(

You can read it with the following code:

`pdfDoc['getInfoDict']().lookup(PDFName.of('FooMetadataValue'))`

**Comment by Al1st1c** [comment]
`pdfDoc['getInfoDict']().set(PDFName.of('fooMetadata'), PDFHexString.fromText('FooMetadataValue')); 
`
it works for me, thanks!!!!

**Comment by ghost** [comment]
To read values, use:
`pdfDoc.getInfoDict().get(PDFName.of('key'))?.decodeText();`

**Comment by lohiyalavarthi1** [comment]
How to set the metadata in this format

 const metadata =[
        { anotherKey1: "value1" },
        { anotherKey2: "value2" }
    ]

How to set this metadata for the pdf-lib?

**Comment by human211** [comment]
The options that were written above did not help in my case. Gotenberg creates a PDF with such a field:
`Directory: '/tmp/bc5165b4-fa30-4758-8012-d0ad07104afc/05614ac5-e441-4c03-ae75-d2c99533e5b7'`

I tried:
```
1. pdfDoc.catalog.set(PDFName.of('Directory'), PDFString.of('test'));
2. pdfDoc['getInfoDict']().set(PDFName.of('Directory'), PDFHexString.fromText('test'));
3. addMetadataToDoc //tried to insert directly to XML field Directory`
```
How can I change 'Directory' field or remove it? this prevents the same hash from being generated

**Comment by AnthonyLevillon** [comment]
> The options that were written above did not help in my case. Gotenberg creates a PDF with such a field: `Directory: '/tmp/bc5165b4-fa30-4758-8012-d0ad07104afc/05614ac5-e441-4c03-ae75-d2c99533e5b7'`
> 
> I tried:
> 
> ```
> 1. pdfDoc.catalog.set(PDFName.of('Directory'), PDFString.of('test'));
> 2. pdfDoc['getInfoDict']().set(PDFName.of('Directory'), PDFHexString.fromText('test'));
> 3. addMetadataToDoc //tried to insert directly to XML field Directory`
> ```
> 
> How can I change 'Directory' field or remove it? this prevents the same hash from being generated

I tried to ask ChatGPT and it seems to roughly do the same thing

https://chatgpt.com/share/43e12843-ad8d-4816-b28c-e925695ad35c

Are you sure that the /tmp is a metadata under the /Info dictionary?

**Comment by human211** [comment]
gotenberg has route for read metadata
`localhost:3000/forms/pdfengines/metadata/read`
and it gives me this result:

```
Asd: 'FooMetadataValue',
    Author: 'test',
    CreateDate: '2024:08:29 13:40:23.691Z',
    Creator: 'Humpty Dumpty',
    CreatorTool: 'pdf-lib pdf-lib_version_goes_here (https://github.com/Hopding/pdf-lib)',
    Directory: '/tmp/bc5165b4-fa30-4758-8012-d0ad07104afc/05614ac5-e441-4c03-ae75-d2c99533e5b7',
    ExifToolVersion: 12.57,
    FileAccessDate: '2024:08:29 13:40:24+00:00',
    FileInodeChangeDate: '2024:08:29 13:40:24+00:00',
    FileModifyDate: '2024:08:29 13:40:24+00:00',
    FileName: 'test.pdf',
    FilePermissions: '-rw-r--r--',
    FileSize: '85 kB',
    FileType: 'PDF',
    FileTypeExtension: 'pdf',
    Format: 'application/pdf',
    Keywords: 'test',
    Language: 'ru',
    Linearized: 'No',
    MIMEType: 'application/pdf',
    MetadataDate: '2024:08:29 13:40:23.691Z',
    ModifyDate: '2024:08:29 13:40:23.691Z',
    PDFVersion: 1.7,
    PageCount: 1,
    Producer: "Your App's Name Goes Here",
    SourceFile: '/tmp/bc5165b4-fa30-4758-8012-d0ad07104afc/05614ac5-e441-4c03-ae75-d2c99533e5b7/test.pdf',
    Subject: [ 'eggs', 'wall', 'fall', 'king', 'horses', 'men' ],
    Title: 'The Life of an Egg',
    XMPToolkit: 'Adobe XMP Core 5.2-c001 63.139439, 2010/09/27-13:37:26       
``` 

some fields were successfully rewritten, but the Directory field was not. 

> Are you sure that the /tmp is a metadata under the /Info dictionary?

How can I determine this? Deleting all metadata would help me, but I don't know how

**Comment by AnthonyLevillon** [comment]
I'm not 100% suer but I think that when you load the file in pdf-lib you can pass options and setting updateMetadata to true or false

```
await PDFDocument.load(buffer, {
      updateMetadata: true // Load the original PDF file by updating its existing metadata
})
```

Said that, there might be a way to start fresh but that would mean creating a blank pdf and add every page to it but not performance efficient for sure

**Comment by human211** [comment]
it seems the problem is in the **pdfdoc.catalog**.

if I copy the original pdf file then everything works as expected with the copy of the file (the hash is the same for several generations)
`const pdfDoc = await pdfDoc1.copy();`

I compared the pdfdoc.catalog of the original pdf and the copied one and
original has many items:
```
keys
[
  PDFName { encodedName: '/Type' },
  PDFName { encodedName: '/Pages' },
  PDFName { encodedName: '/OpenAction' },
  PDFName { encodedName: '/Outlines' },
  PDFName { encodedName: '/Lang' },
  PDFName { encodedName: '/Metadata' }
]
values
[
  PDFName { encodedName: '/Catalog' },
  PDFRef { objectNumber: 6, generationNumber: 0, tag: '6 0 R' },
  PDFArray {
    array: [ [PDFRef], [PDFName], PDFNull {}, PDFNull {}, [PDFNumber] ],
    context: PDFContext {
      largestObjectNumber: 34,
      header: [PDFHeader],
      trailerInfo: [Object],
      indirectObjects: [Map],
      rng: [SimpleRNG]
    }
  },
  PDFRef { objectNumber: 24, generationNumber: 0, tag: '24 0 R' },
  PDFString { value: 'ru-RU' },
  PDFRef { objectNumber: 34, generationNumber: 0, tag: '34 0 R' }
]
```
but copy has:
```
keys
[ PDFName { encodedName: '/Type' }, PDFName { encodedName: '/Pages' } ]
values
[
  PDFName { encodedName: '/Catalog' },
  PDFRef { objectNumber: 1, generationNumber: 0, tag: '1 0 R' }
]
```
Сan i just delete the extra items in original PDF? won't it break the PDF?
And if i can, what is the best way to do it?


UPD:
I also tried delete items from catalog
```
const catalog = pdfDoc.catalog;
catalog.delete(PDFName.of('OpenAction'));
catalog.delete(PDFName.of('Outlines'));
catalog.delete(PDFName.of('Lang'));
catalog.delete(PDFName.of('Metadata'));
```
but it didn't help- the hash changes after each generation

**Comment by liuzhaoxu1996** [comment]
> Hi [@Hopding](https://github.com/Hopding) , Thanks for the great work.
> 
> If anyone need to add custom metadata, as a temporary fix, even if getInfoDict function is private, I was able to add custom metadata like so:
> 
> `pdfDoc['getInfoDict']().set(PDFName.of('fooMetadata'), PDFHexString.fromText('FooMetadataValue'));`

it works for me, thanks!!!!
