### ISSUE TITLE
Is it possible to replace text and save pdf as new file?

### ISSUE THREAD

**Issue by techsin** [Hopding/pdf-lib#550]
1. open existing pdf file.
2. find all email addresses (or anything)
3. replace it with new email
4. save as a new file

Documentation seems to imply pdf-lib lets you write how html5 canvas lets you write. I don't want to write anywhere. I want to fill out the form. Also would be nice to get information about multiline, max length, etc..

My strategy was: 

1. Open file
2. Loop over all pages
3. Get all form fields that are of type text
4. Update the ones that match my filter
5. Save the file

But unless I'm wrong that is simply not possible.

**Comment by Hopding** [comment]
Hello @techsin!

Are you trying to read and write PDF form fields? Is there a sample document you could provide to help me understand what you're trying to do?

**Comment by techsin** [comment]
Let say you have 10 forms, and you have to fill out First Name and Last Name 10 times. So I'm trying to create base 10 forms and fill them out like $FirstName, $LastName, $DOBM, $DOBD, $DOBY, $Gender, .........etc. Then have my program read the fields, replace the text with data, and save it as a new form in output folder. So basically it's a form of Search and Replace.

**Comment by techsin** [comment]
@Hopding

**Comment by Hopding** [comment]
I think I understand what you are trying to do. So the functionality you're looking for from `pdf-lib` is the ability to read and edit PDF form fields?

**Comment by techsin** [comment]
yes, so something like `form.pages[0].fields.filter(x => fields.text.includes('$...'))`

**Comment by Hopding** [comment]
The current release of `pdf-lib` does not provide a high level API for form filling/reading. However, the [`AcroForms`](https://github.com/Hopding/pdf-lib/tree/AcroForms) branch has code that can do exactly this. Here's a link to one of the tests on that branch demoing the forms API: https://github.com/Hopding/pdf-lib/blob/AcroForms/apps/node/tests/test14.ts#L54. 

The code to accomplish what you are describing would look about like this:
```js
const pdfDoc = await PDFDocument.load(...);
const form = pdfDoc.getForm();
const fields = form.getFields();

const firstNameField = fields.find(field => field.getText().includes('$FirstName'));
firstNameField.setText('Hopding');

const genderField = fields.find(field => field.getText().includes('$Gender'));
genderField.setText('Male');

const pdfBytes = await pdfDoc.save();
```

It'll probably be a few more weeks until the code is fully documented and released in `master`. If you're interested in using it before then, I can cut a pre-release for you. Let me know if you're interested!

**Comment by techsin** [comment]
@Hopding oh no please don't bother, I can wait few weeks. But this is perfect. The api is very readable and easy to reason. While I'd keep checking back and see the status in month or so. Much appreciate all the work.

**Comment by ricky-sb** [comment]
>If you're interested in using it before then, I can cut a pre-release for you.  

If it's not too much trouble, would you mind setting up a pre-release for us? The API looks really neat and I wanted to play around with it

**Comment by Hopding** [comment]
@ricky-sb @techsin I've just cut a prerelease with this feature: [`v1.11.0-rc1`](https://www.npmjs.com/package/pdf-lib/v/1.11.0-rc1). Thoughts and feedback are appreciated!

**Comment by techsin** [comment]
Great, I'll get back.

**Comment by Hopding** [comment]
The form creation and filling APIs have been released. See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFTextField.setText`](https://pdf-lib.js.org/docs/api/classes/pdftextfield#settext) method is of particular relevance to this issue.

**Comment by techsin** [comment]
Magnificent. It's all magic to me. But I have been searching something like
this on and off for years.

**Comment by Hopding** [comment]
Hope it works for you! Any feedback you have would be appreciated.

**Comment by fabio-smu** [comment]
Hi! Can I find and replace a text (like $first_name) without be a form field, just a text  somewhere in the page?
thx
