### ISSUE TITLE
Is it possible to fill PDF textbox field with a check mark, or check a checkbox ? 

### ISSUE THREAD

**Issue by blocks-master** [Hopding/pdf-lib#551]
Hi I'm trying to dynamically fill a textbox with the "✓"  symbol but got the following error: 
WinAnsi cannot encode "✓". Fill fuction below where I put fieldnames.value as "\u2713"

```
const fillInField = (fieldName, text) => {
            const field = findAcroFieldByName(pdfDoc, fieldName)
            if (field) fillAcroTextField(field, text, helveticaFont)
        }


 for (var i = 0; i < fieldNames.length; i++) {
            fillInField(fieldNames[i].name, fieldNames[i].value);
}

```

I also tried putting a checkbox on the PDF , but what should I put as fieldNames.value to check that checkbox ? Possible ?

**Comment by Hopding** [comment]
@blocks-master Have you tried using `StandardFonts.ZapfDingbats` instead of `StandardFonts.Helvetica`?

**Comment by Hopding** [comment]
pdf-lib has a new form filling API that should take care of this for you. See the README and API docs for more details.
