### ISSUE TITLE
Unable to find way to add multiple links. 

### ISSUE THREAD

**Issue by FawadMahmood** [Hopding/pdf-lib#552]
Unable to find way to add multiple links. , When I add more than one link, only the last link I add appears.

**Comment by Hopding** [comment]
Hello @FawadMahmood!

Can you please share some sample code and documents to demonstrate what you are doing?

**Comment by FawadMahmood** [comment]
Hello, Thank you so much for you response, I need to add create summary page, that having links to multiple pages, but I am unable to add multiple links on one page, if I add new it replaces previous one. 

https://ibb.co/frNQtmD

Please have a look, each link drop user you specific page index.

**Comment by punisher97** [comment]
> Hello, Thank you so much for you response, I need to add create summary page, that having links to multiple pages, but I am unable to add multiple links on one page, if I add new it replaces previous one.
> 
> https://ibb.co/frNQtmD
> 
> Please have a look, each link drop user you specific page index.

I was same problem, its simply, you can check if annotation exists in this pages, and reuse PDFArray, example:

```typescript
  let annots: PDFArray;
  try {
    annots = page.node.lookup(Constants.Annots, PDFArray);
  } catch (error) {
    annots = pdfDoc.context.obj([]);
    page.node.set(PDFName.Annots, annots);
  }
....
annots.push(linkAnnotationRef);
```

**Comment by FawadMahmood** [comment]
Thank you so much brother for a quick response, I have been working with multiple projects, I started this again today, I will test and get back to you. very much helpful. 👍
