### ISSUE TITLE
opacity option not working for drawPage?

### ISSUE THREAD

**Issue by hdwong** [Hopding/pdf-lib#553]
I try to embed a pdf file into the page, when I use the `page.drawPage` function and set the option object property `opacity`, it does not reflect any of the value I set.

    page.drawPage(embedContent, {
      x,
      y,
      width,
      height,
      opacity,
   });

But I found `PDFPageDrawPageOptions` in https://pdf-lib.js.org/docs/api/interfaces/pdfpagedrawpageoptions, it has the `opacity` property defined.

Did I miss something?

Thank you.

**Comment by Hopding** [comment]
@hdwong Can you please share a document and some code that I can use to reproduce the issue?

**Comment by hdwong** [comment]
I forked your example code in the following link: https://jsfiddle.net/ouz0cjqw/2/

The American flag covers the text area and the `opacity` property has no effect.

**Comment by hdwong** [comment]
@Hopding Is this problem a bug? Can you please help me? Thank you very mush!

**Comment by jonnyfluckey** [comment]
Curious to see if there was been any additional work on this issue? I am also having an issue with the Opacity. I also attempted to update the example JFiddle, and the opacity would not change when updated

**Comment by nimmc** [comment]
Is this one fixed? I also have this problem. No matter what value I set in opacity it seems there's no change at all.

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
