### ISSUE TITLE
characters in hebrew (utf-8 support) 

### ISSUE THREAD

**Issue by ds21194** [Hopding/pdf-lib#561]
I'm using the function drawText, and I get en error when I'm using characters in Hebrew "WinAnsi cannot encode" 

The lib specify that it should have support in utf-8 encode, but I don't find anything about it on the doc to actually change it.

**Comment by Hopding** [comment]
Hello @ds21194!

You'll need to use an embedded font that supports Hebrew characters. The README has been updated to clarify this. Please see https://github.com/Hopding/pdf-lib#fonts-and-unicode.
