### ISSUE TITLE
drawImage on pdf that get rotation

### ISSUE THREAD

**Issue by cboivin80** [Hopding/pdf-lib#562]
If we load a PDF that get a rotation (in my case 270 degrees). The PDF is in portrait display with that rotation. If i do a draw image on the page that get the rotation at position (0,0), the image will be supposed to be draw at the left bottom corner, but actually it draw at the right bottom corner, and the direction of the image is bottom to top. 

So that mean, when the PDF get the rotation, the origin is not good, and the with and height are reversed.

Maybe i don't understand something ?

**Comment by cboivin80** [comment]
duplicate sorry ... get an error on the first post

**Comment by princ09** [comment]
@SecureExchanges have you found solution for it?
