### ISSUE TITLE
PDF draw image with rotation issue

### ISSUE THREAD

**Issue by cboivin80** [Hopding/pdf-lib#563]
If we load a PDF that get a rotation (in my case 270 degrees). The PDF is in portrait display with that rotation. If i do a draw image on the page that get the rotation at position (0,0), the image will be supposed to be draw at the left bottom corner, but actually it draw at the right bottom corner, and the direction of the image is bottom to top. 

So that mean, when the PDF get the rotation, the origin is not good, and the with and height are reversed.

Maybe i don't understand something ?

**Comment by Hopding** [comment]
Hello @cboivin80!

When a PDF page is rotated, so is it's origin. You must detect and correct for this manually. Please see https://github.com/Hopding/pdf-lib/issues/65#issuecomment-468064410.

I'm open to PRs providing a more user-friendly solution to this.
