### ISSUE TITLE
Find and replace text?

### ISSUE THREAD

**Issue by keyhoffman** [Hopding/pdf-lib#564]
Reading through the docs.. can't seem to find answer to this

Is there a way to find and replace text?

Here is the use case:

- I need to generate a lot of PDFs from a template
- The only thing that changes in each template is a url that is in several places throughout the PDF
- Is there a way to add a tag like `<URL-REPLACEMENT>` to the template and then use pdf-lib to find and replace the tag with the actual url?

thanks!

**Comment by ThibDums** [comment]
I need the same functionnality.
Find a text or an input to fill in the pdf...
Is there a way to do it ?

**Comment by onigor** [comment]
From what I can see this is not something that is supported by PDF format itself.

**Comment by fabioselau077** [comment]
I need the same functionnality.
Same solution?

**Comment by Hopding** [comment]
Hello @keyhoffman!

This is possible only if the text you want to find and replace is in a text field (see https://github.com/Hopding/pdf-lib#fill-form). If the text is just normal text on a page and is not in a form field, it is not currently possible (see https://github.com/Hopding/pdf-lib#limitations).

**Comment by Shahzad6077** [comment]
Hey @keyhoffman @fabioselau077, any solution or workaround to generate a pdf from a template PDF?

**Comment by CarlosUlisesOchoa** [comment]
any solution?

**Comment by jjason685** [comment]
Had a similar use case recently; the following snippet is what I used to handle this.

```
const { PDFDocument, PDFName, PDFRawStream, decodePDFRawStream, arrayAsString } = require('pdf-lib');
const zlib = require('zlib');
const fs = require('fs');

// Can use either exact string or regex pattern
const rules = [
    {
        pattern: 'oldstring',
        replacement: 'newstring'
    }
];

const replaceText = async (data) => {
    const pdfDoc = await PDFDocument.load(data);

    const enumeratedIndirectObjects = pdfDoc.context.enumerateIndirectObjects();

    enumeratedIndirectObjects.forEach(([pdfRef, pdfObject]) => {
        if (!(pdfObject instanceof PDFRawStream)) {
            return;
        }

        if (pdfObject?.dict?.get(PDFName.of('Subtype')) === PDFName.of('Image')) {
            return;
        }

        let text = arrayAsString(decodePDFRawStream(pdfObject).decode());
        let modified = false;

        for (const rule of rules) {
            const newText = text.replace(rule.pattern, rule.replacement);

            if (newText !== text) {
                text = newText;

                modified = true;
            }
        }

        if (modified) {
            pdfObject.contents = zlib.deflateSync(text);
        }
    });

    const bytes = await pdfDoc.save();

    return Buffer.from(bytes);
};

replaceText(
    fs.readFileSync('./test.pdf')
).then(buf => fs.writeFileSync('./result.pdf', buf));
```

This only applies to text contents that don't use charmaps, where the strings are represented in this format: <1A>-1<06>-3<1D>3<04>-2<1509>9<10>-4, instead of just plaintext. To handle these, you'll have to use some sort of parser that maps the character back to it's original plaintext representation, then combines the string using the offsets.

**Comment by anhba817** [comment]
@jjason685 Thank you for your solution. I tried it in Typescript and got this error:
`error TS2540: Cannot assign to 'contents' because it is a read-only property.`
Any idea?

**Comment by svatal** [comment]
> @jjason685 Thank you for your solution. I tried it in Typescript and got this error: `error TS2540: Cannot assign to 'contents' because it is a read-only property.` Any idea?

You can use something like 
```
type Writeable<T> = {
  -readonly [P in keyof T]: T[P];
};

(pdfObject as Writeable<PDFRawStream>).contents = zlib.deflateSync(text);
```

to tell TS that `contents` (well, everything) is writeable.

**Comment by sayhicoelho** [comment]
> Had a similar use case recently; the following snippet is what I used to handle this.
> 
> ```
> const { PDFDocument, PDFName, PDFRawStream, decodePDFRawStream, arrayAsString } = require('pdf-lib');
> const zlib = require('zlib');
> const fs = require('fs');
> 
> // Can use either exact string or regex pattern
> const rules = [
>     {
>         pattern: 'oldstring',
>         replacement: 'newstring'
>     }
> ];
> 
> const replaceText = async (data) => {
>     const pdfDoc = await PDFDocument.load(data);
> 
>     const enumeratedIndirectObjects = pdfDoc.context.enumerateIndirectObjects();
> 
>     enumeratedIndirectObjects.forEach(([pdfRef, pdfObject]) => {
>         if (!(pdfObject instanceof PDFRawStream)) {
>             return;
>         }
> 
>         if (pdfObject?.dict?.get(PDFName.of('Subtype')) === PDFName.of('Image')) {
>             return;
>         }
> 
>         let text = arrayAsString(decodePDFRawStream(pdfObject).decode());
>         let modified = false;
> 
>         for (const rule of rules) {
>             const newText = text.replace(rule.pattern, rule.replacement);
> 
>             if (newText !== text) {
>                 text = newText;
> 
>                 modified = true;
>             }
>         }
> 
>         if (modified) {
>             pdfObject.contents = zlib.deflateSync(text);
>         }
>     });
> 
>     const bytes = await pdfDoc.save();
> 
>     return Buffer.from(bytes);
> };
> 
> replaceText(
>     fs.readFileSync('./test.pdf')
> ).then(buf => fs.writeFileSync('./result.pdf', buf));
> ```
> 
> This only applies to text contents that don't use charmaps, where the strings are represented in this format: <1A>-1<06>-3<1D>3<04>-2<1509>9<10>-4, instead of just plaintext. To handle these, you'll have to use some sort of parser that maps the character back to it's original plaintext representation, then combines the string using the offsets.

This will remove the utf-8 characteres from your PDF.
