### ISSUE TITLE
Where is the documentation for PDFString, PDFNumber, PDFName etc.

### ISSUE THREAD

**Issue by janiskopsisko** [Hopding/pdf-lib#565]
Hi, I am trying to understand how to work with fillable pdf's. I have found a working example how to fill an AcroForm [here](https://github.com/Hopding/pdf-lib/issues/185). Does anybody know where can I find more info?

Thx

**Comment by Hopding** [comment]
Hello @janiskopsisko!

`pdf-lib` has a new forms API. See the [create form](https://github.com/Hopding/pdf-lib#create-form) and [fill form](https://github.com/Hopding/pdf-lib#fill-form) examples. You can find more info in the [README](https://github.com/Hopding/pdf-lib#creating-and-filling-forms) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform).
