### ISSUE TITLE
Is there a way to enable CSS-styles inside this PDF?

### ISSUE THREAD

**Issue by Neohiro79** [Hopding/pdf-lib#568]
I want to be able to use HTML + CSS to "style" the result in the PDF.

I don't want to use another library based on jQuery and some other external "tool" like this one:

> https://github.com/Xportability/css-to-pdf

**Comment by thebenlamm** [comment]
This would be very helpful. Currently using another library to turn some css styled text into an image and embedding that image into the pdf.

My current use case requires `letter-spacing`.

**Comment by Neohiro79** [comment]
Well, i needed to solve my problem, so I tried [pdfmake]( https://pdfmake.github.io): 

They offer at least "some" styling - which might be useful if you generate a PDF with text ...

---

> https://pdfmake.github.io/docs/0.1/document-definition-object/styling/

---

**Comment by thebenlamm** [comment]
I had a very specific scenario that required a more complex drawing as well so I went with [puppeteer](https://www.npmjs.com/package/puppeteer) and wrote some html with css to render into an image. Probably overkill for most other applications.

**Comment by Neohiro79** [comment]
Yeah, but I don't like the approach of having to "render to an image".

Since PDF is such an important format in this world I am actually really surprised how less editable this format in fact is.
It's like Adobe never improved the API to make at least basic useful CSS available in PDF.

Would it still be Macromedia I'm pretty sure they would've improved the API quite a lot.
What a pain in the ass.

**Comment by Neohiro79** [comment]
Please let me know if you plan to implement some useful css options to edit text for the output of a pdf.

**Comment by Hopding** [comment]
Hello @Neohiro79!

`pdf-lib` does not support CSS per se, but there are several different text styles that can be achieved using the `drawText` options and graphics operators. For example:
```js
import {
  PDFDocument,
  popGraphicsState,
  pushGraphicsState,
  setCharacterSpacing,
  setCharacterSqueeze,
  rgb,
  StandardFonts,
} from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();
  const helveticaBoldItalic = await pdfDoc.embedFont(
    StandardFonts.HelveticaBoldOblique,
  );

  const page = pdfDoc.addPage();

  page.pushOperators(
    pushGraphicsState(),
    setCharacterSpacing(100),
    setCharacterSqueeze(42),
  );
  page.drawText('Foo Bar\nQux Baz', {
    x: 125,
    y: 500,
    size: 50,
    lineHeight: 50,
    color: rgb(0, 0.5, 1),
    font: helveticaBoldItalic,
  });
  page.pushOperators(popGraphicsState());

  const pdfBytes = await pdfDoc.save();
})();
```

This script produces a page with text that looks like the following:

>

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/93653149-42adda80-f9dd-11ea-8966-a4c97e3d2445.png" alt="">
</kbd>

>

Most (or all) of the options provided by `pdfmake` can be achieved in `pdf-lib`. But the current `drawText` API doesn't make it easy to use all of them. 

I'd be happy to accept PRs that add additional text styling options to [`PDFPageDrawTextOptions`](https://pdf-lib.js.org/docs/api/interfaces/pdfpagedrawtextoptions) for [`PDFPage.drawText`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawtext). I personally won't have time to implement them for awhile. But I can certainly provide tips and guidance to anybody interested in working on this!

**Comment by mohitsharma88** [comment]
Does PDF-lib support CSS property to the image?
