### ISSUE TITLE
How to read data from Acroform PDF

### ISSUE THREAD

**Issue by Nilanth** [Hopding/pdf-lib#571]
@Hopding

How to read data from Acroform PDF?

**Comment by EricDaviesRok** [comment]
My guess is that we first need to use the acrofrom branch rather than the main brainch.
However, that opens up the question of "what is the procedure to build a version we can use in a browser".

**Comment by Hopding** [comment]
Hello @Nilanth! 


`pdf-lib` has a new forms API. Please see the [create form](https://github.com/Hopding/pdf-lib#create-document) and [fill form](https://github.com/Hopding/pdf-lib#fill-form) examples and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). You are likely particularly interested in the [`PDFTextField.getText`](https://pdf-lib.js.org/docs/api/classes/pdftextfield#gettext) method.

**Comment by Hopding** [comment]
@EricDaviesRok Per my previous comment, you should be able to use the new forms API. But, if you do need to build a branch that hasn't yet been released, there are instructions in the [`CONTRIBUTING.md`](https://github.com/Hopding/pdf-lib/blob/master/CONTRIBUTING.md#compiling-the-project) file. It's pretty simple to do.

**Comment by EricDaviesRok** [comment]
I've successfully used the new forms API. There were some gotchas in the
values I was passing because I wasn't using typescript.
