### ISSUE TITLE
drawSvgPath rotate

### ISSUE THREAD

**Issue by sbraaa** [Hopding/pdf-lib#572]
I need to write some svg path to a pdf with different rotation angles but it seems there's some problems with this feature (or more probably I cannot understand how it should work!)

My code is very simple:
```
svgOptions = {
	x: offset_x,
	y: page.getHeight() - offset_y,
	borderWidth: svgSignWidth,
	scale: scaling,
	borderColor: rgb(0, 0, 0),
	rotate: degrees(rotation_angle)
}

page.drawSvgPath(svgSignPath, svgOptions);
```

with rotation_angle = 0 I obtain this -> [svg path with 0 degrees](https://github.com/sbraaa/tmp/raw/master/pdf_svg_path_0_degrees.pdf)
witch is whats expected to see.

Then I try with 90 degrees -> [svg path with 90 degrees](https://github.com/sbraaa/tmp/raw/master/pdf_svg_path_90_degrees.pdf)
Here two things seems to be wrong:

- why Counterclockwise rotation? 
- which is the origin point of rotation ? shouldn't be SVG path center point?

I could solve rotation direction behaviour -> [svg path with - 90 degrees](https://github.com/sbraaa/tmp/raw/master/pdf_svg_path_-90_degrees.pdf)
...but origin point of rotation seems to be a mistery!

**Comment by sbraaa** [comment]
Ok, it seems it depens on my lack of trigonometric functions (a lot of time passed since I studied them...)
Anyway, rotation counterclockwise is the standard math convention and rotation origin point is set to top-left so everything is ok.
If you need to rotate your svg path using center as origin point you must calculate  rotation of top-left point.
Let a,b the coordinates of  C (center of svg path) and x,y the coordinates of top-left point, to calculate rotation of top-left of desired angle you (x1, y1) do:

x1 = (x - a) * cos(angle) - (y - b) * sin(angle) + a
y1 = (x - a) * sin(angle) + (y - b) * cos(angle) + b

and don't forget that angle must be radian type.
Hope it helps someone.

**Comment by sebastianfast** [comment]
I had to adjust @sbraaa 's code a little bit, because it was not working for me and I had to understand the calculations myself.

My objects come from a fabric.js canvas which I translate into pdf-lib with the following code. Note that in fabric.js my objects are centered, i.e. obj.top and obj.left is not the top/left corner, but the center of the object. Since fabric.js coordinate system starts at the top-left, but pdf-lib's coordinate system starts at the bottom-left, I need to adjust the center_y position. The angle in fabric.js is calculated differently as well, so I need to adjust that, too.

```
const center_x = obj.left;
const center_y = page_height - obj.top;
const width = obj.width * obj.scaleX;
const height = obj.height * obj.scaleY;
const rotate = degrees(360 - obj.angle);

const half_width = width / 2;
const half_height = height / 2;
const alpha = obj.angle * (Math.PI / 180);
const rot_x = center_x - (half_width * Math.cos(alpha)) - (half_height * Math.sin(alpha));
const rot_y = center_y - (half_height * Math.cos(alpha)) + (half_width * Math.sin(alpha));

page.drawImage(png, { x: rot_x, y: rot_y, width, height, rotate });
```
