### ISSUE TITLE
Failed to parse PDF document (line:4917 col:887 offset=759675): No PDF header found

### ISSUE THREAD

**Issue by anton-smh** [Hopding/pdf-lib#573]
Hi,

I'm trying to load a pdf but I get this error :
_errors.js?8fdb:173 Uncaught (in promise) Error: Failed to parse PDF document (line:4917 col:887 offset=759675): No PDF header found at MissingPDFHeaderError.PDFParsingError..._

and this is my code :

`const { PDFDocument } = require('pdf-lib')

      const pdfUrl = '/pdfs/map.pdf'

      const pdfBuffer = await fetch(pdfUrl)
        .then((res) => res.arrayBuffer())
        .then((buffer) => new Uint8Array(buffer))

      console.log('Typee:', typeof pdfBuffer)
      console.log('Is Uint8Array:', pdfBuffer instanceof Uint8Array)
      console.log(pdfBuffer)

      const pdfDoc = await PDFDocument.load(pdfBuffer)
      console.log(pdfDoc.context.header.toString())`

in the console I get :
Typee: object
Download.vue?be04:77 Is Uint8Array: true
Download.vue?be04:78 Uint8Array(1620433) [37, 80, 68, 70, 45, 49, 46, 51, 13, 37, 226, 227, 207, 211, 13, 10, 49, 32, 48, 32, 111, 98, 106, 13, 60, 60, 47, 76, 97, 110, 103, 40, 102, 114, 45, 70, 82, 41, 47, 77, 101, 116, 97, 100, 97, 116, 97, 32, 50, 32, 48, 32, 82, 47, 79, 117, 116, 112, 117, 116, 73, 110, 116, 101, 110, 116, 115, 91, 60, 60, 47, 68, 101, 115, 116, 79, 117, 116, 112, 117, 116, 80, 114, 111, 102, 105, 108, 101, 32, 49, 49, 32, 48, 32, 82, 47, 73, 110, 102, 111, …]
Download.vue?be04:84 %PDF-1.3
%
errors.js?8fdb:173 Uncaught (in promise) Error: Failed to parse PDF document (line:4917 col:887 offset=759675): No PDF 

What I doing wrong ?

**Comment by iamshulz** [comment]
@antoinesimeha  does `fetch` work on loading local file ?
