### ISSUE TITLE
How to make filling form text fields and checkboxes work in Typescript

### ISSUE THREAD

**Issue by tristan-sharma** [Hopding/pdf-lib#575]
In previous issues, @Hopding has provided code to show how `pdf-lib` can be used to programmatically fill out text fields in a template PDF. I've been trying to make the code provided [here](https://github.com/Hopding/pdf-lib/issues/185) work in TypeScript, but this raises several problems with various functions like `save`, `context`, and `lookup`. For example, with the `lookup` function, the return type is PDFObject which is incorrect because PDFObject does not have a set method (see [here](https://imgur.com/a/Fr2gZ0U)).

I have similarly had difficulties in trying to make the [checkbox code](https://github.com/Hopding/pdf-lib/issues/109#issuecomment-568484109) work in TypeScript.

@Hopding Could you please provide sample TypeScript code that programmatically fills out form text fields and checkboxes?

Thanks!

**Comment by Hopding** [comment]
Hello @tristan-sharma!

`pdf-lib` has a new forms API. Please see the [create form](https://github.com/Hopding/pdf-lib#create-document) and [fill form](https://github.com/Hopding/pdf-lib#fill-form) examples and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform).
