### ISSUE TITLE
Is it possible to draw text within a path?

### ISSUE THREAD

**Issue by softwarerero** [Hopding/pdf-lib#576]
I would like to draw text withing shapes, think of speech bubbles in a comic. Not only would I like to clip on the path but I would also like to know if all text fits, otherwise I would like to iterate with a smaller font size until things match. Is that doable with pdf-lib. 
<img width="319" alt="Screen Shot 2020-08-25 at 20 04 58" src="https://user-images.githubusercontent.com/2768891/91239848-75322380-e70e-11ea-996d-a45ac6dee7ab.png">

**Comment by Hopding** [comment]
Hello @softwarerero! 

`pdf-lib` does not have any high level APIs designed for this purpose. But it provides all the APIs you need to implement this yourself:
* [`PDFPage.drawText`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawtext)
* [`PDFFont.widthOfTextAtSize`](https://pdf-lib.js.org/docs/api/classes/pdffont#widthoftextatsize)
* [`PDFFont.heightAtSize`](https://pdf-lib.js.org/docs/api/classes/pdffont#heightatsize)

You would need to implement an algorithm that, given a path and a string of text, figures out how to break the text into lines that fit within the path. And if the text simply won't fit, the algorithm should try again with a smaller font size. The [`layoutMultilineText`](https://github.com/Hopding/pdf-lib/blob/aa457ba/src/api/text/layout.ts#L135-L205) and [`computeFontSize`](https://github.com/Hopding/pdf-lib/blob/aa457ba/src/api/text/layout.ts#L30-L56) functions do something roughly like this, but only for rectangle bounding boxes. You would need to adapt them to work for arbitrary path/shape bounds.

I hope this helps! Please let me know if you have any additional questions.
