### ISSUE TITLE
[Feature Request] API for text alignment

### ISSUE THREAD

**Issue by woodfordnono** [Hopding/pdf-lib#578]
Would be great if there is align text-like feature like the microsoft office or google docs. It takes time to implement new features but willing to wait.

**Comment by Hopding** [comment]
Hello @djxcds! I'm happy to accept PRs for this. I personally don't expect to have time to work on it in the near future.

Note also that you can still align text with the APIs that exist today, though it's not quite as simple as passing an `align: 'right'` option. See https://github.com/Hopding/pdf-lib/issues/432.

**Comment by Hopding** [comment]
This will be implemented as part of a larger effort to improve pdf-lib's typography and text layout support: https://github.com/Hopding/pdf-lib/discussions/998.
