### ISSUE TITLE
Is there a way to keep the original font?

### ISSUE THREAD

**Issue by ElePhontitis** [Hopding/pdf-lib#579]
I want to modify an existing pdf. Unfortunately pdf-lib replaces the font and breaks the layout. Is there any way that only the modified parts of the pdf are actually modified?

**Comment by zeteticl** [comment]
same problem

**Comment by ElePhontitis** [comment]
@zeteticl In my case the problem wasn't the library but the pdf itself. It hadn't any of the used fonts embedded, so the library couldn't do anything but to use the default font. Pdf's are often stripped of their fonts in favor of filesize. Did you check your pdf for embedded fonts?
