### ISSUE TITLE
Facing issues while opening a merged file using pdf-lib

### ISSUE THREAD

**Issue by sanketjo96** [Hopding/pdf-lib#580]
@Hopding We are basically merging multiple pdfs together to generate single PDF file. Idea is to insert a spacial back page after every other page of the main pdf file. 

<img width="588" alt="Screenshot 2020-08-27 at 8 08 11 PM" src="https://user-images.githubusercontent.com/31438283/91456546-0933f480-e8a1-11ea-8759-22b273e41108.png">

<img width="270" alt="Screenshot 2020-08-27 at 8 09 14 PM" src="https://user-images.githubusercontent.com/31438283/91456693-31bbee80-e8a1-11ea-8964-246b54abd864.png">

**Unfortunately when I am opening this file in acrobat its erroring out, worked using chrome/safari ** 

<img width="422" alt="Screenshot 2020-08-27 at 8 12 37 PM" src="https://user-images.githubusercontent.com/31438283/91457122-a7c05580-e8a1-11ea-9478-76b940c183e1.png">

**Tried qpdf check with below output **

checking response10.pdf
PDF Version: 1.7
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect

**Comment by sanketjo96** [comment]
@Hopding can you please direct what could be a reason. qpdf check seems clean but it still says it may contain
errors

**Comment by JoshElgar** [comment]
@sanketjo96 Do you still need help with this?

**Comment by Hopding** [comment]
Hello @sanketjo96! Can you please share some code and PDFs that I can use to reproduce the issue?

**Comment by Hopding** [comment]
I'm going to close this for now. Please feel free to reopen with additional info if you're still having trouble!
