### ISSUE TITLE
How to fetch/copy existing contents?

### ISSUE THREAD

**Issue by ipd-otto** [Hopding/pdf-lib#582]
I've just started using this library and it's working fine so far. But now I ran into a problem:
I need to repeat existing content on a page. I could not yet figure out where to find the existing content yet. Seems there's no easy way at the moment. An entry point seems to be the page's _node_ property.

Maybe I've missed something - if so, a hint would be nice, if not, I'd really appreciate such a feature.

**Comment by Hopding** [comment]
Hello @ipd-otto!

I'm not sure exactly what you're trying to do here. It sounds like cloning pages may be of use to you. If so, please see https://github.com/Hopding/pdf-lib/issues/422#issuecomment-622169968.

If you do, in fact, need to extract existing content from a page, then the best you can do is try to use a library like `pdf.js` to read the contents of the file, and just use `pdf-lib` to modify it. Please see https://github.com/Hopding/pdf-lib#limitations for more details.
