### ISSUE TITLE
Push breakTextIntoLines into public API

### ISSUE THREAD

**Issue by FlorianPons** [Hopding/pdf-lib#588]
I use pdf-lib to create PDF with text and to do so I need to be able to wrappe text and continue to write after this paragraphe.
To calculate the height of the text I have to use breakTextIntoLines so I have the number of lines and it works well. But this function is not exposed as a standard function in the documentation. Can you move it to public API ?

**Comment by FlorianPons** [comment]
#193 Is the PR linked to this request.

**Comment by Hopding** [comment]
This will be addressed as part of a larger effort to improve the typography and text layout support in pdf-lib: https://github.com/Hopding/pdf-lib/discussions/998
