### ISSUE TITLE
replace texts in original pdf

### ISSUE THREAD

**Issue by fabioselau077** [Hopding/pdf-lib#590]
I need one question, for example: have one pdf for "model", i need replace some texts in original pdf.
Original: "I'm 10 years old".
After change: "I'm 9 years old".
In Vue It would be like one variable like {{y}}, how would it look to do that in the pdf using Vue?

**Comment by Hopding** [comment]
Hello @fabioselau077!

You can do this pretty easily if your original PDF has form fields. See the [form filling](https://github.com/Hopding/pdf-lib#fill-form) example. 

If your original PDF does not use form fields, then you won't be able to achieve this with `pdf-lib` right now. See https://github.com/Hopding/pdf-lib/issues/177 for more details.
