### ISSUE TITLE
How to make a table?

### ISSUE THREAD

**Issue by lamecus** [Hopding/pdf-lib#591]
Is there an easy way to make a table, such as with [jspdf-autotable](https://github.com/simonbengtsson/jsPDF-AutoTable)? If so, can someone provide a minimal example?

**Comment by naknode** [comment]
I, too, am looking for this kind of feature. Would be very handy.

**Comment by Hopding** [comment]
Hello @lamecus! 

`pdf-lib` does not provide any table APIs. Happy to accept PRs for this feature though! I personally won't have time to work on something like this anytime soon. But I'm happy to answer questions and provide guidance to anybody that would like to create a PR.

It's worth noting that the PDF file format doesn't have any special accommodations for tables. They're just constructed from lines and rectangles (see [`PDFPage.drawLine`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawline) and [`PDFPage.drawRectangle`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawrectangle)). And, of course, the actual content of the cells is just text, images, etc... (see [`PDFPage.drawText`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawtext) and [`PDFPage.drawImage`](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawimage)).

**Comment by Hopding** [comment]
Closing in favor of https://github.com/Hopding/pdf-lib/issues/382.
