### ISSUE TITLE
Trying to parse invalid object

### ISSUE THREAD

**Issue by rtrachelteng** [Hopding/pdf-lib#592]
Hi I am encountering this error while loading the pdf document. I am using version 1.10.0. Have attached the file and error message
![Screenshot 2020-09-08 at 12 11 22 PM](https://user-images.githubusercontent.com/36838392/92432329-6c405800-f1cc-11ea-9bb7-77491966779b.png)

```
PDFDocument.load(docBuffer).then(() => {
        passwordProtected = false;
      }).catch(() => {
        passwordProtected = true;
      });
```
[UserManual.pdf](https://github.com/Hopding/pdf-lib/files/5186009/UserManual.pdf)

**Comment by Hopding** [comment]
Hello @rtrachelteng! Looks like the PDF you're trying to open is encrypted. Note the message of the error that is thrown:
```
Error: Input document to `PDFDocument.load` is encrypted.
```
`pdf-lib` does not support encrypted documents (see [here](https://github.com/Hopding/pdf-lib#encryption-handling)). https://github.com/Hopding/pdf-lib/issues/233 and https://github.com/Hopding/pdf-lib/issues/243 are tracking support for this feature.
