### ISSUE TITLE
Adding to Page Dictionary

### ISSUE THREAD

**Issue by charmingbandit** [Hopding/pdf-lib#593]
Is there a way to add custom entries to the Page dictionary when creating a PDF?

**Comment by Hopding** [comment]
Hello @charmingbandit!

You can do whatever you like with the structure of the PDF using the lower level APIs. Of course, you'll have to be careful that you don't add entries that give PDF readers trouble when they try to open your PDF. Here's an example of adding a custom entry:
```js
const pdfDoc = await PDFDocument.create();
const page = pdfDoc.addPage();
page.node.set(PDFName.of('Foo'), PDFHexString.of('bar'));
const pdfBytes = await pdfDoc.save();
```

Note, however, that PDF readers don't like to open the PDF created by the above example - though it works fine if you do not set a custom entry.

**Comment by jbeuckm** [comment]
What about custom entries to other dictionaries / not just page? How could I add a `PDFString` object to the `indirectObjects` list and read it back later?
