### ISSUE TITLE
Deno bundle: error: Uncaught TypeError: Cannot read property 'FontNames' of undefined

### ISSUE THREAD

**Issue by Fire7** [Hopding/pdf-lib#594]
I'm trying to run code after successful build and get error.

In this place:
```javascript
   StandardFontValues = values(standard_fonts_js_1.FontNames);
```

Error: 
```
error: Uncaught TypeError: Cannot read property 'FontNames' of undefined
            StandardFontValues = values(standard_fonts_js_1.FontNames);
                                                            ^
```

Here is same thing with another bundle: https://github.com/timreichen/Bundler/issues/19

**Comment by Hopding** [comment]
@Fire7 Can you please provide some sample code and commands I can use to reproduce the issue?

**Comment by Fire7** [comment]
@Hopding 

1. example.ts ( it's from example) 

```javascript
import { PDFDocument, StandardFonts, rgb } from 'https://cdn.pika.dev/pdf-lib@^1.7.0'

// Create a new PDFDocument
const pdfDoc = await PDFDocument.create()

// Embed the Times Roman font
const timesRomanFont = await pdfDoc.embedFont(StandardFonts.TimesRoman)

// Add a blank page to the document
const page = pdfDoc.addPage()

// Get the width and height of the page
const { width, height } = page.getSize()

// Draw a string of text toward the top of the page
const fontSize = 30
page.drawText('Creating PDFs in JavaScript is awesome!', {
  x: 50,
  y: height - 4 * fontSize,
  size: fontSize,
  font: timesRomanFont,
  color: rgb(0, 0.53, 0.71),
})

// Serialize the PDFDocument to bytes (a Uint8Array)
const pdfBytes = await pdfDoc.save();

Deno.writeFileSync(`__example.pdf`, pdfBytes);
```

`deno run --allow-write --allow-net example.ts` 
works fine

2. makeBundle.ts (make bundle)

```javascript  

const [diagnostics, emit] = await Deno.bundle(
  "./example.ts",
  undefined
  {
    module: 'commonjs',
    checkJs: false,  // Skip TypeScript errors in external lib (pdf-lib)
    strict: false, // Skip TypeScript errors in external lib (pdf-lib)
    allowJs: true,  // Skip TypeScript errors in external lib (pdf-lib)
    lib: ["esnext", "deno.ns", 'deno.window'],
    target: 'es2019'
  }
);

if (diagnostics) {
  console.log(diagnostics);
  Deno.exit(1);
}

Deno.writeTextFileSync('bundle/example.bundle.js', emit);

```

`deno run --allow-read --allow-write --unstable --allow-net makeBundle.ts`
works fine, create `example.bundle.js`

Then just try to run result file causes an error:

`deno run --allow-write bundle/example.bundle.js`

**Comment by Hopding** [comment]
@Fire7 `@pdf-lib/standard-fonts` is a dependency of `pdf-lib`. It looks like it’s not being included in the bundle. I’m not too familiar with `Deno.bundle`. Perhaps you need to instruct it to include this dependency?

**Comment by Hopding** [comment]
@Fire7 Any luck getting the dependency into the bundle?

**Comment by Fire7** [comment]
@Hopding nope. 
I have tried to include deps (`standard-fonts`), but still got an error. 
I'm not sure where problem is (with deno `bundle` or `pdf-lib` itself), but already resolve it by creating custom bundler: https://github.com/Fire7/denode

We can close issue for now, I guess.
