### ISSUE TITLE
PDF: remove excessive white borders around PDF pages

### ISSUE THREAD

**Issue by gabhisheks** [Hopding/pdf-lib#595]
Hi @Hopding !

Please can you guide to achieve for removing unwanted white space from PDF page?
E.g: suppose, a page has X-height & the content on page is taking space as Y-height. Now, in the page, there are some extra space [ X - Y ] is remaining. I want to remove that unwanted spaces.

Overall, Needs to remove white-spaces from all sides of pdf-page. 

Please let me know if there are any features. 

Thanks! in advance.

**Comment by Hopding** [comment]
Hello @gabhisheks!

These two methods should let you achieve what you're after:
* [`PDFPage.setSize`](https://pdf-lib.js.org/docs/api/classes/pdfpage#setsize)
* [`PDFPage.translateContent`](https://pdf-lib.js.org/docs/api/classes/pdfpage#translatecontent)
