### ISSUE TITLE
Is there a way to change the initial state of the OCG for hide or show certain layers?

### ISSUE THREAD

**Issue by ezalorpro** [Hopding/pdf-lib#597]
Basically that, is there a way to change the initial state of the OCG to hide or show certain layers? I want to use acrobat pdf embedded api to annotate and display pre existing building plans, but acrobat pdf embedded api does not come with the ability to hide or show layers, but it does take into account the initial states of the layers, so those that are hidden by default will not be shown.

So I want to put a checklist, modify the pdf accordingly, and reload the viewer I guess.

Feel free to give me a better option ;)

Regards.

PS: Doing the opposite seems to be more difficult, I mean use pdf.js which comes with layer support (since two weeks ago) and implement the annotation system.

**Comment by Hopding** [comment]
Hello @ezalorpro! I'm not to familiar with how OCG or layers work. `pdf-lib` does not have any special APIs for this. But if it's something that requires you to edit the structure of a PDF to achieve, it should be possible to do with `pdf-lib`. However, you'd need to use the lower-level APIs. Please let me know if you have any questions about this!

**Comment by soadzoor** [comment]
@Hopding some high level API would be nice for this indeed, something like this: https://github.com/mozilla/pdf.js/pull/12170

Basically if you open a PDF with multiple layers, you can toggle the layers from the left hand-side panel if you open the PDF in firefox. In pdf-lib, the initial states are not even respected, so if we open a PDF, where a layer is turned off, then save the PDF without modifying it on purpose, the hidden layer will be visible on the newly created PDF file.

Example PDF with 2 layers (one of them is hidden by default):
[Lavatory.pdf](https://github.com/Hopding/pdf-lib/files/6272614/Lavatory.pdf)
