### ISSUE TITLE
Exception from drawText()

### ISSUE THREAD

**Issue by kevinswartz** [Hopding/pdf-lib#60]
Hi again guys,
I'm getting an error back from drawText on a specific pdf file.  The pdf itself is sensitive and I can't upload it, but I have a stack trace for you.  

```
pdf-lib.min.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at s.i.normalizeCTM (pdf-lib.min.js:1)
    at s.i.addContentStreams (pdf-lib.min.js:1)
    at C.drawText (all-classes.js:1)
```

Here's my code calling drawText().  As far as I can tell all arguments are input correctly.
```
var pages = me.pdfDoc.getPages();
var page  = pages[pageIndex];

var toWidth = page.get('MediaBox').array[2].number;
var toHeight = page.get('MediaBox').array[3].number;

var embeddedFontRef = null;
var embeddedFont = null;
if(me.isStandardFont(fontFamily)){
  var arr = me.pdfDoc.embedStandardFont(fontFamily);
  embeddedFontRef = arr[0];
  embeddedFont = arr[1];
}
else{
  var arr = me.pdfDoc.embedNonstandardFont(me.getFontData(fontFamily));
  embeddedFontRef = arr[0];
  embeddedFont = arr[1];
}

fontSize = +fontSize.split('px')[0];
page.addFontDictionary(fontFamily, embeddedFontRef);

var encodedText = null;
if(embeddedFont && typeof embeddedFont.encodeText === "function"){
  console.log('encoding text', text);
  encodedText = embeddedFont.encodeText(text);
  console.log('text encoded', encodedText);
}
else{
  console.log('not encoding text');
  encodedText = text;
}

var contentStream = me.pdfDoc.createContentStream(
  window.PDFLib.drawText(encodedText, {
    x: (x / scale),
    y: toHeight - ((y + fontSize) / scale),
    size: (fontSize / scale),
    font: fontFamily,
    colorRgb: [0,0,0],
  })
);

page.addContentStreams(me.pdfDoc.register(contentStream));
```

Any thoughts?
Thanks for your help!
Kevin

**Comment by Hopding** [comment]
Nothing jumps out at me from your code sample. I'll take a longer look at this over the weekend though and see if I can't find the problem. One thing that would help is if you can reproduce the stack trace using the non-minified version of `pdf-lib`. That will make the stack trace a lot more intelligible.

Note that the non-minified version is available from the same CDN as the minified version, just without the `.min` in the extension: https://unpkg.com/pdf-lib/dist/pdf-lib.js

**Comment by kevinswartz** [comment]
Here's a non-minified stack trace.  We also were able to reproduce this with a file that I can send over.  Let me know what you think.  Thanks!

```
Error saving pdf changes TypeError: Cannot read property '0' of undefined
    at PDFPage._this.normalizeCTM (pdf-lib.js:10647)
    at PDFPage._this.addContentStreams (pdf-lib.js:10687)
    at constructor.drawText (PDFGenerationHelper.js?_dc=1546810361298:149)
```
[write_fail.pdf](https://github.com/Hopding/pdf-lib/files/2730887/write_fail.pdf)

**Comment by Hopding** [comment]
@kevinswartz I found the bug causing this issue and fixed it in https://github.com/Hopding/pdf-lib/pull/63.

I just cut prerelease [`0.6.1-rc1`](https://www.npmjs.com/package/pdf-lib/v/0.6.1-rc1) with the fix.

You can install this prerelease with npm:
```
npm install pdf-lib@0.6.1-rc1
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.1-rc1/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.1-rc1/dist/pdf-lib.min.js

Please try it out and let me know if it works for you!

**Comment by kevinswartz** [comment]
Looks fixed to me.  Thanks for your help!
