### ISSUE TITLE
[Feature Request] Transparent Fields

### ISSUE THREAD

**Issue by gregharkins** [Hopding/pdf-lib#605]
Allow backgroundColor and borderColor to be undefined for transparent backgrounds in Form Field Widgets.

**Comment by Hopding** [comment]
@gregharkins I just tested setting `backgroundColor: undefined` and `borderColor: undefined` and the resulting fields had transparent backgrounds and borders in Preview and Adobe Acrobat. So this already appears to be working. Please feel free to reopen this issue with some additional information if there's something I'm missing here 👍
