### ISSUE TITLE
drawPage for embedded PDF seems to lose hyperlink annotations

### ISSUE THREAD

**Issue by Mattykins** [Hopding/pdf-lib#606]
I am generating a bunch of PDF documents using puppeteer, and then compiling them into one large PDF using pdf-lib. The links from the individual PDFs seem to be lost when embedding them into the main PDF via `drawPage`

Here is some psuedocode detailing the problem:

```javascript
const myPdfToEmbed = const pdfDoc = await PDFDocument.load(handoutPdfBytes);
fs.writeFileSync("./test.pdf", await myPdfToEmbed.save()); // This PDF has clickable links
const finalDoc = await PDFDocument.create();
const page = finalDoc.addPage();
const embeddedPage = await finalDoc.embedPage(myPdfToEmbed, { ... });
page.drawPage(embeddedPage);
fs.writeFileSync("./test2.pdf", await finalDoc.save()); // This PDF does not have clickable links
```

I'm not sure if I'm just using the library wrong or if there's a bug  :) Happy to provide any additional info you need

**Comment by Hopding** [comment]
Hello @Mattykins! Can you please share some PDFs and a complete script that I can use to reproduce the issue?

**Comment by Hopding** [comment]
I'm going to close this for now. Please feel free to reopen with additional information.
