### ISSUE TITLE
AddPage throw an exception

### ISSUE THREAD

**Issue by cboivin80** [Hopding/pdf-lib#607]
Hello,

We don't really know why (we do not investiguated) but with some specific document we are not able to addPage.

The error occur in that method 
```js
 PDFPageTree.prototype.ascend = function (visitor) {
      visitor(this);
      var Parent = this.Parent();
      if (Parent)
        Parent.ascend(visitor);
    };
```
We fixed the issue by adding the validation on the ascend function. The object exist, but the ascend do not.
```js
 PDFPageTree.prototype.ascend = function (visitor) {
      visitor(this);
      var Parent = this.Parent();
      if (Parent&&Parent.ascend)
        Parent.ascend(visitor);
    };
```

**Comment by Hopding** [comment]
Hello @cboivin80! Thanks for reporting this. Are you able to share a document that can be used to reproduce the issue?

**Comment by cboivin80** [comment]
Unfortunately no, it is a banking doument. I can however share the ownership of the document. Can that help? Sorry, the screenshots are in french.

![image](https://user-images.githubusercontent.com/38925527/93536820-e765e480-f917-11ea-8e24-55c763ca61ac.png)
![image](https://user-images.githubusercontent.com/38925527/93536840-efbe1f80-f917-11ea-9b4e-2de063eb172a.png)
![image](https://user-images.githubusercontent.com/38925527/93536860-fba9e180-f917-11ea-9755-129b8e1a5cdc.png)

**Comment by cboivin80** [comment]
Ok there is the file. 

I remove all the pages and leave only one.

[bugged-document.pdf](https://github.com/Hopding/pdf-lib/files/5242394/bugged-document.pdf)

**Comment by Hopding** [comment]
@cboivin80  Release candidate [`1.11.2-rc1`](https://www.npmjs.com/package/pdf-lib/v/1.11.2-rc1) is now published. It contains a fix for this issue (see https://github.com/Hopding/pdf-lib/pull/608). Please let me know if it solves the problem for your private document!

You can install this new version with npm:

```
npm install pdf-lib@1.11.2-rc1
```

It's also available on unpkg:

- https://unpkg.com/pdf-lib@1.11.2-rc1/dist/pdf-lib.js
- https://unpkg.com/pdf-lib@1.11.2-rc1/dist/pdf-lib.min.js

As well as jsDelivr:

- https://cdn.jsdelivr.net/npm/pdf-lib@1.11.2-rc1/dist/pdf-lib.js
- https://cdn.jsdelivr.net/npm/pdf-lib@1.11.2-rc1/dist/pdf-lib.min.js

**Comment by cboivin80** [comment]
Yes it's fix. Thank you so much.
