### ISSUE TITLE
[ Question ] Using the embedPdf method.

### ISSUE THREAD

**Issue by m-majetic** [Hopding/pdf-lib#610]
Hi !

What brought me to this library a few days ago was the ability to merge two or more documents efficiently.
For the sake of this question, we'll only focus on combining two documents.

Before I continue with the issue description, I want to say that I have taken a look at your example where you used the "embedPdf" method, but I didn't quite get it because you were manipulating a single page which isn't what I'm trying to do here ( my assumption might be wrong about what's going on behind the scenes though ).

Let's say one of the documents is large with a large page count, and the other one only has two pages. Let's call the larger one "doc1" and the smaller one "doc2".

So, right away, as I see the "embedPdf" method, I assume that I can load up one document and embed the other one into it and get the complete document out.

```
const doc1Url = 'https://example/doc1.pdf'
const doc1SourcePdf = await fetch(doc1Url).then((res) => res.arrayBuffer())

const doc2Url = 'https://example/doc2.pdf'
const doc2SourcePdf = await fetch(doc2Url).then((res) => res.arrayBuffer())

const doc1 = await PDFDocument.load( doc1SourcePdf );

// Here, I don't assign the return value to a variable since I don't expect to use the embedded page or manipulate it
await doc1.embedPdf( doc2SourcePdf )
// With the "embedPdf" method used on "doc1" I assume that the "doc2" was embedded into it.

const doc1Base64 = await doc1.saveToBase64()
// What I'm expecting here is that "doc2" was merged into "doc1" with all of it's pages, but it isn't so.
```

[In another issue](https://github.com/Hopding/pdf-lib/issues/252) I saw that you used "PDFDocument.create()" method to instantiate a new PDF document into which another two can be merged and they are pieced together using the "copyPages" and "addPage" methods. ( doc1 + doc2 = doc3 )

Do I have to create a new PDF document using the `create` method for this to work ?
It doesn't make sense to me because I don't need a new document, but just use the first one with `PDFDocument.load(doc1)` and embed something into it at the end.
I only see how making a new PDF document using the `create` method would make sense is if it's a necessity of the library for it to be able to do these manipulations.

What I fear with the [page copying method](https://github.com/Hopding/pdf-lib/issues/252) is that it could be unnecessarily costly. e.g. Why would I copy every page in a big document ( doc1 ) and in ( doc2 ) to create a new document ( doc3 ) if I can load up `doc1` and place `doc2` at it's end ?

As I said, I'm working of the assumption that I don't have to instantiate a new document using `PDFDocument.create()`. If I can use the `PDFDocument.load()` and work with that right off the bat.

**Comment by matteoulissi** [comment]
I look forward to an answer , i think i'm experiencing the same problem, probably because i'm a newbee to this library and to the pdf world in general

Btw the library is great, i resolved a problem i had with puppeteer thanks to pdf-lib, thanks @Hopding

**Comment by Hopding** [comment]
Please see the API docs for https://pdf-lib.js.org/docs/api/classes/pdfdocument#embedpdf and open a [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) if it's not working as described.
