### ISSUE TITLE
Creating Ink Annotations

### ISSUE THREAD

**Issue by charmingbandit** [Hopding/pdf-lib#611]
Hello @Hopding,

Is it possible to create Ink annotations using pdf-lib?  If so, how could this be achieved?

pdf-lib is working great so far BTW!

Thanks in advance!

**Comment by Hopding** [comment]
Hello @charmingbandit! You can use pdf-lib to create any kind of annotation you like. But high level APIs do not exist for all annotations (including ink annotations), so you'll have to leverage the low-level APIs to do it. See https://github.com/Hopding/pdf-lib/issues/555 and https://github.com/Hopding/pdf-lib/issues/529. You may also need to take a look at the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) to understand what you need to do with the low-level APIs. If you get something working, I'd be happy to accept a PR introducing a high-level API for this.
