### ISSUE TITLE
This is to good to be true!?!

### ISSUE THREAD

**Issue by Lex-talionis** [Hopding/pdf-lib#616]
Im writing a tool that was originally using .exes written in c# to manipulate pdfs for a client which became a pig to maintain.

Ive had a little tinker and its so easy to use and under a MIT license. Whats the catch?

Anyway very easy to use, thanks for the great work.

**Comment by Hopding** [comment]
Hello @Lex-talionis!

There is no catch. I'm glad you've found pdf-lib useful. Good luck with your project 😄
