### ISSUE TITLE
Form: Checkbox group

### ISSUE THREAD

**Issue by neeeekto** [Hopding/pdf-lib#617]
Hi!
I have a document with checkbox group.

I'm trying to fill in the `Kundendaten` (id: legal_salutation) field
[Doc](https://drive.google.com/file/d/12buZ5Fd6wgmi-tEdwdL5bKfL3KJe73KJ/view?usp=sharing)

Code:
```
const form = pdf.getForm();
const checkBox = form.getCheckBox('legal_salutation'); // Kundendaten field in PDF
checkBox.check();
```
As a result, the `Herr` field is selected. I do not know how to select the`Frau` field.

**Comment by dungvu-qe** [comment]
I have same issue, could you have me @neeeekto :)

**Comment by StefanZivkovic** [comment]
@neeeekto have you been able to solve this? If yes - how?
