### ISSUE TITLE
[Question] createFieldText() Font fills height of field

### ISSUE THREAD

**Issue by bjbk** [Hopding/pdf-lib#619]
I found pdf-lib when searching for a pdf generator that plays well with Electron.  (Electron makes PDF's from page views out of the box, but I need the ability to export PDF's that contain form elements. 🤷‍♂️ 

I have been trying to create a text entry field that allows for a paragraph of text to be entered by the user, say 200 char max.  Here is my code:
```javascript
// relevant part of code
const wednesdayform = form.createTextField('wednesday.agenda')
          wednesdayform
            .addToPage(agendaPage, {
              x: 155,
              y: agendaLine - 102,
              width: width - 180,
              height: 100,
              borderWidth: 0.1,
              borderColor: rgb(0.2, 0.2, 0.2),
              font: defaultFont
            })
          const getFieldForMultiline = form.getTextField('wednesday.agenda')
          getFieldForMultiline.enableMultiline()
          getFieldForMultiline.setMaxLength(200)
```
So far so good!  However in testing the generated PDF the font grows to the size of the text field:
<img width="1429" alt="Screen Shot 2020-10-01 at 1 42 50 PM" src="https://user-images.githubusercontent.com/7434052/94844324-18501a00-03ec-11eb-98d7-8760b2bdbe7c.png">

(This is testing using Readdle's PDF Expert)
I have not been able to figure out how to have multilines but adjust the font size so the user doesn't think that he can only type a few words.  Overflow moves to new lines, but is hidden.
This is an example (also opened with PDF Expert) using a different library ([PDFKit](https://github.com/foliojs/pdfkit/blob/master/docs/forms.md#text-field-options)) that is very difficult to use in an Electron environment, however it has the desired result:

![image](https://user-images.githubusercontent.com/7434052/94844949-f6a36280-03ec-11eb-84e2-fb486390a339.png)

**Comment by Hopding** [comment]
@bjbk What happens if you set `enableMultiline()` before you call `wednesdayform.addToPage`?

**Comment by bjbk** [comment]
That did the trick!  I hadn't realized that I could call it before render.  Brilliant library @Hopding !  Thanks for your help
