### ISSUE TITLE
Ability to add named destinations

### ISSUE THREAD

**Issue by aceakash** [Hopding/pdf-lib#622]
Does pdf-lib support adding named destinations?
I quite like the look of [that feature in PDFKit](https://github.com/foliojs/pdfkit/blob/master/docs/destinations.md), but couldn't find anything similar in pdf-lib.

If it's not supported yet, is there anything related on the library's roadmap?

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998

**Comment by furstenheim-goodnotes** [comment]
Hi, I wasn't able to find any example in the repository. Is this supported? Thanks
