### ISSUE TITLE
Method PDFSignature.needsAppearancesUpdate() not implemented

### ISSUE THREAD

**Issue by Graig123git** [Hopding/pdf-lib#625]
I am trying to input text into a PDF field however getting the following error (Error): Method PDFSignature.needsAppearancesUpdate() not implemented  can someone clarify what this means and how to fit please ?

**Comment by Graig123git** [comment]
fixed by adding updateFieldAppearances:false		
const pdfBytes = await pdfDoc.saveAsBase64({ updateFieldAppearances: false, dataUri: true });

**Comment by Hopding** [comment]
@Graig123git This is fixed in the latest release (just published a few mins ago). Please try it out and reopen this issue if it doesn't work for you!
