### ISSUE TITLE
Restrict Pdf Editing

### ISSUE THREAD

**Issue by welkaddouri** [Hopding/pdf-lib#627]
We are using **pdf-lib** to generate pdfs . it works perfectly . we are trying to find a way to restrict editing generated PDF,  we did understand that is not possible for now , because permissions pass by encryption.  My question is did you plan in short or medium term to support encryption and permissions ?

**Comment by cboivin80** [comment]
We also need it. What could be the effort to inspire by that file ... ?
https://github.com/foliojs/pdfkit/blob/master/lib/security.js

The standard look almost simple ... 
https://www.cs.cmu.edu/~dst/Adobe/Gallery/anon21jul01-pdf-encryption.txt

**Comment by Hopding** [comment]
Support for setting document permissions is being tracked in https://github.com/Hopding/pdf-lib/issues/472. Support for loading encrypted documents is being tracked in https://github.com/Hopding/pdf-lib/issues/233. 

Adding support for encrypted documents is the next feature I personally plan to work on for pdf-lib. Not sure when I'll get around to document permissions. Happy to provide assistance to anybody that would like to submit a PR for it though. 

Note also that you can set fields to be read-only using the [`PDFField.enableReadOnly()`](https://pdf-lib.js.org/docs/api/classes/pdffield#enablereadonly) method.
