### ISSUE TITLE
How to Click PDFButton ?

### ISSUE THREAD

**Issue by Graig123git** [Hopding/pdf-lib#628]
How do we Click a pdf button ? i have the following code which gets a button however i am unable to click that button after 
getting it. Is there a button.click method ? code below

const button = form.getButton('Secure');
button.click() // Is there such a method

**Comment by Graig123git** [comment]
@Hopding any thoughts on how to do this ?

**Comment by Hopding** [comment]
Hello @Graig123git!

I’m afraid pdf-lib cannot “click” buttons. You can only click buttons inside of a PDF reader. Executing the click action handler of a button requires the runtime of a PDF reader, which pdf-lib does not (and will never) provide. I’m not aware of any other PDF libraries that provide this functionality either.

**Comment by Graig123git** [comment]
Is there any alternative to clicking the Button ?

**Comment by Hopding** [comment]
Not that I know of. But I’m not entirely sure what you mean.

**Comment by NickyMaggon** [comment]
Is is possible to click button and open modal after loading pdf

**Comment by Graig123git** [comment]
@Hopding sorry for the late reply,  I have a PDFButton type field, what i mean is can i some how set this PDFButton to TRUE which would indicate that this PDFButton was click programmatically or set to TRUE.

**Comment by Graig123git** [comment]
@Hopding  here is a reference to the PDFButton that am trying to push/click
<img width="831" alt="Screen Shot 2020-09-29 at 12 54 57 PM" src="https://user-images.githubusercontent.com/45980452/98838068-c5697980-2411-11eb-947d-283fd53b1d8c.png">

**Comment by Graig123git** [comment]
@Hopding are you able to address my previous comments above ?

**Comment by Hopding** [comment]
@Graig123git I’m afraid I don’t understand what it is that you’re trying to do.
