### ISSUE TITLE
WinAnsi cannot encode "ő" (0x0151), "ű" (0x0171)

### ISSUE THREAD

**Issue by LaKing** [Hopding/pdf-lib#629]
It seems that Strings may contain characters that cannot be encoded. 
In my case it's Hungarian, and two common characters.

Is there any way around this?

Thank you, ...

**Comment by Hopding** [comment]
Hello @LaKing!
 
There is indeed a way around this error. Please see https://github.com/Hopding/pdf-lib#fonts-and-unicode.

**Comment by Hopding** [comment]
No worries! Good luck with your project 😄
