### ISSUE TITLE
PDFDropdown.updateAppearances causes tsc error

### ISSUE THREAD

**Issue by dqu123** [Hopding/pdf-lib#630]
https://github.com/Hopding/pdf-lib/blob/581d87e2a12628df94161df72c9d36e661eb7e2c/src/api/form/PDFDropdown.ts#L595
the above line is a recursive type reference that breaks tsc
![image](https://user-images.githubusercontent.com/7023570/96052571-d68f8c80-0e4b-11eb-97d5-3e58277957eb.png)

`package.json`
```
    "ts-loader": "3.1.1",
    "ts-node": "^5.0.1",
    "tsconfig-paths": "^3.1.3",
    "tslint": "5.5.0",
    "tslint-loader": "^3.6.0",
    "typescript": "3.4.5",
```

**Comment by Hopding** [comment]
Does this work in newer versions of TypeScript?

**Comment by dqu123** [comment]
@Hopding works for "typescript": "3.8.3" +
closing.
