### ISSUE TITLE
bbox is undefined when embed TTC type font

### ISSUE THREAD

**Issue by gjSCUT** [Hopding/pdf-lib#634]
Here is my font:
[MEIRYO.TTC.zip](https://github.com/Hopding/pdf-lib/files/5389573/MEIRYO.TTC.zip)

When I called 
```
pdf.embedFont(fs.readFileSync(path.resolve('fonts', 'MEIRYO.TTC')));
```

It throwed undefined exception:
```
TypeError: Cannot read property 'minX' of undefined
    at CustomFontEmbedder.<anonymous> (/home/guojun/HUE/WorkSpace/Develop/recruiting-admin-page/node_modules/pdf-lib/src/core/embedders/CustomFontEmbedder.ts:157:17)
    at step (/home/guojun/HUE/WorkSpace/Develop/recruiting-admin-page/node_modules/pdf-lib/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/guojun/HUE/WorkSpace/Develop/recruiting-admin-page/node_modules/pdf-lib/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/home/guojun/HUE/WorkSpace/Develop/recruiting-admin-page/node_modules/pdf-lib/node_modules/tslib/tslib.js:112:62)
```

**Comment by nigamimi** [comment]
- pdf-lib is using @pdf-lib/fontkit for parsing fonts.
- type definition for fontkit is incorrect
  - [d.ts says fontkit.craete() always returns Font](https://github.com/Hopding/fontkit/blob/master/fontkit.d.ts#L640)
  - but reality it returns TrueTypeCollection when passed binary is TTC without second argument. see implementation
      - https://github.com/Hopding/pdf-lib/blob/master/src/core/embedders/CustomFontEmbedder.ts#L23-L31
      - https://github.com/foliojs/fontkit/blob/master/src/index.js#L9-L15
      - https://github.com/foliojs/fontkit/blob/master/src/base.js#L40-L51
      - https://github.com/Hopding/fontkit/blob/master/src/TrueTypeCollection.js#L21-L23
  - TrueTypeCollection does not  have bbox for its member
 - incorrect type definition allows incorrect codes to pass `tsc`.

I am not really sure that `CustomFontEmbedder` can embed a font if `CustomFontEmbedder#for` accepts an extra argument for `postscriptName`.
I've never tried that or don't have enough knowledge about Font program.

**Comment by Leko** [comment]
Same here on [NotoSansCJK-Regular.ttc and NotoSansCJK-Bold.ttc](https://www.google.com/get/noto/help/cjk/)

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998
