### ISSUE TITLE
Load from Google Cloud Storage returns an empty file with no page

### ISSUE THREAD

**Issue by axelvaindal** [Hopding/pdf-lib#636]
Hello,

Thanks for your library.
I've tried to make it work but I'm kinda stuck so I'm writing here.

I'm trying to load a pdf and generate a 10 pages extract thanks to a cloud function triggered at the moment the upload is complete in Google Cloud Storage.

To do so, here is my code:

```js
  const [[content], { connection }] = await Promise.all([
    manuscriptsBucket.file(manuscriptFileName).download(),
    Mongo.connect(),
  ]);

  const [extract, original] = await Promise.all([
    PDFDocument.create(),
    PDFDocument.load(content.buffer, { throwOnInvalidObject: true }),
  ]);
 
  await extract.copyPages(original, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
  const savedExtract = await extract.save();

  logger.info(`Writing extract document to temporary file...`);
  const filename = `${manuscriptMetadata.filename.split(".")[0]}_extract.pdf`;
  const temporaryLocalFile = path.join(os.tmpdir(), filename);

  fs.appendFileSync(temporaryLocalFile, savedExtract);

  logger.info(`Successfully generated extract.`);

```

`content` here is supposed to be a `Buffer` so I tried to pass the underlying `UInt8Array` representation to your lib, but the result is the same, the pdf is empty and there is no pages inside.
Obviously, the `copyPages` is not copying anything apart from the blank page and the extract is empty as well.

However, it does not throw an error of any kind during the process 😞 
Do you have an insight of why the pdf loaded is empty and have no pages inside?

Note: I've successfully opened/downloaded the uploaded PDF from the Google Cloud Storage, there is no issue with the uploaded file.
Below is a screenshot of the `original` var content supposed to contain the loaded file:

![image](https://user-images.githubusercontent.com/11026659/96373106-98a3a880-116a-11eb-9768-0cc52484f316.png)

**Comment by Hopding** [comment]
Hello @axelvaindal!

Can you please supply a NodeJS script and PDF I can use to reproduce the issue? Note that I’ll need to be able to run it locally on my machine without any connections to Google Cloud Storage.

**Comment by axelvaindal** [comment]
Hello @Hopding !

Pretty hard to reproduce without having access to Google Cloud Storage, as I think the problem relies on the link between the Buffer provided by Google Cloud Storage and the lib 😕 
I can give you the PDF I'm using for my tests though. 
If it can help you know more about what's happening, here it is: 
[edith_et_nous_complet_V2 (3).pdf](https://github.com/Hopding/pdf-lib/files/5397889/edith_et_nous_complet_V2.3.pdf)

Can you test it locally with your lib to see if it's working?
I'll try as well with a local script to see what's going on locally 🤞

**Comment by axelvaindal** [comment]
@Hopding 
```
const fs = require("fs");
const { PDFDocument } = require(`pdf-lib`);

(async () => {
  const content = fs.readFileSync("test.pdf");

  const [extract, original] = await Promise.all([
    PDFDocument.create(),
    PDFDocument.load(content.buffer, { throwOnInvalidObject: true }),
  ]);
  await extract.copyPages(original, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
  const savedExtract = await extract.save();

  fs.appendFileSync("extract.pdf", savedExtract);
})();

```

I've tried this local script locally and it's not working as well with the pdf I sent to you☝️ 
Does that help?

**Comment by Hopding** [comment]
@axelvaindal Looks like you forgot to add the pages to the recipient document after copying them. See https://github.com/Hopding/pdf-lib#copy-pages.

**Comment by axelvaindal** [comment]
OK, I'm a moron. It's working locally now, I'll test on Google Cloud Storage with the pages rightfully added.
Just to know though, why do I need to manually add them even though I'm passing the source and recipient document in the call ? 
Is there a mean to reduce this in a single call by looping automatically on generated pages to add them to the recipient document ? 🤔

**Comment by Hopding** [comment]
No worries! Glad it’s working.

The reason you have to add them manually is that the pages can be added to the recipient document in any order. You could interleave them, or add them backwards, for example. You could even add the same page to the recipient document multiple times. This API allows for that kind of flexibility.

**Comment by axelvaindal** [comment]
Alright, very clear.
Really great job with this library, thanks a lot for your help and your availability!
