### ISSUE TITLE
Error while parsing PDF

### ISSUE THREAD

**Issue by axelvaindal** [Hopding/pdf-lib#638]
Hello,

I'm trying to extract pages from a PDF, but I encounter this error.

```
UnhandledPromiseRejectionWarning: Error: Trying to parse invalid object: {"line":24229,"column":6,"offset":87733096})
    at PDFParser.tryToParseInvalidIndirectObject (/Users/axelvaindal/Downloads/test-lib/node_modules/pdf-lib/cjs/core/parser/PDFParser.js:165:19)
    at PDFParser.<anonymous> (/Users/axelvaindal/Downloads/test-lib/node_modules/pdf-lib/cjs/core/parser/PDFParser.js:209:30)
    at step (/Users/axelvaindal/Downloads/test-lib/node_modules/tslib/tslib.js:141:27)
    at Object.throw (/Users/axelvaindal/Downloads/test-lib/node_modules/tslib/tslib.js:122:57)
    at rejected (/Users/axelvaindal/Downloads/test-lib/node_modules/tslib/tslib.js:113:69)
(node:30894) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30894) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The PDF is 80MB large, so I can't put it here.
Is there any way I can verify the integrity of the PDF document before I try to process it?

**Comment by Hopding** [comment]
There are a number of PDF validation tools you can find online. The only way to check with pdf-lib specifically is to call `PDFDocument.load` and see if it succeeds.

A possible cause of the error you shared is that the document is encrypted. This is a pretty common occurrence. PDFs can still be encrypted even if you can open them without a password.

**Comment by axelvaindal** [comment]
Alright, I'll `try catch` the load and fallback if any error during the process.

Thanks for your answer.

**Comment by OrganicChem** [comment]
Will you have be able to release new code that can parse and merge a PDF despite having password encryption and it's ability to open fine?

By the way, you are doing the community a great job with this robust and powerful PDF tool.
