### ISSUE TITLE
set PDF Version

### ISSUE THREAD

**Issue by ezehurt** [Hopding/pdf-lib#640]
I would like to know the version of PDF can be changed at the moment of generate. Currently it is generating with 1.6 PDF Version. I need to be 1.4

Thanks.-

**Comment by Hopding** [comment]
Hello @ezehurt! pdf-lib does provide any APIs for changing the output version. See also https://github.com/Hopding/pdf-lib/issues/541#issuecomment-695361756.

**Comment by ezehurt** [comment]
hello @Hopding, I made the change but i still have a problem. The problem is with Adobe Reader (when i open the generated file with other viewer there is no problem)
![image](https://user-images.githubusercontent.com/7167879/99648385-47315680-2a53-11eb-923a-c2f426257e1f.png)
And when I hold ctrl and click on acept it's says a Dicctionary Object was spected.
Any suggest?

**Comment by Hopding** [comment]
Not sure. Please open a new issue with all the code and PDFs necessary to reproduce the problem and I'll take a look when I get a chance.

**Comment by ezehurt** [comment]
> Not sure. Please open a new issue with all the code and PDFs necessary to reproduce the problem and I'll take a look when I get a chance.

Thanks a lot. I already opened
