### ISSUE TITLE
I can't set color: rgb(0,74,153) 

### ISSUE THREAD

**Issue by sundsx** [Hopding/pdf-lib#646]
Hi, if i try to set color rgb(0,74,153)  which is a strong blue, i get an error.

Uncaught (in promise) Error: `green` must be at least 0 and at most 1, but was actually 74

it seems to accept only values from 0 to 1.
for example color:
rgb (0,0,1); are ok
rgb(0,74,153) are bad

I need to use color like illustrator rgb palette which is expressed with values greater than 0 and 1.

How can I solve this little problem?

Thank you

**Comment by Hopding** [comment]
Hello @sundsx! Good question. pdf-lib expresses colors as fractional values between 0 and 1. You can divide each of your color component values by 255 to produce the correct fractional value. For example:
```js
rgb(0 / 255, 74 / 255, 153 / 255)
```

**Comment by sundsx** [comment]
Thank you!
pdf-lib is awesosome. I hope in future will be possible insert directly
without divide.



Il giorno sab 14 nov 2020 alle 19:27 Andrew Dillon <notifications@github.com>
ha scritto:

**Comment by ricky11** [comment]
this solved my issue, but why is it expressed as a fractional value? couldn't find that in the documents when searching for how color input should be represented.  thanks.

**Comment by Hopding** [comment]
Happy to accept documentation update PRs!

**Comment by roboli** [comment]
> Happy to accept documentation update PRs!

Not much but hope it helps https://github.com/Hopding/pdf-lib-docs/pull/39

**Comment by yeahoffline** [comment]
very nice surprise feature... 🎊
