### ISSUE TITLE
witch font I can use instead of helveticaFont

### ISSUE THREAD

**Issue by faisal-almalki** [Hopding/pdf-lib#647]

**Comment by faisal-almalki** [comment]
I have pdf and I want to write in it but I also want to change the default font is their solution for that?

**Comment by canhpc** [comment]
The list of supported fonts can be found here: https://pdf-lib.js.org/docs/api/enums/standardfonts.
You can also use your font by following the example here: https://www.npmjs.com/package/pdf-lib#embed-font-and-measure-text.  ( I have not tried this so I am not sure how it work)

**Comment by Hopding** [comment]
In addition to the links provided by @canhpc, you can see examples of how to change the default font in the [Usage Examples](https://github.com/Hopding/pdf-lib#usage-examples) section of the README.
