### ISSUE TITLE
is linearization available in this library?

### ISSUE THREAD

**Issue by lioj** [Hopding/pdf-lib#649]

**Comment by Hopding** [comment]
Hello @lioj! pdf-lib does not provide any APIs for outputting linearized PDF documents.

**Comment by JacobSiegle** [comment]
Linearized PDF documents is a hard requirement for many when streaming large PDF files it would be great to see support come to pdf-lib especially since using pdf-lib removes linearization from PDFs. 

https://www.pdftron.com/blog/pdf-format/what-is-pdf-linearization/
