### ISSUE TITLE
How to Add PNG image on multiple selected pages 

### ISSUE THREAD

**Issue by princ09** [Hopding/pdf-lib#651]
I have stored page numbers as key and corresponding images (PNG  as base64) as the value in Dictionary. Now I am iterating that dictionary to see if the page has images then add it on pdf. 
![image](https://user-images.githubusercontent.com/47990313/97484571-e2686c00-197e-11eb-8540-8f1f32b28c68.png)
![image](https://user-images.githubusercontent.com/47990313/97484641-fdd37700-197e-11eb-8d6f-825b3a9f9599.png)
I am getting png base64 correctly. my logic is re-loading pdf bytes that I get after saving png image on one page.
above code is not working, I don't know where I am making mistake. I am getting pdf with no changes.

**Comment by Hopding** [comment]
Hello @princ09! From what you've shared, I'm guessing that you are not passing the correct value to `embedPng`. But I can't say for sure since I have no context about your code. If you'd like additional help, please share HTML/JS files that I can use to reproduce the issue.

**Comment by princ09** [comment]
Hi, Thank you for the reply and sorry for the late reply. can't share a snippet, This is all I can share. After doing Much R&D, I found that the issue is with Async and Await, Pdf gets download before updating. 
The above code works fine with pdf with a smaller size (in KBs), but not working with pdf (in MBs).
Is there any way to be sure that every process runs one after another strictly.
