### ISSUE TITLE
Bug on addPage method

### ISSUE THREAD

**Issue by woodfordnono** [Hopding/pdf-lib#652]
I created a function to add a number of pages of the copied pdf(Copy Pages Feature) into the existing pdf(Modify page Feature) using while loop dynamically. The problem I encountered is that when using addPages method to add more than 2 copies of the copied file's selected page makes the rest of the pages corrupted while the first 2 two pages are ok. While the insertPage method makes the first page ok and the rest of the pages are corrupted.

**Comment by Hopding** [comment]
Hello @djxcds! Can you please share code and PDF files that I can use to reproduce the issue?

**Comment by djxcds** [comment]
Sorry I am late replying back cause I took a break for a week to lessen my stress and I feel better as ever.

Back to the problem, I use your example on copy page and added comments there. Here is the link https://jsfiddle.net/djxcds/6b53fyou/10/

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
