### ISSUE TITLE
How to set radio button style to square ?

### ISSUE THREAD

**Issue by hovikkhachatryan** [Hopding/pdf-lib#653]
I have a pdf where I added radio buttons with custom style (border color, button style is square, ...) using acrobat pro.
After editing the document via pdf-lib the button style is being changed from square to circle. Is there a way to set button style programmatically ? Thanks!

**Comment by Hopding** [comment]
Hello @hovikkhachatryan! Currently the only way to do this would be to write your own appearance provider that produces square radio buttons and pass it to [`PDFRadioGroup.updateAppearances`](https://pdf-lib.js.org/docs/api/classes/pdfradiogroup#updateappearances).
