### ISSUE TITLE
TS compiler error: 'provider' is referenced directly or indirectly

### ISSUE THREAD

**Issue by mcmule** [Hopding/pdf-lib#655]
Hello guys,

I'm using pdf-lib latest version: 1.11.2 with Typescript 3.3, in a Node.js app.
I get this compiler error: 

`node_modules/pdf-lib/ts3.4/cjs/api/form/PDFDropdown.d.ts(379,38): error TS2502: 'provider' is referenced directly or indirectly in its own type annotation.`

Given the path above ("ts3.4"), I guess this error may be related to my version of TypeScript, however, updating TS in our project is currently not possible right now, short term speaking. Does anyone with a deeper understanding of Typescript could explain to me what's happening and :
1) tell me if this is a bug or a TS version issue,
2) (is TS version related) provide advice about how I could solve this on my side,

Cheers,

**Comment by Hopding** [comment]
Does the error persist if you use a newer version of TypeScript?

**Comment by Hopding** [comment]
Note that you can just setup a sample project to test it out.

**Comment by mcmule** [comment]
Hi! 
I've tried in a new sample project, but I'm not able to reproduce this compiler error yet.
I tried to use both TS 3.3 (the same version as my main project) and TS 3.4.
I also tried to tweak compiler configuration to get the same on both side, but I'm not able to get this error in a sample project yet. I'll keep on trying

**Comment by mcmule** [comment]
So, I have tried multiple things, but has never been able to reproduce it in a small, clean sample project. Not yet at least.

Since I need to move forward, I have downgraded pdf-lib to 1.10, before "form features". 

I understand it may be annoying for people w. the same issue in the future to find no workaround here but I guess my issue is deeply related to : typescript version, @types/node version (had some false positive with it), tsc & tsc configuration.

You can close this. When I update pdf-lib and our environment sometime (node, typescript), if I encounter this issue once again, I'll add new info here.
Thank you for the awsome package :)

**Comment by Hopding** [comment]
That's quite interesting. Downgrading pdf-lib until you're able to update your node and TS versions seems like a reasonable solution. Please do update this issue if you still encounter it after updating!

**Comment by tandy077** [comment]
**A=>Error message：**
        ERROR in node_modules/pdf-lib/ts3.4/cjs/api/form/PDFDropdown.d.ts:400:38 - error TS2502: 'provider' is referenced directly or indirectly in its own type annotation.
        
        400     updateAppearances(font: PDFFont, provider?: AppearanceProviderFor<PDFDropdown>): void;
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        
        ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
        i ｢wdm｣: Failed to compile.

**B=>Version information：**
**node -v>** v14.21.3
**npm -v>**  6.14.18
**ng -v=>**
@angular-devkit/architect         0.803.29
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.3.29
@angular-devkit/schematics        8.3.29
@angular/cdk                      8.2.3
@angular/cli                      8.3.29
@angular/elements                 9.0.0
@angular/material                 8.2.3
@ngtools/webpack                  8.3.29
@schematics/angular               12.2.18
@schematics/update                0.803.29
rxjs                              6.4.0
typescript                        3.4.3
webpack                           4.39.2
