### ISSUE TITLE
RTL document 

### ISSUE THREAD

**Issue by YumcoderCom** [Hopding/pdf-lib#657]
I would be obliged if you could kindly provide an example to create a right to left document, such as :

![image](https://user-images.githubusercontent.com/29568969/98230004-dfb5da00-1f6f-11eb-9ad2-9fef4d025a1e.png)

https://fonts.google.com/specimen/Amiri?subset=arabic&query=amiri&sidebar.open=true&selection.family=Amiri#standard-styles

**Comment by seriiix** [comment]
RTL is a needed feature for Persian/Arabic languages (and many more).

**Comment by ofiroha** [comment]
+1 really needed feature!

**Comment by Hopding** [comment]
Right now the only way to do this is by drawing each character individually. Better support for typography and text layout is on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
