### ISSUE TITLE
Forking and NPM install

### ISSUE THREAD

**Issue by Wian-TMC** [Hopding/pdf-lib#658]
Hi There, When I forked the repo, I want to be able to install the fork via npm again but  it does not compile to javascript. What is the command needed in the package.json so that the package is usable after forking and reinstalling using npm?

**Comment by Hopding** [comment]
Hello @Wian-TMC. See https://github.com/Hopding/pdf-lib/blob/master/CONTRIBUTING.md#compiling-the-project.
