### ISSUE TITLE
Best way to rotate all document's  page?

### ISSUE THREAD

**Issue by facku** [Hopding/pdf-lib#659]
Hi, whats the best way to rotate all page in a pdf document?

**Comment by Hopding** [comment]
Hello @facku! See the following APIs:
* [`PDFDocument.getPages`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#getpages)
* [`PDFPage.setRotation`](https://pdf-lib.js.org/docs/api/classes/pdfpage#setrotation)
