### ISSUE TITLE
Dimensions and aligning issues when trying to draw a rectangle 

### ISSUE THREAD

**Issue by fullcycleRay** [Hopding/pdf-lib#66]
Hi Hopding,
Thanks for the good work, we are using this library to add a redact feature on the PDF. 
So we have used the translate to set the axis as (0, pageheight). Whenever we increase the width of the box, the position of our box does appear in the place where we actually placed it in our frontend editor, it works perfectly fine for a square box.

**Comment by Hopding** [comment]
Hello @fullcycleRay.

I've having a bit of trouble visualizing exactly what's happening. Can you share some example code, and some sample PDFs or screenshots that demonstrate the problem?

-----

Also, you mentioned you are implementing a redact feature. It sounds like you are doing this by drawing filled-in rectangles on top of the redacted content. I just want to caution you that this approach **does not remove the information from the PDF file**. This simply prevents it from being visible in standard PDF viewers. If an attacker wants to access the redacted info in the modified file, they can absolutely still do this. 

Obviously, I don't know the full context here, so this may not be a concern for you. I just want to caution you in case you have to comply with legal requirements or the like.

**Comment by Hopding** [comment]
I'm going to go ahead and close this issue for now. Feel free to reopen it if you're still having trouble!
