### ISSUE TITLE
TextField setText custom font

### ISSUE THREAD

**Issue by raducostea** [Hopding/pdf-lib#661]
Can't seem to figure out how to use custom font on TextFields

```
        const fontData = fs.readFileSync('arialuni.ttf');
        const pdfDoc = await PDFDocument.load(fileData.Body);
        pdfDoc.registerFontkit(fontkit)
        const leFont = await pdfDoc.embedFont(fontData);
        const form = pdfDoc.getForm();
        form.updateFieldAppearances(leFont);

        const pdfField = form.getTextField(field);
        pdfField.setText('Doamnă Judecător');
```

Getting
```
 Error: WinAnsi cannot encode "ă" (0x0103)
```

If i try with
```
        const page = await pdfDoc.getPage(0);
        page.drawText('Doamnă/Domnule Judecător delegat', {
            font: leFont,
            size: 20,
            x: 10,
            y: 10,
        });
```

This works just fine, so the font i am using is ok.

I also tried with `pdfField.defaultUpdateAppearances(leFont);` but same error.

**Comment by Hopding** [comment]
@raducostea Please see the example in [this](https://github.com/Hopding/pdf-lib#creating-and-filling-forms) section of the README. Note that `form.updateFieldAppearances(yourCustomFont);` must be called after you have finished making other changes to the form and its fields.
