### ISSUE TITLE
Form fields - preserve existing style

### ISSUE THREAD

**Issue by ajaishankar** [Hopding/pdf-lib#663]
I'm loading an existing PDF and filling out form fields.

The text fields have a font style of Courier and the checkboxes checked state is a X

If I load the doc and just save without touching anything in the doc - the existing style is preserved.

But as soon as a field is touched the current style is lost!

```
  doc
    .getForm()
    .getFields()
    .forEach((field) => field.disableReadOnly())

  doc.save()
```

Is it possible to preserve the current style (annotation) when setting field values?

**Comment by mrlowe** [comment]
@Hopding I'm new to this codebase, but maybe we do need to do "this" in order to preserve the acrofield resources? https://github.com/Hopding/pdf-lib/blob/dfe7c47ee2eba7567710cd6e6bb93fab4d8d9ec6/src/api/form/PDFField.ts#L400

**Comment by Hopding** [comment]
Hello @ajaishankar @mrlowe! By default, pdf-lib tries to automatically detect modified form fields and updates their appearances if you access the form of a document. But you can disable this behavior by setting the [`updateFieldAppearances`](https://pdf-lib.js.org/docs/api/interfaces/saveoptions#optional-updatefieldappearances) option to `false` in [`PDFDocument.save`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#save):
```js
await pdfDoc.save({ updateFieldAppearances: false });
```

Note that if you do this, pdf-lib will not automatically update any field appearances. If you want certain field appearances to be updated, you can do so by calling their respective `defaultUpdateAppearances` method. For example, [`PDFTextField.defaultUpdateAppearances`](https://pdf-lib.js.org/docs/api/classes/pdftextfield#defaultupdateappearances).

pdf-lib is unable to extract existing fonts from a document, so you cannot use preexisting fonts to fill form fields of a PDF. If you want to modify the content of a text field using a font other than Helvetica, you will have to embed a font (custom or standard) with [`PDFDocument.embedFont`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#embedfont) and pass it to [`PDFForm.updateFieldAppearances`](https://pdf-lib.js.org/docs/api/classes/pdfform#updatefieldappearances).

**Comment by ajaishankar** [comment]
@Hopding Thanks for the great library! I tried the following

```
const courierBold = doc.embedStandardFont(StandardFonts.CourierBold)

const form = doc.getForm()
const fields = form.getFields()

fields.forEach(field => {
  if (field instanceof PDFTextField) {
    field.defaultUpdateAppearances(courierBold)
    field.setText('Test')
  }
})

form.updateFieldAppearances(courierBold)

return doc.save({ updateFieldAppearances: false })

```
At this point, the fields show up as Courier Bold as expected. But as soon as I click edit a field, it reverts to Helvetica. Not sure why this would be happening?

**Comment by Hopding** [comment]
@ajaishankar Would you please open a new issue for this (e.g. "Text field switches fonts when editing")? Please also include a PDF that I can use to reproduce the issue.
