### ISSUE TITLE
PDF Download from React-Express

### ISSUE THREAD

**Issue by fsanna23** [Hopding/pdf-lib#667]
I'm trying to download a PDF I created on an Express server through an HTTP request made from a React app. The PDF is readable if downloaded from Express, but as soon as I pass it to React I can't seem to get a readable PDF, it doesn't open, like the content is wrong. I read the issue #131 but it didn't help me.
Express tells me that the PDF I generated is a Uint8Array, so I tried to pass it to React as an ArrayBuffer, without success.
The React code is the following (I'm using Axios for the HTTP requests and downloadjs to create a browser download):

```
let pdfResponse = await axios.get(
        "http://localhost:9000/getgeneratedpdf",
        { responseType: "arraybuffer" }
      );
let myBuffer = new Blob(pdfResponse.data, {
        type: "application/pdf",
      });
download(myBuffer, "certificate.pdf", "application/pdf");
```

What could the problem be?

**Comment by Hopding** [comment]
Hello @fsanna23! I'm not sure how to do this with `axios`. I use `axios` a lot for sending/receiving JSON, but I've had trouble getting it to handle binary data properly. This is what I would do with `fetch`:
```js
const pdfBytes = await fetch('http://localhost:9000/getgeneratedpdf').then(res => res.arrayBuffer());
download(pdfBytes, 'certificate.pdf', 'application/pdf');
```
See also https://github.com/Hopding/pdf-lib/issues/163 for an example of how to return a PDF generated with pdf-lib from an express server.

**Comment by nafetswirth** [comment]
@fsanna23 Ran into something similar some time ago, with axios you can do it like this

```js
const existingPdfBytes = await axios.get(url, { responseType: 'arraybuffer' })
      .then((res) => res.data)
```

FYI @Hopding :)
