### ISSUE TITLE
interactive editing?

### ISSUE THREAD

**Issue by waspinator** [Hopding/pdf-lib#67]
Is there a plan to support integration with pdf.js or some other viewer to allow for interactive editing? i.e. adobe acrobat in a browser.

an old project: https://github.com/instructure/pdf-annotate.js

**Comment by louisxie0830** [comment]
Could it support PDF digital signatures?

**Comment by Hopding** [comment]
Hello @louisxie0830. Are you talking about adding/filling PDF signature fields? If so, then the answer is yes. `pdf-lib` supports acroform manipulation. See [here](https://github.com/Hopding/pdf-lib/issues/39) and [here](https://github.com/Hopding/pdf-lib/issues/48) for more info. Let me know if you have any questions!
