### ISSUE TITLE
run a function when PDFButton is clicked

### ISSUE THREAD

**Issue by NickMakesGames** [Hopding/pdf-lib#671]
hi all! I'm trying to create an interactive PDF, and I'm interested in using buttons to help the user with some functionality. Is it possible to create a PDF with a button that can modify other fields in the PDF? Something like the following:

```javascript
    const sumField = form.createTextField('sum');
    sumField.addToPage(page, { x: 25, y: 75, height: 25, width: (width - 50) / 2, borderWidth: 2 });
    sumField.setText('10');


    const addButton = form.createButton('add');
    // I can't find anything in documentation for the following:
    addButton.onClick = () => {
        const currentText = staminaField.getText()
        const textAsNum = parseInt(currentText, 10);
        staminaField.setText(textAsNum + 10);
    }
```

**Comment by Hopding** [comment]
Hello @NickMakesGames!

This is possible to do, but it's not quite as straightforward as the example you showed. Here's an example:
```js
import { PDFDocument, PDFHexString, PDFName } from 'pdf-lib';

(async () => {
  const pdfDoc = await PDFDocument.create();

  const page = pdfDoc.addPage();

  const form = pdfDoc.getForm();

  const button = form.createButton('foo.bar');
  button.addToPage('Hello World!', page, {
    width: 100,
    height: 50,
    x: page.getWidth() / 2 - 100 / 2,
    y: page.getHeight() / 2 - 50 / 2,
  });

  const helloWorldScript = 'console.show(); console.println("Hello World!");';
  button.acroField.getWidgets().forEach((widget) => {
    widget.dict.set(
      PDFName.of('AA'),
      pdfDoc.context.obj({
        U: {
          Type: 'Action',
          S: 'JavaScript',
          JS: PDFHexString.fromText(helloWorldScript),
        },
      }),
    );
  });

  const pdfBytes = await pdfDoc.save();
})();
```

This produces the following file: [out.pdf](https://github.com/Hopding/pdf-lib/files/5541429/out.pdf) (note that you'll have to open it in Adobe Acrobat for the JavaScript to work when you click the button - most PDF readers don't support JavaScript).

You'll want to familiarize yourself with how embedded JavaScript works in PDF files: [JavaScript for Acrobat API Reference](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/js_api_reference.pdf).

If you end up creating any cool scripts, please do share! I'm sure others would find them very useful to reference.

**Comment by herbbetz** [comment]
Sorry, but why is the one 'button' comprised of several widgets? Github copilot and all other AI that I tried, have a hard time to get the code right for embedding the JS and connecting the 'button' action to it. Could you clarify the above question about summing up 2 fields a bit further for me? I tried the appended JS code, but nothing happens on pressing the button in the resulting pdf.

[calcsum.txt](https://github.com/user-attachments/files/18722995/calcsum.txt)

**Comment by herbbetz** [comment]
const { PDFDocument,  PDFHexString, PDFName, StandardFonts } = require('pdf-lib');
const fs = require('fs').promises;

async function createSumPDF() {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([550, 750]);
  const form = pdfDoc.getForm();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);

  // Create input fields
  const number1Field = form.createTextField('number1');
  const number2Field = form.createTextField('number2');
  // Create output field
  const sumField = form.createTextField('sum');

  const button = form.createButton('calculate.button');
  
  // Position and style fields
  number1Field.addToPage(page, { x: 50, y: 700, width: 100, height: 30 });
  number2Field.addToPage(page, { x: 50, y: 650, width: 100, height: 30 });
  sumField.addToPage(page, { x: 50, y: 600, width: 100, height: 30 });
  button.addToPage('Calculate', page, {x: 50, y: 550, width: 100, height: 30 });

  // Add labels
  page.drawText('Number 1:', { x: 50, y: 740, size: 12, font });
  page.drawText('Number 2:', { x: 50, y: 690, size: 12, font });
  page.drawText('Sum:', { x: 50, y: 640, size: 12, font });
  
  /*
  const calculateAction = pdfDoc.addJavaScript('main', `
    var calculateSum = function() {
      var field1 = this.getField("number1");
      var field2 = this.getField("number2");
      var resultField = this.getField("sum");
      
      if (field1 && field2 && resultField) {
        var num1 = parseFloat(field1.value) || 0;
        var num2 = parseFloat(field2.value) || 0;
        var sum = num1 + num2;
        resultField.value = sum.toString();
      }
    };
  `);
  */

  const sumScript =  `var calculateSum = function() {
      var field1 = this.getField("number1");
      var field2 = this.getField("number2");
      var resultField = this.getField("sum");
      
      if (field1 && field2 && resultField) {
        var num1 = parseFloat(field1.value) || 0;
        var num2 = parseFloat(field2.value) || 0;
        var sum = num1 + num2;
        resultField.value = sum.toString();
      }
    };`;
  button.acroField.getWidgets().forEach((widget) => {
    widget.dict.set(
      PDFName.of('AA'),
      pdfDoc.context.obj({
        U: {
          Type: 'Action',
          S: 'JavaScript',
          JS: PDFHexString.fromText(sumScript),
        },
      }),
    );
  });
  // button.setAction(calculateAction);
  // button.setJavaScript('main');

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}

async function savePDFToDisk() {
  try {
    const pdfBytes = await createSumPDF();
    await fs.writeFile('calcsum.pdf', pdfBytes);
    console.log('PDF successfully created');
  } catch (error) {
    console.error('Error creating or saving PDF:', error);
  }
}

savePDFToDisk();

**Comment by DishantPal** [comment]
For anyone who is droping by to see how to submit a form to a URL

This is you can do it

```javascript
const submitButton = form.createButton('foo.bar');
submitButton.addToPage('Hello World!', firstPage, {
  width: 100,
  height: 50,
  x: firstPage.getWidth() / 2 - 100 / 2,
  y: firstPage.getHeight() / 2 - 50 / 2,
});

// const helloWorldScript = 'this.submitForm("https://webhook.site/d722f7c9-5bd2-4dd7-8adb-5e06c2ea6b0f", true); console.show(); console.println("Hello World!");';
// const helloWorldScript = 'this.submitForm({cURL: "https://webhook.site/d722f7c9-5bd2-4dd7-8adb-5e06c2ea6b0f", cSubmitAs:"PDF", cCharSet:"utf-8"}); console.show(); console.println("Hello World!");';
const helloWorldScript = 'this.submitForm({cURL: "https://webhook.site/d722f7c9-5bd2-4dd7-8adb-5e06c2ea6b0f", cSubmitAs:"HTML", cCharSet:"utf-8"}).then(r => {app.alert("Form Submitted!");});  console.show(); console.println("Hello World!");';

// const helloWorldScript = 'this.submitForm({cURL: "https://webhook.site/d722f7c9-5bd2-4dd7-8adb-5e06c2ea6b0f", cSubmitAs:"XML", cCharSet:"utf-8"}); console.show(); console.println("Hello World!");';
submitButton.acroField.getWidgets().forEach((widget) => {
  widget.dict.set(
    PDFName.of('AA'),
    pdfDoc.context.obj({
      U: {
        Type: 'Action',
        S: 'JavaScript',
        JS: PDFHexString.fromText(helloWorldScript),
      },
    }),
  );
});
```

These links can help to better understand the logic:
https://www.pdfill.com/download/Acro6JSGuide.pdf
https://www.pdfscripting.com/public/Free_Videos.cfm#CoreJS
https://www.gnostice.com/nl_article.asp?id=310&t=An_
https://acrobatusers.com/tutorials/dynamically-setting-submit-e-mail-address/index.html
https://acrobatusers.com/tutorials/submitting-data/#:~:text=The%20submitForm()%20function%20is,PDF%2C%20and%20custom%20XML%20formats.
