### ISSUE TITLE
Unable to get value entered from the user in Text Field

### ISSUE THREAD

**Issue by sachin-thaware** [Hopding/pdf-lib#672]
The value can be successfully received if we set it via method setText() programmatically. But it is always undefined user enters value into the textbox. Please let me know the solution

**Comment by Hopding** [comment]
Hello @sachin-thaware! Please share code and a PDF that I can use to reproduce the issue.

**Comment by sachin-thaware** [comment]
I am clicking a button from html which will call the function checkAnswer()


async  function checkAnswer(){
  

  console.log('check answer called');

  pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true ,updateFieldAppearances: true });
  
  form = pdfDoc.getForm()

  

  const fields = form.getFields()


  fields.forEach(field => {
  const name = field.getName();
  const field1 = form.getField(name);
    field1.enableReadOnly();
   // field_count++;
  })// count the number of fields in form

    
  
  for(k=0;k<i; k++)// set text to current fields
  {
    const current_field_name = fields[k].getName()
    const textField = form.getTextField(current_field_name)

   //  parent.postMessage("sachin","*");  //  `*` on any domain    

const text = textField.getText();

console.log('Text field contents:', text);  ///////////////////// This is Always Undefined ////////////////////////////


    
  var field_name = current_field_name;

  
  var res = field_name.split("#");
  var myres=res[0].split("-");
  var correct_answer = myres[1];
  var answer_difficulty = res[1];



    
  if (correct_answer == value) {
    correctAnswer(answer_difficulty);
    console.log("Correct answert is "+correct_answer);
    textField.setText(correct_answer)
    i++
  }else {
 
    inCorrectAnswer();
    i--;
  }
  
  
  }
  
  if(i!=field_count)//get the current field
  {
    const current_field_name = fields[i].getName()
    const field2 = form.getField(current_field_name);
    field2.disableReadOnly();
  console.log(`${current_field_name}`
  )   
 
}
  else{
      console.log("no fields to display") //enter code when end of the field. It may be show code of submit button
      document.getElementById("submit_exam").disabled = false;       
    }
  



 pdfDataUri = await pdfDoc.saveAsBase64({ dataUri: true });

  document.getElementById('viewer').innerHTML = `
    <iframe id="iframe" src="${pdfDataUri}#zoom=100" height="100%" width="100%"/>
    `;

}

**Comment by sachin-thaware** [comment]
[story1.pdf](https://github.com/Hopding/pdf-lib/files/5541899/story1.pdf)


This is the pdf on which i am working

**Comment by sachin-thaware** [comment]
Please also do let me know if we can place 'keyUp' event on text field , so that we can grab user input from text box

**Comment by Hopding** [comment]
Thanks for sharing the JS and PDF. But I'm afraid this is insufficient for me to reproduce your issue. Please share a complete working example. In your case, that would mean an HTML file when all the necessary JS and HTML I need to reproduce your specific issue.

**Comment by sachin-thaware** [comment]
Sure. Herewith attached html and pdf files

[Uploading story1.pdf…]()

**Comment by sachin-thaware** [comment]
Sure. Herewith attached html and pdf files

[pdfdemo.zip](https://github.com/Hopding/pdf-lib/files/5542591/pdfdemo.zip)

**Comment by Hopding** [comment]
The PDF you are loading contains empty text fields. This means that when you try to read the field values, they will be `undefined` (or an empty string). Editing the PDF in a browser (e.g. Chrome) does not send a modified field back to your server. So every time you fetch the file from your server and load it with pdf-lib, you are getting the original unmodified file.

**Comment by sachin-thaware** [comment]
Thanks for the response. I had understood the issue but i thought saveasBase64 will work to save pdf after entering text from user.
Can you please also let me know hot to addEventListner() on text field?

**Comment by Hopding** [comment]
@sachin-thaware I don't have time to provide a complete example right now. But you can take a look at https://github.com/Hopding/pdf-lib/issues/671#issuecomment-727262137 to see how to add JavaScript event handlers to a form field.
