### ISSUE TITLE
How to set eventListner on pdf text field

### ISSUE THREAD

**Issue by Anthaware** [Hopding/pdf-lib#673]
is there any way to get a keypress event on the text field. 
for example :

textField.addEventListener("keyup", event => {
 
  // do something
});

**Comment by Hopding** [comment]
Hello @Anthaware! Maybe, depending on what specifically you're trying to do. But the listener would only work if you opened the document in Adobe Acrobat. See https://github.com/Hopding/pdf-lib/issues/672#issuecomment-732507019.
