### ISSUE TITLE
Text rendering problem in Thai Language

### ISSUE THREAD

**Issue by jewkub** [Hopding/pdf-lib#675]
### Code used to embed the font

```javascript
import * as fs from 'fs/promises';
import fontkit from '@pdf-lib/fontkit';
import { PDFDocument } from 'pdf-lib'
const pdfDoc = await PDFDocument.create();
pdfDoc.registerFontkit(fontkit);
const fontData = await fs.readFile('[myfont].ttf');
const myFont = await pdfDoc.embedFont(fontData, { subset: true });
const page = pdfDoc.addPage();
page.drawText('น้ำ คล้ำ', {
  font: myFont,
  x: 50,
  y: 50
});
const pdfBytes = await pdfDoc.save();
await fs.writeFile('[file].pdf', pdfBytes);
```

### Results

| Fonts | In Generated PDF | In MS Word |
|---|---|---|
| Angsana New | ![image](https://user-images.githubusercontent.com/6770593/99191552-ef1ef980-279f-11eb-8cf9-6807eeefb93e.png) | ![image](https://user-images.githubusercontent.com/6770593/99191528-cd257700-279f-11eb-93b3-9b9b5b3be385.png) |
| Cordia New | ![image](https://user-images.githubusercontent.com/6770593/99191845-1971b680-27a2-11eb-955d-a0b26bb5edd7.png) | ![image](https://user-images.githubusercontent.com/6770593/99191824-019a3280-27a2-11eb-91cb-9ce5e337fee5.png) |

Position of some float characters are not valid when they are used together in one consonant. Am I missing configurations ? Thanks in advance.

**Comment by Hopding** [comment]
Seems to be related to https://github.com/Hopding/pdf-lib/pull/726. 

@jewkub what if you set `{ subset: false }` when embedding the font?

**Comment by zapkub** [comment]
@Hopding I also dig into this issue ( I also try to use Cordia New ) the problem happens only in Microsoft standard Thai font set.

It looks like `fontkit` has some bug inside Ligature rule table parsing for Substitution table ( I guess ) and this also related to #726 too

**Comment by Hopding** [comment]
Added to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
