### ISSUE TITLE
Drag and drop or resize a drawn image

### ISSUE THREAD

**Issue by meliodev** [Hopding/pdf-lib#676]
Hello, I couldn't figure out how to manipulate an image after drawing it on a pdf. I mean.. is it possible to drag it and drop it or resize it (using finger touch) before saving the new pdf ? Thanks for the support.

**Comment by Hopding** [comment]
Hello @meliodev! pdf-lib does not provide any kind of UI or user-interactive functionality. It only provides JS/TS APIs to create and manipulate documents. You'd have to build the interface yourself and just hook into pdf-lib APIs.
