### ISSUE TITLE
Added images & text not appearing in Illustrator

### ISSUE THREAD

**Issue by ckdot** [Hopding/pdf-lib#679]
This is my sample code - it's basically the same like the documentation example code:
```js
const { PDFDocument } = require('pdf-lib');
const fs = require('fs');

// PDF Modification
async function modify() {
    const pdfDoc = await PDFDocument.load(fs.readFileSync('./source.pdf'));
    const pages = pdfDoc.getPages();
    const imageBytes = fs.readFileSync('./source.png');
    const image = await pdfDoc.embedPng(imageBytes);

    pages[0].drawImage(image, {
        width: pages[0].getWidth(),
        height: pages[0].getHeight(),
        x: 0,
        y: 0
    })

    pdfDoc.save().then((pdfBytes) => {
        fs.writeFileSync('./target.pdf', pdfBytes);
    });
}

modify();
```

This basically works, if I open the PDF afterwards with several tools they will show the placed image. But it doesn't work in Illustrator. The image layer just doesn't show up. There's no error message or anything when opening the file. What also doesn't work for Illustrator is:
- drawing text
- changing the page width

Do you have any idea if this can be fixed or is there a workaround?

**Comment by Hopding** [comment]
Hello @ckdot! I'm not sure what would cause this. I don't have Adobe Illustrator and am not familiar with how it works. Have you tried feeding your output PDF into a PDF validator to make sure its valid? E.g. https://www.pdf-online.com/osa/validate.aspx or https://github.com/qpdf/qpdf?
