### ISSUE TITLE
Unhandled bounds

### ISSUE THREAD

**Issue by btecu** [Hopding/pdf-lib#680]
While testing filling forms I noticed a few cases where the text had really small font size.
It turned out that the issue was a negative bound, which apparently is valid.
So likely we need `Math.abs(bounds.height)` here:
https://github.com/Hopding/pdf-lib/blob/581d87e2a12628df94161df72c9d36e661eb7e2c/src/api/text/layout.ts#L50

**Comment by Hopding** [comment]
The changes in this PR were just released in `v1.13.0`.
