### ISSUE TITLE
Draw Image flip 180 for some pdf files

### ISSUE THREAD

**Issue by meet0929** [Hopding/pdf-lib#681]
Why does draw image flip the image 180 degrees for some pdf files?

**Comment by Hopding** [comment]
Hello @meet0929! The pages in those PDF documents are probably rotated. You'll have to manually detect and account for rotated pages. pdf-lib provides APIs to detect (and change) page rotation. Check out some of the issues related to rotated pages: https://github.com/Hopding/pdf-lib/issues?q=is%3Aissue+rotation.
