### ISSUE TITLE
Border default

### ISSUE THREAD

**Issue by btecu** [Hopding/pdf-lib#682]
If a `TextField` has a background color but no border (transparent), the library adds a black border of value one by default:
https://github.com/Hopding/pdf-lib/blob/b4d9731ed6beb63d889ce996e13fbebbaf0fb118/src/api/form/appearances.ts#L446

So a field with a white background color end up looking like this:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/7517745/99842898-a324d980-2b3e-11eb-8331-d5c4281bf0b8.png">

Instead they should look like this:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/7517745/99842929-b46de600-2b3e-11eb-98bf-5a884f80035a.png">

**Comment by vielhuber** [comment]
This is still the case on 1.17.1, or am I wrong?

![image](https://user-images.githubusercontent.com/3183737/160192019-13fc6419-7e72-4434-bd65-b3c9cefb0595.png)

**Comment by btecu** [comment]
@vielhuber check your PDF, maybe the inputs have a border set.

**Comment by vielhuber** [comment]
Hmm, this looks quite clean beforehand:
![image](https://user-images.githubusercontent.com/3183737/160214355-7130aa90-21e3-464a-ae66-82729d90492e.png)
![image](https://user-images.githubusercontent.com/3183737/160214381-769d57c6-cb7d-4870-b3d9-d94090c97564.png)

Output with pdf-lib:
![image](https://user-images.githubusercontent.com/3183737/160214297-829454a0-8423-442c-934a-39ed263bd39c.png)

This is the original PDF:
[dummy2.pdf](https://github.com/Hopding/pdf-lib/files/8354265/dummy2.pdf)

When the "fill color" is transparent and *no* border is set in the pdf, it has a border after processing it with pdf-lib:
![image](https://user-images.githubusercontent.com/3183737/160214465-caa2fe86-257b-497f-916d-55d3202f4fbe.png)
![image](https://user-images.githubusercontent.com/3183737/160214481-d3e014cd-642f-449c-83ce-198415c5cc52.png)

If the "fill color" is set to white and *no* border is set in the pdf, the behaviour is correct and it has no border after processing with pdf-lib:
![image](https://user-images.githubusercontent.com/3183737/160214504-e9138c32-8561-4935-a2c1-0efc7e3c5b09.png)

**Comment by vielhuber** [comment]
Can you reproduce this issue on your side?

**Comment by epratt000** [comment]
I'm running into this same issue. I'm using V1.17.1.

I'm creating a bran new text field on a page and I'm only setting x, y, width, and height.

It shows a black border around the field.

        const pdfPage = pdf.getPage(1);
        const font = await pdf.embedFont(StandardFonts.Helvetica);
        const options = {
            x: 250,
            Y: 715,
            width: 25,
            height: 10
        };
        const newField = pdf.getForm().createTextField('newField');
        newField.addToPage(pdfPage, options);
        newField.defaultUpdateAppearances(font);
        
        const savedPdf = await pdf.save({ updateFieldAppearances: true });

The existing PDF that was loaded has no border selected on every single existing field

![image](https://github.com/Hopding/pdf-lib/assets/106725030/1527891e-09bd-4abb-9808-9ded94b18995)

**Comment by stx-chris** [comment]
This issue still persists for `PDFCheckBox` fields which have transparent background. Currently it is not possible to get rid of the border (by setting it to `0` or `undefined`). Is there a workaround?

**Comment by lbesiche** [comment]
I don't know if this answers your question, but if you would like to remove the border of a text field. I notice you can set the borderColor when you add the textfield to the page:

```
const page = pdfDoc.getPage(0);
  const textField = form.createTextField(fieldName);

  textField.addToPage(page, {
    x,
    y,
    width,
    height,
    borderColor: rgb(1, 1, 1),
  });
```
