### ISSUE TITLE
Copy Multiple Pages in one action

### ISSUE THREAD

**Issue by irtzasuhail** [Hopding/pdf-lib#686]
Hi,

Apologies if I missed this somewhere in the documentation, but is there a way we can provide a page range/array of page numbers to copyPages to be able to copy pages from one pdf to another faster? 

Alternatively, is there a faster way to copy pages into a pdf? I am trying to copy large documents across (over 1500 pages) and it takes several minutes and I would like to reduce that time if possible

**Comment by Hopding** [comment]
See the API docs for [`PDFDocument.copyPages`](https://pdf-lib.js.org/docs/api/classes/pdfdocument#copypages). The second parameter is a list of page indices that you wish to copy over. If this doesn't speed up your code, please open a new issue with code and PDFs that I can use to reproduce the issue.

**Comment by irtzasuhail** [comment]
Thanks! That + some refactoring on my part got the timings down significantly.
