### ISSUE TITLE
Filled hebrew characters unable to render unless clicked

### ISSUE THREAD

**Issue by dfrancoS37** [Hopding/pdf-lib#688]
I'm having an issue when filling in fields with hebrew characters.  Works OK for english (latin) & russian (cyrillic).

Because I may have non-latin characters, I am embedding the Ubuntu font in the pdfDoc as recommended https://www.npmjs.com/package/pdf-lib#creating-and-filling-forms. 

After the document is filled in, the english & russian values are clearly visible.  Hebrew characters are not.  They are empty boxes.  But when clicked, the value is clearly shown.  When clicked outside the textfield, the value goes back to boxes.  If I click inside the box and modify the value, like adding a space, the value remains visible even after clicking outside the field.

Example PDF file: [Consent_Form_pdf-lib_Completed.pdf](https://github.com/Hopding/pdf-lib/files/5625845/Consent_Form_pdf-lib_Completed.pdf)

[test_pdf-lib.zip](https://github.com/Hopding/pdf-lib/files/5625852/test_pdf-lib.zip)

##### Additional Info:
The results are inconsistent with different viewers.
* `Apple Preview` (on macBook): Results are as reported above.
* `Safari`: Hebrew is empty boxes until clicked.  Remains viewable when clicked outside textfield.
* `Chrome`: Results are as Apple Preview, but when hebrew viewable, it's backwards (LTR).
* `Adobe Acrobat Reader`: Hebrew is empty boxes.  When clicked, the boxes change to dots. Clicking outside textfield changes back to boxes.
* `Confluence viewer`: Results remain empty boxes

Is PDF viewer inconsistency an issue which needs to be taken into consideration?  Is there a preferred viewer?
Thank you,   Dan

**Comment by vlio20** [comment]
@dfrancoS37 did you embed any specific font?

**Comment by Hopding** [comment]
Hello @dfrancoS37!

Sounds like there's a problem with the way `pdf-lib` or `@pdf-lib/fontkit` is processing the custom font you're embedding. This crops up occasionally for some users (see https://github.com/Hopding/pdf-lib/issues?q=is%3Aissue+font).

This issue may be related to https://github.com/Hopding/pdf-lib/pull/726.

**Comment by Hopding** [comment]
@dfrancoS37 What happens if you try to just draw the those characters somewhere on the page with `PDFPage.drawText`?

**Comment by dfrancoS37** [comment]
Hi @Hopding & @vlio20 Thank you for following up.   I'm not working on this anymore, but my colleague was able to get this working by embedding the DejaVuSans.ttf font.
