### ISSUE TITLE
Update pako dependency to version ^2.0.2 for better tree shaking

### ISSUE THREAD

**Issue by lpl14** [Hopding/pdf-lib#689]
Angular11 generates warnings for pdf-lib because of the old module format of pako
> 
> Warning: C:\Users\\*****\node_modules\pdf-lib\es\core\PDFContext.js depends on 'pako'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
> 
> Warning: C:\Users\\*****\node_modules\@pdf-lib\upng\UPNG.js depends on 'pako'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Recently pako switched with version 2.0.0 to es6. Would it be possible to update the dependency?
Thank you!

**Comment by Hopding** [comment]
Hello @lpl14! It should be possible to upgrade pdf-lib to the latest version of pako. I don't have time to work on this right now, but I'd be happy to accept a PR for it!

**Comment by jwfx** [comment]
@Hopding 
Since both pull requests didn't go through, this issue should probably be reopened again as this issue still persists?

**Comment by DineshSolanki** [comment]
is there any update on this

**Comment by andreaslarssen** [comment]
Is there anyone here with permission to reopen please?

**Comment by jwfx** [comment]
@andreaslarssen 

I think by now this project here can safely be pronounced dead, see also: https://github.com/Hopding/pdf-lib/issues/1423#issuecomment-1492631262

**Comment by andreaslarssen** [comment]
> @andreaslarssen
> 
> I think by now this project here can safely be pronounced dead, see also: [#1423 (comment)](https://github.com/Hopding/pdf-lib/issues/1423#issuecomment-1492631262)

Thanks, added issue to forked repo and hoping for the best:
https://github.com/cantoo-scribe/pdf-lib/issues/24

**Comment by Sharcoux** [comment]
Hi guys,

The following dependencies of pdf-lib rely on pako 1.

 *   "@pdf-lib/standard-fonts": "^1.0.0",
 *   "@pdf-lib/upng": "^1.0.1",

I'm not sure what we can do without Hopding, unless we fork all 3 projects, but I'm not so sure that we can maintain all that...

**Comment by Sharcoux** [comment]
@DineshSolanki @jwfx Would anyone of you be able to maintain a fork of @pdf-lib/standard-fonts ?

**Comment by DineshSolanki** [comment]
Yes, I think I can take it up. Just let me know if there's something specific that would need to be taken care also

**Comment by andreaslarssen** [comment]
@DineshSolanki : see https://github.com/cantoo-scribe/pdf-lib/issues/24#issuecomment-1558895821

**Comment by DineshSolanki** [comment]
> @DineshSolanki : see https://github.com/cantoo-scribe/pdf-lib/issues/24#issuecomment-1558895821

Okay, I'll take a look, I'm not really the js guy, but will check, if I understand it properly then might some time into it

**Comment by DineshSolanki** [comment]
> @DineshSolanki : see [cantoo-scribe#24 (comment)](https://github.com/cantoo-scribe/pdf-lib/issues/24#issuecomment-1558895821)

I just published a standard-fonts package with updated dependency, mind trying it out
https://www.npmjs.com/package/@dineshsolanki/standard-fonts
