### ISSUE TITLE
How can I export iframe content inside pdf?

### ISSUE THREAD

**Issue by vinay000** [Hopding/pdf-lib#690]
I have to export iframe content inside pdf. Is it possible to do using pdf-lib ?? if yes please help me with piece of a code.

**Comment by Hopding** [comment]
Not directly. Please see https://github.com/Hopding/pdf-lib#limitations. You could try exporting the iframe to an image and then embedding that image into a PDF document with pdf-lib. Can't think of any other approaches though.
