### ISSUE TITLE
Add hyperlink to page?

### ISSUE THREAD

**Issue by NQNStudios** [Hopding/pdf-lib#691]
I'd like to be able to add a normal hyperlink, or a hyperlink image, in a PDF I'm making. Is there a way to do that, or could it be added?

**Comment by Hopding** [comment]
Hello @NQNStudios! There is indeed a way to do this. Please see https://github.com/Hopding/pdf-lib/issues/555.

**Comment by NQNStudios** [comment]
Can I make a PR adding an example to the documentation?
