### ISSUE TITLE
Info only: Made a simple resizer app using this lib

### ISSUE THREAD

**Issue by vegarringdal** [Hopding/pdf-lib#692]
Hi

Made a simple resizer app using this lib

App can be found here with full source code:
* https://github.com/vegarringdal/simple-pdf-resizer

Its a window app using electron. So making it work on mac/linux should work fine I guess. Dont have mac and dont need pdf tools on my linux os.
GUI part is using simple wrapper [lib](https://github.com/simple-html/simple-html) I make around lit-html.

Made it because I did not want to use print to PDF to resize.  And software I found did not do what I wanted.
Have code parts that needs cleanup/ could be improved. But it work for what I need it to do, so changes is not a very high priority.
Its been stable during my own beta testing, so just put a version 1.0.0 label on it.

**Comment by Hopding** [comment]
Very nice! Thanks for sharing @vegarringdal. I added a link to it in the README: https://github.com/Hopding/pdf-lib/commit/8c9d745c76657731504d481cf5690dca8001d2cf
