### ISSUE TITLE
How to Modify multiple PDF pages without reloading it.

### ISSUE THREAD

**Issue by princ09** [Hopding/pdf-lib#697]
Hi Thank for this Awesome Lib. 
My Requirement is , I need to add Images to multi-page , Image can be on all pages and pdf can be hundreds of pages. Currently I am reloading Pdfbytes in each Itteration. 
Following is Snippet
```
pageSet.forEach(async (pageNum: number) => {
			const currentPage = pages[pageNum - 1];
			const { width, height } = currentPage.getSize();
			let url =  await this.getCanvasUrl(pageNum, width, height); // data url of image that can be of 3000x5000
			const pngBytes = await fetch(url).then((res) => res.arrayBuffer());
			const pngImage = await this.pdfDoc.embedPng(pngBytes);
			const pngDims = pngImage.scale(1);
			currentPage.drawImage(pngImage, {
				x: 0,
				y: 0,
				width: width,
				height: height,
			});
			this.pdfBytes = await this.pdfDoc.save();
			this.pdfDoc = await PDFDocument.load(this.pdfBytes);
			this.operation();
});
```
Now this way create big performance Issue when pdf is of more then 50 pages and if we need to add image on all page. You can see that I am loading `the.pdfBytes` again.
So is there any way to get pages from pdf , update it and insert is back? or any other way to improve this?
Thank You.

**Comment by btecu** [comment]
What is `pageSet`?

Are you embedding the same image on all or multiple pages?

**Comment by princ09** [comment]
> What is `pageSet`?
> 
> Are you embedding the same image on all or multiple pages?

It can be same or can't be. Its upto user.
User can add one image on all pages,  or on selected pages. User can also add multiple images on single page.
Pageset is set of pages where i stored page list.
As async-await doesn't work properly in forEach so i used traditional for-loop instead and also removed save() out of the loop.

Now its working properly but when pdf size get more then 50mb then my browser get crashed(i7, 8GB ram).

Any solution to optimizing it further?

**Comment by Hopding** [comment]
Afraid not. Large PDFs are difficult to work with. This may become easier once pdf-lib supports I/O streaming, as everything is done in-memory today. I'd suggest trying to use SVGs if possible. They use less space than images. If you must use images, then try lowering their quality so they don't take up as much space prior to embedding them in the document.
