### ISSUE TITLE
Trying to add image to signature field, instead getting filled red color

### ISSUE THREAD

**Issue by VineelG** [Hopding/pdf-lib#698]
@Hopding First of all Thanks very much for this brilliant library.

While trying to add an image to signature field using the code you provided at #418, signature field is getting filled with red color no image is added. Out pdf is [here](https://da0cbzix1wd46.cloudfront.net/out_pdf_with_red_as_signature.pdf).   

Used exactly the same code, base64 and pdf file. Is there anything missing, I am using version 1.12.0.

Thanks

**Comment by btecu** [comment]
I believe once #700 gets merged, we could do something very similar for `SignatureField` that we do in #700 for `TextField`.

**Comment by VineelG** [comment]
Hopefully this will be merged soon and setImage() can be used more widely and easily with other field types. In the meanwhile, will try why this #418 working approach isn't working for me. Thanks

**Comment by Hopding** [comment]
Hello @VineelG!

I'd suggest trying the approach implemented in https://github.com/Hopding/pdf-lib/pull/700 and https://github.com/Hopding/pdf-lib/pull/718. The `setImage()` method itself doesn't exist on all field types yet. But it should be fairly easy with the changes made in those PRs. Please open a new issue if you find that doesn't work.
