### ISSUE TITLE
Text Alignment Center for a Multi line text

### ISSUE THREAD

**Issue by rachnakhokhar** [Hopding/pdf-lib#701]
I have a client's house address which I have to render on PDF, and addresses tend to wrap in multiple lines so when I render the text using drawText with maxWidth I am getting as displayed in attached PDF. I need the text to be center aligned in all rows. Currently the text by default is getting left aligned.

*Important - I only need help with multiline text, as aligning a single line text was not an issue.
<img width="131" alt="Screenshot 2020-12-11 at 10 38 34 PM" src="https://user-images.githubusercontent.com/2536611/101933338-0f58a180-3c02-11eb-9011-854fd07ebb54.png">

**Comment by Hopding** [comment]
Hello @rachnakhokhar! 

pdf-lib doesn't have any high-level APIs designed for this right now. So you'll have to implement it yourself. You'll need to take your text and break it apart manually by measuring it, just like pdf-lib does internally: https://github.com/Hopding/pdf-lib/blob/2b4ee6b097b7231935eac610f0e43a1befa7cac6/src/api/PDFPage.ts#L902-L907

Then you can draw each string of text individually with `PDFPage.drawText` and center it that way. 

Another option would be to use the `layoutMultilineText` method to break apart your text. This method is used internally for form filling. See https://github.com/Hopding/pdf-lib/blob/2b4ee6b097b7231935eac610f0e43a1befa7cac6/src/api/text/layout.ts#L135
