### ISSUE TITLE
PDF Decryption

### ISSUE THREAD

**Issue by Ayfel** [Hopding/pdf-lib#703]
So all I want to do is to be able to open decrypted documents to write on top. I don't need any ability to read text inside the document or parse other data inside (it would be great to have the amount that pdf.js allows when viewing it), and as a matter of fact I am just trying to visually overlay some data. My app allows users to select a pdf and decide where to write some data. I am using pdf.js to visualize these and overlay some data on top and I want to create a new pdf with pdf-lib to print it.

Also I want to say this is an amazing project, great job : D

**Comment by Hopding** [comment]
Hello @Ayfel!

If you're input document is encrypted then it must be decrypted before anything can be done with it, even for a simple task like drawing content on top. Built in support for document decryption is being tracked in https://github.com/Hopding/pdf-lib/issues/233. In the meantime, you might consider using another library or CLI tool to decrypt the document before passing it to `pdf-lib` for processing.
