### ISSUE TITLE
enableReadOnly not working for checkbox fields?

### ISSUE THREAD

**Issue by rosscournoyer602** [Hopding/pdf-lib#705]
const formField = form.getField(field)
    formField.enableReadOnly()

If I get a text field, or radio field, the pdf is read-only. However this same approach with checkboxes, still allows checkbox to be interacted with/changed.

    app.post('/write', (req, res) => {
	fs.readFile('./sample.pdf', async (fsErr, data) => {
		if (fsErr) {
			res.send({
				status: 'error',
				data: null,
				error: fsErr
			})
		}

		const formPdfBytes = data
		const pdfDoc = await PDFDocument.load(formPdfBytes)
		const form = pdfDoc.getForm()
		const fields = form.getFields()
		const fieldNames = fields.map(f => (f.getName()))
		fieldNames.forEach(field => {
			const formField = form.getField(field)
			// if it is a text field
			if (formField.setText) {
				formField.setText(req.body[field])
			}
			// if its a checkbox field
			if (formField.isChecked) {
				if (req.body[field] === 'true') {
					formField.check()
				}
			}
			// if its a radio
			if (formField.getOptions) {
				if (req.body[field]) {
					formField.select(req.body[field])
				}
			}
			formField.enableReadOnly()
		})

	const pdfBytes = await pdfDoc.save()

	fs.writeFile('./filled.pdf', pdfBytes, (error) => {
		if (!error) {
			res.send({
				status: 'ok',
				data: pdfBytes,
				error: null
			})
			} else {
				res.send({
					status: 'error',
					data: null,
					error: error
				})
			}
		})
	})
    });

**Comment by btecu** [comment]
Are you testing this in `Preview` on a Mac? I don't believe `Preview` respects the read only state of a checkbox.

You can try opening the same document with Acrobat Reader and you can also create a document in Adobe Acrobat with a read only checkbox and test in `Preview`.

**Comment by rosscournoyer602** [comment]
Hi, yes I was indeed testing on preview, and it also appears that when i open on an iOS device it is the same behavior. So clearly this is not a bug, just a device limitation. It behaves differently on android devices and with Acrobat. Thanks!

**Comment by NurdinDev** [comment]
Adding `form.flatten()` before `save` is working with me 👍
