### ISSUE TITLE
Unhandled Rejection Error

### ISSUE THREAD

**Issue by BarishSarac** [Hopding/pdf-lib#706]
Hi,

Some PDF files I have work, but I have two PDFs that both give this attached `Unhandled Rejection (TypeError): Cannot read property 'node' of undefined` error. I re-saved these PDFs again and tried no help, I converted them to Word then back to PDF no help...

Below is part of the code to create PDF
```
 const pdfDoc = await PDFDocument.create();
    const basePDFBytes = await this.getPDFAndConvert();
    const pdfPages = await pdfDoc.embedPdf(basePDFBytes, [0, 1]);
```

and

```
  getPDFAndConvert = async () => {
    let file = myPdf;
    return await fetch(file).then((res) => res.arrayBuffer());
  };
```
Note: myPdf is a PDF imported like `import myPdf from "./../PDFs/myPdf.pdf";`

**Comment by Hopding** [comment]
Hello @BarishSarac!

This might be related to https://github.com/Hopding/pdf-lib/issues/709, so I'd suggest looking at the solution I proposed there. If that doesn't work, please reopen this issue with a complete script and the PDF files necessary to reproduce the issue.

Also, I'm not sure if you can use `fetch` to load an imported asset.
