### ISSUE TITLE
Extract Image exif/metadata data

### ISSUE THREAD

**Issue by RhaldGian** [Hopding/pdf-lib#707]
Hi everyone !
I'm trying to extract images from pdf and also trying to get the images exif/metada like colorspace, width & height.
Is there a way to go about this using PDFLib thank you.

Thank you four your answers :)

**Comment by Hopding** [comment]
Hello @RhaldGian!

Please see the following:
* https://github.com/Hopding/pdf-lib/pull/509
* https://github.com/Hopding/pdf-lib/issues/504
* https://github.com/Hopding/pdf-lib/issues/710
* https://github.com/Hopding/pdf-lib/issues/83#issuecomment-487383843
* https://github.com/Hopding/pdf-lib#limitations

**tl;dr** - probably not.
