### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'node' of undefined ERROR

### ISSUE THREAD

**Issue by hansvmourik** [Hopding/pdf-lib#709]
Hello everyone! 

I recently started working with this exciting library. However I am facing the following issue:

Using the script below I would like to merge pdf documents. The script works perfectly with the provided template PDFs. However, when I add the following PDFs to the script, it doesn't work. It returns the error: 
```
pdf-lib@1.11.0:15 Uncaught (in promise) TypeError: Cannot read property 'node' of undefined
    at e.<anonymous> (pdf-lib@1.11.0:15)
    at pdf-lib@1.11.0:15
    at Object.next (pdf-lib@1.11.0:15)
    at a (pdf-lib@1.11.0:15)
```

As the script runs without problems with the template PDFs, I can't figure out what I am doing wrong here. You can find the documents that lead to the error in the script below:

```js
async function merge() {

        const url1 = 'https://pdf-lib.js.org/assets/with_update_sections.pdf'  // working pdf
        const url2 = 'https://sptl.nl/wp-content/themes/understrap-3/inc/orderblok2.pdf' // not working pdf

        const firstDonorPdfBytes = await fetch(url1).then(res => res.arrayBuffer())
        const secondDonorPdfBytes = await fetch(url2).then(res => res.arrayBuffer())

        const firstDonorPdfDoc = await PDFDocument.load(firstDonorPdfBytes)
        const secondDonorPdfDoc = await PDFDocument.load(secondDonorPdfBytes)

        const pdfDoc = await PDFDocument.create();

        const [firstDonorPage] = await pdfDoc.copyPages(firstDonorPdfDoc, [0])
        const [secondDonorPage] = await pdfDoc.copyPages(secondDonorPdfDoc, [742])

        pdfDoc.addPage(firstDonorPage)
        pdfDoc.insertPage(0, secondDonorPage)

        const pdfBytes = await pdfDoc.save()

        // Trigger the browser to download the PDF document
      download(pdfBytes, "pdf-lib_pdf_page_embedding_example.pdf", "application/pdf");
    }
```

I really hope that someone would be able to point me in the right direction here! 

If you have any further questions, please let me know!

Hans

**Comment by Hopding** [comment]
Hello @hansvmourik!

You're trying to copy a page that does not exist. The second document you linked to (https://sptl.nl/wp-content/themes/understrap-3/inc/orderblok2.pdf) has only a single page. But you're trying to copy the 743rd page.

You need to change this line:
```
const [secondDonorPage] = await pdfDoc.copyPages(secondDonorPdfDoc, [742])
```
To the following:
```
const [secondDonorPage] = await pdfDoc.copyPages(secondDonorPdfDoc, [0])
```

---

That being said, the error message is fairly obtuse. If you're interested in fixing this, you could make a PR that adds an `assertRange` check for each of the indices passed to `PDFDocument.copyPages`. The assertion would go in this method: https://github.com/Hopding/pdf-lib/blob/2b4ee6b097b7231935eac610f0e43a1befa7cac6/src/api/PDFDocument.ts#L721-L735

Here's an example of a method that already has this check: https://github.com/Hopding/pdf-lib/blob/2b4ee6b097b7231935eac610f0e43a1befa7cac6/src/api/PDFDocument.ts#L682
