### ISSUE TITLE
Is it possible to compress images in an existing PDF?

### ISSUE THREAD

**Issue by tsemerad** [Hopding/pdf-lib#71]
I'm building an app that allows users to upload PDFs to a server. I'd like to compress the images in the PDFs to cut down on the file size, since sometimes the PDFs can be over 30MB. 

I see that `pdf-lib` has many options for modifying existing PDFs, but that it is mainly to add text or images to the existing document, or to add pages. Can `pdf-lib` compress the existing images, and if not, is that a feature it may support in the future?

**Comment by Hopding** [comment]
Hello @tsemerad. `pdf-lib` doesn't currently provide an API for compressing images. I doubt that this feature would be added to the main `pdf-lib` codebase. But it would be possible to use `pdf-lib` to extract existing images from a PDF. You could then compress them on your own, and re-insert them with `pdf-lib`.

Also, my apologies for the late response. I've been very busy at work and school the past few weeks.
