### ISSUE TITLE
Does pdf-lib has a method for extracting embedded images from a PDF file?

### ISSUE THREAD

**Issue by adetoola** [Hopding/pdf-lib#710]
I want to extract an image from a PDF file but I can't see a way to do that in the documentation. How can this be done?

P.S. I see `PDFIMage` but it seems it is limited to embedding images into a PDF and not extraction.

**Comment by Hopding** [comment]
Hello @adetoola! Please see https://github.com/Hopding/pdf-lib/issues/83#issuecomment-487383843.
