### ISSUE TITLE
How to make fonts work for outline?

### ISSUE THREAD

**Issue by lillallol** [Hopding/pdf-lib#711]
I have created [this](https://www.npmjs.com/package/@lillallol/outline-pdf) package that depends on `pdf-lib` to add outline to an outline-less pdf. The code is in accordance to what is suggested here : [1](https://github.com/Hopding/pdf-lib/issues/127#issuecomment-502450179) , [2](https://github.com/Hopding/pdf-lib/issues/127#issuecomment-641710694)  . I use `PDFString.of()` to add the text to the pdf outline.

 I have tried what is mentioned [here](https://github.com/Hopding/pdf-lib#fonts-and-unicode) , but the font does not seem to affect the outline.

**Comment by Hopding** [comment]
Hello @lillallol!

Try using `PDFHexString.fromText()` instead of `PDFString.of()`. That should solve your issue. See https://github.com/Hopding/pdf-lib/pull/486#discussion_r460346527.
