### ISSUE TITLE
How to  make  embedfont with chinese font 

### ISSUE THREAD

**Issue by RylaiCrestfall** [Hopding/pdf-lib#712]
怎么样可以生成导出带有中文字体的pdf啊。。。。如果直接嵌入中文字体的话会导致pdf文件太大，希望可以能加入中文字体库

**Comment by Hopding** [comment]
Please see https://github.com/Hopding/pdf-lib/issues/725#issuecomment-753519315. Note that if the built-in subsetting functionality does not work for your font, you could always subset it with another tool prior to embedding it with pdf-lib.
