### ISSUE TITLE
Using Cyrillic symbols. Russian language

### ISSUE THREAD

**Issue by Vladislav747** [Hopding/pdf-lib#715]
Hello! I am facing error when i try to put in drawText or setText russian symbols(cyrillic). How to encode them properly for your module?

**Comment by Kiteow** [comment]
1) u need to obtain cyrillic font **.ttf prefered**   (https://fonts.google.com/?subset=cyrillic)
const exFont = await fetch('link to  a raw file').then(res=>{
  return res.arrayBuffer()
})
 2) const pdfDoc = await PDFDocument.create(); || or load yours 
 3) pdfDoc.registerFontkit(fontkit)
 4) const **myfont** = await pdfDoc.embedFont(exFont);

5) page.drawText("Какой-то текст", {
  x: 150,
  y: height - 4 * fontSize,
  size: fontSize,
  font: **myfont**,
  color: rgb(0, 0.53, 0.71),
})

**Comment by Kiteow** [comment]
> Hello! I am facing error when i try to put in drawText or setText russian symbols(cyrillic). How to encode them properly for your module?
_______________________________________________________________________
u need to obtain cyrillic font **.ttf prefered** (https://fonts.google.com/?subset=cyrillic)
const exFont = await fetch('link to a raw file').then(res=>{
return res.arrayBuffer()
})

const pdfDoc = await PDFDocument.create(); || or load yours

pdfDoc.registerFontkit(fontkit)

const **myfont** = await pdfDoc.embedFont(exFont);

page.drawText("Какой-то текст", {
x: 150,
y: height - 4 * fontSize,
size: fontSize,
font: **myfont**,
color: rgb(0, 0.53, 0.71),
})

**Comment by th69nd** [comment]
for setText use updateAppearances()
smth like this

```
let nameField = form.getTextField('name')
nameField.setText('Иван')
nameField.updateAppearances(Roboto)
```

**Comment by Hopding** [comment]
See also https://github.com/Hopding/pdf-lib#fonts-and-unicode and https://github.com/Hopding/pdf-lib#creating-and-filling-forms.
