### ISSUE TITLE
Help with checkbox method updateAppearances!!!!

### ISSUE THREAD

**Issue by Chinocy** [Hopding/pdf-lib#717]
Hi,

Can someone help me to update form PDFCheckBox field appearance??

I try to use **updateAppearances** but fail in the attempt. Also i tried to use **defaultUpdateAppearances** in a existing PDFCheckBox field and nothing happened.

Thanks.

**Comment by btecu** [comment]
Why do you have to call those directly? `field.check()` and `field.uncheck()` should update the appearance for you.

**Comment by Chinocy** [comment]
@btecu I trying to fill a previously generated pdf, in some fields when i use `field.check()`, nothing happen, when i fill it manually on google chrome, the same. After some research it's likely that those **checkboxes** don't have appearances o was wrong setted at the creation time.
