### ISSUE TITLE
Text in multiple lines

### ISSUE THREAD

**Issue by joseph20** [Hopding/pdf-lib#72]
Hi! First of all, thanks a lot for this library.

I am trying to paint a long and dynamic text that comes from an API, the text is content of multiple paragraphs that must be painted on one or several pages, the characters have not been identified, I use "**drawText (text, options);**" the result is painted on a single line, it outside the canvas. (Attached image)

![captura de pantalla 2019-01-28 a las 10 20 16](https://user-images.githubusercontent.com/2975135/51828355-b1f82780-22eb-11e9-95fc-7ac5fc22c868.png)

How can it be achieved so that the text is painted in multiple lines and pages?
[](url)
On the other hand, when a text contains characters like '\ r' or '\ n' (manually split), I use "**drawLinesOfText (text.split ('\ n'), options);**", and the result is correct, but If the text is too long, how should a new page be generated with the remaining text?
(attached image)

![captura de pantalla 2019-01-28 a las 10 39 39](https://user-images.githubusercontent.com/2975135/51828376-be7c8000-22eb-11e9-823c-8d9029f8fcc9.png)
How can it be achieved so that the text is painted on multiple pages?

Thansk!

**Comment by Hopding** [comment]
Hello @joseph20. 

As you've noticed, `pdf-lib` doesn't automatically wrap your text once it reaches the edge of the page. However, it does provide the necessary APIs for you to do so manually. 

In order to wrap your text, you need to be able to measure the length of a string so that you know when it will run past the edge of the page. Here are two examples that demonstrate how to measure text in `pdf-lib` using the `font.widthOfTextAtSize()` and `font.heightOfFontAtSize()` methods:
* https://github.com/Hopding/pdf-lib#embed-font-and-measure-text
* https://github.com/Hopding/pdf-lib/tree/master/examples/measuring_text/node

I hope this is what you're looking for. Let me know if you have any additional questions!

(Also, my apologies for the late response. I've been very busy at work and school the past few weeks.)

**Comment by tohchenlong** [comment]
How do you get the position of the pointers after text wrap?

**Comment by Temkit** [comment]
easy solution, convert your string before : 

let say content is your string;
```
   if (item.break) {
        let j = item.break;
        while (j < content.length) {
          content =
            content.slice(0, item.break * j) +
            "\n" +
            content.slice(item.break * j);
          j = j + item.break;
        }
      }
```

**Comment by stadlo** [comment]
you can use the the multilinetextlayout object from pdf-lib to split your text into lines of  certain width 
<pre><code>const multiText = layoutMultilineText(text, {
         alignment: 'left', 
         font: lightFont,
         fontSize: fontSize,  
         lineHeight: lineHeight,
         bounds: { width: width - 100, height: 10000  }
      })</code></pre>
from there your can write the each line and move your starting position down correspondingly. If your starting position goes
below 0 you are past the page limit and should add a new page
<pre><code>for(let i = 0; i < multiText.lines.length; i++) {
  if((startingPositon) < 50) {
    page = pdfDoc.addPage()
    page.setFont(lightFont)
    addFooter(page, logoImage, encounter, patient, doctor, patientUser, medFont)
  // reset starting position
    startingPositon = height - 100
  }
  page.drawText(`${multiText.lines[i].text}`, {
    x: x,
    y: startingPositon,
    size: fontSize,
    maxWidth: width - 100,
    color: color,
    font: font
  })
// move position down
  startingPositon = startingPositon - (lineHeight)
  }
  return startingPositon
}</code></pre>

**Comment by AkshayBh28** [comment]
Hello @joseph20 ,
I am facing a similar issue and when trying to use drawLinesofText getting an error as mentioned below..
Index:153 Uncaught (in promise) TypeError: page.drawLinesofText is not a function"
Can you help with this?
Looking for a simple solution..

**Comment by JoaoHenriqueBarbosa** [comment]
For me the solution was to make a function to mesure and wrap the lines.

```
/*
  * Using font.widthOfTextAtSize transform text adding \n to break lines
  * if width of text is bigger than the width passed as parameter
  * and return the text with the line breaks
  * @param text: string
  * @param width: number
  * @param font: font
  * @param fontSize: number
  * @returns string
  */
const wrapText = (text, width, font, fontSize) => {
  const words = text.split(' ');
  let line = '';
  let result = '';
  for (let n = 0; n < words.length; n++) {
    const testLine = line + words[n] + ' ';
    const testWidth = font.widthOfTextAtSize(testLine, fontSize);
    if (testWidth > width) {
      result += line + '\n';
      line = words[n] + ' ';
    } else {
      line = testLine;
    }
  }
  result += line;
  return result;
}
```

**Comment by sumitaney** [comment]
@stadlo can you elaborate the starting position, do you have full code?

**Comment by mrnoobnoobies** [comment]
> For me the solution was to make a function to mesure and wrap the lines.
> 
> ```
> /*
>   * Using font.widthOfTextAtSize transform text adding \n to break lines
>   * if width of text is bigger than the width passed as parameter
>   * and return the text with the line breaks
>   * @param text: string
>   * @param width: number
>   * @param font: font
>   * @param fontSize: number
>   * @returns string
>   */
> const wrapText = (text, width, font, fontSize) => {
>   const words = text.split(' ');
>   let line = '';
>   let result = '';
>   for (let n = 0; n < words.length; n++) {
>     const testLine = line + words[n] + ' ';
>     const testWidth = font.widthOfTextAtSize(testLine, fontSize);
>     if (testWidth > width) {
>       result += line + '\n';
>       line = words[n] + ' ';
>     } else {
>       line = testLine;
>     }
>   }
>   result += line;
>   return result;
> }
> ```

Hi, how to use this ? means, should i use it like this ?
longtext = " long long long very long and so so long text";
wrappedtext = wrapText( longtext, 300, times, 12);

how to use the wrapText exactly, could you please help me with an example, really I need to understand this. tq

**Comment by mrnoobnoobies** [comment]
> > For me the solution was to make a function to mesure and wrap the lines.
> > ```
> > /*
> >   * Using font.widthOfTextAtSize transform text adding \n to break lines
> >   * if width of text is bigger than the width passed as parameter
> >   * and return the text with the line breaks
> >   * @param text: string
> >   * @param width: number
> >   * @param font: font
> >   * @param fontSize: number
> >   * @returns string
> >   */
> > const wrapText = (text, width, font, fontSize) => {
> >   const words = text.split(' ');
> >   let line = '';
> >   let result = '';
> >   for (let n = 0; n < words.length; n++) {
> >     const testLine = line + words[n] + ' ';
> >     const testWidth = font.widthOfTextAtSize(testLine, fontSize);
> >     if (testWidth > width) {
> >       result += line + '\n';
> >       line = words[n] + ' ';
> >     } else {
> >       line = testLine;
> >     }
> >   }
> >   result += line;
> >   return result;
> > }
> > ```
> 
> Hi, how to use this ? means, should i use it like this ? longtext = " long long long very long and so so long text"; wrappedtext = wrapText( longtext, 300, times, 12);
> 
> how to use the wrapText exactly, could you please help me with an example, really I need to understand this. tq

never mind, got this from stackoverflow post(if i'm not wrong), and i'm not sure which of wordBreaks  or lineHeight that solved my problem here :

 **longtext** = " long long long very long and so so long text"; 
 firstPage.drawText(**longtext** , {
   x: 115,
    y: 373,
    size: 12,
    font: font,
    maxWidth: 290, 
	wordBreaks: [" "],
	**_lineHeight_**: 12,
	color: rgb(0, 0, 0),
  });

**Comment by Lukenickerson** [comment]
A custom line-splitting function is not needed. This is done in https://github.com/Hopding/pdf-lib/blob/93dd36e85aa659a3bca09867d2d8fac172501fbe/src/api/text/layout.ts#L134

The solution that @mrnoobnoobies used worked for me. Here is an example formatted:

```js
const longText = (
`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi non justo eget libero commodo mattis. Nam ullamcorper lectus dolor, at euismod est lacinia semper. Suspendisse iaculis vehicula magna, eu consectetur neque malesuada molestie. Nullam lacus leo, rhoncus nec ultrices nec, posuere vitae diam. Donec tellus ex, rutrum in sem vitae, elementum elementum tellus. Suspendisse feugiat venenatis mi vitae mollis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur non eros at dolor efficitur ullamcorper vitae a velit. Fusce scelerisque aliquet mi, quis convallis sapien auctor a. Donec tristique diam et urna blandit, vitae convallis ex facilisis. Integer a tempus justo, ac viverra nibh.

Donec placerat tempus urna sit amet rhoncus. Nam quam diam, blandit a condimentum sit amet, eleifend sed tortor. Cras egestas ante a velit pulvinar sagittis. Duis vestibulum mollis elit, nec pellentesque lacus imperdiet in. Praesent dapibus vel ante in ultricies. Maecenas tristique nunc orci, auctor eleifend arcu tempor quis. Cras quis auctor orci.

In erat eros, tempor vel dapibus ullamcorper, dapibus id orci. Aenean tincidunt convallis est, maximus gravida ante tincidunt sed. Etiam dictum nulla vel lorem dapibus scelerisque vulputate in nulla. Nunc et lacinia nibh. Curabitur leo elit, convallis eu nisl at, eleifend euismod urna. Aenean id mauris volutpat, vehicula erat non, suscipit elit. Vestibulum ac aliquam tortor. Sed sollicitudin ullamcorper placerat. Maecenas tempor neque non dui tempus, a commodo dolor venenatis.`
);
const size = 12;
page.drawText(longText , {
   x: 115,
   y: 373,
   size,
   font: font,
   maxWidth: 290,
   wordBreaks: [" "],
   lineHeight: size * 1.1,
});
```
NOTE: this only work horizontally, not vertically. It does not flow over to a new page.

**Comment by GabrielBrL** [comment]
I adopted other way. I chosen get the number of lines and multiple by its height. For example:

```
/*
*text: string -> text that you want discover its lines
*font: PDFFont -> the font that you're using
*fontSize: number -> the number of your font size

*the number 550 it's the width limit that I putted in my pdf
*/

function linesFromText(text: string, font: PDFFont, fontSize: number): number {
      var textComplete = '';
      let countLines = 1;
      for (let index = 0; index < text.length; index++) {
        textComplete += text[index];
        var width = font.widthOfTextAtSize(textComplete, fontSize);
        if (width > 550) {
          countLines++;
          textComplete = '';
        }
      }
      return countLines;
    }
```
