### ISSUE TITLE
PDF doesn't appear to have fields and requires Reader to view

### ISSUE THREAD

**Issue by LanceGundersen** [Hopding/pdf-lib#721]
I am attempting to read in the fields and then edit this PDF 👉  https://www.public.navy.mil/bupers-npc/reference/forms/NAVPERS/Documents/NAVPERS_1610-2_Rev11-11.pdf but it appears the form authors are using something different than most of the other forms available [here](https://www.public.navy.mil/bupers-npc/career/performanceevaluation/Pages/SoftwareForms.aspx). 

I am not exactly sure what to look for to debug/google but is this some sort of adobe security thing, etc? If pdf-lib isn't able to work with whatever it is in this file causing problems I can always take a blank form and create new fields, etc.

**Comment by btecu** [comment]
These type of PDF documents are called Dynamic XFA. XFA stands for XML Form Architecture. As of currently, Safari, Chrome and Firefox do not support these type PDF forms thus Dynamic XFA based PDF documents cannot be opened in browsers.

In addition, `pdf-lib` does not support them either. 

You can view these type of PDFs by downloading and installing Adobe Reader.

**Comment by LanceGundersen** [comment]
@btecu thank you for filling in those gaps and also letting me know about the pdf-lib support of them. I will close this out and create a new document I can fill out with my project. Thanks again!

**Comment by bestickley** [comment]
For anyone else who ran into this issue I used this library to fill out a Navy SAAR-N form by following these steps:
1. `qpdf --decrypt SAAR-N.pdf SAAR-N-Decrypted.pdf`
2. Open SAAR-N-Decrypted.pdf with Adobe Pro DC then File > Save As > Encapsulated PostScript files
3. Use Adobe Pro DC "Combine Files" to combine all 4 pages of .eps files
4. Open File with Prepare Form and manually adjust field data types to what you need (Date, Signatures, remove incorrect auto-created forms)
5. Save and load into pdf-lib!
