### ISSUE TITLE
Need way to change font size for text inserted into existing field

### ISSUE THREAD

**Issue by duffyd** [Hopding/pdf-lib#727]
* We're using the PDF-LIB for filling PDFs (https://pdf-lib.js.org/docs/api/classes/pdftextfield). It is likely not relevant but we also embed a font for characters outside of the winansi set (Latin)
* On Nov 23rd, someone asked the author (Hopding) if there is a way to change the font size used. He said, "There are not currently any APIs for changing the font size of an existing field. But such an API could certainly be built. Happy to provide some pointers if anybody is interested in making a PR for it."
* This issue is the formal request for pointers :)

**Comment by btecu** [comment]
Look at the code that retrieves the font size:
https://github.com/Hopding/pdf-lib/blob/2b4ee6b097b7231935eac610f0e43a1befa7cac6/src/api/form/appearances.ts#L123-L135

You just have to reverse the process. The `DA` (default appearance) is a string (or HEX) containing the font name, size and a few possible other details.

**Comment by duffyd** [comment]
@btecu thanks for your reply! So just to clarify, should I be setting the **DA** property (ref [here](https://github.com/Hopding/pdf-lib/blob/2b4ee6b097b7231935eac610f0e43a1befa7cac6/src/core/acroform/PDFAcroField.ts#L89)) on the PDF field to a string representing what I want it to look like before doing a **getTextField**?

**Comment by btecu** [comment]
Yes, you can use `getDefaultAppearance`, modify the string to reflect the font size that you want and then use `setDefaultAppearance`: https://github.com/Hopding/pdf-lib/blob/2b4ee6b097b7231935eac610f0e43a1befa7cac6/src/core/acroform/PDFAcroField.ts#L85-L87

**Comment by duffyd** [comment]
@btecu: Great, thanks again!!

**Comment by Hopding** [comment]
@duffyd Just want to mention that what @btecu said is accurate.

Are you planning to make a PR that introduces an API for changing a text field's font size? If so, note that the `DA` property is optional and may not have a font size already defined in it. So you'll need to handle the case of a text field having a `DA` with a font size defined and the case where it does not have a font size defined (and the case of there being no `DA` property at all).

If you're not planning to make a PR, then I'll go ahead and close this issue.

**Comment by duffyd** [comment]
Hi @Hopding, I'm happy to do a PR but just concerned whether you require some tests as well? Just I've never done testcases/etc in JS before. JS coding is fine, though.

**Comment by Hopding** [comment]
@duffyd There will need to be tests, but we can work through those once you finish the code. I can help you on the tests if necessary. They're not too hard to write. Note that some of them will need to be integration tests, which are just run-of-the-mill scripts (e.g. [test8.ts](https://github.com/Hopding/pdf-lib/blob/master/apps/node/tests/test8.ts)). But again, I can help you with those. 

Please be sure to read https://github.com/Hopding/pdf-lib/blob/master/CONTRIBUTING.md before you get started.

**Comment by duffyd** [comment]
@Hopding I've finished writing the code and have also successfully got an integration test running. How should I create a PR? Fork project into my own GitHub repo and then create a PR or create a fork in your repo?

**Comment by duffyd** [comment]
@Hopding just reiterating my comment in my PR - all requested changes have been implemented and are in my fork awaiting approval.

**Comment by Hopding** [comment]
Support for this added in v1.16.0

**Comment by yaakovyitzchak** [comment]
BH
Hi i have a form text field in about 4 different pages of the pdf and the above method only changes the font size on some but not in all cases?
