### ISSUE TITLE
PDFForm.flatten() does not handle rotated fields correctly

### ISSUE THREAD

**Issue by Hopding** [Hopding/pdf-lib#733]
PDF form fields can be rotated. However, the rotation logic for form field widgets should be "in-place" (see [`rotateInPlace`](https://github.com/Hopding/pdf-lib/blob/0eda76033da7db4a4793aa4443032ffabb03680e/src/api/operations.ts#L440-L461)), as opposed to the more common (at least in PDF land) logic of "about-the-origin" rotation. The current logic used in `PDFForm.flatten()` appears to be using "about-the-origin" logic, which leads to incorrect results after flattening a rotated field. See below for examples clarifying this:

##  ✅ Correct Rendering of Rotated Fields 
You can generate this document yourself by running `yarn apps:node 17` and looking at the first page of the resulting document.

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/103593876-9bd24900-4ebc-11eb-899b-cfdc23ea6a66.png" width="500">
</kbd>

>

##  ❌ Incorrect Rendering of Rotated Fields 
You can generate this document yourself by running `yarn apps:node 18` and looking at the fifth page of the resulting document.

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/103593913-bb697180-4ebc-11eb-8182-2a7da5310d10.png" width="500">
</kbd>

>

**Comment by Hopding** [comment]
@btecu Think it would be fairly straightforward to use `rotateInPlace` for flattening? I'm assuming that's not what's currently being used.

**Comment by btecu** [comment]
Curiously, this evening it was brought to my attention this issue so it was already on my radar.
The document before the fix:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/7517745/103602962-5ec97f00-4edb-11eb-9076-673c498effd0.png">

After the fix:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/7517745/103602988-6be66e00-4edb-11eb-9324-e28e5429e2dc.png">

I've also tested the document mentioned above and it's also fixed.

**Comment by princ09** [comment]
Hi @Hopding , Thanks for this wonderful lib. I just saw documentation related rotateInPlace  but I am not able to understand how to use it. should be used with PngImage? 
I want to have like this https://user-images.githubusercontent.com/47990313/103611620-ab976f00-4f48-11eb-9eb6-c37802238308.jpg
where pdf might be rotated but image i want to be fixed at top left.
Please provide example for rotateInPlace for pngImage.
