### ISSUE TITLE
[Help Wanted] Can't save fillable PDF due to rich text fields not being disabled

### ISSUE THREAD

**Issue by jonscl** [Hopding/pdf-lib#735]
When attempting to fill in text form fields in a PDF I am using, I run into the following error after attempting to save the PDF:

```
(node:59727) UnhandledPromiseRejectionWarning: Error: Reading rich text fields is not supported: Attempted to read rich text field: Other:
    at new RichTextFieldReadError (/node_modules/pdf-lib/src/api/errors.ts:88:5)
    at PDFTextField.getText (/node_modules/pdf-lib/src/api/form/PDFTextField.ts:105:13)
    at exports.defaultTextFieldAppearanceProvider (/node_modules/pdf-lib/src/api/form/appearances.ts:444:26)
    at PDFTextField.updateWidgetAppearance (/node_modules/pdf-lib/src/api/form/PDFTextField.ts:794:45)
    at PDFTextField.updateAppearances (/node_modules/pdf-lib/src/api/form/PDFTextField.ts:783:12)
    at PDFTextField.defaultUpdateAppearances (/node_modules/pdf-lib/src/api/form/PDFTextField.ts:754:10)
    at PDFForm.updateFieldAppearances (/node_modules/pdf-lib/src/api/form/PDFForm.ts:638:15)
    at PDFDocument.<anonymous> (/node_modules/pdf-lib/src/api/PDFDocument.ts:1235:22)
    at step (/node_modules/tslib/tslib.js:141:27)
    at Object.next (/node_modules/tslib/tslib.js:122:57)
(node:59727) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:59727) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am trying to fill a number of rich formatted PDFTextFields using getTextField and setText. When I disable rich formatting on every PDFTextField in the entire form, the problem goes away and I can save the PDF without any error, however, even without editing any text fields attempting to save the PDF as it is loaded will result in this same error. From the documentation I was under the impression that setText would automatically disable rich formatting on these fields for me.

Disabling rich formatting on all form fields and saving also has the unintended side effect of disabling all fillable form fields in the saved PDF. This is undesirable to me and I am unable to find the reason for this happening, as other PDFs I've used have preserved their fillable form fields after setting text and saving, which leads me to believe it is a problem with this particular PDF's formatting, but I am unable to deduce what the exact issue is.

Trying to save the PDF with the option {updateFieldAppearances: false} will save the PDF without error, but will not preserve any changes I made to the document (i.e. all fields are blank).

Lastly, after saving the PDF and opening it in Adobe Acrobat Reader, I get the following notification:

> This document enabled extended features in Adobe Acrobat Reader. The document has been changed since it was created and use of extended features is no longer available. Please contact the author for the original version of this document.

It sounds like I should be able to avoid this if I just create a new PDF using a copy of the original, which I have not tried yet.

Any assistance with this would be appreciated, the specific PDF I am trying to work with can be found here:
https://www.mass.gov/doc/english-snap-benefits-application-snapa-1/download

**Comment by Hopding** [comment]
@jonscl Please share code for a script that I can use to reproduce the issue.

**Comment by 32teeths** [comment]
Hello , 

Is RTF support there for writing HTML text to pdf forms ?

**Comment by Jamesweng** [comment]
This is still an issue. Thanks @jonscl for providing the workaround - call disableRichFormatting() on all text fields before save works.
