### ISSUE TITLE
minified pdf-lib : no access to field.constructor.name

### ISSUE THREAD

**Issue by somel-web** [Hopding/pdf-lib#736]
When using the minified version of pdf-lib field.constructor.name return a or e.
So it's impossible to differentiate field type. 
No problem with the non-minified version.

**Comment by Hopding** [comment]
Not exactly sure what you're trying to do since you didn't share any code snippets. If you're trying to refine the type of a field, please use `instanceof` checks. For example:
```js
import { PDFTextField } from 'pdf-lib';

const fields = form.getFields();
fields.forEach(field => {
  if (field instanceof PDFTextField) {
    console.log(field.getText());
  }
});
```

**Comment by somel-web** [comment]
Using javascript browser code

**from the api doc**
[https://pdf-lib.js.org/docs/api/classes/pdfform#getfields](https://pdf-lib.js.org/docs/api/classes/pdfform#getfields)
```
const form = pdfDoc.getForm()
const fields = form.getFields()
fields.forEach(field => {
  const type = field.constructor.name
  const name = field.getName()
  console.log(`${type}: ${name}`)
})
```
with minified version
`<script src="https://unpkg.com/pdf-lib/dist/pdf-lib.min.js"></script>`
....
`field.constructor.name` return 'a' or 'e'

with non-minified version
`<script src="https://unpkg.com/pdf-lib/dist/pdf-lib.js"></script>`
....
`field.constructor.name` return the correct type,  eg : `PDFTextField`

indeed
```
const {PDFDocument,PDFTextField,PDFButton} = PDFLib
....
const fields = form.getFields();
fields.forEach(field => {
  if (field instanceof PDFTextField) {
    console.log(field.getText());
  }
});
```
is working well  in both case.
