### ISSUE TITLE
Is it possible to increase size of page from the bottom?

### ISSUE THREAD

**Issue by joelpoloney** [Hopding/pdf-lib#737]
I'm trying to add spacing to the **bottom** of a PDF page however if I use the `page.setHeight()` command, it adds the spacing at the top. Is it possible to add to the bottom? Or somehow move the existing code to the top?

Code to add 30 pixels of spacing:
```ts
page.setHeight(page.getSize().height + 30)
```

Before:
<img width="1011" alt="Screen Shot 2021-01-07 at 10 50 10 AM" src="https://user-images.githubusercontent.com/10091917/103932042-1fb34d80-50d6-11eb-9293-2762a507f7f0.png">

After: 
<img width="1007" alt="Screen Shot 2021-01-07 at 10 49 16 AM" src="https://user-images.githubusercontent.com/10091917/103931973-feeaf800-50d5-11eb-9fb7-8e2033f37952.png">

**Comment by Hopding** [comment]
Hello @joelpoloney! You can use [`PDFPage.translateContent`](https://pdf-lib.js.org/docs/api/classes/pdfpage#translatecontent) to shift everything up by 30 units after increasing the height by 30 units.

**Comment by joelpoloney** [comment]
Thank you @Hopding!
