### ISSUE TITLE
drawSvgPath (and other draw* methods) don't support line join

### ISSUE THREAD

**Issue by electronicwhisper** [Hopding/pdf-lib#738]
`PDFPage`'s `drawSvgPath`, `drawCircle`, etc methods support a line cap (`borderLineCap`) but not a line join (bevel, miter, round) in their options.

I see there's an [Enum for LineJoinStyle](https://pdf-lib.js.org/docs/api/enums/linejoinstyle) but it doesn't look like it's exposed anywhere.

For completeness, this feature would also need to support changing the miter limit. The equivalent Canvas properties would be [lineJoin](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin) and [miterLimit](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/miterLimit).

PS: Thank you for making this well-documented, well-structured PDF library!

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.
