### ISSUE TITLE
Support non-zero and even-odd fill rules for drawSvgPath

### ISSUE THREAD

**Issue by electronicwhisper** [Hopding/pdf-lib#739]
There's no option to choose "non-zero" vs "even-odd" as the fill rule when drawing an SVG path. It looks like "non-zero" is chosen by default.

Fill rules are supported in PDFKit: https://pdfkit.org/docs/vector.html#winding_rules

In Canvas, fill rule is supported with the optional fillRule parameter. https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fill

**Comment by ccc159** [comment]
Any news on this feature?

**Comment by Hopding** [comment]
Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by Sharcoux** [comment]
We gave support in version 1.19.16 of [@cantoo/pdf-lib](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwj4p4v-zreCAxW2TKQEHdNnBm8QFnoECA8QAQ&url=https%3A%2F%2Fwww.npmjs.com%2Fpackage%2F%40cantoo%2Fpdf-lib&usg=AOvVaw0HVA3VXldV5YTbKgPOr5Kf&opi=89978449)
