### ISSUE TITLE
Cannot merge pages together

### ISSUE THREAD

**Issue by GkqqNkKC** [Hopding/pdf-lib#740]
I want from a document with multiple pages to generate one with just a page which contains all the content. I started by creating a new `PDFDocument` and page: `let outPage = out.addPage([inputPages[0].getWidth(), inputPages[0].getHeight() * inputPageCount]);` (considering all input pages have the same size)

I have no idea how to copy now. I guess I have to copy all elements one by one and modify their position, but there's no exposed API to do that. I suggest to implement functions along the lines:

- `PDFPage.copy(obj: PDFObject)`
- `PDFObject.setPos(...`

Probably iterating `input.getPages()` I can get the objects with `page.node.values()`, but I have no idea how to insert them in another page (after cloning them probably)

Did I miss something somewhere? If not, what workaround I can use to merge my pages?

**Comment by Hopding** [comment]
Hello @GkqqNkKC!

I'm afraid there is currently no high level API for merging the content of two distinct pages into a single page. This could be done, but you'd need to use the low-level APIs to copy the resources and content streams from the original pages into the new page. I'm afraid I don't have enough time to write up an example of how to do something like this. You'd need to be a little bit familiar with the low-level structure of PDF documents to pull it off.

**Comment by isohanvanani** [comment]
@GkqqNkKC Have you found any solution to this? I also needs to do the same but not finding any solution with this lib

**Comment by toverux** [comment]
@Hopding (or anyone else) I'd like to do the same thing. I was looking at the PDFObjectCopier, a naive approach would be to reuse an existing Page instance [instead of cloning it](https://github.com/Hopding/pdf-lib/blob/93dd36e85aa659a3bca09867d2d8fac172501fbe/src/core/PDFObjectCopier.ts#L55). But it feels way too simple to be true, surely merging and copying are different things right?

**Comment by bencooling** [comment]
Did anyone find a solution for this by chance, or any plan for it to be added as feature in future?

**Comment by bencooling** [comment]
FYI: This worked for me (embeds two pages side by side into one page)

```
const { PDFDocument } = require('pdf-lib');
const fs = require('fs');

const file1 = fs.readFileSync('./a.pdf');
const file2 = fs.readFileSync('./b.pdf');

(async () => {
  const pdfDoc1 = await PDFDocument.load(file1);
  const pdfDoc2 = await PDFDocument.load(file2);

  const page1 = pdfDoc1.getPages()[0];
  const page2 = pdfDoc2.getPages()[0];

  const mergedPdfDoc = await PDFDocument.create();
  const mergedPage = mergedPdfDoc.addPage([page1.getWidth() * 2, page1.getHeight()]);

  const [embeddedPage] = await mergedPdfDoc.embedPdf(page1.doc);
  const [embeddedPage2] = await mergedPdfDoc.embedPdf(page2.doc);

  mergedPage.drawPage(embeddedPage, {
    x: 0,
    y: 0,
  });
  mergedPage.drawPage(embeddedPage2, {
    x: page1.getWidth(),
    y: 0,
  });

  const mergedPdfBytes = await mergedPdfDoc.save();
  fs.writeFileSync('./c.pdf', mergedPdfBytes);
})();
```

**Comment by oiver555** [comment]
Wow this code snippet was so helpful, I was very close to giving up lol
