### ISSUE TITLE
Typescript Errors When Installed in Angular 6 (pdf-lib ver 1.15.0)

### ISSUE THREAD

**Issue by jonlave** [Hopding/pdf-lib#749]
I've already tried to uninstall and re-install typescript, but it didn't seem to help. Not sure if I can ignore these since they are in an external package.

Typescript version: 2.7.2

ERROR in node_modules/pdf-lib/cjs/api/colors.d.ts(27,63): error TS1005: ',' expected.
node_modules/pdf-lib/cjs/api/colors.d.ts(28,64): error TS1005: ',' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,67): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,120): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,177): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,226): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,279): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,336): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,391): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroNonTerminal.d.ts(10,21): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroNonTerminal.d.ts(10,22): error TS1003: Identifier expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroNonTerminal.d.ts(10,44): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroTerminal.d.ts(13,21): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroTerminal.d.ts(13,22): error TS1003: Identifier expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroTerminal.d.ts(13,44): error TS1005: ';' expected.

**Comment by dPliakos** [comment]
I'm getting errors too when I'm using typescript 2.9.2 (used in an angular 6 project)

```
ERROR in node_modules/pdf-lib/cjs/core/streams/Stream.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdf-lib/cjs/core/streams/Stream.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/pdf-lib/cjs/api/PDFDocumentOptions.d.ts(4,15): error TS1066: In ambient enum declarations member initializer must be constant expression
```

**Comment by BlueClouDragon** [comment]
Hello @jonlave and @dPliakos, Did you solve this problem?

**Comment by jonlave** [comment]
@BlueClouDragon No, I ended up having to use an alternative library, jsPDF. It's not ideal, but I was able to get a solution working with that.

**Comment by BlueClouDragon** [comment]
thanks to your response, I am fixing pdf-lib code for v6

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.

**Comment by dPliakos** [comment]
For the record, in the end I used the `skipLibCheck` typescript option to bypass the typing errors

**Comment by rafaneri** [comment]
> For the record, in the end I used the `skipLibCheck` typescript option to bypass the typing errors

What's the version of your rxjs and typescript?

**Comment by dPliakos** [comment]
- rxjs@6.3.3
- typescript@2.9.2

**Comment by rafaneri** [comment]
> * rxjs@6.3.3
> * typescript@2.9.2

Is the angular version 6? What's the version of pdf-lib?

I'm using this:

``` json
    "pdf-lib": "1.17.0",
    "rxjs": "6.3.3",
    "rxjs-compat": "6.2.2",
    "typescript": "^2.7.2",
```

I tried to put **skipLibCheck** in my tsconfig.json, but without effect:

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "esModuleInterop": true,
    **"skipLibCheck": true,**
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "es2016", "es2015", "dom"]
  },
  "include": ["main.ts", "src/**/*"],
  "exclude": ["node_modules"]
}
```

I'm still getting...

```bash
ERROR in node_modules/pdf-lib/cjs/api/colors.d.ts(27,63): error TS1005: ',' expected.
node_modules/pdf-lib/cjs/api/colors.d.ts(28,64): error TS1005: ',' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,67): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,120): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,177): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,226): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,279): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,336): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/api/form/appearances.d.ts(32,391): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroNonTerminal.d.ts(10,21): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroNonTerminal.d.ts(10,22): error TS1003: Identifier expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroNonTerminal.d.ts(10,44): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroTerminal.d.ts(13,21): error TS1005: ';' expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroTerminal.d.ts(13,22): error TS1003: Identifier expected.
node_modules/pdf-lib/cjs/core/acroform/PDFAcroTerminal.d.ts(13,44): error TS1005: ';' expected.
```

**Comment by JesseFriedman01** [comment]
Wanted to follow up on this issue. Was there ever a resolution? I'm experiencing the same error with pdf-lib version 1.17.0.

Per rxjs, typescript versions:

rsjx@6.2.1
typescript@2.7.2

Thanks!

**Comment by stefnotch** [comment]
@JesseFriedman01 I think the reasonable solution would be to upgrade to a newer version of Typescript/Angular. Typescript Version 2.7 is already four years old at this point. The current version is 4.7.4, with 4.8 coming up.

**Comment by stefnotch** [comment]
`"skipLibCheck": true` would be the alternative, which should work in some cases. You might have to make sure that Angular actually picks up on the `tsconfig.json` https://stackoverflow.com/questions/43136859/angular-cli-ignores-tsconfig-json

**Comment by tandy077** [comment]
A=>Error message：
ERROR in node_modules/pdf-lib/ts3.4/cjs/api/form/PDFDropdown.d.ts:400:38 - error TS2502: 'provider' is referenced directly or indirectly in its own type annotation.

    400     updateAppearances(font: PDFFont, provider?: AppearanceProviderFor<PDFDropdown>): void;
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    
    ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
    i ｢wdm｣: Failed to compile.
B=>Version information：
node -v> v14.21.3
npm -v> 6.14.18
ng -v=>
@angular-devkit/architect 0.803.29
@angular-devkit/build-angular 0.803.29
@angular-devkit/build-optimizer 0.803.29
@angular-devkit/build-webpack 0.803.29
@angular-devkit/core 8.3.29
@angular-devkit/schematics 8.3.29
@angular/cdk 8.2.3
@angular/cli 8.3.29
@angular/elements 9.0.0
@angular/material 8.2.3
@ngtools/webpack 8.3.29
@schematics/angular 12.2.18
@schematics/update 0.803.29
rxjs 6.4.0
typescript 3.4.3
webpack 4.39.2
