### ISSUE TITLE
_this.catalog.Pages.traverse is not a function

### ISSUE THREAD

**Issue by minhnhatspk** [Hopding/pdf-lib#75]
As the title, I got that error when attaching some text on my pdf file.
here is full error logs
```
Found Linearization param dict and cross reference index, but no associated trailer.
/Users/minhnhat/Documents/MN/test/pdf-lib/examples/document_modification/node/node_modules/pdf-lib/lib/core/pdf-document/PDFDocument.js:48
            _this.catalog.Pages.traverse(function (kid) {
                                ^

TypeError: _this.catalog.Pages.traverse is not a function
    at PDFDocument.getPages (/Users/minhnhat/Documents/MN/test/pdf-lib/examples/document_modification/node/node_modules/pdf-lib/lib/core/pdf-document/PDFDocument.js:48:33)
    at Object.<anonymous> (/Users/minhnhat/Documents/MN/test/pdf-lib/examples/document_modification/node/index.js:49:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```
Could you guys help me find the problem?
see my attached file.
[asample.pdf](https://github.com/Hopding/pdf-lib/files/2884150/asample.pdf)

**Comment by Hopding** [comment]
@minhnhatspk I found the bug causing this issue and fixed it in https://github.com/Hopding/pdf-lib/pull/76.

I just cut prerelease [`0.6.1-rc3`](https://www.npmjs.com/package/pdf-lib/v/0.6.1-rc3) with the fix.

You can install this prerelease with npm:
```
npm install pdf-lib@0.6.1-rc3
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.1-rc3/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.1-rc3/dist/pdf-lib.min.js

Please try it out and let me know if it works for you!

P.S. It looks like you are using the `document_modification` example. You'll need to update it's [`package.json`](https://github.com/Hopding/pdf-lib/blob/master/examples/document_modification/node/package.json#L13) to use this prerelease. Once I cut this as an official release, I'll update the example's `package.json` as well.

**Comment by Hopding** [comment]
@minhnhatspk I'd like to add the `asample.pdf` you shared to this repo so I can write an integration test for this bug fix. Do you mind if I do that? Does it have any private info in it?

**Comment by minhnhatspk** [comment]
> @minhnhatspk I'd like to add the `asample.pdf` you shared to this repo so I can write an integration test for this bug fix. Do you mind if I do that? Does it have any private info in it?

Yes, you can use it.
Thanks for you help.

**Comment by Hopding** [comment]
Great, thanks!
