### ISSUE TITLE
Support for Text Styles: Bold, Italic, Underline

### ISSUE THREAD

**Issue by soadzoor** [Hopding/pdf-lib#752]
Hello @Hopding ,

I can't express how much I love this lib, although from time to time I bump into some obstacles when I try to achieve some basic things. Now it's the font styles. As far as I know there's no easy way to achieve **bold**, _italic_, nor <ins>underlined</ins> texts with this lib.

In theory I could load up a bold version of the font if I want to have bold. Also, I could load up an italic version if I want to have italic. But what if I want to have both of them at the same time? There's usually no "combined" versions, so I'd have to create my own. Even then, if someone wants to combine those things (eg.: `bold-italic`, `italic-underlined`, `bold-italic-underlined`, etc), we'd need to load 2^3 = 8 `ttf` files altogether for a single font-family, which is crazy.

I'm pretty sure there's a better way to do this. Ideally, we could pass some boolean arguments within the `drawText`'s options object, and it would just work as it should.

I'd gladly take a deeper look, and try to come up with a PR, but first I just wanted to ask your opinion. And maybe if you could give me a direction of where I should start, that would be very helpful.

Thanks,
Peter

**Comment by tw1t611** [comment]
There is a workaround for `bold` and `italic`

Many fonts do have `bold` and `italic` versions of itself. You can generate a new font of this version and update the appearance.

1. Create the fonts you need
```js
    pdfDoc.registerFontkit(fontkit);
    const fontBytes = fs.readFileSync(__dirname + "/MuseoSans-300.otf");
    const fontBytesBold = fs.readFileSync(__dirname + "/MuseoSans-900.otf");
    const font = await pdfDoc.embedFont(fontBytes);
    const fontBold = await pdfDoc.embedFont(fontBytesBold)
```

2. Update the appearance of all acro form text fields to get the default font
(this step is optional, but I want to share it, because it was hard to figure out and is not documented)

```js
    const fields = form.getFields();
    fields.forEach((field) => {
      const type = field.constructor.name;
      const name = field.getName();
      console.log(`${type}`);
      if (type === "PDFTextField")
        form.getTextField(name).updateAppearances(font);
    })
```

3. Update the fields you want to styles with styled fonts
```js
    form.getTextField("Fahrzeugnettopreis").updateAppearances(fontBold);
```

**Comment by soadzoor** [comment]
@tw1t611 Thanks for your ideas, although I believe I was already aware of such workarounds. But they're really not convenient/efficient. What do you do if you want to have bold AND italic fonts? See the second paragraph in my OP, starting with ```In theory I could load up...```

**Comment by tw1t611** [comment]
@soadzoor You are right. It really only is a workaround for people how need `bold` or `italic`. I just wanted to share a solution, for I couldn't fine one in the docs. The problem itself remains. Sadly I am not very experienced with `pdf`.
This is something the devs would need to implement.

Personally I would add something like `makeBold()`, `makeItalic(angle)`... methods to `TextField`.

Page 10 of the specs show the options:
![image](https://user-images.githubusercontent.com/13353525/123589071-fa7fdc00-d7e8-11eb-8109-2edb607d74f0.png)

https://adobe-type-tools.github.io/font-tech-notes/pdfs/T1_SPEC.pdf

I could imagine, this would not be hard to implement. @Hopding seems to be inactive since January though and its hard to contact him.

**Comment by Hopding** [comment]
@soadzoor I agree. Would definitely like to improve support for this type of thing. I need to spend some time researching options to figure out the best way to handle this. It's listed in the roadmap for tracking purposes https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by SikandAlex** [comment]
@Hopding 

Is there an example for this in the docs? This issue is not linked to an MR and the roadmap just links back to the issue.

edit: Sorry I read “closed as completed” thinking it was implemented.

**Comment by SikandAlex** [comment]
Sorry I read “closed as completed” thinking it was implemented.

**Comment by MickL** [comment]
@Hopding Is underline implemented? The issue is marked as completed but I cant find any option to do so.  There is also #1272

For bold and italic the font needs to be change, I guess this is okay.

**Comment by GitHubRulesOK** [comment]
@MickL Underline is NOT generally a PDF construct it needs to be emulated one way or another 
1) A font.ttf especially constructed by adding a line into the font https://www.1001fonts.com/underlined-fonts.html

2) An especially unusual UTF emulation encoding like https://yaytext.com/underline/ these will be found in HTML files but exceptionally rare for a PDF.

3) A word processor draws a line across/under a text selection and that is exceptionally easy to do with PDF as you draw a graphic line from before <strike>A to after B</strike> but how to raise or lower the line is usually done in a GUI like Adobe Pro

**Comment by MickL** [comment]
I know it needs to be done manually. But without underline most usecases for PDFs like invoices are not possible and therefor the whole library is kinda useless innit?

Unfortunately I needed to switch back to pdfkit who does has an underline feature.

**Comment by MickL** [comment]
@hopding could you please reopen?

**Comment by thevalleyy** [comment]
Yeah... Text styles. A little story

I'm also working with pdf-lib and I need text styles, just like everyone else does. First I thought that pdf-lib had an option to apply text styles automatically somehow. Hmm, doesn't seem like that. 
Alright, I wrote a function then that detects manual markdown-like formatting (\*\*bold\*\*, \_\_italic\_\_, \~\~strikethrough\~\~) just to find out that there isn't even an option in the `drawText` function to apply the styles...

I don't understand how a pdf library lacks this basic feature, or am I somehow wrong? 
It's also very disappointing to see @Hopding just ignoring the comments and the community in general. I think repo ownership should be transferred if he doesn't find time to oversee all these issues and feature suggestions.

**Comment by MickL** [comment]
I highly recommend not to use this, or any other, js/ts library. It is a bottomless hole. Personally I switched to [weasyprint](https://weasyprint.org) which uses html/css, so no special markup needs to be written and it can create the most complex pdf's.

**Comment by thevalleyy** [comment]
Yeah, I can basically watch the hour hand of my clock turn as I try to figure out how to create PDFs using pdf-lib. I've also wondered if this would've been faster using a webapp which then prints to PDF. 
Thank you for your suggestion and I'll definitely have a look into it on my next PDF project :+1:
