### ISSUE TITLE
Support Creation and Editing of Tagged PDFs or PDF/UA

### ISSUE THREAD

**Issue by danshick** [Hopding/pdf-lib#756]
I don't see any documentation supporting tagging PDFs or editing tags on existing PDFs. Is this a capability that pdf-lib is interested in supporting?

https://www.pdfa.org/wp-content/uploads/2015/12/StructureElementsBestPracticeGuide_2016-01-19.pdf

**Comment by kndt** [comment]
Any information regarding this issue?

**Comment by danshick** [comment]
> Any information regarding this issue?

What information would be helpful?

**Comment by kndt** [comment]
@danshick To know if there's any intention to support the listed features

**Comment by danshick** [comment]
If you are asking me, I'm afraid I dont have the expertise (or the time to gain it) to offer support. My issue was an inquiry as to whether this feature might land in a roadmap for this project.

**Comment by Hopding** [comment]
Support for PDF/A is listed in now listed in the research section of the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
