### ISSUE TITLE
How to change DPI

### ISSUE THREAD

**Issue by funnymomo** [Hopding/pdf-lib#758]
Looks like the pdf's are created with a default of 72 DPI. 
How do I change the default to say 150 ?

**Comment by ahansson89** [comment]
@funnymomo, did you find a solution for this? I need to generate PDFs with 300 dpi

**Comment by ahansson89** [comment]
@Hopding maybe you can provide some guidance on this?

I have a PDF, which is generated by Puppeteer. Puppeteer has a default DPI of 72, which can not be changed. I need to provide the PDF with a DPI of 300 to an external provider.

The external provider accepts the PDF with the dimensions of 305 x 305mm and 3544x3544px my generated PDF is 3544 x 3544px with physical dimensions of 12502 x 12502mm

How would you go about getting the DPI to 300 with your library?

**Comment by ahansson89** [comment]
Actually, after researching this, this is not an issue.

PDFs scale as fonts and texts are vectors, so generating a 72 DPI will scale up to 300 DPI just fine. The only thing that does not scale up is images for obvious reasons. Images are embedded and fill the container they are put in. So just make sure you include images at full resolution.

**Comment by Hopding** [comment]
@ahansson89 is right. If you're still having trouble with this, please open a new Discussion with additional details (you can use the [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form as a template.
