### ISSUE TITLE
Can pdf-lib be used as a node.js module?

### ISSUE THREAD

**Issue by mboehmhh** [Hopding/pdf-lib#761]
Hi everybody!
Can anyone tell me if there is a way to use pdf-lib as node.js module and how?
Regards

**Comment by btecu** [comment]
Yes, add it to your `package.json` dependencies and use it by importing directly:
```js
const { PDFDocument } = require('pdf-lib');
```

**Comment by Hopding** [comment]
@btecu is spot on!
