### ISSUE TITLE
[Support] Is it possible to get the bounding box of all visible items in the PDF?

### ISSUE THREAD

**Issue by davidmhewitt** [Hopding/pdf-lib#762]
Hi, thanks for the great library!

I'm currently working on a use case where I'd like to prepare some PDFs for printing. The printer adds some quite large print marks that cover the left 7% of the page so I'd like to add margins to avoid content getting covered.

To begin, I've used the `setSize` and `translateContent` methods on `PDFPage` and proven that I can scale the page and move the content to introduce a margin on the left side of the page.

However, in an ideal world, I wouldn't do this for every page, just pages that didn't already have enough margin.

Is there a way I can iterate through all visible objects in a page and check if their bounding box intersects a certain area of the page?

Thank you!

**Comment by Hopding** [comment]
I'm not entirely sure. Need some visuals and code snippets to better understand your question.
