### ISSUE TITLE
Add stroke to text?

### ISSUE THREAD

**Issue by OctaneInteractive** [Hopding/pdf-lib#763]
Hi!

I see that the [drawText() method doesn't have an option for stroke](https://pdf-lib.js.org/docs/api/interfaces/drawtextoptions), but I was wondering if it would be possible to add one somehow?

As an example (and I'm guessing, here), would it be possible to convert text to an outline and add a stroke to it?

**Comment by Hopding** [comment]
This is definitely possible to do. There are operators that can be used for this: https://pdf-lib.js.org/docs/api/#const-fillandstroke. I don't have time to provide an example myself, but if you search the issues you'll find some places where I've provided examples of how to use the low level operators API. See also https://pdf-lib.js.org/docs/api/classes/pdfpage#pushoperators.

**Comment by mmayla** [comment]
Hey @OctaneInteractive did you manage to do it? I would be grateful if you provide an example of how to do it as I couldn't achieve it using the low-level operators.

**Comment by OctaneInteractive** [comment]
> Hey @OctaneInteractive did you manage to do it? I would be grateful if you provide an example of how to do it as I couldn't achieve it using the low-level operators.

Sadly, no — I had to abandon this option in the project.

**Comment by alexbrazier** [comment]
I've got this working using this:

```ts
const drawOutlinedText = (
  page: PDFPage,
  text: string,
  options: PDFPageDrawTextOptions
) => {
  page.pushOperators(
    pushGraphicsState(),
    setFillingColor(rgb(0, 0, 0)),
    setStrokingColor(rgb(1, 1, 1)),
    setTextRenderingMode(TextRenderingMode.FillAndOutline),
    setLineWidth((options.size || 25) / 25)
  );

  page.drawText(text, options);

  page.pushOperators(popGraphicsState());
};
```

```ts
 drawOutlinedText(page, "Hello World!", {
    x: 50,
    y: 70,
    size: 30,
  });
```

![image](https://github.com/Hopding/pdf-lib/assets/5689874/03c653de-b47f-4e20-890f-9093474a195e)
