### ISSUE TITLE
page.getHeight() returning negative value

### ISSUE THREAD

**Issue by kevinswartz** [Hopding/pdf-lib#764]
Hello again @Hopding !
I've come across a strange pdf that is returning me negative values for page.getHeight().  I've attached it here.  If you pull page.getHeight() for the first page, you get -792.  Interestingly enough nothing seems to be broken, I use Math.abs on the value and use pdf-lib like normal without issue.

I reproduced this on pdf-lib 1.9.0, and 1.15.0.
Thanks again for your help!  This library is fantastic.

[merged.pdf](https://github.com/Hopding/pdf-lib/files/5846389/merged.pdf)

**Comment by Hopding** [comment]
Hey @kevinswartz! Thanks for the report, definitely something I want to get fixed. Added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by LonHon** [comment]
@Hopding 

same problem，v1.17.1
![image](https://github.com/user-attachments/assets/e0e03bc3-c138-4bee-a05c-3c7c576b2e33)
