### ISSUE TITLE
[bug+fix] Example PDF file (dod_character.pdf) has wrong field type.

### ISSUE THREAD

**Issue by Sjoerd82** [Hopding/pdf-lib#765]
While troubleshooting #755 I came across the following:

The field "Faction Symbol Image" is currently a "Text Field", but should be "Button":
![image](https://user-images.githubusercontent.com/15013786/105344261-fd93f200-5be2-11eb-852f-f35304eb72e4.png)

The corrected PDF is attached, I tried to create a new branch/pull request, but I think I don't have that authorization. So perhaps someone else can update this asset: [dod_character.pdf](https://github.com/Hopding/pdf-lib/files/5848983/dod_character.pdf)

**Comment by btecu** [comment]
Why _should_ it be a button? I changed it to a `TextField` to illustrate stamping an image on a `TextField` here https://github.com/Hopding/pdf-lib/pull/718.

**Comment by Sjoerd82** [comment]
Aha, I had no idea that was a thing. Originally this field is a button, allowing for changing the image. As I understand it, "stamping" creates a sort of static image? Perhaps add this as a note to the example. I will close this issue.
