### ISSUE TITLE
Low Quality PNG Image added on Pdf-lib.

### ISSUE THREAD

**Issue by princ09** [Hopding/pdf-lib#766]
[blank-BV.pdf](https://github.com/Hopding/pdf-lib/files/5849458/blank-BV.pdf)
![callOut_man](https://user-images.githubusercontent.com/47990313/105355060-83319500-5c17-11eb-9e89-9c1243c0ece6.png)
Hi I am working on this Lib from last 4 month. It's very Great Lib. but I noticed that images getting blur / low resolution after adding it to PDF. 
I am sure why this Happening. I have added Image and resulted pdf both for reference. Any Reason why this might happening?
````
let url = this.getCanvasUrl(+i, pageRotation.angle);
	console.log(url);
	const pngBytes = await fetch(url).then((res) => res.arrayBuffer());
	const pngImage = await this.pdfDoc.embedPng(pngBytes);
	let x = 0;
	let y = 0;
	currentPage.drawImage(pngImage, {
		x: x,
		y: y,
		width: drawWidth,
		height: drawHeight,
		rotate: degrees(pageRotation.angle),
	});
````

above is simplified version of my code for adding Image. i also checked my canvas url , there is no issue.

Thanks In Advance.

**Comment by princ09** [comment]
I found that blurriness happening because of changing width  & height of canvas whose data URL I am generating. If i don't make any changes to canvas dimension , there is no blurriness at all.  Default size of canvas is same as pdf page size. 
It's too weird , I don't have idea how to solve it.

**Comment by Hopding** [comment]
Working with canvases is outside the scope of `pdf-lib`. You'll have to find a different forum to get help with that.
