### ISSUE TITLE
Can we set the font size (to auto) in the new form filling API?

### ISSUE THREAD

**Issue by Sjoerd82** [Hopding/pdf-lib#767]
In recent versions of pdf-lib we now have the form-filling API, no longer do we need to work directly with those AcroForms. As mentioned in #48:

> `pdf-lib` now has form creation and filling APIs that should be used instead of the above example(s). See the [form filling JSFiddle](https://jsfiddle.net/Hopding/0mwfqkv6/3/) for a working example. Additional information is available in the [README](https://github.com/Hopding/pdf-lib/blob/master/README.md) and [API docs](https://pdf-lib.js.org/docs/api/classes/pdfform). The [`PDFTextField.setText`](https://pdf-lib.js.org/docs/api/classes/pdftextfield#settext) method is of particular relevance to this issue.

However, at this point we may seem have lost the ability to set the font size to **Auto**? When I now use setText(), it reverts the size from auto (as specified in the PDF) to 12. Preventing the text to scale down. Is there a solution for this?

**Comment by leapdev1** [comment]
Having the same issue wit the new [form-filling API](https://pdf-lib.js.org/docs/api/) as well

**Comment by Hopding** [comment]
https://github.com/Hopding/pdf-lib/pull/983 might help here. If not, please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form and we can pick things up there.

**Comment by khanhubgit** [comment]
You can also set form fields font size to Auto with JavaScript
`pdfDoc.addJavaScript("customJS", "for(var i = 0; i < this.numFields; i++) {
         this.getField(this.getNthFieldName(i)).textSize = 'Auto'
     }"
)`

**Comment by zacwellmer** [comment]
@Hopding I don't think #983 covers it since it sets the fontsize based on the field size. However, Acrobat has a way to set the font size to `Auto`, which will set the font size based on the content.
<img width="523" alt="image" src="https://github.com/Hopding/pdf-lib/assets/9603276/06103ad4-0368-4963-87f2-7a2212661d81">

One work around is to avoid the [assertPositive](https://github.com/Hopding/pdf-lib/blob/93dd36e85aa659a3bca09867d2d8fac172501fbe/src/api/form/PDFTextField.ts#L340) by calling
```typescript
// @ts-expect-error
textField.acroField.setFontSize('Auto')
```

**Comment by Dude29** [comment]
I'm having some trouble using the workaround provided by @zacwellmer. 

It seems that the font size set to auto that way is not propagated to the PDF and it ends up still being overwritten with a numeric font size 😕 

I've tried marking the fields as dirty after setting the size but that didn't seem to make a difference. 
I even tried setting the DA string with the Auto value in there following the suggestions from [this comment](https://github.com/Hopding/pdf-lib/issues/727#issuecomment-752842433) but the problem persisted.

@Hopding Could you reopen this issue?

**Comment by Filipe-QuickFlip** [comment]
@Dude29 
I'll start by apologizing for my English, but I imagine that what could solve your problem with dynamically sized text would be the solution I found, I defined `textField.acroField.setFontSize(0)`, the text is being changed based on the number of characters, However, if the text is too short and the textField is large, the text will be too large and the opposite also happens, this solution solved my problem, I hope it helps

**Comment by gbryant3000** [comment]
@Dude29 

**Issue**
We have had an issue where we have PDFs with multiple of the same named field in a form all set to auto font size, some fields have less room, some have more, so the filled size should vary, but pdf-lib was running the auto size logic once and setting all widgets of the field to the same font size.

**Solution**
Comment out the call to updateDefaultAppearance in `src/api/form/appearances.ts` around  line number 487:

```
  if (widgetColor || widgetFontSize !== undefined) {
    updateDefaultAppearance(widget, textColor, font, fontSize);
  } else {
    // updateDefaultAppearance(textField.acroField, textColor, font, fontSize);
  }
```

This prevents the source textField from having its font size set, allowing all display widgets to get autosize logic, this works for me, but could break something for you, good luck.

**Comment by psamaan** [comment]
I'm having the same issue as @Dude29, and unfortunately @Filipe-QuickFlip 's answer doesn't solve it.

Setting `textField.acroField.setFontSize(0)` leads to the size of the font to change at PDF creation time, but it is _set_ to a number still, not to "Auto". The only way I've managed to achieve a setting of "Auto" so far has been following @khanhubgit 's suggestion.

@Hopding is there a way to achieve this without runtime javascript? guidance would be much appreciated, or if you see this as a bug I'm happy to open a bug report as well.
