### ISSUE TITLE
Text drawn using page.drawText doesn't work on MacOS

### ISSUE THREAD

**Issue by pedro-surf** [Hopding/pdf-lib#768]
I want to generate pagination number for each of my doc pages. 
On Windows, it creates fine, however on Mac it's not being added.

**Comment by moos** [comment]
Adding a code snippet would be useful to help you.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
