### ISSUE TITLE
Flattened documents will not print using Adobe products

### ISSUE THREAD

**Issue by bjbk** [Hopding/pdf-lib#771]
Issue: A flattened PDF using the `form.flatten()` method will not print using Adobe Acrobat Reader or Adobe Pro. (Both macOS and Windows 10)

No Page Selected error

PDF Expert, Preview and other readers are unaffected.

Fix: remove flatten method.

Note: Setting the fields as read only works fine and the document will print.
`fields.forEach(f => f.enableReadOnly())`

**Comment by btecu** [comment]
The issue has been fixed, it's just it has not been released yet.
cc @Hopding

**Comment by bjbk** [comment]
Thanks for the update!  Will keep an eye out.

**Comment by andrewdcato** [comment]
Found this thread while researching a similar issue - upgrading from 1.14.x to 1.16 resolved for me!

**Comment by 700software** [comment]
See: https://github.com/Hopding/pdf-lib/issues/800#issuecomment-981404466
