### ISSUE TITLE
pdfDoc.addJavaScript is not a function

### ISSUE THREAD

**Issue by viveksingh007** [Hopding/pdf-lib#772]
I am trying to add custom validation on textField using the addJavaScript function. While doing so getting an error 'pdfDoc.addJavaScript is not a function'. Adding the code snippet

`const pdfDoc = await PDFDocument.create()

        pdfDoc.addJavaScript(
            'foo',
            'function foo() { return "foo"; }'
        );`

Above javaScript function want to call on textFiled change event.

Please help me to achieve this.

**Comment by timothyjohnwilson** [comment]
Bump

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
