### ISSUE TITLE
[Feature request] drawText() option to add pages as needed

### ISSUE THREAD

**Issue by moos** [Hopding/pdf-lib#774]
Use Case:  Trying to emulate "Save as PDF" feature of the browser (aside from Chrome extension API, I've found no way to intercept the generated PDF in JS).

It'd be great if `page.drawText()` could add pages as needed.  It already does line wrapping (`maxWidth` option).  

Note:  this feature is available in **pdfkit**'s [line-wrapper](https://github.com/foliojs/pdfkit/blob/master/lib/line_wrapper.js#L171).

**Comment by moos** [comment]
I've got this mostly working locally by breaking the text into lines and drawing each line.  I've had to turn off line wrapping because it messes up my height calculation. (`newPage` simply does an `doc.addPage([w, h])` and sets other page params.)

```js
    newPage();
    let lines = text.split('\n');
    lines.forEach(line => {
        page.drawText(line, {
            x: border,
            y,
            // FIXME line wrapping messes up our height calc
            // maxWidth: pageWidth - 2 * border
        });
        y -= lineHeight;
        if (y + lineHeight <= border) newPage();
    })
```
As an interim, if `drawText` could return the number of rendered lines (including wrapped lines), then this will work:
```js
   let linesAdded = page.drawText(line, opts);
   y -= linesAdded * lineHeight;
```

**Comment by Hopding** [comment]
Better typography & text layout support is on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
