### ISSUE TITLE
Mutltiline drawText() does not honor blank lines

### ISSUE THREAD

**Issue by moos** [Hopding/pdf-lib#775]
Using `drawText()` with the `maxWidth` option breaks long text into multiple lines (using the `PDFLib.breakTextIntoLines()`).

 Lines with spaces only do get returned.
```
PDFLib.breakTextIntoLines('aa \n \n \nbb cc', [' '], 10, () => 3)
(4) ["aa ", " ", " ", "bb cc"]  // 4 lines ✔️ 
```
But completely blank lines don't get returned. 
```
PDFLib.breakTextIntoLines('aa \n\n\nbb cc', [' '], 10, () => 3)
(2) ["aa ", "bb cc"]  // 2 lines  ❌ 
```
pdf-lib 1.15.0

**Comment by moos** [comment]
Interim fix is to add a space to blank lines in the incoming text:
```
drawText(text.split('\n\n').join('\n \n'), {...});
```

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) or [proposal](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=proposal%2Cneeds-triage&template=proposal.yml) form if you're still interested in this.
