### ISSUE TITLE
Adobe Reader ERROR 14

### ISSUE THREAD

**Issue by ezehurt** [Hopding/pdf-lib#778]
I get an error on opening files that have more than one page with adobe reader. It's just with adobe reader.
Adobe Reader XI 
Version 11.0.23 (but i tested with others and also happend)
The first page looks fine, but when I click to go second page 
![image](https://user-images.githubusercontent.com/7167879/106044523-2125d380-60e0-11eb-8ab8-abd0ff186de7.png)
Second page.
![image](https://user-images.githubusercontent.com/7167879/106043940-5e3d9600-60df-11eb-99df-07a9af46f871.png)
and sometimes do this
![image](https://user-images.githubusercontent.com/7167879/106044619-4581b000-60e0-11eb-9905-3a88c06910b1.png)

Im saving the pdf like this.
` pdfDoc
                      .save({ useObjectStreams: false })
                      .then((pdf) => {
                        pdfBytes = pdf;
                        pdfName = 'Order_${shippmentID}.pdf';
                        resolve(pdfBytes);
                      })
                      .catch((error) => {
                        console.log('Cant save pdf', error);
                      });`

I also tried without the useObjectStreams: false.
I draw images and text in other pages
Only its happening with Adobe Reader. If I open the file with browser, its ok. 

Any idea?

**Comment by p-kuen** [comment]
I have similar problems just with Adobe Reader. In my case it is not even opening the pdf. I am drawing images and forms on the first page too.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
