### ISSUE TITLE
Add Link To Draw Image

### ISSUE THREAD

**Issue by alibakhshiilani** [Hopding/pdf-lib#781]
[https://stackoverflow.com/questions/65977523/set-link-for-pdf-image-annotation-in-pdf-lib](https://stackoverflow.com/questions/65977523/set-link-for-pdf-image-annotation-in-pdf-lib)

How Can I Add LInk To An Image 

`
const pngImage = await pdfDoc.embedPng(pngImageBytes)
        
        const pngDims = pngImage.scale(0.5)
        
        // Draw the PNG image near the lower right corner of the JPG image

        //   x: page.getWidth() / 2 - pngDims.width / 2 + 75,
        //   y: page.getHeight() / 2 - pngDims.height,
        page.drawImage(pngImage, {
            x:coordinations.x - pngDims.width / 2,
            y:coordinations.y - pngDims.height / 2,
            width: pngDims.width,
            height: pngDims.height,
        })

`

**Comment by alibakhshiilani** [comment]
i tried https://pdf-lib.js.org/docs/api/classes/pdfbutton

but it is annotation type 20 with subtype of widget 

but i want annotation type 2 with subtype of link and no background color so people can see image and click on annotation .....

**Comment by alibakhshiilani** [comment]
is there any hope ?

**Comment by RichardBray** [comment]
So you don't add a link to an image, instead, you draw a rectangle on the pdf that when clicked will go to a URL. You'll have to match the position of your rectangle to the position of your image.

```js
  const pdfUrlDict = pdfDoc.context.obj({
    Type: "Annot",
    Subtype: "Link",
    Rect: [imgXPos, imgYPos, (imgXPos + image.width), (imgYPos + image.height)],
    A: {
      Type: "Action",
      S: "URI",
      URI: PDFString.of("https://www.google.co.uk/"),
    },
  });
  const pdfUrl = pdfDoc.context.register(pdfUrlDict);

  page.node.set(PDFName.of("Annots"), pdfDoc.context.obj([pdfUrl]));
```

**Comment by Hopding** [comment]
@RichardBray is spot on!

**Comment by Tapasvi48** [comment]
can i do same for the signature image to add widgetDict for sign over a drawn image .
