### ISSUE TITLE
form.flatten is not a function

### ISSUE THREAD

**Issue by Deizadave** [Hopding/pdf-lib#782]
Hello.
I filled the fields of a pdf using a library (pdfform.js) and I'm trying to flatten it using pdf-lib but I'm getting "form.flatten is not a function" error message.
Other methods like getPages() and getForm().getFields() work well but getForm().flatten() throws an error.
Please I need help with this urgently.

**Comment by btecu** [comment]
What version are you using?

**Comment by Deizadave** [comment]
> What version are you using?

1.12

**Comment by btecu** [comment]
The feature does not exist in 1.12, use 1.16.

**Comment by Deizadave** [comment]
I've updated and it works. Thanks!
