### ISSUE TITLE
form.removeField() fails with "Error: Unexpected N type: undefined"

### ISSUE THREAD

**Issue by ShaheedHaque** [Hopding/pdf-lib#789]
I have some code which looks like this:
```js
    const tmp = form.getFields().find(f => f.getName() === changeField.name);
    form.removeField(tmp);
```
which fails with the message "Error: Unexpected N type: undefined" like this:
```
VM5571:17 Uncaught (in promise) c
    at e.t.getNormalAppearance (eval at importUMD (mypdf.html:12), <anonymous>:17:380111)
    at e.findWidgetAppearanceRef (eval at importUMD (mypdf.html:12), <anonymous>:17:477503)
    at e.removeField (eval at importUMD (mypdf.html:12), <anonymous>:17:476260)
    at PdfEditor.setUrl (mypdf.html:583)
```
The [code](https://github.com/Hopding/pdf-lib/blob/d213f921237daca7a5e21fb38eb69d733ff34796/src/core/annotation/PDFAnnotation.ts#L65) has lines like this:
```js
  getNormalAppearance(): PDFRef | PDFDict {
    const AP = this.ensureAP();
    const N = AP.get(PDFName.of('N'));
    if (N instanceof PDFRef || N instanceof PDFDict) return N;

    throw new Error(`Unexpected N type: ${N?.constructor.name}`);
  }
```
and the issue is that the result of `AP.get()` is `undefined`. In the call to `ensureAP()`:
```js
ensureAP(): PDFDict {
    let AP = this.AP();
    if (!AP) {
      AP = this.dict.context.obj({});
      this.dict.set(PDFName.of('AP'), AP);
    }
    return AP;
  }
```
I can see that `this.AP()` returns `undefined`, and so we enter the `if` block which, IIUC, sets up an empty AP dict.

FWIW, I'm using the latest code via CDN (and I'm not especially familiar with either PDF or JS or TS).

**Comment by ShaheedHaque** [comment]
The following workaround bypasses the above error:
```js
    const tmp = form.getFields().find(f => f.getName() === changeField.name);
    # Ensure AP has an N entry.
    const widget0 = tmp.acroField.getWidgets()[0];
    const AP = widget0.ensureAP();
    AP.set(pdfLib.PDFName.of('N'), pdfLib.PDFRef.of(0, 0));
    form.removeField(tmp);
```
However, my *actual* goal is not just to remove a field, but to *replace* it (e.g. swap a text input for a dropdown), and it seems that `removeField` is not quite enough, but I'll file a separate issue for that.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
