### ISSUE TITLE
How to get Annots  from pdf

### ISSUE THREAD

**Issue by wuqi713** [Hopding/pdf-lib#79]
Hi @Hopding ,
  I want know how to get the annotations from pdf ?

**Comment by wuqi713** [comment]
Relate of #39

**Comment by Hopding** [comment]
Hello @wuqi713.

There isn't currently a nice high-level API to get all the annotation from a PDF. But you can certainly still do it with `pdf-lib`. The code is just a bit low-level.

Essentially, to find all the annotations in a document, you'll have to visit each page and look at its `Annots` entry (which is an array of references to Annotation Dictionaries). I can write up an example script demonstrating how to do this, if you're able to provide me with a sample PDF that has some annotations in it.

-----

If you're interested, here's the relevant section from the [PDF specification](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) describing how Annotation Dictionaries are stored in PDF documents:

> **12.5.2 Annotation Dictionaries**
> The optional `Annots` entry in a page object (see 7.7.3, “Page Tree”) holds an array of annotation dictionaries, each representing an annotation associated with the given page. Table 164 shows the required and optional entries that are common to all annotation dictionaries. The dictionary may contain additional entries specific to a particular annotation type; see the descriptions of individual annotation types in 12.5.6, “Annotation Types,” for details. A given annotation dictionary shall be referenced from the `Annots` array of only one page. This requirement applies only to the annotation dictionary itself, not to subsidiary objects, which may be shared among multiple annotations.

**Comment by Hopding** [comment]
I'm going to close this issue for now. But please feel free to reopen it if you have more questions!

**Comment by fortrenitalia** [comment]
Hi @Hopding,
I would like to ask you to provide code for getting annotations from PDF document. I have attached the document with some annotations.
[t.pdf](https://github.com/Hopding/pdf-lib/files/3338162/t.pdf)

**Comment by Hopding** [comment]
Hello @fortrenitalia! 

Here's an example script demonstrating how to load a PDF and print out all the annotations it contains:
```js
// These are *all* possible PDF annotation types
const annotationSubtypes = [
  PDFName.from('Text'),
  PDFName.from('Link'),
  PDFName.from('FreeText'),
  PDFName.from('Line'),
  PDFName.from('Square'),
  PDFName.from('Circle'),
  PDFName.from('Polygon'),
  PDFName.from('PolyLine'),
  PDFName.from('Highlight'),
  PDFName.from('Underline'),
  PDFName.from('Squiggly'),
  PDFName.from('StrikeOut'),
  PDFName.from('Stamp'),
  PDFName.from('Caret'),
  PDFName.from('Ink'),
  PDFName.from('Popup'),
  PDFName.from('FileAttachment'),
  PDFName.from('Sound'),
  PDFName.from('Movie'),
  PDFName.from('Widget'),
  PDFName.from('Screen'),
  PDFName.from('PrinterMark'),
  PDFName.from('TrapNet'),
  PDFName.from('Watermark'),
  PDFName.from('3D'),
  PDFName.from('Redact'),
];

// Load a PDF
const pdfDoc = PDFDocumentFactory.load(...);

// Get an array of all the objects in the PDF
const objects = Array.from(pdfDoc.index.index.entries());

// Print out all the annotations in the PDF
objects.forEach(([ref, object]) => {
  const subtype = object.getMaybe('Subtype');
  if (
    object instanceof PDFDictionary &&
    annotationSubtypes.includes(subtype)
  ) {
    console.log(`Found annotation (${ref}) of type: ${subtype}`);
    console.log('----------------------------------');
    console.log(object.toString());
    console.log('----------------------------------');
    console.log();
    console.log();
  }
});
```

When run on the PDF you provided, it outputs the following:
```
Found annotation (149 0 R) of type: /Text
----------------------------------
<<
/AP <<
/N 128 0 R
/R 129 0 R
>>
/C [ 1 0.819611 0 ]
/Contents (test)
/CreationDate (D:20190628095759+02'00')
/F 28
/M (D:20190628095806+02'00')
/NM (c174acef-700d-450e-886f-4e18afe2d43e)
/Name /Comment
/P 127 0 R
/Popup 150 0 R
/RC (<?xml version="1.0"?><body xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/" xfa:APIVersion="Acrobat:19.12.0" xfa:spec="2.0.2" ><p dir="ltr"><span dir="ltr" styweight:normal;font-style:normal">test</span></p></body>)\
/Rect [ 171.998 733.619 195.998 757.619 ]
/Subj (Sticky Note)
/Subtype /Text
/T (miculka)
/Type /Annot
>>
----------------------------------


Found annotation (150 0 R) of type: /Popup
----------------------------------
<<
/F 28
/Open false
/Parent 149 0 R
/Rect [ 595.32 643.619 799.32 757.619 ]
/Subtype /Popup
/Type /Annot
>>
----------------------------------


Found annotation (151 0 R) of type: /Text
----------------------------------
<<
/AP <<
/N 128 0 R
/R 129 0 R
>>
/C [ 1 0.819611 0 ]
/Contents (test2)
/CreationDate (D:20190628095813+02'00')
/F 28
/IRT 149 0 R
/M (D:20190628095813+02'00')
/NM (a865be06-8593-4035-8383-fc38bf15024c)
/Name /Comment
/P 127 0 R
/Popup 152 0 R
/RC (<?xml version="1.0"?><body xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/" xfa:APIVersion="Acrobat:19.12.0" xfa:spec="2.0.2" ><p dir="ltr"><span dir="ltr" styweight:normal;font-style:normal">test2</span></p></body>)
/Rect [ 171.998 733.619 195.998 757.619 ]
/Subj (Sticky Note)
/Subtype /Text
/T (miculka)
/Type /Annot
>>
----------------------------------


Found annotation (152 0 R) of type: /Popup
----------------------------------
<<
/F 28
/Open false
/Parent 151 0 R
/Rect [ 595.32 643.619 799.32 757.619 ]
/Subtype /Popup
/Type /Annot
>>
----------------------------------


Found annotation (153 0 R) of type: /Highlight
----------------------------------
<<
/AP <<
/N 130 0 R
>>
/C [ 1 0.819611 0 ]
/CA 0.399994
/CreationDate (D:20190628095817+02'00')
/F 4
/M (D:20190628095817+02'00')
/NM (f7a566ea-a03a-49e0-bea4-0bff70babdbd)
/P 127 0 R
/Popup 154 0 R
/QuadPoints [ 88.1014 574.51 322.148 574.51 88.1014 563.47 322.148 563.47 ]
/Rect [ 85.1542 563.125 325.096 574.855 ]
/Subj (Highlight)
/Subtype /Highlight
/T (miculka)
/Type /Annot
>>
----------------------------------


Found annotation (154 0 R) of type: /Popup
----------------------------------
<<
/F 28
/Open false
/Parent 153 0 R
/Rect [ 595.32 460.51 799.32 574.51 ]
/Subtype /Popup
/Type /Annot
>>
----------------------------------


Found annotation (155 0 R) of type: /Highlight
----------------------------------
<<
/AP <<
/N 133 0 R
>>
/C [ 1 0.819611 0 ]
/CA 0.399994
/CreationDate (D:20190628095819+02'00')
/F 4
/M (D:20190628095819+02'00')
/NM (76eef8d3-acdb-4a2c-866e-83725949a862)
/P 127 0 R
/Popup 156 0 R
/QuadPoints [ 196.051 560.11 284.768 560.11 196.051 549.07 284.768 549.07 ]
/Rect [ 193.104 548.725 287.715 560.455 ]
/Subj (Highlight)
/Subtype /Highlight
/T (miculka)
/Type /Annot
>>
----------------------------------


Found annotation (156 0 R) of type: /Popup
----------------------------------
<<
/F 28
/Open false
/Parent 155 0 R
/Rect [ 595.32 446.11 799.32 560.11 ]
/Subtype /Popup
/Type /Annot
>>
----------------------------------


Found annotation (17 0 R) of type: /Text
----------------------------------
<<
/AP <<
/N 128 0 R
/R 129 0 R
>>
/C [ 1 0.819611 0 ]
/Contents (aaa)
/CreationDate (D:20190628095914+02'00')
/F 28
/M (D:20190628095919+02'00')
/NM (ffec35f8-b929-45b6-9b59-3fd7c33be79d)
/Name /Comment
/P 1 0 R
/Popup 18 0 R
/RC (<?xml version="1.0"?><body xmlns="http://www.w3.org/1999/xhtml" xmlns:xfa="http://www.xfa.org/schema/xfa-data/1.0/" xfa:APIVersion="Acrobat:19.12.0" xfa:spec="2.0.2" ><p dir="ltr"><span dir="ltr" styweight:normal;font-style:normal">aaa</span></p></body>)-\
/Rect [ 329.562 610.625 353.562 634.625 ]
/Subj (Sticky Note)
/Subtype /Text
/T (miculka)
/Type /Annot
>>
----------------------------------


Found annotation (18 0 R) of type: /Popup
----------------------------------
<<
/F 28
/Open false
/Parent 17 0 R
/Rect [ 595.32 520.625 799.32 634.625 ]
/Subtype /Popup
/Type /Annot
>>
----------------------------------
```

I hope this helps. Please let me know if you have any additional questions!

(P.S. My apologies for the late reply. I've been working on the [v1.0.0 release](https://github.com/Hopding/pdf-lib/issues/134) of `pdf-lib`.)

**Comment by fortrenitalia** [comment]
Hi @Hopding ,
thank you very much, it works perfectly. 

But I have one more question. How can I get page number for each annotation?

I tried to get annotations per page: 
 
 ```
//Load a PDF
const pdfDoc = PDFDocumentFactory.load(...);

const page1 = pdfDoc.getPages()[0]; 

// Get an array of all the objects in the PDF
const objects = Array.from(page1.index.index.entries());
 ```

But it always returns annotations from entire document (not only from provided page).

**Comment by Hopding** [comment]
@fortrenitalia Here's a script that prints out annotations per-page:
```js
const fs = require('fs');
const { PDFDocumentFactory } = require('pdf-lib');

// Load a PDF
const pdfDoc = PDFDocumentFactory.load(fs.readFileSync('./with_annots.pdf'));

// Print out the annotations per page
const pages = pdfDoc.getPages();
pages.forEach((page, idx) => {
  const pageAnnotRefs = pdfDoc.index.lookupMaybe(page.getMaybe('Annots'));
  if (pageAnnotRefs) {
    pageAnnotRefs.forEach(annotRef => {
      const annot = pdfDoc.index.lookup(annotRef);
      const subtype = annot.get('Subtype');
      console.log(
        `Found annotation (${annotRef}) of type ${subtype} on page ${idx}`,
      );
      console.log('----------------------------------');
      console.log(annot.toString());
      console.log('----------------------------------');
      console.log();
      console.log();
    });
  }
});
```

**Comment by fortrenitalia** [comment]
This is exactly what I need. Thank you very much

**Comment by Menencia** [comment]
The lib has been updated and this code doesn't work any longer :(

**Comment by Dohuythangglcs** [comment]
Hi @Hopding 

I have one more question. I can't get page number different first page.

```
const widget = pdf.ref({
    Type: 'Annot',
    Subtype: 'Widget',
    FT: 'Sig',
    Rect: [100, 200, 150, 250],
    V: signature,
    T: new String('Signature'),
    F: 4,
    P: pdf.page.dictionary, 
  });
  pdf.page.dictionary.data.Annots = [widget]; 
```

Thanks you!

**Comment by drthree** [comment]
I know this is rather late, but I just spent a horribly long time faffing about trying to infer what the docs do not tell you about how to do this.

I was trying to add some new Link annotations to an existing document (and remove, en passant, the existing links on the page which are not needed).

Here is a page:

     var pg = pdfDoc.getPages()[docpn-1]

Create 'links' as an array of page link annotations to be added to this page:
They are created by calling this function:

	const createPageLinkAnnotation = (pdfDoc, rect, pageRef, clr) => (
		pdfDoc.context.register( 
			pdfDoc.context.obj( { 
				Type:   'Annot', Subtype: 'Link', 
				Rect:   rect,			// Bounds of the link on the page 
				Border: [0, 0, 2],		// Give the link a 2-unit-wide border, with sharp corners 
				C:       ( clr || [0,0,1] ),	// Border color defaults to blue: rgb(0, 0, 1) 
				Dest:   [pageRef, 'XYZ', null, null, null],		// Page to be visited when the link is clicked 
			}), 
		) 
	); 

Having created the array of new links, replace the existing links on the page by
brute force (wholesale replacement of the annotations on the page), thus:

	const PNannots = PDFName.of('Annots'), PNsubtype = PDFName.of('Subtype');
	const annots = pg.node.get(PNannots), annots_array = annots  &&  annots.array  ||  [];
	const new_annots_array = [];
	annots_array.forEach( (ann) => {
		const subtype = annots.context.lookup(ann).dict.get(PNsubtype).decodeText();
		if (subtype != 'Link') new_annots_array.push(ann);	// Keep only non-Link annotations
	});
	new_annots_array.push(...links);	// append our new Link annotations to the array
	LOG("\nPage ", docpn);
	LOG("ADDING Links\n", {links});
	LOG("ADDING TO . . .\n", {annots_array});
	LOG("ADDING RESULT . . .\n", {new_annots_array});
	// Set the Annotations object for this page
	pg.node.set( PNannots, pg.doc.context.obj(new_annots_array) );

**Comment by amchconsult** [comment]
> @fortrenitalia Here's a script that prints out annotations per-page:
> 
> ```js
> const fs = require('fs');
> const { PDFDocumentFactory } = require('pdf-lib');
> 
> // Load a PDF
> const pdfDoc = PDFDocumentFactory.load(fs.readFileSync('./with_annots.pdf'));
> 
> // Print out the annotations per page
> const pages = pdfDoc.getPages();
> pages.forEach((page, idx) => {
>   const pageAnnotRefs = pdfDoc.index.lookupMaybe(page.getMaybe('Annots'));
>   if (pageAnnotRefs) {
>     pageAnnotRefs.forEach(annotRef => {
>       const annot = pdfDoc.index.lookup(annotRef);
>       const subtype = annot.get('Subtype');
>       console.log(
>         `Found annotation (${annotRef}) of type ${subtype} on page ${idx}`,
>       );
>       console.log('----------------------------------');
>       console.log(annot.toString());
>       console.log('----------------------------------');
>       console.log();
>       console.log();
>     });
>   }
> });
> ```
 pdfDoc.getPages() is an error as getPages() does not exists. what function can i use instead of?
thank you

**Comment by drthree** [comment]
I imagine that the file you are trying to open in 

>           const pdfDoc = PDFDocumentFactory.load(fs.readFileSync('./with_annots.pdf'));

does not exist.  Then  'pdfDoc' will be 'null' and you'l get "ReferenceError: pdfDoc is not defined"

**Comment by amchconsult** [comment]
I am using PDF-LIB v1.17.1

I did change the PDF file name. But it is giving an error of .load does not exists.

TypeError: Cannot read properties of undefined (reading 'load')

If I change 
const { PDFDocumentFactory } = require('pdf-lib');
for
const { PDFDocument } = require('pdf-lib');
It reads the file but gives error .getPages() does not exists.

**Comment by drthree** [comment]
Hmm, didn't read your post closely enough, sorry.

I don't have a PDFDocumentFactory member in my pdf-lib (1.17.1), just PDFDocument. Your original reference to PDFDOcumentFactory would have returned null/undefined and accessing the **_.load_** member on that reference would produce " .load does not exist ".

Note also that the **_.load_** method  [https://pdf-lib.js.org/docs/api/classes/pdfdocument#static-load](https://pdf-lib.js.org/docs/api/classes/pdfdocument#static-load) returns a **_Promise_** . . . it's not synchronous, so you need to **_await_**  or **_.then_** on it.

You cannot assume that the **_.load_** call would just return you a document as result - your will code run on and try to use the _**pdfDOoc**_ before it has been set from the **_.load_** call (which is queued in the background, waiting for a chance to do work).  So again, at the point you try to use it **_pdfDoc_** is null/undefined and hence calling the **_.getPages_**  method gets " .getPages() does not exist ".

Given the above, if @Hopding 's example code (of 3 years ago) used to work, it no longer does (things have moved on in the API).  You could try something like the following:


```
const { PDFNumber, PDFArray, PDFName, PDFDictionary, PDFDocument } = require('pdf-lib');; 
const pad = (len,val) => `${val}${Array(Math.max(len - val.length,0)).fill(" ").join("")}`;

function main (pdfDoc) {
	const PNannots = PDFName.of('Annots'), PNsubtype = PDFName.of('Subtype');
	const pages    = pdfDoc.getPages()  ||  [];
	pages.forEach( (page, idx) => {
		const annots    = page.node.get(PNannots)  ||  {};
		const annotRefs = annots.array  ||  [];
		annotRefs.forEach( annotRef => {
			const subtype = annots.context.lookup(annotRef).dict.get(PNsubtype).decodeText();
			console.log( `\nFound annotation (${annotRef.toString()}) of type ${subtype} on page ${idx+1}` );

			let dict = annots.context.lookup(annotRef).dict; 
			dict.forEach( (e,k) => {
				let s = pad(12,k.encodedName) + " = ";
				if (e instanceof PDFName) s += e.encodedName;
				else if (e instanceof PDFArray) {
					const av = [];
					e.array.forEach( (v,i) => { 
						if (v instanceof PDFNumber) av.push( v.stringValue );
						else av.push( v.toString() );
					});
					s += av.join(" , ");
				}
				else {
					s += JSON.stringify(e);
				}
				console.log(s);
			});

		});
	}); 
};

const args = process.argv.slice(2), fPath = args[0] || "missing-input-file.pdf"; 
PDFDocument.load( require('fs').readFileSync(fPath) )
.then( main )
.catch( console.error );

```

**Comment by StephenBentley-ATS** [comment]
Here is the code Hopding posted in 2019 updated to work with pdf-lib 1.17.1:

```javascript
const { PDFDocument, PDFDict, PDFName } = PDFLib;

const formPdfBytes = await fetch('with_annots.pdf').then(res => res.arrayBuffer());
const pdfDoc = await PDFDocument.load(formPdfBytes);

const annotationSubtypes = [
  PDFName.of('Text'),
  PDFName.of('Link'),
  PDFName.of('FreeText'),
  PDFName.of('Line'),
  PDFName.of('Square'),
  PDFName.of('Circle'),
  PDFName.of('Polygon'),
  PDFName.of('PolyLine'),
  PDFName.of('Highlight'),
  PDFName.of('Underline'),
  PDFName.of('Squiggly'),
  PDFName.of('StrikeOut'),
  PDFName.of('Stamp'),
  PDFName.of('Caret'),
  PDFName.of('Ink'),
  PDFName.of('Popup'),
  PDFName.of('FileAttachment'),
  PDFName.of('Sound'),
  PDFName.of('Movie'),
  PDFName.of('Widget'),
  PDFName.of('Screen'),
  PDFName.of('PrinterMark'),
  PDFName.of('TrapNet'),
  PDFName.of('Watermark'),
  PDFName.of('3D'),
  PDFName.of('Redact'),
];

const objects = Array.from(pdfDoc.context.enumerateIndirectObjects());
objects.forEach(([ref, object]) => {
  if (
    object instanceof PDFDict &&
    annotationSubtypes.includes(object.get(PDFName.of('Subtype')))
  ) {
    const subtype = object.get(PDFName.of('Subtype'));
    console.log(`Found annotation (${ref}) of type: ${subtype}`);
    console.log('----------------------------------');
    console.log(object.toString());
    console.log('----------------------------------');
    console.log();
    console.log();
  }
});
```
