### ISSUE TITLE
form.createTextField field size

### ISSUE THREAD

**Issue by keyboardbreaker** [Hopding/pdf-lib#791]
How do you make forms fields which are small like presented in this template, I want to create fields as big as the character name2 field or age field which are much smaller.
https://jsfiddle.net/Hopding/0mwfqkv6/3/

the textFields in the one punch man example are way too big:
https://jsfiddle.net/Hopding/bct7vngL/4/

is there a way of controlling their width and height? @Hopding

**Comment by Hopding** [comment]
The API docs are available here: https://pdf-lib.js.org/docs/api/classes/pdftextfield#addtopage.
