### ISSUE TITLE
Add Signature Field to existing PDF

### ISSUE THREAD

**Issue by alexhaegler** [Hopding/pdf-lib#794]
First of all: thank you for providing this awesome library! 

After hours of searching for it, it seems like there's only a "getSignature" function, but no createSignature function (unlike for other fields like createTextField etc.).

We tried to use AcroForms directly, but without notable success.

@Hopding 
Maybe I just don't understand the mechanism and there's already a solution fort that (I'm super happy for every suggestion btw. :) ), but this would be a great feature for this library.

Are there any plans on adding this?

Best regards
Alex

**Comment by Hopding** [comment]
> `pdf-lib` does not currently provide any specialized APIs for creating digital signatures or reading the contents of existing digital signatures.
> https://pdf-lib.js.org/docs/api/classes/pdfsignature

Support for digital signatures is on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by BMgec** [comment]
Hi there! Thanks for all your work.

Any news on this topic?

**Comment by Param-Harrison** [comment]
Is this currently possible?

**Comment by auggustus6** [comment]
Any news about this?
