### ISSUE TITLE
Barcode  font is removed from the pdf if edited by pdf-lib

### ISSUE THREAD

**Issue by herevrush** [Hopding/pdf-lib#795]
I have a pdf with barcode font code128. When I try to use pdf-lib in react, pdf field where font is code128, is changing to some other simple text font. 

Just wondering whether this font is removed from the pdf? is there any workaround for this.

**Comment by jgarcia24n** [comment]
Had the same issue, what I did was embedded the font using embedFont updated the fields that needed that font and then saved it, and then reloaded the new pdf from that save and editing any other fields that where different fonts.
`const code128Buffer = await fetch('url-of-font.ttf').then(res => res.arrayBuffer())`
`const code128Font = await pdfDoc.embedFont(code128Buffer)`
`let form = pdfDoc.getForm()`
Set the values for the fields that required this font
Update Field Apperance
`form.updateFieldAppearances(code128Font)`
`let fontPDFBuffer = await pdfDoc.save()`
Reload the pdf document
`pdfDoc = await PDFDocument.load(fontPDFBuffer)`
Continue modifying any other fields like normal.

**Comment by herevrush** [comment]
I have embedded the font and its generating the barcode. Barcode generated is not getting scanned.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
