### ISSUE TITLE
Missing Contents Error

### ISSUE THREAD

**Issue by doneumark** [Hopding/pdf-lib#796]
I'm getting a "**Can't embed page with missing Contents**" error, from the ``pdfDoc.save()`` command at the end of creating pdf document, using "pdf-lib".
I noticed that if I delete the line: ``this.doc.embedPdf(fileBuffer)``, previously written in the code - the error doesn't pop, but also of course, doesn't embed a PDF document I loaded.
Any ideas?

```
const fs = require('fs');
const { PDFDocument } = require('pdf-lib');

// ...

const pdfDoc = await PDFDocument.create();

// ...

const fileBuffer = fs.readFileSync(`${process.cwd()}/${pdfFileName}.pdf`);
const embeddedPdf = await pdfDoc.embedPdf(fileBuffer);
const page = this.addNewPage();
page.drawPage(pdfPage);

// ...

try {
    await pdf.doc.save();
} catch(err) {
   // thats where the error hits
}
```

while debugging the code, all of the variables (fileBuffer, embeddedPdf, page) seems legit.

**Comment by jywarren** [comment]
I found that writing anything onto the page solved this. It's not ideal, but you could draw a white rectangle and i think it would resolve at least for now.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.

**Comment by tomaskikutis** [comment]
I bumped into this one as well. I've worked around it by drawing a space `.drawText(' ')`.

**Comment by enoh-barbu** [comment]
@Hopding why opening a new bug? this issue was not solved.
