### ISSUE TITLE
Add image to Signature field

### ISSUE THREAD

**Issue by lokesh545** [Hopding/pdf-lib#797]
Thanks for the library, it's very helpful.

I have successfully added an image to the PDFTextField, but I'm unable to get it worked for PDFSignature. I tried the approach implemented in #700  and #718 but I feel it's not straightforward as mentioned. When I try to implement, need to add too many references from the original library. Could you please guide me with the right approach to add an image in the Signature field.

Thank you.

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
