### ISSUE TITLE
RE: drawPage for embedded PDF seems to lose hyperlink annotations

### ISSUE THREAD

**Issue by SvV-CWinJS** [Hopding/pdf-lib#798]
Hello,

First: Thank you for providing this great utility. My compliments!

As stated in issue #606: when drawing an embedded pdf, the hyperlink is lost.

Reproduced by:
Using Google Spreadsheet's formula HYPERLINK(). Save this as pdf. Embed and draw this pdf on a new pdf. Hyperlink is lost.
I copied the Javascript code for pdf-lib.js to Google Apps Script (GAS). Merging pages and so works in GAS, so I guess this setup should work as intended.

Code (GAS) used:
async function myFunction()
{
  var id1 = "10DoFgOYMywiZVscn9DwRGbcjEAPrqlNe";  
  const pdfDoc = await PDFDocument.create();  
  var pdf1Bytes = new Uint8Array(DriveApp.getFileById(id1).getBlob().getBytes());
  const [pdf1Embed] = await pdfDoc.embedPdf(pdf1Bytes);  
  var page = pdfDoc.addPage([297/25.4*72, 210/25.4*72]);  
  page.drawPage(pdf1Embed, {x: 148.5/25.4*72, y: 0});  
  const pdfBytes = await pdfDoc.save();  
  DriveApp.createFile(Utilities.newBlob(pdfBytes, 'application/pdf', "test draw.pdf"));
}

P.S.: This is my first post on Github, and English is not my mother tongue. Using "Reference in new issue" I don't see an option to add a file. If you need a file to test with, please provide instructions to give you the file.

**Comment by Hopding** [comment]
Congrats on your first GitHub post! And no worries about your English 🙂.

As stated in https://github.com/Hopding/pdf-lib/issues/606#issuecomment-694539149, I need example PDFs to provide any help with this. Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.

My apologies for the delayed response!
