### ISSUE TITLE
Manually checking Checkbox

### ISSUE THREAD

**Issue by jboxxx** [Hopding/pdf-lib#799]
I need to 'manually' check a checkbox, as an aside, I'm migrating from 0.6.0 to 1.6.0.

My PDF (attached) does not have AcroForm, I cannot call `pdfDoc.getForm()`, as this errors and throws `pdfDoc.getForm is not a function`.  I need to check the Checkbox by getting reference to them.  In 0.6.0, after getting references to all of the checkboxes, I am calling the below.  And this works.

`const pdfDoc = PDFDocumentFactory.load(fileData);`
`const pages = pdfDoc.getPages();`
`pages[0].index.lookup(checkBoxRefs[0]).set('V', PDFName.from('Yes'));`

Is there an equivalent for 1.6.0?  I've tried a few things, none seem to work.  This is what I have so far.

`const pdfDoc = await PDFDocument.load(fileData);`
`const pages = pdfDoc.getPages();`
`pages[0].doc.context.lookup(checkBoxRefs[0]).set(PDFName.of('V'), PDFName.of('Yes'));`

Ho hum.  This does not error, but also does not check my checkbox.

Thank you

[form_8949_ST.pdf](https://github.com/Hopding/pdf-lib/files/5993003/form_8949_ST.pdf)

**Comment by jboxxx** [comment]
This can be closed.  The issue was NOT that the 1.6.0 code above doesn't work, it does!

I was pulling down my newly created pdf from aws s3, and the pdf s3 was saving is NOT what I am passing to it.  If this is a common issue any ideas would be helpful as well.  Thanks

**Comment by Hopding** [comment]
Sounds like you were able to figure this out. If not, please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form.
