### ISSUE TITLE
Issue with Pdfs from Google docs

### ISSUE THREAD

**Issue by Gsuz** [Hopding/pdf-lib#80]
I'm getting an error splitting pdf's created by google docs. I'm only get these errors from these types of pdf's so far. The error message is: 

`_this.catalog.Pages.traverse is not a function
TypeError: _this.catalog.Pages.traverse is not a function
    at PDFDocument.getPages (PDFDocument.js:41)
    at pdf-cutter.component.ts:92`

Are the pdf's created by google docs any different than other pdf's in this regard?

My code is below.

```

  async cut(pageNumber: number) {
    this.buttonDisabled = true;

    const firstHalfPdfDoc = PDFDocumentFactory.create();
    const secondHalfPdfDoc = PDFDocumentFactory.create();

      await fetch(this.fileUrl).then(async function(response) {
        const buffer = response.arrayBuffer();

        await buffer.then(res => {
          const test = new Uint8Array(res);
          const firstDonorPdfDoc = PDFDocumentFactory.load(test);
          const Pages = firstDonorPdfDoc.getPages();
          
          for (let index = 0; index < pageNumber; index++) {
            const element = Pages[index];
            firstHalfPdfDoc.addPage(element);
          }
          for (let index = pageNumber; index < Pages.length; index++) {
            const element = Pages[index];
            secondHalfPdfDoc.addPage(element);
          }
        });
      });
      const firstPdfBytes = await PDFDocumentWriter.saveToBytes(firstHalfPdfDoc);
      this.uploadPdf(firstPdfBytes, firstpath)


    const secondPdfBytes = await PDFDocumentWriter.saveToBytes(secondHalfPdfDoc);
    this.uploadPdf(secondPdfBytes, secondpath)
```

**Comment by Hopding** [comment]
Hello @Gsuz. 

I just cut version [`0.6.1`](https://www.npmjs.com/package/pdf-lib/v/0.6.1) of `pdf-lib`. It contains a few bug fixes that were merged over the past few weeks. Please try this new version out and let me know if it fixes the error you are encountering.

You can install this prerelease with npm:
```
npm install pdf-lib@0.6.1
```
It's also available on unpkg:
* https://unpkg.com/pdf-lib@0.6.1/dist/pdf-lib.js
* https://unpkg.com/pdf-lib@0.6.1/dist/pdf-lib.min.js

**Comment by Gsuz** [comment]
Works like a charm. Thanks
