### ISSUE TITLE
Issue with printing flattened form with Adobe Acrobat

### ISSUE THREAD

**Issue by Hugo229234** [Hopding/pdf-lib#800]
Hi, I've been lost on this issue for a few days, hope you can help!

I fill in a a PDF file then flatten the file. I am able to view and print the PDF file when using the PDF viewer in the browser, but when I download the file and open it with Adobe Acrobat I get the error: "The document could not be printed". When I download the file but don't flatten the PDF file there is no issue. This issue seems to only be caused in Adobe Acrobat.

if flattened -> error
else -> no error

Any clue what could be causing this?

**Comment by weinspach** [comment]
Are you using v1.16.0? There is a fix or flattening in that version. So if not you should update pdf-lib and try again.

**Comment by Hugo229234** [comment]
Thank you I was using v1.14, this has fixed the issue.

**Comment by HodayaGruz** [comment]
not works on v1.17.1, downgrade to v1.16.0 and works again

**Comment by 700software** [comment]
> not works on v1.17.1, downgrade to v1.16.0 and works again

Same with us. cc @nomoney4me
