### ISSUE TITLE
Render an image from a PDF page

### ISSUE THREAD

**Issue by wildky** [Hopding/pdf-lib#803]
Hello, 

I'm trying to render an image generated from a page of a PDF. Is this possible with pdf-lib? If not, is it in scope of the library for a new feature or does anyone have recommendations for other approaches? Ideally I do not want to rely on additional software outside of node libraries. 

I also checked some other libraries. Some exist but they rely on other software like imagemagick which makes me think it is probably not an easy solution :(  

I looked through pdf-lib issues and didn't see much relevant either. I did find #83 but that is about extracting images from a PDF, while I want to render a page of a PDF to an image. 

Thanks, 
Ky

**Comment by soadzoor** [comment]
@wildky I suggest you take a look at mozilla's pdf.js. As far as I know that's the only opensource js library that is capable of this.
If you're unsure how to use it, feel free to check my [PDF-merger](https://github.com/soadzoor/PDF-merger), where I use both this (pdf-lib) for manipulating the pdf itself, and mozilla's pdf.js to render the little thumbnails.

You'll probably looking for the "getSnapShot" function within `PDFRenderer.ts`. It returns a canvas context, and you can call canvas.toDataURL() to generate a base64 png from that.

**Comment by wildky** [comment]
Thanks @soadzoor, this is definitely a helpful reference!
