### ISSUE TITLE
Result PDF file size is too big

### ISSUE THREAD

**Issue by davidvpe** [Hopding/pdf-lib#804]
Hello all,

I am working on an invoicing system for my company and I am using pdf-lib for this. I just finished everything today but I realized the result pdf's size is about 1 MB when the template pdf I am using is about 80 kb, 

So I gave this a try, I just did a PDFDocument.load(...) and then a doc.save() to a file, and I realized that the resulting pdf is about 400 kb without adding anything. That's almost 300 Kb of nothing, what is happening?

Maybe I'm missing a hidden option? I found that adding subset: true to the embedded fonts helps a LOT, but for this case, I'm not doing anything, just loading and saving.

I'd appreciate your comments or just a thumbs up if you have faced a similar issue.

**Comment by hcpgod** [comment]
I had the same problem when merge two pdf about 200k.
the rusult pdf's size is about 1.72M.

**Comment by festwirt** [comment]
Same problem. I want to merge two or more PDF files into one. 
`

      const files = ....incoming files....
      let pdfDok = await PDFDocument.create();
      for (const file of this.files) {
        const dokument = await PDFDocument.load(file)
        for (let i = 0; i < dokument.getPageCount(); i++) {
          const [page] = await pdfDok.copyPages(dokument, [i])
          pdfDok.addPage(page)
        }
      }
      const blob = new Blob([await pdfDok.save()], {type: 'application/pdf;charset=utf-8'});
      const FileSaver = require('file-saver');
      FileSaver.saveAs(blob, "merged.pdf");
    `
My test files are:
 

- File 1:  142 pages, size 1,5 MB
- File 2:  139 pages, size 1 MB

After the merge, i get a new file with 165 MB. 
Is this a BUG, or am i doing something wrong?

**Comment by Hopding** [comment]
https://github.com/Hopding/pdf-lib/pull/817 will likely solve this. If not, please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form and we can go from there.
