### ISSUE TITLE
MissingPDFHeaderError while loading PDFDocument from buffer

### ISSUE THREAD

**Issue by ravivarma-dot** [Hopding/pdf-lib#805]
Hi,

I'm trying to load Buffer from Azure Blob storage into a PDFDocument but getting MissingPDFHeaderError, see below image.

Is there a way to fix this issue or ignore PDF header while loading into PDFDocument ?

![image](https://user-images.githubusercontent.com/64154058/108777019-2df7e480-7531-11eb-8e03-f70fb84d4844.png)

![image](https://user-images.githubusercontent.com/64154058/108777400-c0988380-7531-11eb-8831-daddf0d53544.png)

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
