### ISSUE TITLE
How to set custom metadata or custom properties to PDF file

### ISSUE THREAD

**Issue by sebbmagnacerta** [Hopding/pdf-lib#807]
Hello

I was wondering if anyone has any idea how can I set custom metadata or custom properties to a PDF file with this library, any suggestions will be appreciated.

**Comment by RedSwift** [comment]
I had the same question but managed to find the answer by searching through the closed issues
https://github.com/Hopding/pdf-lib/issues/55 - shows a few ways to modify

Hope you already found your answer else here you go :)

**Comment by Hopding** [comment]
@RedSwift is spot on!

Also, improved support for this is on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
