### ISSUE TITLE
Text Align Center

### ISSUE THREAD

**Issue by chintankamani** [Hopding/pdf-lib#810]
Hi , I am able to center the text in the pdf,  but how do I center align the paragraph that is centered within a pdf, the docs is getting a bit tricky for me . Thanks

**Comment by musicjoeyoung** [comment]
I don't know if we're asking a similar question, chintankamani, but I'm trying to ensure my text input renders centered. I've referenced Rohan750's page on [how to make a certificate generator](https://rocoderes.com/create-a-certificate-generator-website-in-javascript/). 

What I'm trying to fix is that the inputted name always renders centered on the PDF. Currently that's not happening. It's only centered if the name has just the right number of letters (roughly 5-6 letters). I know my x-axis (below) determines where the inputted text is rendered, but I'm wondering if it's somewhere here I can dictate that it, instead, always prints center-aligned.
`  firstPage.drawText(name, {
    x: 300,
    y: 270,
    size: 58,
    font: SanChezFont,
    color: rgb(0, 0, 0),
  });
`
Any thoughts/advice are greatly appreciated!

**Comment by Hopding** [comment]
See https://github.com/Hopding/pdf-lib/issues/10#issuecomment-593108695.
