### ISSUE TITLE
Options for creating PDF to remove problems from file

### ISSUE THREAD

**Issue by peterzanetti** [Hopding/pdf-lib#813]
Hello,

I am working in a project where certain PDF files result in massive memory leaks when rendered. We've found that we can convert these files in Acrobat and produce "clean" copies that do not demonstrate these problems.

We are trying to do this on the server with pdf-lib, but so far the output files still have the same issues as the originals, so they are too "similar" to the original. What options exist for creating the new PDF so that I can ditch much of the original file's data and make a clean new copy?

Thanks,

**Comment by Hopding** [comment]
You can copy pages into a new document. That might help. I'd need more information to be of any more help with this. If you're still working on this, feel free to fill out one of the new issue templates:
* [Bug Report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml)
* [Proposal](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=proposal%2Cneeds-triage&template=proposal.yml)
