### ISSUE TITLE
During flatten, expected instance of PDFDict or PDFStream, but got instance of undefined

### ISSUE THREAD

**Issue by levex** [Hopding/pdf-lib#814]
Hello!

I'm encountering the following crash when trying to flatten a W4 from the IRS' website.

```
/home/ubuntu/src/x/node_modules/pdf-lib/cjs/core/errors.js:38
this = _super.call(this, msg) || this;
^
Error: Expected instance of PDFDict or PDFStream, but got instance of undefined
at new UnexpectedObjectTypeError (/home/ubuntu/src/x/node_modules/pdf-lib/cjs/core/errors.js:38:24)
at PDFContext.lookup (/home/ubuntu/src/x/node_modules/pdf-lib/cjs/core/PDFContext.js:93:15)
at PDFDict.lookup (/home/ubuntu/src/x/node_modules/pdf-lib/cjs/core/objects/PDFDict.js:64:48)
at PDFWidgetAnnotation.PDFAnnotation.getAppearances (/home/ubuntu/src/x/node_modules/pdf-lib/cjs/core/annotation/PDFAnnotation.js:89:20)
at PDFTextField.needsAppearancesUpdate (/home/ubuntu/src/x/node_modules/pdf-lib/cjs/api/form/PDFTextField.js:670:48)
at PDFForm.updateFieldAppearances (/home/ubuntu/src/x/node_modules/pdf-lib/cjs/api/form/PDFForm.js:534:23)
at PDFForm.flatten (/home/ubuntu/src/x/node_modules/pdf-lib/cjs/api/form/PDFForm.js:450:18)
at file:///home/ubuntu/src/x/fillOut.js:293:6
```

Using v1.16.0, any suggestions to workaround this issue?

My code adds a bunch of text (it doesn't use the Form API, just writes at given coordinates), and then flatten the PDF using PDFForm.flatten().

**Comment by levex** [comment]
The crash happens here:

```
const AP = this.ensureAP();
const N = AP.get(PDFName.of('N'));
```

Looks like one of the widget's AP dictionary doesn't have a normal appearance (`N`). According to PDF1.7 spec, that dictionary however is required. I wonder what's going on here.

**Comment by levex** [comment]
<img width="512" alt="CleanShot 2021-03-01 at 04 38 57@2x" src="https://user-images.githubusercontent.com/849140/109449168-0c728d80-7a48-11eb-8e23-3688a6a4659c.png">

From PDF1.7, appears that the AP dictionary itself is optional, so maybe the widget annotations corresponding to the PDF fields don't have an appearance?

**Comment by levex** [comment]
The following is a workaround that works for me, but it probably leaves in the widget annotations which may result in odd behavior from some PDF viewers. I tested Preview on macOS Big Sur and it looks good so far.

```
function workaroundFlatten(form) {
  const fields = form.getFields();
  for (let i = 0, lenFields = fields.length; i < lenFields; i++) {
    const field = fields[i];
    form.acroForm.removeField(field.acroField);
    form.doc.context.delete(field.ref);
  }
}
```

**Comment by NoNameProvided** [comment]
It also worked for me to "touch" all field via setting an empty text as value inside:

```js
const pdfDoc = await PDFDocument.load(pdfDocBytes);
const form = pdfDoc.getForm();
const fields = form.getFields();

fields.forEach(field => form.getTextField(field.getName()).setText(''));

// Form flatten works now as expected.
form.flatten();
```

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.

**Comment by satyajitnayk** [comment]
> It also worked for me to "touch" all field via setting an empty text as value inside:
> 
> ```js
> const pdfDoc = await PDFDocument.load(pdfDocBytes);
> const form = pdfDoc.getForm();
> const fields = form.getFields();
> 
> fields.forEach(field => form.getTextField(field.getName()).setText(''));
> 
> // Form flatten works now as expected.
> form.flatten();
> ```

This will work iff `field` is instance of `PDFTextField`!!

updated code:
```ts
fields.forEach((field) => {
      if (field instanceof PDFTextField) {
        pdfForm.getTextField(field.getName()).setText('');
      }
});
```

**Comment by YO-SC** [comment]
> > It also worked for me to "touch" all field via setting an empty text as value inside:
> > ```js
> > const pdfDoc = await PDFDocument.load(pdfDocBytes);
> > const form = pdfDoc.getForm();
> > const fields = form.getFields();
> > 
> > fields.forEach(field => form.getTextField(field.getName()).setText(''));
> > 
> > // Form flatten works now as expected.
> > form.flatten();
> > ```
> 
> This will work iff `field` is instance of `PDFTextField`!!
> 
> updated code:
> 
> ```ts
> fields.forEach((field) => {
>       if (field instanceof PDFTextField) {
>         pdfForm.getTextField(field.getName()).setText('');
>       }
> });
> ```

This did it for me, thx. It would be cool if the package itself could just insert empty strings on save to avoid this issue. Although for the eyes of some, I understand why that would not be desirable.
