### ISSUE TITLE
Encryption NEEDED!

### ISSUE THREAD

**Issue by randnix** [Hopding/pdf-lib#815]
I understand there's no support for encryption -- this is a requirement for us -- I did note that the documentation says do not use pdf-lib to work WITH encrypted documents, but what about being at least able to create an encrypted pdf -- even if that means you can't work with it later?   Is that possible?

**Comment by ShaheedHaque** [comment]
See #233 and #243. I'm really looking forward to #233.

**Comment by Hopding** [comment]
Nope. You can't produce or load encrypted documents right now. Support for both of these is on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
