### ISSUE TITLE
Set Text method removes border/boxes of text field

### ISSUE THREAD

**Issue by vbgsmanzoor** [Hopding/pdf-lib#819]
Set Text method removes border/boxes of the text field
![ssn-no-border](https://user-images.githubusercontent.com/75968426/110883115-d038fb80-8297-11eb-9b80-9045e7668f87.png)

**Comment by vbgsmanzoor** [comment]
If it is not an issue or duplicated please let me know the solution

**Comment by Nitesh-BB** [comment]
You can make transparent Texfield by setting  backgroundColor: undefined and borderColor: undefined at the time of adding textfield to pdf.

**Comment by vbgsmanzoor** [comment]
> You can make transparent Texfield by setting backgroundColor: undefined and borderColor: undefined at the time of adding textfield to pdf.

what I found these are the properties for creating a new field how can I apply these to the existing field?

**Comment by vbgsmanzoor** [comment]
@Hopding please look at the issue

**Comment by REdlstein** [comment]
@vbgsmanzoor   Did you find a way to apply properties to existing field?

**Comment by btecu** [comment]
You have to get the widgets of your field and set the property `BS` (border style).

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
