### ISSUE TITLE
Hide FormFields

### ISSUE THREAD

**Issue by Nitesh-BB** [Hopding/pdf-lib#821]
I added some formfields on PDf. Now I want to hide some Formfields using there name . Can I do this ? If there is any method please let me know. TIA

**Comment by Hopding** [comment]
The API docs are available here: https://pdf-lib.js.org/docs/api/.

**Comment by nux1701** [comment]
I have the exact same issue. I couldn't find a direct way to hide/show a field even using AcroForm API. Documentation isn't helping here.

Please reopen.
