### ISSUE TITLE
Is it possible to upload pdf first and use it as a template to create a fillable pdf?

### ISSUE THREAD

**Issue by sprklinginfo** [Hopding/pdf-lib#825]
Hi, My use case is that I want to allow a user to upload a pdf in the browser, then show the user back a fillable/interactive PDF so it can be modified, e.g. add a new field, draw images, etc. so the uploaded pdf serves as a template. Is it possible to use pdf-lib for this? Thanks.

**Comment by Hopding** [comment]
pdf-lib doesn't provide any sort of rendering or UI functionality.
