### ISSUE TITLE
Default font kerning is off?

### ISSUE THREAD

**Issue by honzasuchy** [Hopding/pdf-lib#826]
Hi, is there a way to enable/get to work default font kerning? As you can see in a screenshot below spacing between T and O is bit off (blue one is rendered via pdf-lib). It seems like pdf-lib doesn't calculate glyph width with bbox in mind (not sure, I'm not really a type person). I found out that correct way to calculate width of character in fontkit would be `glyph.advanceWidth - glyph.bbox.width`? 
<img width="340" alt="Screenshot 2021-03-15 at 21 07 33" src="https://user-images.githubusercontent.com/13457548/111218132-a0ab2b80-85d6-11eb-9679-c9237d4e45e1.png">

**Comment by Hopding** [comment]
I need more information to help with this. Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble.

**Comment by simonbuchan** [comment]
Indeed, this looks like a classic example of not applying [kerning](https://en.m.wikipedia.org/wiki/Kerning)  information from the font. You probably don't want to implement a OTF / TTF runtime though.
