### ISSUE TITLE
Remove or replace text in pdf file 

### ISSUE THREAD

**Issue by duchiep123** [Hopding/pdf-lib#827]
Hi everyone, my case is when the users upload pdf files (in particular CV files), I will remove some sensitive information such as phone number or email, maybe I replace that information into ****** and then send the user a pdf file that has deleted such information. 
I tried placing the image to hide the information, but the user can still copy the information.
Is there a way to do it?
Give me some keyword plz 
Thanks a lot
I'm using Node js v12.18.3

**Comment by MallRoy** [comment]
I am also facing the same issue. @Hopding is there any way to fix this?

**Comment by MamoMC** [comment]
Same problem to.
A solution would be more tan welcome.
TIA!

**Comment by Malik056** [comment]
Same Issue here

**Comment by Malik056** [comment]
Any Solution yet? any work around?

**Comment by yotavm** [comment]
?

**Comment by slavikme** [comment]
+1

**Comment by jordyortega** [comment]
++

**Comment by trants** [comment]
+1

**Comment by Hopding** [comment]
https://github.com/Hopding/pdf-lib#limitations

**Comment by jjason685** [comment]
posted a potential solution here:

https://github.com/Hopding/pdf-lib/issues/564#issuecomment-1786082117

**Comment by rafahlobo** [comment]
+1
