### ISSUE TITLE
Is there a way to implement default value for PDFTextField?

### ISSUE THREAD

**Issue by vijay-qburst** [Hopding/pdf-lib#829]
I am trying to implement something like `setText`, but to set the default value for a text field. Something like `setDefaultValue`. Is there a way to implement this? 

For context, I need to set the default value for text fields. The default value will be available for backend systems that try to fill in the user values. But when you print the pdf these values will not be printed and the user is free to write on the printed pdf.

**Comment by Hopding** [comment]
I don't think this is possible with any tool/library. Are you able to achieve something similar with Acrobat or other PDF tools/libraries? If so, let me know and I can look into this further.
