### ISSUE TITLE
Merging Big Pdfs Using Stream

### ISSUE THREAD

**Issue by aakashgarg19** [Hopding/pdf-lib#831]
I saw issues being raised regarding this around 1 year back in the list. But wanted to check is it possible to use pdf-lib for merging pdf documents without using too much heap via IO streaming somehow? As currently we first need to load the buffer from drive then pass it to pdf-lib for loading the document and then copy and add pages. Which increases the memory utilization.

**Comment by Hopding** [comment]
Not yet, but it's on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
