### ISSUE TITLE
Get coordinates/position of button form field.

### ISSUE THREAD

**Issue by ArifNawaz36** [Hopding/pdf-lib#832]
I am using pdf-lib in our NodeJs project. We are modifying our existing pdfs to place an image on button form field. I want to get the exact  coordinates of the button field. 

Can you please help me with this.
Thanks.

**Comment by MorganWaya** [comment]
Up! Same question here!

**Comment by ArifNawaz36** [comment]
> Up! Same question here!

**Comment by ArifNawaz36** [comment]
@MorganWaya I then did it manually by using acroField of PDF lib. It required some research but it eventually resulted as desired.

**Comment by bjbk** [comment]
If placing an image on a button, not sure if this helps you: https://pdf-lib.js.org/docs/api/classes/pdfbutton#setimage

As long as you know the name of the button.

https://github.com/Hopding/pdf-lib/issues/602#issuecomment-693010472

Maybe that helps?

**Comment by Hopding** [comment]
@ArifNawaz36 seems to have the right idea. It can be done, but you'll have to use the lower-level widgets API. You can find some examples in other issues.
