### ISSUE TITLE
Moving page from one document to another

### ISSUE THREAD

**Issue by aakashgarg19** [Hopding/pdf-lib#835]
Can we simply move page from one document to another without copying. As currently it gives Page is from foreign document error. Is there a way to simply move a page from one document to another at a specific index without copying? As i don't want original document to be maintained?

**Comment by Hopding** [comment]
Yes. I've provided examples in several other issues showing how to do this. If it's not working for you, please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form.

**Comment by aakashgarg19** [comment]
@Hopding can you please point me where you have given an example?
