### ISSUE TITLE
justified text

### ISSUE THREAD

**Issue by tasarsu** [Hopding/pdf-lib#836]
is it possible to make paragraph justified? I mean can text be aligned with both margins via word spacing or letter spacing?

regards.

**Comment by Hopding** [comment]
Yes, but you'd have to do it all manually. The API doesn't provide an option to handle it automatically.

**Comment by anisharya16** [comment]
> Yes, but you'd have to do it all manually. The API doesn't provide an option to handle it automatically.

I also want justification of text in my pdf, how to achieve it?
