### ISSUE TITLE
Why isn't PDF-LIB hosted at deno.land?

### ISSUE THREAD

**Issue by webdev3301** [Hopding/pdf-lib#837]
Do you believe your library would get a lot more exposure if it was the only PDF library hosted at deno.land? Because it would be the only PDF library available to everyone looking for extensions.

**Comment by Hopding** [comment]
`pdf-lib` relies on https://www.skypack.dev to convert its compiled source into something that Deno can work with. In particular, the import syntax produced by the build is only compatible with Node (or common JS loaders). At least, that was the state of things last I checked. That being said, it would be cool to be listed on deno.land, so I've added it to the roadmap: https://github.com/Hopding/pdf-lib/discussions/998. Thanks for the suggestion!
