### ISSUE TITLE
Create new Layer/Version or watermark

### ISSUE THREAD

**Issue by espositovitor** [Hopding/pdf-lib#839]
It's possible to create a new version from PDF or a new Layer? My file have signatures and if I change will break.

**Comment by Hopding** [comment]
Don't quite understand what you're trying to do there.

Please create a Discussion or fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
