### ISSUE TITLE
Problem with PDFDocumentFactory.load It's getting stuck for a document 

### ISSUE THREAD

**Issue by ankitchoudary** [Hopding/pdf-lib#84]
PDFDocumentFactory.load function is getting stuck for Uint8Array of a document. 
I have latest pdf-lib 0.6.1. It's working for other documents , but it's failing for this one.

**Comment by Hopding** [comment]
@ankitchoudary I need more information in order to debug this. Can you please provide both the error message and stack trace you are getting? Also, are you able to share the document you're having trouble with?

**Comment by Hopding** [comment]
@ankitchoudary I'm going to close this for now. But please feel free to reopen if you are still having trouble!

**Comment by CamiloTDex** [comment]
@Hopding  I have the same issue, its stucked forever, i'll share the pdf document

My code: this.pdf = PDFDocumentFactory.load(buf);

buf is the binary for the attached file:
[SE630ac.pdf](https://github.com/Hopding/pdf-lib/files/3527426/SE630ac.pdf)

**Comment by Hopding** [comment]
Hello @CamiloTDex! Based on the code snippet you shared, it looks like you are using an older version of pdf-lib. Please give the latest version a try (`1.0.1`) and let me know if you're still having the issue.
