### ISSUE TITLE
How to add OCR feature to pdf-lib? 

### ISSUE THREAD

**Issue by Sharcoux** [Hopding/pdf-lib#841]
Hi,

I'd like to try and add an OCR feature to pdf lib (might be as a PR or as a spare lib).

I think that I have a clear vision of how to use Tesseract to read and locate the texts from the input pdf. The question is "then, what ?". How can I write the text so that it is interpreted as a searchable image?

Using drawText won't work because it will overlap with the original image.

**Comment by MarcelloTheArcane** [comment]
You could draw a filled rectangle, then drawText over the top

**Comment by Sharcoux** [comment]
I thought that there was a kind of special layer for that, but maybe the trick is just to write the text with a transparent color. This way, it will appear only on selection.

**Comment by Hopding** [comment]
Hello @Sharcoux! Appreciate your interest in contributing to `pdf-lib`. OCR is outside the scope of this library, but you could certainly create a separate library. I'm sure others would find that capability useful.

**Comment by Sharcoux** [comment]
Yes, I solved it on my side, but only from images for now so, anyway, that won't be compatible with pdf-lib for now.

**Comment by nk-gears** [comment]
@Sharcoux , I am trying to make a Image Scanned PDF to Searchable PDF. I have the Bounding Geometry Info about the text and position. Could you please shed some lights on how to make a PDF searchable with this Geometry Info using NodeJS/Lib

**Comment by Sharcoux** [comment]
Just draw the text transparent with PDF-lib, over the image ;)
