### ISSUE TITLE
Viewer preferences have no effect (toolbars shown in Firefox)

### ISSUE THREAD

**Issue by kheber92** [Hopding/pdf-lib#844]
I'm trying to create a pdf viewer where all toolbars are hidden and just the pdf shows up.
pdf-lib does this on their website (https://pdf-lib.js.org/viewer/?url=/assets/create_document.pdf) so I guess it should be possible with this library.

I have set the following preferences:
```
const viewerPrefs = pdfDoc.catalog.getOrCreateViewerPreferences();
    viewerPrefs.setHideToolbar(true);
    viewerPrefs.setHideMenubar(true);
    viewerPrefs.setHideWindowUI(true);
```

Although, all default browser toolbars (especially in Firefox) are displayed.
When I log the preferences (e.g. `viewerPrefs.getHideToolbar()`), I see that they are set correctly but the toolbars are still there.

How did pdf-lib setup their pdf-viewer on their website?
I'm rendering the pdf in an iframe.

Thank you in advance!

**Comment by MorganWaya** [comment]
Up! Same question here!

**Comment by Hopding** [comment]
Not all viewers respect the viewer preferences. Note the word **"should"** is used to describe the behavior in the docs: https://pdf-lib.js.org/docs/api/classes/viewerpreferences#sethidetoolbar. I think Acrobat respects them. Foxit might as well.
