### ISSUE TITLE
Is there a way to flatten a PDF of images

### ISSUE THREAD

**Issue by jumanahalasadi** [Hopding/pdf-lib#847]
The requirement is to create a PDF of images, created from canvas, however we do not want them to be saved as embedded images in the pdf,
we want the entire pdf to be completely flat.

Thank you!

**Comment by Hopding** [comment]
Not sure what you're trying to do here. What do you mean by a "completely flat" PDF? What alternative could there be to embedding the images?

**Comment by xxorax** [comment]
I guess I have the same requirement.

With a PDF built with multiple images, it's easy to extract each of them. This is an issue for "hand" signed PDF for example : we don't want to be able to extract the signature (which is stored as an image).

But the only way seems to convert the PDF to an image, and then convert it back to PDF... or at least only the pages that we want to "flatten".

Thanks
