### ISSUE TITLE
Is there a way to add custom properties to PDF

### ISSUE THREAD

**Issue by lhgomes** [Hopding/pdf-lib#848]
I have used the solution to add Author and Creator to the PDF, but now I need to add a custom property (or a custom metadata) to the document.

Can I do this with this solution ?

I have tried to do this:

```
const pdfDoc = await PDFDocument.load(pdfBytes, { 
    updateMetadata: true 
});

pdfDoc.setAuthor("My name");
pdfDoc.setCreator("My Company");

const key = PDFName.of('customName');
pdfDoc.context.obj({}).set(key, PDFHexString.fromText("customValue"));

return pdfDoc.saveAsBase64();
```

But only the Author and Creator were included to the document.

Thank you and congratulations for the amazing job!

**Comment by lhgomes** [comment]
I also checked the [#55](https://github.com/Hopding/pdf-lib/issues/55), but looks like this doesn´t work with the current version.

**Comment by BoLaMN** [comment]
try 

```
const key = PDFName.of('customName');
pdfDoc.getInfoDict().set(key, PDFString.of('' + value));
```

**Comment by lhgomes** [comment]
> const key = PDFName.of('customName');
> pdfDoc.getInfoDict().set(key, PDFString.of('' + value));

Thank you @BoLaMN, but with this approach I got the following issue:
`Property 'getInfoDict' is private and only accessible within class 'PDFDocument'.`

I suppose I have two options here: 

1. Change the PDFDocument to make getInfoDict public
2. Create a method into PDFDocument to expose a new function to set the custom metadata

Any other suggestions?

Thank you.

**Comment by BoLaMN** [comment]
try 

```
    let info = pdfDoc.context.lookup(pdfDoc.context.trailerInfo.Info);
    
    if (!(info instanceof PDFDict)) {
      info = pdfDoc.context.obj({})
      pdfDoc.context.trailerInfo.Info = pdfDoc.context.register(info);
    }

    const key = PDFName.of('customName');
    info.set(key, PDFString.of('' + value));
```
