### ISSUE TITLE
Retain annotations when embedding pages

### ISSUE THREAD

**Issue by juanludlf** [Hopding/pdf-lib#849]
Annotations are retained by using `copyPages` but they are not retained with the `embedPage` method.

Is there any way to retain annotations when embedding pages?

**Comment by acoyfellow** [comment]
I ran into the same issue. I also needed a way to add more annotations on the fly. Here was my solution:
```js
const existingAnnots = page.node.Annots().array;
const annots = [ ...existingAnnots ];
/* create new annots, push into array */
await page.node.set(PDFName.of('Annots'), pdfDoc.context.obj(annots));
```

**Comment by juanludlf** [comment]
Hi @acoyfellow,
Thanks for the solution. The point is we need to scale the embedded page (and all included objects, like annotations) before call `drawPage`. 
If we copy annotations after page has been scaled, how can we scale them according to the new dimensions of the page?

**Comment by Hopding** [comment]
https://pdf-lib.js.org/docs/api/classes/pdfpage#drawpage can't (and won't) preserve annotations. You should use https://pdf-lib.js.org/docs/api/classes/pdfdocument#addpage instead.

**Comment by juanludlf** [comment]
Hi @Hopding,
But [addPage](https://pdf-lib.js.org/docs/api/classes/pdfdocument#addpage) doest not accept an [PDFEmbeddedPage](https://pdf-lib.js.org/docs/api/classes/pdfembeddedpage). What if I need to scale the page before adding it to the document?
Thank you

**Comment by juanludlf** [comment]
I've just seen a PR in progress that will solve this problem: https://github.com/Hopding/pdf-lib/pull/991

**Comment by wildhart** [comment]
I don't think PR #991 completely solves the original problem: How to embed PDF at **given cooridinates and scale** on a page **and retain annotations**.  This requirement comes from needing to embed an external pdf into my document, but I need my own border around the embeded pages, and my own header, footer and page numbers as the embeded pdf is part of a larger document.

Here's the problems:
* Using `page.drawPage()` only takes an `embeddedPage`, not another `page` instance, and as per this original bug report, embedded pages do not retain their annotations.
* Using `doc.addPage()` retains annotations.  Then it's possible to use `page.scaleContent(); page.scaleAnnotations()` and then `page.translateContent()` but there is no `page.translateAnnotations()` method, so it's not possible to scale and translate the embedded pdf annotations into the center of my own page.

@Hopding can you suggest a work-around for this?

**Comment by CharlyPoppins** [comment]
hi @wildhart , have you found a workaround ?

**Comment by wildhart** [comment]
I did, but it's very complicated!  Since trying to draw the page within my own page doesn't scale and translate the annotations, instead, I added the full original page into my document, then scale the **entire page** down within itself and changed the media boxes, etc, and then drew my border and header/footer around it.

It was a long time ago now, but here's some of my code:

```ts
// `this` = my own PDF helper class in which this code is contained:
const pages = await this.doc.copyPages(srcDoc, indices);
pages.forEach(p => this.doc.addPage(p));

if (this.frameEmbbededPages) {
	for (const page of pages) {
		let size = page.getSize();
		const rotated = (page.getRotation().angle % 180) === 90;
		const rotated90 = page.getRotation().angle == 90; // PDFCreator does this - most other landscape pages are 270
		if (rotated) {
			size = {width: size.height, height: size.width};
		}
		const landscape = size.width > size.height;

		const targetSize = {
			width: PageSizes.A4[landscape ? 1 : 0],
			height: PageSizes.A4[landscape ? 0 : 1],
		};

		// calculate the maximum width and height available for the embedded page
		this.page = page;
		this.pageSize = this.page.getSize();
		...
		const scale = Math.min(1, maxWidth / size.width, maxHeight / size.height);

		page._embedScale = scale;
		let left = (targetSize.width - size.width * scale) / 2;
		let bottom = this.yMargin + margin + (maxHeight - size.height * scale) / 2;
		if (rotated) {
			const temp = left;
			left = bottom;
			bottom = temp;
			if (rotated90) { // PDFCreator does this - most other landscape pages are 270
				left = targetSize.height - left - size.height * scale;
			}
		}

		page.scaleContent(scale, scale);
		page.scaleAnnotations(scale, scale);

		const currentBox = page.getMediaBox();
		left -= currentBox.x * scale;
		bottom -= currentBox.y * scale;

		[page.setMediaBox, page.setArtBox, page.setBleedBox, page.setCropBox, page.setTrimBox].forEach(fn => {
			fn.call(page, -left, -bottom, rotated ? targetSize.height : targetSize.width, rotated ? targetSize.width : targetSize.height);
		});
		page._embedXOrigin = - left / scale;
		page._embedYOrigin = - bottom / scale;
		this.yPos = this.getPageHeightWithRotationAndScale() - this.yMargin / scale;

		// draw a border around the embedded page
		page.drawRectangle({
			x: -margin / scale + currentBox.x,
			y: -margin / scale + currentBox.y,
			width: this.pageSize.width + 2 * margin / scale,
			height: this.pageSize.height + 2 * margin / scale,
			borderWidth: 0.01,
			opacity: 0,
		});
		this.pageSize = this.page.getSize();

		// add the header logo and heading
		if (this.opts.headers) {
			this.addHeaderImg();
		}
		await this.addHeading(heading, headings.h2);

		// add the footer
		const footer = `Attachment: ${caption} - page ${++count} of ${pages.length}`;
		await this.setFont('normal', 'normal')
		this.setFontSize(10); // scale is included within
		page.drawText(footer, this.addRotation({
			x: this.xMargin / scale,
			y: this.oneLineHeight + this.baseLineOffset,
			size: this.fontSize,
			font: this.font,
		}));
	}
}

...

addRotation(options: PDFPageDrawTextOptions) {
	if (!this.page) {
		return options;
	}
	const angle = this.page?.getRotation().angle;
	if (!angle) {
		options.x! += this.page!._embedXOrigin || 0;
		options.y! += this.page!._embedYOrigin || 0;
		return options;
	}
	const x = angle == 90 ? PageSizes.A4[0] / this.page._embedScale! - options.y! : options.y!;
	const y = angle == 90 ? options.x! : PageSizes.A4[1] / this.page._embedScale! - options.x!;
	const rotated = {
		...options,
		x: this.page._embedXOrigin! + x,
		y: this.page._embedYOrigin! + y,
		rotate: degrees(angle),
	}
	return rotated;
}

```

I think the important bits are:
```ts
		page.scaleContent(scale, scale);
		page.scaleAnnotations(scale, scale);

		[page.setMediaBox, page.setArtBox, page.setBleedBox, page.setCropBox, page.setTrimBox].forEach(fn => {
			fn.call(page, -left, -bottom, rotated ? targetSize.height : targetSize.width, rotated ? targetSize.width : targetSize.height);
		});
		page._embedXOrigin = - left / scale;
		page._embedYOrigin = - bottom / scale;
		page._embedScale = scale;
```

This transforms the scale of the page (and translates and rotates the page origin).  Then the `page._embedXOrigin`, etc, properties are used within my `page.drawText()`, `page.drawRectangle()`, etc, functions to draw the text, rectangle and header logo bigger than they should be (and rotated/translated), so when the scale of the page it taken into account they are consistent with my other A4 pages.

I hope that helps - if you can make any sense of it!

**Comment by CharlyPoppins** [comment]
Thanks @wildhart, I'll give it a try with your approach.
