### ISSUE TITLE
Circles and ellipses are not visible on some PDF readers

### ISSUE THREAD

**Issue by mlecoq** [Hopding/pdf-lib#85]
Hi, I have modified a PDF with pdf-lib. My modifications are visible in some tools (firefox through pdf.js for example), but not in others (chrome)

There is an example here : 
https://s3.amazonaws.com/mle-sandbox/archireport-sample.pdf

it does not depend on the OS since the issue has been reproduced on macOS, linux and windows

**Comment by mlecoq** [comment]
I have reproduced the issue with the document creation example of the lib. 

There is a green and purple ellipse at the bottom of the first page. When I open the document with Chrome, the ellipse is not displayed

**Comment by Hopding** [comment]
@mlecoq Can you please share the code for the content stream you are adding?

**Comment by mlecoq** [comment]
Sure, 

`
 const textStream = pdfDoc.register(
                    pdfDoc.createContentStream(
                        drawText(fontFont.encodeText(name), {
                            x,
                            y,
                            rotateDegrees: rotation,
                            size: currentTextSize,
                            font: 'pdfFont',
                            colorRgb: convertRgbColor([255, 255, 255]) //rgb(255,255, 255)
                        })
                    )
                );

                const whiteDisk = pdfDoc.register(
                    pdfDoc.createContentStream(
                        drawCircle({
                            x,
                            y,
                            size: circleSize + 3,
                            colorRgb: convertRgbColor([255, 255, 255]) //rgb(255,255,255)
                        })
                    )
                );

                const cycle = pdfDoc.register(
                    pdfDoc.createContentStream(
                        drawCircle({
                            x,
                            y,
                            size: circleSize + 1.5,
                            colorRgb: convertRgbColor([66, 71, 73]) //rgb(66, 71, 73)
                        })
                    )
                );

                const colored = pdfDoc.register(
                    pdfDoc.createContentStream(
                        drawCircle({
                            x,
                            y,
                            size: circleSize,
                            colorRgb: color //rgb(66, 71, 73)
                        })
                    )
                );


  page.addContentStreams(whiteDisk, cycle, colored, textStream);
`

But since I have reproduced the issue with your example : https://github.com/Hopding/pdf-lib/tree/master/examples/document_creation/node

All ellipses are not displayed on chrome (and other tools)

**Comment by Hopding** [comment]
@mlecoq I've been looking into the cause of this. The ellipses do display correctly on some readers (including Mac's Preview). I'm not sure why Chrome and Acrobat do not display them correctly. As far as I can tell, the `drawEllipse` function is compliant with the PDF spec.

I've been experimenting with other approaches, and have found one that does appear to work correctly across all PDF readers. However, I can't replace `drawEllipse` with it yet, because this approach doesn't support the `rotation` and `skewAngles` options. So I'll just share it here and you can just drop it in your codebase and use it, until I can fully reimplement `drawEllipse`:

```js
const {
  pushGraphicsState,
  moveTo,
  appendBezierCurve,
  popGraphicsState,
  fillAndStroke,
  fill,
  stroke,
  closePath,
  fillingRgbColor,
  strokingRgbColor,
  lineWidth,
} = require('pdf-lib');

const KAPPA = 4.0 * ((Math.sqrt(2) - 1.0) / 3.0);

const customDrawEllipsePath = ({
  x = 0,
  y = 0,
  xScale = 100,
  yScale = 100,
}) => {
  x -= xScale;
  y -= yScale;

  const ox = xScale * KAPPA;
  const oy = yScale * KAPPA;
  const xe = x + xScale * 2;
  const ye = y + yScale * 2;
  const xm = x + xScale;
  const ym = y + yScale;

  return [
    pushGraphicsState(),
    moveTo(x, ym),
    appendBezierCurve(x, ym - oy, xm - ox, y, xm, y),
    appendBezierCurve(xm + ox, y, xe, ym - oy, xe, ym),
    appendBezierCurve(xe, ym + oy, xm + ox, ye, xm, ye),
    appendBezierCurve(xm - ox, ye, x, ym + oy, x, ym),
    popGraphicsState(),
  ];
};

const customDrawEllipse = (options) => [
  pushGraphicsState(),
  fillingRgbColor(
    options.colorRgb ? options.colorRgb[0] : 0,
    options.colorRgb ? options.colorRgb[1] : 0,
    options.colorRgb ? options.colorRgb[2] : 0,
  ),
  strokingRgbColor(
    options.borderColorRgb ? options.borderColorRgb[0] : 0,
    options.borderColorRgb ? options.borderColorRgb[1] : 0,
    options.borderColorRgb ? options.borderColorRgb[2] : 0,
  ),
  lineWidth(options.borderWidth || 15),
  ...customDrawEllipsePath({
    x: options.x || 0,
    y: options.y || 0,
    xScale: options.xScale || 100,
    yScale: options.yScale || 100,
  }),
  options.colorRgb && options.borderColorRgb ? fillAndStroke()
  : options.colorRgb                         ? fill()
  : options.borderColorRgb                   ? stroke() 
  : closePath(),
  popGraphicsState(),
];
```

Please let me know if this works for you, or if you have any other questions!

**Comment by mlecoq** [comment]
Great ! Thank you, I will try it soon. We were using hummus and are very happy with your lib ;)

**Comment by mlecoq** [comment]
Close this issue since we have a valid workaround
