### ISSUE TITLE
Acroform - Text Field - get font type/size?

### ISSUE THREAD

**Issue by earlallin** [Hopding/pdf-lib#850]
I cannot find a way to retrieve the font type and size of a pdf Form field.. is this possible?

**Comment by Hopding** [comment]
You'll have to check the internal code for text fields and widgets. It can be done, there just aren't high level, well documented APIs built for it.

**Comment by jketcham** [comment]
I just had this question. In case it helps anyone: for _most_ (hopefully) TextFields, you should be able to call `field.acroField.getDefaultAppearance()`, method defined here on `PDFAcroField`: https://github.com/Hopding/pdf-lib/blob/2f36ae324b0e98dec9a2262f12c28a68c37cb41a/src/core/acroform/PDFAcroField.ts#L97-L105

Should return something like:
```
0 g
/Helvetica 9 Tf
```
Format of that last line being: `/{font-name} {font-size} Tf`

More info on the `Tf` 'operation' [https://stackoverflow.com/questions/58847233/pdf-text-object-what-font-and-decoding-should-be-used-if-there-is-no-tf-opera](here).
