### ISSUE TITLE
Fetch out PDF from Base64 String.

### ISSUE THREAD

**Issue by Geniewave** [Hopding/pdf-lib#852]
Hello guys I'm using the PDF-LIB JS right now to add form documents to a PDF, I'm starting to work with the project and I need the document to be loaded through Base64, I've been trying to find documentation on how to load a Base64String in my create form() function, but wasn't lucky at all. 

I am not a native Javascript developer, so I'm still learning around, I've managed to make the Save to Base64 work flawlessly and create form over my current document, but I need to push my PDF to get modified as Base64 for my final implementation.

Thank you

-Best

**Comment by bjaraujo83** [comment]
const dataUri = 'data:application/pdf;base64,JVBERi0xLjcKJYGBgYEKCjUgMCBvYmoKPDwKL0ZpbHRlciAvRmxh....'
let pdfDoc = await PDFDocument.load(dataUri)

const base64= 'JVBERi0xLjcKJYGBgYEKCjUgMCBvYmoKPDwKL0ZpbHRlciAvRmxh....'
let pdfDoc = await PDFDocument.load(base64)

**Comment by Geniewave** [comment]
Thanks a lot for you, can't believe it was that simple, the first one did the trick! Cheers !
