### ISSUE TITLE
[Feature Request] Variable Fonts Support

### ISSUE THREAD

**Issue by bjaraujo83** [Hopding/pdf-lib#853]
I tried to use the Bold and Condensed styles of the Bahnschrift font without success as the variations are in a single file.

I found this demonstration of variable font with fontkit. 
[https://github.com/devongovett/fontkit-demo](https://github.com/devongovett/fontkit-demo)

**Comment by Hopding** [comment]
Closing this for now. Added it to the roadmap in https://github.com/Hopding/pdf-lib/discussions/998.

**Comment by Re-n-Im** [comment]
Is this feature request already implemented in the project, because as I saw in the roadmap here:

> Closing this for now. Added it to the roadmap in [#998](https://github.com/Hopding/pdf-lib/discussions/998).

it is (as almost all the records in the list are) marked as completed?

I tried this (with different values for wght and wdth) without success:

```js
const url = location.origin + '/bahnschrift.ttf'
const fontBytes = await fetch(url).then(res => res.arrayBuffer())

// Create a new PDFDocument
const pdfDoc = await PDFDocument.create()

// Register the `fontkit` instance
pdfDoc.registerFontkit(fontkit)

var font = fontkit.create(fontBytes).getVariation({
	wght: 700,
	wdth: 75
});

// Embed our custom font in the document
const customFont = await pdfDoc.embedFont(font.stream.buffer)

// Add a blank page to the document
const page = pdfDoc.addPage()

// Create a string of text and measure its width and height in our custom font
const text = 'Test string'
const textSize = 17
const textWidth = customFont.widthOfTextAtSize(text, textSize)
const textHeight = customFont.heightAtSize(textSize)

// Draw the string of text on the page
page.drawText(text, {
	x: 40,
	y: 450,
	size: textSize,
	font: customFont,
	color: rgb(0, 0.53, 0.71),
})
```

Maybe that's not the right way to set variation of font that will be used in pdf file. :)
