### ISSUE TITLE
copyPage includes rawPDFStream in page being copied

### ISSUE THREAD

**Issue by irtzasuhail** [Hopding/pdf-lib#855]
I am trying to use copyPage to copy pages out of one pdf and into another. The original pdf is ~55 MB in size, but each page that gets extracted, copied is ~51 MB in size. This means that if i copy 2 pages into another pdf, that pdf ends up >110 MB in size. Is there any way I can strip out the raw pdf stream from the copy page, or any other way I can trim down the size of the extracted page? 
Edit: Tried using PdfDocument.flush() but had no effect.

**Comment by Hopding** [comment]
Make sure you're copying all the pages in one shot by passing multiple indices to https://pdf-lib.js.org/docs/api/classes/pdfdocument#copypages.

Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
