### ISSUE TITLE
_this.catalog.Pages().traverse is undefined

### ISSUE THREAD

**Issue by SecureExchanges** [Hopding/pdf-lib#861]
Hello, 

We currently load a PDF with the library
`const pdfDoc = await PDFDocument.load(pdf);`

 and then made a getPages() to get the number of pages in the current PDF. 
  `var pages = pdfDoc.getPages();`

For most of PDF everything workin fine but for a specific PDF we received an error traverse is undefined.

Did somebody already get this error ?
I try to figure where the traverse function is created. I found that is seen to be an extended object create with the `PDFPageTree.prototype.traverse`

That propably mean the PDFPageTree never created or throw an exception. Anybody could point the place to lookup and see what is going wrong ?
thanks.

see the image bellow
![image](https://user-images.githubusercontent.com/38925527/115083767-e4df6380-9ed5-11eb-880b-164d86b28244.png)

**Comment by mmarcotte** [comment]
We were able to reproduce this with a PDF created by PaperPort

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
