### ISSUE TITLE
How to edit existing PDF elements? (Question)

### ISSUE THREAD

**Issue by Danieliessen** [Hopding/pdf-lib#862]
Is there a way to edit existing PDF elements?

**Comment by MonteePoke** [comment]
The only workaround i found is to leave space for text you want to insert
I've heard about using one lib for loading pdf and using HummusJS for editing it, try looking into it
Support for HummusJS has ended tho and it has no types if you're using TypeScript

**Comment by Hopding** [comment]
You can fill form fields https://github.com/Hopding/pdf-lib#fill-form.
