### ISSUE TITLE
'tt' being replace with Ʃ when using drawText

### ISSUE THREAD

**Issue by MonteePoke** [Hopding/pdf-lib#864]
![image](https://user-images.githubusercontent.com/44632941/115518661-1cad2900-a291-11eb-8faf-0e92aef8a5c9.png)

Displays this in both Google Chrome and Opera

**Comment by MonteePoke** [comment]
Tested it a bit more, happens only with embeded fonts with fontkit.
Using this [font](https://www.freebestfonts.com/calibri-font
)

**Comment by Hopding** [comment]
Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you're still having trouble with this.
