### ISSUE TITLE
Apply styles to a subset of the text being added?

### ISSUE THREAD

**Issue by xZwei** [Hopding/pdf-lib#865]
when calling `.drawText("some text to draw", { ...options })`, is there a way to have text styles apply to only a subset of the text being added? Say, I want to change the font color of "some text" but leave "to draw" as is. Or just a way to add styles to text separately from the `.drawText()` call?

**Comment by MonteePoke** [comment]
I doubt you can draw text with different styles with single drawText call, at least i didn't find a way to do it.
Instead I made a parser which splits text into array of strings. If string starts with <b>  and ends with </b> i swap current font to bold and drawText. 
I also used code for line wrapping made by raphaelvazuso in this [issue](https://github.com/Hopding/pdf-lib/issues/20)

**Comment by Hopding** [comment]
@MonteePoke is spot on!

**Comment by vedantrajc** [comment]
> I doubt you can draw text with different styles with single drawText call, at least i didn't find a way to do it. Instead I made a parser which splits text into array of strings. If string starts with and ends with i swap current font to bold and drawText. I also used code for line wrapping made by raphaelvazuso in this [issue](https://github.com/Hopding/pdf-lib/issues/20)

Can anyone explain in more detail, as to how this can be done?
