### ISSUE TITLE
different size of pdf files

### ISSUE THREAD

**Issue by AmilKey** [Hopding/pdf-lib#866]
I generated two files with a picture and text inside and each time I save the file I get a different size, why is this happening?

`cmp test4.pdf test5.pdf`
`test4.pdf test5.pdf differ: char 5056, line 75`

[test (5).pdf](https://github.com/Hopding/pdf-lib/files/6376778/test.5.pdf)
[test (4).pdf](https://github.com/Hopding/pdf-lib/files/6376779/test.4.pdf)

**Comment by jmsofarelli** [comment]
Yes, it seems like the generation of PDF files using this library is not deterministic! :(
I am also getting a similar issue, but copying pages.
I have my source PDF document and I am generating another one copying some pages from the source document.
Every time that I run my code a different PDF file is generated, although the appearance is exactly the same!
Anyone knows the reason?

**Comment by chebum** [comment]
It seems the library adds a content stream that's get changed every minute. For example, if I merge two PDFs together, I get the same result. If the second try is about minute later, I get a different result.

There is a different in one content stream only:
![Screenshot 2021-04-30 112529](https://user-images.githubusercontent.com/1398682/116676324-24fb1780-a9a7-11eb-8c70-86b05b695d44.png)

Everything else is identical.

I suppose the library adds some kind of signature to processed PDFs. I haven't dug into the library's code though.

**Comment by jmsofarelli** [comment]
Amazing man! `create()` method always will generate a new timestamp / metadata. But I found a tricky solution to my use case: instead of creating a new file I open an already created blank file (preserving the metadata), remove the blank page and append the content I want in a deterministic way! Thanks a lot for the help!
