### ISSUE TITLE
Retrieve and modify link url

### ISSUE THREAD

**Issue by olup** [Hopding/pdf-lib#867]
Hi,
I am just dipping in this quite wonderful library. My goal is to list the hyperlink in a PDF, and be able to modify them before saving back the document. I understand I need to access the low level API for this.

I have a bit of trouble understanding the structure and navigating the doc. So far, I was able to list the annotations in a page. I can see the one I am interested in, however I cannot retrieve the actual URL of the link. I think I am missing a final lookup on the document in the pdfdoc context, but I am not sure how and what to request.

So, from an annotation like this one (outputted here as string) :
```
<<
/A 132 0 R
/BS <<
/S /S
/Type /Border
/W 0
>>
/Border [ 0 0 0 ]
/H /N
/Rect [ 187.394 439.03 401.38 403.001 ]
/Subtype /Link
/Type /Annot
>>
```

How should I query the context to find the actual URL ? And, moreover, what should I edit and save to modify this URL ?

Cheers !

**Comment by olup** [comment]
Actually, looking through the issues lead me to search for the dict whose ref was store in the `/A` key... And I am getting my links !
Just have to modify and save, will revert for future reference once I manage that.

**Comment by olup** [comment]
For reference : how to retrieve all links in a PDF and update them with some derivation : 
```typescript
  const pages = pdfDoc.getPages();
  pages.forEach((p) => {
    p.node
      .Annots()
      ?.asArray()
      .forEach((a) => {
        const dict = pdfDoc.context.lookupMaybe(a, PDFDict);
        const aRecord = dict.get(asPDFName(`A`));
        const link = pdfDoc.context.lookupMaybe(aRecord, PDFDict);
        const uri = link.get(asPDFName("URI")).toString().slice(1, -1); // get the original link, remove parenthesis
        if (uri.startsWith("http"))
          link.set(asPDFName("URI"), PDFString.of( /*Wathever value*/ )); // update link value
      });
  });
```

**Comment by jonfreynik** [comment]
@olup - Fantastic Code Snippet - where did you find how to extract that annotation information? Very grateful to @Hopding for this fantastic library and to you for following up on your question with a working solution.

**Comment by abdulbadii** [comment]
> For reference : how to retrieve all links in a PDF and update them with some derivation :
> 
> ```ts
>   const pages = pdfDoc.getPages();
>   pages.forEach((p) => {
>     p.node
>       .Annots()
>       ?.asArray()
>       .forEach((a) => {
>         const dict = pdfDoc.context.lookupMaybe(a, PDFDict);
>         const aRecord = dict.get(asPDFName(`A`));
>         const link = pdfDoc.context.lookupMaybe(aRecord, PDFDict);
>         const uri = link.get(asPDFName("URI")).toString().slice(1, -1); // get the original link, remove parenthesis
>         if (uri.startsWith("http"))
>           link.set(asPDFName("URI"), PDFString.of( /*Wathever value*/ )); // update link value
>       });
>   });
> ```

Would you please share documentartion source you read on reference of `.node` method ?
Please help?
