### ISSUE TITLE
PDF page size and document coordinates origin

### ISSUE THREAD

**Issue by PolGuixe** [Hopding/pdf-lib#87]
Is there a way of getting or setting the page dimensions of an existing PDF document when loading it: 

`const pdfDoc = PDFDocumentFactory.load(existingPdfDocBytes);` 

Is the origin of the coordinates system in the bottom left? Can it be changed to the top-left?

**Comment by AntonioCunha** [comment]
First of all thanks for this great lib. I was using some old java libs for pdf manipulation i having this on node with this simplicity is great. So we are using your lib for merging several pdf and puting a new page number on the final merged pdf, this works great on the basic size pdfs. But when we have different size pages the page number is a bit akward cause it's not dinamic. 
I also agree that a top-left system is more natural for developers. 

Having a getter with a page size would allow us to have a relative position coordinates fixer, but even better was the lib to this by itself example:
x: 25 (from left)
x: -25 (from right)
y: 25 (from top)
y:-25 (from bottom)

If this is something that you think that can be done and something you like to have i'll be happy to help.

**Comment by Hopding** [comment]
@PolGuixe Yes, there is a way to get the dimensions of an existing PDF page. You have to manually define a `getPageDimensions(page: PDFPage)` helper. I've provided this helper in my post here: https://github.com/Hopding/pdf-lib/issues/62#issuecomment-453847201. You could use a similar approach to change the dimensions of a page.

**Comment by Hopding** [comment]
@PolGuixe @AntonioCunha The coordinates system is located in the bottom left. It operates like a standard Cartesian Plane. I'll admit that this may be a bit awkward, since a lot of computer graphics define their origin in the upper left. However, the [PDF spec](https://github.com/Hopding/pdf-lib/blob/master/pdf_specification.pdf) requires that it be in the lower left:

> **8.3.2 Coordinate Spaces**
> Paths and positions shall be defined in terms of pairs of coordinates on the Cartesian plane. A coordinate pair is a pair of real numbers x and y that locate a point horizontally and vertically within a two-dimensional coordinate space. A coordinate space is determined by the following properties with respect to the current page:
> * The location of the origin
> * The orientation of the x and y axes
> * The lengths of the units along each axis

Once you obtain the height and width of the page with `getPageDimensions`, it should be pretty easy to place things where you what them with a bit of adjustment for the location of the origin. I think that relocating the origin is an interesting idea. However, it probably won't be feasable to implement this as part of `pdf-lib`'s standard API without creating another layer of abstraction on top of the PDF spec. I am planning on creating a layer like this in the coming months, in order to create a more user friendly set of APIs.

**Comment by hdwong** [comment]
+1

**Comment by thatisuday** [comment]
@Hopding If I am not wrong, not only the PDF origin is located at bottom-left corner and it follow standard cartesian coordinate system but drawing direction is also follows this system, correct? For example, if you draw a rectangle, then it's **top-left** corner wouldn't be at given `x,y` position but rather it's **bottom-left** corner because draw operation took `x,y` and draw in **bottom-to-top** and **left-to-right** direction. Is this hypothesis correct?

**Comment by glimmbo** [comment]
Are there currently any methods of determining the 'box' around a multiline text in cartesian then? I see `layoutMultilineText` but I'm unsure how to make use of it.. attempting to create a table that accommodates variable multiline cells.

**Comment by kitzj** [comment]
I got the below example to work as a demo. It makes it so you can define coordinates as if 0,0 is in the upper left for 0, 90, 180 and 270 degrees of rotation of the page. Makes it simple so if you're using web coordinates where 0,0 is in the upper left, you can use those values as xCoord and yCoord below, and you'll always get an image at 50,100 from the upper left visual orientation regardless of page rotation.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image to Rotated PDF</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            background-color: #f0f0f0;
        }
        #container {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
            text-align: center;
        }
        #preview {
            max-width: 300px;
            max-height: 300px;
            margin: 10px 0;
            display: none;
        }
        #rotateBtn, #downloadBtn {
            padding: 10px 20px;
            margin: 5px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            background-color: #007bff;
            color: white;
            font_size: 16px;
        }
        #rotateBtn:hover, #downloadBtn:hover {
            background-color: #0056b3;
        }
        #downloadBtn:disabled {
            background-color: #cccccc;
            cursor: not-allowed;
        }
        #rotationInfo {
            margin: 10px 0;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div id="container">
        <h2>Upload Image and Create Rotated PDF</h2>
        <input type="file" id="imageInput" accept="image/*">
        <img id="preview" alt="Image Preview">
        <div id="rotationInfo">Current Rotation: 0°</div>
        <button id="rotateBtn">Rotate 90°</button>
        <button id="downloadBtn" disabled>Download PDF</button>
    </div>

    <script src="https://unpkg.com/pdf-lib@1.17.1/dist/pdf-lib.min.js"></script>
    <script>
        const imageInput = document.getElementById('imageInput');
        const preview = document.getElementById('preview');
        const rotateBtn = document.getElementById('rotateBtn');
        const downloadBtn = document.getElementById('downloadBtn');
        const rotationInfo = document.getElementById('rotationInfo');
        let imageData = null;
        let currentRotation = 0;

        // Handle image upload
        imageInput.addEventListener('change', async (e) => {
            const file = e.target.files[0];
            if (file && file.type.startsWith('image/')) {
                const reader = new FileReader();
                reader.onload = (event) => {
                    imageData = event.target.result;
                    preview.src = imageData;
                    preview.style.display = 'block';
                    downloadBtn.disabled = false;
                };
                reader.readAsDataURL(file);
            }
        });

        // Handle rotation
        rotateBtn.addEventListener('click', () => {
            currentRotation = (currentRotation + 90) % 360;
            rotationInfo.textContent = `Current Rotation: ${currentRotation}°`;
        });

        // Handle PDF download
        downloadBtn.addEventListener('click', async () => {
            if (!imageData) return;

            const { PDFDocument, degrees } = PDFLib;
            const pdfDoc = await PDFDocument.create();
            const page = pdfDoc.addPage([595, 842]); // A4 size in points
            page.setRotation(degrees(currentRotation));

            // Load image
            const img = await fetch(imageData).then(res => res.arrayBuffer());
            let pdfImage;
            if (imageData.includes('image/jpeg')) {
                pdfImage = await pdfDoc.embedJpg(img);
            } else if (imageData.includes('image/png')) {
                pdfImage = await pdfDoc.embedPng(img);
            } else {
                alert('Unsupported image format. Please use JPEG or PNG.');
                return;
            }

            // Image dimensions
            const { width, height } = pdfImage;
            const scale = Math.min(200 / width, 200 / height);
            const scaledWidth = width * scale;
            const scaledHeight = height * scale;

            // Set position and rotation based on page rotation
            let x, y, imgRotation;
            const pageWidth = page.getWidth();
            const pageHeight = page.getHeight();

            //These are your coordinates from the orientation as if the top left of the page is 0,0
            const xCoord = 50;
            const yCoord = 100;       
    
            switch (currentRotation) {
                case 0:
                    x = xCoord;
                    y = pageHeight - scaledHeight - yCoord;
                    imgRotation = 0;
                    break;
                case 90:
                    x = scaledHeight + yCoord;
                    y = xCoord;
                    imgRotation = -90;
                    break;
                case 180:
                    x = pageWidth - xCoord;
                    y = scaledHeight + yCoord;
                    imgRotation = -180;
                    break;
                case 270:
                    x = pageWidth - scaledHeight - yCoord;
                    y = pageHeight - xCoord;
                    imgRotation = -270;
                    break;
            }

            // Correct flipping for 90° and 270°
            if (currentRotation === 90 || currentRotation === 270) {
                imgRotation += 180;
            }

            // Draw image
            page.drawImage(pdfImage, {
                x,
                y,
                width: scaledWidth,
                height: scaledHeight,
                rotate: degrees(imgRotation),
            });

            // Save and download PDF
            const pdfBytes = await pdfDoc.save();
            const blob = new Blob([pdfBytes], { type: 'application/pdf' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = 'rotated_image.pdf';
            link.click();
            URL.revokeObjectURL(url);
        });
    </script>
</body>
</html>
```
