### ISSUE TITLE
Save pdf to server 

### ISSUE THREAD

**Issue by mozez-a** [Hopding/pdf-lib#870]
How to save pdf to server

**Comment by walmac** [comment]
I used axios and a POST message using  headers:  content-type': 'application/pdf', then in nodejs you can read the post as a request with the file in the body.

**Comment by Hopding** [comment]
@walmac has the right idea. You just need to send the `Uint8Array` to your server somehow. There are lots of options. This is a more generic JS question though. Stackoverflow can probably help you out here.
