### ISSUE TITLE
Font issue with specific character combination

### ISSUE THREAD

**Issue by donmb1** [Hopding/pdf-lib#871]
Hi folks,
I have successfully embedded a custom font. Now I have an issue with font rendering. It only occurs if there is a combination of two `ff` characters => there is an unintended space behind the two letter. The font itself works properly. I can test it in Word, Pages and other tools and there the issue is not reproduceable. Only in `pdf-lib` I see this strange behaviour so I believe the font encoding might not be correct.

Here is a screenshot of my PDF for visualization:
![font-issue](https://user-images.githubusercontent.com/3296757/117122938-b2b77800-ad96-11eb-89d6-6df260f5119e.png)

Here is my code for embedding the custom font:

```
import fontkit from "@pdf-lib/fontkit";

...

      const aktivGroteskExThinUrl =
        "<font-url>/aktivGroteskExThin.ttf";

      const url = `some-pdf.pdf`
      const existingPdfBytes = await fetch(url).then(res => res.arrayBuffer())

      const pdfDoc = await PDFDocument.load(existingPdfBytes)

      // register fontKit to use custom fonts
      pdfDoc.registerFontkit(fontkit);

      // define fonts
      const res = await fetch(aktivGroteskExThinUrl);
      const customFont = await res.arrayBuffer();
      const aktivGroteskExThinFont = await pdfDoc.embedFont(customFont);

      // define first Page layout
      const pages = pdfDoc.getPages()
      const firstPage = pages[0]

      // top left
      firstPage.drawText(`Some Text with double ff-char combination: Pfeffer `, {
        x: 17,
        y: 193,
        size: 6,
        font: aktivGroteskExThinFont
      })

```

Any hint in the right direction would be appreciated. Thank you.

**Comment by MonteePoke** [comment]
https://github.com/Hopding/pdf-lib/issues/864
I'm having same problem but with different font and letter combinations

**Comment by ironsm4sh** [comment]
This probably happens because of the font ligatures.
see #490

To solve your issue, register your font as follows.
```typescript
const aktivGroteskExThinFont = await pdfDoc.embedFont(customFont, { 
   subset: true, 
   features: { liga: false }, 
 }); 
 ```

**Comment by Hopding** [comment]
I suspect @ironsm4sh is right about the ligatures. If that doesn't solve your problem, feel free to fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form.
