### ISSUE TITLE
Question: Can the code be executed  on serverside? 

### ISSUE THREAD

**Issue by MathiasKrill** [Hopding/pdf-lib#872]
Hi, iam very new to Angular and Javascript/Typescript. 
In our app-browser which has some security modifications the lib methods are leading to crashes which can not be changed.  

As the title says iam interessted to know if the library functions can be excuted on serverside ?

**Comment by btecu** [comment]
Yes, you can use this library on a server using Node or Deno.

**Comment by alwins0n** [comment]
you find the answer on the very first section in the documentation. https://github.com/Hopding/pdf-lib#motivation

**Comment by Hopding** [comment]
@btecu and @alwins0n are spot on 👍
