### ISSUE TITLE
Remove or edit form field appearence.

### ISSUE THREAD

**Issue by SAGOlab** [Hopding/pdf-lib#875]
Hi there,

take a look at this pdf file [sample pdf](https://www.interno.gov.it/sites/default/files/2020-10/modello_autodichiarazione_editabile_ottobre_2020.pdf).

I can fill its form fields, but I'm wondering if there is a way to fill a single input form and replace it with only input value, removing underline and unused space before next sentences.

thanks.

**Comment by Hopding** [comment]
If I understand your question correctly, the closest thing to what you're looking for is https://pdf-lib.js.org/docs/api/classes/pdfform#flatten.
