### ISSUE TITLE
Support for annotations and page labels?

### ISSUE THREAD

**Issue by mrobe** [Hopding/pdf-lib#878]
Are there plans to add support for annotations and/or page labels?

Regarding annotations, I'm wondering if I could use pdf-lib to open a PDF that already includes annotations, then, add some new annotations via pdf-lib, and then save the PDF with both old and new annotations. I'm specifically interested in being able to highlight lines of text (i.e., colored rectangles) and add text notes as annotations.

Regarding page labels, I'm wondering if I could use pdf-lib to access book-style page numbering, since many academic books in PDF use roman followed by Arabic numbers (i.e., i, ii, iii, iv, ... 1, 2, 3, 4, etc.). When book-style page numbers are used, the PDF standard can handle it with page labels, but the "absolute page numbers" of most PDF readers (e.g., page numbers start from 1) are incorrect.

Thanks!

**Comment by mrobe** [comment]
Bump

**Comment by mrobe** [comment]
From discussion on the Discord channel, I have been told that there is in principle support for both annotations and page labels, though it hasn't been documented.

So, I would propose the addition of documentation as a step to resolve this issue.

**Comment by Hopding** [comment]
See https://github.com/Hopding/pdf-lib/issues/464#issuecomment-643834048 for how to add/change labels.

Better support for annotations is now on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
