### ISSUE TITLE
Process a SVG as XML

### ISSUE THREAD

**Issue by laura-bergoens** [Hopding/pdf-lib#881]
Hi !
We are using this great lib to create PDF documents at Pix (https://github.com/1024pix?type=source).
Lately, we have been asked to insert images into the PDF document.
The images are SVG as xml, with a quite complex xml composition in terms of variety of nodes and such.

I noticed in the docs that there is a [drawSvgPath](https://pdf-lib.js.org/docs/api/classes/pdfpage#drawsvgpath) method which takes a path as an input. In our case, as I say, the xml is quite more complex (several paths and other nodes like `stroke-*`).

Am I missing something in the documentation ? Maybe there is a method that takes directly a SVG as XML ?

Thank you very much for your work

**Comment by alwins0n** [comment]
have a look at this: https://github.com/Hopding/pdf-lib/pull/823

**Comment by Sharcoux** [comment]
@laura-bergoens you can try this: [@cantoo/pdf-lib](https://www.npmjs.com/package/@cantoo/pdf-lib)
It's a fork of this lib, adding support to what you're asking with the code of the PR that was linked to you by @alwins0n

If you notice bugs, please report.

**Comment by laura-bergoens** [comment]
Thank you very much both of you, I'll take a look

**Comment by laura-bergoens** [comment]
@Sharcoux I've tried the lib, particularly the function `drawSvg(...)`. It does not work but it's due to the fact that my .svg file contains <defs> tags, and it seems like it's not supported in the code.
Also, I've tried to alter my .svg using Inkscape and find a way to "flatten" those defs, but I could not (I'm really not familiar with this software 😅 ).

Any thoughts ? Thanks again for your time

**Comment by laura-bergoens** [comment]
Sorry, to be more specific, some color value in fill attributes are in fact url to definitions, like this :
```xml
<path
 d="SOME PATH VALUES"
 id="Fill-2"
 fill="url(#linearGradient-4)" />
```
which is not handled by the function. (It fails when trying to convert the color into string)
The element pointed by the ID given in the url is defined in a `<def>` tag, like this for instance :
```xml
<defs
   id="defs1115">
   <linearGradient
     x1="51.7006812%"
     y1="2.37326458%"
     x2="54.8974687%"
     y2="102.107497%"
     id="linearGradient-4">
     <stop
       stop-color="#12A3FF"
       offset="0%"
       id="stop1054" />
     <stop
       stop-color="#3D68FF"
       offset="100%"
       id="stop1056" />
  </linearGradient>
</defs>
```

**Comment by alwins0n** [comment]
use inkscape shell or rsvg-convert as tools to convert svg to pdf. I don't want to speak for the maintainer, but I think full svg support ist out of scope of this project/library

**Comment by Sharcoux** [comment]
How do you handle that in a cross platform app RN +RNWeb?

**Comment by Hopding** [comment]
Hello @laura-bergoens! `pdf-lib` does not currently provide an API to directly embed an SVG. You'll have to find a way to either convert the SVG to an image or an SVG path (maybe more than one path). I don't have any experience with those conversions though, so I can't help you there.

**Comment by tafakkur** [comment]
I faced a similar issue, inserting a highcharts svg into a pdf doc.
My solution was a create a single page using pdfmake, then inserting the page in the destination document using this lib.

**Comment by Sharcoux** [comment]
Just as a reference, there is this PR in process of integration: https://github.com/Hopding/pdf-lib/pull/1073

**Comment by tafakkur** [comment]
@Sharcoux Thanks for the great work.
