### ISSUE TITLE
How would I pass PDF data between models in Node?

### ISSUE THREAD

**Issue by OctaneInteractive** [Hopding/pdf-lib#882]
Hi!

I'm attempting to move from `writeStream = fileOperations.createWriteStream( ... )` to streaming the data between models in Node.

```
try {
  // Create the PDF.
  pdfDoc.pipe(writeStream)
  pdfDoc.end()
  writeStream.on('finish', function () {
    return resolve(true)
  })
} catch(exception) {
  return reject(exception)
}
```
While this works, [this example doesn't](https://github.com/Hopding/pdf-lib/issues/163) when using `pdfBytes.buffer`, where I'm told:

> The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

```
try {
  // Create the PDF.
  const pdfBytes = await pdfDoc.save()
  let buffer = Buffer.from(pdfBytes, 'binary')
  return resolve(buffer)
} catch(exception) {
  return reject(exception)
}
```

Here I'm told:

> The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of PDFDocument

The PDF files I'm creating are trivial — less than 10 kilobytes — and it's pointless saving them to disk when it _should_ be possible to pass them between methods.

Any idea how I get at the data in the `pdfBytes` constant?

**Comment by Hopding** [comment]
`pdfBytes` is already a buffer-like object that has the serialized PDF (see https://pdf-lib.js.org/docs/api/classes/pdfdocument#save). There's no need to save it to disk. The `Uint8Array` is a standard type to represent binary data in JavaScript. `Buffer` is node-specific, but you can certainly convert a `Uint8Array` to a `Buffer`. I'm not sure how offhand, google and stackoverflow could probably help you there.
