### ISSUE TITLE
Create a mailto button with PDF LIB?

### ISSUE THREAD

**Issue by Geniewave** [Hopding/pdf-lib#885]
Hi folks, I've been reading through the API documentation and saw that we could create a button to be pressed on the layout, but didn't quite see anything on how to configure them. 

How could I create a simple mailto button with a pre-programmed email address that will simply open the email protocol on the user's computer viewing the PDF? I don't want anything fancy, but having that will make a tremendous difference in my work!

I would assume it is with the acroField property ?

Thanks to all!

**Comment by bjbk** [comment]
I, too, am looking for a way to accomplish this.

Docs:
>PDFButton fields are interactive controls that users can click with their mouse. This type of PDFField is not stateful. The purpose of a button is to perform an action when the user clicks on it, such as opening a print modal or resetting the form. Buttons are typically rectangular in shape and have a text label describing the action that they perform when clicked

How does one set the action?  Adding a `addJavaScript` to the document perhaps?  But then, how to call that from the button?

`pdfDoc.addJavaScript( 'submit', 'function submit() { return "mailto:foo@example.com"; }' )`

Could the submit function be called when clicking the button?  Does one add an event listener?

**Comment by Hopding** [comment]
I'm not sure if this is possible offhand. I'd suggest looking into using a link rather than a button. You can check out some of the other issues where I've provided link examples. You might be able to replace the HTTP URL with a `mailto:`. Please open a Discussion if you're still having trouble with this.

**Comment by bjbk** [comment]
Thanks for looking at this. I think I can work with a link. Just looking for a way to submit a form.  Interesting that buttons can be made but seems there is no way to implement functionality.  Was thinking I was missing something from the docs.  Thanks again for looking into it.  Overall, this has been an excellent library for my needs!
