### ISSUE TITLE
Modify existing PDF, two downloads instead of one?

### ISSUE THREAD

**Issue by Hansos1** [Hopding/pdf-lib#886]
HI, i have my code to modify an existing PDF almost working; One issue that is keeping me from deploying is that it downloads twice. 

As soon as I call 

**const pdfDoc = await PDFDocument.load(dataUri)** 

it downloads a file with <<UNIQUEID >>.PDF name is no PDF format and has as content **[object Promise]**; I would expect it to keep as variabele and use for modifying in the next line. Which it does and at the end it downloads the correct an readable modified pfd; I just don't want the const pdfDoc = await PDFDocument.load(dataUri)  to download the  incorrect and not needed document. What am I doing wrong? Any help appreciated! Thanks, Hans

This is my code:
**INPUT BYTES = BASE64 STRING of EXISTING PDF**

async function modifyPdf(bytes) {
                const { degrees, PDFDocument, StandardFonts, rgb } = PDFLib
		const dataUri = 'data:application/pdf;base64,' + bytes

		**const pdfDoc = await PDFDocument.load(dataUri) --> WHEN CALLED DOWNLOAD EMPTY DOCUMENT WITH A UNIQUEIDENTIFIER (CHAR(36)) .PDF as Filename??? and [object Promise] as content? **  

		const helveticaFont = await pdfDoc.embedFont(StandardFonts.Helvetica)

		const pages = pdfDoc.getPages();
		const firstPage = pages[0]
		const { width, height } = firstPage.getSize()
		firstPage.drawText('INSERTED STRING', {
			x: 5,
			y: height / 2 + 300,
			size: 50,
			font: helveticaFont,
			color: rgb(0.95, 0.1, 0.1),
			rotate: degrees(-45),
		})

		const pdfBytes = await pdfDoc.save()
		**download(pdfBytes, "pdf-lib_modification_example.pdf", "application/pdf"); --> WHEN CALLED DOWNLOADS MODIFIED PDF; CORRECT**
		}

**Comment by Hopding** [comment]
Not enough information provided for me to easily reproduce the issue.
