### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by oktapodia** [Hopding/pdf-lib#887]
Hello,

Great library there.

I am looking to generate a PDF in portrait and landscape mode. Everything is fine with the portrait mode but I am wondering if there is an easy way to make a similar one in landscape mode?

I've seen that I can do the following with https://github.com/Hopding/pdf-lib/issues/65 but unfortunately, I have to specify the rotation + rework all placement of texts/images for each elements populating the page.

```
const page = pdf.addPage(PageSizes[paperSize]);
page.setRotation(degrees(90))
```

Thanks in advance.

**Comment by inane** [comment]
Any solution? I am looking the same.. :-(

**Comment by gputto** [comment]
Update
I just found myself doing this:

const page = pdfDoc.addPage([841.89, 595.28])

Instead of this:
 
const page = pdfDoc.addPage(PageSizes.A4)

**Comment by joel-matthias** [comment]
Or

`const page = pdfDoc.addPage([PageSizes.A4[1], PageSizes.A4[0]] )`
