### ISSUE TITLE
How to add ZIP file as an attachment in PDF?

### ISSUE THREAD

**Issue by chinnawip** [Hopding/pdf-lib#889]
Hi,
I tried this in the following way, but after downloaded from PDF, I can't unzip it, it says like unsupported format. Please help me on this.
Here is snippets.
```
 	let zipFile = File.fromPath(archive);
			let content = zipFile.readSync();
			let enc = new TextEncoder();
			let contentBase64 = enc.encode(content);
			// let contentBase64  = base64.encode(content); // I tried this way also

			fileAttach = fileAttach.replace('.json','.zip');
			console.log('Attaching attachment... :', fileAttach);
			await this.pdfDoc.attach(contentBase64, fileAttach, {
				mimeType: 'application/zip',
				description: '',
				creationDate: new Date(),
				modificationDate: new Date(),
			});
```
Thanks & Regards
Chinna

**Comment by Hopding** [comment]
Need more information to help with this. Please filll out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) if you're still having trouble.
