### ISSUE TITLE
Is there any way to extract text from a PDF using pdf-lib library i.e.  using x , y coordinates

### ISSUE THREAD

**Issue by HassanTarique27** [Hopding/pdf-lib#892]

**Comment by Hopding** [comment]
https://github.com/Hopding/pdf-lib#limitations
> it **cannot** extract plain text on a page outside of a form field. This is a difficult feature to implement, but it is within the scope of this library and may be added to pdf-lib in the future. See #93, #137, #177, #329, and #380.

**Comment by xulihang** [comment]
`pdf.js` can extract text with coordinates. Maybe we can just learn from its implementation?
