### ISSUE TITLE
How to display a HTML content or draw a html content on PDF 

### ISSUE THREAD

**Issue by sairamsunkara673M** [Hopding/pdf-lib#894]
I have to print  content Like the following
 Hai
 How are u?
 How can  I help u
 
 I'm using  the following method here node.textContent is the every single line like Hai, How are u? here I want line break how to achieve that.
 page.drawText(node.textContent, {
                y: node_parameters.pdf_page_y,
                x: node_parameters.pdf_page_x,
                font: pdf_font,
                color: rgb(color[0], color[1], color[2]),
                size: font_size,
              }); 
              
              or else is there a way to show HTML content as plain text 
         <div>
      <p>
        <span> Sairam</span>
      </p>
      <p><span>Sunkara</span></p>
      <p><br /></p>
    </div>
    
    like 
              Sairam
              Sunkara

**Comment by Hopding** [comment]
`pdf-lib` doesn't support this.
