### ISSUE TITLE
Generating a dark mode version

### ISSUE THREAD

**Issue by crysfel** [Hopding/pdf-lib#896]
Hi folks! Thanks for this awesome project!! It's really really good!!

I do have a mobile app where I'm showing sheet music as a PDF file, they look beautiful on the device. However, the app supports dark mode and I'd like to show a dark version of the PDF. I'm thinking of generating two sets of files, one in a light color and another one in dark.

Is it possible to change the background of each file from white to black? Is it possible to change the content of the document from black to white?

This is the original PDF I have:

[1.pdf](https://github.com/Hopding/pdf-lib/files/6556443/1.pdf)

It looks like the background color can be changed like this: https://github.com/Hopding/pdf-lib/issues/446

But what about the content? Texts and notes?

Thanks!

**Comment by Hopding** [comment]
I don't think you're going to have much luck changing that amount content in an existing file. I think the best approach would be to generate a light and dark version up front, when the sheet music PDF is first being generated. If that can't be done, then you could try applying some sort of graphical filter on top of the rendered PDF to modify the colors.
