### ISSUE TITLE
How I can get updated value of form fields?

### ISSUE THREAD

**Issue by sohailafzal3** [Hopding/pdf-lib#898]
I am loading PDF document on change of dropdown and able to get/set all form fields initially but when I change any field (Text, checkbox or radio) I am not able to get updated values. Can anyone help me out what I am missing.

Thanks

**Comment by dcsline** [comment]
If you loading the pdf document in a browser, so known this. it's only the MS Edge Browser, which is saving the pdf document with the changed values.

**Comment by Hopding** [comment]
See https://github.com/Hopding/pdf-lib/issues/965#issuecomment-925360182.
