### ISSUE TITLE
How to increase the content size after crop

### ISSUE THREAD

**Issue by khanakia** [Hopding/pdf-lib#899]
I am cropping the pdf and then i want to scale the size of cropped content but when i increase the page size it simply adds the white space not the scale the content itself.

**Comment by Hopding** [comment]
You can [translate](https://pdf-lib.js.org/docs/api/classes/pdfpage#translatecontent) the content, but there is not currently a way to scale it. That feature might be available soon though. See https://github.com/Hopding/pdf-lib/pull/991.
