### ISSUE TITLE
How to set a image for a form field?

### ISSUE THREAD

**Issue by ConandSherry** [Hopding/pdf-lib#90]
Can `pdf-lib` be used to programmatically fill form field with a image in a template PDF
I tried like this,but failed
```
const sigAppearanceStream = PDFContentStream.of(   
  PDFDictionary.from({
    Type: PDFName.from('XObject'),
    Subtype: PDFName.from('Form'),
    BBox: PDFArray.fromArray([
      PDFNumber.fromNumber(0),
      PDFNumber.fromNumber(0),
      PDFNumber.fromNumber(200),
      PDFNumber.fromNumber(50),
    ], pdfDoc.index),
    Resources: PDFDictionary.from({
      XObject: PDFDictionary.from({}, pdfDoc.index)
    }, pdfDoc.index),
  }, pdfDoc.index),
    drawImage('MarioEmblem', {
      x: 447,
      y: 520,
      width: marioEmblemDims.width * 0.75,
      height: marioEmblemDims.height * 0.75,
    }),
);
```

**Comment by ConandSherry** [comment]
i find that i need to set FRM stream for sigAppearanceStream,n0 stream and n2 stream in FRM, finally set image stream in n2. This is the right way to set a image in a form field.

**Comment by FilipeAraujo** [comment]
hi, @ConandSherry can you please show a sample of your code on how you manage to create a signature appearance with an image? 
I know that I need to create inside the `Resources` a value `FRM` but the way I'm doing it's not working. 

Hope with your help I will manage to get this thing working. 

Thanks!

**Comment by FilipeAraujo** [comment]
@ConandSherry @Hopding can you help me with this? thanks

**Comment by ConandSherry** [comment]
can u show me your pdf structure opened with iText

**Comment by FilipeAraujo** [comment]
@ConandSherry what do you mean by opened with iText?  Do you mean the content of the pdf? I'm not using iText I'm using this lib and `node-signpdf` to sign a pdf.

**Comment by ConandSherry** [comment]
@FilipeAraujo  i changed the api drawImage.The original one can't support FRM value which PDF structure needed

**Comment by FilipeAraujo** [comment]
@ConandSherry did you created a fork for it? can I have a look on the code? thanks

**Comment by ConandSherry** [comment]
@FilipeAraujo  i use `drawImage('FRM')` to create FRM stream and i add
```javascript

if (!options) {    
   return [
      pushGraphicsState(),  
      translate(0, 0),  
      image(name),  
      popGraphicsState(),  
    ].filter(Boolean) as PDFOperator[];  
  }

```
 in the orignal `drawImage` function  
![Untitled222](https://user-images.githubusercontent.com/13324408/60815994-4c2d9700-a1cb-11e9-870d-f545e07e90fc.png)
with iText u can see the pdf struct. so u can compare the difference between yours and pdf which has a signature appearance with an image

**Comment by ConandSherry** [comment]
@FilipeAraujo  also `pdf-lib`'s saving function can't suport incremental addition. u may also have trouble when adding a signuature form field with a pdf has one. `pdf-lib` will make the origin one modified.

**Comment by FilipeAraujo** [comment]
Thanks for the tips @ConandSherry , for now, I will not have incremental additions/updates. 
Although, and help me with this @Hopding , I thought that was possible in 'pdf-lib' to do something like:

```
const n2 = PDFContentStream.of(
      PDFDictionary.from(
        {
          Type: PDFName.from('XObject'),
          Subtype: PDFName.from('Form'),
          BBox: PDFArray.fromArray(
            [
              PDFNumber.fromNumber(0),
              PDFNumber.fromNumber(0),
              PDFNumber.fromNumber(width),
              PDFNumber.fromNumber(height)
            ],
            pdfDoc.index
          ),
          Resources: PDFDictionary.from(
            {
              Font: PDFDictionary.from(
                {
                  Helvetica: this.font
                },
                pdfDoc.index
              )
            },
            pdfDoc.index
          )
        },
        pdfDoc.index
      ),

      drawImage('watermark', {
        x: 0,
        y: 0,
        width: width * 0.4,
        height: height * 0.4
      }),

      drawText(this.cargo, {
        x: MARGIN * 4,
        y: height / 2,
        font: 'Helvetica',
        size: 20,
        colorRgb: [0, 0, 0]
      }),
      drawLinesOfText(this.dn.split('\n'), {
        x: width / 2,
        y: height / 2 + (10 * this.dn.split('\n').length) / 2,
        font: 'Helvetica',
        lineHeight: 10,
        size: 5,
        colorRgb: [0, 0, 0]
      })
    );

    const FRM = PDFContentStream.of(
      PDFDictionary.from(
        {
          Type: PDFName.from('XObject'),
          Subtype: PDFName.from('Form'),
          BBox: PDFArray.fromArray(
            [
              PDFNumber.fromNumber(0),
              PDFNumber.fromNumber(0),
              PDFNumber.fromNumber(width),
              PDFNumber.fromNumber(height)
            ],
            pdfDoc.index
          ),
          Resources: PDFDictionary.from(
            {
              n2: n2
            },
            pdfDoc.index
          )
        },
        pdfDoc.index
      )
    );

    const sigAppearanceStream = PDFContentStream.of(
      PDFDictionary.from(
        {
          Type: PDFName.from('XObject'),
          Subtype: PDFName.from('Form'),
          BBox: PDFArray.fromArray(
            [
              PDFNumber.fromNumber(0),
              PDFNumber.fromNumber(0),
              PDFNumber.fromNumber(width),
              PDFNumber.fromNumber(height)
            ],
            pdfDoc.index
          ),
          Resources: PDFDictionary.from(
            {
              FRM: FRM
            },
            pdfDoc.index
          )
        },
        pdfDoc.index
      )
    );
    const sigAppearanceStreamRef = pdfDoc.register(sigAppearanceStream);
```

This is a rough conversion and it's just to explain what I mean.

Isn't that possible? I'm trying to follow the structure of 
https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PPKAppearances.pdf (page 11).

**Comment by ConandSherry** [comment]
@FilipeAraujo  u miss a n0 stream . i think your file struct is wrong. if u need the right struct, `pdf-lib` can do almost all things,  u only need to modify the `drawImage` API.
```
PDFContentStream.of(
        PDFDictionary.from(
            {
                Type: PDFName.from('XObject'),
                Subtype: PDFName.from('Form'),
                Resources: PDFDictionary.from(
                    {
                        XObject: PDFDictionary.from(
                            {
                                n0: pdfDoc.register(n0Stream),
                                n2: pdfDoc.register(n2Stream)
                            },
                            pdfDoc.index
                        )
                    },
                    pdfDoc.index
                ),
                BBox: PDFArray.fromArray(defaultBBox(), pdfDoc.index),
                FormType: PDFNumber.fromNumber(1),
                Matrix: PDFArray.fromArray(defaultMatrix(), pdfDoc.index)
            },
            pdfDoc.index
        ),
        drawImage('n0'),
        drawImage('n2')
    );
```

**Comment by FilipeAraujo** [comment]
@ConandSherry thanks! however, would it be great to do this without changing the `pdf-lib` core. @Hopding do you have something in the pipeline related to this? thanks!

**Comment by Hopding** [comment]
@FilipeAraujo I do plan to greatly improve pdf-lib's support for signatures and acroform fields. I'm currently working on [finishing v1.0.0](https://github.com/Hopding/pdf-lib/issues/134), which includes a new high level API for pdf-lib's existing features. After that, one of the things I'd like to work on is better acroform and signature support. I can't commit to a specific timeline. But hopefully it'll be done within a few months.

**Comment by conor909** [comment]
@Hopding I'm trying to add an image into a form field location instead of x y coordinates, is this possible yet?
