### ISSUE TITLE
PDF-LIB is less permissive with corrupt file than viewers such as PDF.js and PDFium

### ISSUE THREAD

**Issue by cetinsert** [Hopding/pdf-lib#902]
**Steps to Reproduce**

1. Open new tab.
2. Open developer console.
3. Navigate to https://webpdf.glitch.me/x/pdf-lib/1/ (shown below)

**What happened?**

```html
<link rel=icon href=//cdn.blue/{fa-5.15}/svgs/duotone/times-circle.svg> 
<title>#902</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.16.0/pdf-lib.min.js"></script>
<pre id="m">⏳ ⋯</pre>
<script>
  console.clear();
  const load = async url => {
    const  f = await fetch(url);
    const  b = await f.arrayBuffer();
    
    const { PDFDocument } = PDFLib;
    const  O = { ignoreEncryption: true };
    const  n = await PDFDocument.create();
    const  o = await PDFDocument.load(b, O); // ⚠️
    const  P = await n.copyPages(o, [ 2 ]);  // ❌
    for (const p of P) await n.addPage(p);
    /**/   x = await n.save();
    
    /**/   m.textContent = `💾 ${x.length}`;
  };
  const file = [
    `https://pdf.ist/web.pdf`,
    `https://pdf.ist/r/DJI_FPV_User_Manual_EN.pdf`,
    `https://pdf.ist/r/DJI_FPV_User_Manual_EN_repaired.pdf`
  ];  
  load(file[1]);
  /*
file[1] is corrupt but loads and renders fine with PDF.js and PDFium.
file[1] generates a false PDF-LIB warning on line 14: ⚠️ Error: Input document to `PDFDocument.load` is encrypted. You can use `PDFDocument.load(..., { ignoreEncryption: true })` if you wish to load the document anyways.
file[1] generates a       PDF-LIB   error on line 15: ❌ Error: Expected instance of e, but got instance of undefined ⋯
  */    
</script>
```

**Expected Behavior**

Be at least as permissive as viewers.

---

**Additional Questions**

1. Is there a more robust PDF-LIB-only way of copying files from corrupt files one should be aware of?
2. Is there a different browser-only library that might work such corrupt files? (pdftk, ...!?)
3. Is there a known browser-only library that can repair corrupt PDF files?

---

Adobe's own tools fail the same way as in line 19 above thinking the file is encrypted.

![image](https://user-images.githubusercontent.com/27027/120538982-18446600-c422-11eb-8ea7-5d4f9333a586.png)

---

Ran the file through https://www.ilovepdf.com/repair-pdf and the repaired version is also attached and does work.

**Comment by Hopding** [comment]
Hello @cetinsert!

Sounds like the PDF you're having trouble with _is_ actually encrypted. See https://github.com/Hopding/pdf-lib/issues/134#issuecomment-509452191 for details on how that could be the case.
