### ISSUE TITLE
Not working with Qualtrics

### ISSUE THREAD

**Issue by tafakkur** [Hopding/pdf-lib#904]
Hi,
I'm relatively new with JavaScript, so I apologize if I missed out something obvious.
Qualtrics is a survey platform, and it gives a lot flexibility while working with JS.

I've been able to use pdfmake to generate PDF ([link](https://iima.au1.qualtrics.com/jfe/form/SV_eM8dbdx03IIt3AG)).

However, when I use pdf-lib, the file is always corrupted.

I'm following the basic example from [this fiddle](https://jsfiddle.net/Hopding/rxwsc8f5/13/). 
I initially thought it was an issue with my browser, so I copied eveything into an HTML. ([fiddle_html.txt](https://github.com/Hopding/pdf-lib/files/6594909/fiddle_html.txt)) and its working fine.

But the pdfs being created when inside Qualtrics, don't open. ([error demo](https://iima.au1.qualtrics.com/jfe/form/SV_cItXY7QaXf3r3fw))

Could somebody please help.

Thanks.

**Comment by Hopding** [comment]
I'm not sure how Qualtrics works and you haven't provided enough information for me to reproduce the issue myself.

That being said, when I try to download the PDF from the link you shared, I get back just 90 bytes. There's no way you can fit a PDF file into just 90 bytes.

<img width="1095" alt="Screen Shot 2021-09-22 at 6 55 16 PM" src="https://user-images.githubusercontent.com/10351828/134437089-94f4e20c-c7df-49e4-8f88-139eb8c166bd.png">

When I look at what those 90 bytes are composed of, I see a very incomplete PDF document:
```
$ cat ~/Downloads/pdf-lib_creation_example.pdf
%PDF-1.7
%����

8 0 obj
<<
>>
stream
x�c`���Q��
          1
endstream
endobj

startxref
16
%%EOF
```
There seems to be something wrong how you're using pdf-lib, saving the document, and sending it to the user.
