### ISSUE TITLE
 Text following a curve or text on a path

### ISSUE THREAD

**Issue by testdami555** [Hopding/pdf-lib#906]
Is there an alternative to making the text follow a curve or a path?

Something like this:
https://www.pdflib.com/pdflib-cookbook/textflow/text_with_image_clipping_path/
https://www.pdflib.com/pdflib-cookbook/text_output/text_on_a_path/php

But I need to do it with JavaScript

Thanks

**Comment by Hopding** [comment]
Hmm. That's an interesting question. I'm not sure offhand. If you provide a sample document with the type of text you're describing, then I can look at how it's achieved and see if `pdf-lib` can do something similar. If you're still interested in this, please open a Discussion and we can go from there.
