### ISSUE TITLE
Does pdf-lib support creating Optional Content Groups?

### ISSUE THREAD

**Issue by Clonkex** [Hopding/pdf-lib#907]
We want to programmatically create PDFs for use in a specialised printing machine, and we need to use Optional Content Groups (layers) to specify where the bottom white layer and top varnish layer will be laid down.

Does pdf-lib support OCGs?

**Comment by Hopding** [comment]
It doesn't provide special support for them. I am not too familiar with OCGs myself. I'd need more information about what they are and how they work to say if you could implement them with `pdf-lib`.
