### ISSUE TITLE
Getting widget text appearance (font family, size, color)

### ISSUE THREAD

**Issue by aluisiora** [Hopding/pdf-lib#908]
Hi! I'm not really into the PDF inner bits, so I'm struggling to figure out how to get a widget's font family.

I was able to get some of the information I need by using the `getDefaultAppearance` method from the acroField object which returned something like this:

```javascript
// field.acroField.getDefaultAppearance()

0 0 0 rg /F3 9 Tf
```

From what I understood, the 0 0 0 is the rgb from 0 to 1. 
The 'rg' I have no idea what is.
The '/F3' is what I'm guessing is a reference to the font family? But I have no ideia how to get that value.
9 is the font size and the Tf I also have no ideia.

I'm trying to read a pdf which has some fields in it.

**Comment by Hopding** [comment]
`/F3` is a key in the widget's resource dictionary, the value of which should be a font object. You should be able to find the name in there. If you're still working on this, feel free to open a Discussion with example code and I can take a look when I have time.
