### ISSUE TITLE
drawSvgPath does not work correctly.

### ISSUE THREAD

**Issue by mhuryanov** [Hopding/pdf-lib#909]
If I draw an SVG path with a long SVG path, PDF shows differently from the original SVG in HTML show. 

--- original SVG path
https://codepen.io/mhuryanov/pen/LYWBBag
--- draw SVG path in pdf
https://codepen.io/mhuryanov/pen/OJpwweV

Try download the pdf from the second link. Even though the same SVG is in the code as the first Codepen, the results are slightly different from each other as you can see from here:

![image](https://user-images.githubusercontent.com/62013740/121328194-c9fcfe80-c91c-11eb-90ea-d02e00a078e7.png)
![image](https://user-images.githubusercontent.com/62013740/121328252-d5502a00-c91c-11eb-8359-c353e2317ff0.png)

Did I make a mistake on my code or is it a kind of bug? Please let me know if I did or not, as soon as possible.

**Comment by Hopding** [comment]
I'm not sure if it's a bug because I'm unable to reproduce the issue. Your first link returns 404.
