### ISSUE TITLE
Update `computeFontSize` to support automatic line-wrapping and automatic font size calculation.

### ISSUE THREAD

**Issue by mnash-dbg** [Hopding/pdf-lib#910]
As per the comment at https://github.com/Hopding/pdf-lib/blob/master/src/api/text/layout.ts#L144, _"This is hardcoded to make it easier to perform automatic line-wrapping."_.

This greatly reduces the usability of the library for those who need to leverage multiline inputs with a font size of "Auto".

Please consider this issue as a request/placeholder to implement this feature and make its current absence more prominent to consumers of the library.

**Comment by Hopding** [comment]
This has been shipped. Thanks again @milesnash!
