### ISSUE TITLE
How can I access a PDFTextField's format information?

### ISSUE THREAD

**Issue by j-at-maderausd** [Hopding/pdf-lib#913]
Text fields in Acrobat can have Format information added:

![adobe-text-format-options](https://user-images.githubusercontent.com/74678107/121927077-80812a80-ccf3-11eb-9856-a43077fc8c5e.png)

Formats include None, Number, Percentage, Date, Time, Special, and Custom.

Each format can then have additional data set, such as specifying the format of a date:

m/d
m/d/yy
m/d/yyyy (etc.)

How can this data be accessed in pdf-lib from the PDFTextField object?

I don't see any mention of it in the documentation.

**Comment by stx-chris** [comment]
Hi @j-at-maderausd you ever find a solution? thx!

**Comment by j-at-maderausd** [comment]
Nope, never found a solution. I wound up having to use a suffix naming convention on fields to indicate format information.

**Comment by Hopding** [comment]
I don't _think_ form fields have a format property. Pretty sure Acrobat achieves this by adding JS to the field that's executed when the user provides input in a PDF viewer. Using a particular naming convention when creating the fields seems like a good way to go about this to me 👍.
