### ISSUE TITLE
Destroy PDF Object

### ISSUE THREAD

**Issue by mattsputnikdigital** [Hopding/pdf-lib#914]
Is there a way to destroy the PDF object when it is no longer required?

Im thinking a PDF full of images may be sitting in memory a bit before garbage collection gets around to it, which I really don't want in a mobile app.

I guess I could loop through and remove all pages when the PDF is no longer needed and just set its reference to null so that it takes up less memory before gc.

Any thoughts?

**Comment by pablodenadai** [comment]
@mattsputnikdigital did you come up with any solution for this problem?

**Comment by MatthewPringle** [comment]
@pablodenadai im just doing this

```
clearPDF: function( pdf ) {

        var pages = pdf && typeof pdf === 'object' ? pdf.getPageCount() : 0;
        
        if ( pages > 0 ) {
            
            for ( var page = 0; page < pages; page++ ) {
                
                if ( pdf.getPageCount() > 0 ) {
                    
                    pdf.removePage( 0 );
                    
                }
                
            }
            
        }

 }
```

**Comment by pablodenadai** [comment]
Thanks @MatthewPringle.
It'd be good if the library exposed a `.destroy()` method.

**Comment by Hopding** [comment]
Not sure I understand what you're looking for here. A way to work around the JS garbage collector? Feel free to fill out a [proposal](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=proposal%2Cneeds-triage&template=proposal.yml) with more details and we can go from there.
