### ISSUE TITLE
Embedding PDF onto pre-existing PDF help 

### ISSUE THREAD

**Issue by tianyuduan** [Hopding/pdf-lib#915]
The documentation entails-- to create embedded PDF pages you would create a new PDFDocument, and embed two pdf pages on top of the newly created PDF. 
```
const pdfDoc = await PDFDocument.create();

  const [americanFlag] = await pdfDoc.embedPdf(flagPdfBytes);

  const usConstitutionPdf = await PDFDocument.load(constitutionPdfBytes);
  const preamble = await pdfDoc.embedPage(usConstitutionPdf.getPages()[1], {
    left: 55,
    bottom: 485,
    right: 300,
    top: 575,
  });
```

My question is, is it possible to embed on top of a pre-existing PDF
```
// embed doc
  const baseDoc = await PDFDocument.load(fs.readFileSync(projectPath))
  const pages = baseDoc .getPages()
  const firstPage = pages[0]
  const secondPage = pages[1]

  const stampPDF = await PDFDocument.load(fs.readFileSync(stampAddress));
  const embededStamp = await outputPDF.embedPage(stampPDF.getPages()[0]);

  // stamp
  const scaleStamp = embededStamp.scale(1.5);
  firstPage.drawPage(embededStamp, {
      ...scaleStamp,
      rotate: degrees(90),
      x: 590,
      y: firstOutputPage.getHeight() / 2 - scaleStamp.height * 1.625,
    });

```

I tried something like this but to no avail. The function runs, but will not add the stamp.

**Comment by Hopding** [comment]
This should definitely be possible. If you think something isn't working right I'll need more information to help. Consider filling out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=proposal%2Cneeds-triage&template=proposal.yml) form.
