### ISSUE TITLE
create new PDF Document always return version 1.7

### ISSUE THREAD

**Issue by PhakornKiong** [Hopding/pdf-lib#916]
I couldn't find information on what pdf-version does `pdf-lib` support when generating a new document. It always generates pdf version 1.7.
A little digging and I found the values are hard-coded here

https://github.com/Hopding/pdf-lib/blob/d213f921237daca7a5e21fb38eb69d733ff34796/src/core/PDFContext.ts#L63-L69

https://github.com/Hopding/pdf-lib/blob/d213f921237daca7a5e21fb38eb69d733ff34796/src/core/writers/PDFWriter.ts#L121-L124

I think there are 2 issues with this (Please correct me if I'm wrong)
1) The original header created in the `PDFContext` will never be used since the writer will create a new one when `PDFDocument.save()` is called. Maybe it should be changed to `const header = this.context.header;`

2) Is the library supporting other lower version for the new pdf? I can't find any in the documentation. Maybe someone clarifies if version 1.7 is intentional, and what is the reason behind it. Maybe we could add this to the documentation as well.

Let me know what you think.

**Comment by Hopding** [comment]
`pdf-lib` allows users to do things to a PDF that are only supported in newer version of the PDF spec. Dynamically figuring out what the appropriate version should be based on how a user manipulates the document would be tricky. Preventing certain operations based on the version would be equally challenging. As best I can tell, it would at minimum require every possible operation in pdf-lib to be marked with a supported version. 

If anybody has ideas for an efficient way to find and use the lowest possible version, I'd be happy to review a [proposal](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=proposal%2Cneeds-triage&template=proposal.yml). 

I think there are some other issues out there where I've discussed this as well. E.g. https://github.com/Hopding/pdf-lib/issues/541.

Documenting it would be good. Happy to accept a PR for that as well. A good spot might be the `PDFDocument.save` method doc comment.
