### ISSUE TITLE
Get coordinates/position of a form item

### ISSUE THREAD

**Issue by MorganWaya** [Hopding/pdf-lib#918]
I'm trying to get le location/position of form items using this library and I found tons of interesting features excepted this one.

Any idea?

**Comment by dcsline** [comment]
For which application do you need the location / position?
You determine the position of an element yourself when creating the PDF form and you can always use the name to query the content / properties of the element.

**Comment by Hopding** [comment]
Need more information to provide any kind of detailed help with this. But at a high level, you should be able to:
1. Get the widget(s) for a form field
2. Get the position information of each widget

See https://github.com/Hopding/pdf-lib/issues/660#issuecomment-727254413 for an example of accessing & processing widgets.
