### ISSUE TITLE
bug with embedded fonts

### ISSUE THREAD

**Issue by oktapodia** [Hopding/pdf-lib#919]
Hello,

When embedding fonts and opening those with the acrobat reader DC software, we are getting the following error.

![image](https://user-images.githubusercontent.com/2752200/123250480-023a3a80-d4e2-11eb-96b6-69f8717a5f4d.png)

I have created a reproducible example here: https://jsfiddle.net/oktapodia/d7e80bmL/1/

Any ideas of how to solve this?

**Comment by moldfield1995** [comment]
@oktapodia Had the same problem, found that if I used WOFF this would happen, converted it to TTF and it worked fine. 
Don't know if this is a pdf lib issue or a font kit problem.

**Comment by Hopding** [comment]
There are some known issues with WOFF2 fonts: https://github.com/Hopding/pdf-lib/issues/231. I'd suggest the same thing as @moldfield1995: convert it to TTF.
