### ISSUE TITLE
Open PDF in new tab rather than download

### ISSUE THREAD

**Issue by mickeydelo** [Hopding/pdf-lib#921]
Instead of downloading the PDF, is there a way to open the PDF in a new tab/window?

```
// Trigger the browser to download the PDF document
download(pdfBytes, "pdf-lib_modification_example.pdf", "application/pdf");
```

**Comment by dcsline** [comment]
of course. 
One possibility is this:
----------------------------------------------------------------------------------------------------------
in javscript file:
	pdfname =  "/public/data/pdf-lib_modification_example.pdf";         
    
       // download(pdfBytes, fn, 'application/pdf');
    fs.writeFileSync(__dirname + pdfname, await pdfDoc.save());
	socket.emit('resFill', pdfname);

in HTML-Page:	
	 socket.on('resFill',  function (filename) {
     	   window.open('http://localhost:3000/pdf-lib_modification_example.pdf', "_blank")
   });
----------------------------------------------------------------------------------------------------------
this example is part of my socket.oi - express - app.

I hope this is what you have been looking for

**Comment by Hopding** [comment]
Pretty sure this should be possible. Don't have time to provide an example myself atm. Feel free to open a Discussion if you're still interested in this 👍
