### ISSUE TITLE
Implementing multiple signatures

### ISSUE THREAD

**Issue by kevinbror** [Hopding/pdf-lib#922]
Is there a way to support multiple signatures without flattening the form? I have a use case where one party will fill out some fields and sign and a second party will fill the remaining fields and sign. 

I'm using the final sample from this issue https://github.com/Hopding/pdf-lib/issues/112

**Comment by Hopding** [comment]
The tl;dr is `pdf-lib` doesn't provide signature support. You can search some of the other issues to find more detail I've provided elsewhere.
