### ISSUE TITLE
Converting a pdf into mono / greyscale

### ISSUE THREAD

**Issue by Lex-talionis** [Hopding/pdf-lib#925]
I need to convert a pdf into mono / greyscale to reduce the price of printing. I started going down the route of converting the pdf to an image, converting it to black and white and then saving that image to a pdf. I then noticed that in the documentation there is a section on color. With functions like setFillColour setDrawColour... So my question is, when I load the pdf is there a way of converting it to greyscale within this package or will I have to carry on with my original logic. Sorry I don't have an example of my code because I'm on my phone but can supply one if it helps.

**Comment by Hopding** [comment]
Your original solution is definitely the way to go for something like this 👍. Those operators are for different purposes than you're describing.
