### ISSUE TITLE
Add identifying attributes to HTML elements (like ID or something else)

### ISSUE THREAD

**Issue by NicMul** [Hopding/pdf-lib#926]
Question: I am looking to add some sort of identifying attribute to an `html` tag. Like an `ID` or `data`. Then have it be persistent during `pdf` export / save. Once the same pdf file is imported again, the specific tag can be referenced and used.

**Comment by Hopding** [comment]
The only thing that comes to mind is tagged content attributes, but `pdf-lib` doesn't currently support those.
