### ISSUE TITLE
How to draw a page to an HTML Canvas?

### ISSUE THREAD

**Issue by mattiaz9** [Hopding/pdf-lib#928]
Is it possible to draw a single page to an html canvas element?

**Comment by jamols09** [comment]
This is actually the same question I have but with some added few like can I make fields draggable ? or can I make the field dynamically added/removed and it would reflect on the canvas.

**Comment by Hopding** [comment]
See https://github.com/Hopding/pdf-lib/issues/940#issuecomment-925378515, https://github.com/Hopding/pdf-lib/issues/803, and other issues related to page rendering.
