### ISSUE TITLE
opacity option for annotations

### ISSUE THREAD

**Issue by yugimani** [Hopding/pdf-lib#929]
Hi,

I am looking to set transparent background for Text field annotations, however the high-level api sets the default background to white. Removing background dictionary (/BG)  seem to do the trick for my usecase. Before I submit PR, I am not sure if and how to test this with "Transparency Group XObject". Does pdf-lib support rollover and down appearances, if yes, how to set those appearances?

Thanks!

**Comment by Hopding** [comment]
Hello @yugimani! I don't entirely understand what you're looking to accomplish here. It sounds similar to https://github.com/Hopding/pdf-lib/issues/605#issuecomment-693686848 though.

If you have a different idea in mind and would like to propose a change or work on a PR, please fill out the new [proposal](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=proposal%2Cneeds-triage&template=proposal.yml) form and we can go from there 👍.
