### ISSUE TITLE
add text alignment option to PDFPage.drawText()

### ISSUE THREAD

**Issue by TNGPS** [Hopding/pdf-lib#930]
The `drawText` method does a nice job with multiline texts that in a box when maxWith is defined in options. However it always aligns the text LEFT, while in some cases we would like to use CENTER of RIGHT.

It seems line we have some code that can does a good job splitting la text into lines with different text alignment options `layoutMultilineText` defined in  `layouts.ts`. However this is used only for the layout of text fields in forms.

It would be nice to refactor the `drawText()` method as to use the `layoutMultilineText` and accepting an extra option for the text alignment from the type `TextAlignment`

**Comment by Hopding** [comment]
Agreed! Happy to accept a PR if anybody wants to work on this. Looks like @TNGPS has a PR, but it'll need to be reopened to account for the recent git history rewrite.

**Comment by Hopding** [comment]
Closing this for now since #931 went stale.

Note also that better typography & text layout support is on the roadmap: https://github.com/Hopding/pdf-lib/discussions/998.
