### ISSUE TITLE
No page reference for newly created widget

### ISSUE THREAD

**Issue by chislin** [Hopding/pdf-lib#932]
Let's take https://jsfiddle.net/Hopding/bct7vngL/4/ as an example.
If you'll try to list all form fields widgets of result PDF (like `console.log(form.getFields().map((f) => f.acroField.getWidgets().map((w) => w.P())))`) - references will be empty. I'm not completely sure that this is expected behaviour. They can be found by pdf.js though, but I use it only as fallback method.

**Comment by Hopding** [comment]
Hello @chislin! Not quite sure I understand what you're describing here. If you think something is working correctly, please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) and we can go from there.
