### ISSUE TITLE
Form input items such as PDFRadioGroup,PDFTextField,  constructor.name is "r" in production env

### ISSUE THREAD

**Issue by iamzuijiasunyou** [Hopding/pdf-lib#933]

**Comment by iamzuijiasunyou** [comment]
`const form = pdfDoc.getForm();
  const fields = form.getFields();
  fields.forEach(field => {
   // distinguish input item by name
    const name = field.constructor.name; // dev mode is ok, but prod not working
  });`

**Comment by emilsedgh** [comment]
That's because you're using a minifier on Webpack or something like that.
You shouldn't use `field.contructor.name`. Rely in `field instanceof PDFTextField`.

**Comment by Hopding** [comment]
@emilsedgh is spot on. Use `instanceof` to check the type of an object.
