### ISSUE TITLE
Executing two draws does not render the second drawing

### ISSUE THREAD

**Issue by alaksandarjesus** [Hopding/pdf-lib#934]
**app.js**

```
import { WebReader } from './pdf/reader';
const url = '/pdfs/test.pdf';

const webReader = new WebReader(url);


// const drawAnnotations = webReader.drawAnnotations();  // working fine. I see the text

// const drawRectangle = webReader.drawRectangle(); // working fine. I see the rectangle box

const drawAnnotations = webReader.drawAnnotations();
drawAnnotations.then(() => {   // the default text in red color is drawn
    console.log("i am executed after defaultDrawAnnotations");  // console.log output works
    const drawRectangle = webReader.drawRectangle();
    drawRectangle.then(() => {   // the red rectangle is not visible. But i am able to see the flicker as page is rendered
        console.log(" i am executed after drawRectangle") // console.log output works
    });
});
```

The project can be downloaded and tested at https://github.com/alaksandarjesus/PDF-WebViewer-.git

What  i am trying to achieve is to create annotations like https://pspdfkit.com/ and would like to integrate default functionalities as in

https://github.com/highkite/pdfAnnotate

**Comment by Sharcoux** [comment]
Probably because your implementation is wrong. I can confirm that the lib works as expected.

**Comment by Hopding** [comment]
Thanks for providing the git repo. However, I'm not entirely sure what you're trying to achieve here. Links are appreciated, but I need to be able to understand what you're after just by reading the body of your issue. if you'd like to pursue this further, feel free to open up a new Discussion with additional details.
