### ISSUE TITLE
Text written top-to-bottom

### ISSUE THREAD

**Issue by harrisonpaynelaw** [Hopding/pdf-lib#935]
I want to write some text vertically rather than horizontally. The PDF I want to programmatically generate, quite simply, has vertical text. The existing rotate function doesn't cover this case, as the letters would all be facing the wrong direction (downwards instead of to the right). 
Any solution would be appreciated, however an option to rotate the individual letters of a piece of text relative to the direction of writing comes to mind. In such a way, you would rotate the text 90deg one way, and then rotate the letters 90deg the other, and thus achieve vertical text. A simple text direction option would also be nice.

**Comment by Hopding** [comment]
Not sure if I understand exactly what you're trying to do. A visualization would be quite helpful here.

That being said, `pdf-lib` only offers very limited typography and text layout support (see https://github.com/Hopding/pdf-lib/discussions/998). Anything more advanced than basic left-to-right layout will require you to manually position and layout the text. In this case, you'd probably need to measure the height of each character and render them one at a time. 

You could also try setting a very small `maxWidth` value for `PDFPage.drawText`. That should allow you to produce a column of individual characters.

**Comment by harrisonpaynelaw** [comment]
Okay, understood. Thanks for the suggestions!
