### ISSUE TITLE
Feature Request : Convert page 1 to image?

### ISSUE THREAD

**Issue by ricky11** [Hopding/pdf-lib#940]
Would be pretty awesome if we could extend pdf-lib to convert the 0 index of the pdf to a image jpg or webp.

edit  : this could be done with nodes gm module?

**Comment by Lex-talionis** [comment]
i would suggest looking a node-poppler. It has something in there called pdfcario which can do that then you can just embed it into the pdf and draw it on.

**Comment by Hopding** [comment]
Rendering a PDF is a huge undertaking and is well outside the scope of `pdf-lib`. However, you should be able to use https://mozilla.github.io/pdf.js/ to rasterize PDF pages.
