### ISSUE TITLE
Converting a pdf to pdf/x-1a

### ISSUE THREAD

**Issue by Lex-talionis** [Hopding/pdf-lib#943]
Hi, I was wondering if there is a way to convert a pdf into a pdf/x-1a format via this library or if this can be done manually?

Regards

**Comment by eduarevalo** [comment]
I would like to hear about this feature.

**Comment by PhakornKiong** [comment]
Based on my brief exposure to the `PDFWriter` of this library, it is unlikely to support `pdf/x-1a` without significant code changes.

1) Current writer is fixed to v1.7 as raised here  #916
2) The way each of the `elements` in the document is build-up doesn't really allow this extensibility.

**Comment by Hopding** [comment]
I'm not familiar with the PDF/X-1A spec specifically. `pdf-lib` doesn't offer special support for any particular PDF subtype. See also https://github.com/Hopding/pdf-lib/pull/508 and https://github.com/Hopding/pdf-lib/issues/230.
