### ISSUE TITLE
Is it possible to set document ID using pdf-lib?

### ISSUE THREAD

**Issue by RopoMen** [Hopding/pdf-lib#947]
Hi,
Is it possible to set unique document id using pdf-lib? Document ID should show up like this in the PDF file
```
trailer
<<
/Root 1 0 R
/Info 3 0 R
/ID [<B6014D890345884B0EDF8D5AA0C95B37> <B6014D890345884B0EDF8D5AA0C95B37>]
/Size 47
>>
```

Where https://www.oreilly.com/library/view/pdf-explained/9781449321581/ch04.html
>  ID | Array of two Strings | Uniquely identifies the file within a work flow. The first string is decided when the file is first created, the second modified by workflow systems when they modify the file.

> Here’s an example trailer dictionary:

> <<
   /Size 421
   /Root 377 0 R
   /Info 375 0 R
   /ID [<75ff22189ceac848dfa2afec93deee03> <057928614d9711db835e000d937095a2>]
>>

I have tried following by looking how pdf-lib is setting author etc. inside trailer Info section.
```
const ID = PDFName.of('ID')
const existingID = pdfDocument.context.lookup(
  pdfDocument.context.trailerInfo.ID
)
if (existingID instanceof PDFDict) {
  existingID.set(ID, PDFString.of('1234567890'))
} else {
  const newID = pdfDocument.context.obj({})
  pdfDocument.context.trailerInfo.ID = pdfDocument.context.register(newID)
  newID.set(ID, PDFString.of('1234567890'))
}
```

If I use console.log to print "pdfDocument.context.trailerInfo.ID" it has been changed from "undefined" to "PDFRef" (or similar) but when document is saved into file, I cannot see ID to show up properly, like ```/ID [<1234567890>]```

Br,
Markku

**Comment by Hopding** [comment]
This should be possible to do. I don't have time to provide an example right now though. I'd suggest checking out the following classes:
* https://github.com/Hopding/pdf-lib/blob/master/src/core/writers/PDFWriter.ts
* https://github.com/Hopding/pdf-lib/blob/master/src/core/writers/PDFStreamWriter.ts

That's where the serialization is implemented. Serializing a trailer is slightly different from the main body of the document, so you'll want to review that code in particular to make sure the ID isn't somehow omitted.

Also, you'll want to save the document with `pdfDoc.save({ useObjectStreams: false })` when you're testing. It's much easier to debug things that way 🙂.
