### ISSUE TITLE
link document - summary odf-lib

### ISSUE THREAD

**Issue by 7feeh7** [Hopding/pdf-lib#948]
hello, I'm implementing a summary, I would like to know how to link the pages so that as soon as I click on the item in the summary the pdf opens the clicked document.
attached the implemented item.
![example](https://user-images.githubusercontent.com/20801260/127216500-52303ae4-cc6e-4775-8c71-98597415c91c.JPG)
t

**Comment by Hopding** [comment]
Sounds like you're looking for internal links? If so, check out https://github.com/Hopding/pdf-lib/issues/206#issuecomment-568806160.
