### ISSUE TITLE
can I edit text in pdf with PDF-lib?

### ISSUE THREAD

**Issue by lindamacdonald** [Hopding/pdf-lib#950]
Hey there guys :) this looks really good, but am a bit unsure if I can use it for what I need...can I edit text in a pdf with this?

thanks in advance

**Comment by bcholmes** [comment]
There's a comment on in the README.md under "Limitations" that says that while it's in the scope of what pdf-lib is trying to accomplish, it's not currently supported. The note references these issues: #93, #137, #177, #329, and #380.

**Comment by Hopding** [comment]
@bcholmes is spot on!
