### ISSUE TITLE
Inconsistent line height when rendering multiline text inside form with custom font

### ISSUE THREAD

**Issue by chislin** [Hopding/pdf-lib#953]
Line height seems to be out of place, it doesn't really matter which custom font to use - happens to all of them. Maybe something is wrong here with rendering `textLines`, I'm not really sure.

Also, this was the only was to embed default form font:
```
const font = await pdfDoc.embedFont(CUSTOM_FONT);
const form = pdfDoc.getForm();
form.defaultFontCache = Cache.populatedBy(() => font);
```
Otherwise it was rewritten by Helvetica.

Here's an example of options list:
|Standard Font - Helvetica | Custom Font - San Francisco | Custom Font - Open Sans|
|---|---|---|
|![Helvetica](https://user-images.githubusercontent.com/17890260/128041820-4219d525-bfba-4fc0-bad3-66471f8061d5.png)|![San Francisco](https://user-images.githubusercontent.com/17890260/128042351-e2692a4e-4159-4a7d-9ed6-cab70f468b08.png)|![Open Sans](https://user-images.githubusercontent.com/17890260/128042402-8740afae-bed3-4164-93f2-79f8e0250570.png)|

I could've used Helvetica of course, but it doesn't support cyrillic characters unfortunately.

**Comment by Hopding** [comment]
Hello @chislin! I'll need more information to investigate this further. Please consider filling out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form and we can go from there.
