### ISSUE TITLE
Is there a method to sign the PDF files?

### ISSUE THREAD

**Issue by byteshiva** [Hopding/pdf-lib#956]
Is there a method to sign the PDF files?

**Comment by Kickassbadboy** [comment]
Extract X- Y Coordinates from a different package, get signature as png and use `pdf.drawImage()`  from this package

**Comment by pentolbakso** [comment]
this is more like it

https://github.com/Hopding/pdf-lib/issues/418#issuecomment-697052730

**Comment by Hopding** [comment]
`pdf-lib` doesn't offer high-level APIs for digital signature. There are a few issues you can find related to signing where I've provided some examples of different ways to do it. But it's tricky atm and not well supported.

**Comment by KIngCrzy** [comment]
> Extract X- Y Coordinates from a different package, get signature as png and use `pdf.drawImage()` from this package

How to make the background color of the picture transparent? The white color will block the content of the original Pdf. Thanks for help
