### ISSUE TITLE
How to copy a page with its fieldName

### ISSUE THREAD

**Issue by jaytang0508** [Hopding/pdf-lib#958]
Hello, I am dealing with a pdf with "continuation sheet", which means that if I have to fill in more than one set of information, I need to add pages to the pdf document. The way I plan to do that is to use pdfDoc.copyPages() to copy the specific page and then I fill in the extra information in that copied page. However, when I do field.getName() for the copied page, I am not able to get the name of the fields and therefore, I am not able to fill in the information in the copied page... Wonder if there is any solution for this? And wonder how we can add/change the name of a given pdf page?

**Comment by Hopding** [comment]
See this thread: https://github.com/Hopding/pdf-lib/issues/417.
