### ISSUE TITLE
How can I get string or image from "PDFDocument.context.indirectObjects"

### ISSUE THREAD

**Issue by wangxi83** [Hopding/pdf-lib#962]
I've load a pdf using 

```javascript
const existingPdfBytes = fs.readFileSync("C:/test/1.pdf");
const pdfDoc = await pdfLib.PDFDocument.load(existingPdfBytes);
```

and I can find many things in PDFDocument.context.indirectObjects

I've tried ways to get the content from indrectObjects. ex:

```javascript
pdfDoc.context.indirectObjects.forEach((v,k)=>{
        const {decodePDFRawStream, PDFRawStream} =require('pdf-lib');
        if(v instanceof PDFRawStream){
            // console.log(dengXian.encodeText(v.contents.toString()));
            let stream = decodePDFRawStream(v);
            console.log(Utf8ArrayToStr(stream.getBytes()));
            // console.log(iconv.decode(Buffer.from(bytes), "cp936"));
        }
    });
```

but none of ways is the right way...

can anyone help me? Thanks!!

**Comment by nealdyrkacz** [comment]
@wangxi83 

Take a look at [this](https://github.com/Hopding/pdf-lib/issues/83)

I have been able to find the images and their sizes.... I am still trying to figure out if its possible to find what page the image is on and what the image coordinates are.....  ( my [issue](https://github.com/Hopding/pdf-lib/issues/963)

Find images:

const enumeratedIndirectObjects = pdfDoc.context.enumerateIndirectObjects();
enumeratedIndirectObjects.forEach(x => {
const pdfRef = x[0];
const pdfObject = x[1];

  if (!(pdfObject instanceof PDFRawStream)) return;

  const { dict } = pdfObject;

  const subtype = dict.get(PDFName.of('Subtype'));
  const width = dict.get(PDFName.of('Width'));
  const height = dict.get(PDFName.of('Height'));
  const name = dict.get(PDFName.of('Name'));

  if (subtype == PDFName.of('Image')) {
   //FOUND IMAGE, NOW WHAT PAGE DOES IT EXIST ON
   //push image coordinates into an array for page
  }
});

**Comment by Hopding** [comment]
`pdf-lib` doesn't currently provide good support for processing content streams. It can be done, but you'll have to read the PDF spec to understand the inner structure of PDF files. See also https://github.com/Hopding/pdf-lib/issues/963#issuecomment-925363121.
