### ISSUE TITLE
Issue with Flattening Forms after typing something into a fillable field in the Browser, confirm that you want to leave page

### ISSUE THREAD

**Issue by sscotti** [Hopding/pdf-lib#965]
I'm been trying to figure out how to do what I want for awhile now.  I can embed a form in an iFrame in the Browser and pre-populate some fillable fields with data from the back-end.  That works fine.

I am attaching a screenshot:

![image](https://user-images.githubusercontent.com/236933/129838016-99ae8a4d-e671-495c-b316-c779d1d6731a.png)

I also have that "Flatten" button at the top, which apparently does work, but only if I don't edit any of the fields on the form.

![image](https://user-images.githubusercontent.com/236933/129838086-317a396e-c8a1-4b69-9aaf-32d395e44dd8.png)

If I type something in and then try to flatten I get an error message because the document has changed apparently, and I probably would need to do something with JS to actually set the form field value on the backend, or otherwise update the form.  The error that I get is:

![image](https://user-images.githubusercontent.com/236933/129838201-187d1a54-1d6f-4d64-ad19-e9ff47181f8a.png)

My flatten button does this:

```
$("#flatten").on("click", function(e) {

async function Flatten() {

 pdfDoc = await PDFLib.PDFDocument.load(document.getElementById('pdf').src)
 form = pdfDoc.getForm()
 form.updateFieldAppearances();
 form.flatten()
 pdfBytes = await pdfDoc.saveAsBase64({ dataUri: true })
 document.getElementById('pdf').src = pdfBytes
}

Flatten();
});
```
I'd be happy to sure the other code, but that at least explains the issue.

**Comment by sscotti** [comment]
My ultimate goal is to then submit the flattened version to the backend so that I can store it on the file system or in the DB as a blob or binary.

**Comment by sscotti** [comment]
Adding a bit more code for this since now I have it almost working.  I am attaching 2 files in a .zip file.  if you put those on a web server and then just open the test.html file in a browser you should be able to see what the issue is:

The Flatten, Save and Send work if I do not change / edit any of the form fields.  However, if I edit a form field, then I get an error asking if I want to Stay on Page or Leave page.

Hope that Helps.

[Archive.zip](https://github.com/Hopding/pdf-lib/files/7027965/Archive.zip)

**Comment by Hopding** [comment]
Hello @sscotti!

The essence of your question is the same as these others:
* https://github.com/Hopding/pdf-lib/issues/129
* https://github.com/Hopding/pdf-lib/issues/130
* https://github.com/Hopding/pdf-lib/issues/346
* https://github.com/Hopding/pdf-lib/issues/532
* https://github.com/Hopding/pdf-lib/issues/694
* https://github.com/Hopding/pdf-lib/issues/690

The tl;dr is that PDFs rendered in iframes are sandboxed from the rest of your app and external code (including `pdf-lib`) can't interact with them or gain access to changes the user made within the iframe.

**Comment by sscotti** [comment]
Hey.  Thank you much. Sorry I did not see the other issues.  I guess one work-around then would be to somehow have the front-end submit any changes to the back-end, and then reload the form with any changes ?

Is there any other way to handle that without using an iFrame ?

**Comment by Hopding** [comment]
I'm not aware of a way to get a user's changes out of an iframe in the first place. PDF editing in-browser is a much sought after capability that doesn't really exist atm. The closest thing you'll find is https://mozilla.github.io/pdf.js. Some folks use a combination of that with pdf-lib to implement their apps.
