### ISSUE TITLE
Wrong orientation drawing images

### ISSUE THREAD

**Issue by pucci08** [Hopding/pdf-lib#968]
Hi!
I work in a web application that receives images from a mobile application (images taken with the cell phone camera) and then I convert them into pdf and leave a watermark on them.

The problem is that certain cell phones capture the image in a certain way that when embedding it in the pdf, it places them in the wrong orientation (they should be vertical and NOT horizontal)

In the image properties, the orientation of those that are saved wrong is as "Right-top" and the orientation of those that are saved well is as "Top-left"

Why could it be?

**Comment by andrei-gubarev** [comment]
+1. I have the same issue while drawing rectangles on the PDF that includes images only.

**Comment by Hopding** [comment]
This probably has something to do with the image's EXIF orientation data. I'll need more information to investigate this further. Please fill out the [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form and we can continue from there.

**Comment by minhan997** [comment]
> Hi! I work in a web application that receives images from a mobile application (images taken with the cell phone camera) and then I convert them into pdf and leave a watermark on them.
> 
> The problem is that certain cell phones capture the image in a certain way that when embedding it in the pdf, it places them in the wrong orientation (they should be vertical and NOT horizontal)
> 
> In the image properties, the orientation of those that are saved wrong is as "Right-top" and the orientation of those that are saved well is as "Top-left"
> 
> Why could it be?

did you fix this error, how to fix it? plz
