### ISSUE TITLE
Can I get a list of embedded fonts in a PDF

### ISSUE THREAD

**Issue by elaich** [Hopding/pdf-lib#971]
This is a simple question as the title is mentioning. I'd like to load a pdf and get the embedded fonts. By the look at the API of `PDFDocument` this is not the case I'd say it's not possible for the time being?

**Comment by Hopding** [comment]
`pdf-lib` has low-level APIs that can be used to traverse and access most parts of a PDF document. If you just want to get a list of the fonts, that is possible to do. If you want to extract and reuse those fonts in other `pdf-lib` methods (e.g. `drawText`), that _might_ be possible. I haven't tried to do it myself.

I don't have time to provide an example for this atm. Also, the low-level APIs are not documented right now. You'll have to crawl around the source and read examples I've provided in other issues to learn how it works.

I'd like to better support this in the future. I added it to the roadmap in https://github.com/Hopding/pdf-lib/discussions/998 for tracking.

**Comment by toverux** [comment]
Need this too :)
My document is mostly generated by Puppeteer but is modified with PDF-Lib. I'd like to retrieve the font embedded by Chromium and reuse it to draw more text on the document using PDF-Lib.

**Comment by ryangriggs** [comment]
I am interested in this feature to allow modifications to an existing PDF using the font(s) it was created with. Also, to avoid wasting resources by embedding a new font to write on an existing PDF.  If this becomes possible it would be handy.
