### ISSUE TITLE
Return number of lines when using drawText maxWidth

### ISSUE THREAD

**Issue by dsernst** [Hopding/pdf-lib#972]
When using `drawText()`'s `maxWidth` option to automatically wrap text, it would be very handy to return to the number of lines used.

Then we can move other text down to accommodate multi-line text, etc.

Without this, it seems like we still need to recalculate the number of lines manually again?

**Comment by Hopding** [comment]
I would like to improve the layout/typography support of pdf-lib. What you've noted here is really one small part of a larger improvement.

For now what you'll have to do is use the `breakTextIntoLines` function, essentially replicating the logic that `drawText` used internally: https://github.com/Hopding/pdf-lib/blob/9168383d88e60b77922d2d031f4f9138eeff7240/src/api/PDFPage.ts#L902-L933

I've added this to the roadmap for tracking: https://github.com/Hopding/pdf-lib/discussions/998.

And ofc I'm happy to review PRs and/or offer [proposal](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=proposal%2Cneeds-triage&template=proposal.yml) feedback if anybody is interested in working on this 😄.
