### ISSUE TITLE
Table creation

### ISSUE THREAD

**Issue by Jordan-E** [Hopding/pdf-lib#973]
Hi I was wondering if there was any functionality for table creation. Something along the lines of voilab-pdf-table which is avalible for pdfkit. 
I am wanting to use this library for my project as I've tried the two frameworks and I really like how simple yours is to use.

Also is there any possibility that the documentation could include some more information I am newish to JavaScript and reading source code isn't the easiest. 

I know your must be a busy person. Thanks you for this great library. Any response would be appropriated.

**Comment by Hopding** [comment]
Hello @Jordan-E! I'm glad you've found pdf-lib useful 🙂.

There is no built-in API for table generation. See https://github.com/Hopding/pdf-lib/issues/382 and https://github.com/Hopding/pdf-lib/issues/591. I'm not sure if there are any third party APIs for this or not.

I'd like to have additional documentation. Not sure when I'll get around to creating it though. I added it to the roadmap for tracking: https://github.com/Hopding/pdf-lib/issues/973.
