### ISSUE TITLE
Flatten does not format multiline field correctly

### ISSUE THREAD

**Issue by alexbrickwedde** [Hopding/pdf-lib#974]
Hi,

i have a template with a textfield, which is being filled.
[template.pdf](https://github.com/Hopding/pdf-lib/files/7066474/template.pdf)

After being filled, this is the result:
[without flatten.pdf](https://github.com/Hopding/pdf-lib/files/7066475/without.flatten.pdf)

After calling flatten, it looks like this:
[with flatten.pdf](https://github.com/Hopding/pdf-lib/files/7066476/with.flatten.pdf)

I took a quick look into flatten, but i don't have enough experience with the internals of PDF.

**Comment by chislin** [comment]
I think it's the same as #953

**Comment by alexbrickwedde** [comment]
I just tried with some more lines of text. It's just half a line added to the top position.

**Comment by Hopding** [comment]
Looks like the text field's line height is too large. `pdf-lib` should use whatever formatting is configured for a field when flattening it. You can decrease the line height in acrobat. I suspect that will fix this issue for you:

## Large Line Height
<img width="1474" alt="Screen Shot 2021-09-24 at 6 32 45 PM" src="https://user-images.githubusercontent.com/10351828/134749494-95caab57-94f0-46fa-ad0c-225d878656e6.png">

## Small Line Height
<img width="1474" alt="Screen Shot 2021-09-24 at 6 32 53 PM" src="https://user-images.githubusercontent.com/10351828/134749496-065fa03a-5cca-41eb-a9ec-0550c4e05fd9.png">

In theory `pdf-lib` could override the configured formatting if it detects that doing so would allow the text to fit within the field's bounds. But I'm not sure how widely used such a capability would be. If anybody is interested in working on this, I'm happy to accept PRs!
