### ISSUE TITLE
Bookmarks Support

### ISSUE THREAD

**Issue by drowhunter** [Hopding/pdf-lib#975]
So, I am using `PDFDocument.load()` to load two PDF's , the idea is i want to merge 2 pdfs together.

I then use `PDFDocument.copyPages` to copy the pages from one document into the other by using `insertPage(pdf1, 0)

This works almost perfectly, the bookmarks on the side of pdf1 are retained.  However the newly inserted pages don't show up.

Is there a way to modify the bookmarks/TOC like PDFDocument.Bookmarks.addBookmark ?

or access the bookmark tree as a nested json object?

The bookmarks in my files are nested like

Topic 1 
 * Page 1
 * Page 2
Topiic 2
* Page 3
* Page 4

Also is it possible to get the title of each page as I iterate the page objects from copy pages?

**Comment by Hopding** [comment]
See https://github.com/Hopding/pdf-lib/issues/218 and https://github.com/Hopding/pdf-lib/discussions/998.
