### ISSUE TITLE
Is there a way to make textfield transparent

### ISSUE THREAD

**Issue by iresh96** [Hopding/pdf-lib#977]
I want to make the textfield transparent when I add it to the document. If I add a text field to document where there are fonts , text field box will cover those. I'm trying to use the text field as a placeholder and get inputs from user to fill it.

**Comment by Spike-Leung** [comment]
> I want to make the textfield transparent when I add it to the document. If I add a text field to document where there are fonts , text field box will cover those. I'm trying to use the text field as a placeholder and get inputs from user to fill it.

Hello, have you solved this problem? If so, can you share your solution? Thanks a lot : P

**Comment by Patzi275** [comment]
hey @iresh96, did you find a solution for that ?

**Comment by Spike-Leung** [comment]
> hey @iresh96, did you find a solution for that ?

see: https://github.com/Hopding/pdf-lib/issues/605, have a try~
