### ISSUE TITLE
Trouble Copying From User Uploaded PDF

### ISSUE THREAD

**Issue by mphox-phoxdev** [Hopding/pdf-lib#979]
Hello,

I'm trying to upload only the first page of a user selected PDF and I'm having some trouble working with the input. To test things out, I'm just trying to download a pdf with the first page but when I run the below code, I end up with a single page, blank PDF.

The user selects the file from an `input tupe="form"` dialog and it's passed to the following react function

```js
async function onFileChange(e) {
    const inputFile = e.target.files[0];
    const buffer = await inputFile.arrayBuffer();
    const inputPDF = await PDFDocument.load(buffer, { ignoreEncryption: true });
    const truncatedDoc = await PDFDocument.create();

    const [firstPage] = await truncatedDoc.copyPages(inputPDF, [0]);

    truncatedDoc.addPage(firstPage);
    const docBytes = await truncatedDoc.save();
    download(docBytes, "truncated.pdf", "application/pdf");
}
```

Any advice or suggestions about where I'm going wrong would be greatly appreciated

**Comment by Hopding** [comment]
Hello @mphox-phoxdev! I need more information in order to provide any assistance here. Please fill out the new [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) form if you'd like to pursue this further.
