### ISSUE TITLE
Is there support for url-links on text

### ISSUE THREAD

**Issue by joseDaKing** [Hopding/pdf-lib#980]
Hi is there support for url-links on text

**Comment by Hopding** [comment]
See:
* https://github.com/Hopding/pdf-lib/issues/957
* https://github.com/Hopding/pdf-lib/issues/867
* https://github.com/Hopding/pdf-lib/issues/555#issuecomment-670241308

**Comment by Leone25** [comment]
In case anyone needs it in the future,

This is how you remove all links from a pdf:
```js
pdf.getPages().forEach((p) => {
    p.node.Annots()?.asArray().forEach((a) => {
        pdf.context.delete(a)
    })
})
```
