### ISSUE TITLE
Highlight or Change Background color of PDF fields, Text-Fields, Checkboxes and Radio Buttons

### ISSUE THREAD

**Issue by vbgsmanzoor** [Hopding/pdf-lib#981]
It's more like a question, not an issue but I want to Highlight or Change the Background color of PDF fields, Text-Fields, Checkboxes, and Radio Buttons after comparing values of two different PDFs. Please guide me!!!

**Comment by Hopding** [comment]
See https://github.com/Hopding/pdf-lib/issues/660 for an example.
