### ISSUE TITLE
Update the DrawTextOptions in the Docs

### ISSUE THREAD

**Issue by Psycc** [Hopding/pdf-lib#984]
Heii,

I'm currently using your Libary and wanted to add a Watermark.
First, I think this wouldn't work because there is no opacity parameter, but then I saw the Release Notes for v1.8.0.

Can you add this to the Documentation?

**Comment by Hopding** [comment]
Hello @Psycc! 

Looks like this is already in the documentation:

<kbd>
<img src="https://user-images.githubusercontent.com/10351828/134264976-0ec72387-fabd-46ae-ad25-e2f95e987be9.png">
</kbd>

>

See https://pdf-lib.js.org/docs/api/classes/pdfpage#drawtext and https://pdf-lib.js.org/docs/api/interfaces/pdfpagedrawtextoptions#optional-opacity for one example. 

If you have specific suggestions for how to improve the docs, I'd be happy to accept a PR!
