### ISSUE TITLE
PR #917 Use encryption in UMD build

### ISSUE THREAD

**Issue by Psycc** [Hopding/pdf-lib#989]
#917  @PhakornKiong
These errors occurred when executing `npm run  #build`

```
$ rollup --config rollup.config.js --file dist/pdf-lib.min.js --environment MINIFY,MODULE_TYPE:umd

es/index.js → dist/pdf-lib.min.js...
(!) Missing shims for Node.js built-ins
Creating a browser bundle that depends on 'path'. You might need to include https://github.com/ionic-team/rollup-plugin-node-polyfills

(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
crypto (imported by node_modules/crypto-js/core.js, crypto?commonjs-external)
fs (imported by node_modules/saslprep/lib/memory-code-points.js, fs?commonjs-external)
path (imported by node_modules/saslprep/lib/memory-code-points.js, path?commonjs-external)

(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
crypto (guessing 'crypto')
fs (guessing 'fs')
path (guessing 'path')

created dist/pdf-lib.min.js in 17.6s
```

**Comment by Psycc** [comment]
Where should I exclude `scratchpad/` ?

**Comment by PhakornKiong** [comment]
@Psycc apologies for the misconception on the `scratchpad`, I thought that you were doing a build manually.

I believe the issue raised due to the additional package `saslprep` and `crypto-js`.

I think we might have to port `saslprep` manually since it was using node specific module, while `crypto-js` should require additional settings for in the build.

**Comment by Hopding** [comment]
Hello 👋! If this discussion needs to continue, please relocate it to a Discussion, the PR (https://github.com/Hopding/pdf-lib/pull/917), or an issue on https://github.com/PhakornKiong/pdf-lib/tree/develop/DocEncrypt.
