### ISSUE TITLE
Failed to save PDF larger than 2G

### ISSUE THREAD

**Issue by 921451861** [Hopding/pdf-lib#990]
![1631155495(1)](https://user-images.githubusercontent.com/26274556/132614002-f4f438f7-3c42-4f67-bc23-4318d11485c8.jpg)

**Comment by Hopding** [comment]
This happens because `pdf-lib` reads the entire file into memory and also serializes the entire document in memory. I've added an enhancement to the roadmap to address this problem: https://github.com/Hopding/pdf-lib/discussions/998.
