### ISSUE TITLE
Disable "save changes to document?"

### ISSUE THREAD

**Issue by imhaeussler** [Hopding/pdf-lib#992]
I have a document with a form that before closing asks whether I would like to save the changes done to it

I am filling its fields and making them readonly using pdf-lib, but when closing the modified document it still asks the same question

Is it possible to disable it for the entire document using pdf-lib?

**Comment by Hopding** [comment]
Perhaps, but I'll need more information to be of anymore assistance. Please consider opening a new issue with the [bug report](https://github.com/Hopding/pdf-lib/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug.yml) template.
